### PR TITLE
Fix: Care crash page redirection

### LINKED ISSUE #10024: Redirection not working in Care Crash page
**Description**

The care crash page is just reloading but not redirecting.

Before:

https://github.com/user-attachments/assets/4222534d-0709-4026-b53b-793a36c37e5c

**Expected Behavior**

The Page should reload and redirect to the base url

After

https://github.com/user-attachments/assets/efd82bb3-6cf1-413e-bd13-bc96fb1c777e

### PR DESCRIPTION
**Pull request by Rishith25**
## Proposed Changes

- Fixes #10024 
- In the Care crash page redirection fixed

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved error page navigation by adding a more intelligent back button that preserves application history before reloading the page.

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

File: src/components/ErrorPages/DefaultErrorPage.tsx [hunk 1]
```diff
@@ -56,10 +59,11 @@ export default function ErrorPage({
           <br />
           <br />
           <Button
-            onClick={() =>
+            onClick={() => {
               // Refresh the Page
-              window.location.reload()
-            }
+              goBack();
```
Comment (Jacobjeevan) [inline src/components/ErrorPages/DefaultErrorPage.tsx]: Let's pass a fallback url ("/") in case user encounters error on opening link in a new tab (in which case, there would be no history).

**Review by rithviknishad — APPROVED** [review]
Other than @Jacobjeevan's comment, LGTM

**Review by rithviknishad — APPROVED** [review]

**Comment by Rishith25** [comment]
@rithviknishad Can you assign story points for this
