### PR TITLE
Use ShadCN Select for Language Selector in User Profile Page

### LINKED ISSUE #12736: Use Shadcn `select` for language selector in user profile
**Describe**
Update the language selector in the user profile page to use ShadCN Select instead of the native select, to maintain consistency with CARE’s codebase and design system

**To Reproduce**

1. Go to 'Profile'
2. Scroll down to lang selector

**Screenshots**

https://github.com/user-attachments/assets/0f6e49f7-1a24-4c38-b571-202b3716b3f6

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Krupa-1010**
## Proposed Changes

- Fixes #12736 
- Replaced native <select> element with ShadCN <Select> component for consistent UI
- Moved the placeholder string to en.json
- Applied appropriate styling to match design system

**After**

https://github.com/user-attachments/assets/97f8319b-c404-4771-b49a-3bcf5e008154

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **New Features**
  * The language selector now uses a custom dropdown component with improved styling and localization support.

* **Refactor**
  * Updated the language selector interface for a more consistent and user-friendly experience.

* **Documentation**
  * Added a new localization string for the language selector.

### CODE REVIEW

File: src/components/Common/LanguageSelector.tsx [hunk 1]
```diff
@@ -27,23 +33,19 @@ export const LanguageSelector = (props: any) => {
...
-        value={i18n.language}
-        onChange={(e: any) => handleLanguage(e.target.value)}
-      >
-        {availableLocales.map((e) => (
-          <option key={e} value={e}>
-            {LANGUAGES[e]}
-          </option>
-        ))}
-      </select>
+    <div className="relative flex items-center w-full">
```
Comment (AdityaJ2305) [inline src/components/Common/LanguageSelector.tsx]: Looks like div wrapper is no longer needed, so we can remove it

File: src/components/Common/LanguageSelector.tsx [hunk 2]
```diff
@@ -27,23 +33,19 @@ export const LanguageSelector = (props: any) => {
...
+      <Select value={i18n.language} onValueChange={handleLanguage}>
+        <SelectTrigger className="focus:border-primary-500 focus:outline-none focus:ring-primary-500">
```
Comment (AdityaJ2305) [inline src/components/Common/LanguageSelector.tsx]: we don't have any focus state for any of select in codebase so we should remove className from here just to be consistent with design 
```suggestion
        <SelectTrigger>
```

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

**Review by AdityaJ2305 — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]

**Review by abhimanyurajeesh — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
