### PR TITLE
Fix : Asset cards in Asset list page is not a link. Unable to open in new tab

### LINKED ISSUE #5471: Asset cards in Asset list page is not a link. Unable to open in new tab.
**Describe the bug**
Asset cards in the asset list page can't be opened in a new tab as the component is not a link. However, cards in other list pages (such as patient list page) can be opened in a new tab as those are links.

**To Reproduce**

1. Go to Assets list page
2. Attempt to open asset in a new tab

**Expected behavior**

Should be able to open assets in a new page like in other list pages.
image

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: Ubuntu 23.04
- Browser: Chrome

### PR DESCRIPTION
**Pull request by souravghosh01**
### <samp>🤖 Generated by Copilot at 4f9a0ef</samp>

Refactored `AssetsList` component to use `raviger` links for navigation. This enhances the accessibility and usability of the asset management feature.

## Proposed Changes

- Fixes #5471 

Recording 2023-05-18 at 21 45 46

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [X] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 4f9a0ef</samp>

*  Import `Link` component from `raviger` to enable navigation to asset details page using hyperlinks ([link](https://github.com/coronasafe/care_fe/pull/5484/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49L13-R13))
*  Wrap each asset card with a `Link` component and remove `onClick` handler ([link](https://github.com/coronasafe/care_fe/pull/5484/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49L243-R291))

### CODE REVIEW

File: src/Components/Assets/AssetsList.tsx [hunk 1]
```diff
@@ -240,50 +240,55 @@ const AssetsList = () => {
...
-                    } text-2xl`}
-                  />
+            <div
+              key={asset.id}
+              className="w-full bg-white rounded-lg cursor-pointer border-1 shadow p-5 justify-center items-center border border-transparent hover:border-primary-500"
+              onClick={() =>
+                navigate(
+                  `facility/${asset?.location_object.facility.id}/assets/${asset.id}`
+                )
+              }
```
Comment (rithviknishad) [inline src/Components/Assets/AssetsList.tsx]: @souravghosh01 do we need the onClick to navigate too when the `Link` is already serving the purpose?
```suggestion
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Assets/AssetsList.tsx (hunk 1 above)
Comment (souravghosh01) [reply src/Components/Assets/AssetsList.tsx]: @rithviknishad Thank you for noticing. We don't need the `onClick` It can be removed.

File: src/Components/Assets/AssetsList.tsx [hunk 2]
```diff
@@ -240,50 +240,50 @@ const AssetsList = () => {
...
-            key={asset.id}
-            className="w-full bg-white rounded-lg cursor-pointer border-1 shadow p-5 justify-center items-center border border-transparent hover:border-primary-500"
-            onClick={() =>
-              navigate(
-                `facility/${asset?.location_object.facility.id}/assets/${asset.id}`
-              )
-            }
+          <Link
+            href={`/facility/${asset?.location_object.facility.id}/assets/${asset.id}`}
+            style={{ textDecoration: "none", color: "inherit" }}
```
Comment (rithviknishad) [inline src/Components/Assets/AssetsList.tsx]:
```suggestion
            className="text-inherit"
```

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
