### PR TITLE
Death report is missing patient age

### LINKED ISSUE #8160: Death report is missing patient age
**Describe the bug**

When the patient's age is less than a year, we are showing it as month and days in the platform now, that same is not being copied to the death report form

**To Reproduce**

1. Create a new patient with age less than 1 years of age
2. Discharge the patient as expired
3. Go to the patient details page and click of death report

**Expected behavior**

The age column in the death report should be filled with month and date, if the patient is less than 1 years old

**Screenshots**

image
image

### PR DESCRIPTION
**Pull request by HitishRaoP**
## Proposed Changes

- Fixes #8160 
- Added a check to show the age in month and day format if it is 0 and otherwise the normal age in number

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

File: src/Components/DeathReport/DeathReport.tsx [hunk 1]
```diff
@@ -111,7 +112,10 @@ export default function PrintDeathReport(props: { id: string }) {
         const patientComorbidities = getPatientComorbidities(res.data);
         const data = {
           ...res.data,
-          age: patientAgeInYears(res.data!),
+          age:
+            patientAgeInYears(res.data!) == 0
+              ? formatPatientAge(res.data!, true)
+              : patientAgeInYears(res.data!),
```
Comment (rithviknishad) [inline src/Components/DeathReport/DeathReport.tsx]: the `formatPatientAge` function takes care of all edge cases right? why use `patientAgeInYears`? Isn't it redundant?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/DeathReport/DeathReport.tsx (hunk 1 above)
Comment (HitishRaoP) [reply src/Components/DeathReport/DeathReport.tsx]: @rithviknishad Yes. But If the age is greater than 1, it will add "yr" if we use `formatPatientAge(res.data! ,true)` . If this behavior is fine with you, I'll go ahead and update the commit. Previously, this detail wasn't shown. Let me know if you'd like to proceed with this.

Screenshot 2024-10-05 155303

**Comment by nihal467** [comment]
LGTM

File: src/Components/DeathReport/DeathReport.tsx [hunk 2]
```diff
@@ -1,15 +1,14 @@
 /* eslint-disable @typescript-eslint/no-unused-vars */
```
Comment (khavinshankar) [inline src/Components/DeathReport/DeathReport.tsx]:
```suggestion
```

**Review by khavinshankar — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
