### PR TITLE
Fixed: No notification shown when invalid OTP is entered

### LINKED ISSUE #9656: No notification shown when invalid OTP is entered
**Describe the bug**
No notification is shown to the user when an invalid OTP is entered

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Login with Patient Login
2. Enter a random OTP

**Expected behavior**
Should notify the user that the entered otp is invalid

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by abhimanyurajeesh**
## Proposed Changes

- Fixes #9656 
- Change 1: Introduced a default error message **"invalid_otp": "Invalid OTP, Please check the OPT and try Again"** to en.json
- Change 2: Added conditional checks to determine if the error object follows the expected structure (error.cause.errors).

**Summary**
- These changes aim to make the error handling more reliable and user-friendly by ensuring that any issues during the OTP process are communicated clearly to the user, reducing confusion and improving the overall user experience during authentication.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Screenshot 
image

## Summary by CodeRabbit

- **New Features**
	- Added localized error message for invalid OTP verification.

- **Bug Fixes**
	- Improved OTP error handling in login process.
	- Enhanced user feedback for authentication errors.

### CODE REVIEW

**Comment by abhimanyurajeesh** [comment]
@rithviknishad please let me know if it works or I made any mistakes. Thank You!

File: src/components/Auth/Login.tsx [hunk 1]
```diff
@@ -167,19 +167,24 @@ const Login = (props: { forgot?: boolean }) => {
...
-      if (Array.isArray(errors) && errors.length > 0) {
-        // BE returns a different format for invalid OTP
-        // TODO: fix this
-        //const firstError = errors[0] as OtpError;
-        //setOtpError(firstError.msg);
-        const firstError = errors[0];
-        setOtpValidationError(firstError.otp);
-      } else {
-        setOtpValidationError(t("invalid_otp"));
+      Notification.Error({ msg: t("invalid_otp") });
```
Comment (rithviknishad) [inline src/components/Auth/Login.tsx]: the otp error notification is likely not being dispatched due to it's useQuery being passed with silent=true.

This is ideally auto handled by our global error handler defined here:

https://github.com/ohcnetwork/care_fe/blob/develop/src/Utils/request/errorHandler.ts

As for the set otp error for the field error, LGTM.

**Review by rithviknishad — COMMENTED** [review]
cc: @Jacobjeevan

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
