### PR TITLE
Enhance LocationSearch: Use "instance" for search & Adjust Input Padding

### LINKED ISSUE #10550: Bugs in Questionnaire Form
**Describe the bug**

In location association questionnaire, dropdown gets cut off at the top. Also, it should search based on instance rather than kind.

**To Reproduce**

1. Select a facility
2. Go to encounters and select any
3. Click on update encounter under questionnare
4. In the form , select add questionnare and add Location Association
5. Click on Select Location to see the bug.

**Expected behavior**
The input should not be clipped and the results shown should be based on instance.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by DonXavierdev**
## Proposed Changes

- Fixes #10550 
- Replace "Kind" with "Instance" to fetch location details based on it
- Fix Input box clipping issue

@rithviknishad 

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Enhanced location search functionality with an additional filtering option, allowing for more precise, instance-based selection.
  
- **Style**
  - Adjusted spacing in the search interface for a cleaner and more consistent user experience.

### CODE REVIEW

File: src/components/ui/command.tsx [hunk 1]
```diff
@@ -39,7 +39,7 @@ const CommandInput = React.forwardRef<
   React.ComponentPropsWithoutRef<typeof CommandPrimitive.Input>
 >(({ className, ...props }, ref) => (
   // eslint-disable-next-line react/no-unknown-property
-  <div className="flex items-center border-b px-2" cmdk-input-wrapper="">
+  <div className="flex items-center border-b px-2 py-2" cmdk-input-wrapper="">
```
Comment (bodhish) [inline src/components/ui/command.tsx]: Lets not edit SHADCN!!!!

File: src/components/Location/LocationSearch.tsx [hunk 2]
```diff
@@ -20,7 +20,7 @@ import locationApi from "@/types/location/locationApi";
 
 interface LocationSearchProps {
   facilityId: string;
-  mode?: "kind" | "location";
+  mode?: "kind" | "location" | "instance";
```
Comment (bodhish) [inline src/components/Location/LocationSearch.tsx]: Location is not a valid mode
```suggestion
  mode?: "kind" | "instance";
```

**Review by bodhish — DISMISSED** [review]

File: src/components/ui/command.tsx (hunk 1 above)
Comment (DonXavierdev) [reply src/components/ui/command.tsx]: Oh sorry my mistake

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
