### PR TITLE
Fix #15003 Handle undefined page param in Facility Users offset calculation

### LINKED ISSUE #15003: UI sends offset=NaN when loading Facility Users list
**Describe the bug**
When clicking on the Users option , the frontend sends an invalid pagination parameter to the backend. The API request looks like:

/api/v1/facility/<facility_id>/users/?limit=15&offset=NaN

This happens because the UI calculates offset using (qParams.page - 1) * limit, but page is not initialized on the first load. As a result, page becomes undefined and the computed offset turns into NaN

**To Reproduce**

1. Log in 
2. Go to Users

**Expected behavior**
offset should always be a non-negative integer. Sending NaN is incorrect and can break pagination behavior. The UI should default page to 1 when it is not present so that the initial request sends offset=0.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Deepcode007**
## Proposed Changes

Fixes #15003 
## Description
This PR fixes a bug where the Facility Users list API request would send offset=NaN on the initial load.

The issue was caused by `qParams.page` being undefined when no page parameter is present in the URL, causing (undefined - 1) to evaluate to NaN.

This change ensures that page defaults to 1 if it is missing, resulting in a correct offset of 0 for the first page.
### Screenshots:
image

### Testing:
Manually verified that navigating to the Facility Users page now sends a valid offset=0 query parameter in the API request.
Verified pagination still works for subsequent pages.

Tagging: @ohcnetwork/care-fe-code-reviewers @yash-learner @NikhilA8606 

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed pagination offset calculation across multiple list and data table views to properly handle edge cases when page values are zero or other falsy values. This ensures consistent pagination behavior and prevents negative offset errors.

### CODE REVIEW

File: src/components/Facility/FacilityUsers.tsx [hunk 1]
```diff
@@ -39,7 +39,7 @@ export default function FacilityUsers(props: { facilityId: string }) {
       queryParams: {
         username: qParams.username,
         limit: resultsPerPage,
-        offset: (qParams.page - 1) * resultsPerPage,
+        offset: ((qParams.page || 1) - 1) * resultsPerPage,
```
Comment (abhi-battula) [inline src/components/Facility/FacilityUsers.tsx:42]: This doesn't fully fix the bug. '||' defaults on any falsy value, not just when page is missing. '??' is the correct fallback here.

**Review by nihal467 — APPROVED** [review]

**Review by abhimanyurajeesh — APPROVED** [review]

File: src/components/Facility/FacilityUsers.tsx (hunk 1 above)
Comment (Deepcode007) [reply src/components/Facility/FacilityUsers.tsx:42]: Using `??` would treat 0 as valid → `(0 - 1) * resultsPerPage = -resultsPerPage`, causing a negative offset, which will likely cause a issue.
Thanks for the review btw.

**Review by rithviknishad — APPROVED** [review]

**Review by Deepcode007 — COMMENTED** [review]
@abhi-battula  Reviewed.

File: src/components/Facility/FacilityUsers.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (Deepcode007) [reply src/components/Facility/FacilityUsers.tsx:42]: @coderabbitai Using `??` would treat 0 as valid → `(0 - 1) * resultsPerPage = -resultsPerPage`, causing a negative offset, which will likely cause a issue, right?

Comment (Jacobjeevan) [reply src/components/Facility/FacilityUsers.tsx:42]: You can do

`((qParams.page ?? 1) - 1) * resultsPerPage`

Anyways, check for other/similar usages that need to be fixed as well, there are a few.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Facility/FacilityUsers.tsx (hunk 1 above)
Comment (Deepcode007) [reply src/components/Facility/FacilityUsers.tsx:42]: Fixed this and other files as well.

Comment (Jacobjeevan) [reply src/components/Facility/FacilityUsers.tsx:42]: are you sure? there's 42 usages

Image

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Organization/OrganizationPatients.tsx [hunk 2]
```diff
@@ -81,7 +81,7 @@ export default function OrganizationPatients({ id, navOrganizationId }: Props) {
         ...(organization?.org_type === "govt" && { organization: id }),
         page: qParams.page,
         limit: resultsPerPage,
-        offset: ((qParams.page ?? 1) - 1) * resultsPerPage,
+        offset: ((qParams.page || 1) - 1) * resultsPerPage,
```
[the remark this answers is not in the document]
Comment (Deepcode007) [reply src/pages/Organization/OrganizationPatients.tsx]: @coderabbitai check latest commit.

File: src/components/Facility/FacilityUsers.tsx (hunk 1 above)
Comment (Deepcode007) [reply src/components/Facility/FacilityUsers.tsx:42]: @Jacobjeevan I have done the changes that I had overlooked.

**Comment by Deepcode007** [comment]
@Jacobjeevan Merge conflicts have been resolved.

**Comment by Deepcode007** [comment]
Resolved!

**Review by adarsh-priydarshi-5646 — APPROVED** [review]

**Comment by Deepcode007** [comment]
Merge conflicts have been resolved!
@Jacobjeevan Please review

File: src/pages/Appointments/AppointmentsPage.tsx [hunk 3]
```diff
@@ -836,7 +836,7 @@ function AppointmentRow(props: {
         tags: props.tags,
         tags_behavior: props.tags_behavior,
         limit: props.resultsPerPage,
-        offset: ((props.page ?? 1) - 1) * props.resultsPerPage,
+        offset: ((props.page || 1) - 1) * props.resultsPerPage,
         patient: props.patient,
```
[the remark this answers is not in the document]
Comment (Deepcode007) [reply src/pages/Appointments/AppointmentsPage.tsx:840]: @coderabbitai Will work on this negative and infinite check if maintainer recommends.

**Comment by Deepcode007** [comment]
Resolved!

**Review by Deepcode007 — COMMENTED** [review]
re-reviewed

**Comment by Deepcode007** [comment]
Resolved !

**Comment by Deepcode007** [comment]
@coderabbitai resume

**Review by yash-learner — APPROVED** [review]
https://github.com/ohcnetwork/care_fe/pull/15065/changes#r2675129915, the chance page being 0 is rare, it would happen only if someone manually sets it to 0 in url

**Comment by Deepcode007** [comment]
> https://github.com/ohcnetwork/care_fe/pull/15065/changes#r2675129915, the chance page being 0 is rare, it would happen only if someone manually sets it to 0 in url

That's also a point, this is just a safety check, so do you recommend any changes?

**Comment by Deepcode007** [comment]
@Jacobjeevan Please review.

**Review by Jacobjeevan — APPROVED** [review]
Looks fine, need to be tested before being merged due to changes across the code base, low priority change.

**Review by nihal467 — APPROVED** [review]
