### PR TITLE
Changed Doctors Log to progress notes

### LINKED ISSUE #8036: Rename the Round Type  "DOCTORS_LOG" to Progress Notes on Daily Rounds Module
**Describe the bug**
The round type mentioned on Daily Rounds tab is still DOCTORS_LOG. since it is renamed to Progress Notes on round type please change it to Progress Notes on Daily rounds Tab also. 
**To Repropduce**

1. Login on CARE with doctor's User credentials
2. Click on any Patient
3. click on file notes and file a progress note
4. access to the Daily rounds / Events Module
5. see the error

**Expected behavior**
Round Type should be Progress notes since there is no round type as Doctors Log update on round type.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by shivankacker**
## Proposed Changes

- Fixes #8036
- Changes `DOCTORS_LOG` to `Progress Notes`

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

File: src/Components/Facility/Consultations/DailyRounds/LogUpdateCardAttribute.tsx [hunk 1]
```diff
@@ -69,7 +69,9 @@ const LogUpdateCardAttribute = <T extends keyof DailyRoundsModel>({
           <span className="text-sm font-semibold text-gray-700">
             {(attributeValue as string) === "VENTILATOR"
               ? "CRITICAL CARE"
-              : (attributeValue as string)}
+              : (attributeValue as string) === "DOCTORS_LOG"
+                ? "Progress Notes"
```
Comment (nihal467) [inline src/Components/Facility/Consultations/DailyRounds/LogUpdateCardAttribute.tsx]:
```suggestion
                ? "PROGRESS NOTE"
```

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
