### PR TITLE
Fix: login error translation

### LINKED ISSUE #12891: Login Error messages not showing in selected language
**Describe the bug**
The error messages for respective languages are not showing when switching between languages.
the translation for otp error is written in some languages ( malayalam)

https://github.com/user-attachments/assets/e985a77c-468c-423f-9a64-f3e00eb34635

**Expected behavior**
Error messages should automatically update to display in the currently selected language.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Denyme24**
## Proposed Changes

- Fixes #12891 

https://github.com/user-attachments/assets/e68fb6a4-2844-4919-8b4e-00af3ed41bac

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **Bug Fixes**
  * OTP-related error messages on the login screen now update automatically when the app language changes, ensuring users always see error messages in their selected language.
  * Improved display of OTP error messages to show server-provided details directly, enhancing clarity for users during login issues.

### CODE REVIEW

File: src/components/Auth/Login.tsx [hunk 1]
```diff
@@ -126,6 +126,37 @@ const Login = (props: LoginProps) => {
     localStorage.setItem(LocalStorageKeys.loginPreference, loginMode);
   }, [loginMode]);
 
+  // Reactive translation for error messages
+  const translatedOtpError = useMemo(() => {
```
Comment (Jacobjeevan) [inline src/components/Auth/Login.tsx]: why over complicate this? 🤔 

Instead call t(otpError) in line 544.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Auth/Login.tsx (hunk 1 above)
Comment (Denyme24) [reply src/components/Auth/Login.tsx]: have done the changes.

File: src/components/Auth/Login.tsx [hunk 2]
```diff
@@ -179,13 +178,19 @@ const Login = (props: LoginProps) => {
           (e: OtpValidationError) => e.otp,
         );
         if (otpError && otpError.otp) {
-          errorMessage = otpError.otp;
+          setOtpValidationError(otpError.otp); // Keep server message as-is
+          toast.error(otpError.otp);
+          return;
```
Comment (Jacobjeevan) [inline src/components/Auth/Login.tsx]: why not keep earlier approach? set values to errorMessage and use that variable instead.

Better readability imo.

File: src/components/Auth/Login.tsx [hunk 3]
```diff
@@ -138,9 +138,9 @@ const Login = (props: LoginProps) => {
       const errors = error?.data || [];
       if (Array.isArray(errors) && errors.length > 0) {
         const firstError = errors[0] as OtpError;
-        setOtpError(firstError.msg);
+        setOtpError(firstError.msg); // Keep server message as-is
```
Comment (Jacobjeevan) [inline src/components/Auth/Login.tsx]: rm unnecessary comments.

**Review by Jacobjeevan — DISMISSED** [review]

File: src/components/Auth/Login.tsx (hunk 2 above)
Comment (Denyme24) [reply src/components/Auth/Login.tsx]: did the changes,
i though we should not use same variable for displaying both server error message and generic translated message, but anyways i have made the changes

File: src/components/Auth/Login.tsx (hunk 3 above)
Comment (Denyme24) [reply src/components/Auth/Login.tsx]: removed those comments

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
