### PR TITLE
Resolved Edit resource category form and charge item definition edit form bug

### LINKED ISSUE #15068: Bug: Resource categrory and Charge item defintion edit form
**Describe the bug**
- Edit resource category form is resetting into initial state after reopen it 2nd time
- Update button persist even after changing the slug value in Charge item defnion edit form
Also check the similar issue elsewhere in the platform

https://github.com/user-attachments/assets/16fa614e-d9ea-4fe8-8313-e925beeff004

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Sreyas62**
## Proposed Changes

Fixes #15068 
- Consolidated the two useEffects that handles both create and edit modes based on isOpen state, eliminating the race condition that caused form reset on second open.
- Added shouldDirty: true flag so the form properly tracks changes in slug values, enabling the Update button in ChargeItemDefinitionForm.
- Find and fixed similar issue in ProductKnowledgeForm and ResourceCategoryForm

https://github.com/user-attachments/assets/630b30cd-da0b-48de-bf71-93983b7cdacf

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Bug Fixes**
  * Consolidated form initialization for create/edit sheets so fields reliably reset or populate when a sheet opens, preventing stale or incorrect values.
  * Slug input handling now marks manual/sanitized changes as “dirty,” ensuring validation and change tracking run consistently during edits.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/components/Common/ResourceCategoryForm.tsx [hunk 1]
```diff
@@ -96,28 +96,28 @@ export function ResourceCategoryForm({
...
         description: categoryData.description || "",
         resource_sub_type: categoryData.resource_sub_type,
       });
-    }
-  }, [categoryData, form]);
-
-  useEffect(() => {
-    if (!isOpen) {
+    } else if (!isEditing) {
+      // Create mode: reset to empty defaults
```
Comment (AdityaJ2305) [inline src/components/Common/ResourceCategoryForm.tsx]:
```suggestion
    } else {
```

File: src/components/Common/ResourceCategoryForm.tsx [hunk 2]
```diff
@@ -96,28 +96,28 @@ export function ResourceCategoryForm({
...
   });
 
-  // Update form when category data loads
+  // Update form when sheet opens - handles both create and edit modes
   useEffect(() => {
-    if (categoryData) {
+    if (!isOpen) return;
+
+    if (isEditing && categoryData) {
+      // Edit mode: populate form with existing data
```
Comment (AdityaJ2305) [inline src/components/Common/ResourceCategoryForm.tsx]:
```suggestion

```

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

File: src/components/Common/ResourceCategoryForm.tsx [hunk 3]
```diff
@@ -96,28 +96,28 @@ export function ResourceCategoryForm({
...
+      // Create mode: reset to empty defaults
       form.reset({
         title: "",
         slug_value: "",
         description: "",
         resource_sub_type: ResourceCategorySubType.other,
       });
     }
-  }, [isOpen, form]);
+  }, [isOpen, isEditing, categoryData, form]);
```
[the remark this answers is not in the document]
Comment (Jacobjeevan) [reply src/components/Common/ResourceCategoryForm.tsx]: @Sreyas62 Do remove form from dependency array.

**Review by Jacobjeevan — APPROVED** [review]

**Review by abhimanyurajeesh — APPROVED** [review]
