### PR TITLE
 fix: permission check to rebalance

### LINKED ISSUE #14689: Add permission check to rebalance
- In accounts, add permission check to rebalance.

### PR DESCRIPTION
**Pull request by StephZam**
## Proposed Changes

Fixes #14689 
- Added permissions for account
- Added permission check to rebalance

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **New Features**
  * Added account-level permission flags and switched Create/Edit/Rebalance UI to permission-driven gating across lists, details, and action panels.

* **Bug Fixes / Behavior**
  * Removed legacy write-prop gating so action visibility consistently follows the new permission checks.

* **Tests**
  * Added end-to-end tests verifying Create/Edit/Rebalance visibility for facility admin, admin, and nurse roles.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

File: src/components/Patient/AccountSheet.tsx [hunk 1]
```diff
@@ -109,7 +119,7 @@ export function AccountSheetButton({
                     <ExternalLink className="size-4" />
                     {t("more_details")}
                   </Button>
-                  {canWrite && (
+                  {canWrite && canUpdateAccount && (
```
Comment (Jacobjeevan) [inline src/components/Patient/AccountSheet.tsx]: we can remove canWrite now since we have added the correct permissions 👍 Remove from props as well

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
Minor things, other lgtm.

**Review by Jacobjeevan — APPROVED** [review]

**Review by nihal467 — CHANGES_REQUESTED** [review]
fix the playwright failure related to your PR

**Review by nihal467 — APPROVED** [review]
