### PR TITLE
Replaced Empty Div With Avatar When SideBar is Closed

### LINKED ISSUE #9831: Blank Div Appears When Sidebar is Closed
#### Description
- When the sidebar is closed, a blank div appears where an icon or avatar could be placed. This issue particularly affects items inside the sidebar that don't have an icon assigned to them, causing a poor user experience and visual inconsistency.

#### Steps to Reproduce
- Open the application with the sidebar expanded.
- Close the sidebar.
- Observe the blank div that appears in place of where an icon or avatar should be.
### Expected Behavior
- An appropriate placeholder, such as a default icon or avatar, should be displayed in the blank space to enhance the UI and maintain consistency.
#### Actual Behavior
- A blank div appears, which looks empty and unpolished.
- 
Image

#### Proposed Solution
Add a default icon or avatar to items without an assigned icon when the sidebar is closed.
Screenshots
(Attach screenshots showing the issue if possible)

Environment
Browser: (e.g., Chrome 117.0, Firefox 116.0)
OS: (e.g., Windows 11, macOS Ventura)
Version: (e.g., v1.2.3)

### PR DESCRIPTION
**Pull request by AnveshNalimela**
## Proposed Changes

- Fixes #9831 
- Change 1
- Change 2
- More?

@ohcnetwork/care-fe-code-reviewers

Screenshot from 2025-01-09 11-29-22

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced sidebar link display with dynamic icon and avatar rendering
	- Added fallback avatar when no icon is specified for a link
	- Improved link name presentation with slight margin adjustment

### CODE REVIEW

File: src/components/ui/sidebar/nav-main.tsx [hunk 1]
```diff
@@ -45,8 +47,16 @@ export function NavMain({
                 activeClass="bg-white text-green-700 shadow"
                 exactActiveClass="bg-white text-green-700 shadow"
               >
-                {link.icon && <CareIcon icon={link.icon as IconName} />}
-                <span className="group-data-[collapsible=icon]:hidden">
+                {link.icon ? (
+                  <CareIcon icon={link.icon as IconName} />
+                ) : (
+                  <Avatar
```
Comment (Jacobjeevan) [inline src/components/ui/sidebar/nav-main.tsx:53]: 🤔  Why add Avatar here? It wouldn't make any sense to do so. Just add icons to the relevant sidebar links instead (you can find icons at /icons if you want to hunt for relevant ones).

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/ui/sidebar/nav-main.tsx (hunk 1 above)
Comment (AnveshNalimela) [reply src/components/ui/sidebar/nav-main.tsx:53]: @Jacobjeevan  What if user associated with Multiple organizations. If we add an icon it would same for multiple organizations. Doesnt make any distinction.
