### PR TITLE
Fixed #13732: Fixed UI of Tags dropdown in Add Patient Details page

### LINKED ISSUE #13732: Enhance usability by solving the UI inconsistencies on the "Add Patient Details" page
**Description**
This issue addresses UI inconsistencies in the Patient Tag drop down menu of "Add Patient Details" page:

- Tag Menu Dropdown: The height of the search input as well as the menu items need to be adjusted to align with our design system.

- Keyboard Shortcuts: The size of the keyboard shortcuts is inconsistent and needs to be fixed.

- The padding for each tag option within the dropdown should be consistent with the provided Figma file, ensuring proper alignment and spacing.

**Steps to Reproduce**

1. Navigate to Add Patient's details page.

2. Scroll down to the Patient Tags field.

3. Open the dropdown menu.

4. Observe the current option height.

**Expected Behaviour**

- The tag menu dropdown should adhere to the following specifications:

        - The search input field at the top of the dropdown should have a fixed height of 40 pixels.

        - The padding for each tag option within the dropdown should be consistent with the provided Figma file, ensuring proper alignment and spacing. 

- Keyboard Shortcuts

      -  The size of the keyboard shortcut indicators should match the design specifications. They currently appear smaller than intended.         

- Add a secondary button to complete the action.

**Visual Reference**

Image
Image
Image

**Proposed Solution**
Attached screenshot for reference
Image
Refer the figma file for the correct dimensions https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=26304-10329&t=AskluDORl8G3ixs5-1

---
### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Ishu813**
## Proposed Changes

Fixes #13732
- Made changes in Tailwind classes as suggested.
- Made changes in Navigation Buttons as suggested.

**Screenshot**

Screenshot 2025-10-22 at 19 25 20

Figma Link : https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=26304-10329&t=AskluDORl8G3ixs5-1

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

* **New Features**
  * Added an English translation entry: "To Select".
  * Keyboard/arrow navigation controls added for tag selection.

* **UI Improvements**
  * Redesigned tag selector with improved spacing and responsive behavior.
  * Clearer parent/child tag indicators and improved truncation for long tags.
  * Updated header and footer controls and labels for a more consistent mobile and desktop experience.

### CODE REVIEW

File: src/components/Tags/MultiFilterStyleTagSelector.tsx [hunk 1]
```diff
@@ -631,28 +635,36 @@ export function MultiFilterStyleTagSelector({
...
+                  <span className="text-xs text-gray-700 self-center">
+                    {t("to_select")}
                   </span>
                 </div>
+                <div className="flex gap-1 my-2 mx-2">
+                  <button
+                    type="button"
+                    data-cy="tag-selector-done"
+                    onClick={() => setOpen(false)}
+                    className="bg-green-800 text-white px-3 py-2 rounded-md flex items-center gap-2"
```
Comment (AdityaJ2305) [inline src/components/Tags/MultiFilterStyleTagSelector.tsx]: Use shadcn button with variant instead of adding tailwind class 👍

File: src/components/Tags/MultiFilterStyleTagSelector.tsx [hunk 2]
```diff
@@ -631,28 +635,36 @@ export function MultiFilterStyleTagSelector({
...
-                  <span className="text-xs text-gray-500 self-center">
-                    {t("select")}
+                  <span className="text-xs text-gray-700 self-center">
+                    {t("to_select")}
                   </span>
                 </div>
+                <div className="flex gap-1 my-2 mx-2">
+                  <button
+                    type="button"
+                    data-cy="tag-selector-done"
```
Comment (AdityaJ2305) [inline src/components/Tags/MultiFilterStyleTagSelector.tsx]:
```suggestion

```

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

File: src/components/Tags/MultiFilterStyleTagSelector.tsx (hunk 2 above)
Comment (Ishu813) [reply src/components/Tags/MultiFilterStyleTagSelector.tsx]: @AdityaJ2305 Have done the changes...pls have a look.

**Comment by AdityaJ2305** [comment]
@anaghathedesigner Could you check the changes in the UI ? 

Use this link to check the changes in UI: https://deploy-preview-14087.preview.ohc.network/

**Review by NikhilA8606 — CHANGES_REQUESTED** [review]
For now, remove the Done button; we only need the Select button.

**Comment by NikhilA8606** [comment]
Mention the figma link in the PR description

**Comment by Ishu813** [comment]
> Mention the figma link in the PR description

@NikhilA8606 Have done the changes....pls have a look.

**Comment by anaghathedesigner** [comment]
Let's ensure these layout specifications are met:

- The Search Input height should be set to 40 px.

- The container height for the "Done" action area is defined as 44 px.

**Comment by tasnimshaji** [comment]
LGTM @nihal467

**Comment by nihal467** [comment]
@anaghathedesigner can you review it once

**Comment by anaghathedesigner** [comment]
Verified the update — the issue has been resolved.

**Review by anaghathedesigner — APPROVED** [review]
LGTM

**Review by AdityaJ2305 — APPROVED** [review]

**Comment by nihal467** [comment]
@Ishu813 fix the failing test is your PR

**Comment by nihal467** [comment]
LGTM
