### PR TITLE
 Fix: Minor Resources Form UI and `UserSelector` display option alignment

### LINKED ISSUE #11670: Incorrect alignment for display name in User Selector and Practicioner Selector
**Describe the bug**

Incorrect alignment for display name in User Selector and Practicioner Selector.

**To Reproduce**

1. Go to any place where practicioner selector or user selector component is being used
2. See dropdown containing a long name similar to shown in screenshots

**Expected behavior**
Display name should be followed by username. Not as separate columns. Should be in a single span, left aligned.

**Screenshots**
Image

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- [x] Header margin fix
- [x] Made UserSelector to match width with other selectors
- [x] UserSelector and PractitionerSelector options alignment issue fix
- [x] Fixes:  #11670 

- Before
Screenshot 2025-04-02 at 2 23 50 AM
Screenshot 2025-04-02 at 11 54 35 AM

- After

Screenshot 2025-04-02 at 4 03 58 PM

Screenshot 2025-04-02 at 1 38 10 PM

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Expanded the contact section with new fields and an updated phone input.
  - Switched the emergency selection to radio buttons for a clearer choice.

- **Refactor**
  - Reorganized the form layout and field order for a more streamlined experience.
  - Enhanced the display of user information in both the UserSelector and PractitionerSelector components.

- **Style**
  - Improved spacing, field descriptions, and placeholders to enhance usability.
  - Consolidated user information presentation for better alignment and styling.

### CODE REVIEW

**Review by abhimanyurajeesh — CHANGES_REQUESTED** [review]
1. do you think its good to have the title like this (soo far )?
2. follow the merge check list

**Comment by AdityaJ2305** [comment]
@abhimanyurajeesh , Sorry but couldn't understand the first point 😅 and second, it was one line change so I thought Just add Before and after+ merge checklist is checked already, Prep Screenshot and request for review. What am I missing? 🤔

**Comment by rithviknishad** [comment]
completion of QA?

**Comment by rithviknishad** [comment]
@AdityaJ2305 avoid creating PRs without issues. Moreover when doing small fixes like these, it'd be good to ensure all of the minor UI issues in that page is also completed;

**Comment by AdityaJ2305** [comment]
@rithviknishad , Let me check if I can find other UI issues on this page and it was single line change 😅 so directly created PR

**Comment by AdityaJ2305** [comment]
@rithviknishad , Couldn't find more UI issues on same page , Updated the description with User Selector width issue 
Ready for review

File: src/components/Common/UserSelector.tsx [hunk 1]
```diff
@@ -61,7 +61,7 @@ export default function UserSelector({
         <Button
           variant="outline"
           role="combobox"
-          className="min-w-60 justify-start"
+          className="min-w-60 justify-start w-full"
```
Comment (rithviknishad) [inline src/components/Common/UserSelector.tsx]: just pass this as `popoverClassName` instead like done in other places.

File: src/components/Resource/ResourceForm.tsx [hunk 2]
```diff
@@ -231,7 +231,7 @@ export default function ResourceForm({ facilityId, id }: ResourceProps) {
     <Page
       title={id ? t("update_resource_request") : t("create_resource_request")}
     >
-      <div className="container mx-auto max-w-4xl">
+      <div className="container mx-auto max-w-4xl  space-y-6 p-4 md:p-6">
```
Comment (rithviknishad) [inline src/components/Resource/ResourceForm.tsx]:
```suggestion
      <div className="container mx-auto max-w-4xl space-y-6 p-4 md:p-6">
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]
like @abhimanyurajeesh already said, the page title should be aligned with where the form's card starts.

i.e., page title should fall within the element containing `max-w-4xl mx-auto` classes.

let's also keep the styling consistent. let's not add white background and card and all to the form. let's keep it similar to how other forms are.

similar to other forms like devices:

image

File: src/components/Common/UserSelector.tsx (hunk 1 above)
Comment (AdityaJ2305) [reply src/components/Common/UserSelector.tsx]: done

File: src/components/Resource/ResourceForm.tsx [hunk 3]
```diff
@@ -228,241 +228,299 @@ export default function ResourceForm({ facilityId, id }: ResourceProps) {
...
-
-                <div className="space-y-6">
-                  <div>
-                    <h3 className="text-lg font-medium">
-                      {t("basic_information")}
-                    </h3>
-                    <p className="text-sm text-gray-500">
-                      {t("resource_request_basic_info_description")}
-                    </p>
+    <div className="container mx-auto max-w-4xl  space-y-6 p-4 md:p-6">
```
Comment (rithviknishad) [inline src/components/Resource/ResourceForm.tsx]:
```suggestion
    <div className="container mx-auto max-w-4xl space-y-6 p-4 md:p-6">
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]
previously requested changes have not been fully completed! 

image


please refrain from requesting reviews until you've ensured everything is completed!

**Comment by AdityaJ2305** [comment]
Screenshot 2025-04-02 at 4 03 58 PM


@rithviknishad  Apologies, Missed that one , Done with the changes ready for review

**Review by rithviknishad — APPROVED** [review]

**Comment by rithviknishad** [comment]
please update the screenshots as well in the PR's body!

**Review by rithviknishad — APPROVED** [review]

File: src/components/Resource/ResourceForm.tsx [hunk 4]
```diff
@@ -228,373 +227,342 @@ export default function ResourceForm({ facilityId, id }: ResourceProps) {
...
+                  <FormMessage />
+                </FormItem>
+              )}
+            />
+          </div>
+
+          <Separator />
+
+          <div className="space-y-6">
+            <div className="flex flex-col lg:flex-row gap-2 lg:items-center justify-between">
```
Comment (abhimanyurajeesh) [inline src/components/Resource/ResourceForm.tsx]:
```suggestion
            <div className="flex flex-col sm:flex-row gap-2 sm:items-center justify-between">
```

**Review by abhimanyurajeesh — COMMENTED** [review]
LGTM

**Review by abhimanyurajeesh — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
