### PR TITLE
Enhance Expired On Label Styling on Encounter and Patient details Page for Better Visibility

### LINKED ISSUE #10990: Improve "Expired On" Label Design on Encounter page
**Describe the bug**
The "Expired On" label design is not visually optimized

**To Reproduce**

[Click here to reproduce](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/patient/dba186d6-87a7-4df0-ae81-9b0d5b26d96e/encounter/01a53e83-5cb8-4c11-af4d-7b3502cb5b5f/updates)

 See error

**Expected behavior**
The "Expired On" label should be clear, visually distinct, and consistent with the UI.

**Screenshots**

Image

Expected

Image

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [132.0.6834.111]

**Additional context**

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes

1. Improved Styling for Better Visibility and Readability.

- Fixes #10990 
- Change 1
- 

https://github.com/user-attachments/assets/e53ff992-d7b6-4905-a685-d8e42a4caffe

- Change 2
- More?

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style**
  - Enhanced the visual presentation of patient death status badges with refined borders, background colors, and hover effects for a more distinct, engaging look.
  
- **New Features**
  - Updated labeling across patient views to provide clearer information, now displaying "time_of_death" or "deceased" instead of older terminology for improved consistency.
  
- **Documentation**
  - Updated localization strings to reflect new terminology, adding "deceased" and "time_of_death" while removing outdated terms like "expired" and "expired_on".

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]
Lgtm.

Hmm, we would potentially add a new variant, but leave it for now. We can add it later if we use this style anywhere else.

**Comment by amjithtitus09** [comment]
@modamaan Can you change "Expired on" to "Time of death"? And wherever "Expired" badge is displayed to "Deceased".

**Comment by modamaan** [comment]
Screenshot 2025-03-07 001536

**Comment by modamaan** [comment]
Screenshot 2025-03-07 001007

File: src/pages/Encounters/EncounterList.tsx [hunk 1]
```diff
@@ -706,7 +706,7 @@ export function EncounterList({
                           {encounter.patient.death_datetime && (
                             <Badge variant="destructive" className="ml-2 py-0">
                               <h3 className="text-xs font-medium">
-                                {t("expired")}
+                                {t("deceased")}
```
Comment (Jacobjeevan) [inline src/pages/Encounters/EncounterList.tsx]: Why are the styling changes not applied here? 🤔

Comment (modamaan) [reply src/pages/Encounters/EncounterList.tsx]: updated

**Comment by modamaan** [comment]
Screenshot 2025-03-09 150141

**Comment by Jacobjeevan** [comment]
Adjust for mobile as well, doesn't look too nice on patient details page. Also test for much longer names as well 👍 

image

**Comment by modamaan** [comment]
Screenshot 2025-03-16 114625
Screenshot 2025-03-16 114617

**Comment by Jacobjeevan** [comment]
Let's adjust the spacing between name and age, deceased badge for encounter listing.

Right now, spacing between name and latter block seems too much, and not enough spacing between age and deceased.

**Comment by modamaan** [comment]
Screenshot 2025-03-18 213257
Screenshot 2025-03-18 213248

**Comment by modamaan** [comment]
@Jacobjeevan 
Screenshot 2025-03-18 214806

**Comment by modamaan** [comment]
Screenshot 2025-03-18 214853

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
