### PR TITLE
Fix :  Alignment of Country List in Phone Number Search

### LINKED ISSUE #10733: Improve Country List Alignment
**Describe the bug**
The country list in the phone number search section is not consistently aligned.

**To Reproduce**

1. Go to 'Search Patients' tab and login tab (login tab - Phone Number login)
2. The country list in the phone number search section is not consistently aligned.

**Expected behavior**
The country names and their corresponding phone codes should always be aligned under each other.

**Screenshots**

Image    -> 

Image

Expect behavior

Image

Image

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #10733
- Used align="start" sideOffset={5}
p2

p1

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Enhanced the layout and positioning of the popover display within the country selection component. The responsive design improves usability on smaller screens, ensuring a polished and intuitive experience when interacting with the selection field.

### CODE REVIEW

**Comment by Jacobjeevan** [comment]
Check the dropdown for other devices as well:

image

File: src/components/ui/phone-input.tsx [hunk 1]
```diff
@@ -120,7 +120,11 @@ const CountrySelect = ({
           />
         </Button>
       </PopoverTrigger>
-      <PopoverContent className="w-[300px] p-0">
+      <PopoverContent
+        className="w-[90vw] sm:w-[300px] p-2 sm:p-0"
```
Comment (Jacobjeevan) [inline src/components/ui/phone-input.tsx]: See if you can make this work using `--radix-popover-trigger-width` variable (check for examples in codebase), so we don't use custom width here.

File: src/components/ui/phone-input.tsx [hunk 2]
```diff
@@ -121,7 +121,8 @@ const CountrySelect = ({
         </Button>
       </PopoverTrigger>
       <PopoverContent
-        className="w-[90vw] sm:w-[300px] p-2 sm:p-0"
+        className="p-2 sm:p-0"
+        style={{ width: "var(--radix-popover-trigger-width)" }}
```
Comment (Jacobjeevan) [inline src/components/ui/phone-input.tsx]: you can use tailwind's custom width:

`w-[var(--radix-popover-trigger-width)]`

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/components/ui/phone-input.tsx [hunk 3]
```diff
@@ -120,7 +120,11 @@ const CountrySelect = ({
           />
         </Button>
       </PopoverTrigger>
-      <PopoverContent className="w-[300px] p-0">
+      <PopoverContent
+        className="p-2 sm:p-0 w-[var(--radix-popover-trigger-width)] min-w-[250px]"
```
Comment (rithviknishad) [inline src/components/ui/phone-input.tsx]: let's NOT use arbitrary pixel values when it's possible without it!
```suggestion
        className="p-2 sm:p-0 w-[var(--radix-popover-trigger-width)] min-w-64"
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/ui/phone-input.tsx (hunk 3 above)
Comment (rithviknishad) [reply src/components/ui/phone-input.tsx]: do check and verify things before requesting next review

**Review by rithviknishad — APPROVED** [review]
