### PR TITLE
Selected organization appearing in Selected Organizations list

### LINKED ISSUE #12619: Bug: Selected organization not appearing in 'Selected Organizations' list
**Describe the bug**
In the Manage Organizations modal, when a user selects an organization from the dropdown, the organization gets visually selected (with a checkmark), but it does not appear in the "Selected Organizations" list displayed above.

**To Reproduce**
1. Go to 'edit questionnaire'
2. Click on 'manage organizations'
3. select one

**Expected behavior**
Once an organization is selected from the dropdown, it should immediately be displayed in above list.

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by vara-prasad-07**
## Proposed Changes

- Fixes #12619
changed "organizations" to "availableOrganizations"
which adds selected organizations dynamically 

view:

https://github.com/user-attachments/assets/59c970f2-aa9c-4503-a5ff-73f1d27d6036

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved organization selection in the questionnaire management interface to ensure all selected organizations are displayed, including those from both initial and searched results.
  - Enhanced organization selection to show detailed information for each selected organization, improving clarity and usability.

### CODE REVIEW

**Comment by vara-prasad-07** [comment]
Hi @Jacobjeevan 
can you please review this PR
thank you

**Comment by sindhureddy-6** [comment]
@vara-prasad-07 
check the related points in merge checklist

**Comment by vara-prasad-07** [comment]
> @vara-prasad-07 check the related points in merge checklist

Done

**Review by AdityaJ2305 — APPROVED** [review]

**Review by AdityaJ2305 — DISMISSED** [review]
@vara-prasad-07 , do checkout comment by codeRabbitai 
just tested out: when you search in searchbar selected org disappear since query is dependent on search right ? 

Update Status: not-approved

**Comment by vara-prasad-07** [comment]
hi @AdityaJ2305 
I made changes according to codeRabbitai again could you please review it 
Thank you

**Comment by Jacobjeevan** [comment]
> hi @AdityaJ2305 I made changes according again could you please review it Thank you

As Aditya mentioned, on search the items (added but not saved) disappear, so you would need to handle that 👍

**Comment by vara-prasad-07** [comment]
Hi @Jacobjeevan @AdityaJ2305 

Everything works fine. when we search in search bar, the selected org also appears.

video:

https://github.com/user-attachments/assets/6d6739af-03fc-4772-b18e-d7c4777fb379


Thank you

**Comment by Jacobjeevan** [comment]
> Hi @Jacobjeevan @AdityaJ2305
> 
> Everything works fine. when we search in search bar, the selected org also appears
> 
> video:
> search_bug_video.mp4
> 
> Thank you

@vara-prasad-07 

It's fine if you are doing it for an already selected org, but not for a new org:


https://github.com/user-attachments/assets/6693e505-b479-4a89-9575-2a752c609d15

**Comment by Jacobjeevan** [comment]
@vara-prasad-07 any updates?

**Comment by vara-prasad-07** [comment]
Hi @Jacobjeevan 

Sorry for delay Because of my sem exams. I will complete by 5th July 
Thank you

**Comment by vara-prasad-07** [comment]
Hi @Jacobjeevan 
i made changes and fixed the bug. 

video :

https://github.com/user-attachments/assets/02a79239-04f6-49d3-932a-6400ae6b6aec

Thank you

**Comment by vara-prasad-07** [comment]
Hi @Jacobjeevan ,
Can you review my recent changes
Thank you

**Comment by vara-prasad-07** [comment]
Hi @Jacobjeevan @AdityaJ2305 ,
Can anyone of you review the latest changes i made. If pr merge as soon as possible because it will helpfull for junior full stack developer role i applied recently. 

Thank you

**Comment by nihal467** [comment]
LGTM

**Review by Jacobjeevan — APPROVED** [review]

File: src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx [hunk 1]
```diff
@@ -152,6 +152,13 @@ export default function ManageQuestionnaireOrganizationsSheet({
   const [open, setOpen] = useState(false);
   const [searchQuery, setSearchQuery] = useState("");
   const [selectedIds, setSelectedIds] = useState<string[]>([]);
+  const [selectedOrgs, setSelectedOrgs] = useState<
+    Array<{
+      id: string;
+      name: string;
+      description?: string;
+    }>
+  >([]);
```
Comment (rithviknishad) [inline src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]: since the newer array state contains both id name and description, do we even need the previous array which contains id only?

isn't this unnecessary duplication of states which would lead to unpredictable behaviours if not maintained correctly?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx (hunk 1 above)
Comment (vara-prasad-07) [reply src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]: yes what you noticed make sense, i didn't  even think about unnecessary duplicant states. I will make changes to use only single state and make sure all related functions works without errors.
ETA: end of the day

Thank you

**Comment by vara-prasad-07** [comment]
Hi @rithviknishad ,
Removed duplicate states and make use only a single state and everything works as desired 

result :

https://github.com/user-attachments/assets/b6bd2f64-e465-4ab0-8fad-8eb73c472058

**Review by rithviknishad — APPROVED** [review]

File: src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx [hunk 2]
```diff
@@ -151,7 +151,10 @@ export default function ManageQuestionnaireOrganizationsSheet({
   const { t } = useTranslation();
   const [open, setOpen] = useState(false);
   const [searchQuery, setSearchQuery] = useState("");
-  const [selectedIds, setSelectedIds] = useState<string[]>([]);
+  // Remove selectedIds state - only keep selectedOrgDetails
+  const [selectedOrgDetails, setSelectedOrgDetails] = useState<
```
Comment (AdityaJ2305) [inline src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]: Let's use already type declared for `Organization`

File: src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx [hunk 3]
```diff
@@ -151,7 +151,10 @@ export default function ManageQuestionnaireOrganizationsSheet({
   const { t } = useTranslation();
   const [open, setOpen] = useState(false);
   const [searchQuery, setSearchQuery] = useState("");
-  const [selectedIds, setSelectedIds] = useState<string[]>([]);
+  // Remove selectedIds state - only keep selectedOrgDetails
```
Comment (AdityaJ2305) [inline src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]:
```suggestion

```

File: src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx [hunk 4]
```diff
@@ -185,35 +188,48 @@ export default function ManageQuestionnaireOrganizationsSheet({
       setOpen(false);
     },
   });
-
-  // Initialize selected IDs when organizations are loaded
+  // Initialize selected organizations when organizations are loaded
```
Comment (AdityaJ2305) [inline src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]:
```suggestion

```

File: src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx [hunk 5]
```diff
@@ -185,35 +188,48 @@ export default function ManageQuestionnaireOrganizationsSheet({
...
+    // Extract IDs from selectedOrgDetails for the API call
+    const selectedIds = selectedOrgDetails.map((org) => org.id);
     setOrganizations({ organizations: selectedIds });
   };
-
-  const selectedOrganizations = organizations?.results.filter((org) =>
-    selectedIds.includes(org.id),
-  );
-
+  const selectedOrganizations = selectedOrgDetails;
```
Comment (AdityaJ2305) [inline src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]: why ???

I think we should rename selectedOrgDetails to selectedOrganizations
wait for @rithviknishad @Jacobjeevan comment for this

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]
Please remove unnecessary comments

File: src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx (hunk 5 above)
Comment (vara-prasad-07) [reply src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]: That can be done. Let's wait for maintainer's response.

**Comment by nihal467** [comment]
LGTM

File: src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx (hunk 5 above)
Comment (Jacobjeevan) [reply src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]: Go ahead and do it 👍

**Comment by vara-prasad-07** [comment]
Hi @rithviknishad @Jacobjeevan, 
i renamed renamed selectedOrgDetails to selectedOrganizations and make sure everything works as desired.
can anyone review this changes 
Thank you

File: src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx (hunk 2 above)
Comment (AdityaJ2305) [reply src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]: @vara-prasad-07  any reason of not doing this change ? 🤔

Comment (AdityaJ2305) [reply src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]: @vara-prasad-07  any reason of not doing this change ? 🤔

**Review by Jacobjeevan — APPROVED** [review]

File: src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx (hunk 2 above)
Comment (vara-prasad-07) [reply src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]: @AdityaJ2305, i didn't understand what you were trying to say, if you don't mind can you clarify more about it.

Comment (AdityaJ2305) [reply src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]: we already have  type declared in types folder which we can use here in useState to define type instead of creating an new object 

Screenshot 2025-07-23 at 5 48 50 PM

File: src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx [hunk 6]
```diff
@@ -151,7 +151,9 @@ export default function ManageQuestionnaireOrganizationsSheet({
   const { t } = useTranslation();
   const [open, setOpen] = useState(false);
   const [searchQuery, setSearchQuery] = useState("");
-  const [selectedIds, setSelectedIds] = useState<string[]>([]);
+  const [selectedOrganizations, setSelectedOrganizations] = useState<
+    { id: string; name: string; description?: string }[]
+  >([]);
```
Comment (AdityaJ2305) [inline src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]: import type instead !! (don't make direct commit from github you need to import the same in file)

```suggestion
  const [selectedOrganizations, setSelectedOrganizations] = useState<
    Organization[]
  >([]);
```

Comment (vara-prasad-07) [reply src/components/Questionnaire/ManageQuestionnaireOrganizationsSheet.tsx]: Thanks for clarification. Just now I started making changes, but @Jacobjeevan already committed changes.

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
