### PR TITLE
Minor fixes in resource creation form

### LINKED ISSUE #9866: Minor fixes in resource creation form
Resources request form is not submitting and Resources are not displayed properly in board view

I have debugged and tried to create resources and the form is not submitting due to sub category error

And also the created resources are not dispalyed properly in board, they should be visible according to status

Image

EDIT:
- Instead of facility ID , facilityname should be visible in breadcrumps

Image
Expected

Image

- Instead of patient id , we can show patient name and add a link
- Expected:

Image

### PR DESCRIPTION
**Pull request by Rishith25**
## Proposed Changes

- Fixes #9866 
- To display the patient name in resource creation form
- Instead of facility ID , facilityname should be visible in breadcrumbs

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Enhanced patient data handling in resource creation.
  - Added ability to link and display patient information.
  - Introduced dynamic breadcrumb replacements based on facility ID in the resource list.

- **UI Updates**
  - Added navigation link to patient resource requests page.

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]

**Comment by Jacobjeevan** [comment]
LGTM, but which deprecated components are being replaced 🤔

**Comment by Rishith25** [comment]
> LGTM, but which deprecated components are being replaced 🤔

@Jacobjeevan It got replaced in PR #10214. I have to change the description of the issue

**Comment by nihal467** [comment]
image
image

- [ ] fix the redirection of resources in the breadcrumbs along with this PR

**Comment by Rishith25** [comment]
@nihal467 Done the changes

File: src/components/Resource/ResourceCreate.tsx [hunk 1]
```diff
@@ -159,22 +166,33 @@ export default function ResourceCreate(props: ResourceProps) {
       title={t("create_resource_request")}
       crumbsReplacements={{
         [facilityId]: { name: facilityData?.name || "" },
-        resource: { style: "pointer-events-none" },
+        resource: {
+          uri: `/resource`,
+          style: "pointer-events-none",
+        },
```
Comment (rithviknishad) [inline src/components/Resource/ResourceCreate.tsx]: this will be changed in https://github.com/ohcnetwork/care_fe/pull/10308

**Comment by Rishith25** [comment]
@rithviknishad this PR is still valid. can you please repoen this PR. #10308 doesn't addressed the changes made in this PR.

**Comment by rithviknishad** [comment]
Made the changes?

**Comment by Rishith25** [comment]
> Made the changes?

@rithviknishad the changes requested by nihal are done

**Review by rithviknishad — DISMISSED** [review]

**Comment by DonXavierdev** [comment]
@rithviknishad About the data fetching done in breadcrumbs here, I had done the same approach in  issue #9822  where i fixed every breadcrumb ID to its corresponding name.But there bodhi suggested that fetching data just for breadcrumbs is not needed.

**Comment by rithviknishad** [comment]
Yup, you are right. 

A high level overview for the right way to solve this at scale would be to use layouts and ensure layouts do the necessary data fetching and set the context for breadcrumbs.

cc: @bodhish

**Comment by nihal467** [comment]
image

- [ ] facility name direction is not working in the request form

image

- [ ] other forms related to the resource such as the tab, details page, update page, none of the resources related breadcrumps are changed.

@Rishith25 follow the solution approach mentioned by @rithviknishad and make the changes only in the resources related breadcrumbs

**Comment by Rishith25** [comment]
> image
> 
> * [ ]  facility name direction is not working in the request form
> 
> image
> 
> * [ ]  other forms related to the resource such as the tab, details page, update page, none of the resources related breadcrumps are changed.
> 
> @Rishith25 follow the solution approach mentioned by @rithviknishad and make the changes only in the resources related breadcrumbs

@rithviknishad @nihal467 
I have done (1)st one
(2)nd one will be solved in #9822 anyways right???

**Comment by nihal467** [comment]
@Rishith25 can you clear the merge conflict

**Comment by Rishith25** [comment]
> @Rishith25 can you clear the merge conflict

@nihal467 Done..

File: src/components/Resource/ResourceCreate.tsx [hunk 2]
```diff
@@ -145,23 +152,34 @@ export default function ResourceCreate(props: ResourceProps) {
...
+              {patientData && (
                 <Alert>
                   <div className="flex items-center gap-2">
-                    <CareIcon icon="l-user" className="h-5 w-5 text-blue-700" />
-                    <AlertDescription className="text-sm text-blue-700">
-                      {t("linked_patient")}:{" "}
-                      <span className="font-medium">{related_patient}</span>
-                    </AlertDescription>
+                    <Link
+                      href={`/facility/${facilityId}/patient/${related_patient}/demography`}
```
Comment (Jacobjeevan) [inline src/components/Resource/ResourceCreate.tsx]: Let's link to resources tab instead.

```suggestion
                      href={`/facility/${facilityId}/patient/${related_patient}/resource_requests`}
```

**Review by Jacobjeevan — APPROVED** [review]
Otherwise lgtm

**Review by rithviknishad — APPROVED** [review]
