### PR TITLE
fix incorrect date filters in verify patient's appointments listing

### LINKED ISSUE #15470: bookings completed today are not being shown in verify patient's past appointments

### PR DESCRIPTION
**Pull request by rithviknishad**
- fixes #15470

## Summary by CodeRabbit

* **Bug Fixes**
  * The "Past" bookings view now uses today as the cutoff, ensuring bookings up to and including today are correctly categorized and visible, improving consistency between tabs.

* **Chores**
  * Removed an unused date utility to simplify the codebase and reduce clutter.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/pages/Appointments/BookAppointment/BookingsList.tsx [hunk 1]
```diff
@@ -73,15 +71,13 @@ export const BookingsList = ({ patientId, facilityId }: BookingsListProps) => {
...
               facilityId={facilityId}
               statuses={UpcomingAppointmentStatuses}
-              date_after={today}
             />
           </TabsContent>
           <TabsContent value="past" className="space-y-4 overflow-x-auto">
             <BookingListContent
               patientId={patientId}
               facilityId={facilityId}
               statuses={PastAppointmentStatuses}
```
Comment (yash-learner) [inline src/pages/Appointments/BookAppointment/BookingsList.tsx:83]:
```ts
export const PastAppointmentStatuses = [
  ...UpcomingAppointmentStatuses,
  AppointmentStatus.FULFILLED,
  AppointmentStatus.NO_SHOW,
];
```
Now without a datefilter

Doesn't this would show appointments of `BOOKED, IN_CONSULTATION, PROPOSED` of future dates in past tab as well is this expected ?

and do you think we need to have one more tab called `In Progress`
