### PR TITLE
Made the  badges responsive in Activity Defination and ProductKnowledgeForm

### LINKED ISSUE #13385: Misaligned badges in Activity Defination details
**Describe the bug**
The badges in the activity defination page is not aligned properly in mobile view.

**To Reproduce**

1. Go to Activity defination
2. Click on See Details
3. See error

**Expected behavior**
The badges should align according to screen size.

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by sj11105**
Fixes #13385
- Made changes in ActivityDefinationPage to align badges.
- Solved the Overlapping in ProductKnowledgeForm.

Tagging: @ohcnetwork/care-fe-code-reviewers

Screenshot 2025-08-19 153710

Screenshot 2025-08-19 154102

## Merge Checklist

- [] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.

## Summary by CodeRabbit

* **Style**
  * Improved header and action layouts for better horizontal flow, gaps and wrapping; added consistent bottom spacing for action buttons.
  * Standardized icon sizing and reduced icon-to-label spacing across headers and form controls.
  * Compacted form section spacing and made certain action buttons responsive (full-width on small screens).

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by tasnimshaji** [comment]
image
Is it alright if the 'active' and 'edit' badge is in different alignment

**Comment by nihal467** [comment]
@sj11105 can you fix the alignment issue reported by @tasnimshaji

**Comment by sj11105** [comment]
okay, i will fix the issue.

**Comment by sj11105** [comment]
image
@tasnimshaji @nihal467  is this fine?

**Comment by Jacobjeevan** [comment]
> image @tasnimshaji @nihal467 is this fine?

Nah, keep in mind there's also delete button. Explore and suggest an alternate design that works for both desktop and mobile.

**Comment by sj11105** [comment]
@Jacobjeevan , As of now there is no delete button on this page.
image
Do you want me to add one ?

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan , As of now there is no delete button on this page.
> image
> Do you want me to add one ?

🧐 check activity definition. 

Can you address that as well? 

My bad, earlier screenshots were for product.

**Comment by sj11105** [comment]
@Jacobjeevan , okay i will make changes to that page as well

**Comment by sj11105** [comment]
Screenshot 2025-08-31 094935


Screenshot 2025-08-31 095136

@nihal467 @Jacobjeevan 
These are the changes in both the pages, If these are correct please let me know, I will push the changes.

File: src/pages/Facility/settings/productKnowledge/ProductKnowledgeForm.tsx [hunk 1]
```diff
@@ -605,7 +605,7 @@ function ProductKnowledgeFormContent({
                       });
                     }}
                   >
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/productKnowledge/ProductKnowledgeForm.tsx:693]: Do ahead and adjust this as well, adjust flex for smaller screens

Image

File: src/pages/Facility/settings/activityDefinition/ActivityDefinitionView.tsx [hunk 2]
```diff
@@ -181,14 +181,14 @@ export default function ActivityDefinitionView({
...
-          <div className="flex gap-2">
+          <div className="flex gap-2 mb-6">
             {definition.status !== "retired" && (
               <Button
                 variant="outline"
                 onClick={() => setShowDeleteDialog(true)}
                 disabled={isDeleting}
               >
-                <CareIcon icon="l-trash" className="mr-2 size-4" />
+                <CareIcon icon="l-trash" className="size-4" />
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/activityDefinition/ActivityDefinitionView.tsx:172]: adjust the width, so each button takes half screen width for small screens.

**Review by Jacobjeevan — DISMISSED** [review]

**Comment by sj11105** [comment]
image

@Jacobjeevan , is this correct

**Comment by Jacobjeevan** [comment]
> image
> 
> @Jacobjeevan , is this correct

Does that seem in line with rest of our design? Think from a user perspective whether it makes sense or not 👍

**Comment by sj11105** [comment]
image
@Jacobjeevan , I have made changes .

**Comment by Jacobjeevan** [comment]
> image
> @Jacobjeevan , I have made changes .

In this case, better to move button to next row (for smaller devices). Though do test for tablet as well.

**Comment by sj11105** [comment]
image
I  have moved the button to the next , and checked for tab screens also.
@Jacobjeevan

**Comment by AdityaJ2305** [comment]
> image I have moved the button to the next , and checked for tab screens also. @Jacobjeevan

@sj11105 we can make button take full width on smaller devices

**Comment by sj11105** [comment]
@AdityaJ2305 , okay i have made the changes, if everything else is fine, i will push the changes.

**Comment by AdityaJ2305** [comment]
>  if everything else is fine, i will push the changes.

What do you mean by "if everything else is fine" ? 🤔

**Comment by sj11105** [comment]
> > if everything else is fine, i will push the changes.
> 
> What do you mean by "if everything else is fine" ? 🤔

If there are some other changes to make to this page ?

**Comment by AdityaJ2305** [comment]
@sj11105 ohk just a heads-up you can push the changes since you already made them locally to post the image. These aren’t heavy changes otherwise, reviewers might come to the PR, see no changes (just a question), and then have to come back again to check if the updates were made correctly

It’s better to push in such cases, and reviewers will let you know if any additional changes are needed 👍

**Comment by tasnimshaji** [comment]
@sj11105 
image
Is it okay if the "edit' button overflows

**Comment by sj11105** [comment]
@tasnimshaji , I will make the required changes.

**Comment by sj11105** [comment]
@tasnimshaji can you please specify the dimensions where you encountered this  issue

**Comment by nihal467** [comment]
LGTM

**Comment by AdityaJ2305** [comment]
@sj11105 Update the title of PR to more meaningful and aligned with the changes you've made and files you've targeted

**Review by khavinshankar — APPROVED** [review]
