### PR TITLE
Fix Button Overflow and Minor Responsive Issues on Mobile View

### LINKED ISSUE #10524: Fix Button Overflow on Mobile View & Add List/Card Toggle Button in Organization Section
**Describe the bug**
On smaller screens, some buttons overflow their containers, causing layout issues. Additionally, the organization section lacks a toggle button to switch between list and card views, making it less user-friendly

**To Reproduce**

[Click here to reproduce](https://care.ohc.network/organization/f52dadb6-2740-4231-bc79-31c5e8ced210/users)

 See error

**Expected behavior**
Buttons should remain within their containers and adapt properly to different screen sizes.
The organization section should have a functional toggle button to switch between list and card views seamlessly.

**Screenshots**

1. Add card/list toggle button
[Click here to reproduce](https://care.ohc.network/organization/f52dadb6-2740-4231-bc79-31c5e8ced210/users)

Image

2. Link user button overflow on mobile screen
[Click here to reproduce](https://care.ohc.network/organization/f52dadb6-2740-4231-bc79-31c5e8ced210/users)

Image

3. signout button overflow on small screen
[Click here to reproduce](https://care.ohc.network/)

Image

4. button overflow on locations
[Click here to reproduce](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/settings/location/acdeb11a-084f-423d-8c2d-1dfb8a7bbaf4)

Image

5. Adjust the width of the questionnaire dropdown.
[Click here to reproduce](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/patient/7590e278-dff0-449c-8e7d-b68cd4923a23/encounter/1103ff2e-f352-41f5-9770-977e22f75451/questionnaire/preview_test)

Image

6. not a proper width on desktop size (pick a date button)
[Click here to reproduce](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/users/careadmin/availability?tab=exceptions&sheet=add_exception)

Image

7. correct the arrow position 
[Click here to reproduce](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/patients/verify?phone_number=%2B916354065347&year_of_birth=2005&partial_id=7590e)

Image

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [132.0.6834.111]

**Additional context**

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes

- Fixes #10524 
- Change 1
Screenshot 2025-02-10 201732

 change 2
Screenshot 2025-02-10 211452

change 3
Screenshot 2025-02-11 061315

change 4

Screenshot 2025-02-11 062612

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Introduced updated localization strings, including a new entry for full-day unavailability and differentiated questionnaire labels.
- **Style**
  - Enhanced responsive layouts for search popovers, form buttons, and availability tabs.
  - Updated headings and navigation labels to reflect the new text entries.
- **Chores**
  - Refined locale files for consistency and resolved formatting discrepancies in specific languages.

### CODE REVIEW

File: src/components/Questionnaire/QuestionnaireSearch.tsx
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireSearch.tsx:1]: The input inside the Popover Content, let's not have green focus border and all.

Take inspiration from the `ValueSetSelect` component

File: public/locale/en.json [hunk 1]
```diff
@@ -1707,6 +1708,7 @@
   "questionnaire_not_exist": "The questionnaire you tried to access does not exist.",
   "questionnaire_submission_failed": "Failed to submit questionnaire",
   "questionnaire_submitted_successfully": "Questionnaire submitted successfully",
+  "questionnaires": "Questionnaire",
```
Comment (rithviknishad) [inline public/locale/en.json]: ensure singular keys have singular values and vice versa for plural

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: public/locale/en.json [hunk 2]
```diff
@@ -2347,6 +2351,8 @@
   "yesterday": "Yesterday",
   "yet_to_be_decided": "Yet to be decided",
   "you_need_at_least_a_location_to_create_an_assest": "You need at least a location to create an assest.",
+  "your_facilities": "Your Facilities",
+  "your_organization": "Your Organizations",
```
Comment (AdityaJ2305) [inline public/locale/en.json]: >ensure singular keys have singular values and vice versa for plural

Same here

File: public/locale/en.json (hunk 1 above)
Comment (modamaan) [reply public/locale/en.json]: solved

File: public/locale/en.json (hunk 2 above)
Comment (modamaan) [reply public/locale/en.json]: 👍

File: public/locale/en.json [hunk 3]
```diff
@@ -1715,6 +1716,7 @@
   "questionnaire_not_exist": "The questionnaire you tried to access does not exist.",
   "questionnaire_submission_failed": "Failed to submit questionnaire",
   "questionnaire_submitted_successfully": "Questionnaire submitted successfully",
+  "questionnaires": "Questionnaires",
```
Comment (Jacobjeevan) [inline public/locale/en.json]: There's already a key for questionnaire; https://www.i18next.com/translation-function/plurals

Make sure to modify existing instances (including any relevant language files).

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
Let's adjust this as well 

image

**Comment by modamaan** [comment]
Screenshot 2025-02-12 213035

File: public/locale/mr.json
Comment (Jacobjeevan) [inline public/locale/mr.json:1]: Let's not add to other languages if they aren't already there. These will be added automatically.

Editing existing entries is fine.

File: src/components/Users/UserAvailabilityTab.tsx [hunk 4]
```diff
@@ -175,8 +175,8 @@ export default function UserAvailabilityTab({ userData: user }: Props) {
       />
 
       <div className="space-y-4">
-        <div className="flex items-end justify-between">
-          <div className="flex bg-gray-100 rounded-lg p-1 gap-1 max-w-min">
+        <div className="flex items-center md:items-end justify-between gap-1 md:gap-0">
```
Comment (Jacobjeevan) [inline src/components/Users/UserAvailabilityTab.tsx]: Galaxy Z-fold (344x882)

image

Comment (Jacobjeevan) [reply src/components/Users/UserAvailabilityTab.tsx]: Same for Add Exceptions button as well.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Users/UserAvailabilityTab.tsx (hunk 4 above)
Comment (modamaan) [reply src/components/Users/UserAvailabilityTab.tsx]: added

**Comment by modamaan** [comment]
Screenshot 2025-02-14 193448

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx [hunk 5]
```diff
@@ -210,8 +210,8 @@ export default function CreateScheduleExceptionSheet({
                     control={form.control}
                     name="valid_from"
                     render={({ field }) => (
-                      <FormItem>
-                        <FormLabel required>Valid From</FormLabel>
+                      <FormItem className="flex flex-col">
```
Comment (rithviknishad) [inline src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: this changes does nothing right?

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx [hunk 6]
```diff
@@ -225,8 +225,8 @@ export default function CreateScheduleExceptionSheet({
                     control={form.control}
                     name="valid_to"
                     render={({ field }) => (
-                      <FormItem>
-                        <FormLabel required>Valid Till</FormLabel>
+                      <FormItem className="flex flex-col">
```
Comment (rithviknishad) [inline src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: here as well

File: src/components/Users/UserAvailabilityTab.tsx [hunk 7]
```diff
@@ -190,6 +195,8 @@ export default function UserAvailabilityTab({ userData: user }: Props) {
               className={cn(
                 view === "exceptions" && "shadow",
                 "hover:bg-white",
+                "text-xs sm:text-sm",
+                "px-2 md:px-4",
```
Comment (rithviknishad) [inline src/components/Users/UserAvailabilityTab.tsx]: why not just put everything in just one string?

File: src/components/Users/UserAvailabilityTab.tsx [hunk 8]
```diff
@@ -175,12 +175,17 @@ export default function UserAvailabilityTab({ userData: user }: Props) {
...
+          <div className="flex bg-gray-100 rounded-lg p-0 md:p-1 gap-1 max-w-min">
             <Button
               variant={view === "schedule" ? "outline" : "ghost"}
               onClick={() => setQParams({ tab: "schedule" })}
-              className={cn(view === "schedule" && "shadow", "hover:bg-white")}
+              className={cn(
+                view === "schedule" && "shadow",
+                "hover:bg-white",
+                "text-xs sm:text-sm",
+                "px-2 md:px-4",
```
Comment (rithviknishad) [inline src/components/Users/UserAvailabilityTab.tsx]: here and other places as well

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: public/locale/ml.json [hunk 9]
```diff
@@ -1505,7 +1505,8 @@
   "quantity_approved": "അളവ് അംഗീകരിച്ചു",
   "quantity_requested": "അഭ്യർത്ഥിച്ച അളവ്",
   "quantity_required": "ആവശ്യമായ അളവ്",
-  "questionnaire": "ചോദ്യാവലി",
+  "questionnaire_one": "ചോദ്യാവലി",
+  "questionnaire_other":"ചോദ്യാവലികൾ",
```
Comment (rithviknishad) [inline public/locale/ml.json]: violates translations guidelines as mentioned in readme

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: public/locale/ml.json (hunk 9 above)
Comment (modamaan) [reply public/locale/ml.json]: updated

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]

File: public/locale/en.json [hunk 10]
```diff
@@ -1751,9 +1753,10 @@
   "quantity_approved": "Quantity Approved",
   "quantity_requested": "Quantity Requested",
   "quantity_required": "Quantity Required",
-  "questionnaire": "Questionnaire",
```
Comment (Jacobjeevan) [inline public/locale/en.json:1887]: You will need to update the existing usages to the new key accordingly.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: public/locale/en.json (hunk 10 above)
Comment (modamaan) [reply public/locale/en.json:1887]: solved

**Comment by nihal467** [comment]
@Jacobjeevan can you review this

File: public/locale/en.json [hunk 11]
```diff
@@ -2462,7 +2464,6 @@
   "valid_year_of_birth": "Please enter a valid year of birth (YYYY)",
   "value": "Value",
   "value_set": "Value Set",
-  "save_valueset":"Save ValueSet",
```
Comment (Jacobjeevan) [inline public/locale/en.json]: Why is this being removed? Hmm, coming from a merge?🧐

File: public/locale/en.json [hunk 12]
```diff
@@ -2007,8 +2009,8 @@
   "save": "Save",
   "save_and_continue": "Save and Continue",
   "save_investigation": "Save Investigation",
+  "save_valueset": "Save ValueSet",
   "saving": "Saving...",
-  "retired":"Retired",
```
Comment (Jacobjeevan) [inline public/locale/en.json]: Same here

Comment (modamaan) [reply public/locale/en.json]: @Jacobjeevan  @rithviknishad , It's not removed; it just automatically updated the position

Comment (modamaan) [reply public/locale/en.json]: solved

File: public/locale/en.json (hunk 11 above)
Comment (modamaan) [reply public/locale/en.json]: updated

**Review by Jacobjeevan — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@modamaan clear the merge conflicts

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
