### PR TITLE
fix: Add missing icons for facility & calendar in public page

### LINKED ISSUE #12285: Icons are missing for facility & calendar in public page
**Describe the bug**

When we login to the public page, the calendar and facility icons are missing in the public page logins

**To Reproduce**

1. Log in with your phone number
2. OTP : 45612
3. See error

**Expected behavior**

- [ ] The icons should be properly visible in the public page

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Tanuj1718**
## Proposed Changes

- Fixes #12285

Screenshot 2025-05-12 at 9 20 35 PM

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Updated patient navigation links to display icons using visual components instead of plain text identifiers for a more consistent and visually appealing interface.
  - Improved organization navigation by standardizing navigation item properties and enhancing icon rendering with visual components for clearer and more consistent menus.

### CODE REVIEW

File: src/components/ui/sidebar/nav-main.tsx [hunk 1]
```diff
@@ -120,7 +122,7 @@ export function NavMain({ links }: { links: NavigationLink[] }) {
                       exactActiveClass="bg-white text-green-700 shadow-sm"
                     >
                       {link.icon ? (
-                        link.icon
+                        <CareIcon icon={link.icon as IconName} />
```
Comment (rithviknishad) [inline src/components/ui/sidebar/nav-main.tsx]: let's not do type-casting!

the right solution here is to fix the root cause! we should be accepting react node instead of icon name in the list!

see what was done here: https://github.com/ohcnetwork/care_fe/commit/0c135565b93ffa8ebec3b1c2e413ce74dfe27832

this file was missed out accidentally I believe.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — CHANGES_REQUESTED** [review]
could you change this for `OrganizationLayout.tsx` as well? 🤔 

Also, re-use the types. I see duplicate type implementations for the same in that file and `org-nav.tsx` as well

**Review by rithviknishad — APPROVED** [review]
