### PR TITLE
Fixed camera is offline error in other than staging 

### LINKED ISSUE #3829: Getting error message in consultation feed, even though camera is working fine
image

this happens in production and not in staging dev camera

cc: @nihal467

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #3829 

## Proposed Changes

- Fixed camera is offline error in other than staging 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

File: src/Components/Facility/Consultations/Feed.tsx [hunk 1]
```diff
@@ -163,6 +163,7 @@ export const Feed: React.FC<IFeedProps> = ({ consultationId }) => {
     StreamStatus.Offline
   );
 
+  const middlewareHostname = cameraMiddlewareHostname;
```
Comment (gigincg) [inline src/Components/Facility/Consultations/Feed.tsx]: Do we need `middlewareHostname`? Shouldn't we be refactoring all usages for it with `cameraMiddlewareHostname`

**Review by gigincg — APPROVED** [review]
