### PR TITLE
Show all locations in CNS page by default and added a cancel button to setLoaction Modal

### LINKED ISSUE #5346: Autoselect Location for CNS Screen
Currently the CNS Screen asks the user to select a location, it should default to all locations (If Possible) Or select the first available location with beds.

### LINKED ISSUE #5351: CNS modal not closing when there is no vitals monitor present
**Describe the bug**

**To Reproduce**

1. Go to https://care.coronasafe.in/facility
2. Click onCNS of [WeCare Hospital](https://care.coronasafe.in/facility/36f4f9e7-9e37-441f-904c-89562f24163f) from list of facilities
3. Modal does not close.

**Expected behavior**
There shall be a cancel button in the modal to close it.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by patelaryan7751**
### <samp>🤖 Generated by Copilot at 095b7b2</samp>

This pull request enhances the facility CNS page by adding a location filter option and improving the UI and speed of the page components. It modifies the `FacilityCNS.tsx` file and some related components.

## Proposed Changes

- Fixes #5346
- Show all locations in CNS page by default
image
- Added a show all location button
image

- Fixes #5351 
-  Added a cancel button to setLoaction Modal
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 095b7b2</samp>

*  Add a new state variable to store the user preference for viewing all monitors or only the selected location ([link](https://github.com/coronasafe/care_fe/pull/5378/files?diff=unified&w=0#diff-ad41f23b1187ec4f7000793014b0380c568fd2951cc72df118dd990b6513d7e8R39))
*  Change the initial value of the state variable that controls the location selection modal to avoid showing it on every page load ([link](https://github.com/coronasafe/care_fe/pull/5378/files?diff=unified&w=0#diff-ad41f23b1187ec4f7000793014b0380c568fd2951cc72df118dd990b6513d7e8L48-R49))
*  Modify the page title to reflect the user preference and the selected location ([link](https://github.com/coronasafe/care_fe/pull/5378/files?diff=unified&w=0#diff-ad41f23b1187ec4f7000793014b0380c568fd2951cc72df118dd990b6513d7e8L134-R139))
*  Conditionally render the options section based on the presence of monitors and add a "Go Back" button if there are none ([link](https://github.com/coronasafe/care_fe/pull/5378/files?diff=unified&w=0#diff-ad41f23b1187ec4f7000793014b0380c568fd2951cc72df118dd990b6513d7e8L140-R190))
*  Update the pagination data to match the total count of monitors based on the user preference and the selected location ([link](https://github.com/coronasafe/care_fe/pull/5378/files?diff=unified&w=0#diff-ad41f23b1187ec4f7000793014b0380c568fd2951cc72df118dd990b6513d7e8L178-R204))
*  Simplify and enhance the location selection modal to remove unnecessary messages and add new buttons for "Show All Locations", "Confirm", and "Cancel" ([link](https://github.com/coronasafe/care_fe/pull/5378/files?diff=unified&w=0#diff-ad41f23b1187ec4f7000793014b0380c568fd2951cc72df118dd990b6513d7e8L186-R216), [link](https://github.com/coronasafe/care_fe/pull/5378/files?diff=unified&w=0#diff-ad41f23b1187ec4f7000793014b0380c568fd2951cc72df118dd990b6513d7e8L225-R266))
*  Filter the main grid of monitors based on the user preference and the selected location ([link](https://github.com/coronasafe/care_fe/pull/5378/files?diff=unified&w=0#diff-ad41f23b1187ec4f7000793014b0380c568fd2951cc72df118dd990b6513d7e8L240-R281))
*  Import the `Cancel` component from `../Common/components/ButtonV2` to use in the location selection modal ([link](https://github.com/coronasafe/care_fe/pull/5378/files?diff=unified&w=0#diff-ad41f23b1187ec4f7000793014b0380c568fd2951cc72df118dd990b6513d7e8L13-R13))

### CODE REVIEW

File: src/Components/Facility/FacilityCNS.tsx [hunk 1]
```diff
@@ -237,7 +274,11 @@ export default function FacilityCNS({ facilityId }: { facilityId: string }) {
       )}
       <div className="mt-4 grid grid-cols-1 lg:grid-cols-3 gap-1">
         {monitors
-          ?.filter((m) => m.asset.location_object.id === location?.id)
+          ?.filter((m) =>
+            defaultShowAllLocation
+              ? true
+              : m.asset.location_object.id === location?.id
+          )
```
Comment (rithviknishad) [inline src/Components/Facility/FacilityCNS.tsx]: Return monitors directly without `.filter` if `defaultShowAllLocation` so that it won't needlessly iterate.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Comment by patelaryan7751** [comment]
Hey @nihal467 I have added the location name to monitor card 
image

**Review by khavinshankar — APPROVED** [review]
