### PR TITLE
Fix : Old OTP Value Persists After Changing Phone Number in Patient Login

### LINKED ISSUE #13038: Old OTP Value Persists After Changing Phone Number in Patient Login
**Describe the bug**
When logging in as a patient, if we enter a phone number and OTP, then click "change phone number,"
 type a new number, and click "send OTP" again, the old OTP is shown in the input box.

**To Reproduce**

1. Go to 'Login Page' -> "Login as patient".
2. Enter the phone number and click sent otp and input some otp.
3. Then click on change phone number and edit the phone number and click send otp
4. See error , the previous otp is persist.

https://github.com/user-attachments/assets/1c3a1d46-9769-467f-84d2-b17f7ecd57c2

**Expected behavior**
After entering a new phone number, the otp input should be clear.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #13038
- Reset the otp state.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **Bug Fixes**
  * The OTP input field now clears automatically when changing the phone number during login, enhancing the user experience.

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
image

@Jeffrin2005 post clicking change phone number, reset the phone number field as well

**Comment by Jeffrin2005** [comment]
@nihal467 @Jacobjeevan 
Now we are clearing phone number field also .

https://github.com/user-attachments/assets/53c96b06-95cb-4953-a4eb-08691ca39f92

File: src/components/Auth/Login.tsx [hunk 1]
```diff
@@ -632,8 +632,10 @@ const Login = (props: LoginProps) => {
                               className="h-auto p-0 text-primary-600"
                               onClick={() => {
                                 setIsOtpSent(false);
+                                setOtp("");
                                 setOtpError("");
                                 setOtpValidationError("");
+                                setPhone("");
```
Comment (rithviknishad) [inline src/components/Auth/Login.tsx]: let's not clear the phone number; the most primary use case to change the phone number would be to correct the already entered phone number and not change it entirely altogether. so this would mean that user would have to type the phone number all over again instead of just correcting it.

```suggestion
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

**Review by amjithtitus09 — APPROVED** [review]
