### PR TITLE
fix:alignment issue for view details button in encounter list

### LINKED ISSUE #10971: BUG: alignment issue for view details button in encounter list
**Describe the bug**
- the "view details " button is not fixed  at the bottom, they why ,  in responsive mode , they are align  together ,(specially in tablet mode ) 

**To Reproduce**
issuse : http://localhost:4000/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/encounters

1. Go to 'facility'
2. Click on 'encounters'
3. See error

**Expected behavior**
- for every cards the alignment of that "view details" must be same " 

**Screenshots**

Image
Image

**Tablet( or min width 768 px):**

- tablet: [ipad air]

### PR DESCRIPTION
**Pull request by Vikaspal8923**
## Proposed Changes

- Fixes #10971  
- Align "View Details" button in the encounter list for widths >768px  
- Use `flex` and `flex-grow` to ensure the button stays at the bottom, aligning with other cards  
  
  ##screenshot
    -before: 
     
al1
   
  -after: 

Screenshot 2025-03-04 011811

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [X] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- **Responsive Layout:** The encounters list now displays one column on small screens, two columns on large screens, and three columns on extra-large screens.
	- **Encounter Information Display:** A new card component has been introduced to showcase detailed medical encounter data, including patient profile links, encounter dates, status badges, and priority labels with localized text, along with a link to view more details.

### CODE REVIEW

**Comment by Vikaspal8923** [comment]
@Jacobjeevan   sir , i have fix the issue . please review pr and let me know if you need anything improvement or change in this  issue

File: src/pages/Encounters/EncounterList.tsx [hunk 1]
```diff
@@ -693,7 +693,7 @@ export function EncounterList({
               {encounters.map((encounter: Encounter) => (
                 <Card
                   key={encounter.id}
-                  className="hover:shadow-lg transition-shadow group"
+                  className="hover:shadow-lg  md:flex md:flex-col  transition-shadow group"
```
Comment (rithviknishad) [inline src/pages/Encounters/EncounterList.tsx]:
```suggestion
                  className="hover:shadow-lg md:flex md:flex-col transition-shadow group"
```

File: src/pages/Encounters/EncounterList.tsx [hunk 2]
```diff
@@ -719,8 +719,8 @@ export function EncounterList({
                         format(new Date(encounter.period.start), "PPp")}
                     </CardDescription>
                   </CardHeader>
-                  <CardContent className="">
-                    <div className="flex flex-col space-y-2">
+                  <CardContent className=" md:flex-grow">
```
Comment (rithviknishad) [inline src/pages/Encounters/EncounterList.tsx]:
```suggestion
                  <CardContent className="md:flex-grow">
```

File: src/pages/Encounters/EncounterList.tsx [hunk 3]
```diff
@@ -741,17 +741,19 @@ export function EncounterList({
...
-                          className="ml-1 h-4 w-4"
-                        />
-                      </Link>
+                      <div className="">
+                        <Separator className="my-2" />
+                        <Link
+                          href={`/facility/${facilityId}/patient/${encounter.patient.id}/encounter/${encounter.id}/updates`}
+                          className="text-sm text-primary hover:underline text-right flex items-center justify-end group-hover:translate-x-1 transition-transform"
+                        >
+                          View Details
```
Comment (rithviknishad) [inline src/pages/Encounters/EncounterList.tsx]: to checkout the readme, and kindly follow the merge checklist; translations are missing

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by Vikaspal8923** [comment]
@rithviknishad  @Jacobjeevan  i have  fix the changes requ
ested. take a look on this

File: src/pages/Encounters/EncounterList.tsx
Comment (Jacobjeevan) [inline src/pages/Encounters/EncounterList.tsx:1]: Let's modify the grid to `lg:grid-cols-2 xl:grid-cols-3`

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by Vikaspal8923** [comment]
@Jacobjeevan   I have fix the requested change and also resolve the merge conflict. tell me  is  something other needed in this issue to improve

File: src/pages/Encounters/EncounterList.tsx [hunk 4]
```diff
@@ -679,7 +679,7 @@ export function EncounterList({
         </div>
 
         <div
-          className="grid gap-4 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3"
+          className="grid gap-4 sm:grid-cols-1 xl:grid-cols-2 lg:grid-cols-3"
```
Comment (Jacobjeevan) [inline src/pages/Encounters/EncounterList.tsx]:
```suggestion
          className="grid gap-4 sm:grid-cols-1 lg:grid-cols-2 xl:grid-cols-3"
```

File: src/pages/Encounters/EncounterList.tsx [hunk 5]
```diff
@@ -719,8 +719,8 @@ export function EncounterList({
                         format(new Date(encounter.period.start), "PPp")}
                     </CardDescription>
                   </CardHeader>
-                  <CardContent className="">
-                    <div className="flex flex-col space-y-2">
+                  <CardContent className="md:flex-grow">
```
Comment (Jacobjeevan) [inline src/pages/Encounters/EncounterList.tsx]: why md? Let's just have 
```suggestion
                  <CardContent className="flex-grow">
```

File: src/pages/Encounters/EncounterList.tsx [hunk 6]
```diff
@@ -719,8 +719,8 @@ export function EncounterList({
...
+                    <div className="flex flex-col md:justify-between md:h-full space-y-2">
```
Comment (Jacobjeevan) [inline src/pages/Encounters/EncounterList.tsx]: why md 🤔  h-full might be unnecessary here.

File: src/pages/Encounters/EncounterList.tsx [hunk 7]
```diff
@@ -741,17 +741,20 @@ export function EncounterList({
...
-                        className="text-sm text-primary hover:underline text-right flex items-center justify-end group-hover:translate-x-1 transition-transform"
-                      >
-                        View Details
-                        <CareIcon
-                          icon="l-arrow-right"
-                          className="ml-1 h-4 w-4"
-                        />
-                      </Link>
+
+                      <div className="">
```
Comment (Jacobjeevan) [inline src/pages/Encounters/EncounterList.tsx]: let's remove the className here.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Encounters/EncounterList.tsx (hunk 6 above)
Comment (Vikaspal8923) [reply src/pages/Encounters/EncounterList.tsx]: sir , i used h-full to ensure that this `<div className="flex flex-col md:justify-between md:h-full space-y-2">` take up full height of its parent which prevent inconsistencies in alignment between cards. if  h-full is not used then, if one card has more content than another, the "View Details" button in cards with less content appears slightly higher, breaking uniformity.

Comment (Jacobjeevan) [reply src/pages/Encounters/EncounterList.tsx]: Ok, @Vikaspal8923 Fix the merge conflict 👍

**Review by Jacobjeevan — APPROVED** [review]

**Comment by Vikaspal8923** [comment]
@rithviknishad  please review it and tell me if i have to need change something in this.

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
