### PR TITLE
Removed actions prop from PatientHeader and moved closer to the component

### LINKED ISSUE #14769: Remove actions from PatientHeader and move it closer to the component
**Describe the bug**
Currently, the actions prop is passing too much code into the PatientHeader component, which is bad practice. This code should be moved closer to the PatientHeader component.

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Sreyas62**
## Proposed Changes

Fixes #14769 
- Removed actions prop completely from PatientHeader component
- Added wrapping card component to the AccountShow and EncounterShow components
- Aligned the styling accordingly

image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Refactor**
  * Restructured header areas to use a card-based layout across patient, encounter, and account pages for improved visual grouping.
  * Moved action controls into the new card headers (right-aligned), improving responsive behavior and spacing on mobile and desktop.
  * Removed inline action UI from the patient header—header now shows core info only.
  * Minor button label and icon sizing adjustments to align with the updated layouts.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/components/Patient/PatientHeader.tsx [hunk 1]
```diff
@@ -31,7 +25,7 @@ export function PatientHeader({
   return (
     <Card
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientHeader.tsx]: we can just change this to div

**Review by NikhilA8606 — APPROVED** [review]

**Review by nihal467 — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
