### PR TITLE
Fix condition check for boolean questions in questionnaire

### LINKED ISSUE #12176: Conditions are not working for Boolean type questions on Questionnaire
**Describe the bug**
When trying to apply the condition on a Boolean question on questionnaire, its not working.
the scenario is : 
question 1 - Was the consultation Scheduled easily? 
Ans : Yes/No (Boolean)
question  2: If No please specify the reason ( need to enalbe the condition)
Ans : free text box

**To Reproduce**

1. Login on CARE as admin
2. Go to Questionnaire editor section on admin dashboard
3. Create a new questionnaire and add the above mentioned first question as a boolean type
4. Add another question as " If No please specify the reason" and enable  the conditon ( to show the text box if the user select the NO option. )
5. Go to the  patient file and select the questionnarie 
6. update the question with the No option.
7. See the error 
**Expected behavior**
Enabled conditions must be working on the questionnaires
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by siva222003**
## Proposed Changes

- Fixes #12176 
- Normalized boolean values to ensure correct condition checks in `enableWhen` logic.
- Modified the `null` check for the question responses

[Screencast from 2025-05-20 17-38-09.webm](https://github.com/user-attachments/assets/2153f82a-7970-4517-a511-5e74b07cf881)

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved handling of dependent responses in questionnaires, ensuring questions are enabled or disabled more accurately based on previous answers, especially for boolean values.

### CODE REVIEW

File: src/components/Questionnaire/QuestionTypes/QuestionGroup.tsx [hunk 1]
```diff
@@ -43,15 +43,25 @@ function isQuestionEnabled(
     )?.values[0];
 
     // Early return if no dependent value exists
-    if (!dependentValue?.value) return false;
+    if (dependentValue?.value == null) return false;
+
+    function normalizeValue(value: unknown): unknown {
+      if (typeof value === "boolean") {
+        return value ? "Yes" : "No";
+      }
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionTypes/QuestionGroup.tsx:51]: We will need to add a check for number and convert into to string since equals below is doing a comparison against string.

Other value types should be fine, but can you do a check for different question types and ensure they are working with different conditions?

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/QuestionTypes/QuestionGroup.tsx (hunk 1 above)
Comment (siva222003) [reply src/components/Questionnaire/QuestionTypes/QuestionGroup.tsx:51]: Yeah, will add a check for number also. But it also won't work for the boolean types right?

Comment (siva222003) [reply src/components/Questionnaire/QuestionTypes/QuestionGroup.tsx:51]: @Jacobjeevan Added the check for number types also, and checked other conditions. They are working fine!

Please confirm the above one,as for the boolean type questions booleans values are being compared against string

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM, except boolean condition, its a know issue in the backend @vigneshhari have been informed
