### PR TITLE
Fix: FacilityData not populating on Edit 

### LINKED ISSUE #10073: Facility data not updating automatically after editing
## Description

The facility data is not reflecting updated information after editing. The user is required to manually refresh the page to see the updated data, which disrupts the expected seamless experience.

## Expected Behaviour

After editing the facility, the updated data should automatically reflect in the UI without requiring a page refresh.

## Steps to Reproduce: 

- Open a facility in the application.
- Edit the facility details and save the changes.
- Observe that the changes do not reflect immediately.
- Refresh the page to see the updated data.

## Additional Information:

https://github.com/user-attachments/assets/c939ac6d-e959-4c87-93d8-72a0aab0d37f

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #10073 
- Change 1
- Change 2
- More?

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x]  Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced query management for facility data using React Query's `useQueryClient` hook.
	- Improved data synchronization mechanism for facility-related operations.
	- Added extra query invalidation for facility updates to ensure data consistency.

- **Bug Fixes**
	- Removed unnecessary query invalidation in the facility editing process for simplification.

- **Chores**
	- Standardized localization keys for cover image notifications to improve consistency and readability.

### CODE REVIEW

**Comment by AdityaJ2305** [comment]
Hey Team, Don't you think we should show `Upload Cover Photo` when there is no image present. Just a typo addition. LMK

File: src/pages/Organization/components/EditFacilitySheet.tsx [hunk 1]
```diff
@@ -37,7 +37,7 @@ export default function EditFacilitySheet({ facilityId, trigger }: Props) {
             onSubmitSuccess={() => {
               setOpen(false);
               queryClient.invalidateQueries({
-                queryKey: [["facility", facilityId], "organizationFacilities"],
+                queryKey: ["facility", facilityId],
               });
             }}
```
Comment (rajku-dev) [inline src/pages/Organization/components/EditFacilitySheet.tsx]: @AdityaJ2305 you don't need to drop invalidating the second query,
changes only need to be made in this file to solve the issue,
just invalidate the two queries separately
Refer https://tanstack.com/query/latest/docs/framework/react/guides/invalidations-from-mutations

Comment (AdityaJ2305) [reply src/pages/Organization/components/EditFacilitySheet.tsx:42]: It is working fine with it. I have checked it for the orgFacilities 😊

File: public/locale/en.json [hunk 2]
```diff
@@ -675,8 +675,8 @@
   "copying_is_not_allowed": "Copying is not allowed",
   "could_not_load_page": "We are facing some difficulties showing the Page you were looking for. Our Engineers have been notified and we'll make sure that this is resolved on the fly!",
   "countries_travelled": "Countries travelled",
-  "cover_image_deleted.": "Cover image deleted.",
-  "cover_image_updated.": "Cover image updated.",
+  "cover_image_deleted": "Cover Image Deleted",
+  "cover_image_updated": "Cover Image Updated",
```
Comment (rithviknishad) [inline public/locale/en.json:679]: nice find, how did this even end up here 🤣

**Review by rithviknishad — APPROVED** [review]
