### PR TITLE
fix: Organization Users page needs responsiveness

### LINKED ISSUE #10405: Mobile View UI: Organization Users page needs responsiveness
**Describe the bug**
Container is overflowing in users page.

**To Reproduce**

1. Go to [https://care.ohc.network/organization/f52dadb6-2740-4231-bc79-31c5e8ced210/users](url)
2. Check for responsiveness
3. See error

**Expected behavior**
There should be proper responsiveness in users page

**Screenshots**

Image

**Desktop:**

- OS: [MacOS]
- Browser [Chrome]

### LINKED ISSUE #10429: Mobile View UI: Edit User Page of Organization Users needs responsiveness
**Describe the bug**
Edit user page needs responsiveness as the username it overlapping.

**To Reproduce**

1. Go to [https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/settings/departments/85a2a34f-ec1d-411f-b081-9c97826f11b3/users](url)
2. Check for responsiveness.

**Expected behavior**
There should be proper responsiveness or we can apply restriction on username ( like max characters )

**Screenshots**

Image

**Desktop:**

- OS: [MacOS]
- Browser [Chrome]

### PR DESCRIPTION
**Pull request by Tanuj1718**
## Proposed Changes

- Fixes #10405 #10429

Before Update:
Screenshot 2025-02-05 at 12 42 02 PM

After Update:
Screenshot 2025-02-05 at 1 37 22 PM

**EDIT 1:**  Color of Link User button changed. Now it is same as earlier.
**EDIT 2:**  Fixes #10429

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style**
	- Updated layouts and component spacing for improved responsiveness, including flex and grid adjustments.
	- Refreshed button appearances and enhanced text truncation to better handle variable content.
- **Refactor**
	- Reorganized the arrangement of user information for a more fluid and consistent display.

These visual enhancements provide a cleaner, more adaptive experience without altering any underlying functionality.

### CODE REVIEW

**Comment by Jacobjeevan** [comment]
Include #10429 as well 👍

File: src/pages/Facility/settings/locations/LocationView.tsx
Comment (Jacobjeevan) [inline src/pages/Facility/settings/locations/LocationView.tsx:1]: Changes not relevant to the PR; remove.

File: src/pages/Facility/settings/organizations/components/EditFacilityUserRoleSheet.tsx [hunk 1]
```diff
@@ -155,18 +155,22 @@ export default function EditUserRoleSheet({
               </div>
             </div>
 
-            <div className="grid grid-cols-2 gap-4 pt-2 border-t">
-              <div>
-                <span className="text-sm text-gray-500">{t("username")}</span>
-                <p className="text-sm font-medium">{userRole.user.username}</p>
+            <div className="flex flex-col flex-wrap gap-2 pt-2 border-t">
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/components/EditFacilityUserRoleSheet.tsx:160]: image

Let's add truncate and tooltip for usernames (refer to other examples in codebase).

File: src/pages/Organization/OrganizationUsers.tsx
Comment (Jacobjeevan) [inline src/pages/Organization/OrganizationUsers.tsx:1]: image

Check multiple devices.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by Jacobjeevan** [comment]
> Include #10429 as well 👍

Add this issue number in the description as well.

File: src/pages/Organization/components/LinkUserSheet.tsx
Comment (Jacobjeevan) [inline src/pages/Organization/components/LinkUserSheet.tsx:1]: image


Let's add tooltip and truncate for this as well (TooltipComponent).

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
In OrganizationUsers:

image

Adjust for iPad; make sure to check other devices as well, for any changes you make.

Ensure more details button remains at the bottom

image

Seems to be fine for FacilityOrganizationUsers, so check against that.

File: src/pages/Organization/components/LinkUserSheet.tsx [hunk 2]
```diff
@@ -192,15 +193,16 @@ export default function LinkUserSheet({
...
-
-              <Button
-                className="w-full"
-                onClick={handleAddUser}
-                disabled={!selectedRole}
-                data-cy="link-user-button"
-              >
-                Link to Organization
-              </Button>
+              <TooltipComponent content="Click here to link the user to the organization">
```
Comment (Jacobjeevan) [inline src/pages/Organization/components/LinkUserSheet.tsx]: 🤔 We don't need to add tooltip for the button

File: src/pages/Organization/components/LinkUserSheet.tsx [hunk 3]
```diff
@@ -135,7 +136,7 @@ export default function LinkUserSheet({
           {selectedUser && (
             <div className="space-y-4">
               <div className="rounded-lg border p-4 space-y-4">
-                <div className="flex items-start gap-4">
+                <div className="flex items-start gap-4 truncate border-t">
```
Comment (Jacobjeevan) [inline src/pages/Organization/components/LinkUserSheet.tsx]: why was this border added, plus truncate shouldn't be added to the div anyways.

Test before requesting review:

image

File: src/components/Common/UserSelector.tsx
Comment (Jacobjeevan) [inline src/components/Common/UserSelector.tsx:1]: Let's remove the changes in this file, as it's being addressed elsewhere.

File: src/pages/Facility/settings/organizations/components/LinkFacilityUserSheet.tsx
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/components/LinkFacilityUserSheet.tsx:1]: image

We are just clipping it off - does this look right? Compare to the other choices:

image

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
Make changes, self-review and test before requesting review again.

File: src/pages/Organization/components/LinkUserSheet.tsx (hunk 3 above)
Comment (Tanuj1718) [reply src/pages/Organization/components/LinkUserSheet.tsx]: Oh sorry for this. I had added truncate to the div which has width defined. I did not focus that no width is defined here. It was clipping the text, so I thought it is working.🥲

File: src/pages/Facility/settings/organizations/components/LinkFacilityUserSheet.tsx [hunk 4]
```diff
@@ -136,13 +136,13 @@ export default function LinkFacilityUserSheet({
           {selectedUser && (
             <div className="space-y-4">
               <div className="rounded-lg border p-4 space-y-4">
-                <div className="flex items-start gap-4">
+                <div className="flex flex-wrap items-start gap-4">
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/components/LinkFacilityUserSheet.tsx]: Don't add flex-wrap here.

image


We need the avatar and name to both be in the same row, truncate the name accordingly.

Refer to https://css-tricks.com/snippets/css/a-guide-to-flexbox/ for flex grow properties

Comment (Jacobjeevan) [reply src/pages/Facility/settings/organizations/components/LinkFacilityUserSheet.tsx]: image

It sort of works for LinkUserSheet (that need to be adjusted as well).

You can probably use flex's grow properties so that Avatar is the correct size.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/organizations/components/LinkFacilityUserSheet.tsx (hunk 4 above)
Comment (Tanuj1718) [reply src/pages/Facility/settings/organizations/components/LinkFacilityUserSheet.tsx]: I had fixed it in LinkUserSheet and the same is needed in LinkFacilityUserSheet. So I just copy it. Also I have done the adjustment with aligning items to the center. Seems fine?🤔

**Comment by nihal467** [comment]
@Tanuj1718 what is the status of the PR

**Comment by Tanuj1718** [comment]
> @Tanuj1718 what is the status of the PR

@nihal467  It is ready for review

**Comment by nihal467** [comment]
LGTM

**Review by Jacobjeevan — APPROVED** [review]
