### PR TITLE
Device Info Page: expand option for notes and disable update/save button until valid input

### LINKED ISSUE #11836: Add tooltip and disable buttons in Service History section of Devices
**Describe the bug**
1. The content in notes column of Service History is truncated. We can use Tooltip component for better UX.
2. Update button is enable when there is no change in Service record.
3. Save button is enable when there is no description in Add Service Record sheet

**To Reproduce**

1. Go to [link](https://care.ohc.network/facility/0eea83cf-0ac3-4d6b-a659-dc23c5f66fd9/settings/devices/10f679a1-5f48-4e00-9fdc-fa9b1c1aab54)
2. Check the above mentions errors

**Expected behavior**
Use tooltip for notes column
Disable Update button when there is no change in service record
Disable Save button when the description in empty.

**Screenshots**

https://github.com/user-attachments/assets/509a0788-db33-4fd8-8a92-e0c28674cbe2

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by abeeto**
## Proposed Changes

- Fixes #11836 
- Wrote a new file/component, `ClampableText.tsx` so that truncated text can be collapsible/expanded - it uses `line-clamp` and a useEffect where it calculates whether or not to show the expand/hide button on rescale
- Wrote a useMemo in `ServiceHistoryForm.tsx` so that when editing existing records: 
  - Update button is enabled only when the fields are not empty and a change has been made to original values (useWatch hook)
  - Save Button is enabled only when the fields are not empty

https://github.com/user-attachments/assets/1979709e-0330-44d2-94b7-b83607f9a735

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [X] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
	- Added expandable text functionality to service notes in the device service history, allowing users to expand and collapse long notes for easier reading.
- **User Interface**
	- Updated the service history table to display notes with an expandable "Read more" option.
	- Submit button in the service history form is now disabled unless there are unsaved changes.
- **Localization**
	- Added a new "Read more" label for expandable text support.

### CODE REVIEW

**Comment by nihal467** [comment]
image

- expand or tooltip is missing for truncated note as per issue

**Comment by abeeto** [comment]
> image
> 
> * expand or tooltip is missing for truncated note as per issue

Hi, @nihal467 
The expand was missing because of changes to the component, `TableCell` (which were pulled from the latest merge of develop branch). TableCell got a `whitespace-nowrap` class added which is why my code was no longer working, as I have a useEffect that needs to check if text in the child component is wrapping in order to render the expand.

Added a quick fix by just overriding the class to  `whitespace-normal`  for this particular `TableCell` element.
Please have a look now, should work!

File: src/pages/Facility/settings/devices/components/ServiceHistoryForm.tsx [hunk 1]
```diff
@@ -182,7 +196,11 @@ export default function ServiceHistoryForm({
           )}
         />
         <div className="flex justify-end space-x-2 pt-4">
-          <Button type="submit" disabled={isPending} data-cy="submit-button">
+          <Button
+            type="submit"
+            disabled={isFormNotReady || isPending}
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/devices/components/ServiceHistoryForm.tsx]: let's not over-complicate this, use !form.formState.isDirty instead.

File: src/pages/Facility/settings/devices/components/ClampableText.tsx
Comment (Jacobjeevan) [inline src/pages/Facility/settings/devices/components/ClampableText.tsx:1]: While this is nice, I'm not sure if we need this here, rather than just displaying the full text 🤔  

I'll wait on Nihal to add his feedback.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/devices/components/ClampableText.tsx [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+  toggleTextBtnClassName = "px-0 hover:cursor-pointer text-primary-600",
+}) => {
+  const [isClamped, setIsClamped] = useState(true);
+  const [showToggleButton, setShowToggleButton] = useState(true);
+  const [textExpanded, setTextExpanded] = useState(false);
+
+  const textContainerRef = useRef<HTMLDivElement>(null);
+  const resizeObserverRef = useRef<ResizeObserver | null>(null);
+
+  useEffect(() => {
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/devices/components/ClampableText.tsx]: Also no need to over-engineer this 😅  Let's keep it simple, let tailwind handle the truncation, rather than using these refs.

Edit: also check behavior when you save an existing long note into a shorter one.

Comment (abeeto) [reply src/pages/Facility/settings/devices/components/ClampableText.tsx]: Hi, I used the refs as a way to tell React to render the expand button only when there's multiple lines. Not sure how to do this without refs tbh.. since the truncate/line-clamp tailwind class is still applied to all text elements

Either way, if we want to show the full message from the start, I can just remove this component/file altogether 👍

File: src/pages/Facility/settings/devices/components/ServiceHistoryForm.tsx (hunk 1 above)
Comment (abeeto) [reply src/pages/Facility/settings/devices/components/ServiceHistoryForm.tsx]: Didn't know about this; very cool! Added.

**Review by Jacobjeevan — APPROVED** [review]
I've simplified the logic a bit. There's an edge case - if user has expanded the text and then shortens it, hide text will be visible even though it wouldn't be applicable anymore. If the user clicks it, it disappears.

File: src/pages/Facility/settings/devices/components/ClampableText.tsx [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+    if (textRef.current) {
+      const isOverflowing =
+        textRef.current.scrollHeight > textRef.current.clientHeight;
+      setHasOverflow(isOverflowing);
+    }
+  }, [text, textRef]);
+
+  return (
+    <div className={`clampable-text-wrapper ${className}`}>
```
Comment (rithviknishad) [inline src/pages/Facility/settings/devices/components/ClampableText.tsx]: does `clampable-text-wrapper` classname do anything? 🤔

Comment (abeeto) [reply src/pages/Facility/settings/devices/components/ClampableText.tsx]: No it doesn't do anything. Removed.

File: src/pages/Facility/settings/devices/components/ClampableText.tsx [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+      setHasOverflow(isOverflowing);
+    }
+  }, [text, textRef]);
+
+  return (
+    <div className={`${className}`}>
+      <div
+        ref={textRef}
+        className={!isExpanded ? `line-clamp-${linesToClamp}` : ""}
+      >
```
Comment (rithviknishad) [inline src/pages/Facility/settings/devices/components/ClampableText.tsx]: tailwind will not be able to compile this class!

https://tailwindcss.com/docs/detecting-classes-in-source-files#dynamic-class-names

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/devices/components/ClampableText.tsx (hunk 4 above)
Comment (abeeto) [reply src/pages/Facility/settings/devices/components/ClampableText.tsx]: I mapped the linesToClamp prop to a static class name instead as suggested in the link

**Comment by abeeto** [comment]
@Jacobjeevan 
The simplifying changes made in [7696762](https://github.com/ohcnetwork/care_fe/pull/11868/commits/769676202cbf73914adfce5f553cb62ac1c210cb) means that when we resize the web browser window to a smaller width, the expand button will no longer show up. So if a text was able to be displayed on one line originally but then overflows when it's been resized, the button won't show up (like it used to)

**Comment by rithviknishad** [comment]
@abeeto I've cleaned up things quite a lot. Followed composable component pattern and avoided all those hacks to make tailwind work! The current one is a very clean approach on solving this!

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image

- now the readmore is shown for all text even for ever small test

**Comment by yash-learner** [comment]
Question:

Why don't we have a `Read less` button after expanding, is it a deliberate decision?

**Comment by rithviknishad** [comment]
> Question:
> 
> Why don't we have a `Read less` button after expanding, is it a deliberate decision?

Yes! Why do we need read less :) I don't see any use case

**Comment by nihal467** [comment]
LGTM
