### PR TITLE
fix:Scrolling issue in Facility Features Dropdown in Mobile View

### LINKED ISSUE #11213: Facility Features Dropdown Lacks Scrolling in Mobile View
**Describe the bug**

In the mobile view, the facility features dropdown does not have a scrollbar, preventing users from scrolling through the entire list.

**To Reproduce**

1. Go to kerala organisation
2. Click on facility and open create facility form
3. scroll through the facility features

device : iPhone 14 pro

**Expected behavior**

A scrollbar should be added to the facility features dropdown in mobile view, allowing users to navigate through the entire list.

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by ashwinpraveengo**
## Proposed Changes

- Fixes #11213 
- Added `onTouchStart` and `onTouchMove` event handlers to `PopoverContent` and `CommandList` to stop event propagation, preventing hover effects from interfering with scrolling.
- Added a ref to `CommandList` for potential future scroll position management. 

@ohcnetwork/care-fe-code-reviewers

https://github.com/user-attachments/assets/38ef6b2a-59af-44fd-9145-d3dc26033c68

https://github.com/user-attachments/assets/1433dada-1794-4a08-905b-816515c2113c

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
	- Improved touch responsiveness in the multi-select component to provide a smoother user experience on touch devices. 
	- Enhanced styling for the command list within the multi-select component.

### CODE REVIEW

File: src/components/ui/multi-select.tsx [hunk 1]
```diff
@@ -56,6 +56,8 @@ export const MultiSelect = React.forwardRef<
   ) => {
     const [selectedValues, setSelectedValues] = React.useState<string[]>(value);
     const [isPopoverOpen, setIsPopoverOpen] = React.useState(false);
+    const commandListRef = React.useRef<HTMLDivElement>(null);
+
```
Comment (rithviknishad) [inline src/components/ui/multi-select.tsx]: i don't see any reason for this ref. it's not even used anywhere

**Review by rithviknishad — DISMISSED** [review]

File: src/components/ui/multi-select.tsx (hunk 1 above)
Comment (ashwinpraveengo) [reply src/components/ui/multi-select.tsx]: Ya will remove it..

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
