### PR TITLE
fix: prevent success message on consent form when file upload fails

### LINKED ISSUE #14951: Bug: Consent form displays success message despite file upload failure
**Describe the bug**

When creating or updating a consent with file attachments, if the file upload fails, the form still shows a success message and closes the dialog. The `handleFileUpload` function in `useFileUpload` hook doesn't throw an error or reject the promise when file uploads fail, so the consent form's `try-catch` block never catches the failure and proceeds to show success.

**To Reproduce**

1. Go to a patient's encounter page
2. Click on the consent form dialog
3. Fill in the consent details
4. Add one or more files to upload
5. Submit the form
6. Simulate a file upload failure (e.g., set network to "Offline" in DevTools, or block the upload endpoint)
7. Observe that no error is thrown, and the form shows success even though files weren't uploaded

**Screenshots**

https://github.com/user-attachments/assets/dfa020a0-c431-4e43-92a8-b944ab9592c0

**Expected behavior**

If file upload fails:
- `handleFileUpload` should throw an error or reject the promise
- The error should be caught in the consent form's `try-catch` block
- Show an error message about the upload failure
- Keep the dialog open so the user can retry or cancel
- Do not show a success message
- Do not close the dialog

The success message and dialog closure should only occur when both the consent creation/update and file uploads succeed.

**Desktop:**

- OS: macOS
- Browser: Chrome
- Version: Latest

**Smartphone:**

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

**Additional context**

- Root cause: `src/hooks/useFileUpload.tsx` - `handleUpload` function (lines 248-317) catches file upload errors but doesn't throw/reject, so the promise resolves successfully even when files fail
- Secondary issue: `src/components/Consent/ConsentFormSheet.tsx` - `handleSuccess` function (lines 172-199) doesn't verify if file upload actually succeeded
- Impact: Users may think files were uploaded when they weren't, leading to incomplete consent records
- Workaround: None currently; users must check manually if files were uploaded

### PR DESCRIPTION
**Pull request by harsh04044**
## Proposed Changes

Fixes #14951

This PR fixes a bug where the consent form would display a success message even when file uploads failed. Previously, if file uploads encountered network errors or other failures, the form would still proceed to show the success toast and close the dialog, misleading users into thinking their consent was created successfully.

**Changes made:**
- Modified `useFileUpload` hook to throw an error when any file upload fails, ensuring the error propagates to the calling component
- Updated `ConsentFormSheet` to catch upload errors and display an appropriate error toast
- Added early return in `ConsentFormSheet` to prevent the success message from showing when file upload fails
- Files are now only cleared on successful upload, allowing users to retry failed uploads

**Behavior after fix:**

https://github.com/user-attachments/assets/de4794a3-3a75-42ed-b5b2-06085abfe855

- When file upload fails, users see an error toast notification
- The consent form dialog remains open, allowing users to retry the upload
- Success message only appears when both consent creation and file upload succeed
- Failed files remain in the upload queue for retry

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **New Features**
  * Attachment list now displays a status badge showing "uploaded" or "file_upload_error" per file.

* **Bug Fixes**
  * Upload handling now clearly separates success and failure flows.
  * Failed uploads preserve failed-file state and show errors; successful uploads clear files.
  * Camera modal reliably closes after upload results; spurious success actions on failure are prevented.

### CODE REVIEW

**Comment by Ishu813** [comment]
@harsh04044 I think it would be better to show a custom, user-friendly error message when the upload fails, instead of relying on the system-generated error. This would improve UX and keep the error handling consistent with the rest of the app.

**Comment by parvathyns-creator** [comment]
@nihal467 This looks fine to me

**Comment by harsh04044** [comment]
> @harsh04044 I think it would be better to show a custom, user-friendly error message when the upload fails, instead of relying on the system-generated error. This would improve UX and keep the error handling consistent with the rest of the app.

yes it can be done waiting for other reviewers

File: src/hooks/useFileUpload.tsx [hunk 1]
```diff
@@ -304,15 +304,24 @@ export default function useFileUpload(
...
     }
 
     setUploading(false);
-    setFiles(errors);
-    setUploadFileNames(errors?.map((f) => f.name) ?? []);
-    setError(t("file_error__network"));
+
+    // If any files failed to upload, throw an error
+    if (errors.length > 0) {
+      setFiles(errors);
```
Comment (AdityaJ2305) [inline src/hooks/useFileUpload.tsx:316]:
```
      setFiles(errors);
```

I think this should have a more meaningful name that aligns with the action it performs.

File: src/hooks/useFileUpload.tsx [hunk 2]
```diff
@@ -304,15 +304,24 @@ export default function useFileUpload(
         if (data) {
           await uploadfile(data, file);
         }
-      } catch {
+      } catch (_error) {
```
Comment (AdityaJ2305) [inline src/hooks/useFileUpload.tsx:307]:
```suggestion
      } catch {
```

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

File: src/hooks/useFileUpload.tsx (hunk 1 above)
Comment (harsh04044) [reply src/hooks/useFileUpload.tsx:316]: > ```
>       setFiles(errors);
> ```
> 
> I think this should have a more meaningful name that aligns with the action it performs.

@AdityaJ2305 
Since setFiles is a React state setter, we can't rename it. 
Am i right or  you r suggesting something else(like renaming the variable errors to something more descriptive (e.g., failedFiles) )?

Comment (AdityaJ2305) [reply src/hooks/useFileUpload.tsx:316]: >you r suggesting something else(like renaming the variable errors to something more descriptive (e.g., failedFiles) )?

yes

**Review by nihal467 — APPROVED** [review]

File: src/hooks/useFileUpload.tsx [hunk 3]
```diff
@@ -304,15 +304,24 @@ export default function useFileUpload(
...
-    setUploadFileNames(errors?.map((f) => f.name) ?? []);
-    setError(t("file_error__network"));
+
+    // If any files failed to upload, throw an error
+    if (errors.length > 0) {
+      setFiles(errors);
+      setUploadFileNames(errors?.map((f) => f.name) ?? []);
+      setError(t("file_error__network"));
+      setCameraModalOpen(false);
+      throw new Error(t("file_error__network"));
```
Comment (Jacobjeevan) [inline src/hooks/useFileUpload.tsx]: let's not throw an error, issue with this is sheet remains open which can be confusing to the user since consent is created.

File: src/components/Consent/ConsentFormSheet.tsx [hunk 4]
```diff
@@ -175,6 +175,8 @@ export default function ConsentFormSheet({
         await fileUpload.handleFileUpload(consentId);
       } catch (_error) {
         toast.error(t("error_uploading_files"));
+        // Don't proceed with success flow if file upload failed
```
Comment (Jacobjeevan) [inline src/components/Consent/ConsentFormSheet.tsx]: we can remove the try/catch and just proceed with rest of the code. Let it notify user that consent is created successfully. On network errors, toast will be shown anyways.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
We can instead display a badge in ConsentDetail page (upload_completed attribute coming from FileReadMinimal in available for source_attachments).

**Comment by harsh04044** [comment]
Screenshot 2026-01-14 at 7 22 10 PM


@Jacobjeevan  i have addressed your suggestion.

**Review by Jacobjeevan — APPROVED** [review]

**Review by nihal467 — APPROVED** [review]
