### PR TITLE
Removed the questionnaire print button from the treatment summary page

### LINKED ISSUE #11843: Remove the questionnaire print button in the treatment summary of a patient
**Describe the bug**

We're having the unintentional questionnaire print button in the treatment summary

**To Reproduce**

**Expected behavior**

- remove the questionnaire print button in the treatment summary

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by karanziie1990**
## Related Issue

Fixes #11843 

## Type of change

-  Added conditional rendering for the questionnaire print button so that it no longer appears when the current route corresponds to `facility/..../encouter/.../treatment_summary`.

## Screenshots

Print button is visible on other pages:
Screenshot from 2025-04-11 20-18-19

Hidden on the Treatment Summary page:
Screenshot from 2025-04-11 20-18-40

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Enhanced the response view by conditionally displaying the dropdown menu. The menu is now hidden in print preview mode, ensuring a cleaner and more focused layout.
  - These changes improve the user interface by adapting to the context, reducing visual clutter, and providing a more intuitive interaction when reviewing responses.

### CODE REVIEW

File: src/components/Facility/ConsultationDetails/QuestionnaireResponsesList.tsx [hunk 1]
```diff
@@ -237,7 +237,8 @@ function ResponseCard({
   isPrintPreview?: boolean;
 }) {
   const { t } = useTranslation();
-
+  const path = usePath() || "";
+  const isTreatmentSummaryRoute = path?.includes("/treatment_summary");
```
Comment (khavinshankar) [inline src/components/Facility/ConsultationDetails/QuestionnaireResponsesList.tsx]: This approach of using path to render is not scalable, using a prop would be ideal. In this case we already have prop, isPrintPreview, so we don't have to show a print button when it already is a print preview

**Review by khavinshankar — CHANGES_REQUESTED** [review]

**Comment by khavinshankar** [comment]
@karanziie1990 As this is a priority PR, I'll make the changes required, please feel free to explore and pick up new issues.

cc: @nihal467

**Review by khavinshankar — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
