### PR TITLE
FIXED: Disable Reschedule Button When Appointment Status Is 'In Consultation

### LINKED ISSUE #12135: Disable Reschedule Button When Appointment Status Is 'In Consultation
**Describe the bug**
Reschedule button is still active when the appointment status is "In Consultation", causing users to wrongly modify ongoing appointments.

**To Reproduce**

1. login as patient
2. take "in-consultation" status appointment

**Expected behavior**
Reschedule button should be disabled when the appointment status is "In Consultation" to prevent changes.

**Screenshots**

https://github.com/user-attachments/assets/858e3063-70f6-4351-99ce-7ef16c864de7

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes
disbled attribute added

- Fixes #12135 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
  - Disabled and hid the "Reschedule" and "Cancel Appointment" buttons during active consultations to prevent changes.
  - Prevented rescheduling and cancellation actions while an appointment is in consultation.
  - Hid the primary action button in appointment scheduling during ongoing consultations to avoid conflicts.

### CODE REVIEW

**Comment by modamaan** [comment]
which is better ?

Screenshot 2025-04-29 153650

**Comment by modamaan** [comment]
Screenshot 2025-04-29 153812

**Review by rithviknishad — CHANGES_REQUESTED** [review]
is this the only place in care where appointments can be rescheduled? 🤔

**Comment by modamaan** [comment]
Screenshot 2025-05-01 005610

**Comment by modamaan** [comment]
Screenshot 2025-05-01 005435

**Comment by modamaan** [comment]
@rithviknishad what about cancel appointment,  should I disable that also

**Review by Jacobjeevan — COMMENTED** [review]
Hmm, reschedule and cancel buttons should be disabled for all 4 of the final statuses as well 🤔  (AppointmentFinalStatuses), no? @rithviknishad 

- fulfilled
- cancelled (i.e. already cancelled)
- entered_in_error
- rescheduled

**Comment by modamaan** [comment]
@rithviknishad @Jacobjeevan  i have disbled `cancel_appointment` and `reschedule` buttons when appointment status `in_consultation`
any changes needed?

**Comment by rithviknishad** [comment]
marking this on hold as waiting for final confirmation

**Review by NikhilA8606 — CHANGES_REQUESTED** [review]
Can we hide the button instead of disabling, or show a tooltip stating the reason why the button is disabled so that users are aware why it’s disabled.

**Comment by modamaan** [comment]
CC @rithviknishad

**Comment by rithviknishad** [comment]
yeah @modamaan , let's do that!

File: src/pages/PublicAppointments/Schedule.tsx [hunk 1]
```diff
@@ -326,27 +326,29 @@ export function ScheduleAppointment(props: AppointmentsProps) {
...
+                disabled={isCreatingAppointment || isCancellingAppointment}
+                onClick={() => {
+                  if (appointmentId && appointment) {
+                    handleRescheduleAppointment(appointment);
+                  } else {
+                    localStorage.setItem(
+                      "selectedSlot",
+                      JSON.stringify(selectedSlot),
+                    );
+                    localStorage.setItem("reason", reason);
```
Comment (rithviknishad) [inline src/pages/PublicAppointments/Schedule.tsx:341]: although not related to the PR, we no longer need this btw. can we remove this?

cc: @Jacobjeevan

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by rithviknishad** [comment]
other than that lgtm

File: src/pages/PublicAppointments/Schedule.tsx (hunk 1 above)
Comment (modamaan) [reply src/pages/PublicAppointments/Schedule.tsx:341]: Removed

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image
image

- When we're trying to book a fresh appointment for an existing patient in a facility, after selecting the time slot, it crashes the page, since the local storage is not properly handled

Steps to replicate

1. login with +91 9855955878
2. select facility test-nihal
3. select a slot and try to select a patient
4. See the crash

**Comment by rithviknishad** [comment]
@modamaan revert the change made in the local storage for now, create a separate issue to not be dependent on local storage for things like these.

if i remember correctly, we decided not to use local storage for state management, this is bad.

**Comment by modamaan** [comment]
@rithviknishad can we use this method instead localstorage  
```
   queryClient.setQueryData(["appointment-selection"], {
      selectedSlot,
      reason,
    });
```

**Comment by rithviknishad** [comment]
NO! we do not want to store internal states that cannot be recreated when directly navigated from a URL.

Think of this way: user navigates to something directly via a URL. This would break!

Create separate issue to not use local storage for now.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
