### PR TITLE
Questionnaire List & Edit UI Redesign

### LINKED ISSUE #10602: Bug: Create Button for tag creation in questionnaire is not working
**Describe the bug**
Create Button for tag creation in questionnaire is not working.

**To Reproduce**

1. Go to [https://care.ohc.network/questionnaire/arterial_blood_gas](url)
2. Click on Manage , then click on manage tags.
3. Create a new tag

**Expected behavior**
It need scrolling as two containers are overlapping.

**Screenshots**

https://github.com/user-attachments/assets/e7985665-788f-4f2a-a1c5-1bfb3d071f6d

### LINKED ISSUE #10603: Error message should be clear
**Describe the bug**
Error is not recognisable with the error message.

**To Reproduce**

1. Go to [https://care.ohc.network/questionnaire/arterial_blood_gas](url)
2. Click on Manage, then click on clone questionnaire
3. Click on clone
4. See error message

**Expected behavior**
Error message should be: Slug should be unique

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by amjithtitus09**
- Questionnaire List & Edit UI Redesign
- Fixes https://github.com/ohcnetwork/care_fe/issues/10602
- Fixes https://github.com/ohcnetwork/care_fe/issues/10603

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Expanded localization options now enable creating, searching, and managing questionnaires with improved navigation and selection features.
	- The questionnaire editor has been enhanced with organization and tag management capabilities, along with clearer error notifications during cloning.
	- Preview mode now disables data interactions to prevent unintended actions.

- **Style**
	- Improved layouts include scrollable content areas, refined date picker behavior, and updated styling for footers and encounter notes for a cleaner, more consistent user experience.

### CODE REVIEW

**Comment by amjithtitus09** [comment]
Issue created for Questionnaire Preview Redesign https://github.com/ohcnetwork/care_fe/issues/10679

File: src/components/Questionnaire/CloneQuestionnaireSheet.tsx [hunk 1]
```diff
@@ -67,12 +68,11 @@ export default function CloneQuestionnaireSheet({
       navigate(`/admin/questionnaire/${data.slug}`);
       setOpen(false);
     },
-    onError: (error: any) => {
-      if (error.response?.status === 400) {
-        setError("This slug is already in use. Please choose a different one.");
-      } else {
-        setError("Failed to clone questionnaire. Please try again.");
-      }
+    onError: (error) => {
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/CloneQuestionnaireSheet.tsx:71]: I'd suggest keeping this as is for now...BE's error messages for this aren't clear for users 😅  I'll be modifying this slightly in #10506 

BE returns when cloning existing questionnaire with the same slug:

`Value error, Slug must be unique`
`List should have at least 1 item after validation, not 0`

File: src/components/Questionnaire/QuestionTypes/AllergyQuestion.tsx [hunk 2]
```diff
@@ -121,6 +121,7 @@ export function AllergyQuestion({
         limit: 100,
       },
     }),
+    enabled: patientId !== "preview",
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionTypes/AllergyQuestion.tsx]: can we add a previewMode prop instead? 🤔

**Comment by nihal467** [comment]
image

- [ ] keep the left side (Navigation) and right side (Questionnaire) card width static, currently its dynamic width management based on question heading text is weird

image

- [ ] add * to the organisation 
- [ ] add missing i18n translation for the place holder

**Comment by amjithtitus09** [comment]
@nihal467 Done

File: src/components/Questionnaire/QuestionnaireEditor.tsx
Comment (AdityaJ2305) [inline src/components/Questionnaire/QuestionnaireEditor.tsx:1]: @amjithtitus09, it’s not redirecting back after a successful edit. Should it?

Line 675

File: src/components/Questionnaire/CloneQuestionnaireSheet.tsx (hunk 1 above)
Comment (amjithtitus09) [reply src/components/Questionnaire/CloneQuestionnaireSheet.tsx:71]: Let's keep this for now since the current error is very generic and might not help fix the error. Organization has been made mandatory now, so the second error won't show up.

File: src/components/Questionnaire/QuestionTypes/AllergyQuestion.tsx (hunk 2 above)
Comment (amjithtitus09) [reply src/components/Questionnaire/QuestionTypes/AllergyQuestion.tsx]: Added isPreview

File: eslint.config.mjs [hunk 3]
```diff
@@ -66,15 +66,15 @@ export default [
...
+        "warn",
         {
           argsIgnorePattern: "^_",
           varsIgnorePattern: "^_",
           caughtErrorsIgnorePattern: "^_",
         },
       ],
       "@typescript-eslint/no-unused-expressions": [
-        "error",
+        "warn",
```
Comment (rithviknishad) [inline eslint.config.mjs]: let's revert this and take this separately? 

we could explore better approaches from errors getting in our way during development

doing it this way will allow anyone to check-in such issues to the repo without our CI checks from being able to reject it.

File: src/components/Questionnaire/ManageQuestionnaireTagsSheet.tsx [hunk 4]
```diff
@@ -150,133 +151,136 @@ export default function ManageQuestionnaireTagsSheet({
...
+                    t("create_tag")
+                  )}
+                </Button>
+              </CollapsibleContent>
+            </Collapsible>
+          </ScrollArea>
         </div>
 
-        <SheetFooter className="absolute bottom-0 left-0 right-0 p-4 border-t bg-background">
+        <SheetFooter className=" bottom-0 left-0 right-0 p-4 border-t bg-background">
```
Comment (rithviknishad) [inline src/components/Questionnaire/ManageQuestionnaireTagsSheet.tsx]: is this even a valid class? 🤔 

```suggestion
        <SheetFooter className="bottom-0 left-0 right-0 p-4 border-t">
```

File: src/components/ui/input.tsx [hunk 5]
```diff
@@ -13,6 +13,12 @@ const Input = React.forwardRef<HTMLInputElement, React.ComponentProps<"input">>(
         )}
         ref={ref}
         {...props}
+        onFocus={(e) => {
+          if (type === "date") {
+            e.target.showPicker();
+          }
+          props.onFocus?.(e);
+        }}
```
Comment (rithviknishad) [inline src/components/ui/input.tsx:21]: i don't think we should be modifying shadcn's input to achieve this. we could pass onFocus to the places wherever this is needed alone. Primary issue here is the picker's dropdown icon is not shown due to size restrictions right?

just adding a note, this would revert https://github.com/ohcnetwork/care_fe/issues/10303 

cc: @nihal467

Comment (amjithtitus09) [reply src/components/ui/input.tsx:21]: This would affect the date picker alone, not the time component mentioned in https://github.com/ohcnetwork/care_fe/issues/10303

File: eslint.config.mjs (hunk 3 above)
Comment (amjithtitus09) [reply eslint.config.mjs]: Yup there were commits from another PR here. Reverted

File: src/components/Questionnaire/ManageQuestionnaireTagsSheet.tsx (hunk 4 above)
Comment (amjithtitus09) [reply src/components/Questionnaire/ManageQuestionnaireTagsSheet.tsx]: We don't have it defined. Removed from a few other places too

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 6]
```diff
@@ -106,16 +619,35 @@ export default function QuestionnaireEditor({ id }: QuestionnaireEditorProps) {
...
+    queryFn: query(organizationApi.list, {
+      queryParams: {
+        org_type: "role",
+        name: orgSearchQuery || undefined,
+      },
+    }),
+  });
+
+  const { data: availableTags, isLoading: isLoadingAvailableTags } = useQuery({
+    queryKey: ["tags", tagSearchQuery],
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireEditor.tsx:644]: let's keep the key more verbose. this could be mixed up with other tags (maybe patient tags when it comes up)

```suggestion
    queryKey: ["questinnaire_tags", tagSearchQuery],
```

**Review by rithviknishad — APPROVED** [review]

File: src/components/Questionnaire/QuestionnaireEditor.tsx (hunk 6 above)
Comment (rithviknishad) [reply src/components/Questionnaire/QuestionnaireEditor.tsx:644]: https://github.com/ohcnetwork/care_fe/blob/develop/src/components/Questionnaire/ManageQuestionnaireTagsSheet.tsx#L66

Comment (amjithtitus09) [reply src/components/Questionnaire/QuestionnaireEditor.tsx:644]: Alrighty
