### PR TITLE
Fixed mismatch in data rendering for product page

### LINKED ISSUE #13384: Mismatch in data rendering for card and table for product page
**Describe**
Refer to the video attached, here are the changes that needs to make :

- Show  Name instead of Id for first column of table 
- Add divide-x for header row 
- Show product name in card instead of id 

https://github.com/user-attachments/assets/bc01b25c-b3d5-48ac-bad7-1cc2591badc6

**To Reproduce**
Steps to reproduce the behaviour:

- Go to any facility 
- Go to sidebar setting tab
- Go to product sub-tab 
- see the errors

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Akhileswaran-K-R**
## Proposed Changes

Fixes #13384 
- Show Name instead of Id for first column of table
- Added divide-x for header row
- Show product name in card instead of id

card view

table view

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

- **Refactor**
  - Product list now uses richer product data and displays product names instead of IDs across cards and tables.
  - First column in the desktop table renamed to “Name” for clarity.
  - Consistent name display on both mobile and desktop views.

- **Style**
  - Improved card header text wrapping for better readability.
  - Added column dividers to the desktop table header for clearer separation.

### CODE REVIEW

File: src/pages/Facility/settings/product/ProductList.tsx [hunk 1]
```diff
@@ -54,8 +53,8 @@ function ProductCard({
                 {t(product.status)}
               </Badge>
             </div>
-            <h3 className="font-medium text-gray-900">
-              Product ID: {product.id}
+            <h3 className="font-medium text-gray-900 break-normal">
+              Product Name: {product.product_knowledge.name}
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/product/ProductList.tsx]: I don't think we need heading "Product Name" for card. show name directly 

wait for core member approval

Comment (Akhileswaran-K-R) [reply src/pages/Facility/settings/product/ProductList.tsx]: Ok

**Review by rithviknishad — DISMISSED** [review]
PR's failing to follow merge checklist will not be reviewed.

File: src/pages/Facility/settings/product/ProductList.tsx (hunk 1 above)
Comment (Jacobjeevan) [reply src/pages/Facility/settings/product/ProductList.tsx]: @Akhileswaran-K-R Do it 👍

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
