### PR TITLE
fix: Record Payment form reset

### LINKED ISSUE #14635: Record Payment form not resetting on close
**Describe the bug**
Record Payment form retains old values including `payment_datetime` when the sheet is closed and reopened.

**To Reproduce**

1. Go to 'Billing' -> 'Accounts'
2. Click on 'Go to Account'
3. Click on 'Record Payment' button

**Expected behavior**
Form should reset when the sheet closes.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by StephZam**
## Proposed Changes

Fixes #14635 
- Record Payment form is reset once the sheet is closed and reopened,  updating the values including `payment_datetime`.

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Bug Fixes**
  * Payment reconciliation form now reliably re-initializes and resets whenever opened, ensuring correct default values and preventing stale data.
  * Fix applied across account and invoice views so the payment sheet behaves consistently when opened and closed.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@StephZam 

https://react-hook-form.com/docs/useform/reset#:~:text=It%27s%20fine%20to%20run%20reset%20without%20argument%20as%20long%20as%20you%20have%20provided%20a%20defaultValues%20at%20useForm


image

**Review by nihal467 — APPROVED** [review]

File: src/pages/Facility/billing/account/AccountShow.tsx [hunk 1]
```diff
@@ -579,6 +579,7 @@ export function AccountShow({
       />
 
       <PaymentReconciliationSheet
+        key={`${paymentSheet.isOpen}`}
```
Comment (rithviknishad) [inline src/pages/Facility/billing/account/AccountShow.tsx]: why do we need to change `key` here when open is changed? 🤔
