### PR TITLE
change the NIBP display from last 30 mins to current bed assignment date

### LINKED ISSUE #6429: Vitals Monitor - NIBP: Only show if data is later than the current bed's assigned start date
**Describe the bug**
As a follow-up of coronasafe/care_fe#6407, currently, we are showing NIBP only if it was measured in the last 30 minutes and hiding it otherwise. However, the "30 minutes" has no meaning/logic in it.

Instead, we can always send the last measured NIBP data from the middleware, and hide it from the care front-end based on when it was measured.

**Expected behavior**
NIBP should be shown if it was measured after the consultation's current bed assignment's start date. Other times it should be hidden.

### Tasks
- [x] coronasafe/teleicu_middleware#112
- [ ] Update Patient Vitals Monitor component to hide based on the above-mentioned logic

### PR DESCRIPTION
**Pull request by sriharsh05**
### <samp>🤖 Generated by Copilot at 8c5f324</samp>

This pull request adds the feature to show the blood pressure data from the HL7 vitals monitor for a consultation, based on the bed assignment history. It modifies the `HL7PatientVitalsMonitor` component, the `api` and `models` files, and the `ConsultationUpdatesTab` component. It also updates the `ChannelOptions` interface to include the `consultationId` property.
Changed the NIPB display in vitals monitor. It was showing only if the NIBP was measured 30 mins from current time. Now Changed it to display the measured NIBP from the current bed assignment date.

## Proposed Changes

- Fixes #6429 
- Changed the display timing of NIBP in vitals monitor.
- used useQuery to implement the API request required to get the current bed of the patient.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 8c5f324</samp>

*  Add consultationId prop to HL7PatientVitalsMonitor component and use it to fetch and display the bed assignment history for the consultation ([link](https://github.com/coronasafe/care_fe/pull/6479/files?diff=unified&w=0#diff-a1ae41968a05e24ed2d94c91009fbb88f1319a60a3b965773b3395130d27658bR116), [link](https://github.com/coronasafe/care_fe/pull/6479/files?diff=unified&w=0#diff-d27bcfa41f9f44dbc974e1c9def92d0b6a2a699177dc915b731c4fd5ab4ed6d8L1-R1), [link](https://github.com/coronasafe/care_fe/pull/6479/files?diff=unified&w=0#diff-d27bcfa41f9f44dbc974e1c9def92d0b6a2a699177dc915b731c4fd5ab4ed6d8R12-R13), [link](https://github.com/coronasafe/care_fe/pull/6479/files?diff=unified&w=0#diff-d27bcfa41f9f44dbc974e1c9def92d0b6a2a699177dc915b731c4fd5ab4ed6d8L28-R56), [link](https://github.com/coronasafe/care_fe/pull/6479/files?diff=unified&w=0#diff-d27bcfa41f9f44dbc974e1c9def92d0b6a2a699177dc915b731c4fd5ab4ed6d8L42-R77), [link](https://github.com/coronasafe/care_fe/pull/6479/files?diff=unified&w=0#diff-feda63a5a3cad0832ad09097bb20ec4786cf119d37354f99be40a385ab506f61R49), [link](https://github.com/coronasafe/care_fe/pull/6479/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cL3-R7), [link](https://github.com/coronasafe/care_fe/pull/6479/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cR306-R307))
* Define consultation bed request and response interfaces in `models.tsx` file ([link](https://github.com/coronasafe/care_fe/pull/6479/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfR221-R241))

### CODE REVIEW

File: src/Components/Facility/models.tsx [hunk 1]
```diff
@@ -218,6 +218,27 @@ export interface CurrentBed {
...
+  previous: string;
+  results: CurrentBed[];
+  is_occuiped?: boolean;
+  created_date?: string;
+  modified_date?: string;
+  name?: string;
+  description?: string;
+  meta?: Record<string, any>;
+  assets_objects?: AssetData[];
+}
```
Comment (rithviknishad) [inline src/Components/Facility/models.tsx]: 1. Interfaces/Types should be in PascalCase
2. Use PaginatedResponse type wrapper for paginated responses instead of manually defining count, next, previous.

File: src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx [hunk 2]
```diff
@@ -25,6 +27,32 @@ export default function HL7PatientVitalsMonitor(props: IVitalsComponentProps) {
...
+    if (!bedsData) console.log("error");
+    else {
+      const startDate = new Date(bedsData.results[0].created_date);
+      setBedAssignmentStartDate(startDate);
+    }
+  }, [props.consultationId, bedsRes, bedsData]);
+
+  useEffect(() => {
+    bedsFetch();
+  }, [bedsFetch]);
```
Comment (rithviknishad) [inline src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx]: The `useQuery` itself will do an auto refetch / fetch on initial mount. You need not wrap it in useEffect

```suggestion
```

File: src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx [hunk 3]
```diff
@@ -25,6 +27,32 @@ export default function HL7PatientVitalsMonitor(props: IVitalsComponentProps) {
...
+    },
+  });
+
+  useEffect(() => {
+    if (!bedsData) console.log("error");
+    else {
+      const startDate = new Date(bedsData.results[0].created_date);
+      setBedAssignmentStartDate(startDate);
+    }
+  }, [props.consultationId, bedsRes, bedsData]);
```
Comment (rithviknishad) [inline src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx]: use the `onResponse` property of `useQuery` instead of doing this in `useEffect`

File: src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx (hunk 2 above)
Comment (rithviknishad) [inline src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx]: Move this logic to the parent component instead. `HL7PatientVitalsMonitor` should be responsible only for displaying data, and not fetching co-related data.

You can move this logic to the `ConsultationUpdatesTab` and pass a prop called `hideNIBP?: boolean` instead. Simply set it true/false based on the condition.

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Changes in middleware is also required right?

File: src/Components/Facility/models.tsx [hunk 4]
```diff
@@ -222,6 +223,23 @@ export interface CurrentBed {
...
+
+export interface ConsultationBedResponse extends PaginatedResponse<CurrentBed> {
+  is_occuiped?: boolean;
+  created_date?: string;
+  modified_date?: string;
+  name?: string;
+  description?: string;
+  meta?: Record<string, any>;
+  assets_objects?: AssetData[];
+}
```
Comment (rithviknishad) [inline src/Components/Facility/models.tsx]: You are adding `created_date`, `modified_date`, `name`, and other attributes at the root of the interface. shouldn't these be properties of AssetBed (item of `results` rather than the `PaginatedResponse` itself?

File: src/Components/VitalsMonitor/types.ts [hunk 5]
```diff
@@ -46,6 +46,7 @@ export interface ChannelOptions {
 }
 
 export interface IVitalsComponentProps {
+  minutesSinceAssignment?: number;
```
Comment (rithviknishad) [inline src/Components/VitalsMonitor/types.ts]: 1. This variable name is confusing. Another contributor may not understand what this prop does. `minutesSinceAssignment` of what?

2. Consider passing the `datetime` before it should hide rather than passing minutesSinceAssignment. Since vitals monitor component maybe kept visible for prolonged period of time, the `minutesSinceAssignment` needs to change over time as minutes passes. Hence passing the actual cut-off datetime itself would be better.

File: src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx [hunk 6]
```diff
@@ -39,8 +39,12 @@ export default function HL7PatientVitalsMonitor(props: IVitalsComponentProps) {
     connect(props.socketUrl);
   }, [props.socketUrl]);
 
+  // Check if the time difference is within the specified maximum persistence time
+  console.log("Time difference in minutes: ", props.minutesSinceAssignment);
```
Comment (rithviknishad) [inline src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx]: Make sure there are no console.logs pushed

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by sriharsh05** [comment]
hey @rithviknishad
I have implemented the changes you requested. Can you review it please?

File: src/Redux/api.tsx [hunk 7]
```diff
@@ -350,6 +353,8 @@ const routes = {
   listConsultationBeds: {
     path: "/api/v1/consultationbed/",
     method: "GET",
+    TRes: Type<ConsultationBedResponse>(),
+    TBody: Type<ConsultationBedRequest>(),
```
Comment (rithviknishad) [inline src/Redux/api.tsx]: Are you sure GET requests have a request body?
```suggestion
```

File: src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx [hunk 8]
```diff
@@ -39,8 +39,23 @@ export default function HL7PatientVitalsMonitor(props: IVitalsComponentProps) {
...
+    ? new Date(props.patientCurrentBedAssignmentDate)
+    : undefined;
+
+  const minutesSinceCurrentBedAssignment =
+    bedAssignmentStartDate &&
+    (currentDate.getTime() - bedAssignmentStartDate.getTime()) / (1000 * 60);
+  console.log(
+    "minutesSinceCurrentBedAssignment",
+    minutesSinceCurrentBedAssignment
+  );
```
Comment (rithviknishad) [inline src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx]: repeating again,remove console logs
```suggestion
```

File: src/Components/Facility/models.tsx [hunk 9]
```diff
@@ -222,6 +223,15 @@ export interface CurrentBed {
   meta: Record<string, any>;
 }
 
+export interface ConsultationBedRequest {
+  bed?: string;
+  consultation: string;
+  limit?: number;
+  offset?: number;
+}
```
Comment (rithviknishad) [inline src/Components/Facility/models.tsx]: Types for query params are not needed nor would work with useQuery/request



```suggestion
```

File: src/Components/Facility/models.tsx [hunk 10]
```diff
@@ -222,6 +223,15 @@ export interface CurrentBed {
...
+
+export type ConsultationBedResponse = PaginatedResponse<CurrentBed>;
```
Comment (rithviknishad) [inline src/Components/Facility/models.tsx]: You can wrap it `PaginatedResponse` in `api.tsx` file itself instead of creating a new type right?

Comment (rithviknishad) [reply src/Components/Facility/models.tsx]: (Just to keep it consistent on how other api routes are defined. It would be easier to look and know that this route is a paginated route.)

File: src/Components/Facility/ConsultationDetails/ConsultationUpdatesTab.tsx [hunk 11]
```diff
@@ -104,6 +108,21 @@ export const ConsultationUpdatesTab = (props: ConsultationTabProps) => {
...
+    onResponse: ({ res, data }) => {
+      if (res?.ok && data) {
+        setBedAssignmentStartDate(data.results[0].created_date);
+      } else {
+        Notification.Error({
+          msg: "Something went wrong: ",
+        });
+      }
+    },
+  });
```
Comment (rithviknishad) [inline src/Components/Facility/ConsultationDetails/ConsultationUpdatesTab.tsx]: You don't need a seperate `useState` for `bedAssignmentStartDate`. Avoid using `useStates` when you can approach it without one. `useQuery` already manages a state of the data for you.

```suggestion
  const { data } = useQuery(routes.listConsultationBeds, {
    query: { consultation: props.consultationId },
  });
  const bedAssignmentStartDate = data?.results[0].created_date ?? "";
```

File: src/Components/Facility/ConsultationDetails/ConsultationUpdatesTab.tsx [hunk 12]
```diff
@@ -23,6 +26,7 @@ export const ConsultationUpdatesTab = (props: ConsultationTabProps) => {
   const [ventilatorSocketUrl, setVentilatorSocketUrl] = useState<string>();
   const [monitorBedData, setMonitorBedData] = useState<AssetBedModel>();
   const [ventilatorBedData, setVentilatorBedData] = useState<AssetBedModel>();
+  const [bedAssignmentStartDate, setBedAssignmentStartDate] = useState("");
```
Comment (rithviknishad) [inline src/Components/Facility/ConsultationDetails/ConsultationUpdatesTab.tsx]:
```suggestion
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — CHANGES_REQUESTED** [review]
This behaviour should be present for central nursing station too

**Comment by sriharsh05** [comment]
hey @rithviknishad 
I've made some updates to the central nursing station component based on the requirements. I believe it might need a review. Please take a look and let me know if I've taken the right approach.

I've used the useEffect function to fetch the BedAssignmentStartDates of all the patients in the facility. This required two request calls to fetch the required data. However, I'm not certain if I've provided the data to the HL7PatientVitalsMonitor component in the correct order.

Please review the code when you get a chance.

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Undo the last commit for CNS.

1. N+1 API queries are bad!
2. You need not have to make a single API call in the first place, since you already have the bed assignment start date present in `PatientAssetBed.patient.last_consultation.current_bed.start_date`.

**Review by rithviknishad — APPROVED** [review]
Nice work! @sriharsh05, create an issue in the middleware repo to allow data that are measured beyond 30 minutes too. Currently, middleware also skips sending if it's beyond 30 minutes.

**Review by rithviknishad — APPROVED** [review]
Nice work!

**Comment by nihal467** [comment]
@sriharsh05 
image


https://deploy-preview-6479--care-net.netlify.app/facility/6ca0c460-a486-4acc-ad76-b800e8b0d157/patient/7e22e2eb-f85b-4e5c-90fe-681d3f8a4f6f/consultation/b7cc9239-6142-491c-8a2b-8167cee6ad93

this patient is having NIBP data, but it is not getting reflected in the patient consultation page

CC: @rithviknishad

**Comment by sriharsh05** [comment]
Hey @nihal467 , the link above isn't working. It's showing a 'Page Not Found' error.

**Comment by nihal467** [comment]
@sriharsh05 login-in with below credential,

username : test-oct-staff-008
p/w: Test@123

**Comment by sriharsh05** [comment]
Hey @nihal467 
The NIBP of a patient will only be displayed if it's measured after the current bed assignment date. I think the details for the patient you provided in the above link were updated on October 27th, and then the bed was switched later.
Please correct me if I'm mistaken.

**Comment by nihal467** [comment]
@sriharsh05 

image
image

- for the particular patient link already shared, the bed was assigned to the patient at ( 1:35 Pm today (31/10/2023)), and the current time is (3:47 Pm) and in the NIBP monitor is showing latest data received was 3 min ago.
- as per your PR, the latest NIBP data received is for the particular patient, and it should be reflected there but it is not being shown as of now.

File: src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx [hunk 13]
```diff
@@ -39,8 +39,19 @@ export default function HL7PatientVitalsMonitor(props: IVitalsComponentProps) {
...
+
+  const minutesSinceCurrentBedAssignment =
+    bedAssignmentStartDate &&
+    (currentDate.getTime() - bedAssignmentStartDate.getTime()) / (1000 * 60);
   const bpWithinMaxPersistence = !!(
-    (data.bp?.["date-time"] && isWithinMinutes(data.bp?.["date-time"], 30)) // Max blood pressure persistence is 30 minutes
+    data.bp?.["date-time"] &&
+    minutesSinceCurrentBedAssignment !== undefined && // Check if minutesSinceCurrentBedAssignment is defined
+    isWithinMinutes(data.bp?.["date-time"], minutesSinceCurrentBedAssignment)
   );
```
Comment (rithviknishad) [inline src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx]: @sriharsh05 could you simplify this a bit?
You can just write a one-line code for this entire thing using dayjs.
All you have to do is just check if the date is before another date right?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by sriharsh05** [comment]
@nihal467 
I have made the required changes. Now the patients NIBP data is reflecting in the patient consultation page.

File: src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx [hunk 14]
```diff
@@ -40,7 +43,12 @@ export default function HL7PatientVitalsMonitor(props: IVitalsComponentProps) {
   }, [props.socketUrl]);
 
   const bpWithinMaxPersistence = !!(
-    (data.bp?.["date-time"] && isWithinMinutes(data.bp?.["date-time"], 30)) // Max blood pressure persistence is 30 minutes
+    data.bp?.["date-time"] &&
+    props.patientCurrentBedAssignmentDate &&
+    isWithinMinutes(
+      data.bp?.["date-time"],
+      props.patientCurrentBedAssignmentDate
+    )
```
Comment (rithviknishad) [inline src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx]: Have a look at https://day.js.org/docs/en/query/is-after

```suggestion
    dayjs(data.bp?.["date-time"]).isAfter(props.patientCurrentBedAssignmentDate)
```

File: src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx [hunk 15]
```diff
@@ -14,8 +14,11 @@ const minutesAgo = (timestamp: string) => {
   return `${dayjs().diff(dayjs(timestamp), "minute")}m ago`;
 };
 
-const isWithinMinutes = (timestamp: string, minutes: number) => {
-  return dayjs().diff(dayjs(timestamp), "minute") < minutes;
+const isWithinMinutes = (timestamp: string, bedAssignmentStartDate: string) => {
+  return (
+    dayjs().diff(dayjs(timestamp), "minute") <
+    dayjs().diff(dayjs(bedAssignmentStartDate), "minute")
+  );
```
Comment (rithviknishad) [inline src/Components/VitalsMonitor/HL7PatientVitalsMonitor.tsx]: You can delete this unused function too

```suggestion
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by sriharsh05** [comment]
@rithviknishad 
I have made the changes you requested.

**Review by rithviknishad — APPROVED** [review]
Nice! Very clean!

**Comment by rithviknishad** [comment]
@sriharsh05 the issue also mentions changes to be made to the middleware too. Are you working on it?

**Comment by nihal467** [comment]
LGTM

**Comment by sriharsh05** [comment]
> @sriharsh05 the issue also mentions changes to be made to the middleware too. Are you working on it?

@rithviknishad I have not yet started working on it.

**Review by khavinshankar — APPROVED** [review]
