### PR TITLE
Merged configure facility and configure health facility in one page

### LINKED ISSUE #6158: Merge "Configure Facility" and "Configure Health Facility" to one page: "Configure Facility"
**Describe the bug**
In the Facility Home Page, Manage Facility dropdown, there are two options "Configure Facility" and "Configure Health Facility" that could be confused with each other.

https://care.ohc.network/facility/657c32be-d584-476c-9ce2-0412f0e7692e

**Expected behavior**
- Contents of both pages are to be merged into one single page under "Configure Facility".
- Contents of "Configure Health Facility" should be shown only if ABDM is enabled.

**Screenshots**
image

cc: @khavinshankar

### PR DESCRIPTION
**Pull request by kshitijv256**
### <samp>🤖 Generated by Copilot at e9d94be</samp>

Refactored the facility configuration flow to integrate the ABDM feature settings and avoid nested `Page` components. Removed unused `ConfigureHealthFacility` route and component from `AppRouter` and `FacilityHome`. Simplified the rendering of `ConfigureHealthFacility` and `UpdateFacilityMiddleware` components.

## Proposed Changes

- Fixes #6158 
- Merged both pages into one
- Showing configure health page content only when ABDM is enabled
- Removed configure health page option form Manage facility dropdown

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

File: src/Components/ABDM/ConfigureHealthFacility.tsx [hunk 1]
```diff
@@ -121,33 +121,33 @@ export const ConfigureHealthFacility = (props: any) => {
...
-                error={state.errors?.hf_id}
-              />
-            </div>
+    // <Page
+    //   title="Configure Health Facility"
+    //   crumbsReplacements={{
+    //     [facilityId]: { name: state.form.name },
+    //   }}
+    //   className="mx-auto max-w-3xl"
+    // >
```
Comment (khavinshankar) [inline src/Components/ABDM/ConfigureHealthFacility.tsx]: remove the comments

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
