### PR TITLE
No close button once you open the discontinued prescriptions

### LINKED ISSUE #6599: Consultation Medicine Tab: No close button once you open the discontinued prescriptions.
**Describe the bug**
There is no close button once you open the discontinued prescriptions in the medicine tab. So it only closes once you refresh the page

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to a consultation page and open the medicine tab
2. Click on the **Show discontinued prescription** button.
3. Now you can't close the discontinued prescription.

**Expected behaviour**
Have a close button to close the discontinued prescriptions.

**Screenshots**
image
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by AshrafMd-1**
### <samp>🤖 Generated by Copilot at c1cdaf4</samp>

This pull request improves the performance and usability of the `MedicineAdministrationSheet` component, which displays the prescriptions and doses for a patient. It allows the user to filter the discontinued prescriptions and to fetch more data on demand. It also refines the appearance and behavior of the scroll and button components.

## Proposed Changes

- Fixes #6599 
- Add a close button to hide discontinued prescriptions. 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at c1cdaf4</samp>

* Optimize data fetching for discontinued prescriptions by adding a limit parameter that depends on the showDiscontinued state ([link](https://github.com/coronasafe/care_fe/pull/6614/files?diff=unified&w=0#diff-db20bc68269b5cb3e2695b4ab0ce9d97f1736a9179445b635bc28053b74125e2L42-R46))
  - Wrapping the ScrollOverlay inside a styled div and moving the ButtonV2 outside it ([link](https://github.com/coronasafe/care_fe/pull/6614/files?diff=unified&w=0#diff-db20bc68269b5cb3e2695b4ab0ce9d97f1736a9179445b635bc28053b74125e2L100-R163))
  - Adding a loading state and a toggle logic for the ButtonV2 to control the showDiscontinued state ([link](https://github.com/coronasafe/care_fe/pull/6614/files?diff=unified&w=0#diff-db20bc68269b5cb3e2695b4ab0ce9d97f1736a9179445b635bc28053b74125e2L100-R163))

### CODE REVIEW

File: src/Components/Medicine/MedicineAdministrationSheet/index.tsx [hunk 1]
```diff
@@ -39,7 +39,11 @@ const MedicineAdministrationSheet = ({ readonly, is_prn }: Props) => {
 
   const discontinuedPrescriptions = useQuery(MedicineRoutes.listPrescriptions, {
     pathParams: { consultation },
-    query: { ...filters, discontinued: true },
+    query: {
+      ...filters,
+      limit: showDiscontinued ? 100 : 1,
```
Comment (rithviknishad) [inline src/Components/Medicine/MedicineAdministrationSheet/index.tsx:44]:
```suggestion
      limit: showDiscontinued ? undefined : 1,
```

File: src/Components/Medicine/MedicineAdministrationSheet/index.tsx [hunk 2]
```diff
@@ -97,47 +101,66 @@ const MedicineAdministrationSheet = ({ readonly, is_prn }: Props) => {
...
+              )}
+            </>
+          )}
+        </ScrollOverlay>
+        {!!discontinuedCount && (
           <ButtonV2
             variant="secondary"
             className="group sticky left-0 w-full rounded-b-lg rounded-t-none bg-gray-100"
-            onClick={() => setShowDiscontinued(true)}
+            onClick={() => !loading && setShowDiscontinued(!showDiscontinued)}
```
Comment (rithviknishad) [inline src/Components/Medicine/MedicineAdministrationSheet/index.tsx]:
```suggestion
            disable={discontinuedPrescriptions.loading}
            onClick={() => setShowDiscontinued(!showDiscontinued)}
```

File: src/Components/Medicine/MedicineAdministrationSheet/index.tsx [hunk 3]
```diff
@@ -97,47 +101,66 @@ const MedicineAdministrationSheet = ({ readonly, is_prn }: Props) => {
...
           >
-            <span className="flex w-full items-center justify-start gap-1 text-xs transition-all duration-200 ease-in-out group-hover:gap-3 md:text-sm">
-              <CareIcon icon="l-eye" className="text-lg" />
-              <span>
-                Show <strong>{discontinuedCount}</strong> discontinued
-                prescription(s)
+            {loading ? (
```
Comment (rithviknishad) [inline src/Components/Medicine/MedicineAdministrationSheet/index.tsx]:
```suggestion
            {discontinuedPrescriptions ? (
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Medicine/MedicineAdministrationSheet/index.tsx (hunk 3 above)
Comment (AshrafMd-1) [reply src/Components/Medicine/MedicineAdministrationSheet/index.tsx:143]: did u mean `discontinuedPrescriptions.loading`

File: src/Components/Medicine/MedicineAdministrationSheet/index.tsx (hunk 2 above)
Comment (AshrafMd-1) [reply src/Components/Medicine/MedicineAdministrationSheet/index.tsx]: here if i keep `discontinuedPrescriptions.loading` instead of `loading` then the button is not disabled in between of show and hide timing

Comment (AshrafMd-1) [reply src/Components/Medicine/MedicineAdministrationSheet/index.tsx]: image

File: src/Components/Medicine/MedicineAdministrationSheet/index.tsx (hunk 3 above)
Comment (AshrafMd-1) [reply src/Components/Medicine/MedicineAdministrationSheet/index.tsx]: same issue as above

File: src/Components/Medicine/MedicineAdministrationSheet/index.tsx (hunk 2 above)
Comment (rithviknishad) [reply src/Components/Medicine/MedicineAdministrationSheet/index.tsx]: Then you can disable based on both loading states. 

This button is dependent on the discontinued prescriptions query and not the active prescriptions query so depending on discontinued prescriptions loading state is necessary.

File: src/Components/Medicine/MedicineAdministrationSheet/index.tsx (hunk 3 above)
Comment (rithviknishad) [reply src/Components/Medicine/MedicineAdministrationSheet/index.tsx]: same answer as above

**Comment by AshrafMd-1** [comment]
@rithviknishad once can u review it

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
lgtm

**Review by khavinshankar — APPROVED** [review]
