### PR TITLE
Fix: Adjust filter container width for mobile on Accounts page

### LINKED ISSUE #13404: Adjust width of filter containers of Accounts page for Mobile View UI
**Describe the bug**
Make the width full to improve UI and maintain consistency

Image

**To Reproduce**

1. Go to Billings
2. Click on Accounts
3. See error in mobile view

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by ama1t**
## Proposed Changes

Fixes #13404 
Screenshot 2025-08-20 212434

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.

## Summary by CodeRabbit

- Style
  - Improved the Account List header’s responsive layout: header now stacks vertically by default and switches to a horizontal, wrapped, centered layout on small screens and larger. Enhances readability, spacing, and alignment across devices without altering data, behavior, or functionality.

### CODE REVIEW

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

**Comment by nihal467** [comment]
LGTM

File: src/pages/Facility/billing/account/AccountList.tsx [hunk 1]
```diff
@@ -114,7 +114,7 @@ export function AccountList({
             initialValues={editingAccount ? editingAccount : undefined}
             isEdit={!!editingAccount}
           />
-          <div className="mb-4 flex flex-wrap items-center justify-between gap-4">
+          <div className="mb-4 flex flex-col sm:flex-row sm:flex-wrap sm:items-center sm:justify-between gap-4">
```
Comment (Jacobjeevan) [inline src/pages/Facility/billing/account/AccountList.tsx]: can remove sm: for justify-between 👍

**Review by Jacobjeevan — APPROVED** [review]
