### PR TITLE
"Solved facility linking issue under manage facilities/view users"#7474

### LINKED ISSUE #7474: Facilities added but not displayed in Users.
**Describe the bug**
On linking a new facility to user, it is not displayed though it has been added(probably since on adding again, it shows already added).

**To Reproduce**

1. Go to Facilites tab
2. Click on View facility on any facility
3. select View users from the manage facility dropdown
4. Click on "Click here to show "
5. add new facility
6. It is not displayed but on again adding , it shows error "User already has permission to this facility ".

**Expected behavior**
The attached facility should be displayed.

**Screenshots/Video**

https://github.com/coronasafe/care_fe/assets/122200551/d9c4f1ba-54b5-48b0-8cda-4078213d018c

### PR DESCRIPTION
**Pull request by Sulochan-khadka**
## Proposed Changes

- Fixes #7474
- Added linked facilities slider modal 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

File: src/Components/Facility/FacilityUsers.tsx [hunk 1]
```diff
@@ -22,16 +23,21 @@ import request from "../../Utils/request/request";
...
 
 const Loading = lazy(() => import("../Common/Loading"));
 
 export default function FacilityUsers(props: any) {
+  const { t } = useTranslation();
   const { facilityId } = props;
   let manageUsers: any = null;
   const [isUnlinkFacilityLoading, setIsUnlinkFacilityLoading] = useState(false);
   const [isAddFacilityLoading, setIsAddFacilityLoading] = useState(false);
   const [isLoadFacilityLoading, setIsLoadFacilityLoading] = useState(false);
```
Comment (rithviknishad) [inline src/Components/Facility/FacilityUsers.tsx]: These and other unrelated code can be removed now right?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Facility/FacilityUsers.tsx (hunk 1 above)
Comment (Sulochan-khadka) [reply src/Components/Facility/FacilityUsers.tsx]: Are they unrelated? What if the user by mistake linked wrong facility and then wants to unlink it and link different facility?

Comment (rithviknishad) [reply src/Components/Facility/FacilityUsers.tsx]: The Facility Slideover takes care of unlinking too right? Correct me if I'm wrong

Comment (Sulochan-khadka) [reply src/Components/Facility/FacilityUsers.tsx]: Yes...

**Comment by mridulsaggi** [comment]
please assign me this issue as i am willing to work on this.

**Comment by Sulochan-khadka** [comment]
> please assign me this issue as i am willing to work on this.

Hey mate, sadly this is a PR and not an issue, therefore if you want to solve an issue, kindly explore the issue tab.

File: src/Components/Facility/FacilityUsers.tsx (hunk 1 above)
Comment (Sulochan-khadka) [reply src/Components/Facility/FacilityUsers.tsx]: Therefore do I need to remove them to get merged?

**Comment by Sulochan-khadka** [comment]
@rithviknishad let me know the way out for this PR to get merged. Thankyou

**Comment by rithviknishad** [comment]
> @rithviknishad let me know the way out for this PR to get merged. Thankyou

Could you resolve the merge conflicts?

**Comment by Sulochan-khadka** [comment]
> > @rithviknishad let me know the way out for this PR to get merged. Thankyou
> 
> Could you resolve the merge conflicts?

I will do it right away...

**Comment by Sulochan-khadka** [comment]
> > @rithviknishad let me know the way out for this PR to get merged. Thankyou
> 
> Could you resolve the merge conflicts?

Done...

**Comment by Sulochan-khadka** [comment]
@rithviknishad , I also solved a minor error that was causing the deployment to fail. You may have a look.

**Review by khavinshankar — COMMENTED** [review]
changes look good, just resolve the linting issues and remove the comments used for todo reminders

**Comment by nihal467** [comment]
@Sulochan-khadka make the necessary changes

**Comment by Sulochan-khadka** [comment]
@nihal467 @khavinshankar have fixed almost all lint errors... Well I did not find one lint error the workflow was indicating at... replacing `...` with '....' , when there is no such statement . Do let me know immediately if unknowingly I messed up something. Also have just commented out showFacilites since it might be of use in future.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
