### PR TITLE
fix: make user dashboard buttons responsive for mobile view

### LINKED ISSUE #13022: Make Buttons on User Dashboard responsive for mobile view
**Describe the bug**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by ama1t**
## Proposed Changes

- Fixes #13022 
Screenshot 2025-07-23 204144

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **Style**
  * Improved the layout and styling of the user dashboard's top-right button group for better responsiveness and visual consistency across devices.
  * Updated button and dropdown menu designs for enhanced alignment, spacing, and vertical text alignment on both mobile and desktop views.

### CODE REVIEW

File: src/pages/UserDashboard.tsx [hunk 1]
```diff
@@ -88,12 +88,16 @@ export default function UserDashboard() {
             </p>
           </div>
         </div>
-        <div className="flex gap-2">
+        <div
+          className={`flex ${
+            isMobile ? "flex-col gap-2 w-full" : "flex-row gap-2 items-center"
+          }`}
+        >
           {user.is_superuser && (
```
Comment (AdityaJ2305) [inline src/pages/UserDashboard.tsx]: use `cn` utility

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]
- Let's not use leading-tight text is not that long

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
