### PR TITLE
Facility Id in User Profile for Nav User

### LINKED ISSUE #9834: Profile Bug Possibly Connected/Related to Schedules (Availability)
**Describe the bug**
In the profile, when you click on User Information, it shows the Availability tab, and if you click the Availability tab doesn't load properly until you visit the Schedule section in Facility. Even if it loads, an error notification pops up.

**To Reproduce**

1. Go to `Profile` or `Edit Profile` from dashboard 
2. Click on `User Information`
3. See error

**Expected behavior**
Clicking on User Information should not load the Availability tab; if its required to load, it should load properly.

**Screenshots**
Image

### Screen recording available for better understanding 
https://github.com/user-attachments/assets/ee39d128-ee34-4b4e-943c-3b3f2fd0d1c1

**Desktop information:**

- OS: [Windows]
- Browser [Firefox]
- Version [133.0.3 (64-bit)]

### PR DESCRIPTION
**Pull request by Jacobjeevan**
## Proposed Changes

- Adding facilityId to the Nav User/Footer Profile url (if a facility is selected) to ensure availability shows up.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced user navigation in the sidebar to support facility-specific routing.
	- Added ability to dynamically generate navigation URLs based on selected facility.

- **Improvements**
	- Updated the sidebar to conditionally pass the selected facility ID for improved context.
	- Improved URL construction in user navigation for better readability and maintainability.
	- Introduced conditional filtering for breadcrumb items based on visibility settings.
	- Enhanced breadcrumb visibility control with new optional properties.

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
from organizations perspective, opening profile and clicking User Information tab, that redirects to facility: undefined

image

**Comment by nihal467** [comment]
LGTM , ignore the unrelated cypress failure

File: src/components/Users/UserHome.tsx [hunk 1]
```diff
@@ -84,18 +84,24 @@ export default function UserHome(props: UserHomeProps) {
...
+  const userUrl = props.facilityId
+    ? `/facility/${props.facilityId}/users/${username}`
+    : `/users/${username}`;
+
+  const crumbsReplacements = {
+    ...(loggedInUser
+      ? { [username]: { name: "Profile" } }
+      : { [username]: { name: username } }),
+    ...(!props.facilityId && { users: { hide: true } }),
+  };
```
Comment (rithviknishad) [inline src/components/Users/UserHome.tsx]: i wish this was more readable

File: src/components/ui/sidebar/app-sidebar.tsx [hunk 2]
```diff
@@ -126,7 +126,13 @@ export function AppSidebar({
       </SidebarContent>
 
       <SidebarFooter>
-        {(facilitySidebar || selectedOrganization) && <FacilityNavUser />}
+        {(facilitySidebar || selectedOrganization) && (
+          <FacilityNavUser
+            {...(facilitySidebar && {
+              selectedFacilityId: selectedFacility?.id,
+            })}
+          />
```
Comment (rithviknishad) [inline src/components/ui/sidebar/app-sidebar.tsx]: correct me if i'm wrong, this could be made easier right?

```suggestion
          <FacilityNavUser selectedFacilityId={facilitySidebar ? selectedFacility?.id : undefined} />
```

File: src/components/ui/sidebar/nav-user.tsx [hunk 3]
```diff
@@ -27,7 +27,11 @@ import useAuthUser, { useAuthContext } from "@/hooks/useAuthUser";
 import { usePatientSignOut } from "@/hooks/usePatientSignOut";
 import { usePatientContext } from "@/hooks/usePatientUser";
 
-export function FacilityNavUser() {
+export function FacilityNavUser({
+  selectedFacilityId,
+}: {
+  selectedFacilityId?: string;
```
Comment (rithviknishad) [inline src/components/ui/sidebar/nav-user.tsx]: is it really optional?

```suggestion
  selectedFacilityId: string | undefined;
```

File: src/components/ui/sidebar/app-sidebar.tsx (hunk 2 above)
Comment (Jacobjeevan) [reply src/components/ui/sidebar/app-sidebar.tsx]: Technically selectedFacility?.id should be undefined when an org is selected, but let's do this just to be safe 😆

File: src/components/ui/sidebar/nav-user.tsx (hunk 3 above)
Comment (Jacobjeevan) [reply src/components/ui/sidebar/nav-user.tsx]: yea 🤔  optional (all we are using it is to check if it exists and render profile url accordingly anyways)

**Review by rithviknishad — APPROVED** [review]
