### PR TITLE
Fix avatar upload stuck state and update header after changing avatar

### LINKED ISSUE #9426: Avatar upload stuck state and update header after changing avatar in User profile
### Bugs in User profile:
- [ ] Loading state gets stuck when an error occurs during avatar upload.
- [ ] Header does not update to reflect the new avatar after changing it.

**To Reproduce**

1. Click `Users` tab in sidebar.
2. Go to your user profile.
3. Click on `Change Avatar`.
4. Upload image with incorrect dimensions.
5. See error that **Loading state stuck**
6. Another error after successfully changed profile picture then header's profile image does not update

**Expected behavior**
The avatar should upload successfully, and the header should update to display the new avatar immediately after the upload is complete. If an error occurs, the loading state should reset, and an appropriate error message should be displayed.

**Video of Bug:**

https://github.com/user-attachments/assets/4b51cb80-ffb9-44e0-9833-7ea317a421d6

**Video of Solution:**

https://github.com/user-attachments/assets/6ad88d62-4d9f-4bd2-b72e-cafa9db22b55

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Edge
- Version: 131.0.2903.99

### PR DESCRIPTION
**Pull request by shauryag2002**
## Proposed Changes

- Fixes #9426 
- [x] Loading state gets stuck when an error occurs during avatar upload.
- [x] Header does not update to reflect the new avatar after changing it.

**Video of Solution:**

https://github.com/user-attachments/assets/6ad88d62-4d9f-4bd2-b72e-cafa9db22b55

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced error handling for file uploads, including improved notifications for client and network errors.
	- Added an optional `refetchUserData` parameter to the `UserAvatar` component to refresh user data after avatar updates.

- **Bug Fixes**
	- Improved state management in the `AvatarEditModal` to ensure UI reflects the correct status during upload attempts.

- **Documentation**
	- Updated method signatures to reflect changes in function parameters and return types across components.

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/components/Users/UserAvatar.tsx [hunk 1]
```diff
@@ -19,20 +19,25 @@ import uploadFile from "@/Utils/request/uploadFile";
...
-    refetch: refetchUserData,
-  } = useTanStackQueryInstead(routes.getUserDetails, {
-    pathParams: {
-      username: username,
+  const { data: userData, loading: isLoading } = useTanStackQueryInstead(
+    routes.getUserDetails,
+    {
+      pathParams: {
+        username: username,
+      },
```
Comment (rithviknishad) [inline src/components/Users/UserAvatar.tsx:38]: let's switch these to using tanstack query's useQuery instead?

refer: https://docs.ohc.network/docs/care/development/data-fetching-in-care/

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

File: src/components/Users/UserAvatar.tsx (hunk 1 above)
Comment (rithviknishad) [reply src/components/Users/UserAvatar.tsx:38]: can be done separatley
