### PR TITLE
Fix Duplicate key warning #14022

### LINKED ISSUE #14022: Duplicate key warning in Tax Components
**Description:**

- While viewing the Billing → Tax Components page, multiple console warnings appear

`Encountered two children with the same key, 'cgst'.
Keys should be unique so that components maintain their identity across updates.`

Image

**Steps to Reproduce:**

- Go to Settings → Billing → Tax Components.
- Observe the browser console.

**Expected Behavior:**

- Each row in the table should have a unique key, with no warnings in the console.

---
🚨 DO NOT EDIT BELOW THIS LINE 🚨
Instructions for Requesting Assignment:
To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

Describe your solution clearly:
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

Expected Timeline:

End date: [Expected submission date of a completed Pull Request]
Additional Context:
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by KadariPavani**
## Proposed Changes

Problem Summary: The component’s mapped rows in the <TableBody> used key={${component.code?.code || component.title}}, which was not guaranteed to be unique. If multiple tax components had the same title or missing code, React would show a warning: “Each child in a list should have a unique key prop”.
Why It Happened: React needs a stable and unique key for every child in a mapped list to efficiently track updates and preserve component state during re-renders. Using only the index (idx) creates potential performance and correctness issues if the list order ever changes

Fixes #14022 

- Add a secondary fallback — the map index (idx) — to guarantee uniqueness even when IDs or codes repeat.
- Using idx as a fallback (not as the sole key) prevents duplicate warnings but maintains consistent DOM mapping for static lists.
Screenshot 2025-10-11 194354

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [X] Add specs that demonstrate the bug or test the new feature.
- [X] Update [product documentation](https://docs.ohc.network).
- [X] Ensure that UI text is placed in I18n files.
- [X] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [X] Request peer reviews.
- [X] Complete QA on mobile devices.
- [X] Complete QA on desktop devices.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved stability of the Tax Component list in Billing > Tax settings to prevent rare display issues when multiple items share similar names or identifiers.
  * Ensures consistent rendering during filtering and updates, reducing flicker, duplication, and incorrect item alignment.
  * No changes to editing or saving behavior; overall UI is smoother and more reliable.

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

**Comment by KadariPavani** [comment]
Hi @nihal467  thanks again for re-running the checks!
It looks like the only failing test (users_spec/user_creation.cy.ts) crashed due to a Chrome renderer issue, not a test assertion failure.
Could you please re-run this job once more or confirm if it’s a known flaky test?

File: src/pages/Facility/settings/billing/tax/tax-components/TaxComponentSettings.tsx [hunk 1]
```diff
@@ -74,8 +74,10 @@ export function TaxComponentSettings() {
                 </TableCell>
               </TableRow>
             ) : (
-              filteredComponents.map((component) => (
-                <TableRow key={`${component.code?.code || component.title}`}>
+              filteredComponents.map((component, idx) => (
+                <TableRow
+                  key={`${component.code?.code || component.title}-${idx}`}
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/billing/tax/tax-components/TaxComponentSettings.tsx]:
```suggestion
                  key={`${component.title}-${idx}`}
```

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

**Review by yash-learner — CHANGES_REQUESTED** [review]
@KadariPavani 

Build is failing. can you format the file using prettier 

```
1:20:08 PM: /opt/build/repo/src/pages/Facility/settings/billing/tax/tax-components/TaxComponentSettings.tsx
1:20:08 PM:   78:26  error  Replace `⏎··················key={`${component.title}-${idx}`}⏎················` with `·key={`${component.title}-${idx}`}`  prettier/prettier
```

https://github.com/ohcnetwork/care_fe/pull/14055/files

https://app.netlify.com/projects/care-ohc/deploys/68f1f46f68531d00088ad490

**Review by yash-learner — CHANGES_REQUESTED** [review]
@KadariPavani 

Build is failing. can you format the file using prettier 

```
1:20:08 PM: /opt/build/repo/src/pages/Facility/settings/billing/tax/tax-components/TaxComponentSettings.tsx
1:20:08 PM:   78:26  error  Replace `⏎··················key={`${component.title}-${idx}`}⏎················` with `·key={`${component.title}-${idx}`}`  prettier/prettier
```

https://github.com/ohcnetwork/care_fe/pull/14055/files

https://app.netlify.com/projects/care-ohc/deploys/68f1f46f68531d00088ad490

**Comment by KadariPavani** [comment]
> @KadariPavani
> 
> Build is failing. can you format the file using prettier
> 
> ```
> 1:20:08 PM: /opt/build/repo/src/pages/Facility/settings/billing/tax/tax-components/TaxComponentSettings.tsx
> 1:20:08 PM:   78:26  error  Replace `⏎··················key={`${component.title}-${idx}`}⏎················` with `·key={`${component.title}-${idx}`}`  prettier/prettier
> ```
> 
> https://github.com/ohcnetwork/care_fe/pull/14055/files
> 
> https://app.netlify.com/projects/care-ohc/deploys/68f1f46f68531d00088ad490

@yash-learner ,Thank you for the feedback. I have just pushed the formatted changes, kindly re-run the build, and let me know if there are any further issues.

**Review by yash-learner — APPROVED** [review]
LGTM 👍
