### PR TITLE
Fix navigation loop issue in Billing

### LINKED ISSUE #16017: Navigation Loop in Billing
When opening an invoice and clicking the Back button, it goes to the Accounts page.Clicking Back again returns to the same invoice, creating an incorrect navigation loop.

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Proposed Changes
Fix #16017

https://github.com/user-attachments/assets/fa9eec32-b05a-4894-b1e3-1cb76483c333

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved browser history handling so back/forward navigation behaves more predictably when viewing or creating invoices.

* **Refactor**
  * Simplified the back-control on invoice view to a cleaner link-style button.
  * Removed the back-control from invoice creation and made navigation to a newly created invoice replace the history entry to avoid extra back steps.

### CODE REVIEW

File: src/Providers/HistoryAPIProvider.tsx [hunk 1]
```diff
@@ -1,26 +1,43 @@
...
+      return original(...args);
+    };
+  }, []);
 
   useLocationChange(
     (newLocation) => {
       const newPath = newLocation.fullPath + newLocation.search;
+      const isReplace = isReplaceRef.current;
+      isReplaceRef.current = false;
+
```
Comment (rithviknishad) [inline src/Providers/HistoryAPIProvider.tsx:14]: this brings unnecessary complications.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by parvathyns-creator** [comment]
@nihal467 this looks fine

**Comment by gigincg** [comment]
@NikhilA8606 

You should be able to implement this better with the new release of raviger(5.3.0) with https://github.com/kyeotic/raviger/pull/162

File: package.json [hunk 2]
```diff
@@ -116,7 +116,7 @@
     "normalize-wheel": "^1.0.1",
     "pigeon-maps": "^0.22.1",
     "qrcode.react": "^4.1.0",
-    "raviger": "^5.0.0-2",
+    "raviger": "^5.3.0",
```
[the remark this answers is not in the document]
Comment (NikhilA8606) [reply package.json:119]: Are you sure?
Image

File: src/Providers/HistoryAPIProvider.tsx [hunk 3]
```diff
@@ -7,20 +7,33 @@ export const ResetHistoryContext = createContext(() => {});
...
+          return [newPath, ...history.slice(1)];
+        }
+
+        // browser back/forward
+        if (action === "pop") {
           return history.slice(1);
+        }
+
+        // push navigation
+        if (action === "push") {
```
Comment (Jacobjeevan) [inline src/Providers/HistoryAPIProvider.tsx]: same thing as below; so not needed.

File: src/Providers/HistoryAPIProvider.tsx [hunk 4]
```diff
@@ -7,20 +7,33 @@ export const ResetHistoryContext = createContext(() => {});
...
+    (location) => {
+      const newPath = location.fullPath + location.search;
+      const action = location.initiatedBy;
+
       setHistory((history) => {
-        if (history.length && newPath === history[0])
-          // Ignore push if navigate to same path (for some weird unknown reasons?)
-          return history;
+        // instead of pushing, we are popping the history when the same page is navigated to
+        if (history.length > 1 && newPath === history[1]) {
```
Comment (Jacobjeevan) [inline src/Providers/HistoryAPIProvider.tsx]: could add or pop here no?

**Review by Jacobjeevan — COMMENTED** [review]
minor things

File: src/pages/Facility/billing/account/CreateInvoice.tsx [hunk 5]
```diff
@@ -417,14 +416,6 @@ export function CreateInvoicePage({
       {showHeader && (
         <div className="flex items-start justify-between flex-col sm:flex-row gap-4 sm:items-center border-b-3 border-double pb-4">
           <div className="flex gap-3 sm:gap-6 flex-col md:flex-row">
-            <BackButton
-              variant="link"
-              className="px-0 justify-start"
-              fallbackUrl={`/facility/${facilityId}/billing/account/${accountId}`}
-            >
-              <ChevronLeft />
-              <span>{t("back")}</span>
```
Comment (rithviknishad) [inline src/pages/Facility/billing/account/CreateInvoice.tsx:426]: was this removed intentionally?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Facility/billing/account/CreateInvoice.tsx (hunk 5 above)
Comment (NikhilA8606) [reply src/pages/Facility/billing/account/CreateInvoice.tsx:426]: Yeah, because there is already a cancel button , so there is no need for a back button

File: src/Providers/HistoryAPIProvider.tsx [hunk 6]
```diff
@@ -7,20 +7,26 @@ export const ResetHistoryContext = createContext(() => {});
...
+      setHistory((history) => {
+        // instead of pushing, we are popping the history when the same page is navigated to
+        if (
+          (history.length > 1 && newPath === history[1]) ||
+          action === "pop"
+        ) {
           return history.slice(1);
+        }
+
+        // replace navigation
```
Comment (rithviknishad) [inline src/Providers/HistoryAPIProvider.tsx]:
```suggestion
```

File: src/Providers/HistoryAPIProvider.tsx [hunk 7]
```diff
@@ -7,20 +7,26 @@ export const ResetHistoryContext = createContext(() => {});
...
-          // Ignore push if navigate to same path (for some weird unknown reasons?)
-          return history;
+    (location) => {
+      const newPath = location.fullPath + location.search;
+      const action = location.initiatedBy;
 
-        if (history.length > 1 && newPath === history[1])
-          // Pop current path if navigate back to previous path
+      setHistory((history) => {
+        // instead of pushing, we are popping the history when the same page is navigated to
```
Comment (rithviknishad) [inline src/Providers/HistoryAPIProvider.tsx]:
```suggestion
        // Pop current path if navigate back to previous path
```

File: src/Providers/HistoryAPIProvider.tsx [hunk 8]
```diff
@@ -7,20 +7,26 @@ export const ResetHistoryContext = createContext(() => {});
...
           return history.slice(1);
+        }
+
+        // replace navigation
+        if (action === "replace") {
+          return [newPath, ...history.slice(1)];
+        }
 
-        // Otherwise just push the current path
+        // normal navigation or push navigation
```
Comment (rithviknishad) [inline src/Providers/HistoryAPIProvider.tsx]:
```suggestion
        // Otherwise just push the current path
```

**Review by rithviknishad — APPROVED** [review]
