### PR TITLE
Fix: Add a new list view to locations in the facility settings

### LINKED ISSUE #10376: Add a new list view to locations in the facility settings
**Describe the Issue**

Add a new list view to the location section in the facility settings

**Link to Figma**

https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=7769-8053&t=lATfj2xH4or01kbE-1

*Existing Design*

Image

*New Design*

Image

### PR DESCRIPTION
**Pull request by abhimanyurajeesh**
## Proposed Changes

- Fixes #10376 

## Desktop view
image

## Mobile view
image

## Added new search feature
Added client side filtering and auto expand on search as we are already fetching all the data using pagination.

https://github.com/user-attachments/assets/740deed3-bb25-4e76-93bb-87a65e1b4010

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Enhanced on-screen instructions with updated text for clearer action prompts.
  - Revamped location management with a tabbed interface that lets you switch between list and map views.
  - Improved organization of locations through hierarchical, expandable rows and refined filtering for a more intuitive, streamlined experience.
  - Introduced a loading state and skeleton loader for better user feedback while fetching location data.

### CODE REVIEW

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 1]
```diff
@@ -59,72 +76,335 @@ export default function LocationList({ facilityId }: Props) {
...
-                  onEdit={handleEditLocation}
+  const getChildren = (parentId: string) => {
+    return tableData.filter((loc) => {
+      const isChild = loc.parent?.id === parentId;
+      const matchesSearch =
+        !searchQuery ||
+        loc.name.toLowerCase().includes(searchQuery.toLowerCase());
+      return isChild && matchesSearch;
+    });
+  };
```
[the remark this answers is not in the document]
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: ya, let me try something else

**Comment by abhimanyurajeesh** [comment]
Disable/commented out Map View as @shivankacker is working on that. (#10377)

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 2]
```diff
@@ -59,72 +118,321 @@ export default function LocationList({ facilityId }: Props) {
...
+                  variant="link"
+                  onClick={() => toggleRow(location.id)}
+                >
+                  {isExpanded ? (
+                    <CareIcon icon="l-angle-down" className="h-5 w-5" />
+                  ) : (
+                    <CareIcon icon="l-angle-right" className="h-5 w-5" />
+                  )}
+                </Button>
+              ) : location.parent ? (
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/locations/LocationList.tsx]: this results in the right arrow being shown at top level since location.parent is an empty object (you would need to check for Object.keys length instead).

But, let's display the angle icons at root level regardless of whether they have a child or not.

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 3]
```diff
@@ -59,72 +118,321 @@ export default function LocationList({ facilityId }: Props) {
...
+            </div>
+            {isTopLevel && (
+              <div className="flex justify-between items-center gap-2">
+                <div className="flex-1">
+                  {children.length > 0 && (
+                    <Button
+                      variant="white"
+                      size={isMobile ? "xs" : "sm"}
+                      onClick={toggleAllChildren}
+                      className="opacity-100 lg:opacity-0 group-hover:opacity-100 transition-opacity gap-2"
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/locations/LocationList.tsx]: let's not do this for the buttons; display them at all times.

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 4]
```diff
@@ -1,49 +1,108 @@
...
+    [tableData],
+  );
+
+  const getChildren = useCallback(
+    (parentId: string) => {
+      const children = childrenMap.get(parentId) || [];
+      if (!searchQuery) return children;
+
+      return children.filter((loc) =>
+        loc.name.toLowerCase().includes(searchQuery.toLowerCase()),
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/locations/LocationList.tsx]: hmm 🤔  this wouldn't work since you are doing filtering for both top and children.

For example: for children to render, top level would have to match as well.

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 5]
```diff
@@ -59,72 +118,321 @@ export default function LocationList({ facilityId }: Props) {
...
+                    variant="white"
+                    size={isMobile ? "xs" : "sm"}
+                    asChild
+                    className="opacity-100 lg:opacity-0 group-hover:opacity-100 transition-opacity"
+                  >
+                    <Link
+                      href={`/location/${location.id}`}
+                      className="text-gray-900 flex items-center"
+                    >
+                      <CareIcon icon="l-eye" className="h-4 w-4" />
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/locations/LocationList.tsx]: switch to using l-arrow-up-right for both desktop and mobile

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 6]
```diff
@@ -59,72 +118,321 @@ export default function LocationList({ facilityId }: Props) {
...
+                      {t("add_location")}
+                    </span>
+                    <span className="inline-block">
+                      {t("to_add_main_location")}.
+                    </span>
+                  </div>
+                  {/* Desktop view text */}
+                  <div className="hidden lg:flex flex-wrap items-baseline">
+                    <span className="inline-block mr-1">
+                      {t("hover_focus_reveal")}
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/locations/LocationList.tsx]: let's not break it up, as it wouldn't work for other languages.

Also adjust the text once hover is removed, and add l-arrow-up-right icon next to see details in the text - similar to mobile view.

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 7]
```diff
@@ -1,49 +1,108 @@
...
+  const [activeTab, setActiveTab] = useView("locations", "list");
+  const [expandedRows, setExpandedRows] = useState<Record<string, boolean>>({});
+
+  const LIMIT = 1000;
 
   const { data, isLoading } = useQuery({
-    queryKey: ["locations", facilityId, page, limit, searchQuery],
-    queryFn: query.debounced(locationApi.list, {
+    queryKey: ["locations", facilityId, searchQuery],
+    queryFn: query(locationApi.list, {
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/locations/LocationList.tsx]: let's switch to using query.paginated instead of high limit.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
Check the expand all behavior; once I have manually expanded, expand all button should become collapse all (it doesn't, instead user has to click twice).

File: src/pages/Facility/settings/locations/LocationList.tsx (hunk 2 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: done

File: src/pages/Facility/settings/locations/LocationList.tsx (hunk 3 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: sure, did that because it was the feature described in the design.

Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: Anyways removing this and I will update the info tag.

File: src/pages/Facility/settings/locations/LocationList.tsx (hunk 4 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: oh ya, let me make the change.

File: src/pages/Facility/settings/locations/LocationList.tsx (hunk 5 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: okay

File: src/pages/Facility/settings/locations/LocationList.tsx (hunk 6 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: done

File: src/pages/Facility/settings/locations/LocationList.tsx (hunk 7 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: done

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 8]
```diff
@@ -59,72 +143,364 @@ export default function LocationList({ facilityId }: Props) {
...
+                toggleRow={toggleRow}
+                getChildren={getChildren}
+                indent={1}
+              />
+            ))}
+          </TableBody>
+        </Table>
+      </div>
+    );
+  };
```
Comment (rithviknishad) [inline src/pages/Facility/settings/locations/LocationList.tsx]: let's NOT define function as component inline another component. This will cause issues with unable to being properly memoized as everytime the parent component re-renders, the function's reference changes and react sees it as a new component everytime. 

Create a new component under `components` directory, and use that here instead.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/locations/LocationList.tsx (hunk 8 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: Done, lets change it then.

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 9]
```diff
@@ -59,72 +139,224 @@ export default function LocationList({ facilityId }: Props) {
...
+          newExpandedRows[currentLoc.parent.id] = true;
+          currentLoc = allLocations.find(
+            (loc) => loc.id === currentLoc.parent?.id,
+          )!;
+        }
+      }
+    });
+
+    setExpandedRows(newExpandedRows);
+  }, [searchQuery, data?.results]);
```
[the remark this answers is not in the document]
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: done

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 10]
```diff
@@ -59,72 +139,228 @@ export default function LocationList({ facilityId }: Props) {
...
+
+  const renderListView = () => {
+    if (isLoading) {
+      return <TableSkeleton count={6} />;
+    }
```
Comment (rithviknishad) [inline src/pages/Facility/settings/locations/LocationList.tsx]: still not solved :/

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/locations/LocationList.tsx (hunk 10 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: my bad : )

Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: Hopefully now its solved : )

**Comment by nihal467** [comment]
LGTM

**Comment by abhimanyurajeesh** [comment]
The latest commits replaced the `getLocationFormLabel(location.form)` call with `t(location_form${location.form})` to use the translation system directly.

**Review by rithviknishad — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
