### PR TITLE
Fix state & district autofill & multiple other small issues in Patient Registration page

### LINKED ISSUE #9668: Entering pincode does not auto fill state
**Describe the bug**
- Entering pincode does not autofill state. As missing autofill for state, it is also not rendering and autofilling district in the patient registration page.

**To Reproduce**

1. Go to `search patients` tab.
2. Click on '.Add New Patient`.
3. Fill in pincode input 

**Expected behavior**
It should autofill as mentioned

**Screenshots**

https://github.com/user-attachments/assets/cd7e7bdd-e009-445b-b38f-4c91284dc9ea

**Probably Related**

https://github.com/ohcnetwork/care_fe/issues/9649

### LINKED ISSUE #9934: State, District, related info are not being prefilled in the patient details update page
image

the update patients page is not pre-filling, patients state,district, etc... from the dropdown, can you fix it, it exist in develop also

_Originally posted by @nihal467 in https://github.com/ohcnetwork/care_fe/issues/9854#issuecomment-2586711808_

### PR DESCRIPTION
**Pull request by yash-learner**
## Proposed Changes

- Fixes #9668 
- Fixes rendering asterisk.
- Notifies parent on an organisation selection removal by clicking trash icon
- Tiny UI changes.
- Render error message properly in organization selector

---

[auto_fill_state_&_district_based_on_pincode.webm](https://github.com/user-attachments/assets/ef808a63-b03c-49a5-ae6d-e303935cac5d)

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Release Notes

- **New Features**
  - Enhanced pincode handling with automatic state and district retrieval
  - Added visual notification for autofilled pincode information

- **Improvements**
  - Streamlined patient registration workflow
  - Simplified organization selection process

- **Test Updates**
  - Updated patient creation test data and page object model
  - Removed manual state and district selection from test scenarios

The changes focus on improving the patient registration experience by introducing more intelligent location-based data entry and simplifying the user interface.

### CODE REVIEW

File: src/components/Patient/PatientRegistration.tsx [hunk 1]
```diff
@@ -304,6 +320,22 @@ export default function PatientRegistration(
...
+          parent: parentId || "",
+          name,
+        },
+      })({ signal: new AbortController().signal });
+      return data.results?.[0];
+    } catch (error) {
+      toast.error("Error fetching organization");
+      return undefined;
+    }
+  }
```
Comment (yash-learner) [inline src/components/Patient/PatientRegistration.tsx]: At some point, we may need to extract this into a separate hook

**Review by rithviknishad — COMMENTED** [review]
not a fan of this approach. how about we stick with how dependent queries are made as per tanstacks docs? 

https://tanstack.com/query/latest/docs/framework/react/guides/dependent-queries#usequery-dependent-query

this way we wouldn't need to try catch either and stick with the simplicity.

cc @bodhish

File: src/components/Patient/PatientRegistration.tsx (hunk 1 above)
Comment (Jacobjeevan) [reply src/components/Patient/PatientRegistration.tsx]: Yea, go ahead and do that since same logic is being used in #9662.

Also check Rithvik's comment below.

cc: @Mahendar0701

**Comment by yash-learner** [comment]
> not a fan of this approach. how about we stick with how dependent queries are made as per tanstacks docs?
> 
> https://tanstack.com/query/latest/docs/framework/react/guides/dependent-queries#usequery-dependent-query
> 
> this way we wouldn't need to try catch either and stick with the simplicity.
> 
> cc @bodhish

@rithviknishad 

Updated it in this https://github.com/ohcnetwork/care_fe/pull/9711/commits/bdd739f85d33c1c948bb4eb9e8583443c8f49835, https://github.com/ohcnetwork/care_fe/pull/9711/commits/6905db313c932aabafc279d554c5f90ccb07571a. Does it look good ?

File: src/hooks/useOrganization.ts [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+  enabled?: boolean;
+}
+
+export function useOrganization({
+  orgType = "",
+  parentId = "",
+  name = "",
+  enabled = true,
+}: UseOrganizationParams) {
+  const { data, isLoading, isError } = useQuery<{ results: Organization[] }>({
```
Comment (rithviknishad) [inline src/hooks/useOrganization.ts]:
```suggestion
  const { data, isLoading, isError } = useQuery({
```

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
