### PR TITLE
Switched to CARE UI components in facility tiles

### LINKED ISSUE #4113: Uneven padding of chips in facility tiles
**Describe the bug**
Uneven height of chips in facility tiles

**To Reproduce**
See facility list page

**Expected behavior**
Tiles should be of the same height and contain the same amount of padding

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chromium
- Version: Latest

### PR DESCRIPTION
**Pull request by skks1212**
## Proposed Changes

- Fixes #4113 
- Switched to CUI components in facility tiles.
- Reverted to font awesome icons for facility features as current ones were inconsistent.
- Added new chip sizes
- ButtonV2 can now be Links

After:
image

Before:
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

File: src/Components/Common/components/ButtonV2.tsx [hunk 1]
```diff
@@ -53,6 +54,14 @@ export type ButtonProps = RawButtonProps &
...
      */
     loading?: boolean | undefined;
+    href?: string | undefined;
+    /**
+     * A button will convert to a link if the `href` prop is set.
+     */
+    target?: string | undefined;
+    /**
+     * Link target. Only applicable if `href` is set.
+     */
```
Comment (rithviknishad) [inline src/Components/Common/components/ButtonV2.tsx]: Doc comments come above the intended line so that when we hover on 'href' in the editor, it shows up.
```suggestion
    /**
     * A button will convert to a link if the `href` prop is set.
     */
    href?: string | undefined;
    /**
     * Link target. Only applicable if `href` is set.
     */
    target?: string | undefined;
```

**Review by rithviknishad — APPROVED** [review]

File: src/Components/Common/components/ButtonV2.tsx (hunk 1 above)
Comment (shivankacker) [reply src/Components/Common/components/ButtonV2.tsx]: Whoops, thanks for pointing that out 😀

**Comment by rithviknishad** [comment]
- @skks1212 https://github.com/coronasafe/care_fe/pull/4071 will be removing support for unicons. So we could either use CareIcon once it's merged which has all the unicons, or font-awesome.

**Comment by nihal467** [comment]
@skks1212 
image

- [ ] in the responsive view, the buttons are inconsistent
- [ ] the buttons are not showing the complete text in responsive view

**Comment by nihal467** [comment]
@skks1212 marking it for team discussion required for discussing some points

photo-2

- reverting back to font-awesome icons
- the icon of notify  button are been changed
- the size of badges are been reduced

**Comment by nihal467** [comment]
@skks1212 marking it for team discussion required for final approval 

image
image

image

- [ ] Which icon should we be following for the patient button ( For discussion on EOD )

**Comment by nihal467** [comment]
@skks1212 the icon for the patient button are to be changed

**Comment by nihal467** [comment]
@skks1212 icon LGTM, 

**Note for team discussion** 

the icon is inconsistent across the platform

image

**Comment by nihal467** [comment]
@skks1212 check the cypress issue

**Comment by shivankacker** [comment]
@nihal467 as discussed in weekly review today, sidebar icon has been changed to the new icon. Patient list page icon will remain the same.

**Comment by khavinshankar** [comment]
@skks1212 can you take off the failing cypress tests, most likely merging the latest develop branch should fix it

**Comment by shivankacker** [comment]
@khavinshankar tests keep failing, can't figure out why : (

**Comment by khavinshankar** [comment]
@skks1212 the remaining failing cypress tests should be fixed once auto-update is merged, so can you just handle the merge conflicts

cc: @nihal467

**Review by khavinshankar — APPROVED** [review]
