### PR TITLE
Fix: Breadcrumbs redirection to patient edit consultation form

### LINKED ISSUE #8759: Breadcrumbs redirection to patient edit consultation form is not working as expected
**Describe the bug**

from the patient consent record page, when we click on the consultation, in the breadcrumbs, we are taken to a new consultation form,not the existing consultation of the patient

**To Reproduce**

1. Go to any active consultation
2. Click on manage patients and click on the consent records
3. view the breadcrumbs on the left side and click on the consultation

**Expected behavior**

- [ ] When we click on the consultation in the breadcrumbs, it should take the user to the patient's existing consultation page

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by shauryag2002**
## Proposed Changes

- Fixes #8759 
- Added Consultation breadcrumb with URI for updating consultation
- Updated backUrl for consultation update 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Introduced a breadcrumb navigation entry for easier access to consultation details.
	- Updated the `ConfirmDialog` to dynamically display patient code status for consent records.
	- Added a new breadcrumb entry in the `ConsultationDetails` component for direct navigation to the consultation update page.

- **Improvements**
	- Cleaned up URL structure by modifying the `backUrl`.
	- Enhanced upload handling logic for better interaction with existing consent records.
	- Updated rendering logic for consultation tab buttons to conditionally display based on consultation state and user permissions.
	- Minor formatting adjustments for improved clarity in tab navigation.

### CODE REVIEW

File: src/components/Patient/PatientConsentRecords.tsx [hunk 1]
```diff
@@ -107,6 +107,10 @@ export default function PatientConsentRecords(props: {
       crumbsReplacements={{
         [facilityId]: { name: patient?.facility_object?.name },
         [patientId]: { name: patient?.name },
+        consultation: {
+          name: "Consultation",
+          uri: `/facility/${facilityId}/patient/${patientId}/consultation/${consultationId}/update`,
```
Comment (rithviknishad) [inline src/components/Patient/PatientConsentRecords.tsx:117]: shouldn't this ideally be taken to the consultation dashboard instead of the consultation form?

```suggestion
          uri: `/facility/${facilityId}/patient/${patientId}/consultation/${consultationId}`,
```

File: src/components/Patient/PatientConsentRecords.tsx [hunk 2]
```diff
@@ -116,7 +120,7 @@ export default function PatientConsentRecords(props: {
               : patient?.last_consultation?.suggestion_text,
         },
       }}
-      backUrl={`/facility/${facilityId}/patient/${patientId}/consultation/${consultationId}/`}
+      backUrl={`/facility/${facilityId}/patient/${patientId}/consultation/${consultationId}/update`}
```
Comment (rithviknishad) [inline src/components/Patient/PatientConsentRecords.tsx:128]:
```suggestion
      backUrl={`/facility/${facilityId}/patient/${patientId}/consultation/${consultationId}`}
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by nihal467** [comment]
image
image

- [ ] the issue still exist, can you recheck the PR

**Comment by nihal467** [comment]
@shauryag2002 what is the status on the PR ?

**Comment by shauryag2002** [comment]
> @shauryag2002 what is the status on the PR ?

I am little busy past few days, resolving requested changes today!

**Comment by nihal467** [comment]
LGTM

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
