### PR TITLE
fix: Add validations for empty values in Valueset

### LINKED ISSUE #12349: Improve error handling by displaying user friendly error message
**Describe the bug**
Currently when the user is not passing values in valueset as expected, it is showing error  message which is not user friendly

**To Reproduce**

1. Go to [link](https://care.ohc.network/admin/valuesets/pupil_size/edit)
2. Click on add filter
3. Do not pass any value here and click on save

**Expected behavior**
The error message should be user friendly

**Screenshots**

https://github.com/user-attachments/assets/eacaf081-bb34-4ec0-9496-c0f19d5a6150

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### LINKED ISSUE #12568: Restrict unwanted API request in value set
**Describe the bug**

Whenever we are opening an inclusive and exclusive concept or filter, it's throwing an unwanted preview API request  in valueset

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Tanuj1718**
## Proposed Changes

- Fixes #12349
     - Added validations for empty values in filter and concept fields
- Fixes #12568

https://github.com/user-attachments/assets/acbfae7f-c11e-4f44-9b8b-8601118ede91

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
  - Removed unnecessary string concatenation from request parameters, ensuring accurate data retrieval.
  - Query execution is now conditioned on non-empty search input to optimize performance and results.
- **Style**
  - Validation error messages are now displayed inline within form fields for better user feedback.
- **New Features**
  - Enhanced form validation with detailed error messages for multiple input fields.
  - Live preview updates reflecting real-time form changes for improved user experience.
  - Added controls to toggle preview panel visibility, improving user interaction.

### CODE REVIEW

File: src/components/ValueSet/ValueSetForm.tsx [hunk 1]
```diff
@@ -319,14 +337,29 @@ export function ValueSetForm({
...
-                op: z.string(),
-                value: z.string(),
+                property: z.string().refine((val) => val !== "", {
+                  message: t("property_required"),
+                }),
+                op: z.string().refine((val) => val !== "", {
+                  message: t("operator_required"),
+                }),
+                value: z.string().refine((val) => val !== "", {
+                  message: t("value_required"),
```
Comment (rithviknishad) [inline src/components/ValueSet/ValueSetForm.tsx]: just re-use the existing `field_required` instead of keeping the error messages very specific for each field!


```suggestion
                  message: t("field_required"),
                }),
                op: z.string().refine((val) => val !== "", {
                  message: t("field_required"),
                }),
                value: z.string().refine((val) => val !== "", {
                  message: t("field_required"),
```

File: src/components/ValueSet/ValueSetForm.tsx [hunk 2]
```diff
@@ -319,14 +337,29 @@ export function ValueSetForm({
...
             .optional(),
           filter: z
             .array(
               z.object({
-                property: z.string(),
-                op: z.string(),
-                value: z.string(),
+                property: z.string().refine((val) => val !== "", {
+                  message: t("property_required"),
+                }),
```
Comment (rithviknishad) [inline src/components/ValueSet/ValueSetForm.tsx]: see how required fields are done in other places in care...

image

**Review by rithviknishad — CHANGES_REQUESTED** [review]
lgtm, but we could do better

File: src/components/ValueSet/CodingField.tsx [hunk 3]
```diff
@@ -81,13 +86,14 @@ export const CodingField = ({
                 }}
               />
             </FormControl>
+            <FormMessage>{error?.message}</FormMessage>
```
Comment (rithviknishad) [inline src/components/ValueSet/CodingField.tsx]: see how `FormMessage` is used in other places in care... we don't need to de-construct `fieldState` and pass it. shadcn-ui's form components does these automatically!

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image

- there is unwanted request fired when we open the filters in the rules, the issue is present in the develop as well, @Tanuj1718 can you solve that issue as well in this PR

**Comment by Tanuj1718** [comment]
> image
> 
> * there is unwanted request fired when we open the filters in the rules, the issue is present in the develop as well, @Tanuj1718 can you solve that issue as well in this PR

@rithviknishad the requests to the backend are because of Valueset preview. Should i add default values in filter fields to prevent the validation error?

**Comment by rithviknishad** [comment]
@Tanuj1718 do you think the requests won't be sent even if we set default values? 🤔

**Comment by Tanuj1718** [comment]
> @Tanuj1718 do you think the requests won't be sent even if we set default values? 🤔

@rithviknishad It will be sent but the validation error will not appear. We are fetching the data in valueset preview so the request will be sent in both the cases.

**Comment by rithviknishad** [comment]
don't you think that's more of hack? 🤔 why do we have to make an API request on mount in the first place? 🤔 
is it necessary?

**Comment by Tanuj1718** [comment]
@rithviknishad oh got it. i think we should remove "termonologies" also? As i don't get any reason to append this.🤔

Screenshot 2025-05-25 at 4 04 35 PM

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
