### PR TITLE
fix: replace custom loading spinners with skeleton components

### LINKED ISSUE #14749: Replace custom loading spinners with skeleton components in FacilityDetailsPage and UserDepartmentsTab
**Describe the bug**

Found two places where custom loading spinners are used instead of skeleton loaders. This is inconsistent with the rest of the codebase, which uses skeleton components for better UX. The current spinners don't show any content structure, making it harder for users to understand what's loading.

**To Reproduce**

**Issue 1: FacilityDetailsPage**
1. Log out of the application (or use incognito mode)
2. Navigate to `/facility/{facility-id}` (public facility details page)
3. Enable "Slow 3G" or "3G" throttling in browser DevTools Network tab
4. Refresh the page
5. You'll see a centered spinning loader icon instead of skeleton placeholders

Image

**Issue 2: UserDepartmentsTab**
1. Log in to the application
2. Navigate to `/facility/{facility-id}/users`
3. Click on any user to view their details
4. Click on the "Departments" tab
5. Enable "Slow 3G" or "3G" throttling in browser DevTools Network tab
6. Refresh the page or navigate away and back
7. You'll see a centered spinning loader icon in the departments section instead of skeleton placeholders

Image

**Expected behavior**

Both pages should use skeleton loaders that show the content structure:
- **FacilityDetailsPage**: Should show skeleton for facility card + user cards grid (using `CardGridSkeleton`)
- **UserDepartmentsTab**: Should show skeleton for department cards grid (using `CardGridSkeleton`)

This provides better UX as users can see the layout shape while content loads, which is consistent with other pages in the app.

**Desktop:**

- OS: macOS
- Browser: Chrome
- Version: Latest

**Smartphone:**

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

**Additional context**

The codebase already has skeleton components available in `src/components/Common/SkeletonLoading.tsx`:
- `CardGridSkeleton` - for grid layouts
- `CardListSkeleton` - for list layouts
- `TableSkeleton` - for tables
- `FormSkeleton` - for forms

Most other pages in the app use these skeleton components, so these two instances should be updated for consistency.

**Files affected:**
- `src/pages/Facility/FacilityDetailsPage.tsx:59-66` - custom spinner
- `src/components/Users/UserDepartmentsTab.tsx:126-131` - custom spinner

**Additional Context:**

I've verified both issues by navigating to the pages with network throttling enabled. The skeleton components already exist in the codebase, so this is a straightforward replacement. I'll make sure the skeleton count matches the expected number of items displayed on each page.

### PR DESCRIPTION
**Pull request by harsh04044**
## Proposed Changes

Fixes #14749 

I found two places where custom loading spinners were being used instead of skeleton loaders. This was inconsistent with the rest of the codebase, which uses skeleton components for better UX. I've replaced both spinners with appropriate skeleton components:

- **FacilityDetailsPage**: Replaced the centered spinner with skeleton loaders that show the facility card structure and user cards grid layout
- **UserDepartmentsTab**: Replaced the centered spinner with `CardGridSkeleton` to match the department cards grid layout

The skeleton loaders provide better UX by showing users the content structure while data loads, which is consistent with how other pages in the app handle loading states.

**Screenshots:**
image
image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [x] Update [product documentation](https://docs.ohc.network). (N/A - internal code improvement)
- [x] Ensure that UI text is placed in I18n files. (N/A - no new UI text added)
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue. (Screenshots provided in issue)
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **New Features**
  * Replaced spinners with skeleton headers and responsive skeleton card grids for User Departments and Facility Details to improve perceived loading.
  * Added a public endpoint to fetch schedulable facility users for listing available users at a facility.

* **Refactor**
  * Updated loading-state structure to better mirror final content layout while preserving existing error handling.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by harsh04044** [comment]
Reference of previous PR :

link : https://github.com/ohcnetwork/care_fe/pull/14751#event-21585036167

in this @abhimanyurajeesh  gave some suggestions

i will address them in the next commit

**Review by abhimanyurajeesh — CHANGES_REQUESTED** [review]
I had requested changes in the closed PR, but I don’t see them applied here. Please make the necessary changes.

**Comment by harsh04044** [comment]
> I had requested changes in the closed PR, but I don’t see them applied here. Please make the necessary changes.

@abhimanyurajeesh  i have addresed your review  in the latest commit

**Review by nihal467 — APPROVED** [review]

File: src/pages/Facility/FacilityDetailsPage.tsx [hunk 1]
```diff
@@ -41,9 +43,9 @@ export function FacilityDetailsPage({ id }: Props) {
   });
 
   const { data: docResponse, error: docError } = useQuery({
-    queryKey: [routes.getScheduleAbleFacilityUsers, id],
-    queryFn: query(routes.getScheduleAbleFacilityUsers, {
-      pathParams: { facility_id: id },
+    queryKey: ["facilityUsers", id],
```
Comment (Jacobjeevan) [inline src/pages/Facility/FacilityDetailsPage.tsx]: wrong api, be sure to test when changing APIs.

Add getPublicScheduleableFacilityUsers under getPublicScheduleableFacilityUser in scheduleApi.ts and use that. 

cc: @nihal467

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Facility/FacilityDetailsPage.tsx (hunk 1 above)
Comment (harsh04044) [reply src/pages/Facility/FacilityDetailsPage.tsx]: @Jacobjeevan  @nihal467  I've addressed this in my latest commit. I'll make sure to test API changes myself in the future. Thanks for the feedback

**Review by nihal467 — APPROVED** [review]

File: src/pages/Facility/FacilityDetailsPage.tsx (hunk 1 above)
Comment (Jacobjeevan) [reply src/pages/Facility/FacilityDetailsPage.tsx]: use diff query key. Something like "facilityUsersPublic" should work.

@harsh04044

File: src/types/scheduling/scheduleApi.ts [hunk 2]
```diff
@@ -186,6 +186,11 @@ export default {
       method: HttpMethod.GET,
       TRes: Type<UserReadMinimal>(),
     },
+    getPublicScheduleableFacilityUsers: {
+      path: "/api/v1/facility/{facility_id}/schedulable_users/",
+      method: HttpMethod.GET,
+      TRes: Type<PaginatedResponse<UserReadMinimal>>(),
+    },
```
Comment (abhimanyurajeesh) [inline src/types/scheduling/scheduleApi.ts]: where is this used?

**Review by abhimanyurajeesh — CHANGES_REQUESTED** [review]

File: src/types/scheduling/scheduleApi.ts (hunk 2 above)
Comment (harsh04044) [reply src/types/scheduling/scheduleApi.ts]: @abhimanyurajeesh 
This endpoint is used in `src/pages/Facility/FacilityDetailsPage.tsx` (lines 44-48) to fetch schedulable users for a facility. 

It was added to address feedback from @Jacobjeevan to replace the incorrect `facilityApi.getUsers` usage.

File: src/pages/Facility/FacilityDetailsPage.tsx (hunk 1 above)
Comment (harsh04044) [reply src/pages/Facility/FacilityDetailsPage.tsx]: @Jacobjeevan  i have chaged querykey in my latest commmit

File: src/types/scheduling/scheduleApi.ts (hunk 2 above)
Comment (yash-learner) [reply src/types/scheduling/scheduleApi.ts]: @harsh04044 revert the change to latest develop 

In this commit https://github.com/harsh04044/care_fe/commit/83159d5489dac99ed4da8cc87f1bb1a28a90f80c#diff-adf19fecbf15ca8f915dfcbf4d6f2fe4d46b7e7ad5716056ad3f1bcecbfe34a4 you had changed to 

image

That accidental change had lead to Jeevan's comment.


----

On develop

https://github.com/ohcnetwork/care_fe/blob/develop/src/pages/Facility/FacilityDetailsPage.tsx

image

**Review by yash-learner — CHANGES_REQUESTED** [review]

File: src/pages/Facility/FacilityDetailsPage.tsx (hunk 1 above)
Comment (yash-learner) [reply src/pages/Facility/FacilityDetailsPage.tsx]: https://github.com/ohcnetwork/care_fe/pull/14880#discussion_r2745816049

**Comment by harsh04044** [comment]
@yash-learner i have addressed your suggestion

**Review by yash-learner — APPROVED** [review]
