### PR TITLE
Users are able to create Valueset during questionnaire creation.

### LINKED ISSUE #12527: Create Value Set Directly Inside Questionnaire Builder
When users are adding questions that require coded answers, they must leave the questionnaire builder, create the set, save it, and return. This context-switch slows development and increases the chance of errors or omissions. Would be useful to have a sheet or something similar to create value sets directly inside the questionnaire builder.

Instance - There are many repeated and structured list  which would be instance based, as in Palliative Care having assistive devices that are available in the system than the whole list.

### LINKED ISSUE #12625: Valueset Missing from Search Field During Edit Questionnaire
**Describe the bug**

**To Reproduce**

1. Create a questionnaire with type "choice" and option as ValueSet (select a ValueSet that isn't listed on the first page).
2. Edit the Questionnaire
3. See error

**Expected behavior**
The Valuset should be visible while editing

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Proposed Changes
- Fixes #12527 
- Fixes #12625 
- Added a button for "Create Valueset"
- Button opens a sheet form for create value set
- Valueset are added to the valueset list and showed in the input field at the same of creation

Demo Video :

[Screencast from 2025-06-12 00-04-26.webm](https://github.com/user-attachments/assets/b97c3d6f-906f-45af-a2a8-541f6bea875e)

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Added the ability to select or create a ValueSet directly within the questionnaire editor via a new component.
- **Improvements**
  - Enhanced internationalization by translating additional UI labels and messages.
  - Success messages for ValueSet creation and updates are now localized.
  - Added new English localization entries for questionnaire URLs and ValueSet actions.
  - Improved navigation and feedback after creating or updating a ValueSet.

### CODE REVIEW

File: src/components/ValueSet/ValueSetEditor.tsx [hunk 1]
```diff
@@ -18,10 +18,10 @@ import { ValueSetForm } from "./ValueSetForm";
 
 interface ValueSetEditorProps {
   slug?: string; // If provided, we're editing an existing valueset
+  onSuccess?: (data: any) => void;
```
Comment (AdityaJ2305) [inline src/components/ValueSet/ValueSetEditor.tsx]: Can we don't use `any` here and declare type if i'm not wrong it is `ValuesetBase` right ?

Comment (NikhilA8606) [reply src/components/ValueSet/ValueSetEditor.tsx]: yeah , i saw coderabbit suggestion , but it will not work

Comment (AdityaJ2305) [reply src/components/ValueSet/ValueSetEditor.tsx]: oh didn't see coderabbit comment, was on file section while writing comment

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 2]
```diff
@@ -2012,24 +2014,50 @@ function QuestionEditor({
...
+                          </Button>
+                        </SheetTrigger>
+                        <SheetContent
+                          side="right"
+                          className="w-full sm:max-w-2xl overflow-y-auto"
+                        >
+                          <ValueSetEditor
+                            onSuccess={(data) => {
+                              setIsSheetOpen(false);
+                              updateField("answer_value_set", data.slug);
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]: This will work if value set count < 14 and/or the newly created value set appears on first page.

You will need to handle if that isn't the case.

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 3]
```diff
@@ -2231,23 +2259,27 @@ function QuestionEditor({
                         <SelectValue />
                       </SelectTrigger>
                       <SelectContent>
-                        <SelectItem value="equals">Equals</SelectItem>
-                        <SelectItem value="not_equals">Not Equals</SelectItem>
-                        <SelectItem value="greater">Greater Than</SelectItem>
-                        <SelectItem value="less">Less Than</SelectItem>
+                        <SelectItem value="equals">{t("equals")}</SelectItem>
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]: Don't change for for now. Enable when is being modified anyways.

**Review by Jacobjeevan — DISMISSED** [review]

**Review by rithviknishad — APPROVED** [review]

**Review by rithviknishad — CHANGES_REQUESTED** [review]
in edit questionnaire workflow, if the valueset is not present in the first page, it is not being displayed as intended.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
