### PR TITLE
Fix: Asset tab facility and location badges are malfunctioning

### LINKED ISSUE #6473: Asset tab facility and location badges are malfunctioning
**Describe the bug**

the facility and location badges in the asset tab, even though we click the cross button to remove applied filters, the filter get removed but the badges doesn't disappear

**To Reproduce**

1. Go to asset tab
2. Click on advance filter and apply facility and location filters
3. remove the applied filters by clicking the cross button in badges
4. See error that badge still there

**Expected behavior**

when you click the cross button to remove the badge, it should reset the data along with removing badge in asset tab

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Pranshu1902**
### <samp>🤖 Generated by Copilot at 91b364d</samp>

This pull request improves the user interface and functionality of the assets list component. It adds state variables to show the facility name and location in the filter section, and uses the `useQuery` hook to refetch data based on filter changes.

## Proposed Changes

- Fixes #6473 
http://127.0.0.1:4000/assets?page=1&limit=18&facility=df1a22fb-1875-4949-af85-15d1917b8bfd&asset_type=&asset_class=&status=&location=&warranty_amc_end_of_validity_before=&warranty_amc_end_of_validity_after=
Remove the facility and location filter when the cross is clicked
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 91b364d</samp>

*  Add a state variable `facility_location` to store and display the location name of the selected facility in the assets list ([link](https://github.com/coronasafe/care_fe/pull/6474/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49R50), [link](https://github.com/coronasafe/care_fe/pull/6474/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49L109-R120), [link](https://github.com/coronasafe/care_fe/pull/6474/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49L373-R383))
*  Add a state variable `facility_name` to store and display the facility name of the selected facility in the assets list ([link](https://github.com/coronasafe/care_fe/pull/6474/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49R93-R96))
*  Rename the variable `location` to `locationData` to avoid confusion with `facility_location` in `AssetsList.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6474/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49L103-R108))
*  Add a new option `refetchOnUpdate` to the `QueryOptions` interface in `useQuery.ts` to allow refetching the query data when the query parameters change ([link](https://github.com/coronasafe/care_fe/pull/6474/files?diff=unified&w=0#diff-ae7e6ee23684c1a7b8169be4f7177ecca78ddfaa070ec81231db9534ff483a32R9))
*  Use the `refetchOnUpdate` option in the query to get the facility asset location in `AssetsList.tsx` to update the location name when the facility changes ([link](https://github.com/coronasafe/care_fe/pull/6474/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49L109-R120), [link](https://github.com/coronasafe/care_fe/pull/6474/files?diff=unified&w=0#diff-ae7e6ee23684c1a7b8169be4f7177ecca78ddfaa070ec81231db9534ff483a32R47-R56))

### CODE REVIEW

File: src/Utils/request/useQuery.ts [hunk 1]
```diff
@@ -42,6 +43,16 @@ export default function useQuery<TData>(
...
+  useEffect(() => {
+    if (options?.refetchOnUpdate) {
+      runQuery();
+
+      // window.addEventListener("focus", onFocus);
+
+      // return () => window.removeEventListener("focus", onFocus);
+    }
+  }, [runQuery, options?.refetchOnUpdate]);
+
```
Comment (rithviknishad) [inline src/Utils/request/useQuery.ts]: You need not add this, `useQuery` will automatically ALWAYS do a refetch whenever the body/query or anything from the options changes and is intended.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Utils/request/useQuery.ts (hunk 1 above)
Comment (rithviknishad) [reply src/Utils/request/useQuery.ts]: Whenever the `options` changes, `runQuery` is updated since runQuery is from `useCallback` with `options` as it's dependency.

And whenever `runQuery` is updated, and `prefetch` is true, it'll refetch by invoking `runQuery`

All u need to do is ensure prefetch is not set to `false` when this is supposed to happen.

Comment (rithviknishad) [reply src/Utils/request/useQuery.ts]: If you need to force `refetch`, you can always deconstruct the `refetch` from the return type of the `useQuery` and invoke that too. Which will bypass the check of `prefetch` too.

Comment (Pranshu1902) [reply src/Utils/request/useQuery.ts]: @rithviknishad got it, updated the PR

File: src/Components/Assets/AssetsList.tsx [hunk 2]
```diff
@@ -105,9 +110,13 @@ const AssetsList = () => {
       facility_external_id: String(qParams.facility),
       external_id: String(qParams.location),
     },
-    prefetch: !!(qParams.facility && qParams.location),
+    prefetch: qParams.facility || qParams.location,
```
Comment (rithviknishad) [inline src/Components/Assets/AssetsList.tsx]:
```suggestion
    prefetch: !!(qParams.facility && qParams.location),
```

This will cause request to be dispatched with undefined right?

image

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Assets/AssetsList.tsx (hunk 2 above)
Comment (Pranshu1902) [reply src/Components/Assets/AssetsList.tsx]: Yeah, it wasn't working for me locally earlier....strange

File: src/Components/Assets/AssetsList.tsx [hunk 3]
```diff
@@ -108,6 +113,10 @@ const AssetsList = () => {
     prefetch: !!(qParams.facility && qParams.location),
   });
 
+  useEffect(() => {
+    setLocation(location?.name ?? "");
+  }, [location]);
```
Comment (rithviknishad) [inline src/Components/Assets/AssetsList.tsx]: @Pranshu1902 are you sure about this?

Comment (Pranshu1902) [reply src/Components/Assets/AssetsList.tsx]: fixed

File: src/Components/Assets/AssetFilter.tsx [hunk 4]
```diff
@@ -60,13 +48,8 @@ function AssetFilter(props: any) {
...
-    },
-    onResponse: ({ res, data }) => {
-      if (res?.status === 200 && data) {
-        setLocation(data);
-      }
+      facility_external_id: String(facilityId),
+      external_id: String(locationId),
     },
     prefetch: !!(facilityId && locationId),
   });
```
Comment (rithviknishad) [inline src/Components/Assets/AssetFilter.tsx]: You can delete this `useQuery` call and avoid the unused API call entirely right? You are neither doing a setData on response, nor using the returned data from the useQuery.

File: src/Components/Assets/AssetsList.tsx
Comment (rithviknishad) [inline src/Components/Assets/AssetsList.tsx:1]: You don't need a dedicated state (`facility_location` and `facilityName`) when you are simply querying it.

You can do `const { data, refetch } = useQuery(...)` and do a refetch whenever qParams changes

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Assets/AssetFilter.tsx (hunk 4 above)
Comment (Pranshu1902) [reply src/Components/Assets/AssetFilter.tsx]: done

File: src/Components/Assets/AssetsList.tsx
Comment (Pranshu1902) [reply src/Components/Assets/AssetsList.tsx:1]: done

**Review by rithviknishad — APPROVED** [review]

File: src/Components/Assets/AssetsList.tsx [hunk 5]
```diff
@@ -365,12 +363,20 @@ const AssetsList = () => {
...
+              ),
               badge("Name/Serial No./QR ID", "search"),
               value("Asset Type", "asset_type", asset_type ?? ""),
               value("Asset Class", "asset_class", asset_class ?? ""),
               value("Status", "status", status?.replace(/_/g, " ") ?? ""),
-              value("Location", "location", location?.name ?? ""),
+              value(
+                "Location",
+                "location",
+                qParams.facility && locationObject?.name
```
Comment (rithviknishad) [inline src/Components/Assets/AssetsList.tsx]:
```suggestion
                qParams.location && locationObject?.name
```

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
