### PR TITLE
Fix : Image Dragging support for image previews

### LINKED ISSUE #10811: Enhance File Viewer by Adding Mouse Scroll Functionality
**Describe the bug**
When viewing files in the 'Encounters' section. Users are required to use the scroll bar to navigate through the file content, which is not user-friendly.

**To Reproduce**

1. Go to 'Encounters'
2. Click on 'View Details'
3. Click on 'Files'
4. View a file, see error , we need to use scroll bar to move which is not user friendly.

**Expected behavior**
Users should be able to navigate through the file content using the mouse (click and drag) 

https://github.com/user-attachments/assets/9527e894-5ebd-4d2c-9577-1d39bfd7c0ed

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #10811

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- Implemented image dragging functionality 
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

  https://github.com/user-attachments/assets/6c47faae-1641-4df8-90e4-81fdc59a379b

for mobile view
 
https://github.com/user-attachments/assets/43de6715-0ad3-445c-818f-497525dc7778

## Summary by CodeRabbit

- **New Features**
	- Introduced drag-and-drop functionality for image files in the FilePreviewDialog component.
	- Enhanced user interaction with new event handlers for mouse and touch events.
	- Updated layout and rendering logic to support dynamic image movement within the dialog.

### CODE REVIEW

File: src/components/Common/FilePreviewDialog.tsx [hunk 1]
```diff
@@ -94,11 +94,20 @@ const FilePreviewDialog = (props: FilePreviewProps) => {
   const [numPages, setNumPages] = useState(1);
   const [index, setIndex] = useState<number>(currentIndex);
   const [scale, setScale] = useState(1.0);
+  const [isDragging, setIsDragging] = useState(false);
```
Comment (Jacobjeevan) [inline src/components/Common/FilePreviewDialog.tsx]: Can combine these three states.

File: src/components/Common/FilePreviewDialog.tsx [hunk 2]
```diff
@@ -247,15 +299,36 @@ const FilePreviewDialog = (props: FilePreviewProps) => {
...
+              <div
+                className="flex h-[75vh] w-full items-center justify-center overflow-hidden rounded-lg border border-secondary-200"
+                onMouseDown={handleMouseDown}
+                onMouseMove={handleMouseMove}
+                onMouseUp={handleMouseUp}
+                onMouseLeave={handleMouseUp}
+                onTouchStart={handleTouchStart}
+                onTouchMove={handleTouchMove}
+                onTouchEnd={handleTouchEnd}
+                style={{
```
Comment (Jacobjeevan) [inline src/components/Common/FilePreviewDialog.tsx]: use cn and tailwind.

File: src/components/Common/FilePreviewDialog.tsx [hunk 3]
```diff
@@ -247,15 +299,36 @@ const FilePreviewDialog = (props: FilePreviewProps) => {
...
                 {file_state.isImage ? (
-                  <img
-                    src={fileUrl}
-                    alt="file"
-                    className={`h-full w-full object-contain ${
-                      zoom_values[file_state.zoom - 1]
-                    } ${getRotationClass(file_state.rotation)}`}
-                  />
+                  <div
+                    style={{
```
Comment (Jacobjeevan) [inline src/components/Common/FilePreviewDialog.tsx:382]: Should be able to do the same here.

File: src/components/Common/FilePreviewDialog.tsx [hunk 4]
```diff
@@ -247,15 +299,36 @@ const FilePreviewDialog = (props: FilePreviewProps) => {
...
+                      transform: `translate(${position.x}px, ${position.y}px)`,
+                      transition: isDragging ? "none" : "transform 0.1s",
+                    }}
+                  >
+                    <img
+                      src={fileUrl}
+                      alt="file"
+                      className={`h-full w-full select-none object-contain ${
```
Comment (Jacobjeevan) [inline src/components/Common/FilePreviewDialog.tsx]: let's use cn here as well, should look cleaner.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by Jeffrin2005** [comment]
sorry, forgot to combine 3 states

**Comment by Jeffrin2005** [comment]
@Jacobjeevan Any changes required ?

File: src/components/Common/FilePreviewDialog.tsx (hunk 3 above)
Comment (Jacobjeevan) [reply src/components/Common/FilePreviewDialog.tsx:382]: missed this one? @Jeffrin2005  ☝️

**Review by Jacobjeevan — APPROVED** [review]
lgtm otherwise

**Comment by nihal467** [comment]
image

- [ ] After zooming in, I’m unable to drag and navigate through the file. This makes it difficult for users who need to read certain alphabetic reports once they’ve zoomed.

**Comment by Jeffrin2005** [comment]
@nihal467 Sorry , Actualy i forgot to test after the recent request change of jacobjeevan. Could You please test it one more time ?

**Comment by Jeffrin2005** [comment]
@Jacobjeevan  className={cn(
                      "transition-transform duration-100 relative",
                      dragState.isDragging ? "duration-0" : "",
                      `translate-x-[${dragState.position.x}px]`,
                      `translate-y-[${dragState.position.y}px]`
                    )} while using tailwind , the drag functionality is not working, and also i forgot to test it 
                    
                   For dragging functionality, We need to use inline style approach ?

**Comment by rithviknishad** [comment]
merge checklist not followed

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan Completed merge checklist, Can we re-open this PR ?

**Comment by Jeffrin2005** [comment]
@nihal467 Ready for re-test

**Comment by nihal467** [comment]
image

- [ ] I can drag the entire image to the right until it is completely clipped. There should be a limit to prevent this.
- [ ] When I click and hold to drag the image, then release it and click again, the image remains in a dragged state without holding the mouse. It only releases on the next click, which feels unusual.

**Comment by Jeffrin2005** [comment]
@nihal467 changes done.

**Comment by nihal467** [comment]
image

test (5)

- [ ] The normal images are clipping in at the bottom, and they have to drag the image in the normal view to view it fully @Jeffrin2005, before requesting a review, please ensure that existing functionality or view are not broken

**Comment by Jeffrin2005** [comment]
@nihal467 could you please tell me in detail ? Drag functionality is only at the boudaries of images , is this failing?

**Comment by Jeffrin2005** [comment]
@nihal467 
* Fixed - can drag the entire image to the right until it is completely clipped. There should be a limit to prevent this.
* Fixed - The normal images are clipping in at the bottom, and they have to drag the image in the normal view to view it fully.


https://github.com/user-attachments/assets/297ba771-34f3-40d7-a54a-345197b168ba

File: src/components/Common/FilePreviewDialog.tsx [hunk 5]
```diff
@@ -171,12 +209,104 @@ const FilePreviewDialog = (props: FilePreviewProps) => {
...
+      ...prev,
+      isDragging: true,
+      dragStart: {
+        x: e.touches[0].clientX - prev.position.x,
+        y: e.touches[0].clientY - prev.position.y,
+      },
+    }));
+  };
+
+  const handleTouchMove = (e: React.TouchEvent) => {
```
Comment (Jacobjeevan) [inline src/components/Common/FilePreviewDialog.tsx:269]: Isn't the logic exact same as handleMouseMove? handle it accordingly.

File: src/components/Common/FilePreviewDialog.tsx [hunk 6]
```diff
@@ -90,15 +101,40 @@ const FilePreviewDialog = (props: FilePreviewProps) => {
...
+
   const [page, setPage] = useState(1);
   const [numPages, setNumPages] = useState(1);
   const [index, setIndex] = useState<number>(currentIndex);
   const [scale, setScale] = useState(1.0);
+  const [dragState, setDragState] = useState<DragState>({
+    isDragging: false,
+    position: { x: 0, y: 0 },
+    dragStart: { x: 0, y: 0 },
+  });
```
Comment (khavinshankar) [inline src/components/Common/FilePreviewDialog.tsx]: this same thing seems to be repeated; have a 
```ts
const initialDragState = {
    isDragging: false,
    position: { x: 0, y: 0 },
    dragStart: { x: 0, y: 0 },
}
```

File: src/components/Common/FilePreviewDialog.tsx [hunk 7]
```diff
@@ -171,12 +209,104 @@ const FilePreviewDialog = (props: FilePreviewProps) => {
...
+    const imageRect = image.getBoundingClientRect();
+
+    const maxX = Math.max(0, (imageRect.width - containerRect.width) / 2);
+    const maxY = Math.max(0, (imageRect.height - containerRect.height) / 2);
+
+    const newX = e.clientX - dragState.dragStart.x;
+    const newY = e.clientY - dragState.dragStart.y;
+
+    const clampedX = Math.max(-maxX, Math.min(maxX, newX));
+    const clampedY = Math.max(-maxY, Math.min(maxY, newY));
```
Comment (khavinshankar) [inline src/components/Common/FilePreviewDialog.tsx]: This also seems to be repeated; have a util function to calculate this logic

File: src/components/Common/FilePreviewDialog.tsx (hunk 5 above)
Comment (khavinshankar) [reply src/components/Common/FilePreviewDialog.tsx:269]: ➕

**Review by khavinshankar — CHANGES_REQUESTED** [review]
@Jeffrin2005 just some minor cleanup

**Comment by Jeffrin2005** [comment]
@khavinshankar Any changes required ?

**Review by khavinshankar — APPROVED** [review]

**Comment by nihal467** [comment]
image

@Jeffrin2005 the mobile view is breaking, do check everything is working before requesting a review

**Comment by Jeffrin2005** [comment]
@nihal467 , sorry : ) 
I forgot to update the new branch of this file for the button alignement. Now everything is working fine, for mobile view and as well as for desktop.


https://github.com/user-attachments/assets/df2b6947-21ee-4d1f-b5c6-0dcfd6b68ef2

Lets run final test .

**Comment by nihal467** [comment]
LGTM
