### PR TITLE
Fix: Medicine Section Bugs 

### LINKED ISSUE #10610: Bugs in Medicines Section in Encounter Detail Page
**Description**  
- The show/hide toggle for stopped prescriptions on the **Prescription** tab is not functioning correctly.  
- It should behave the same way as the **Medicine Administrator** toggle.  
- Additionally, the **Print** button should be disabled when no medicine is prescribed.  
- There is no **Back** button on **Print Preview**, which should be added.  

#### **Expected Behavior**  
1. The toggle for stopped prescriptions should properly show/hide stopped prescriptions.  
2. The Print button should be disabled when there are no prescribed medicines.  
3. A Back button should be available on Print Preview to allow easy navigation.  

#### **Steps to Reproduce**  
1. Navigate to the **Prescription** tab.  
2. Try toggling stopped prescriptions—it doesn’t work as expected.  
3. Check the **Print** button when no medicine is prescribed—it should be disabled.  
4. Open **Print Preview**—there is no Back button.  

 **Screen Recording**  

https://github.com/user-attachments/assets/a5446f3b-98e0-41a8-ad79-c6fffbcd8b27

**Additional Info**
Approved by @amjithtitus09  ✅

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #10610 
- [x]  Fix Search functionality in Prescription tab in Encounter Detail page
- [x] Fix the toggle behaviour for the same above 
- [x] Show Inactive medicines on search for both Prescription and Administration 
- [x] Add Back button in Print Preview 
- [x] Removed the refetch and used invalidate query instead
- [x] Disable Print button when no medicines are there 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Added a "Back" button on the print view to allow easy return to the previous screen.
  - Introduced a loading indicator on the prescription printing page to enhance user feedback during data retrieval.

- **Style**
  - Updated medication notifications by replacing the phrase "No active medications" with a more general "No Medications" message.
  - Refined how empty states are handled in medication displays for clearer, more accurate information.

- **Enhancements**
  - Improved medication data handling in the MedicationsTable component for better flexibility and performance.
  - Enhanced the PrintPreview component to navigate back to the previous page.
  - Updated logic in the MedicationRequestTable for more explicit messaging when no medications are available.
  - Streamlined query management and filtering logic in the AdministrationTab component for improved efficiency.

### CODE REVIEW

File: src/components/Patient/TreatmentSummary.tsx [hunk 1]
```diff
@@ -217,6 +217,7 @@ export default function TreatmentSummary({
                 {t("medications")}
               </p>
               <MedicationsTable
+                isPrintPreview={true}
                 patientId={encounter.patient.id}
```
Comment (AdityaJ2305) [inline src/components/Patient/TreatmentSummary.tsx]: Can we fetch the data in TreatmentSummary file itself , then we can get rid of Patient id and encoute id prop in MedicationsTable it is the only place which is not doing so  

cc: @amjithtitus09

Comment (amjithtitus09) [reply src/components/Patient/TreatmentSummary.tsx]: Not sure what you mean. Aren't all the tables working the same way. Just encounter is fetched in TreatmentSummary. 
image

**Comment by AdityaJ2305** [comment]
One thing more 😅
I observed in `AdministrationTab.tsx` we are using refetch from UseQuery . Let's not use that instead use `invalidate query` like we are doing all over other places in codebase. LMK ? 

cc: @rithviknishad  @amjithtitus09

File: src/components/Medicine/MedicationRequestTable/index.tsx [hunk 2]
```diff
@@ -167,17 +171,23 @@ export default function MedicationRequestTable({
...
                   <Button
-                    asChild
                     variant="outline"
+                    disabled={
+                      !(
+                        activeMedications?.results?.length ||
+                        stoppedMedications?.results?.length
+                      )
+                    }
+                    onClick={() =>
```
Comment (Jacobjeevan) [inline src/components/Medicine/MedicationRequestTable/index.tsx]: Let's stick with using Link component inside Button as it maintains semantic HTML +  accessibility.

There's a few other instances in the code base that need to be adjusted as well, but we can take that up later.

**Comment by AdityaJ2305** [comment]
@amjithtitus09, one more thing 😅

Shouldn’t we use a popover to display notes in the medicine section, just like we’re doing for the allergies table and others? If yes, can I push that change to the treatment summary PR since I need isPrintPreview, which I’ve already passed there? 😅

**Comment by amjithtitus09** [comment]
@AdityaJ2305 Let's not add more columns in Medicine request table, it'll get too cramped.

**Comment by AdityaJ2305** [comment]
> @AdityaJ2305 Let's not add more columns in Medicine request table, it'll get too cramped.

It wouldn't make any additional column ,I am just asking to update the current one to update it to popover notes and long notes are overflow for all the tables in Print
@amjithtitus09

**Comment by amjithtitus09** [comment]
> > @AdityaJ2305 Let's not add more columns in Medicine request table, it'll get too cramped.
> 
> It wouldn't make any additional column ,I am just asking to update the current one to update it to popover notes and long notes are overflow for all the tables in Print @amjithtitus09

Can you share screenshot of the table you're talking about? @AdityaJ2305

**Comment by AdityaJ2305** [comment]
Current:- 
Screenshot 2025-02-18 at 2 31 21 PM



Updated:- 
Screenshot 2025-02-18 at 2 36 03 PM

@amjithtitus09 , It was just to make it consistent with other tables we have ......

Note:- Although I reported it here, but I will be making the same change in Treatment Summary PR as I need isPrintPreview for it to make it work for Treatment Summary which I have already passed in that PR

**Comment by AdityaJ2305** [comment]
> One thing more 😅 I observed in `AdministrationTab.tsx` we are using refetch from UseQuery . Let's not use that instead use `invalidate query` like we are doing all over other places in codebase. LMK ?
> 
> cc: @rithviknishad @amjithtitus09

Done ✅

**Comment by amjithtitus09** [comment]
@AdityaJ2305 Can you handle this too?

https://github.com/user-attachments/assets/ab1541ce-7c0f-40c2-b42a-5268840036f4

**Comment by AdityaJ2305** [comment]
> @AdityaJ2305 Can you handle this too?
> 
>  Screen.Recording.2025-02-19.at.11.14.40.AM.mov

I was about to ask you this 😅

**Comment by AdityaJ2305** [comment]
@amjithtitus09 Done with the chages, ready for review 😄

**Comment by AdityaJ2305** [comment]
@amjithtitus09 , Made the changes, ready for review ✅

File: src/components/Medicine/MedicationsTable.tsx [hunk 3]
```diff
@@ -36,30 +37,38 @@ export function getFrequencyDisplay(
 }
 
 interface MedicationsTableProps {
-  patientId: string;
-  encounterId: string;
+  patientId?: string;
+  encounterId?: string;
+  medications?: MedicationRequestRead[];
```
Comment (amjithtitus09) [inline src/components/Medicine/MedicationsTable.tsx:42]: Is this needed?

File: src/components/Medicine/MedicationRequestTable/index.tsx [hunk 4]
```diff
@@ -186,35 +198,34 @@ export default function MedicationRequestTable({
...
                 <EmptyState searching searchQuery={searchQuery} />
               ) : (
                 <ScrollArea className="h-[calc(100vh-16rem)]">
                   <div className="min-w-[800px]">
                     <div className="p-2">
-                      <MedicationsTable
-                        patientId={patientId}
-                        encounterId={encounterId}
-                      />
+                      <MedicationsTable medications={displayedMedications} />
```
Comment (amjithtitus09) [inline src/components/Medicine/MedicationRequestTable/index.tsx:200]: Why do we need to pass in medications?

File: src/pages/Encounters/PrintPrescription.tsx [hunk 5]
```diff
@@ -122,7 +125,7 @@ export const PrintPrescription = (props: {
           <div className="text-2xl font-semibold mb-3">℞</div>
 
           {/* Medications Table */}
-          <MedicationsTable patientId={patientId} encounterId={encounterId} />
+          <MedicationsTable medications={medications?.results ?? []} />
```
Comment (amjithtitus09) [inline src/pages/Encounters/PrintPrescription.tsx]: Same here

**Review by amjithtitus09 — CHANGES_REQUESTED** [review]

File: src/components/Medicine/MedicationsTable.tsx (hunk 3 above)
Comment (AdityaJ2305) [reply src/components/Medicine/MedicationsTable.tsx:42]: @amjithtitus09 So, the MedicationTable is used in three places: the “Prescription Tab” in the Encounter Detail Page, “Print Prescription,” and “Treatment Summary.” Out of these, only the Treatment Summary is not fetching medications, while the other two are already fetching them. So, passing medications here is just to avoid re-fetching, as the parent is already fetching them.  If you remember, I had asked about this in our huddle.

Comment (amjithtitus09) [reply src/components/Medicine/MedicationsTable.tsx:42]: Can you do the opposite? See if removing fetching in the other parents is possible.

Comment (AdityaJ2305) [reply src/components/Medicine/MedicationsTable.tsx:42]: @amjithtitus09 I think we shouldn’t do that since the parent component already handles certain medication-related logic. If we add the same logic to MedicationTable, it wouldn’t function purely as a table anymore. For example, in the Prescription tab, we have a search bar and toggle behavior—if we include these in MedicationTable, it would no longer be just a table, right? This would also make it inconsistent with how other tables are used in the flow.

Comment (amjithtitus09) [reply src/components/Medicine/MedicationsTable.tsx:42]: Alright this is fine. But Print Prescription does fetching by itself. The change is in this PR itself, check other comment.

File: src/pages/Encounters/PrintPrescription.tsx (hunk 5 above)
Comment (amjithtitus09) [reply src/pages/Encounters/PrintPrescription.tsx]: Is this necessary?

Comment (AdityaJ2305) [reply src/pages/Encounters/PrintPrescription.tsx]: 🤔Same Parent is already fetching it so passing it to child

Comment (amjithtitus09) [reply src/pages/Encounters/PrintPrescription.tsx]: @AdityaJ2305 Oh I missed that

Comment (AdityaJ2305) [reply src/pages/Encounters/PrintPrescription.tsx]: Yes

Comment (AdityaJ2305) [reply src/pages/Encounters/PrintPrescription.tsx]: Could 't understand your query here ? Isn't it same like above we discussed  ?
@amjithtitus09

**Review by amjithtitus09 — APPROVED** [review]

**Comment by amjithtitus09** [comment]
@AdityaJ2305 Do add a comment before you mark review comments as resolved

**Comment by AdityaJ2305** [comment]
> @AdityaJ2305 Do add a comment before you mark review comments as resolved

@amjithtitus09 , sorry my bad..... I thought other two are related to first one . But yeah I should stick to follow the good practices Apologies

**Comment by amjithtitus09** [comment]
> > @AdityaJ2305 Do add a comment before you mark review comments as resolved
> 
> @amjithtitus09 , sorry my bad..... I thought other two are related to first one . But yeah I should stick to follow the good practices Apologies

@AdityaJ2305 Primarily the earlier ones from @Jacobjeevan

**Comment by AdityaJ2305** [comment]
I am referring to this one 😅 
Screenshot_2025-02-20-16-04-51-92_40deb401b9ffe8e1df2f1cc5ba480b12

File: src/components/Medicine/MedicationRequestTable/index.tsx [hunk 6]
```diff
@@ -92,21 +92,28 @@ export default function MedicationRequestTable({
...
-        ...(activeMedications?.results || []),
-        ...(stoppedMedications?.results || []),
-      ]
-    : activeMedications?.results || [];
-
-  const displayedMedications = medications.filter(
-    (med: MedicationRequestRead) => {
-      if (!searchQuery.trim()) return true;
-      const searchTerm = searchQuery.toLowerCase().trim();
+  const medications = useMemo(
```
Comment (Jacobjeevan) [inline src/components/Medicine/MedicationRequestTable/index.tsx]: Let's not add useMemo here, since it's encounter specific number of medications is never going to be big enough (and/or the logic inside isn't complex enough) for useMemo to be a useful optimization here.

File: src/components/Medicine/MedicationRequestTable/index.tsx [hunk 7]
```diff
@@ -92,21 +92,28 @@ export default function MedicationRequestTable({
...
+      showStopped
+        ? [
+            ...(activeMedications?.results || []),
+            ...(stoppedMedications?.results || []),
+          ]
+        : activeMedications?.results || [],
+    [showStopped, activeMedications, stoppedMedications],
+  );
+
+  const displayedMedications = useMemo(() => {
```
Comment (Jacobjeevan) [inline src/components/Medicine/MedicationRequestTable/index.tsx]: same here.

File: src/components/Medicine/MedicationAdministration/AdministrationTab.tsx [hunk 8]
```diff
@@ -602,14 +608,17 @@ export const AdministrationTab: React.FC<AdministrationTabProps> = ({
       ]
     : activeMedications?.results || [];
 
-  const filteredMedications = medications.filter(
-    (med: MedicationRequestRead) => {
-      if (!searchQuery.trim()) return true;
-      const searchTerm = searchQuery.toLowerCase().trim();
+  const filteredMedications = useMemo(() => {
```
Comment (Jacobjeevan) [inline src/components/Medicine/MedicationAdministration/AdministrationTab.tsx]: Same here as well.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Medicine/MedicationAdministration/AdministrationTab.tsx (hunk 8 above)
Comment (AdityaJ2305) [reply src/components/Medicine/MedicationAdministration/AdministrationTab.tsx]: done

File: src/components/Medicine/MedicationRequestTable/index.tsx (hunk 7 above)
Comment (AdityaJ2305) [reply src/components/Medicine/MedicationRequestTable/index.tsx]: done

File: src/components/Medicine/MedicationRequestTable/index.tsx (hunk 6 above)
Comment (AdityaJ2305) [reply src/components/Medicine/MedicationRequestTable/index.tsx]: done

**Review by Jacobjeevan — APPROVED** [review]

**Comment by AdityaJ2305** [comment]
> Current:- Screenshot 2025-02-18 at 2 31 21 PM
> 
> Updated:- Screenshot 2025-02-18 at 2 36 03 PM
> 
> @amjithtitus09 , It was just to make it consistent with other tables we have ......
> 
> Note:- Although I reported it here, but I will be making the same change in Treatment Summary PR as I need isPrintPreview for it to make it work for Treatment Summary which I have already passed in that PR

@amjithtitus09 @Jacobjeevan, should I take this up as well? Let me know.

**Comment by amjithtitus09** [comment]
@AdityaJ2305 Refrain from making additional changes once PR is marked as reviewed. It will be taken up for testing next.

**Comment by nihal467** [comment]
image

- [ ] when there is no active medicine, the print button is still active

**Comment by AdityaJ2305** [comment]
> image
> 
> * [ ]  when there is no active medicine, the print button is still active

@nihal467 , we want to print the discontinues ones na ? Like it was printing there so I though this is expected behaviour do comfirm it please ?

**Comment by AdityaJ2305** [comment]
@nihal467 , done with the changes

**Comment by nihal467** [comment]
LGTM
