### PR TITLE
FIXED: Avoid Using localStorage for Navigation State in Public Appointment Flow

### LINKED ISSUE #12414: Avoid Using localStorage for Navigation State in Public Appointment Flow
**Describe the bug**
Internal navigation state (selected slot, reason) is stored in localStorage instead of URL, breaking direct navigation and reproducibility.

**To Reproduce**

**Expected behavior**
Navigation state should be passed via URL query parameters so that the flow works correctly when accessed directly or refreshed.

**Screenshots**
(Solution)

https://github.com/user-attachments/assets/de1f6d11-251a-4054-9b2c-f5affdc2aded

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes
added useQueryParams

- Fixes #12414 

https://github.com/user-attachments/assets/b8a7dac7-8632-45e1-989f-b269422f0137

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Refactor**
  - Updated the process of passing appointment slot and reason information between pages to use URL query parameters instead of local storage.

- **Bug Fixes**
  - Improved reliability by ensuring appointment details are consistently retrieved from the URL, reducing potential issues with local storage.

- **Chores**
  - Streamlined navigation logic for public appointment scheduling.

### CODE REVIEW

File: src/pages/PublicAppointments/PatientSelect.tsx [hunk 1]
```diff
@@ -111,10 +111,23 @@ export default function PatientSelect({
...
+        } catch (error) {
+          console.error(
+            t("error_to_parse_selectedSlot_from_URL_parameters"),
+            error,
+          );
+          return undefined;
+        }
+      })()
+    : undefined;
+  const reason = params.reason || "";
```
Comment (Jacobjeevan) [inline src/pages/PublicAppointments/PatientSelect.tsx]: You also need to handle the case when tokenData is not available (line 143).

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/PublicAppointments/PatientRegistration.tsx [hunk 2]
```diff
@@ -47,12 +47,24 @@ type PatientRegistrationProps = {
...
   const { t } = useTranslation();
+  const [params] = useQueryParams();
+  const selectedSlot = params.selectedSlot
+    ? (() => {
+        try {
+          return JSON.parse(
+            decodeURIComponent(params.selectedSlot),
+          ) as TokenSlot;
+        } catch (error) {
+          console.error(
```
Comment (Jacobjeevan) [inline src/pages/PublicAppointments/PatientRegistration.tsx]: Console logging isn't useful here 🤔  Add a toast message instead.

File: src/pages/PublicAppointments/PatientSelect.tsx (hunk 1 above)
Comment (modamaan) [reply src/pages/PublicAppointments/PatientSelect.tsx]: @Jacobjeevan 
 here is already handling it, am i correct ?
```
  } else if (!tokenData) {
    toast.error(t("phone_number_not_found"));
    navigate(`/facility/${facilityId}/appointments/${staffId}/otp/send`); 
```

Comment (Jacobjeevan) [reply src/pages/PublicAppointments/PatientSelect.tsx]: I was referring to params, but thinking on it, it should be fine 👍

File: src/pages/PublicAppointments/PatientRegistration.tsx [hunk 3]
```diff
@@ -47,12 +47,21 @@ type PatientRegistrationProps = {
...
-  const selectedSlot = JSON.parse(
-    localStorage.getItem("selectedSlot") ?? "",
-  ) as TokenSlot;
-  const reason = localStorage.getItem("reason");
-
   const { t } = useTranslation();
+  const [params] = useQueryParams();
+  const selectedSlot = params.selectedSlot
+    ? (() => {
+        try {
```
Comment (Jacobjeevan) [inline src/pages/PublicAppointments/PatientRegistration.tsx]: move into fn/fn expression for readability.

File: src/pages/PublicAppointments/PatientSelect.tsx [hunk 4]
```diff
@@ -111,10 +111,20 @@ export default function PatientSelect({
   staffId: string;
 }) {
   const { t } = useTranslation();
-  const selectedSlot = JSON.parse(
-    localStorage.getItem("selectedSlot") ?? "",
-  ) as TokenSlot;
-  const reason = localStorage.getItem("reason");
+  const [params] = useQueryParams();
+  const selectedSlot = params.selectedSlot
+    ? (() => {
```
Comment (Jacobjeevan) [inline src/pages/PublicAppointments/PatientSelect.tsx]: same here; create a utility fn that you can import on both components.

**Comment by modamaan** [comment]
@Jacobjeevan utility function added

File: src/Utils/utils.ts [hunk 5]
```diff
@@ -324,3 +324,22 @@ export function getWeeklyIntervalsFromTodayTill(pastDate?: Date | string) {
...
+/**
+ * Parses a selectedSlot param (URL-encoded JSON string) into a TokenSlot object.
+ * Returns undefined if parsing fails.
+ * @param selectedSlotParam The URL param value (string or undefined)
+ * @param onError Optional error callback (e.g., for toast)
+ */
+export function parseSelectedSlotParam(
+  selectedSlotParam: string | undefined,
+  onError?: (error: unknown) => void,
+): import("@/types/scheduling/schedule").TokenSlot | undefined {
```
Comment (khavinshankar) [inline src/Utils/utils.ts]: move import statement to the top, also check the ai generated code before committing once

**Review by khavinshankar — DISMISSED** [review]

**Review by Jacobjeevan — DISMISSED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/pages/PublicAppointments/Schedule.tsx [hunk 6]
```diff
@@ -334,13 +334,15 @@ export function ScheduleAppointment(props: AppointmentsProps) {
...
+                    const params = new URLSearchParams({
+                      selectedSlot: encodeURIComponent(
+                        JSON.stringify(selectedSlot),
+                      ),
+                      reason: reason,
+                    }).toString();
+
                     navigate(
-                      `/facility/${facilityId}/appointments/${staffId}/patient-select`,
+                      `/facility/${facilityId}/appointments/${staffId}/patient-select?${params}`,
```
Comment (rithviknishad) [inline src/pages/PublicAppointments/Schedule.tsx]: you don't need to do all those encoding and all. raviger's navigate already takes care of it for you!

```suggestion
                      `/facility/${facilityId}/appointments/${staffId}/patient-select`, { query: {...} }
```

File: src/Utils/utils.ts [hunk 7]
```diff
@@ -324,3 +325,22 @@ export function getWeeklyIntervalsFromTodayTill(pastDate?: Date | string) {
...
+  onError?: (error: unknown) => void,
+): TokenSlot | undefined {
+  if (!selectedSlotParam) return undefined;
+  try {
+    return JSON.parse(decodeURIComponent(selectedSlotParam));
+  } catch (error) {
+    if (onError) onError(error);
+    return undefined;
+  }
+}
```
Comment (rithviknishad) [inline src/Utils/utils.ts]: i don't see any reason why this is a globally declared utility fn. 

this can be scoped to schedule's utility fn's file

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by modamaan** [comment]
should we need toast message for parse
`"error_to_parse_selectedSlot_from_URL_parameters": "Failed to parse selectedSlot from URL parameters",`

File: src/pages/PublicAppointments/Schedule.tsx [hunk 8]
```diff
@@ -334,13 +334,14 @@ export function ScheduleAppointment(props: AppointmentsProps) {
...
-                    );
-                    localStorage.setItem("reason", reason);
+                    const params = {
+                      selectedSlot: JSON.stringify(selectedSlot),
+                      reason: reason,
+                    };
+
                     navigate(
                       `/facility/${facilityId}/appointments/${staffId}/patient-select`,
+                      { query: params },
```
Comment (Jacobjeevan) [inline src/pages/PublicAppointments/Schedule.tsx]: minor thing, but since params is only used once, you can define it here.

File: public/locale/en.json [hunk 9]
```diff
@@ -1363,6 +1363,7 @@
   "error_loading_questionnaire_response": "Error loading questionnaire response",
   "error_removing_bed_assignment": "Error while removing the bed assignment. Please try again later.",
   "error_saving_file": "Error saving file",
+  "error_to_parse_selectedSlot_from_URL_parameters": "Failed to parse selectedSlot from URL parameters",
```
Comment (Jacobjeevan) [inline public/locale/en.json]: are you using this anywhere? 🤔

**Comment by modamaan** [comment]
@rithviknishad @Jacobjeevan can you please update the labels

**Review by rithviknishad — CHANGES_REQUESTED** [review]
let's not JSON dump the entire object to query params. let's keep each individual attributes as spearate query params.

and that too only the needed information.

**Comment by modamaan** [comment]
@rithviknishad can you check the updates

**Review by Jacobjeevan — APPROVED** [review]
quick pass, lgtm.

**Comment by nihal467** [comment]
image

- when you are creating a new appointment for a new patients, the request api send send is wrong

File: src/pages/PublicAppointments/PatientSelect.tsx [hunk 10]
```diff
@@ -111,10 +110,9 @@ export default function PatientSelect({
   staffId: string;
 }) {
   const { t } = useTranslation();
-  const selectedSlot = JSON.parse(
-    localStorage.getItem("selectedSlot") ?? "",
-  ) as TokenSlot;
-  const reason = localStorage.getItem("reason");
+  const [params] = useQueryParams();
+  const slotId = params.slotId;
+  const reason = params.reason || "";
```
Comment (rithviknishad) [inline src/pages/PublicAppointments/PatientSelect.tsx]:
```suggestion
  const [{ slotId, reason }] = useQueryParams();
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]
