### PR TITLE
Adjusted responsiveness of button in Patient Name Dropdown

### LINKED ISSUE #13269: Adjust responsiveness of button in Patient Name Dropdown
**Describe the bug**
There is already a way to close the dialogue (default cross icon ) but still there is a close button. We should remove close button.

Image

**To Reproduce**

1. Go to [link](https://care.ohc.network/facility/b90bf759-077c-46f4-a916-817f332a5a60/billing/account/a512bd48-5345-4870-91f5-bff99a25371f/payments?page=1&limit=14&ordering=-payment_datetime)
2. Click on Patient name dropdown in mobile view

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Akhileswaran-K-R**
## Proposed Changes

Fixes #13269 
- Made the DialogClose to be inside DialogFooter
- Made the close button to be a Button component

close button

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

* **Style**
  * Refreshed the mobile dialog in the Patient Header to a rounded, compact, responsive container for improved readability and spacing.
  * Moved the Close action into a dedicated footer with a full-width, rounded secondary button for clearer and more consistent interaction on small screens.
  * Preserved titles and core content while refining padding and responsive width to avoid a full-bleed, bottom-sheet appearance.

### CODE REVIEW

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

File: src/pages/Facility/services/serviceRequests/components/PatientHeader.tsx [hunk 1]
```diff
@@ -55,7 +56,7 @@ export function PatientHeader({
             </span>
           </div>
         </DialogTrigger>
-        <DialogContent className="p-0 max-w-sm w-full rounded-t-2xl fixed bottom-0 left-1/2 -translate-x-1/2 m-0 shadow-2xl bg-white border-none animate-slide-up">
+        <DialogContent className="mb-8 rounded-lg p-4 w-[calc(100vw-2.5rem)] sm:w-[calc(100%-2rem)] max-w-3xl">
```
Comment (NikhilA8606) [inline src/pages/Facility/services/serviceRequests/components/PatientHeader.tsx]: Use tailwind values instead of rem and %

File: src/pages/Facility/services/serviceRequests/components/PatientHeader.tsx [hunk 2]
```diff
@@ -117,11 +118,13 @@
...
-                {t("close")}
-              </button>
-            </DialogClose>
+            <DialogFooter className="sm:justify-start mt-4">
+              <DialogClose asChild>
+                <button className="mt-4 w-full py-2 rounded-full bg-primary-100 hover:bg-primary-200 text-primary-900 font-semibold shadow transition-colors text-base">
+                  {t("close")}
+                </button>
+              </DialogClose>
+            </DialogFooter>
```
[the remark this answers is not in the document]
Comment (NikhilA8606) [reply src/pages/Facility/services/serviceRequests/components/PatientHeader.tsx]: Check the CodeRabbit suggestion too (Option B)

**Review by NikhilA8606 — CHANGES_REQUESTED** [review]

File: src/pages/Facility/services/serviceRequests/components/PatientHeader.tsx [hunk 3]
```diff
@@ -117,11 +119,17 @@ export function PatientHeader({
                 </div>
               </div>
             </div>
-            <DialogClose asChild>
-              <button className="mt-4 w-full py-2 rounded-full bg-primary-100 hover:bg-primary-200 text-primary-900 font-semibold shadow transition-colors text-base">
-                {t("close")}
-              </button>
-            </DialogClose>
+            <DialogFooter className="sm:justify-start mt-4">
```
Comment (Jacobjeevan) [inline src/pages/Facility/services/serviceRequests/components/PatientHeader.tsx]: classes here shouldn't be needed 🤔

**Review by Jacobjeevan — DISMISSED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
