### PR TITLE
fix:Show numeric keyboard for number question in IOS devices

### LINKED ISSUE #12704: Show numeric keyboard for number question in IOS devices
**Describe the bug**
Numeric keyboard is not showing for IOS devices

**To Reproduce**

1. Select any of number field in IOS device

**Expected behavior**
Numeric keypad should be show for IOS devices

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Proposed Changes

- Fixes #12704 
- Add inputMode and pattern for number type
- Sourced from : https://github.com/orbeon/orbeon-forms/issues/2487

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Enhancements**
  - Improved numeric input fields across patient registration, medication request, questionnaire, scheduling forms, and date fields.
  - Input fields now better support numeric and decimal input with clearer input modes and validation patterns for enhanced usability on various devices and browsers.

### CODE REVIEW

File: src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx [hunk 1]
```diff
@@ -1107,6 +1107,8 @@ const MedicationRequestGridRow: React.FC<MedicationRequestGridRowProps> = ({
           {dosageInstruction?.timing && (
             <Input
               type="number"
+              inputMode="numeric"
+              pattern="[0-9]*"
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx]: this should be decimal as per the spec

image

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

**Review by amjithtitus09 — APPROVED** [review]
Merge after testing

**Comment by nihal467** [comment]
- change the behavior for the DD MM YYYY in the patient registration form

**Comment by nihal467** [comment]
LGTM

**Review by abhimanyurajeesh — APPROVED** [review]
