### PR TITLE
Fix : Phone Numbers and Map Links Don't Appear Clickable

### LINKED ISSUE #12715: Phone Numbers and Map Links Don't Appear Clickable
**Describe the bug**
phone numbers appear as plain text with no visual indication they're clickable

**To Reproduce**

1. Go to 'Settings' -> " General"
2. See error, phone numbers show as normal text.

Image

**Expected behavior**
Phone numbers should appear in green with underline, and map links should also be underlined for clear visibility.

Image

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #12715

- Added hover:underline to FacilityMapLink and text primary and hover underline to the ContactLink.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

https://github.com/user-attachments/assets/8aca9c98-b1f4-4f0c-9212-337a953dcefc

- [ ] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **Style**
  * Improved link appearance by adding primary text color, underline on hover, and enhanced spacing and alignment to contact and facility map links for better visual feedback.
  * Added accessible labels to contact and facility map links to improve screen reader support.

### CODE REVIEW

File: src/components/Common/ContactLink.tsx [hunk 1]
```diff
@@ -7,7 +7,10 @@ type ContactLinkProps =
 export default function ContactLink(props: ContactLinkProps) {
   return (
     <div>
-      <a href={props.tel ? `tel:${props.tel}` : `mailto:${props.mailto}`}>
+      <a
+        href={props.tel ? `tel:${props.tel}` : `mailto:${props.mailto}`}
+        className="text-primary hover:underline flex items-center gap-1 w-max"
```
Comment (AdityaJ2305) [inline src/components/Common/ContactLink.tsx]: can you double check `w-max` ? really need it ?

File: src/components/Facility/FacilityMapLink.tsx [hunk 2]
```diff
@@ -30,7 +30,7 @@ export const FacilityMapsLink = ({
 
   return (
     <Link
-      className="text-primary flex items-center gap-1 w-max"
+      className="text-primary hover:underline flex items-center gap-1 w-max"
```
Comment (AdityaJ2305) [inline src/components/Facility/FacilityMapLink.tsx]: same here

**Review by AdityaJ2305 — APPROVED** [review]

**Comment by Jeffrin2005** [comment]
@rithviknishad Can you review this PR.

File: src/components/Common/ContactLink.tsx [hunk 3]
```diff
@@ -7,7 +7,10 @@ type ContactLinkProps =
 export default function ContactLink(props: ContactLinkProps) {
   return (
     <div>
-      <a href={props.tel ? `tel:${props.tel}` : `mailto:${props.mailto}`}>
+      <a
+        href={props.tel ? `tel:${props.tel}` : `mailto:${props.mailto}`}
+        className="text-primary hover:underline flex items-center gap-1"
+      >
         <CareIcon icon={props.tel ? "l-outgoing-call" : "l-envelope-alt"} />
```
Comment (Jacobjeevan) [inline src/components/Common/ContactLink.tsx:15]: go ahead and add aria-label as well.

**Review by Jacobjeevan — APPROVED** [review]

File: src/components/Facility/FacilityMapLink.tsx [hunk 4]
```diff
@@ -30,7 +30,7 @@ export const FacilityMapsLink = ({
 
   return (
     <Link
```
Comment (AdityaJ2305) [inline src/components/Facility/FacilityMapLink.tsx:32]: aria-label

**Comment by Jeffrin2005** [comment]
@Jacobjeevan Can we change the label.

**Comment by Jeffrin2005** [comment]
@Jacobjeevan  Can we change the label.

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
