### PR TITLE
Fix: Misalignment of Buttons and text for mobile view in User Profile page #13020

### LINKED ISSUE #13020: Misalignment of Buttons and text for mobile view in User Profile page
**Describe the bug**
Refer below screen recording , the alignment of button and text can be improve for mobile view like aligning button to centre and same for text divs 

https://github.com/user-attachments/assets/f4de8a4b-c71e-42de-bf23-9928bba217b0

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by geyamrutha16**
## Proposed Changes

Fixes #13020 

- Buttons are centered on mobile and left-aligned on larger screens.
- Section headings/subheadings remain left-aligned.
- Added responsive spacing for consistent look.
- Applied changes across the relevant sections.

https://github.com/user-attachments/assets/c6cb39d6-260e-4bf8-b251-d03e44791658

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [ ] Update product documentation. *(Not applicable for UI alignment changes)*
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

* **Style**
  * Improved horizontal padding in Two‑Factor and Danger Zone cards for better small-screen layout.
  * Adjusted Reset Password: increased vertical padding on small+ screens, center-aligned header on small viewports, and reduced action button spacing.
  * Reduced default gaps in user detail sections while preserving the two-column layout on small screens.
  * Standardized wrapping/centering of software-update and enable buttons; added disabled-cursor behavior.

### CODE REVIEW

File: src/components/Users/TwoFactorAuth.tsx [hunk 1]
```diff
@@ -174,7 +174,7 @@ export const TwoFactorAuth = ({ userData }: userChildProps) => {
                 <Button
                   onClick={handleSetup}
                   variant="outline"
-                  className="border-blue-600 text-blue-600 hover:bg-blue-50"
+                  className="border-blue-600 text-blue-600 hover:bg-blue-50 disabled:opacity-50 disabled:cursor-not-allowed block mx-auto sm:mx-0"
```
Comment (areebahmeddd) [inline src/components/Users/TwoFactorAuth.tsx]: disabled class is already present in button component

File: src/components/Users/UserSoftwareUpdate.tsx [hunk 2]
```diff
@@ -68,12 +70,14 @@ export default function UserSoftwareUpdate() {
         </UpdatableApp>
       ) : (
         // Default state to check for updates
-        <Button variant="primary" onClick={checkUpdates}>
-          <div className="flex items-center gap-4">
-            <CareIcon icon="l-sync" className="text-xl" />
-            {t("check_for_update")}
-          </div>
-        </Button>
+        <div className="flex justify-center sm:justify-start overflow-hidden rounded-lg bg-white px-4 py-5 shadow-sm sm:rounded-lg sm:px-6 sm:py-6">
```
Comment (Tanuj1718) [inline src/components/Users/UserSoftwareUpdate.tsx]: we can make it sm:p-6, right?🤔

Comment (Tanuj1718) [reply src/components/Users/UserSoftwareUpdate.tsx]: you can write it directly instead of writing for x and y separately

**Review by Tanuj1718 — CHANGES_REQUESTED** [review]

File: src/components/Users/TwoFactorAuth.tsx (hunk 1 above)
Comment (geyamrutha16) [reply src/components/Users/TwoFactorAuth.tsx]: Fixed 👍

File: src/components/Users/UserSoftwareUpdate.tsx (hunk 2 above)
Comment (geyamrutha16) [reply src/components/Users/UserSoftwareUpdate.tsx]: Updated !

**Review by Tanuj1718 — APPROVED** [review]

File: src/components/Users/TwoFactorAuth.tsx [hunk 3]
```diff
@@ -161,11 +161,11 @@ export const TwoFactorAuth = ({ userData }: userChildProps) => {
   return (
     <>
       <Card className="w-full">
-        <CardHeader>
+        <CardHeader className="px-4 sm:px-5">
```
Comment (Jacobjeevan) [inline src/components/Users/TwoFactorAuth.tsx:164]: let's switch to using flex and alignment for these

File: src/components/Users/UserSummary.tsx [hunk 4]
```diff
@@ -170,13 +170,13 @@ export default function UserSummaryTab({
         )}
         {canEditUser && (
           <Card className="border-red-500">
-            <CardHeader>
+            <CardHeader className="px-4 sm:px-5">
```
Comment (Jacobjeevan) [inline src/components/Users/UserSummary.tsx]: same here. Hmm, CardHeader might already have flex, alignment alone might be enough.

File: src/components/Users/UserSummary.tsx [hunk 5]
```diff
@@ -170,13 +170,13 @@ export default function UserSummaryTab({
...
               <CardTitle className="text-destructive">
                 {t("danger_zone")}
               </CardTitle>
             </CardHeader>
-            <CardContent className="space-y-4">
-              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 rounded-md border p-4">
+            <CardContent className="space-y-4 px-4 sm:px-5">
```
Comment (Jacobjeevan) [inline src/components/Users/UserSummary.tsx]: and here, can switch from space to gap as well.

File: src/components/Users/UserSummary.tsx (hunk 4 above)
Comment (geyamrutha16) [reply src/components/Users/UserSummary.tsx]: @Jacobjeevan,  I tried using only alignment (justify-*), but because CardHeader has default p-6, it caused extra horizontal spacing compared to CardContent. I found that either overriding CardHeader padding (px-4 sm:px-5), or removing padding from CardContent keeps the layout consistent (then it becomes the old design).
 Should I use (px-4 sm:px-5) in CardHeader?
image

**Comment by geyamrutha16** [comment]
@Jacobjeevan,  I tried using only alignment (justify-*), but because CardHeader has default p-6, it caused extra horizontal spacing compared to CardContent. I found that either overriding CardHeader padding (px-4 sm:px-5), or removing padding from CardContent keeps the layout consistent (then it becomes the old design).
 Should I use (px-4 sm:px-5) in CardHeader?
image

File: src/components/Users/UserSummary.tsx (hunk 4 above)
Comment (Jacobjeevan) [reply src/components/Users/UserSummary.tsx]: Nah, let's not change Shadn's components.

**Review by Jacobjeevan — APPROVED** [review]

File: src/components/Users/UserSummary.tsx (hunk 5 above)
Comment (geyamrutha16) [reply src/components/Users/UserSummary.tsx]: Fixed!

**Comment by geyamrutha16** [comment]
@Jacobjeevan , I've pushed a commit addressing this change
image

**Comment by nihal467** [comment]
image

- the badge is stretched for no reason in normal desktop view. Can you fix them

**Comment by nihal467** [comment]
LGTM

**Review by Jacobjeevan — APPROVED** [review]
