### PR TITLE
fix: Misalignment and inconsistency in the UI of 'Add Files' dropdown in encounter files

### LINKED ISSUE #12523: Misalignment and inconsistency in the UI of 'Add Files' dropdown in encounter files
**Describe the bug**
There's a misalignment and some inconsistencies in the UI of 'Add Files' dropdown in encounter files 
**To Reproduce**

1. Go to Encounter
2. Click on Files
3. Click add files
4. See

https://github.com/user-attachments/assets/39cfdf49-e5c3-48ff-a003-b4f5d2492e5d

**Desktop (please complete the following information):**

- OS: Fedora
- Browser Brave

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by perpetrator1**
## Proposed Changes
- Fixes #12523

https://github.com/user-attachments/assets/d2201088-f76f-4313-b8fe-26b5d1f0c8d0

This pull request refactors the `FilesPage` component in `src/components/Files/FileSubTab.tsx` to improve accessibility and simplify the codebase. Key changes include replacing the `Label` component with native HTML `<label>` elements, removing unused imports, and replacing `Button` components with `<div>` elements for better customization.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **Refactor**
  * Streamlined dropdown menus for file upload, camera, and audio capture options by simplifying structure and removing nested buttons.
  * Updated styling for dropdown items and labels for improved consistency and appearance.

* **Style**
  * Adjusted icon spacing and hover effects for a cleaner user interface.

* **Accessibility**
  * Added aria-label attributes to dropdown menu items to enhance accessibility.

### CODE REVIEW

File: src/components/Files/FileSubTab.tsx [hunk 1]
```diff
@@ -370,38 +369,36 @@ export const FilesPage = ({
...
           </DropdownMenuItem>
           <DropdownMenuItem asChild>
-            <Button
-              size="sm"
-              variant="ghost"
+            <div
+              role="button"
               onClick={() => fileUpload.handleCameraCapture()}
-              className="flex flex-row justify-stretch items-center w-full text-primary-900"
+              className="text-primary-900"
```
Comment (AdityaJ2305) [inline src/components/Files/FileSubTab.tsx]: Can we use directly `DropdownMenuItem `  onSelect instead of nested div's `onClick` ?

Comment (perpetrator1) [reply src/components/Files/FileSubTab.tsx]: Sure, i was kinda confused with the asChild stuff so i kept it as it was

File: src/components/Files/FileSubTab.tsx [hunk 2]
```diff
@@ -369,39 +368,34 @@ export const FilesPage = ({
...
+            <label
               htmlFor={`file_upload_${type}`}
-              className="py-1 flex flex-row items-center cursor-pointer text-primary-900  w-full"
               data-cy="choose-file-option"
+              className="flex items-center gap-1 w-full text-primary-900 hover:text-black"
             >
               <CareIcon icon="l-file-upload-alt" className="mr-1" />
               <span>{t("choose_file")}</span>
-            </Label>
+            </label>
```
Comment (Tanuj1718) [inline src/components/Files/FileSubTab.tsx]: I think you can import label from components and add classes in it. It will maintain consistency

**Review by Tanuj1718 — CHANGES_REQUESTED** [review]
Why label is not used from components?🤔 I guess we are importing it everywhere from UI components.

**Comment by perpetrator1** [comment]
> Why label is not used from components?🤔 I guess we are importing it everywhere from UI components.

it works just fine without it, we were importing it for pretty much no reason

**Comment by Tanuj1718** [comment]
> > Why label is not used from components?🤔 I guess we are importing it everywhere from UI components.
> 
> it works just fine without it, we were importing it for pretty much no reason

Isn't it reducing consistency?

File: src/components/Files/FileSubTab.tsx (hunk 2 above)
Comment (perpetrator1) [reply src/components/Files/FileSubTab.tsx]: I guess it does maintain consistency

**Review by AdityaJ2305 — APPROVED** [review]

**Comment by Jacobjeevan** [comment]
image

See if you can do something about the empty space to the right of open camera and record audio.

**Comment by perpetrator1** [comment]
CC:@Jacobjeevan 
> See if you can do something about the empty space to the right of open camera and record audio.


https://github.com/user-attachments/assets/6c0303ef-8425-4b95-b38f-2c7374d32bd7

How about now?

File: public/locale/en.json [hunk 3]
```diff
@@ -670,7 +670,7 @@
   "checking_policy_eligibility": "Checking Policy Eligibility",
   "choose_date_time": "Choose Date and Time",
   "choose_district": "Choose District",
-  "choose_file": "Upload From Device",
+  "choose_file": "Choose Files",
```
Comment (AdityaJ2305) [inline public/locale/en.json]:
```suggestion
  "choose_files": "Choose Files",
```

File: src/components/Files/FileSubTab.tsx [hunk 4]
```diff
@@ -365,39 +365,34 @@ export const FilesPage = ({
...
           >
             <Label
               htmlFor={`file_upload_${type}`}
-              className="py-1 flex flex-row items-center cursor-pointer text-primary-900  w-full"
               data-cy="choose-file-option"
+              className="flex items-center w-full text-primary-900 hover:text-black py-1 font-normal"
             >
-              <CareIcon icon="l-file-upload-alt" className="mr-1" />
+              <CareIcon icon="l-file-upload-alt" />
               <span>{t("choose_file")}</span>
```
Comment (AdityaJ2305) [inline src/components/Files/FileSubTab.tsx:378]:
```suggestion
              <span>{t("choose_files")}</span>
```

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]
needs to update the cypress file which is searching for text `Upload From Device` to `Choose files` since you changed the text right

File: src/components/Files/FileSubTab.tsx (hunk 4 above)
Comment (perpetrator1) [reply src/components/Files/FileSubTab.tsx:378]: Thanks a lot :pray:

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
image

Above is the develop

image

Above is the PR

- retain the font format for the text

**Comment by perpetrator1** [comment]
> retain the font format for the text

@nihal467 You mean like this right?

Screenshot_20250708_182654

**Comment by nihal467** [comment]
- why the text changed from upload from device to choose file, keep the text as it is !
- still the font from current develop is different, can you compare them side by side and check once

**Comment by perpetrator1** [comment]
> - why the text changed from upload from device to choose file, keep the text as it is !
> - still the font from current develop is different, can you compare them side by side and check once

https://github.com/ohcnetwork/care_fe/pull/12524#issuecomment-2961255196

CC: @nihal467 @Jacobjeevan

**Comment by perpetrator1** [comment]
> See if you can do something about the empty space to the right of open camera and record audio.
https://github.com/ohcnetwork/care_fe/pull/12524#issuecomment-2961255196

So should i keep it as "Choose Files" or revert to the previous "Upload From Device?"

> still the font from current develop is different, can you compare them side by side and check once

Did you mean font weight?

Screenshot_20250722_223354

I still cant see the font issue. Here's what it looks like when i change "Choose Files" to "Upload From Device" without doing anything to the font

@nihal467 @Jacobjeevan

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
