### PR TITLE
Re-design Encounter Card

### LINKED ISSUE #10297: Bug: Green Progress Bar for Completed Status Only Visible on Hover
**Describe the bug**
The green progress bar in the Encounters page only appears when hovering over a specific section. For entries marked as "Completed", the progress bar should remain green at all times to indicate completion, even without user interaction.

**To Reproduce**

1. Navigate to the Patient Details 
2. Click on Encounters tab.
3. Hover over a "Completed" entry.

**Expected behavior**
For entries marked as "Completed", the green progress bar should remain visible permanently to visually represent the completed status.

**Screenshots**

https://github.com/user-attachments/assets/c67a9661-8853-4f6d-9a05-4f2ffe0440d4

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #10297 
- [x] Redesigned Encounter Card 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Upgraded the encounter information display with refreshed icons, dynamic badge styling, and a reorganized grid layout for improved responsiveness and visual clarity.

- **Style**
  - Streamlined text styling in the encounter type description for a cleaner presentation.

- **Chores**
  - Introduced new encounter icons and constants to enhance functionality related to encounter displays.

image

### CODE REVIEW

File: src/components/Facility/EncounterCard.tsx [hunk 1]
```diff
@@ -20,88 +19,104 @@ export const EncounterCard = (props: EncounterCardProps) => {
...
+                variant="outline"
+                onClick={() =>
+                  navigate(
+                    `/facility/${encounter.facility.id}/encounter/${encounter.id}/updates`,
+                  )
+                }
+                className="p-2 border border-black"
+              >
+                <Eye />
+                {t("View Encounter")}
```
Comment (rithviknishad) [inline src/components/Facility/EncounterCard.tsx]: is this right?

Comment (AdityaJ2305) [reply src/components/Facility/EncounterCard.tsx]: icon ?  `<Eye/>` ? 

@rithviknishad, one more thing—does GitHub send push notifications when replying to a review without tagging? 🤔

File: src/components/Facility/EncounterCard.tsx [hunk 2]
```diff
@@ -20,88 +19,104 @@ export const EncounterCard = (props: EncounterCardProps) => {
...
-            buttonVariants({ variant: "secondary" }),
-            "mt-2 shadow-none border border-secondary-300",
-            !encounter.period.start && "pointer-events-none opacity-50",
-          )}
-        >
-          <CareIcon icon="l-plus-circle" />
-          {t("View Encounter")}
-        </Link>
+            <div className="grid sm:flex sm:flex-wrap sm:justify-between gap-4">
+              {[
```
Comment (Jacobjeevan) [inline src/components/Facility/EncounterCard.tsx]: let's move this array into it's own variable.

File: src/components/Facility/EncounterCard.tsx (hunk 1 above)
Comment (Jacobjeevan) [reply src/components/Facility/EncounterCard.tsx]: He meant the line below.

And no on the push notifications without tagging; we will get the email notifications though.

File: src/components/Facility/EncounterCard.tsx [hunk 3]
```diff
@@ -20,88 +19,104 @@ export const EncounterCard = (props: EncounterCardProps) => {
...
-        <Badge
-          variant={
-            completedEncounterStatus.includes(encounter.status)
-              ? "outline"
-              : "secondary"
-          }
-          className="inline-flex items-center gap-2 -translate-y-2"
-        >
+      <div className="pb-6 block relative border-l-2 px-4 border-l-secondary-300">
+        <div className="absolute -left-[12px] top-0 bg-white">
```
Comment (Jacobjeevan) [inline src/components/Facility/EncounterCard.tsx]: Rm the bg-white; you will probably have to adjust the positioning since border is in parent div (maybe move it to a container div wrapping the card instead?).

Also switch to rem.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Facility/EncounterCard.tsx (hunk 1 above)
Comment (AdityaJ2305) [reply src/components/Facility/EncounterCard.tsx]: Oh, I missed checking that one—it’s an older one. 😅

File: src/components/Facility/EncounterCard.tsx [hunk 4]
```diff
@@ -18,90 +17,105 @@ interface EncounterCardProps {
 
 export const EncounterCard = (props: EncounterCardProps) => {
   const { encounter } = props;
+
+  const encounterDetails = [
```
Comment (bodhish) [inline src/components/Facility/EncounterCard.tsx]: Why do we need a complex dx? Can't we just write pure html for rendering these? 🤔

**Comment by bodhish** [comment]
@AdityaJ2305 please add screenshot or demo video for your PR's so that its really easier for the reviewer to see what chagned visually.

File: src/components/Facility/EncounterCard.tsx (hunk 4 above)
Comment (AdityaJ2305) [reply src/components/Facility/EncounterCard.tsx]: Done

**Comment by AdityaJ2305** [comment]
Screenshot 2025-02-14 at 4 38 12 PM

File: src/components/Facility/EncounterCard.tsx [hunk 5]
```diff
@@ -18,90 +17,106 @@ interface EncounterCardProps {
...
+                    {encounter.external_identifier}
+                  </div>
+                </div>
+              )}
+            </div>
+            <div className="w-full py-2 bg-gray-100 px-2">
+              <Button
+                variant="outline"
+                onClick={() =>
+                  navigate(
```
Comment (Jacobjeevan) [inline src/components/Facility/EncounterCard.tsx]: Let's switch to use Link inside the button here

**Review by Jacobjeevan — COMMENTED** [review]
The font size of card contents (facility, start date etc) relative to other elements in the page is a bit off 🤔  But other than that, lgtm.

image

File: src/components/Facility/EncounterCard.tsx [hunk 6]
```diff
@@ -18,90 +17,106 @@ interface EncounterCardProps {
...
-            <CircleCheck className="w-4 h-4 text-green-300" />
+            <BadgeCheck className="w-5 h-5 text-teal-300" />
           ) : (
-            <CircleDashed className="w-4 h-4 text-yellow-500" />
+            <CircleDashed className="w-5 h-5 text-purple-400" />
           )}
-          {t(`encounter_status__${encounter.status}`)}
-        </Badge>
+          {/* Vertical Line */}
+          <div className="w-[2px] h-full bg-secondary-300"></div>
```
Comment (rithviknishad) [inline src/components/Facility/EncounterCard.tsx]: Arbitrary classes are no longer allowed. Also use Shadcn's `<Separator />` component instead

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by AdityaJ2305** [comment]
@Jacobjeevan, I’m a bit confused about the font size—are you referring to the headings like “Facility” and “Start Date” or the font size of their values? 😅
other than this other changes are done

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan, I’m a bit confused about the font size—are you referring to the headings like “Facility” and “Start Date” or the font size of their values? 😅 other than this other changes are done

Both the labels and values.

**Comment by AdityaJ2305** [comment]
@Jacobjeevan, done!
Although, it was a bit difficult for me to notice the changes when I updated everything at once, so I made the changes step by step to notice them more easily 😅.

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
image
image

- [ ] The encounter type badge number and symbol need to change based on its type as per Figma design,  currently it's not happening
- [ ] Keep the in-progress / active ones on the top

File: src/components/Encounter/CreateEncounterForm.tsx [hunk 7]
```diff
@@ -226,7 +226,7 @@ export default function CreateEncounterForm({
                           <div className="flex flex-col items-center text-center">
                             <Icon className="size-6" />
                             <div className="text-sm font-bold">{label}</div>
-                            <div className="text-wrap text-xs text-center text-xs text-gray-500">
+                            <div className="text-wrap text-xs text-center text-gray-500">
```
Comment (AdityaJ2305) [inline src/components/Encounter/CreateEncounterForm.tsx]: Just typo err

**Comment by AdityaJ2305** [comment]
@nihal467 ,  I've added the icon sync with encounter class like we do have it in "Initiate Patient Encounter" form .

> - [ ] Keep the in-progress / active ones on the top

I'm not able to understand above point

File: src/components/Facility/EncounterCard.tsx [hunk 8]
```diff
@@ -18,90 +29,123 @@ interface EncounterCardProps {
...
   const { encounter } = props;
+
+  const encounterIcons = {
+    imp: BedDouble,
+    amb: Ambulance,
+    obsenc: Stethoscope,
+    emer: Building2,
+    vr: MonitorSmartphone,
+    hh: Home,
+  } as const;
```
Comment (rithviknishad) [inline src/components/Facility/EncounterCard.tsx]: let's move this to constants / types; since it's potentially reusable, also do `as const satisfies Record<encounter_type, ...>`

**Review by rithviknishad — APPROVED** [review]
lgtm, minor thing

File: src/common/constants.tsx [hunk 9]
```diff
@@ -354,6 +366,14 @@ export const FILE_EXTENSIONS = {
...
   DOCUMENT: ["pdf", "docx"],
 } as const;
+export const encounterIcons = {
+  imp: BedDouble,
+  amb: Ambulance,
+  obsenc: Stethoscope,
+  emer: Building2,
+  vr: MonitorSmartphone,
+  hh: Home,
+} as const satisfies Record<EncounterClass, LucideIcon>;
```
Comment (rithviknishad) [inline src/common/constants.tsx]: this could be react node instead.

Comment (AdityaJ2305) [reply src/common/constants.tsx]: Done

**Comment by nihal467** [comment]
LGTM
