### PR TITLE
Move the cancel button to the right in facility inventory add page!

### LINKED ISSUE #6613: Move the cancel button to the right in facility  inventory add page
**Describe the bug**

The cancel button is on the left side in the inventory add page, which is design inconsistency compared to other page

**To Reproduce**

1. Go to facility inventory add page
2. See error

**Expected behavior**

Move the cancel button to the right side of the inventory add a page, to ensure design consistency 

**Screenshots**

image

### PR DESCRIPTION
**Pull request by AshrafMd-1**
### <samp>🤖 Generated by Copilot at 3ae62fc</samp>

This pull request improves the functionality and appearance of the `AddInventoryForm` component. It uses the `useFacility` hook to get the current facility id and adjusts the button layout to match the design.

## Proposed Changes

- Fixes #6613 
- Moved the cancel button to the right side.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 3ae62fc</samp>

* Import the `useFacility` hook to access the selected facility state and dispatch actions ([link](https://github.com/coronasafe/care_fe/pull/6623/files?diff=unified&w=0#diff-0cbcee446c25081b9cc3657703cc28e1aadc287f7d948423827bcff814f803b9R19))
* Add a new state variable `facilityId` and assign it the value of the selected facility id from the `useFacility` hook ([link](https://github.com/coronasafe/care_fe/pull/6623/files?diff=unified&w=0#diff-0cbcee446c25081b9cc3657703cc28e1aadc287f7d948423827bcff814f803b9R126))
* Modify the CSS class of the div that contains the cancel and submit buttons to align them to the end of the flex container in `AddInventoryForm.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6623/files?diff=unified&w=0#diff-0cbcee446c25081b9cc3657703cc28e1aadc287f7d948423827bcff814f803b9L330-R332))

### CODE REVIEW

File: src/Components/Facility/AddInventoryForm.tsx [hunk 1]
```diff
@@ -327,7 +329,7 @@ export const AddInventoryForm = (props: any) => {
                 />
               </div>
             </div>
-            <div className="mt-4 flex flex-col justify-between gap-2 md:flex-row">
+            <div className="mt-4 flex flex-col justify-end gap-2 md:flex-row">
```
Comment (rithviknishad) [inline src/Components/Facility/AddInventoryForm.tsx]:
```suggestion
            <div className="cui-form-button-group">
```

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
