### PR TITLE
Enhancement: Add newPatient type

### LINKED ISSUE #12158: Remove `src/types/emr/patient/patient.ts` type and replace all usages with the `newPatient` type
### Description:
The `src/types/emr/patient/patient.ts` type is deprecated and should be removed from the codebase. All existing references to this type should be identified and replaced with the `newPatient` file to ensure consistency and maintainability.

### Tasks:
1. Identify all instances where the `src/types/emr/patient/patient.ts` type is used in the codebase.
2. Replace these instances with the `newPatient` type.
3. Remove the `src/types/emr/patient/patient.ts` file from the repository.
4. Perform thorough testing to confirm there are no regressions or issues caused by this update.

### PR DESCRIPTION
**Pull request by yadavshubham01**
## Proposed Changes

- Fixes #12158 
- remove src/types/emr/patient/patient.ts type is used in the codebase
- Replace these instances with the newPatient type.
- delete patient.ts
- testing the change locally 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Added new fields to patient records: nationality (optional) and partial ID (required).

- **Refactor**
  - Updated all patient-related features to use a streamlined patient data structure, replacing the previous model.
  - Adjusted age formatting and patient card display to align with the updated patient data structure.
  - Standardized patient type imports across the application for consistency.

- **Chores**
  - Removed legacy patient model and its validation logic from the system.

### CODE REVIEW

File: src/types/emr/newPatient.ts
Comment (rithviknishad) [inline src/types/emr/newPatient.ts:1]: I'd say, move the contents of this file to `types/emr/patient.ts` instead! Ideas is just to phase out the old type away!

Comment (yadavshubham01) [reply src/types/emr/newPatient.ts:1]: if we move the contents of types/emr/newPatient.ts to types/emr/patient.ts, we’d need to update all existing imports across the codebase from newPatient to patient. Since newPatient is already widely used, this could introduce unnecessary churn.

Comment (rithviknishad) [reply src/types/emr/newPatient.ts:1]: That's fine, build will fail if something's wrong anyways :) we are safe to do it!

Comment (yadavshubham01) [reply src/types/emr/newPatient.ts:1]: ok let me convert this file this patient.ts

**Comment by yadavshubham01** [comment]
hey @rithviknishad does we need validatePatient fuction as far i know we cannot use that anywhere in our codebase??

**Comment by rithviknishad** [comment]
> hey @rithviknishad does we need validatePatient fuction as far i know we cannot use that anywhere in our codebase??

@yadavshubham01 nice find!

Yup! Feel free to remove any old pices that has 0 references without hesitation!

image

----

You can enable these two settings to find them out!

image

File: src/types/emr/patient.ts [hunk 1]
```diff
@@ -1,135 +1,48 @@
...
+  year_of_birth: number;
+  created_date: string;
+  modified_date: string;
+  geo_organization: Organization;
+  created_by: UserBareMinimum | null;
+  updated_by: UserBareMinimum | null;
+  permissions: string[];
+  nationality?: string;
+  partial_id: string;
 }
```
[the remark this answers is not in the document]
Comment (yadavshubham01) [reply src/types/emr/patient.ts]: hey @rithviknishad what about this issue ?? does we need any changes ? like as far i know we can handle this thing in patientRegistration correctly

**Comment by yadavshubham01** [comment]
@rithviknishad  done

**Review by rithviknishad — APPROVED** [review]

**Review by abhimanyurajeesh — APPROVED** [review]

**Comment by yadavshubham01** [comment]
@Jacobjeevan need review

**Comment by nihal467** [comment]
@Jacobjeevan can you look into this

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
