### PR TITLE
Encounter overview enhancements

### LINKED ISSUE #12861: Fix responsiveness for encounter page
https://github.com/user-attachments/assets/1c95c873-a6a1-4da8-b210-e2b2bcd796c9

### LINKED ISSUE #12886: Fix console warning for Encounter view page
**Describe the bug**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### LINKED ISSUE #12893: Encounter overview tab Show Add Questionnaire for mobile
**Describe the bug**
Currently, for mobile view there is double rendering of Clinical history button and Add Questionnaire is missing 

https://github.com/user-attachments/assets/d1e2e85e-7fb0-4942-9e88-3d26a9687daa

**Expected behavior**
Show Add Questionnaire instead of second rendered Clinical history button

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a comleted Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by rithviknishad**
### Proposed Changes

- Show encounter created by, updated by and timestamps in right sidebar
- Add load more (infinite query) pagination for symptoms, allergies, diagnosis, prescriptions and medication statement tables.
- Fixed stylings and wrap tabs (by @abhimanyurajeesh)
- Add support for going back from clinical history page (by @abhimanyurajeesh)
- Fixes #12893
- Fixes #12886
- Fixes #12861

## Summary by CodeRabbit

* **New Features**
  * Added an audit log section to encounter overviews, displaying creator and last modifier details with timestamps.
  * Introduced "Load More" functionality for allergies, diagnoses, symptoms, medication statements, medication requests, and prescriptions, enabling incremental loading of large lists.
  * Added a responsive close button to the patient history tabs, allowing users to return to their previous context.
  * Added tag display and management section for encounters with editing capabilities.

* **Improvements**
  * Enhanced pagination and performance for allergy, diagnosis, symptom, medication, and medication request lists with infinite scrolling.
  * Improved mobile responsiveness and button sizing in encounter overview and patient history pages.
  * Updated encounter history and class label styles for better visual clarity.
  * Preserved navigation context when switching patient history tabs.
  * Simplified medication statement row styling by directly using status to indicate errors.
  * Adjusted UI modality for tag selection popover and assignment sheet components.
  * Added automatic sidebar collapse behavior in encounter view for improved focus and layout.
  * Enhanced UI responsiveness and horizontal scrolling in encounter show and overview tabs.
  * Improved icon rendering consistency in pharmacy medication request tabs.
  * Aligned questionnaire search size prop with button component sizing options.
  * Added horizontal scrolling to medication history tabs for better navigation.
  * Updated test setups for consistent viewport sizes and improved element interaction reliability.

### CODE REVIEW

**Review by abhimanyurajeesh — APPROVED** [review]

File: src/components/Patient/MedicationStatementList.tsx [hunk 1]
```diff
@@ -56,12 +79,12 @@ export function MedicationStatementList({
     );
   }
 
-  const filteredMedications = medications?.results?.filter(
+  const filteredMedications = medications?.filter(
```
Comment (Jacobjeevan) [inline src/components/Patient/MedicationStatementList.tsx]: filter in query 👍 We have multi filter for status on BE.

File: src/components/Patient/allergy/list.tsx [hunk 2]
```diff
@@ -64,29 +65,48 @@ export function AllergyList({
...
   });
 
+  const allergies = allergiesData?.pages.flatMap((page) => page.results) ?? [];
+
   if (isLoading) {
     return <TableSkeleton count={5} />;
   }
 
-  const filteredAllergies = allergies?.results?.filter(
+  const filteredAllergies = allergies?.filter(
```
Comment (Jacobjeevan) [inline src/components/Patient/allergy/list.tsx]: Same here, requested @nandkishorr to change to multifilter on BE.

File: src/components/Patient/symptoms/list.tsx [hunk 3]
```diff
@@ -39,27 +40,46 @@ export function SymptomsList({
...
   });
 
   if (isLoading) {
     return <TableSkeleton count={5} />;
   }
 
-  const filteredSymptoms = symptoms?.results?.filter(
+  const symptoms = symptomsData?.pages.flatMap((page) => page.results) ?? [];
+
+  const filteredSymptoms = symptoms?.filter(
```
Comment (Jacobjeevan) [inline src/components/Patient/symptoms/list.tsx]: Same here, can do the same thing as diagnosis since filters are condition spec based.

File: src/components/Patient/allergy/list.tsx (hunk 2 above)
Comment (nandkishorr) [reply src/components/Patient/allergy/list.tsx]: [Issue resolved pr link](https://github.com/ohcnetwork/care/pull/3141) @rithviknishad

**Comment by nihal467** [comment]
- Middle-screen UI for the page is broken
- fix the cypress test

**Review by Jacobjeevan — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]
Quick Aproval
