### PR TITLE
Fix: Render MedicationValueSetSelect when enableProduct is true in EntitySelectionSheet

### LINKED ISSUE #13160: Bug: MedicationStatement in not handling product select for mobile and missing MedicationValuesetselect for desktop
**Describe the bug**
For Desktop, the system is using ValueSetSelect instead of MedicationValueSetSelect and for mobile, it is using MedicationValueSetSelect but not handling product selection 

https://github.com/user-attachments/assets/9e80374c-cd92-43bd-af32-e890843d942b

**To Reproduce**

- Go to any live encounter 
- Add Questionnaire (Medication statement)
- See the error by referring to the video above

**Expected behavior**
Both should use MedicationValueSetSelect and handle product select 

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #13160
- If `onProductEntitySelected` is provided, the `MedicationValueSetSelect` will render
- we only want to show MedicationValueSet for Medicatin request not for medication statement 

Screenshot 2025-08-04 at 8 39 50 PM

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.

## Summary by CodeRabbit

* **New Features**
  * Introduces an optional product-based selection mode for medications. When enabled, users can choose specific medication products directly in the main view and within the selection sheet when no item is selected. Mobile flows are supported. Default behavior remains unchanged (mode off), preserving the existing value-set selection experience. No impact to existing actions or labels.

### CODE REVIEW

**Review by yash-learner — APPROVED** [review]
LGTM

File: src/components/Questionnaire/EntitySelectionSheet.tsx [hunk 1]
```diff
@@ -133,7 +134,7 @@ export function EntitySelectionSheet({
 
   return (
     <>
-      {system === "system-medication" ? (
+      {onProductEntitySelected ? (
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/EntitySelectionSheet.tsx]: Let's not do this. Adding an extra prop is clearer in intent (plus, separation of concerns). While this works now, there's no guarantee that onProductEntitySelected will always be provided in future use cases.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
