### PR TITLE
Fix diagnostic_report translation key across components

### LINKED ISSUE #15452: Fix diagnostic_report translation key across components
The `diagnostic_report` translation key is updated to `diagnostic_report_one` in `en.json` but keys in components are not updated 

For example here:

Image

### PR DESCRIPTION
**Pull request by yash-learner**
## Proposed Changes

Fixes https://github.com/ohcnetwork/care_fe/issues/15452

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Chores**
  * Standardized diagnostic report labels to use pluralization-aware translations across views, print preview, and settings so fallback titles display consistently.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
should be using count https://www.i18next.com/translation-function/plurals

File: src/pages/Encounters/tabs/diagnostic-reports.tsx [hunk 1]
```diff
@@ -69,7 +69,7 @@ function LeftCard({ report, isActive, onClick }: LeftCardProps) {
       <div className="flex items-center justify-between">
         <div className="flex-1 min-w-0">
           <div className="font-medium pb-1 truncate">
-            {report.service_request?.title || t("diagnostic_report")}
+            {report.service_request?.title || t("diagnostic_report_one")}
```
Comment (AdityaJ2305) [inline src/pages/Encounters/tabs/diagnostic-reports.tsx]: Is there any specific reason for using plural implementation here ? Like why can't we just add the `diagnostic_report` key back ?

Comment (yash-learner) [reply src/pages/Encounters/tabs/diagnostic-reports.tsx]: >Is there any specific reason for using plural implementation here ?

`diagnostic_report_one` is singular 

https://github.com/ohcnetwork/care_fe/blob/ffbb163f004ec03ae3abb48d849338ad12f402da/public/locale/en.json#L1737

----

>  Like why can't we just add the diagnostic_report key back ?

Just reusing already present singular one

🤷‍♂️

**Review by bodhish — APPROVED** [review]
