### PR TITLE
Fix: Make Duplicate Patient Pop-up scrollable on mobile devices

### LINKED ISSUE #11514: Duplicate Patient Pop-up Clipping in Mobile View When Entering an Existing Phone Number in Patient Registration
**Describe the bug**

In the patient registration form, when entering a phone number that already exists in a patient record, a pop-up appears displaying the same phone number. However, on mobile view, the pop-up is clipped and not fully visible.

**To Reproduce**

1. Open the add patient form. 
2. Enter a phone number that is already associated with an existing patient record. (+91 9999999999)
3. Observe that a pop-up appears displaying the existing phone number.
4. On mobile view, the pop-up is clipped and not fully visible.

Tested device : iPhone 14 pro

**Expected behavior**

The pop-up should be fully visible and properly positioned on all screen sizes, including mobile view.

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by yadavshubham01**
## Proposed Changes

- Fixes #11514 
- Added max-h-[90vh] overflow-y-auto to DialogContent
- Ensures dialog scrolls properly on small screens
- Verified behavior on multiple breakpoints

@ohcnetwork/care-fe-code-reviewers
## Screenshot

Screenshot 2025-03-26 220012

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Updated the dialog’s layout for improved responsiveness with refined dimensions and enhanced overflow handling.
  - Simplified the table container styling to allow content expansion without restrictive height limits.

### CODE REVIEW

File: src/components/Facility/DuplicatePatientDialog.tsx [hunk 1]
```diff
@@ -56,7 +56,7 @@ const DuplicatePatientDialog = (props: Props) => {
             </p>
           </div>
           <div>
-            <div className="max-h-[200px] overflow-auto ">
+            <div className="overflow-auto ">
```
Comment (khavinshankar) [inline src/components/Facility/DuplicatePatientDialog.tsx]:
```suggestion
            <div className="overflow-auto">
```

**Review by khavinshankar — APPROVED** [review]

**Comment by nihal467** [comment]
image
image

You have changed the normal view on the laptop screen; keep it as same as our current develop branch.

**Comment by yadavshubham01** [comment]
Hey @nihal467, I just fixed it you can check it now.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
