### PR TITLE
Fix: Minor UI Enhancement in questionnaire

### LINKED ISSUE #10253: Minor UI Enhancement in questionnaire
**Describe the bug**

- [ ] The calendar icon for structured questions with dates are clipping-in in normal view
- [ ] When we completely remove the duration field, 0 gets auto-filled and users are not able to erase it in medicine requests
- [ ] Once the encounter class in the questionnaire is changed by a user to a non-hospitalization class, the existing hospitalization details in the questionnaire should be overwritten as undefined.

For example, if a patient was initially recorded in the questionnaire under the Observation class and hospitalization details such as diet preference and admit source were recorded, but later the encounter class is changed to Ambulatory, where hospitalization details are not required, then upon submitting the form, the existing hospitalization records should be overwritten with null

**Screenshots**

Image

Image

Image

Image

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #10253 
- [x] Fix: when we complete remove the dosage field, 0 get auto-filled and users are not able to erase it in medicine request
- [x] once the encounter class is changed by a user to a non-hospitalisation class, the existing hospitalization data should be overwritten to undefined
- [x] n the questionniare in the update encounter, its clipping in on normal review
Screenshot 2025-03-05 at 3 35 41 AM
- [x] Refactor the code for question types to use shadcn components and have consistent design and structure

Screenshot 2025-03-05 at 6 09 45 PM
Screenshot 2025-03-06 at 1 20 15 AM

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA
- [x] Completion of QA in Mobile Devices
- [x]  Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Enhanced patient encounter forms with improved handling for hospital details based on encounter type.
  - Updated medication dosage input to display a blank field instead of showing 0 for a cleaner interface.

- **Style**
  - Refined the layout of allergy records by adjusting table column widths for improved data presentation.

### CODE REVIEW

**Comment by AdityaJ2305** [comment]
@nihal467  @rithviknishad @amjithtitus09 

- [x] In the questionnaire under "Update Encounter," the content is getting clipped in normal review mode.  

- [x] When the dosage field is completely removed in a medicine request, `0` gets auto-filled, and users are unable to erase it.  

- [ ] When all symptoms, diagnoses, and allergies are removed, the message shows "No recorded." Update it to "No active available" or provide an option to view removed items, even if none are currently active.  
  > Please confirm the expected behavior, as this requires significant changes based on the final decision.  

- [ ] Display the recorded time in questionnaires in a human-readable format.  
  > This seems to be caused by broken data. A similar issue was previously assigned to me but was closed as "Not Planned": [Issue #10661](https://github.com/ohcnetwork/care_fe/issues/10661).  

- [x] If the encounter class is changed to a non-hospitalization class, any existing hospitalization data should be cleared.

File: src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx [hunk 1]
```diff
@@ -114,6 +115,13 @@ export function EncounterQuestion({
   ) => {
     clearError();
     const newEncounter = { ...encounter, ...updates };
+    if (
+      newEncounter.encounter_class === "amb" ||
+      newEncounter.encounter_class === "vr" ||
+      newEncounter.encounter_class === "hh"
+    ) {
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx]: let's use `.includes` instead

cc: @khavinshankar

File: src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx [hunk 2]
```diff
@@ -656,7 +659,9 @@ const MedicationRequestGridRow: React.FC<MedicationRequestGridRowProps> = ({
                     repeat: {
                       ...dosageInstruction.timing.repeat,
                       bounds_duration: {
-                        value: Number(value),
+                        value: value
+                          ? Number(value)
+                          : (undefined as unknown as number),
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx]: i don't think undefined is a number, fixing the type is the right way right?

**Review by rithviknishad — DISMISSED** [review]

File: src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx (hunk 1 above)
Comment (AdityaJ2305) [reply src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx]: Done

File: src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx (hunk 2 above)
Comment (AdityaJ2305) [reply src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx]: Done

**Comment by amjithtitus09** [comment]
> @nihal467 @rithviknishad @amjithtitus09
> 
> * [ ]  In the questionnaire under "Update Encounter," the content is getting clipped in normal review mode.
>   > I couldn't understand the issue clearly. Could you share a screenshot? If it's the first one you shared in the issue, it is outdated issue then.
> * [x]  When the dosage field is completely removed in a medicine request, `0` gets auto-filled, and users are unable to erase it.
> * [ ]  When all symptoms, diagnoses, and allergies are removed, the message shows "No recorded." Update it to "No active available" or provide an option to view removed items, even if none are currently active.
>   > Please confirm the expected behavior, as this requires significant changes based on the final decision.
> * [ ]  Display the recorded time in questionnaires in a human-readable format.
>   > This seems to be caused by broken data. A similar issue was previously assigned to me but was closed as "Not Planned": [Issue #10661](https://github.com/ohcnetwork/care_fe/issues/10661).
> * [x]  If the encounter class is changed to a non-hospitalization class, any existing hospitalization data should be cleared.

@AdityaJ2305 Why not clear these doubts in the issue itself?

**Comment by amjithtitus09** [comment]
@AdityaJ2305 Date field looks very weird
image

**Comment by AdityaJ2305** [comment]
> @AdityaJ2305 Date field looks very weird image

@amjithtitus09 , that's the shadcn input we are using , what changes do I need to do to make it look good . If u are referring to calendar icon , as when field is disabled input doesn't enable calendar icon

**Comment by amjithtitus09** [comment]
> > @AdityaJ2305 Date field looks very weird image
> 
> @amjithtitus09 , that's the shadcn input we are using , what changes do I need to do to make it look good . If u are referring to calendar icon , as when field is disabled input doesn't enable calendar icon

@AdityaJ2305 Too much empty space to both sides of the calendar icon

**Comment by AdityaJ2305** [comment]
@amjithtitus09 done with the changes

**Comment by amjithtitus09** [comment]
@AdityaJ2305 Date field is clipped out here
image

**Comment by AdityaJ2305** [comment]
@amjithtitus09 , done with the changes, now it shouldn't make any issue with calendar icon

File: src/components/Questionnaire/QuestionTypes/SymptomQuestion.tsx [hunk 3]
```diff
@@ -183,97 +190,94 @@ const SymptomRow = React.memo(function SymptomRow({
...
-            {t("date")}
-          </div>
+    <>
+      <TableRow
+        className={cn("group hover:bg-gray-50", {
+          "opacity-40 pointer-events-none":
+            symptom.verification_status === "entered_in_error",
+        })}
+      >
+        <TableCell className="min-w-[220px] font-medium py-1 pl-1">
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionTypes/SymptomQuestion.tsx]: See if you can make this work without mentioning a min width, if not, switch to using relative widths or rem instead of pixels. Same goes for other instances here where width is explicitly defined.

File: src/components/Questionnaire/QuestionTypes/DiagnosisQuestion.tsx [hunk 4]
```diff
@@ -228,164 +438,139 @@ interface DiagnosisItemProps {
...
+        ? "opacity-60"
+        : diagnosis.clinical_status === "resolved"
+          ? "line-through"
+          : ""
+  }`;
+
+  const handleNotesToggle = () => {
+    if (showNotes) {
+      setShowNotes(false);
+      onUpdate?.({ note: undefined });
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionTypes/DiagnosisQuestion.tsx]: why? 🤔

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/QuestionTypes/DiagnosisQuestion.tsx (hunk 4 above)
Comment (AdityaJ2305) [reply src/components/Questionnaire/QuestionTypes/DiagnosisQuestion.tsx]: my bad, removed unwanted changes from same file

File: src/components/Questionnaire/QuestionTypes/SymptomQuestion.tsx (hunk 3 above)
Comment (AdityaJ2305) [reply src/components/Questionnaire/QuestionTypes/SymptomQuestion.tsx]: @Jacobjeevan, I think we can remove min-width since it’s already defined for TableHeader, so there’s no need to set it for TableRow.

Comment (AdityaJ2305) [reply src/components/Questionnaire/QuestionTypes/SymptomQuestion.tsx]: As per your review, I'll do the same for other files

File: src/components/Questionnaire/QuestionTypes/DiagnosisQuestion.tsx (hunk 4 above)
Comment (AdityaJ2305) [reply src/components/Questionnaire/QuestionTypes/DiagnosisQuestion.tsx:412]: https://github.com/user-attachments/assets/781c1e22-b2e7-45be-aa76-c47d5222f466

it was not updating the notes it is a bug right ?

Comment (AdityaJ2305) [reply src/components/Questionnaire/QuestionTypes/DiagnosisQuestion.tsx:412]: If it is, it is for every table i should file an issue and it will be solved in this pr only

Comment (AdityaJ2305) [reply src/components/Questionnaire/QuestionTypes/DiagnosisQuestion.tsx:412]: cc: @amjithtitus09

File: src/style/index.css
Comment (Jacobjeevan) [inline src/style/index.css:1]: Hmm, this needs to be tested on mobile + w/ other places where date input is used.

**Review by Jacobjeevan — APPROVED** [review]

File: src/style/index.css
Comment (AdityaJ2305) [reply src/style/index.css:1]: Tested from my side 
in fact, tested the same for this pr https://github.com/ohcnetwork/care_fe/pull/11342

**Comment by nihal467** [comment]
LGTM

File: src/components/Questionnaire/QuestionTypes/DiagnosisQuestion.tsx [hunk 5]
```diff
@@ -191,22 +196,187 @@ export function DiagnosisQuestion({
...
+                  <TableHead className="w-20 text-center px-0.5">
+                    {t("date")}
+                  </TableHead>
+                  <TableHead className="w-21 text-center px-0.5">
+                    {t("status")}
+                  </TableHead>
+                  <TableHead className="w-21 text-center px-0.5">
+                    {t("verification")}
+                  </TableHead>
+                  <TableHead className="w-9"></TableHead>
```
Comment (amjithtitus09) [inline src/components/Questionnaire/QuestionTypes/DiagnosisQuestion.tsx]: @AdityaJ2305  There is not title for action in Diagnosis, but there is in Symptoms. Can you make it consistent?

**Review by amjithtitus09 — CHANGES_REQUESTED** [review]

**Comment by amjithtitus09** [comment]
@AdityaJ2305 
image

File: src/components/Questionnaire/QuestionTypes/DiagnosisQuestion.tsx (hunk 5 above)
Comment (AdityaJ2305) [reply src/components/Questionnaire/QuestionTypes/DiagnosisQuestion.tsx]: Added for allergy question as well :)

File: src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx (hunk 2 above)
Comment (AdityaJ2305) [reply src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx]: Screenshot 2025-03-21 at 2 36 41 PM

@amjithtitus09 @amjithtitus09

**Comment by AdityaJ2305** [comment]
> @AdityaJ2305 image

https://github.com/ohcnetwork/care_fe/pull/10987#discussion_r2007142393

**Comment by amjithtitus09** [comment]
> > @AdityaJ2305 image
> 
> [#10987 (comment)](https://github.com/ohcnetwork/care_fe/pull/10987#discussion_r2007142393)

@AdityaJ2305 Not sure what you're trying to convey. Is it fixed?

**Comment by AdityaJ2305** [comment]
@amjithtitus09 , ignore it

**Comment by AdityaJ2305** [comment]
@amjithtitus09 
Screenshot 2025-03-23 at 9 41 42 PM

all the changes are done already but while resolving conflicts I got stuck with above ui bug a lot a empty side to right side of which is causing overflow, I've tried multpile ways but couldn't figure it out . coudl u help me out with this

**Comment by AdityaJ2305** [comment]
@amjithtitus09  Ready for review and testing

**Comment by amjithtitus09** [comment]
@AdityaJ2305 Reverting changes in Symptom & diagnosis to avoid conflicts with for other larger PRs, also since the original calendar issue no longer exists as a different date picker is being used now.

**Comment by AdityaJ2305** [comment]
@amjithtitus09 changes were made to make structure consistent in desktop view(used shadcn comp like we have for allergy and code refactor ) if i m not wrong you are talking about Improve ui for small device , Should i make changes after that pr got merged ?

**Comment by amjithtitus09** [comment]
@AdityaJ2305 Take it up as a different issue since that's not in the scope of this issue. Better to get this merged quickly.

Can you take a look at criticality field?
image

**Comment by AdityaJ2305** [comment]
Screenshot 2025-03-25 at 5 53 04 PM
Screenshot 2025-03-25 at 5 57 54 PM


@amjithtitus09 , done

**Review by amjithtitus09 — APPROVED** [review]
