### PR TITLE
Fix: Redesign the User view of Department/Teams

### LINKED ISSUE #10375: Redesign the Open view of Department/Teams
*Describe the Issue*

Resign the open view of a department/team view to support the new Figma design

**Link to Figma**

https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=7769-7639&t=lATfj2xH4or01kbE-1

**Existing Design**

Image

**New Design**

Image

Image

### PR DESCRIPTION
**Pull request by abhimanyurajeesh**
## Required Backend

- https://github.com/ohcnetwork/care/pull/2832

## Proposed Changes

- Fixes #10375

### Current Design
image

### Requested Design
image

### Changed Design
image

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Expanded localization with additional translations for department/team and organization management interfaces.
  - Introduced a search functionality to filter user listings by name for improved navigation.
  - Enhanced internationalization of the organization creation interface with localized strings for buttons, titles, and messages.
  - Improved layout organization for user information display in the user listing component.

- **Bug Fixes**
  - Adjusted button styling in the Add User Sheet for better visual alignment.

### CODE REVIEW

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx [hunk 1]
```diff
@@ -29,142 +30,176 @@ interface Props {
...
+                            <span className="text-sm text-gray-500 mr-2 break-words">
                               {userRole.user.username}
                             </span>
-                            <UserStatusIndicator user={userRole.user} />
-                          </span>
+                          </div>
+                          <div className="mt-4 grid grid-cols-2 gap-2 text-sm">
+                            <div>
+                              <div className="text-gray-500">{t("role")}</div>
+                              <div className="font-medium truncate">
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx:146]: I think we shouldn't truncate the fields , we can render it horizontally (more preferred personally ) or use the remaining white space 🤔
Screenshot 2025-02-13 at 3 19 36 AM

cc: @rithviknishad @Jacobjeevan

**Review by abhimanyurajeesh — COMMENTED** [review]
need to update with the latest

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx (hunk 1 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx:146]: @AdityaJ2305 that’s a great suggestion! Let’s keep the truncate but utilize the white space by moving the role to the left just for the mobile view, so that we maintain the new design for desktop.

cc: @rithviknishad @Jacobjeevan

Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx:146]: ### Mobile View
image

### Desktop View
image


Better?

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx [hunk 2]
```diff
@@ -35,39 +34,55 @@ export default function FacilityOrganizationUsers({ id, facilityId }: Props) {
...
+  const filteredUsers = users?.results?.filter((userRole) => {
+    if (!searchQuery) return true;
+
+    const searchLower = searchQuery.toLowerCase();
+    const fullName =
+      `${userRole.user.first_name} ${userRole.user.last_name}`.toLowerCase();
+    const username = userRole.user.username.toLowerCase();
+
+    return fullName.includes(searchLower) || username.includes(searchLower);
+  });
```
[the remark this answers is not in the document]
Comment (Jacobjeevan) [reply src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx]: Coderabbit is right - why are we doing client side filtering here?

Besides, it wouldn't work since you are doing the filtering on the results BE sends (page 1 since there's a limit).

You would need to add a search filter on BE if you want a fuzzy search for username or full name.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx]: @Jacobjeevan Got it. I'll remove the client-side filtering and wait for backend support for search. Should I temporarily disable the search feature in the meantime?

**Comment by abhimanyurajeesh** [comment]
> **Actionable comments posted: 0**
> 🧹 Nitpick comments (1)
> 
> > src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx (1)> `151-153`: **Consider alternative layout for truncated fields.**
> > > Based on the previous discussion, the truncation of role and phone number fields might not be the best approach. Consider:
> > > 
> > > 1. Utilizing the available white space horizontally
> > > 2. Adjusting the layout for mobile view to prevent truncation
> > > 
> > > ```diff
> > > -              <div className="font-medium truncate">
> > > +              <div className="font-medium break-words">
> > >                  {userRole.role.name}
> > >                </div>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```diff
> > > -              <div className="font-medium truncate">
> > > +              <div className="font-medium break-words">
> > >                  {userRole.user.phone_number}
> > >                </div>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also applies to: 159-161
> 
> 📜 Review details

its fix by changing the layout size.

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (Mahendar0701) [reply src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx]: I think @Rishith25 is working on username searching in Facility organization PR https://github.com/ohcnetwork/care_fe/pull/10146

CC : @Jacobjeevan @rithviknishad

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx [hunk 3]
```diff
@@ -29,19 +30,34 @@ interface Props {
 }
 
 export default function FacilityOrganizationUsers({ id, facilityId }: Props) {
-  const [qParams, setQueryParams] = useQueryParams<{
+  const [sheetParams, setSheetParams] = useQueryParams<{
     sheet: string;
     username: string;
   }>();
```
Comment (rithviknishad) [inline src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx]: let's keep this as a useState instead. this would conflict with the qparams managed by useFilters.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx (hunk 3 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx]: I have made the changes, please look into it. Thank you!

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx]: @Mahendar0701 I guess that can be ignored as this is an entire redesign.

**Review by rithviknishad — APPROVED** [review]

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx [hunk 4]
```diff
@@ -28,20 +28,40 @@ interface Props {
...
 export default function FacilityOrganizationUsers({ id, facilityId }: Props) {
-  const [qParams, setQueryParams] = useQueryParams<{
-    sheet: string;
-    username: string;
-  }>();
+  const [sheetState, setSheetState] = useState<SheetState>({
+    sheet: "",
+    username: "",
+  });
+  const { qParams, Pagination, resultsPerPage } = useFilters({
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx]: Since we are using useFilters anyways, let's switch to using updateQuery + qParams for search, instead of maintaining its own state.

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx [hunk 5]
```diff
@@ -28,20 +28,40 @@ interface Props {
...
+  sheet: string;
+  username: string;
+}
+
 export default function FacilityOrganizationUsers({ id, facilityId }: Props) {
-  const [qParams, setQueryParams] = useQueryParams<{
-    sheet: string;
-    username: string;
-  }>();
+  const [sheetState, setSheetState] = useState<SheetState>({
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx]: Hmm, we are not using the interface anywhere else, right? 🤔  Let's just define it inline.

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx [hunk 6]
```diff
@@ -50,121 +70,131 @@ export default function FacilityOrganizationUsers({ id, facilityId }: Props) {
...
-                          {userRole.user.phone_number}
-                        </div>
+                      <div className="mt-2 -mx-2 -mb-2 sm:-mx-4 sm:-mb-4 rounded-md py-4 px-4 bg-gray-50 flex justify-end">
+                        <EditFacilityUserRoleSheet
+                          facilityId={facilityId}
+                          organizationId={id}
+                          userRole={userRole}
+                          trigger={
+                            <Button variant="outline" size="sm">
+                              <span>{t("see_details")}</span>
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx:169]: Hmm, imo we should update this to redirect to user's profile page and add an edit button, but that can be done in a different issue.

**Review by Jacobjeevan — APPROVED** [review]
Minor things, LGTM otherwise.

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx (hunk 6 above)
Comment (AdityaJ2305) [reply src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx:169]: https://github.com/ohcnetwork/care_fe/issues/10651

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx (hunk 4 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx]: done

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx (hunk 5 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx]: yap you are right, done.

**Review by rithviknishad — APPROVED** [review]
