### PR TITLE
Modified the external results sample format

### LINKED ISSUE #6649: Modify the existing external results sample format as it is not working
**Describe the bug**

When attempting to upload the downloaded sample format to external results without making any changes, an error is thrown.

**To Reproduce**

1. Go to external results
2. Click on import and download the sample format then upload the same file without changing
3. See error

**Expected behavior**

the sample format upload should work properly for the external result

**Screenshots**

image

### PR DESCRIPTION
**Pull request by konavivekramakrishna**
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at ed80a98</samp>

The pull request adds a feature to download the external result template file locally and updates the template file with a sample row of data. It modifies the `src/Components/ExternalResult/ExternalResultUpload.tsx`, `public/config.json`, and `public/External-Results-Template.csv` files.

## Proposed Changes

- Fixes #6649 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at ed80a98</samp>

*  Add a sample row of data to the external result template file `External-Results-Template.csv` ([link](https://github.com/coronasafe/care_fe/pull/6694/files?diff=unified&w=0#diff-5d363dd8fce4695d0efab385bea90446289436770e46e686603f9937ece1555bL1-R2))
*  Modify the config file `config.json` to store a relative path to the template file instead of a Google Sheets link ([link](https://github.com/coronasafe/care_fe/pull/6694/files?diff=unified&w=0#diff-67644ab310d9ac1e98b6694f279c0dcd973ae26b1fd9ef1658281a2b91194adeL24-L23))
*  Create a custom download function `handleDownload` in the external result upload page `ExternalResultUpload.tsx` that uses the config value to download the template file locally ([link](https://github.com/coronasafe/care_fe/pull/6694/files?diff=unified&w=0#diff-40181ebadedb37c4a654bf245c2286ce3cbf9cb836d5262fdb373cb9c5e5032cR75-R81))
*  Replace the anchor element that triggers the download with one that calls the `handleDownload` function ([link](https://github.com/coronasafe/care_fe/pull/6694/files?diff=unified&w=0#diff-40181ebadedb37c4a654bf245c2286ce3cbf9cb836d5262fdb373cb9c5e5032cL114-R122))

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
@konavivekramakrishna 

You'll have to update the configs here too: https://github.com/coronasafe/care_deploy_configs

cc: @sainak

**Comment by vivramkrishna** [comment]
@rithviknishad 


https://github.com/coronasafe/care_deploy_configs/pull/19

**Comment by rithviknishad** [comment]
@sainak

File: src/Components/ExternalResult/ExternalResultUpload.tsx [hunk 1]
```diff
@@ -72,6 +72,13 @@ export default function ExternalResultUpload() {
     }
   };
 
+  const handleDownload = () => {
+    const link = document.createElement("a");
+    link.href = sample_format_external_result_import;
+    link.download = "sample_format";
+    link.click();
+    link.remove();
+  };
```
Comment (sainak) [inline src/Components/ExternalResult/ExternalResultUpload.tsx]: this could be converted to a utility function

File: public/config.json [hunk 2]
```diff
@@ -21,6 +21,6 @@
     "kasp_string": "KASP",
     "kasp_full_string": "Karunya Arogya Suraksha Padhathi",
     "sample_format_asset_import": "https://spreadsheets.google.com/feeds/download/spreadsheets/Export?key=11JaEhNHdyCHth4YQs_44YaRlP77Rrqe81VSEfg1glko&exportFormat=xlsx",
-    "sample_format_external_result_import": "https://docs.google.com/spreadsheets/d/17VfgryA6OYSYgtQZeXU9mp7kNvLySeEawvnLBO_1nuE/export?format=csv&id=17VfgryA6OYSYgtQZeXU9mp7kNvLySeEawvnLBO_1nuE",
+    "sample_format_external_result_import": "../../External-Results-Template.csv",
```
Comment (sainak) [inline public/config.json]:
```suggestion
    "sample_format_external_result_import": "/External-Results-Template.csv",
```

**Review by rithviknishad — APPROVED** [review]

File: src/Components/ExternalResult/ExternalResultUpload.tsx [hunk 3]
```diff
@@ -111,7 +112,13 @@ export default function ExternalResultUpload() {
...
                 <a
                   className="focus:ring-blue mx-auto mt-4 max-w-xs items-center rounded-md border border-primary-500 bg-white px-3 py-2 text-sm font-medium leading-4 text-primary-700 transition duration-150 ease-in-out hover:text-primary-500 hover:shadow focus:border-primary-300 focus:outline-none active:bg-gray-50 active:text-primary-800"
-                  href={sample_format_external_result_import}
+                  href="#"
+                  onClick={() =>
+                    downloadFile(
+                      sample_format_external_result_import,
+                      "sample_format"
+                    )
+                  }
```
Comment (khavinshankar) [inline src/Components/ExternalResult/ExternalResultUpload.tsx]: instead of custom download function, why not try download attribute, something like
```suggestion
                  href={sample_format_external_result_import}
                  target="_blank"
                  download
```

**Review by khavinshankar — COMMENTED** [review]
@konavivekramakrishna just some minor alterations

File: src/Components/ExternalResult/ExternalResultUpload.tsx (hunk 3 above)
Comment (vivramkrishna) [reply src/Components/ExternalResult/ExternalResultUpload.tsx]: image

@khavinshankar 
I believe that adding a download attribute to the link allows for direct downloading, but this method may not be preferable. On hover, we can disclose the path, though this approach is also not ideal.

Should I proceed with making these changes, or would you prefer that I leave it as it is?

`http://localhost:4000/External-Results-Template.csv`

Comment (rithviknishad) [reply src/Components/ExternalResult/ExternalResultUpload.tsx]: Is disclosing the path an issue/concern?

Comment (rithviknishad) [reply src/Components/ExternalResult/ExternalResultUpload.tsx]: Why is it not ideal? The lesser the javascript, the better (if it does the same thing and has no compromises).

We are practically doing the same thing with the `downloadFile` utility too anyways right?

image

**Review by khavinshankar — APPROVED** [review]
