### PR TITLE
Fix: Improve Questionnaire Type Validation for Time and Boolean Fields

### LINKED ISSUE #11480: Questionnaire Type validation need to be improved
**Describe the bug**

Image

- [ ] When we select a type : "Time" , it's showing a text field, which is not valid

Expected behavior: Show the time component

- [ ] For the type: "Boolean", its shown as true or false, none of the users are not familiar with the terms in forms

Expected behavior: Change the true or false to Yes or no

Similarly, Check all the types are properly validating and show proper options in the questionnaire, incase we missed to mention in this issue

**To Reproduce**

1. Login as a super admin
2. Click on admin dashboard
3. create a new questionnaire and try to submit questionnaire of each type in the patient encounter post creation

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by siva222003**
## Proposed Changes

- Fixes #11480 
- Updated Time type to render a proper time input instead of a text field.
- Updated Boolean type to display Yes/No instead of True/False for better user clarity.

[Screencast from 2025-03-25 15-34-05.webm](https://github.com/user-attachments/assets/ebb5e34a-6301-4ce3-8ca3-057ea71016d3)

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
	- Enhanced localization: Boolean questions now display language-specific “Yes” and “No” labels.
	- Expanded questionnaire options: Introduced a new time-based input field for capturing answers formatted as "HH:MM".
	- Added support for time-based questions in the questionnaire input component.
	- New `TimeQuestion` component for handling time input in questionnaires.
	- Improved formatting for boolean and time values in the responses list.

### CODE REVIEW

**Comment by siva222003** [comment]
@rithviknishad @Jacobjeevan Please review this PR and let me know if any changes are required.

File: src/components/Questionnaire/QuestionTypes/BooleanQuestion.tsx [hunk 1]
```diff
@@ -1,3 +1,5 @@
+import { t } from "i18next";
```
Comment (AdityaJ2305) [inline src/components/Questionnaire/QuestionTypes/BooleanQuestion.tsx]: use `useTranslation`

ref: https://github.com/ohcnetwork/care_fe/issues/11206

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Comment by nihal467** [comment]
image

- change the values of boolean in the overview page of encounter as well
- show time in HH:MM format only remove the SS as we are not recording seconds in the questionnaire

**Comment by siva222003** [comment]
@nihal467 The backend validation throws an error if I change the format of `TimeQuestion` or `BooleanQuestion`, so I left it as is. Can we modify the backend validation?

**Comment by Jacobjeevan** [comment]
> @nihal467 The backend validation throws an error if I change the format of `TimeQuestion` or `BooleanQuestion`, so I left it as is. Can we modify the backend validation?

@siva222003  You don't need to change either of those, the responses are rendered based on logic in QuestionnaireReponsesList.

You would only need to modify formatValue fn in that file.

**Comment by Jacobjeevan** [comment]
@siva222003 what's the update here?

**Comment by siva222003** [comment]
Hey @Jacobjeevan, sorry for the delay as I was working on another issue in the care_abdm repo, which took some time. Will complete this by EOD and push the new changes.

**Comment by siva222003** [comment]
image

@nihal467 @Jacobjeevan Please review the changes.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
lgtm
