### PR TITLE
Resolve Button Hover Color Problem in Requests Table Status Field

### LINKED ISSUE #10033: Fix Button Hover Color Issue on Requests Table Status Field
**Describe the bug**
When hovering over the status field button in the Requests table, the button color does not change as expected. This issue causes a lack of visual feedback for users, making it difficult to identify interactive elements.

**To Reproduce**

1. Go to 'Encounters'
2. Click on 'view details then click patient details'
3.Go to 'requests'

**Expected behavior**
The status field button in the Requests table should change color when hovered over, providing clear visual feedback to users to indicate that the button is interactive. The hover color should match the intended design or style guide for hover states.

**Screenshots**

https://github.com/user-attachments/assets/d7360144-c3b2-4664-893a-7fdeb6a28d08

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [131.0.6778.109]

**Additional context**

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes

- Fixes #10033 
- Change 1

Before

https://github.com/user-attachments/assets/ac792983-e474-4bee-9e00-f53ae4958418

After

https://github.com/user-attachments/assets/6977e0b2-e31d-49d6-b7db-8963bd7980dd

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style**
	- Enhanced resource request status badges with hover effects.
	- Added interactive hover states for different status colors (Pending, Approved, Rejected, Completed).
	- Introduced a new DEFAULT status for unrecognized statuses, ensuring consistent visual feedback.

### CODE REVIEW

File: src/components/Patient/PatientDetailsTab/ResourceRequests.tsx [hunk 1]
```diff
@@ -40,14 +40,20 @@ export const ResourceRequests = (props: PatientProps) => {
 
   const getStatusBadge = (status: ResourceRequest["status"]) => {
     const statusColors: Record<ResourceRequest["status"], string> = {
-      PENDING: "bg-yellow-100 text-yellow-800",
+      PENDING:
+        "bg-yellow-100 text-yellow-800 hover:bg-yellow-200 hover:text-yellow-900",
```
[the remark this answers is not in the document]
Comment (modamaan) [reply src/components/Patient/PatientDetailsTab/ResourceRequests.tsx:44]: changed

**Review by Jacobjeevan — APPROVED** [review]

File: src/components/Patient/PatientDetailsTab/ResourceRequests.tsx [hunk 2]
```diff
@@ -40,14 +40,22 @@ export const ResourceRequests = (props: PatientProps) => {
...
 
     return (
-      <Badge className={statusColors[status] || "bg-gray-100 text-gray-800"}>
+      <Badge
+        className={
+          statusColors[status] ||
+          "bg-gray-100 text-gray-800 hover:bg-gray-200 hover:text-gray-900"
+        }
+      >
         {status}
```
Comment (rithviknishad) [inline src/components/Patient/PatientDetailsTab/ResourceRequests.tsx:56]: let's also map this from translations instead

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Patient/PatientDetailsTab/ResourceRequests.tsx (hunk 2 above)
Comment (modamaan) [reply src/components/Patient/PatientDetailsTab/ResourceRequests.tsx:56]: default added into the map

**Review by rithviknishad — APPROVED** [review]
