### PR TITLE
hide the view button when facility id is not present

### LINKED ISSUE #11266: Error Page When Viewing Appointment details of a patient via Organization .
**Describe the bug**
When accessing the system via an organization, navigating to the Patients tab, selecting a patient, and then clicking on View Appointment for any of their appointments, an error page appears instead of displaying appointment details.

When accessing a patient through the Organization → Patients tab, there is no facility_id available in the URL or context.
Since the backend requires facility_id to fetch appointment details, this results in an error when trying to view an appointment details 

**To Reproduce**

1.Go to the Organization .
2.Click on the Patients tab.
3.Select any patient from the list.
4.Navigate to the Appointments section for that patient.
5.Click on View Appointment for any listed appointment.
6.Observe that an error page is displayed instead of the appointment details.

**Expected behavior**
The system should correctly display the appointment details instead of an error page.

**Screenshots**

https://github.com/user-attachments/assets/6a1f0f3a-bb02-4ab5-9c6a-64f671d8fb15

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Vikaspal8923**
## Proposed Changes

- Fixes #11266 
- checking facility id to show view button or not

facility id present:
image

facility id is not present:
image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [X] Request for Peer Reviews
- [X] Completion of QA in Mobile Devices
- [X] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved the Patient Details view by conditionally displaying the appointment details button and "actions" header based on the availability of valid facility information, enhancing the user interface's reliability.

### CODE REVIEW

File: src/components/Patient/PatientDetailsTab/Appointments.tsx [hunk 1]
```diff
@@ -127,14 +127,16 @@ export const Appointments = (props: PatientProps) => {
                   </TableCell>
                   <TableCell>{getStatusBadge(appointment.status)}</TableCell>
                   <TableCell className="text-right">
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientDetailsTab/Appointments.tsx]: Since there are no actions present, it wouldn't make sense to display the column anymore, so you will want to make the heading and the cell conditional.

**Review by Jacobjeevan — DISMISSED** [review]

**Comment by Vikaspal8923** [comment]
@Jacobjeevan   i have fixed the requested changes. let me know if something need to change in this

**Review by rithviknishad — APPROVED** [review]
