### PR TITLE
Solved File Management Exceptions

### LINKED ISSUE #7372: Handle File Management Exceptions in File Upload
`TypeError: Cannot read properties of undefined (reading 'name')`

Sentry Issue: [CARE-FE-3BJ](https://coronasafe-network.sentry.io/issues/5019932927/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'name')
  at onFileChange (../../src/Components/Patient/FileUpload.tsx:864:24)
...
(8 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by manasvi-gaur**
- Fixes #7372
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

File: src/Components/Patient/FileUpload.tsx [hunk 1]
```diff
@@ -905,11 +905,11 @@ export const FileUpload = (props: FileUploadProps) => {
...
 
   const onFileChange = (e: ChangeEvent<HTMLInputElement>): any => {
-    if (e.target.files == null) {
-      throw new Error("Error finding e.target.files");
+    if (e.target.files == null || e.target.files.length === 0) {
+      return;
     }
     const f = e.target.files[0];
-    const fileName = f.name;
+    const fileName = f ? f.name : Date.now().toString(); // use timestamp as filename for unnamed files
```
Comment (rithviknishad) [inline src/Components/Patient/FileUpload.tsx]: Why was this changed? `f` would never be evaluated to be falsey since we are doing an early exit in line 909, and hence the Date.now() part would never be used.

File: src/Components/Patient/FileUpload.tsx [hunk 2]
```diff
@@ -905,11 +905,11 @@ export const FileUpload = (props: FileUploadProps) => {
   }
 
   const onFileChange = (e: ChangeEvent<HTMLInputElement>): any => {
-    if (e.target.files == null) {
-      throw new Error("Error finding e.target.files");
+    if (e.target.files == null || e.target.files.length === 0) {
```
Comment (rithviknishad) [inline src/Components/Patient/FileUpload.tsx]:
```suggestion
    if (!e.target.files?.length) {
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by Ashesh3 — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
