### PR TITLE
Separate appointment types for public and normal bookings according to backend changes

### LINKED ISSUE #14154: Separate appointment types for public and normal bookings to align with backend updates
**Describe the bug**
As per the backend update in [BE PR #3302](https://github.com/ohcnetwork/care/pull/3302/files) the TokenBookingRead spec is separated for OTP-based bookings. Update the frontend accordingly by separating appointment types for public and normal bookings.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Proposed Changes
- Fix: #14154
- Reference BE PR : https://github.com/ohcnetwork/care/pull/3302/files
- In be the TokenBookingRead spec, it is separated for OTP, so in fe corresponding separation applied
- Separated Appointment type for public appointments and normal appointments

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.

## Summary by CodeRabbit

- Bug Fixes
  - Patient age now displays correctly when a date of death is present.
  - Patient tag display logic adjusted to rely on a defined tag list (may affect visibility of tags).

- Refactor
  - Standardized appointment data shape across patient, public scheduling, and appointment flows for consistency.

- Chores
  - Updated imports and handler signatures to align with the standardized appointment and patient types.

### CODE REVIEW

**Review by khavinshankar — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by bodhish — APPROVED** [review]
LGTM

File: src/types/scheduling/schedule.ts [hunk 1]
```diff
@@ -221,18 +221,25 @@ export type ScheduleResource =
...
 
-export type Appointment = {
+export type AppointmentBase = {
   id: string;
   token_slot: TokenSlot;
-  patient: PatientRead;
   booked_on: string;
   status: AppointmentStatus;
   note: string;
-  booked_by: UserReadMinimal | null; // This is null if the appointment was booked by the patient itself.
```
Comment (rithviknishad) [inline src/types/scheduling/schedule.ts:231]: why was this removed from base? 🤔

File: src/types/scheduling/schedule.ts [hunk 2]
```diff
@@ -221,18 +221,25 @@ export type ScheduleResource =
...
 } & ScheduleResource;
 
+export type Appointment = AppointmentBase & {
+  patient: PatientRead;
+  booked_by: UserReadMinimal | null;
+};
+
+export type PublicAppointment = AppointmentBase & {
+  patient: PublicPatientRead;
+};
```
Comment (rithviknishad) [inline src/types/scheduling/schedule.ts:241]: doesn't public appointment have `booked_by` attribute?

**Comment by tasnimshaji** [comment]
LGTM @nihal467

File: src/types/scheduling/schedule.ts [hunk 3]
```diff
@@ -221,18 +221,25 @@ export type ScheduleResource =
...
   token_slot: TokenSlot;
-  patient: PatientRead;
   booked_on: string;
   status: AppointmentStatus;
   note: string;
-  booked_by: UserReadMinimal | null; // This is null if the appointment was booked by the patient itself.
   facility: FacilityBareMinimum;
   token: TokenRead | null;
+  booked_by: UserReadMinimal | null;
 } & ScheduleResource;
```
Comment (rithviknishad) [inline src/types/scheduling/schedule.ts:234]: why was the comment removed? 🤔

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]
