### PR TITLE
fix: Adjust containers flexibility and inconsistency

### LINKED ISSUE #10528: Inconsistency in containers during schedule creation for a doctor
**Describe the bug**
Containers alignment is not proper in creating a schedule for a doctor.

**To Reproduce**

1. Go to [https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/users/doctordev/availability?tab=schedule&sheet=create_template](url)
2. Try to fill wrong time range
3. See error

**Expected behavior**
We should fix the container or keep spacing for errors. Containers should not be moving too up or too down.

**Screenshots**

https://github.com/user-attachments/assets/60b96800-51c9-472c-b542-104b744be899

**Desktop (please complete the following information):**

- OS: [MacOS]
- Browser [Chrome]

### PR DESCRIPTION
**Pull request by Tanuj1718**
## Proposed Changes

- Fixes #10528

Before Update:

https://github.com/user-attachments/assets/2a15cd87-fdee-477c-a344-cf7219c14529

After Update:

https://github.com/user-attachments/assets/fb1b0446-3abd-40fe-afc5-1fa1c0b209d3

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style**
	- Redesigned scheduling forms for improved alignment and responsive layouts.
	- Updated field arrangements with flexible spacing for a cleaner, more intuitive interface.
	- Removed unnecessary visual elements to simplify the overall presentation.

### CODE REVIEW

File: src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx [hunk 1]
```diff
@@ -431,50 +431,54 @@ export default function CreateScheduleTemplateSheet({
...
-                                <Input type="time" {...field} />
-                              </FormControl>
-                              <FormMessage />
-                            </FormItem>
-                          )}
-                        />
-
-                        <ArrowRightIcon className="size-4 mt-5" />
+                      <div className="flex items-center gap-0 sm:gap-4 col-span-2 md:col-span-1 h-28">
+                        <div className="flex items-center justify-center mt-16">
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx]: Why add another div with flex wrapping the same contents 🤔  You should be able to address the issue without this.

File: src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx [hunk 2]
```diff
@@ -431,50 +431,54 @@ export default function CreateScheduleTemplateSheet({
...
-                            </FormItem>
-                          )}
-                        />
+                          <ArrowRightIcon className="size-4 mb-20" />
+
+                          <FormField
+                            control={form.control}
+                            name={`availabilities.${index}.end_time`}
+                            render={({ field }) => (
+                              <FormItem className="flex-1 mb-12 h-28">
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx]: See if you can solve this without specifying a particular height for the FormItem components.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx (hunk 2 above)
Comment (Tanuj1718) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx]: I think we have to set the height in both FormItems because we are showing message in one container so it will get adjusted automatically if we will not set the height. Is there any issue with this approach?🤔

Comment (Jacobjeevan) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx]: Yes, we don't want to randomly set height like that 😅 

https://css-tricks.com/snippets/css/a-guide-to-flexbox/

You should be able to solve this without setting height.

Comment (Tanuj1718) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx]: Ok sure. I will do it with different approach.👍

**Comment by rithviknishad** [comment]
mark it for ready for review once changes have been made

**Comment by nihal467** [comment]
@Tanuj1718 what is the status on the PR

**Comment by Tanuj1718** [comment]
> @Tanuj1718 what is the status on the PR

Yeah it is ready. I have asked @Jacobjeevan for some UI changes, waiting for his confirmation.

**Comment by Jacobjeevan** [comment]
The input expands with error:

image


This also doesn't work for mobile screens:

image

**Comment by Tanuj1718** [comment]
@Jacobjeevan Can I solve it this way?(for both mobile and dekstop)
Screenshot 2025-02-19 at 12 59 39 PM

File: src/components/Patient/PatientRegistration.tsx [hunk 3]
```diff
@@ -42,11 +42,7 @@ import DuplicatePatientDialog from "@/components/Facility/DuplicatePatientDialog
 
 import useAppHistory from "@/hooks/useAppHistory";
 
-import {
-  BLOOD_GROUP_CHOICES, // DOMESTIC_HEALTHCARE_SUPPORT_CHOICES,
-  GENDER_TYPES, // OCCUPATION_TYPES,
-  //RATION_CARD_CATEGORY, // SOCIOECONOMIC_STATUS_CHOICES ,
-} from "@/common/constants";
+import { BLOOD_GROUP_CHOICES, GENDER_TYPES } from "@/common/constants";
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientRegistration.tsx]: Try not to include unnecessary changes please. But since it's a minor thing, let's keep it.

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
image

@Tanuj1718 the bug still persist

**Comment by Tanuj1718** [comment]
> image
> 
> @Tanuj1718 the bug still persist

Got it. I have updated only Create Template , not Edit Template. Will update it soon.
EDIT: Updated the file.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
