### PR TITLE
Fix multi-select dropdown for facilities in user creation module

### LINKED ISSUE #7762: Text is not being reenforced for the dropdown when linking facilities while adding the user.
Typed Text gets wiped out/not support to the dropdown shown while linking the multiple facilities to one user when creating the user in the user Module. 
There's a need for enablement to select multiple searched result for relevant keyword Typed. Alongst all facilities should available to select when dropdown arrow is clicked
Screen recording is attached below for ref.

Uploading User_bug.mp4…

### PR DESCRIPTION
**Pull request by Dev-Harwani**
- Fixes #7762 
- will be able to add multiple facilities without text getting wiped out.
- all the available facilities will be shown

https://github.com/coronasafe/care_fe/assets/131504127/fc803244-f576-466b-bf07-e2bc5ee92730

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

File: src/Components/Form/AutoCompleteAsync.tsx [hunk 1]
```diff
@@ -102,7 +102,6 @@ const AutoCompleteAsync = (props: Props) => {
               onChange={({ target }) => setQuery(target.value)}
               onFocus={props.onFocus}
               onBlur={() => {
-                setQuery("");
```
Comment (rithviknishad) [inline src/Components/Form/AutoCompleteAsync.tsx:105]: This change alone should be enough right? What's the reason for having a state to make the number of options to be shown?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Form/AutoCompleteAsync.tsx (hunk 1 above)
Comment (Dev-Harwani) [reply src/Components/Form/AutoCompleteAsync.tsx:105]: Using state variable allows to dynamically update the number of options. Earlier no. of options were hardcoded that is why only 10 options were showing but now all available facilities will be shown.
I think removing setQuery should be enough.

Comment (rithviknishad) [reply src/Components/Form/AutoCompleteAsync.tsx:105]: Yup, removing setQuery should be enough. 

The `showNOptions` is deconstructed from the props passed to the components. Let's not have a state to set the default value for it. 

Instead undefined could be treated as showing all available options instead of defaulting to 10.

File: src/Components/Form/AutoCompleteAsync.tsx [hunk 2]
```diff
@@ -63,7 +63,12 @@ const AutoCompleteAsync = (props: Props) => {
       debounce(async (query: string) => {
         setLoading(true);
         const data = await fetchData(query);
```
Comment (rithviknishad) [inline src/Components/Form/AutoCompleteAsync.tsx]:
```suggestion
        const data = (await fetchData(query)) || [];
```

File: src/Components/Form/AutoCompleteAsync.tsx [hunk 3]
```diff
@@ -63,7 +63,12 @@ const AutoCompleteAsync = (props: Props) => {
...
-        setData(data?.slice(0, showNOptions) || []);
+
+        if (showNOptions !== undefined) {
+          setData(data?.slice(0, showNOptions) || []);
+        } else {
+          setData(data || []);
+        }
```
Comment (rithviknishad) [inline src/Components/Form/AutoCompleteAsync.tsx]:
```suggestion
        if (showNOptions !== undefined) {
          setData(data.slice(0, showNOptions));
        } else {
          setData(data);
        }
```

**Review by rithviknishad — APPROVED** [review]

File: src/Components/Form/AutoCompleteAsync.tsx (hunk 1 above)
Comment (Dev-Harwani) [reply src/Components/Form/AutoCompleteAsync.tsx:105]: Hi @rithviknishad. Now if showNOptions is undefined then all the facilities will be shown.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
