### PR TITLE
Fix :  Hover color for active button

### LINKED ISSUE #10457: Black Color Text in Questionnaires is Not Readable
**Describe the bug**
The Text in the Questionnaires section is displaying in black color, which makes it unreadable

**To Reproduce**

1. Login with careadmin

Image

2. Click on 'Questionnaires' 
3. Click on 'active' in status tab.
4. The text appears in black color and is not readable

**Expected behavior**
The text should be displayed in a color that provides good color ensuring it is easily readable.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #10457
- bg-green-100 text-green-800 -> bg-green-200 text-green-900 hover:bg-green-300
- Changed in index.tsx and show.tsx
When we click status button, the issue is also present in that page. 

https://github.com/user-attachments/assets/ae6c9e53-d3b4-4a08-adb2-50fed2539346

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style**
	- Enhanced the visual appearance of questionnaire status badges with updated color schemes and a new hover effect for a more interactive experience.

### CODE REVIEW

File: src/components/Questionnaire/index.tsx [hunk 1]
```diff
@@ -74,7 +74,7 @@ export function QuestionnaireList() {
                   <Badge
                     className={
                       questionnaire.status === "active"
-                        ? "bg-green-100 text-green-800"
+                        ? "bg-green-200 text-green-900 hover:bg-green-300"
```
Comment (rithviknishad) [inline src/components/Questionnaire/index.tsx]:
```suggestion
                        ? "bg-green-100 text-green-800 hover:bg-green-200"
```

File: src/components/Questionnaire/show.tsx [hunk 2]
```diff
@@ -254,7 +254,7 @@ export function QuestionnaireShow({ id }: QuestionnaireShowProps) {
                       <Badge
                         className={
                           questionnaire.status === "active"
-                            ? "bg-green-100 text-green-800"
+                            ? "bg-green-200 text-green-900 hover:bg-green-300"
```
Comment (rithviknishad) [inline src/components/Questionnaire/show.tsx]:
```suggestion
                            ? "bg-green-100 text-green-800 hover:bg-green-200"
```

**Review by rithviknishad — APPROVED** [review]
