### PR TITLE
Fix print all prescriptions

### LINKED ISSUE #15442: Print All Prescriptions not working
**Describe the bug**
Despite having multiple prescriptions and active medications print all prescription page showing no medication to print 

**Screenshots**

https://github.com/user-attachments/assets/8b8311c0-8aab-4dec-993d-52deccf128dc

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by yash-learner**
## Proposed Changes

Fixes https://github.com/ohcnetwork/care_fe/issues/15442
- Get only the prescription side code from https://github.com/ohcnetwork/care_fe/pull/15548
- https://github.com/ohcnetwork/care_fe/pull/15548 is blocked because of some redesign on dispense side screens just fixing the print all on medicines tab 

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **New Features**
  * Print view now supports printing multiple prescriptions from an encounter, with a multi-prescription preview, per-prescription dividers and a count banner.
  * New print route reachable via facility, patient, and encounter identifiers.
  * Improved loading, empty-state and auto-print behavior when no prescriptions or medications are present.

* **Documentation**
  * Added localization strings for "Encounter not found" and prescription count display.

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]
Wait for @nihal467 to approve.

Also cc @rithviknishad

File: src/components/Prescription/PrescriptionPreview.tsx [hunk 1]
```diff
@@ -117,28 +121,80 @@ const DetailRow = ({ label, value, isStrong = false }: DetailRowProps) => {
...
+    queries: prescriptionIds.map((prescriptionId) => ({
+      queryKey: ["prescription", patientId, prescriptionId, facilityId],
+      queryFn: query(prescriptionApi.get, {
+        pathParams: {
+          patientId,
+          id: prescriptionId,
+        },
+        queryParams: { facility: facilityId },
+      }),
+      enabled: !!patientId && !!prescriptionId && !!facilityId,
```
Comment (rithviknishad) [inline src/components/Prescription/PrescriptionPreview.tsx]:
```suggestion
```

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by nihal467 — APPROVED** [review]
