### PR TITLE
Fixed the misalignments in the mobile view of /encounter/encounterId/updates page

### LINKED ISSUE #9763: The design of encounter/:encounterId/updates seems uneven in mobile view
**Describe the issue**
The design seems uneven and doesn't look good to the viewer.

**To Reproduce**

1. Go to respective page [link](https://care.ohc.network/facility/03560a09-121e-451a-a73a-64240cbfb1ae/encounter/bc110852-54bc-4de5-8873-6add1403d771/updates)
2. Switch to mobile view 
3. See the misalignments

**Expected behavior**
A better design for the viewer

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by Utkarsh-Anandani**
## Proposed Changes

- Fixes #9763 

**Before**
image

**After**
image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style**
	- Updated layout and styling of the patient information card.
	- Adjusted padding and spacing of badge containers.
	- Modified grid and container alignments for improved visual presentation.
	- Updated class names for improved layout dynamics.
	- Implemented responsive design for plot display based on screen size.
	- Introduced horizontal scrolling for the tabs list component.

- **New Features**
	- Added new properties to the PageTitle component for enhanced breadcrumb functionality.
	- Integrated responsive column display for plots based on screen size.

### CODE REVIEW

**Comment by bodhish** [comment]
Why not move the page heading also to the left 
image

**Comment by rithviknishad** [comment]
update the pr's title to something meaningful btw

**Comment by Utkarsh-Anandani** [comment]
> Why not move the page heading also to the left image

Did the required changes

**Comment by vinutv** [comment]
Screenshot 2025-01-09 at 12 28 25 AM

The alignment and spacing on the profile card need to be fixed. Consider reducing the avatar size for smaller screens.
Screenshot 2025-01-09 at 12 25 40 AM

**Comment by vinutv** [comment]
Screenshot 2025-01-09 at 12 26 12 AM

Plots tab cards are broken. We can switch to a single-column layout for smaller screens.

**Comment by Utkarsh-Anandani** [comment]
> Screenshot 2025-01-09 at 12 26 12 AM
> Plots tab cards are broken. We can switch to a single-column layout for smaller screens.

Already being worked upon in a different [PR](https://github.com/ohcnetwork/care_fe/pull/9815)



> Screenshot 2025-01-09 at 12 28 25 AM
> The alignment and spacing on the profile card need to be fixed. Consider reducing the avatar size for smaller screens. Screenshot 2025-01-09 at 12 25 40 AM

Would definitely consider this..

**Comment by rithviknishad** [comment]
@Utkarsh-Anandani combine the plots changes here itself and close the other one.

**Review by vinutv — COMMENTED** [review]
Screenshot 2025-01-09 at 12 28 25 AM

The alignment and spacing on the profile card need to be fixed. Consider reducing the avatar size for smaller screens.

Screenshot 2025-01-09 at 12 25 40 AM

**Comment by Jacobjeevan** [comment]
image

You can adjust this and the next popup's (class history) align property (Popovercontent).

**Comment by Utkarsh-Anandani** [comment]
@Jacobjeevan 
The changes are only required for the alignment?
- A little margin at left for 1st popup
- Can change alignment to "start" or "end", but it doesn't looks good so no change for now 

Does this works??

image
image

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan The changes are only required for the alignment?
> 
>     * A little margin at left for 1st popup
> 
>     * Can change alignment to "start" or "end", but it doesn't looks good so no change for now
> 
> 
> Does this works??
> 
> image image

🤔 

Start and end should work, no?

https://github.com/user-attachments/assets/80130811-0bb7-4d30-89eb-ab7f06fc69b3

**Comment by Utkarsh-Anandani** [comment]
@rithviknishad @Jacobjeevan

File: src/components/Patient/PatientInfoCard.tsx [hunk 1]
```diff
@@ -188,7 +192,10 @@ export default function PatientInfoCard(props: PatientInfoCardProps) {
                         </Badge>
                       </div>
                     </PopoverTrigger>
-                    <PopoverContent className="w-auto p-2">
+                    <PopoverContent
+                      align={isSmallDevice ? "start" : "center"}
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientInfoCard.tsx]: isSmallDevice check isn't necessary here or below 🤔  Using start and end are fine.

File: src/pages/Encounters/tabs/EncounterPlotsTab.tsx [hunk 2]
```diff
@@ -43,21 +47,23 @@ export const EncounterPlotsTab = (props: EncounterTabProps) => {
...
+        </div>
 
         {data.map((tab) => (
           <TabsContent key={tab.id} value={tab.id}>
             <ObservationVisualizer
               patientId={props.patient.id}
               encounterId={props.encounter.id}
               codeGroups={tab.groups}
-              gridCols={2}
+              gridCols={plotColumns}
```
Comment (Jacobjeevan) [inline src/pages/Encounters/tabs/EncounterPlotsTab.tsx:66]: Check iPad.

image

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Patient/PatientInfoCard.tsx (hunk 1 above)
Comment (Utkarsh-Anandani) [reply src/components/Patient/PatientInfoCard.tsx]: In my opinion, for large and medium devices align center looks better. Still, I'd do the changes as per your request.

Comment (Jacobjeevan) [reply src/components/Patient/PatientInfoCard.tsx]: > In my opinion, for large and medium devices align center looks better. Still, I'd do the changes as per your request.

😅  For future: you don't need to do exactly as we request (unless it's an error or something) - use your judgement and justify/explain your reasoning.

**Review by Jacobjeevan — APPROVED** [review]

File: src/components/Patient/PatientInfoCard.tsx (hunk 1 above)
Comment (Utkarsh-Anandani) [reply src/components/Patient/PatientInfoCard.tsx]: Yeah Sure 😊

**Comment by nihal467** [comment]
image
image

The alignments in your PR are currently broken in desktop view compared to the develop branch.

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
