### PR TITLE
fix: Disable comment button based in ResourceCommentSection

### LINKED ISSUE #12425: Disable “Post Your Comment” button until input is non-empty
**Describe the bug**
The “Post Your Comment” button is enabled even when the textarea is empty

**To Reproduce**

1. Go to 'Resource'
2. Scroll down to 'comments section'
3. See error

**Expected behavior**
The “Post Your Comment” button should remain disabled until the textarea contains non-empty

**Screenshots**

https://github.com/user-attachments/assets/c6b02b6e-8a3f-4ad5-95c6-76966d5f6793

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Denyme24**
## Proposed Changes

https://github.com/user-attachments/assets/201cd800-18db-40d9-a010-ce128f0de8b8

- Fixes #12425 
- Added disabled state validation for comment submission button

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
  - The "Post Your Comment" button is now disabled when the comment input is empty or contains only whitespace, preventing accidental empty comment submissions.

### CODE REVIEW

**Comment by Tanuj1718** [comment]
@Denyme24 you have checked demo video in merge checklist, but I not able to see any demo video of your changes🤔

**Comment by Denyme24** [comment]
> @Denyme24 you have checked demo video in merge checklist, but I not able to see any demo video of your changes🤔

OOPS !! i forgot to attach , anyways i have attached it now , you can check it .

File: src/components/Resource/ResourceCommentSection.tsx [hunk 1]
```diff
@@ -73,7 +73,11 @@ const CommentSection = ({ id }: { id: string }) => {
         />
 
         <div className="flex w-full justify-end mt-2">
-          <Button variant="primary" onClick={submitComment}>
+          <Button
+            variant="primary"
+            onClick={submitComment}
+            disabled={!/\S+/.test(commentBox)}
```
Comment (AdityaJ2305) [inline src/components/Resource/ResourceCommentSection.tsx]: Should we go with the one below? Both options work, but this one’s slightly more readable.

Note: Please don’t commit it yet — let’s wait for the maintainer’s input first.
```suggestion
            disabled={commentBox.trim().length == 0}
```

Comment (Denyme24) [reply src/components/Resource/ResourceCommentSection.tsx]: Alright.

**Comment by Denyme24** [comment]
Hey @rithviknishad , could you please review this PR once !

File: src/components/Resource/ResourceCommentSection.tsx (hunk 1 above)
Comment (rithviknishad) [reply src/components/Resource/ResourceCommentSection.tsx]: let's do this

**Comment by Denyme24** [comment]
Hey @rithviknishad, i have made the suggested changes in the PR .

**Review by NikhilA8606 — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
