### PR TITLE
Fix: Duplicate network requests in Patient Details page

### LINKED ISSUE #9269: Duplicate network requests on patient details page
Patient home page:
duplicate requests to policy api
Image

Encounters page:
duplicate requests for consultations list api
patient details api is called again
Image

Notes page:
doctor notes tab initial load calls the notes api twice
Image

### PR DESCRIPTION
**Pull request by Mahendar0701**
## Proposed Changes

- Fixes #9269 
- Removed Duplicate calls of policy
image

- Removed Duplicate calls of consultation details
image

- Removed Duplicate calls of notes
image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Introduced a new `refetch` prop across several components to enable data refetching.
  - Enhanced user experience for volunteer selection with a new `UserAutocomplete` component.

- **Bug Fixes**
  - Improved error handling for unauthorized actions in the `ImmunisationRecords` component.

- **Documentation**
  - Updated import paths for better organization and clarity across various components.

- **Refactor**
  - Streamlined data fetching logic and component structure in `PatientNotesList`, `EncounterHistory`, and `Notes` components.

### CODE REVIEW

File: src/components/Patient/PatientHome.tsx [hunk 1]
```diff
@@ -65,6 +65,12 @@ export const PatientHome = (props: {
     AssignedToObjectModel | undefined
   >(patientData.assigned_to_object);
 
+  const [isPatientHomeMounted, setIsPatientHomeMounted] = useState(false);
+
+  useEffect(() => {
+    setIsPatientHomeMounted(true);
+  }, []);
```
Comment (rithviknishad) [inline src/components/Patient/PatientHome.tsx]: what does this do?

Comment (Mahendar0701) [reply src/components/Patient/PatientHome.tsx]: It ensures PatientHome to render first. Because before rendering of patientHome , demography tab is rendering. Its hapening for only demography tab.

File: src/components/Facility/PatientNotesList.tsx [hunk 2]
```diff
@@ -57,19 +57,15 @@ const PatientNotesList = (props: PatientNotesProps) => {
...
     fetchNotes();
   }, [thread]);
 
   useEffect(() => {
-    setReload(true);
-  }, []);
+    if (reload) {
+      fetchNotes();
+    }
+  }, [reload]);
```
[the remark this answers is not in the document]
Comment (Mahendar0701) [reply src/components/Facility/PatientNotesList.tsx]: Done

File: src/components/Patient/PatientHome.tsx (hunk 1 above)
Comment (Mahendar0701) [reply src/components/Patient/PatientHome.tsx]: I removed it, and ensured policy api to be called after getpatient api completes

**Comment by Mahendar0701** [comment]
@coderabbitai full review

File: src/components/Patient/PatientDetailsTab/index.tsx [hunk 3]
```diff
@@ -11,6 +11,7 @@ export interface PatientProps {
   facilityId: string;
   id: string;
   patientData: PatientModel;
+  refetch: () => void;
```
[the remark this answers is not in the document]
Comment (Mahendar0701) [reply src/components/Patient/PatientDetailsTab/index.tsx:13]: Only `EncounterHistory ` is using refetch prop. Others are not using it

File: src/components/Patient/PatientDetailsTab/EncounterHistory.tsx [hunk 4]
```diff
@@ -4,50 +4,25 @@ import { useTranslation } from "react-i18next";
...
-      id,
-    },
-    onResponse: ({ res, data }) => {
-      if (res?.ok && data) {
-        setPatientData(data);
-      }
-      triggerGoal("Patient Profile Viewed", {
-        facilityId: facilityId,
-        userId: authUser.id,
-      });
```
Comment (rithviknishad) [inline src/components/Patient/PatientDetailsTab/EncounterHistory.tsx]: this is needed. i don't see it added back anywhere else

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Patient/PatientDetailsTab/Notes.tsx [hunk 5]
```diff
@@ -22,15 +22,11 @@ import routes from "@/Utils/request/api";
 import request from "@/Utils/request/request";
 import { classNames, keysOf } from "@/Utils/utils";
 
+import { PatientProps } from ".";
 import * as Notification from "../../../Utils/Notifications";
```
Comment (rithviknishad) [inline src/components/Patient/PatientDetailsTab/Notes.tsx]: switch to using absolute imports instead

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Patient/PatientDetailsTab/EncounterHistory.tsx (hunk 4 above)
Comment (Mahendar0701) [reply src/components/Patient/PatientDetailsTab/EncounterHistory.tsx]: It is already present in PatientHome.tsx from line 86-90

**Comment by Mahendar0701** [comment]
@rithviknishad `triggerGoal` is already implemented in `PatientHome.tsx` so i removed it from `EncounterHistory.tsx` which will be redundant if used again. 

Any further changes required?

**Comment by Mahendar0701** [comment]
Hey @rithviknishad can you please update the review

File: src/components/Patient/PatientDetailsTab/Demography.tsx [hunk 6]
```diff
@@ -61,11 +61,19 @@ export const Demography = (props: PatientProps) => {
...
+      prefetch: false, // Don't prefetch by default
     },
-  });
+  );
+
+  useEffect(() => {
+    if (patientData.id) {
+      refetch();
+    }
+  }, [patientData.id, refetch]);
```
Comment (rithviknishad) [inline src/components/Patient/PatientDetailsTab/Demography.tsx]: why disable prefetch? wouldn't `patientData.id` always be present?

File: src/components/Patient/PatientDetailsTab/Notes.tsx [hunk 7]
```diff
@@ -18,19 +18,15 @@ import { useMessageListener } from "@/hooks/useMessageListener";
 import { PATIENT_NOTES_THREADS } from "@/common/constants";
 
 import { NonReadOnlyUsers } from "@/Utils/AuthorizeFor";
+import * as Notification from "@/Utils/Notifications";
 import routes from "@/Utils/request/api";
 import request from "@/Utils/request/request";
 import { classNames, keysOf } from "@/Utils/utils";
 
-import * as Notification from "../../../Utils/Notifications";
+import { PatientProps } from ".";
```
Comment (rithviknishad) [inline src/components/Patient/PatientDetailsTab/Notes.tsx]: switch to absolute imports.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Patient/PatientDetailsTab/Demography.tsx (hunk 6 above)
Comment (Mahendar0701) [reply src/components/Patient/PatientDetailsTab/Demography.tsx]: In `PatientHome.tsx`, the getPatient API fetches `patientData` and passes it to `Demography` as prop. 

Earlier, I disabled `prefetch`  for the insuranceDetails API in Demography to avoid calls with an undefined `patientData.id`. 

Now, by setting prefetch to !!patientData.id in the query itself, the API triggers only when the `patientData.id` is available,This prevents unnecessary call.

This change working correctly. Please confirm if this correct.

File: src/components/Patient/PatientDetailsTab/Notes.tsx (hunk 7 above)
Comment (Mahendar0701) [reply src/components/Patient/PatientDetailsTab/Notes.tsx]: Done

File: src/components/Patient/PatientDetailsTab/Demography.tsx (hunk 6 above)
Comment (rithviknishad) [reply src/components/Patient/PatientDetailsTab/Demography.tsx]: you can get the patient id using the `useSlug` or by passing it as a prop right? We can prevent request waterfalls this way. There's no reason for fetching insurance details to wait until we get the patient object right?

Comment (Mahendar0701) [reply src/components/Patient/PatientDetailsTab/Demography.tsx]: Ok i will check it .

Comment (Mahendar0701) [reply src/components/Patient/PatientDetailsTab/Demography.tsx]: > you can get the patient id using the `useSlug` or by passing it as a prop right? We can prevent request waterfalls this way. There's no reason for fetching insurance details to wait until we get the patient object right?

Yes we are passing patient id as prop from PatientHome.tsx. This patient id is fetched from getPatient api request. 

But the tabs are rendered before the fetching is completed and props are passed as undefined to demography tab. 

So to prevent this i have made fetching insurance details to wait until we get the property fetched patient object.

Instead of this should i write a conditional statement in patienthome.tsx so that tabs are not rendered until patientdata is fetched completely.

```javascript
{Tab && patientData?.id && (
              <Tab
                facilityId={facilityId || ""}
                id={patientData.id || ""}
                patientData={patientData}
                refetch={refetch}
              />
   )}

Comment (rithviknishad) [reply src/components/Patient/PatientDetailsTab/Demography.tsx]: We can get the patient ID from the URL right?

Comment (Mahendar0701) [reply src/components/Patient/PatientDetailsTab/Demography.tsx]: Yes

**Comment by Mahendar0701** [comment]
Hi @rithviknishad with the latest changes in useQuery.ts , the issues related to demograpgy tab seems to be got fixed.

Here are the screenshots of tabs network calls

image

image

image

File: src/components/Patient/PatientDetailsTab/EncounterHistory.tsx [hunk 8]
```diff
@@ -4,53 +4,24 @@ import { useTranslation } from "react-i18next";
...
-import useTanStackQueryInstead from "@/Utils/request/useQuery";
-
-import { PatientProps } from ".";
-import { PatientModel } from "../models";
 
 const EncounterHistory = (props: PatientProps) => {
-  const { patientData: initialPatientData, facilityId, id } = props;
+  const { patientData: initialPatientData, id, refetch } = props;
   const [patientData, setPatientData] =
     useState<PatientModel>(initialPatientData);
```
Comment (rithviknishad) [inline src/components/Patient/PatientDetailsTab/EncounterHistory.tsx]: Why do we need a state that just takes in the props on mount and never change it in the lifecycle of the component?

```suggestion
  const { patientData, id, refetch } = props;
```

File: src/components/Patient/PatientDetailsTab/EncounterHistory.tsx [hunk 9]
```diff
@@ -4,53 +4,24 @@ import { useTranslation } from "react-i18next";
...
-  const authUser = useAuthUser();
 
   useEffect(() => {
     setPatientData(initialPatientData);
   }, [initialPatientData]);
```
Comment (rithviknishad) [inline src/components/Patient/PatientDetailsTab/EncounterHistory.tsx]:
```suggestion
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Patient/PatientDetailsTab/EncounterHistory.tsx (hunk 8 above)
Comment (Mahendar0701) [reply src/components/Patient/PatientDetailsTab/EncounterHistory.tsx]: Done the changes

File: src/components/Patient/PatientDetailsTab/EncounterHistory.tsx (hunk 9 above)
Comment (Mahendar0701) [reply src/components/Patient/PatientDetailsTab/EncounterHistory.tsx]: Done the changes

**Review by rithviknishad — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
Could replace the Button/Chip with Shad Button/Badge. But, can do that later. Lgtm.

**Comment by Mahendar0701** [comment]
> Could replace the Button/Chip with Shad Button/Badge. But, can do that later. Lgtm.

I will get it done in PR #9377 as you mentioned earlier in that PR

**Comment by nihal467** [comment]
LGTM
