### PR TITLE
Fixed search icon and removed delete option

### LINKED ISSUE #9057: Search Icon is being hidden in every Search Input box
**Describe the bug**
The search icon is not visible on search input component in any page, but it's available in the DOM

**To Reproduce**

1. Go to any page with Search feature like, '/facility' , '/shifting'
2. You can see that Search Icon is not showing up but it's available in the **DOM** with class **l-search-alt**

**Expected behavior**
Search Icon should appear properly

**Screenshots**

Currently this is how it looks :

Image

After Fix :

Image

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version Latest

### PR DESCRIPTION
**Pull request by nithish1018**
## Proposed Changes

- Fixes #9057 
- Fixed Search Input Icon Visibility
- Removed Delete options for Shifting and Resource Records, since they're not supported #8980 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Release Notes

- **New Features**
	- Enhanced visibility of the CareIcon in the SearchInput component.

- **Bug Fixes**
	- Removed deletion functionality for resources and shifts, streamlining user interactions in ResourceDetails and ShiftDetails components.

- **Refactor**
	- Cleaned up unused imports and state variables related to deletion processes in ShiftDetails.

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

File: src/components/Resource/ResourceDetails.tsx [hunk 1]
```diff
@@ -27,25 +22,6 @@ export default function ResourceDetails(props: { id: string }) {
       }
     },
   });
-
-  const handleResourceDelete = async () => {
-    setOpenDeleteResourceDialog(true);
-    const { res, data } = await request(routes.deleteResourceRecord, {
```
Comment (rithviknishad) [inline src/components/Resource/ResourceDetails.tsx:33]: do delete the route definitions too since such api's doesn't exist.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Resource/ResourceDetails.tsx (hunk 1 above)
Comment (nithishsiliveru) [reply src/components/Resource/ResourceDetails.tsx:33]: Sure, I'll

**Review by rithviknishad — APPROVED** [review]
