### PR TITLE
fix: Update HistoricalRecordSelector component to restrict sheet opening to only when button clicks 

### LINKED ISSUE #12313: Restrict sheet opening to only History button clicks
**Description**
Clicking  near the **History** button—including whitespace beside it— is unintentionally triggering the sheet to open. This issue is present across multiple modules (where HistoricalRecordSelector is used ) such as:

- Medication Requests  
- Symptoms  
- Diagnosis  
- Medication Statement

**Steps to Reproduce for DiagnosisQuestion**
1. Go to any active encounter.
2. In overview section . Click on Add Diagnosis.
3. See the error

**Expected**

- Sheet **opens** only when the actual **History** button is clicked  

**Screenshots**

https://github.com/user-attachments/assets/2269c5cb-1e34-4271-837c-db28880a9ada

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Tanuj1718**
## Proposed Changes

- Fixes #12313 

https://github.com/user-attachments/assets/f2078392-2149-42f8-a762-f0f23e222250

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Updated the alignment and layout of the "View History" button for improved visual consistency.

### CODE REVIEW

File: src/components/HistoricalRecordSelector/index.tsx [hunk 1]
```diff
@@ -347,7 +347,7 @@ export function HistoricalRecordSelector<T extends BaseRecord>({
       }}
     >
       <SheetTrigger asChild>
-        <div className="flex items-center justify-end">
+        <div className="w-fit ml-auto">
           <Button
             variant="outline"
             data-cy="view-history"
```
Comment (rithviknishad) [inline src/components/HistoricalRecordSelector/index.tsx]: why do we even need a div in the first place? 🤔

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/HistoricalRecordSelector/index.tsx (hunk 1 above)
Comment (Tanuj1718) [reply src/components/HistoricalRecordSelector/index.tsx]: I didn't remove it as I was thinking what if we use other components in future just like we have used button currently😅

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
