### PR TITLE
Changes on Assigning/Reassigning/Unassigning Volunteer to Patient

### LINKED ISSUE #9316: Incorrect notification message on updating/assigning volunteer to a patient
**Describe the bug**
- When assigning Volunteer to a patient (even for the first time), Notification says 'Volunteer unassigned successfuly' which is inappropriate.
- There is no option to unassign a volunteer 
- There is also a option to Assign volunteer to dead patients which seems inappropriate.
- Also there is typo in notification message i.e 'successfuly'

**To Reproduce**

1. Go to '/patients'
2. Click on any patient
3. Scroll down to 'Assign to a Volunteer' under Actions
4. Choose a Volunteer 
5. See Error

**Expected behavior**
- When assigning volunteer for the first time message should be 'Volunteer assigned successfully'.
- When updating the volunteer message should be 'Volunteer updated successfully'
- Also there should be a option (like a button) to unassign the current Volunteer and give appropriate notification message like 'Volunteer unassigned successfully'.

**Screenshots**
https://github.com/user-attachments/assets/f97f25bf-c4ad-46d1-9e53-e089f4b8ef65

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser - Chrome
- Version 131.0.6778.86 (Official Build) (64-bit)

**Additional context**

### PR DESCRIPTION
**Pull request by rajku-dev**
## Proposed Changes

- Fixes #9316  
- Change Assign Button Label accordingly 
- Give proper Notification message for assigning/unassigning/reassigning volunteer to a patient

## Screenshots

https://github.com/user-attachments/assets/ea4ea518-7adc-47d2-bc40-b7557d8afc31

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Release Notes

- **New Features**
	- Added localization support for new keys: "Unassign" and "Reassign Volunteer."
- **Bug Fixes**
	- Corrected spelling and grammatical errors in existing localization strings.
- **Improvements**
	- Enhanced user notifications for volunteer assignment, unassignment, and updates with clear success messages.
	- Updated action button text in the confirmation dialog to reflect the current volunteer assignment status.

### CODE REVIEW

**Comment by rajku-dev** [comment]
@Jacobjeevan please review the changes.

File: src/components/Patient/PatientHome.tsx [hunk 1]
```diff
@@ -91,6 +91,9 @@ export const PatientHome = (props: {
   });
 
   const handleAssignedVolunteer = async () => {
+    // console.log(patientData)
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientHome.tsx]: Remove the console.log here and in line 108.

**Review by Jacobjeevan — APPROVED** [review]
Apart from the console logs, LGTM.

**Review by rithviknishad — APPROVED** [review]
