### PR TITLE
Fix: Search in the practioner selector

### LINKED ISSUE #14781: Cannot search practitioners/ department to schedule appointment
**Describe the bug**
Cannot search practitioners/ department to schedule appointment

**Expected behavior**
Should be able to search 

**Screenshots**

https://github.com/user-attachments/assets/3c91de09-4eb3-4976-bc79-864b12f62bb8

**Desktop (please complete the following information):**

- Browser chrome
---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Proposed Changes

Fixes #14781
- Set side for the popover to show below 
- Height adjusted

Screenshot :
 
image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Improvement**
  * Option to toggle between showing practitioners from all organizations or limiting to current organizations.

* **Bug Fixes**
  * Practitioner selector dropdown adapts to viewport height and enables vertical scrolling for long lists.
  * Popover placement constrained to appear below the selector for more consistent positioning.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

File: src/pages/Appointments/components/PractitionerSelector.tsx [hunk 1]
```diff
@@ -321,7 +321,7 @@ export const PractitionerSelector = ({
               </div>
             </div>
 
-            <CommandList className="max-h-[400px]">
+            <CommandList className="max-h-[calc(100vh-30rem)]">
```
Comment (Jacobjeevan) [inline src/pages/Appointments/components/PractitionerSelector.tsx]: May need to adjust for smaller devices. cc: @nihal467  do test

**Review by Jacobjeevan — APPROVED** [review]

File: src/pages/Appointments/components/PractitionerSelector.tsx (hunk 1 above)
Comment (yash-learner) [inline src/pages/Appointments/components/PractitionerSelector.tsx]: I think this would break(List items will not be visible), when the input is focused and keyboard is open in drawer 



https://github.com/user-attachments/assets/910739b0-5e71-47a4-9ced-89c7b5227bb2

**Review by yash-learner — DISMISSED** [review]

File: src/pages/Appointments/components/PractitionerSelector.tsx (hunk 1 above)
Comment (khavinshankar) [reply src/pages/Appointments/components/PractitionerSelector.tsx]: @yash-learner  This will not be a problem, tested it with multiple users, it simply overflows

image

**Review by khavinshankar — APPROVED** [review]

File: src/pages/Appointments/components/PractitionerSelector.tsx (hunk 1 above)
Comment (yash-learner) [reply src/pages/Appointments/components/PractitionerSelector.tsx]: @khavinshankar

Test on a  real mobile device and not on dev-tools.

You should see it, like me

Comment (khavinshankar) [reply src/pages/Appointments/components/PractitionerSelector.tsx]: I tried in physical mobile, still works fine

image

**Review by nihal467 — CHANGES_REQUESTED** [review]
Image

When we are searching for a user with my department filter, the user list fetched shows results of users who aren't part of my org

File: src/pages/Appointments/components/PractitionerSelector.tsx (hunk 1 above)
Comment (yash-learner) [reply src/pages/Appointments/components/PractitionerSelector.tsx]: Open the keyboard you should see the issue as shown here, https://github.com/ohcnetwork/care_fe/pull/14785#discussion_r2628174626

File: src/pages/Appointments/components/PractitionerSelector.tsx [hunk 2]
```diff
@@ -321,7 +321,7 @@ export const PractitionerSelector = ({
               </div>
             </div>
 
-            <CommandList className="max-h-[400px]">
+            <CommandList className="md:max-h-[30dvh] overflow-y-auto">
```
Comment (yash-learner) [inline src/pages/Appointments/components/PractitionerSelector.tsx:331]: @coderabbitai I think it will take max height of drawer because on mobile it is rendered inside a drawer and shadcn drawer has a max height

File: src/pages/Appointments/components/PractitionerSelector.tsx [hunk 3]
```diff
@@ -321,7 +328,7 @@ export const PractitionerSelector = ({
...
```
[the remark this answers is not in the document]
Comment (yash-learner) [reply src/pages/Appointments/components/PractitionerSelector.tsx:331]: https://github.com/ohcnetwork/care_fe/pull/14785#discussion_r2634892315

**Comment by yash-learner** [comment]
> Image
> When we are searching for a user with my department filter, the user list fetched shows results of users who aren't part of my org

Fixed https://github.com/ohcnetwork/care_fe/pull/14785/commits/40862754c58f12b025e7bf28a20ab47e72fefca8

image

**Review by rithviknishad — APPROVED** [review]

**Review by nihal467 — APPROVED** [review]
