### PR TITLE
fix: Size of logo in the print

### LINKED ISSUE #14482: The size of logo is too small in the print
**Describe the bug**
The size of logo is too small in the print

**Expected behavior**
It should be a large for visibility

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Proposed Changes
- Fix: #14482
- Adjust the height and width of section-to-print img class

Screenshot:
image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Style**
  * Increased maximum display size for logo images in printed layouts, expanding allowed width and height so logos appear larger and clearer on printouts while preserving aspect ratio and containment.
  
<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

File: src/pages/Facility/billing/invoice/PrintInvoice.tsx [hunk 1]
```diff
@@ -115,7 +115,7 @@ export function PrintInvoice({ facilityId, invoiceId }: PrintInvoiceProps) {
           <img
             src={careConfig.mainLogo?.dark}
             alt="Care Logo"
-            className="h-10 w-auto object-contain mb-2 sm:mb-0 order-2"
+            className="h-10 w-auto object-contain mb-2 sm:mb-0 order-2 print:scale-170"
```
Comment (rithviknishad) [inline src/pages/Facility/billing/invoice/PrintInvoice.tsx]: works, but i'd suggest finding the root cause

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by yash-learner — APPROVED** [review]
