### PR TITLE
Fix : Minimum value in forms should be greater than 0

### LINKED ISSUE #7272: Bug : Values in Forms can be Negative
**Describe the bug**
Currently in forms users are allowed to input negative values in places where it's should be not allowed. 

**To Reproduce** 
(one of the examples)
1. Navigate to '/facility/a782943c-6db9-4994-880d-2c391b89b955'
2. Click on "Add Triage"
3. Fill out the form with a negative value and submit
4. Observe the bug.

**Expected behavior**
The form should not allow for negative values, and the minimum value accepted should be 0.

**Screenshots**

https://github.com/coronasafe/care_fe/assets/91189139/e75ffa39-8930-45a8-af12-bf41ffed4593

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 22

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Keshav-0907**
## Proposed Changes

- Fixes #7272
- Set the minimum value in the triage input field to be 0

https://github.com/coronasafe/care_fe/assets/91189139/82e3721b-c7b4-441e-b357-bd8a6fbadf57

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Review by Ashesh3 — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/Components/Facility/ConsultationForm.tsx [hunk 1]
```diff
@@ -641,6 +641,29 @@ export const ConsultationForm = ({ facilityId, patientId, id }: Props) => {
...
+          if (state.form.suggestion !== "DD") {
+            const value = state.form[field];
+            if (!value || parseFloat(value) <= 0) {
+              errors[field] = "Please enter a valid Height";
+              invalidForm = true;
+              break;
+            }
+          }
+          return;
+        }
```
Comment (khavinshankar) [inline src/Components/Facility/ConsultationForm.tsx]:
```suggestion
        case "weight": 
        case "height": {
          if (state.form.suggestion !== "DD") {
            const value = state.form[field];
            if (!value || parseFloat(value) <= 0) {
              errors[field] = `Please enter a valid ${field}`;
              invalidForm = true;
              break;
            }
          }
          return;
        }
```

@Keshav-0907 The logic looks similar, why not combine the blocks, would be much easier to read. Please do the same in other places too

**Review by khavinshankar — APPROVED** [review]

**Review by rithviknishad — COMMENTED** [review]
There seems to be a problem with this approach. These checks are valid only if the fields are "required". If no value is entered, the checks should still pass. However, that is not the case with this PR.

Fixed in #7775 

cc: @Keshav-0907
