### PR TITLE
Tab Bar Hover Shows Default Arrow

### LINKED ISSUE #12562: Tab Bar Hover Shows Pointer Cursor Instead of Default Arrow
**Describe the bug**
Cursor shows “pointer” hand over Symptom History tab bar instead of default arrow

**To Reproduce**

1. Go to 'Encounters' -> "View Details" -> "Add questionnaire" -> "Symptom History"
2. See error.

https://github.com/user-attachments/assets/4f9f2d84-4646-4617-ae7e-c5e46ec8588e

**Expected behavior**
The cursor should remain the default arrow when hovering.

I will add ` cursor-default` in  <TabsTrigger.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Sreyas62**
## Proposed Changes

- Fixes #12562 
- Hide tab for structuredTypes's length equals 1.
- Implemented new div for 1 tab

- Demo video : 

https://github.com/user-attachments/assets/30d0c5a2-843a-4ebe-ab2a-5afc0d8d46b3

@ohcnetwork/care-fe-code-reviewers @rithviknishad 

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Improved the tab interface in the historical record selector: when only one tab is available, it now appears as a centered, non-interactive label instead of a clickable tab.
  - Added descriptive, localized titles to the historical record selector for diagnosis, medication, and symptom history sections.

### CODE REVIEW

**Review by NikhilA8606 — CHANGES_REQUESTED** [review]
It

File: src/components/HistoricalRecordSelector/index.tsx [hunk 1]
```diff
@@ -356,11 +356,20 @@ export function HistoricalRecordSelector<T extends BaseRecord>({
             className="w-full"
           >
             <TabsList className="w-full">
-              {structuredTypes.map(({ type }) => (
-                <TabsTrigger key={type} value={type} className="flex-1">
-                  {type}
-                </TabsTrigger>
-              ))}
+              {structuredTypes.map(({ type }) =>
+                structuredTypes.length > 1 ? (
```
Comment (NikhilA8606) [inline src/components/HistoricalRecordSelector/index.tsx]: It would be better the ternary condition check for entire Tabs component

**Review by NikhilA8606 — CHANGES_REQUESTED** [review]

**Comment by yadavshubham01** [comment]
Hey @Sreyas62, Please make sure to only check the relevant items in the merge checklist. Avoid ticking options that aren’t applicable to the PR

File: src/components/HistoricalRecordSelector/index.tsx [hunk 2]
```diff
@@ -350,19 +350,32 @@ export function HistoricalRecordSelector<T extends BaseRecord>({
...
+                ))}
+              </TabsList>
+            </Tabs>
+          ) : (
+            <div className="w-full">
               {structuredTypes.map(({ type }) => (
-                <TabsTrigger key={type} value={type} className="flex-1">
+                <div
+                  key={type}
+                  className="flex-1 cursor-default text-center py-1 text-sm text-black bg-white border border-gray-200 rounded-md shadow-sm"
```
Comment (AdityaJ2305) [inline src/components/HistoricalRecordSelector/index.tsx]: why to show it as button or tab trigger if it is not ?


```suggestion
                  className="flex-1 font-semibold text-center py-1 text-md"
```
after suggestion changes:

Screenshot 2025-06-16 at 5 10 29 PM

Comment (bodhish) [reply src/components/HistoricalRecordSelector/index.tsx]: Why do we need the title? Can't we just concat it with the title as `Symptoms History` 🤔

Comment (AdityaJ2305) [reply src/components/HistoricalRecordSelector/index.tsx]: @Sreyas62  👆

Comment (Sreyas62) [reply src/components/HistoricalRecordSelector/index.tsx]: Screenshot From 2025-06-19 11-06-24
Should be like this?
@bodhish

Comment (AdityaJ2305) [reply src/components/HistoricalRecordSelector/index.tsx]: No , see on top left we can directly have title there instead of `History` we should have "Symptom History" in given example

Comment (Sreyas62) [reply src/components/HistoricalRecordSelector/index.tsx]: Screenshot From 2025-06-19 11-23-17
ok?

Comment (AdityaJ2305) [reply src/components/HistoricalRecordSelector/index.tsx]: - [ ] Position `Symptom History` to centre 
- [ ]  As bodhi mentioned in comment, don't need title (Symptoms) anymore,  Sheet title is enough

File: src/components/HistoricalRecordSelector/index.tsx [hunk 3]
```diff
@@ -350,19 +350,32 @@ export function HistoricalRecordSelector<T extends BaseRecord>({
...
+            <div className="w-full">
               {structuredTypes.map(({ type }) => (
-                <TabsTrigger key={type} value={type} className="flex-1">
+                <div
+                  key={type}
+                  className="flex-1 font-semibold text-center py-1 text-md"
+                >
                   {type}
-                </TabsTrigger>
+                </div>
```
Comment (AdityaJ2305) [inline src/components/HistoricalRecordSelector/index.tsx]: remove this only want tabs to be shown and for title we will be using sheettitle only 👍

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

**Comment by AdityaJ2305** [comment]
@Sreyas62 Since you’re already working on this file, could you move the defaults for

```
buttonLabel = "View History",  
title = "History"
```

into the component itself instead of setting them as parameters?
for translation purpose

**Review by AdityaJ2305 — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image

- don't change the design

**Comment by Sreyas62** [comment]
@nihal467 the design is not changed.
image
when there is more than two tabs only the tab button is shown, otherwise only the title.
image

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by NikhilA8606 — APPROVED** [review]
