### PR TITLE
fix(encounter): allow future dates only when status is planned

### LINKED ISSUE #13293: On initiate patient encounter option, future dates are selectable for all the status types.
**Describe the bug**
On initiate encounter page future dates are selectable for all the status types, but it should be applicable only when selecting status as "Planned", not when the status is selected as "In Progress".

**To Reproduce**

1. Go to 'search patient'
2. Click on 'add new patient'
3. Fill in the patient details then save
4. Then click on "create encounter"
5. Then initiate encounter option will pop up
6.  There when selecting dates, future dates are selectable for all status type.
 
**Expected behavior**
Future date should be selectable only when the status type is selected as "Planned"

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by abhi-battula**
## Proposed Changes

Fixes #13293 

- Restricted future date selection only when status is Planned
- Disabled future dates for In Progress and On Hold statuses
- Added frontend validation to prevent manual future date submission
- Added i18n error message for future date restriction- Additional context if needed

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **New Features**
  * Date picker now disables future dates unless an encounter is marked as Planned.
* **Bug Fixes**
  * Form submission is blocked for non-planned encounters with future start dates and shows a clear validation error on the date field.
* **Localization**
  * Added user-facing error message: "Future date is only allowed for planned encounters."

### CODE REVIEW

File: src/components/Encounter/CreateEncounterForm.tsx [hunk 1]
```diff
@@ -136,6 +138,13 @@ export default function CreateEncounterForm({
   });
 
   function onSubmit(data: z.infer<typeof encounterFormSchema>) {
+    if (
```
Comment (Jacobjeevan) [inline src/components/Encounter/CreateEncounterForm.tsx]: make use of zod validations (use refine) instead

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Encounter/CreateEncounterForm.tsx (hunk 1 above)
Comment (abhi-battula) [reply src/components/Encounter/CreateEncounterForm.tsx]: Okay Jacob, I will use Zod's refine method.

**Comment by parvathyns-creator** [comment]
@nihal467 looks fine

File: src/components/Encounter/CreateEncounterForm.tsx [hunk 2]
```diff
@@ -86,20 +86,30 @@ export default function CreateEncounterForm({
...
+      priority: z.enum(ENCOUNTER_PRIORITY),
+      organizations: z.array(z.string()).min(1, {
+        message: t("at_least_one_department_is_required"),
+      }),
+      start_date: z.string(),
+      tags: z.array(z.string()),
+    })
+    .refine(
+      (data) =>
+        data.status === EncounterStatus.PLANNED ||
```
Comment (Jacobjeevan) [inline src/components/Encounter/CreateEncounterForm.tsx]:
```suggestion
        data.status !== EncounterStatus.PLANNED &&
        new Date(data.start_date) > new Date(),
```

to make it clearer

**Review by Jacobjeevan — APPROVED** [review]
Technically the refine situation wouldn't happen since disabled status disallows user from selecting future unless planned, but let's keep it 🤔

**Review by nihal467 — APPROVED** [review]

**Review by amjithtitus09 — APPROVED** [review]
