### PR TITLE
Mobile layout fixes for Appointments List view

### LINKED ISSUE #11281: Appointments List View on mobile is not responsive
**Describe the bug**
The list view page for appointments is not responsive:
- each entry doesn't fit the viewport and overflows
- the appointment status tab also doesn't fit and needs horizontal scrolling

Forces the user to scroll horizontally, makes it unable to see all information easily.
**To Reproduce**
(use a phone)
1. Go to Appointments
2. Click on "List" toggle
3. See error

**Expected behavior**
- Each appointment should fit in the mobile screen and require no scrolling
- All status filters should be visible/clickable without any scrolling

**Recording**

https://github.com/user-attachments/assets/e974d110-be9a-49ce-ae54-ae6f0fe373e7

**Smartphone (please complete the following information):**

- Device: [Pixel 6]
- OS: [Android]
- Browser [chrome]

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by abeeto**
## Proposed Changes

- Fixes #11281 
- Found out UI breaking (UI stretching out of encounter page) was due to page growing to width of its children:
   -  so, added a `overflow-x-auto` to both the status tabs and the table, so ui doesn't break

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [X] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

https://github.com/user-attachments/assets/64acb117-aafa-4c3c-b2d2-6f00ae36adf3

## Summary by CodeRabbit

- **New Features**
  - Introduced a responsive design for the appointments view, featuring a new `Select` component for filtering appointment statuses on mobile devices.
  
- **Style**
  - Enhanced the appointments view with improved responsiveness and horizontal scrolling for a smoother, better-adapted layout across various screen sizes.
  - Streamlined the layout structure for better overflow handling.

### CODE REVIEW

File: src/pages/Appointments/AppointmentsPage.tsx [hunk 1]
```diff
@@ -739,11 +739,11 @@ function AppointmentRow(props: {
     );
   }
   return (
-    <>
-      <div className={cn(!data && "animate-pulse")}>
+    <div className="max-w-[95vw] overflow-x-auto whitespace-nowrap">
+      <div className={`${cn(!data && "animate-pulse")}`}>
```
Comment (rithviknishad) [inline src/pages/Appointments/AppointmentsPage.tsx]: why string interpolate?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Appointments/AppointmentsPage.tsx (hunk 1 above)
Comment (abeeto) [reply src/pages/Appointments/AppointmentsPage.tsx]: My bad.. tried to apply the styling here first, and forgot to change it back. Will revert now. 😅

File: src/pages/Appointments/AppointmentsPage.tsx [hunk 2]
```diff
@@ -739,11 +739,11 @@ function AppointmentRow(props: {
     );
   }
   return (
-    <>
+    <div className="max-w-[95vw] overflow-x-auto whitespace-nowrap">
```
Comment (Jacobjeevan) [inline src/pages/Appointments/AppointmentsPage.tsx]: the max-w shouldn't be needed for either case.

**Review by Jacobjeevan — DISMISSED** [review]

File: src/pages/Appointments/AppointmentsPage.tsx (hunk 2 above)
Comment (abeeto) [reply src/pages/Appointments/AppointmentsPage.tsx]: True, I removed it

**Review by amjithtitus09 — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
