### PR TITLE
Fix: `UserSelector` and `PractitionerSelector` Popover width causing context overflow horizontally

### LINKED ISSUE #11670: Incorrect alignment for display name in User Selector and Practicioner Selector
**Describe the bug**

Incorrect alignment for display name in User Selector and Practicioner Selector.

**To Reproduce**

1. Go to any place where practicioner selector or user selector component is being used
2. See dropdown containing a long name similar to shown in screenshots

**Expected behavior**
Display name should be followed by username. Not as separate columns. Should be in a single span, left aligned.

**Screenshots**
Image

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

Before 
Screenshot 2025-04-08 at 1 12 14 AM

After
Screenshot 2025-04-08 at 12 19 50 PM

- [x] Fixes:  #11670 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
	- Adjusted component layouts to ensure buttons and interactive items span the full container width, enhancing visual consistency and responsiveness.
	- Enhanced input fields to utilize available space more effectively.
- **New Features**
	- Introduced state management in the PractitionerSelector component for better control of the Popover visibility based on user interactions.

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
can we show the username below the name instead? 🤔

File: src/pages/Appointments/components/PractitionerSelector.tsx [hunk 1]
```diff
@@ -40,6 +40,7 @@ export const PractitionerSelector = ({
   clearSelection,
 }: PractitionerSelectorProps) => {
   const { t } = useTranslation();
+  const [open, setOpen] = useState(false);
```
Comment (rithviknishad) [inline src/pages/Appointments/components/PractitionerSelector.tsx:43]: why do we need a state for handling the open/close state? 🤔 

Popover along with Command automatically handles it for us already right? Let's stick with the defaults unless necessary!

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Appointments/components/PractitionerSelector.tsx (hunk 1 above)
Comment (AdityaJ2305) [reply src/pages/Appointments/components/PractitionerSelector.tsx:43]: we have this almost everywhere for commandinput
moreover, popoverclose does that but it is breaking css 🤔

Comment (AdityaJ2305) [reply src/pages/Appointments/components/PractitionerSelector.tsx:43]: We don't have popoverclose implemented aywhere

**Review by rithviknishad — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
lgtm.

On a side note, I'd suggest adjusting the width, esp for smaller screens

image
