### PR TITLE
Fix Notifications for Facility Cover Image Deletion 

### LINKED ISSUE #7595: Add Notifications for Facility Cover Image Deletion
**Describe the bug**

- [ ] Notification is Missing Upon Deletion of Facility Cover Image

**To Reproduce**

1. Go to the Facility detail page with the existing cover image
2. delete the existing cover image
3. See error

**Expected behavior**

- [ ] Upon deletion of a cover image, add a notification stating " Facility Cover Image Deleted Successfully "

**Screenshots**

image

### PR DESCRIPTION
**Pull request by AnkurPrabhu**
## Proposed Changes

- Fixes #7595 
-  Fixing re-render issue 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

screenshot:
Screenshot 2024-04-15 at 12 57 27 AM

### CODE REVIEW

**Comment by AnkurPrabhu** [comment]
@rithviknishad we already had notification for deletion its just that due to re-renders it does not show it. this should fix it

File: src/Components/Facility/CoverImageEditModal.tsx [hunk 1]
```diff
@@ -283,9 +286,19 @@ const CoverImageEditModal = ({
...
+                  {isDeleting ? (
+                    <CareIcon
+                      icon="l-spinner"
+                      className="animate-spin text-lg"
+                    />
+                  ) : (
+                    <CareIcon icon="l-save" className="text-lg" />
+                  )}
+                  <span>
+                    {isDeleting ? `${t("Deleting")}...` : `${t("delete")}`}
```
Comment (bodhish) [inline src/Components/Facility/CoverImageEditModal.tsx]: why are we using capital key `Deleting`? 🤔

Comment (bodhish) [inline src/Components/Facility/CoverImageEditModal.tsx]: Don't we have something simlar to [disabling cover](https://github.com/pupilfirst/pupilfirst/blob/master/app/frontend/shared/components/DisablingCover.res) that disables the entrie action on save?

**Review by bodhish — CHANGES_REQUESTED** [review]

File: src/Components/Facility/CoverImageEditModal.tsx (hunk 1 above)
Comment (AnkurPrabhu) [reply src/Components/Facility/CoverImageEditModal.tsx]: will change it to deleting

Comment (AnkurPrabhu) [reply src/Components/Facility/CoverImageEditModal.tsx]: i just used what we already do for upload we just wanted a re-render to happen here in order to fix the bug, should i remove it ?

**Comment by AnkurPrabhu** [comment]
pls take a look @bodhish

**Review by rithviknishad — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/Components/Facility/CoverImageEditModal.tsx [hunk 2]
```diff
@@ -36,6 +36,7 @@ const CoverImageEditModal = ({
   facility,
 }: Props) => {
   const [isUploading, setIsUploading] = useState(false);
+  const [isDeleting, setIsDeleting] = useState(false);
```
Comment (gigincg) [inline src/Components/Facility/CoverImageEditModal.tsx]: @AnkurPrabhu 

`isDeleting` and `isUploading` can be merged into an `isProcessing` State, since it's best to block both actions, when one action is pending. 

While you're at it, can you also move out the Constants outside of the component, no reason for it to get redeclared every time the component re-renders.

**Review by gigincg — CHANGES_REQUESTED** [review]

File: src/Components/Facility/CoverImageEditModal.tsx (hunk 2 above)
Comment (AnkurPrabhu) [reply src/Components/Facility/CoverImageEditModal.tsx]: will do the changes

Comment (AnkurPrabhu) [reply src/Components/Facility/CoverImageEditModal.tsx]: @gigincg have resolved your comment

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — CHANGES_REQUESTED** [review]
@AnkurPrabhu can u also move the constants (that doesn't depend on any state) outside the function

**Comment by AnkurPrabhu** [comment]
> @AnkurPrabhu can u also move the constants (that doesn't depend on any state) outside the function

@khavinshankar can you explain as in what do you mean by constants here

File: src/Components/Facility/CoverImageEditModal.tsx [hunk 3]
```diff
@@ -123,34 +123,36 @@ const CoverImageEditModal = ({
...
       () => {
         Notification.Error({
           msg: "Network Failure. Please check your internet connectivity.",
         });
-        setIsUploading(false);
+        setIsProcessing(false);
       },
     );
 
     await sleep(1000);
```
Comment (khavinshankar) [inline src/Components/Facility/CoverImageEditModal.tsx:149]: @AnkurPrabhu  can remove this and check if there is any sideeffects

**Review by khavinshankar — CHANGES_REQUESTED** [review]
@AnkurPrabhu some minor suggestions,

Can you please move these constants out of the component (these doesn't depend on any state or props)
const FACING_MODE_USER = "user";
const FACING_MODE_ENVIRONMENT = { exact: "environment" };
const videoConstraints = {
    width: 1280,
    height: 720,
    facingMode: "user",
  };
  const LaptopScreenBreakpoint = 640;

File: src/Components/Facility/CoverImageEditModal.tsx (hunk 3 above)
Comment (AnkurPrabhu) [reply src/Components/Facility/CoverImageEditModal.tsx:149]: @khavinshankar can we connect on slack today i had some doubts.

**Comment by nihal467** [comment]
LGTM
