### PR TITLE
Enhancements to Encounter Discussion/Notes | Fix Translation

### LINKED ISSUE #9842: Enhancements in Encounter Discussion
- Message expects a `profile URL` or `avatar link` to navigate to user profile
link to

- Each message should be labeled with a timestamp indicating when it was sent or received. (backend provides it)

- If this number is used to display the number of users participated in thread, then it needs to be fixed, and next to it we can show number of messages (can be derived from existing backend response)

- Duplicate thread name - labelling them by slicing their provided ids

### PR DESCRIPTION
**Pull request by rajku-dev**
## Proposed Changes

- Fixes #9842
- [X] Add relative time for messages
- [X] Link to user Profile from Avatar
- [X]  Prevent Multiple threads with the same title 
- [x] Show total number of participants and messages in a thread and tooltip for the same
- [x] Handle Scroll to bottom on initial load and scroll to bottom on adding new message

image

https://github.com/user-attachments/assets/7f8915d4-9520-4b9f-9a3b-df384e0b4483

https://github.com/user-attachments/assets/19e3afe5-e880-42e5-a8fd-6586302f3e89

INFINITE SCROLL

Uploading Recording 2025-02-04 144900.mp4…

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Made user avatars within messages clickable for direct profile navigation.
  - Enhanced the thread creation dialog with refined thread selection, consistent button text, and improved error handling for duplicate thread titles.
  - Added clear error messages to inform users when messaging fails.
  - Introduced prompts for users to enter a custom title when creating a new thread without one.
  - Improved messaging capabilities with additional user-friendly error messages.

### CODE REVIEW

**Comment by rajku-dev** [comment]
@Jacobjeevan Please review the changes. Thank you.

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx [hunk 1]
```diff
@@ -400,6 +418,12 @@ export const EncounterNotesTab = ({ encounter }: EncounterTabProps) => {
 
   const handleCreateThread = (title: string) => {
     if (title.trim()) {
+      if (
+        threadsData?.results.some((thread) => thread.title === title.trim())
+      ) {
+        toast.error("Thread with this title already exists.");
```
Comment (Jacobjeevan) [inline src/pages/Encounters/tabs/EncounterNotesTab.tsx]: add translation

Comment (Jacobjeevan) [reply src/pages/Encounters/tabs/EncounterNotesTab.tsx]: You also need to modify the dialog box accordingly (display templates thread names only if any are available, and display filtered list)

image

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx (hunk 1 above)
Comment (Jacobjeevan) [reply src/pages/Encounters/tabs/EncounterNotesTab.tsx]: Also while you are at it, wrap the cancel button inside DialogClose to trigger the onOpenChange behavior instead.

```
<DialogClose asChild disabled={isCreating}>
            <Button variant="outline">{t("Cancel")}</Button>
          </DialogClose>

```

Comment (rajku-dev) [reply src/pages/Encounters/tabs/EncounterNotesTab.tsx]: made the changes as requested.

Comment (Jacobjeevan) [reply src/pages/Encounters/tabs/EncounterNotesTab.tsx]: > You also need to modify the dialog box accordingly (display templates thread names only if any are available, and display filtered list)
> image

☝️  You would still be displaying the subtext here (choose a template or enter a custom title; you would need to display an alternate subtext when threadTemplates count is 0).

Comment (rajku-dev) [reply src/pages/Encounters/tabs/EncounterNotesTab.tsx]: made the changes as requested. Please review.

**Comment by rajku-dev** [comment]
this looks better, trimmed down the ago from relative time
image

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx [hunk 2]
```diff
@@ -161,15 +171,28 @@ const MessageItem = ({ message }: { message: Message }) => {
...
-                <Markdown content={message.message} className="text-sm" />
+              <div className="mt-0">
+                <Markdown content={message.message} className="text-sm mb-2" />
+                <span className="text-[11px] text-gray-500 flex justify-end items-end">
+                  <Tooltip>
+                    <TooltipTrigger>
+                      {relativeTime(message.created_date)
+                        .split(" ")
+                        .slice(0, -1)
+                        .join(" ")}
```
Comment (Jacobjeevan) [inline src/pages/Encounters/tabs/EncounterNotesTab.tsx]: let's add "ago" as well.

Comment (rajku-dev) [reply src/pages/Encounters/tabs/EncounterNotesTab.tsx]: made the changes as requested.

**Comment by nihal467** [comment]
image

- [ ] After 14 messages, the page keeps refreshing when users scroll, preventing them from loading additional content. This issue occurs because infinite scroll is not supported.

@rajku-dev try to solve the above issue ASAP, as it already exist in our develop version as well

**Comment by rajku-dev** [comment]
> image
> 
> - [ ] After 14 messages, the page keeps refreshing when users scroll, preventing them from loading additional content. This issue occurs because infinite scroll is not supported.
> 
> @rajku-dev try to solve the above issue ASAP, as it already exist in our develop version as well

Sure, I have tried solving it, can you check it once more @nihal467

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx [hunk 3]
```diff
@@ -170,14 +179,26 @@ const MessageItem = ({ message }: { message: Message }) => {
...
+                  <Tooltip>
+                    <TooltipTrigger>
+                      {relativeTime(message.created_date)}
+                    </TooltipTrigger>
+                    <TooltipContent>
+                      {new Date(message.created_date).toLocaleString()}
+                    </TooltipContent>
+                  </Tooltip>
+                </span>
+              </div>
```
Comment (rithviknishad) [inline src/pages/Encounters/tabs/EncounterNotesTab.tsx]: we are already showing time of the message. this is redundant

```suggestion
```

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx [hunk 4]
```diff
@@ -170,14 +179,26 @@ const MessageItem = ({ message }: { message: Message }) => {
           </p>
           <div
             className={cn(
-              "p-3 rounded-lg break-words",
+              "pl-2 pr-1 pt-1 rounded-lg break-words border border-primary-200 relative",
```
Comment (rithviknishad) [inline src/pages/Encounters/tabs/EncounterNotesTab.tsx]: are you sure this is right? this is just conflicting with other conditional classes

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx (hunk 4 above)
Comment (rajku-dev) [reply src/pages/Encounters/tabs/EncounterNotesTab.tsx]: made the changes.

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx [hunk 5]
```diff
@@ -177,7 +186,9 @@ const MessageItem = ({ message }: { message: Message }) => {
             )}
           >
             {message.message && (
-              <Markdown content={message.message} className="text-sm" />
+              <div className="mt-0">
+                <Markdown content={message.message} className="text-sm mb-2" />
+              </div>
```
Comment (rithviknishad) [inline src/pages/Encounters/tabs/EncounterNotesTab.tsx]: why was this changed? i don't see any issue with how it's there currently

**Review by rithviknishad — CHANGES_REQUESTED** [review]
do update PR's body to only mention what was changed. keep it updated everytime anything is changed.

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx [hunk 6]
```diff
@@ -539,10 +584,25 @@ export const EncounterNotesTab = ({ encounter }: EncounterTabProps) => {
...
+                      <MessageSquare className="h-4 w-4 ml-3" />
+                      <span>{messages.length}</span>
+                    </div>
+                  </TooltipTrigger>
+                  <TooltipContent>
+                    <p>
+                      Participants:{" "}
+                      {new Set(messages.map((m) => m.created_by.id)).size}
+                    </p>
+                    <p>Messages: {messages.length}</p>
```
Comment (rithviknishad) [inline src/pages/Encounters/tabs/EncounterNotesTab.tsx]: missing i18n

**Review by rithviknishad — APPROVED** [review]
lgtm, add i18n for this:

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx [hunk 7]
```diff
@@ -382,28 +389,66 @@ export const EncounterNotesTab = ({ encounter }: EncounterTabProps) => {
...
       queryClient.invalidateQueries({ queryKey: ["messages", selectedThread] });
       setNewMessage("");
-      setTimeout(() => {
-        messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
-      }, 100);
+      setNextPageFetching(true);
+    },
+    onError: () => {
+      toast.error(t("failed_to_send_message"));
     },
```
Comment (rithviknishad) [inline src/pages/Encounters/tabs/EncounterNotesTab.tsx]: global error handler will handle this.
```suggestion
```

**Comment by rajku-dev** [comment]
> do update PR's body to only mention what was changed. keep it updated everytime anything is changed.

updated ✅

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
**Bug**

image

- [ ] Number of people present and message are missing on the encounter tab in normal view




image

- [ ] When we have more than 25 messages and scroll to the top, the scroller should automatically adjust to the starting point of the newly loaded messages. This ensures a smooth experience where users can continuously load older messages by scrolling upward. Currently, after loading older messages, the scroller stays fixed at the top, forcing users to scroll down and back up again to load more messages.

CC: @Jacobjeevan @rithviknishad

**Comment by rajku-dev** [comment]
I am not able to add new comments for testing ,logged in as a `staffdev`
unable to login as `devdistrictadmin` @nihal467

**Comment by rajku-dev** [comment]
not able to add new comments for testing, while logged in as `staffdev` or `careadmin`
image
@nihal467 
@Jacobjeevan 

Edit : Not able to create thread also
image

**Comment by Jacobjeevan** [comment]
> not able to add new comments for testing, while logged in as `staffdev` or `careadmin` image @nihal467 @Jacobjeevan
> 
> Edit : Not able to create thread also image

Check encounter's status (completed, cancelled, entered in error and discontinued status) don't have edit perms (perms based rendering are yet to be wired).

**Comment by rajku-dev** [comment]
> **Bug**
> * [ ]  Number of people present and message are missing on the encounter tab in normal view
> * [ ]  When we have more than 25 messages and scroll to the top, the scroller should automatically adjust to the starting point of the newly loaded messages. This ensures a smooth experience where users can continuously load older messages by scrolling upward. Currently, after loading older messages, the scroller stays fixed at the top, forcing users to scroll down and back up again to load more messages.
> 
> CC: @Jacobjeevan @rithviknishad

Fixed the first bug.
For the second bug user now can smoothly scroll up to see old messages if they do it gently

**Comment by nihal467** [comment]
image

@rajku-dev The total message count is not visible; the number of messages currently shown is based only on the messages loaded so far.

@Jacobjeevan the scroll still doesn't seem right, I think you can work on it

**Comment by rajku-dev** [comment]
made the changes for total number of messages ✅

**Comment by Jacobjeevan** [comment]
> made the changes for total number of messages ✅

Make sure to remove the changes for scroll as well, if you made any 👍

**Comment by rajku-dev** [comment]
> > made the changes for total number of messages ✅
> 
> Make sure to remove the changes for scroll as well, if you made any 👍

made the changes as requested.

**Comment by Jacobjeevan** [comment]
I'm adding the scroll behavior to this PR 👍  We will get it merged after that.

**Comment by Jacobjeevan** [comment]
> I'm adding the scroll behavior to this PR 👍 We will get it merged after that.

@nihal467 Merging this as the scroll behavior isn't as important right now, you can file an issue later for a contributor.
