### PR TITLE
Replace all window.location.reload() with data refetch.

### LINKED ISSUE #6756: CARE reloads when a patient is discharged
**Describe the bug**
When "Discharge From Care" is submitted, the entire CARE app reloads causing it to fetch all the resources again.

**To Reproduce**

1. Discharge a patient

**Expected behavior**
Instead of refreshing the page, just trigger the refetch of appropriate queries to cause it to re-render with new state.

### PR DESCRIPTION
**Pull request by sriharsh05**
## Proposed Changes

- Fixes #6756 
- replaced window.location.reload with fetchdata function in patient discharge.
- replaced window.location.reload with  refetch while updating facility cover image.
- replaced window.location.reload with  refetch in assetImportModal.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

File: src/Components/Common/UpdatableApp.tsx
Comment (rithviknishad) [inline src/Components/Common/UpdatableApp.tsx:1]: `UpdatableApp` needs to do `window.location.reload()` itself since all the latest resources needs to be re-fetched.

Revert changes made related to `UpdatableApp`

File: src/Components/Assets/AssetImportModal.tsx [hunk 1]
```diff
@@ -170,7 +171,7 @@ const AssetImportModal = ({ open, onClose, facility }: Props) => {
       Notification.Success({ msg: "Assets imported successfully" });
       await sleep(1000);
       setIsImporting(false);
-      window.location.reload();
+      onUpdate && onUpdate();
```
Comment (rithviknishad) [inline src/Components/Assets/AssetImportModal.tsx]:
```suggestion
      onUpdate?.();
```

File: src/Components/Assets/AssetsList.tsx [hunk 2]
```diff
@@ -128,6 +134,12 @@ const AssetsList = () => {
     }
   };
 
+  const handleUpdate = () => {
+    assetsFetch();
+    facilityFetch();
+    locationFetch();
+  };
```
Comment (rithviknishad) [inline src/Components/Assets/AssetsList.tsx]: Why refetch everything when only the asset list is being updated?

File: src/Components/Patient/PatientInfoCard.tsx [hunk 3]
```diff
@@ -141,7 +141,11 @@ export default function PatientInfoCard(props: {
           />
           <DischargeModal
             show={openDischargeDialog}
-            onClose={() => setOpenDischargeDialog(false)}
+            onClose={() => {
+              setOpenDischargeDialog(false);
+              props.fetchPatientData &&
+                props.fetchPatientData({ aborted: false });
```
Comment (rithviknishad) [inline src/Components/Patient/PatientInfoCard.tsx]:
```suggestion
              props.fetchPatientData?.({ aborted: false });
```

File: src/Components/Patient/PatientInfoCard.tsx [hunk 4]
```diff
@@ -141,7 +141,11 @@ export default function PatientInfoCard(props: {
...
+            }}
```
Comment (rithviknishad) [inline src/Components/Patient/PatientInfoCard.tsx]: Wouldn't this cause this to unnecessarily refetch when the dialog is closed without clicking on submit?

File: src/Components/Users/UserProfile.tsx [hunk 5]
```diff
@@ -164,12 +164,18 @@ export default function UserProfile() {
...
+    refetch: skillsFetch,
+    loading: isSkillsLoading,
+  } = useQuery(routes.userListSkill, {
+    pathParams: { username: authUser.username },
+  });
+
+  const onUpdateLocalStorage = () => {
+    skillsFetch();
+    refetchUserData();
+  };
```
Comment (rithviknishad) [inline src/Components/Users/UserProfile.tsx]: Not relevant. Updatable App should cause `window.location.reload()` itself instead of simply re-fetching user profile details.

```suggestion
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by sriharsh05** [comment]
@rithviknishad 
Please review the changes.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
