### PR TITLE
Fix : Expand Tree items by clicking row/text instead of arrow icon

### LINKED ISSUE #11601: Expand Tree items by clicking row/text instead of arrow icon
**Describe the bug**
In the Department/Teams section of Settings. users must explicitly click the arrow button to expand/collapse department items which is not user friendly.

**To Reproduce**

1. Go to 'Settings'
2. Navigate to 'Departments/Teams' section.
3.  Notice that clicking the text/name doesn't expand/collapse the item.
4. Only clicking the small arrow icon works for expansion/collapse.

https://github.com/user-attachments/assets/59b1b50b-ea87-4363-92cd-91812641d135

**Expected behavior**

Clicking anywhere on the item text/name should expand/collapse the item

Expected Output.

https://github.com/user-attachments/assets/7c6035f1-15f8-4351-8f82-7b0122ab7f8b

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #11601

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.

https://github.com/user-attachments/assets/ab52d829-2bc2-4687-a379-a4bc63a7af05

- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

- [ ] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
	- Enhanced click interactions for organization and location nodes, allowing for seamless selection and expansion in one action.
	- Updated location selection behavior to no longer auto-expand parent locations, providing a more focused navigation experience.

### CODE REVIEW

File: src/pages/Facility/settings/organizations/components/FacilityOrganizationNavbar.tsx [hunk 1]
```diff
@@ -54,14 +54,20 @@ function OrganizationTreeNode({
           isSelected && "bg-blue-100 text-blue-800",
         )}
         style={{ paddingLeft: `${level}rem` }}
+        onClick={(_e) => {
```
Comment (rithviknishad) [inline src/pages/Facility/settings/organizations/components/FacilityOrganizationNavbar.tsx]:
```suggestion
        onClick={() => {
```

File: src/pages/Facility/settings/organizations/components/FacilityOrganizationNavbar.tsx [hunk 2]
```diff
@@ -54,14 +54,20 @@ function OrganizationTreeNode({
...
       >
         {organization.has_children ? (
           <Button
             variant="ghost"
             size="icon"
             className="h-6 w-6"
-            onClick={(e) => {
-              e.stopPropagation();
+            onClick={(_e) => {
+              _e.stopPropagation();
```
Comment (rithviknishad) [inline src/pages/Facility/settings/organizations/components/FacilityOrganizationNavbar.tsx]: why?
```suggestion
            onClick={(e) => {
              e.stopPropagation();
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]
let's also do the same for Encounter's locations page.


image

**Comment by Jeffrin2005** [comment]
@rithviknishad Updated the Encounter's locations page, but not able to test it, bcoz it does not contain other sub locations.

**Comment by rithviknishad** [comment]
why don't you create sub locations? 🤔

**Comment by Jeffrin2005** [comment]
@rithviknishad 
I am not able to locate the button to create the sub location.
Can you share where to create the sub-location : ) 

fixing

**Comment by Jeffrin2005** [comment]
@rithviknishad do i need to update in location in maps , bcoz in Encounters page i could able to create the sub location 
t4

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan Now expanding the sub options is implemented in location and departments.
Any changes needed ? 

https://github.com/user-attachments/assets/911d5595-3e60-420e-97b4-c31e5fa6781e


https://github.com/user-attachments/assets/ea80ddd8-9f5a-42a5-a5b9-19157678c25d

**Comment by Jacobjeevan** [comment]
That behavior isn't correct.

Right now, if there's children, it expands to show direct children. However if not, clicking on it results to redirecting to the dept/team page.

Ideally, we want both to happen - redirect and expand when applicable.

**Comment by Jeffrin2005** [comment]
@Jacobjeevan 
In Organization it is working correctly,


https://github.com/user-attachments/assets/c8db5aeb-c1a0-4b10-be3f-57ad1c624b95




 but in location it is not working correct, why it is not working , am i did anythign wrong ?  only clicking the arrow icon it is expanding , but collpasing is working perfectly.
🤔

https://github.com/user-attachments/assets/5868a05f-5cc7-4212-922b-cd665a6a8db6

**Comment by Jeffrin2005** [comment]
@Jacobjeevan 
@Jacobjeevan 
In Organization it is working correctly,


https://github.com/user-attachments/assets/c8db5aeb-c1a0-4b10-be3f-57ad1c624b95




 but in location it is not working correct, why it is not working , am i did anything wrong 🤔?  only clicking the arrow icon it is collpasing, but expanding is working perfectly.



https://github.com/user-attachments/assets/45f4fad0-df29-43db-a34d-cf2f473ab063

**Comment by Jeffrin2005** [comment]
@rithviknishad  @Jacobjeevan
In Organization it is working correctly,


https://github.com/user-attachments/assets/c8db5aeb-c1a0-4b10-be3f-57ad1c624b95




 but in location it is not working correctly, why it is not working , am i did anything wrong 🤔?  only clicking the arrow icon it is collpasing, but expanding is working perfectly.



https://github.com/user-attachments/assets/45f4fad0-df29-43db-a34d-cf2f473ab063

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
