### PR TITLE
Fix user add page checkUsername function

### LINKED ISSUE #4132: Username check issue in User Add page
**Describe the bug**
When you're checking for the availability of a username, it shows "username is available" in red in case it is not available.

**To Reproduce**

1. Try creating a user
2. Fill in a username that already exists, for example "devdistrictadmin"
3. You will see in red "username is available"

**Expected behavior**
It should show username is not available.

**Screenshots**
Screenshot 2022-11-27 at 10 50 13 PM

### PR DESCRIPTION
**Pull request by siddnikh**
- Fixes #4132
Modified UserAdd.tsx file to display "Username is not available" when username already exists.

### CODE REVIEW

File: src/Components/Users/UserAdd.tsx [hunk 1]
```diff
@@ -709,10 +709,24 @@ export const UserAdd = (props: UserProps) => {
                               <i className="fas fa-circle-dot" /> checking...
                             </span>
                           ) : (
-                            validateRule(
-                              usernameExists !== userExistsEnums.exists,
-                              "Username is available"
-                            )
+                            <>
+                              " "
```
Comment (Ashesh3) [inline src/Components/Users/UserAdd.tsx]:
```suggestion

```
This seems unnecessary.
image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@siddnikh can you merge this with the develop branch and after merging if cypress fails, please do resolve that

**Review by khavinshankar — APPROVED** [review]
