### PR TITLE
Fix: Location Association Sheet Search Bar Filtering and Blank Sheet on second time opening same sheet

### LINKED ISSUE #11762: Manage Location Association Filtering in not working
**Describe the bug**

In the location association, even though the API is fired, the list in the UI is not being filtered in the encounter page 

**To Reproduce**

**Expected behavior**

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### LINKED ISSUE #11771: Disable `Schedule for later`  button in Location Association Sheet when no bed is selected
**Describe the bug**
Disable `Schedule for later ` button in Location Association Sheet when no bed is selected

Image

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### LINKED ISSUE #11871: Bug: Encounter Location Association Sheet Not Showing Locations on Reopen
###  Description

When associating a location in the **Encounter Location Association** sheet, the list of available locations appears correctly on the first open. However, upon closing and reopening the sheet (e.g., for another encounter or second time), the list of locations does **not** show up.

### 🔁 Steps to Reproduce

1. Open an encounter.
2. Click on the Add Location button to open the sheet.
3. Locations appear as expected.
4. Close the sheet.
5. Reopen the sheet for the same or another encounter.
6. Notice the locations are no longer shown.

###  Expected Behaviour

The list of available locations should appear **every time** the sheet is opened, regardless of how many times it has been accessed.

### Screen - Recording of Bug
https://github.com/user-attachments/assets/ba76802e-ac9d-4288-a3ea-97334593d311

### Additional Context 

Originally reported by @Tanuj1718 

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #11762
- Fixes #11771
- Fixes #11871
- Added queryParam for name while querying the data
- Empty state handling for beds data , location data and location history
- Disable Schedule for Later button when no bed is selected 

@ohcnetwork/care-fe-code-reviewers

https://github.com/user-attachments/assets/ea885a43-d6ff-4062-a16f-b80edb609592

https://github.com/user-attachments/assets/23eefc0d-931c-469e-a85e-3b7295b8cc7a

https://github.com/user-attachments/assets/06a58cf1-1b41-40ec-8237-c5103421943a

Screenshot 2025-04-09 at 5 08 31 PM

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Enhanced localization with new messages for "No available beds found," "No beds found," and "No location history available."
  - Added user feedback for scenarios with no locations, beds, or location history available.
  - Improved bed selection interface by disabling scheduling and assignment buttons when no bed is selected.
  - Updated beds section to show messages when no beds are available based on filters.

- **Bug Fixes**
  - Refined search filtering for locations and beds to improve matching accuracy.
  - Improved component rendering to gracefully handle empty beds and locations lists, preventing unnecessary UI elements from displaying.

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by AdityaJ2305** [comment]
@rithviknishad , needs a add empty state it is also missing just going for lunch that's why converted it into draft 😅

**Comment by rithviknishad** [comment]
> @rithviknishad , needs a add empty state it is also missing just going for lunch that's why converted it into draft 😅

alright; nice find!

**Comment by AdityaJ2305** [comment]
Re-requesting review since more changes have been pushed

**Review by rithviknishad — APPROVED** [review]

**Review by abhimanyurajeesh — APPROVED** [review]

**Comment by abhimanyurajeesh** [comment]
@AdityaJ2305 
If possible, could you please add some padding to this? The goal is to make sure that:
* The search bar doesn’t break
* The scrollbar doesn’t affect the content layout


image

File: src/components/Location/LocationNavigation.tsx [hunk 1]
```diff
@@ -87,6 +87,17 @@ export function LocationNavigation({
           </div>
         </div>
 
+        {!isLoadingLocations && !selectedLocation && locations.length === 0 && (
+          <div className="text-center text-gray-500 text-sm py-4">
+            {t("no_locations_found")}
+          </div>
+        )}
+
+        {!isLoadingBeds && selectedLocation && beds.length === 0 && (
```
Comment (Jacobjeevan) [inline src/components/Location/LocationNavigation.tsx]: let's adjust this, check the behavior when there are beds but none are available.

User can still see list of beds, but on toggle we switch to this message, which looks weird from that view.

- Adjust the check at line 130
- Add check for rendering BedListing
    - show the message there if no beds are available

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Location/LocationNavigation.tsx (hunk 1 above)
Comment (Jacobjeevan) [reply src/components/Location/LocationNavigation.tsx]: image

Also change this heading from `available beds` to `beds`

Comment (AdityaJ2305) [reply src/components/Location/LocationNavigation.tsx]: https://github.com/user-attachments/assets/d865d447-4ecc-4fc5-9d8b-b9a5aacffc41

File: src/components/Location/LocationNavigation.tsx [hunk 2]
```diff
@@ -135,7 +138,15 @@ export function LocationNavigation({
             </div>
 
             <BedStatusLegend />
-
+            {!isLoadingBeds && beds.length === 0 && (
```
Comment (AdityaJ2305) [inline src/components/Location/LocationNavigation.tsx:135]: Team, I’m a bit unsure here — should I move all of this to BedListing?

File: src/components/Location/BedListing.tsx [hunk 3]
```diff
@@ -17,6 +17,7 @@ export function BedListing({
   onBedSelect,
   onCheckStatus,
 }: BedListingProps) {
+  if (beds.length === 0) return null;
```
Comment (Jacobjeevan) [inline src/components/Location/BedListing.tsx:20]:
```suggestion
  if (beds.length === 0) return <></>;
```

File: src/components/Location/LocationNavigation.tsx [hunk 4]
```diff
@@ -146,7 +138,15 @@ export function LocationNavigation({
...
+              <div className="text-center text-gray-500 text-sm py-4">
```
Comment (Jacobjeevan) [inline src/components/Location/LocationNavigation.tsx]: I'd suggest adjusting the styling a bit - adding extra top padding might be enough, but check how it would look with a background+border (something similar to the bed layout, but spanning the entire width) wrapping the text.

File: src/components/Location/LocationNavigation.tsx (hunk 2 above)
Comment (Jacobjeevan) [reply src/components/Location/LocationNavigation.tsx:135]: it's fine here 👍

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Location/LocationNavigation.tsx (hunk 4 above)
Comment (AdityaJ2305) [reply src/components/Location/LocationNavigation.tsx]: Screenshot 2025-04-09 at 5 08 31 PM

File: public/locale/en.json [hunk 5]
```diff
@@ -1837,9 +1839,10 @@
   "no_linked_facilities": "No Linked Facilities",
   "no_location": "No location assigned",
   "no_location_description": "This device is not currently assigned to any location",
+  "no_location_history_available": "No Location History Available",
   "no_locations": "No locations",
   "no_locations_available": "No locations available",
-  "no_locations_found": "No locations found",
+  "no_locations_found": "No Locations Found",
```
Comment (rithviknishad) [inline public/locale/en.json]: why?

```suggestion
  "no_locations_found": "No locations found",
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by Jacobjeevan — COMMENTED** [review]
What do you think @nihal467? Would this cause confusion? 🤔  There could be locations where there's common beds but with an attached room, no?

image

image

image

**Comment by Jacobjeevan** [comment]
I talked to Nihal; let's not have the "No locations found" at all. So locations will be displayed if they are available, beds component will be displayed regardless (with beds or no beds message).

**Comment by AdityaJ2305** [comment]
@Jacobjeevan , If I'm getting it right , Just need to rm the no_location_found condition handling right ?

File: src/components/Location/LocationSheet.tsx [hunk 6]
```diff
@@ -177,6 +179,7 @@ export function LocationSheet({
           limit: ITEMS_PER_PAGE,
           offset: (bedsPage - 1) * ITEMS_PER_PAGE,
           mode: "instance",
+          name: searchTerm,
           parent: selectedLocation?.id,
           available: showAvailableOnly ? "true" : undefined,
           ...(!selectedLocation ? { mine: true } : {}),
```
Comment (Jacobjeevan) [inline src/components/Location/LocationSheet.tsx:185]: this shouldn't be needed anymore, no?

**Review by Jacobjeevan — APPROVED** [review]

File: src/components/Location/LocationSheet.tsx (hunk 6 above)
Comment (AdityaJ2305) [reply src/components/Location/LocationSheet.tsx:185]: Why? 🤔

**Comment by nihal467** [comment]
LGTM

File: public/locale/en.json [hunk 7]
```diff
@@ -1836,9 +1836,11 @@
   "no_appointments": "No appointments found",
   "no_attachments_found": "This communication has no attachments.",
   "no_availabilities_yet": "No availabilities yet",
+  "no_available_beds_found": "No Available Beds Found",
```
Comment (khavinshankar) [inline public/locale/en.json]:
```suggestion
  "no_available_beds_found": "No available beds found",
```

Lets try to keep the only the first letter of the sentence capital and rest small, If you want all the first letters of the word in a sentence to be in caps, consider using `capitalize` tailwind class name.

File: src/components/Location/BedListing.tsx [hunk 8]
```diff
@@ -17,6 +17,7 @@ export function BedListing({
   onBedSelect,
   onCheckStatus,
 }: BedListingProps) {
+  if (beds.length === 0) return <></>;
```
Comment (khavinshankar) [inline src/components/Location/BedListing.tsx]:
```suggestion
  if (beds.length === 0) return null;
```

consider using null for rendering nothing, usually fragments are meant for grouping.

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@AdityaJ2305 some minor cleanups

File: public/locale/en.json (hunk 7 above)
Comment (AdityaJ2305) [reply public/locale/en.json]: oh ok , no let's just go for lowercase

**Review by rithviknishad — APPROVED** [review]
other than the above, lgtm

**Comment by AdityaJ2305** [comment]
@khavinshankar Done
