### PR TITLE
fix : Hide delete button for group question if only one sub-question exists

### LINKED ISSUE #13248: Hide delete button for sub-question in a group if only one sub-question exists (Questionnaire Create Dashboard)
- On the Questionnaire Create Dashboard, each group question can contain one or more sub-questions. Currently, the delete button is shown even when there's only one sub-question in the group. This can lead to accidental deletion of the last remaining sub-question of a group.

_Originally posted by @nihal467 in https://github.com/ohcnetwork/care_fe/issues/13174#issuecomment-3150691359_

### PR DESCRIPTION
**Pull request by yadavshubham01**
## Proposed Changes

Fixes #13248 

## Screenshot 

https://github.com/user-attachments/assets/679c81ee-b0bc-49d8-bf00-1c567d2d74df

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

* **New Features**
  * Question actions dropdown is hidden for sub-questions when there is only one sibling.
  * Move up/down and delete actions are grouped together in the same dropdown with a separator; delete is now wired to the action.

* **Style**
  * Delete option uses a trash icon and a distinct destructive style for clarity.

### CODE REVIEW

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

**Comment by yadavshubham01** [comment]
@abhimanyurajeesh @rithviknishad need review

**Comment by yadavshubham01** [comment]
@abhimanyurajeesh  @rithviknishad @Jacobjeevan need review and testing

**Comment by yadavshubham01** [comment]
@rithviknishad @abhimanyurajeesh  need review

**Comment by yadavshubham01** [comment]
@rithviknishad @Jacobjeevan need review and testing

**Comment by nihal467** [comment]
LGTM

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 1]
```diff
@@ -1566,6 +1568,7 @@ function QuestionEditor({
   handleEnableWhenDependentClick,
   expandPath,
   questionRefs,
+  totalquestion,
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]: does not follow javascript naming conventions...

**Review by rithviknishad — DISMISSED** [review]

File: src/components/Questionnaire/QuestionnaireEditor.tsx (hunk 1 above)
Comment (yadavshubham01) [reply src/components/Questionnaire/QuestionnaireEditor.tsx]: done changed it to totalSiblings, which is easier to understand.

**Comment by yadavshubham01** [comment]
@rithviknishad @yash-learner need review

**Comment by yadavshubham01** [comment]
@rithviknishad @Jacobjeevan need review

**Comment by yadavshubham01** [comment]
Hey team @rithviknishad @abhimanyurajeesh @Jacobjeevan, could you please review this ?

**Review by abhimanyurajeesh — APPROVED** [review]

**Comment by yadavshubham01** [comment]
@rithviknishad @Jacobjeevan can you please review and merge this PR

**Review by Jacobjeevan — APPROVED** [review]
