### PR TITLE
Fix: Improve Mobile Responsiveness and Layout for Edit User Form

### LINKED ISSUE #10358: Mobile View UI: Edit User Form Needs Improved Layout and Responsive Styling
**Describe the bug**
The current UI design appears cluttered and lacks proper spacing and alignment, making it difficult for users to interact with form fields. This affects usability and user experience.

**To Reproduce**
[Click here to reproduce](https://care.ohc.network/facility/5c7bcf5d-c303-4529-88ee-dd41c602f294/users/devdistrictadmin)
See error

**Expected behavior**
All form fields should be easily accessible and spaced adequately to ensure a seamless user experience. The design should resemble the expected output, with proper padding, margin, and alignment of elements.

**Screenshots**

Image

Expected style

Image

also minor responsive issue

Image

**Desktop (please complete the following information):**
- OS: [windows]
- Browser [chrome]
- Version [132.0.6834.111]

**Additional context**

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes

- Fixes #10358 
- Change 1
- 
Screenshot 2025-02-01 221933

- Change 2

Old
Screenshot 2025-02-01 223607

Updated
Screenshot 2025-02-01 223648

@ohcnetwork/care
-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style**
  - Improved the layout of user form fields to better adapt to smaller screens.
  - Adjusted the spacing between elements on the schedule creation page for a cleaner mobile presentation.
  - Updated labels to prevent text wrapping in the schedule creation form.
  - Enhanced the date picker button and display logic for improved responsiveness and clarity based on screen size.

### CODE REVIEW

File: src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx [hunk 1]
```diff
@@ -431,7 +431,7 @@ export default function CreateScheduleTemplateSheet({
                         )}
                       /> */}
 
-                      <div className="flex items-center gap-4 col-span-2 md:col-span-1">
+                      <div className="flex items-center gap-1 sm:gap-4 col-span-2 md:col-span-1">
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx]: Does this look right?

image

Let's adjust the layout here as well, so that start/end time etc are all on their own lines for smaller devices.

You would need to adjust the icon are well - maybe ArrowDownIcon, test and see if that makes sense.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by modamaan** [comment]
Screenshot 2025-02-03 220952

**Comment by rithviknishad** [comment]
this doesn't look nice, the arrow is too small even though there is enough space for it to be bigger.

**Comment by modamaan** [comment]
@rithviknishad 
Screenshot 2025-02-03 224746

**Comment by modamaan** [comment]
old
Screenshot 2025-02-04 004417

updated
Screenshot 2025-02-04 010136

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
