### PR TITLE
Fixed bug with sidebar indicator

### LINKED ISSUE #8535: Sidebar bug on resize
image

To reproduce:
- Open care in mobile view (thinner viewport)
- Navigate through the sidebar
- Increase viewport width until the sidebar is visible.
- See bug

### PR DESCRIPTION
**Pull request by shivankacker**
## Proposed Changes

- Fixes #8535 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

File: src/Components/Common/Sidebar/Sidebar.tsx [hunk 1]
```diff
@@ -94,8 +94,17 @@ const StatelessSidebar = ({
...
     }
+  };
+
+  useEffect(() => {
+    updateIndicator();
   }, [activeLink, lastIndicatorPosition]);
 
+  useEffect(() => {
+    window.addEventListener("resize", updateIndicator);
+    return () => window.removeEventListener("resize", updateIndicator);
```
Comment (rithviknishad) [inline src/Components/Common/Sidebar/Sidebar.tsx]:
```suggestion
    addEventListener("resize", updateIndicator);
    return () => removeEventListener("resize", updateIndicator);
```

**Review by rithviknishad — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]
