### PR TITLE
Replace MaterialUI in FileUpload.tsx

### LINKED ISSUE #4977: Replace Material UI components in `src/Components/Patient/FileUpload.tsx`:
```tsx
2: import { CircularProgress, InputLabel } from "@material-ui/core";\n16: import LinearProgress from "@material-ui/core/LinearProgress";\n17: import Typography from "@material-ui/core/Typography";\n18: import Box from "@material-ui/core/Box";\n21: import Modal from "@material-ui/core/Modal";
```

### Tasks

Ensure all the below tasks are accomplished if applicable to the file being modified in the PR.

- [ ] Migrate all Material UI components to use new Care UI / custom components. (ref: [🛠️ Tailwinding Care](https://github.com/coronasafe/care_fe/issues/3742))
- [ ] Migrate all Material UI icons to use [🏥 **Care Icons**](https://github.com/coronasafe/care_fe/pull/4071).
- [ ] Migrate `PageTitle` to `Page` component if any. (See [example](https://github.com/coronasafe/care_fe/pull/4796/files#diff-8e39f154ccf13c9dedd0f968d21a0abbde450e88df9724a4e7d4264d487a7846))

For more information see the epic issue that tracks this issue.

### LINKED ISSUE #5540: Make buttons width consistent in mobile view of file section in patient consultation page
**Describe the bug**

In the file tab of patient consultation page, all the buttons are not in full width during responsive view

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/2f4ec032-6748-49f7-b637-f40d2351a9ce/patient/78aad99e-cb65-4756-9ec0-74a1282280c4/consultation/c7f49a18-af4a-4258-b927-a8a420d42342/files
2. See error

**Expected behavior**

in the mobile responsive view, the buttons in the file tab should be on constant full width

**Screenshots**

image

### PR DESCRIPTION
**Pull request by print-Sathvik**
### <samp>🤖 Generated by Copilot at 73b140d</samp>

This pull request refactors the FileUpload component to use custom components and the Page component, and adds a custom background color option to the DialogModal component. These changes aim to improve the performance, design, and maintainability of the application.

## Proposed Changes

- Fixes #4977 
- Fixes #5540 
- Replaced Material UI components with Care UI components

### Edit 29/06/2023:
- Made width of buttons same in mobile view
- Fixed the buttons overflowing from its parent component when page width is less(<1280px)
.
@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### <samp>🤖 Generated by Copilot at 73b140d</samp>

*  Refactor FileUpload component to use custom components instead of Material UI components and legacy components, and to match the design specifications ([link](https://github.com/coronasafe/care_fe/pull/5720/files?diff=unified&w=0#diff-6624210f1e9cdff909251ba965fafd78918e3d0a95fb569b8f151e8528eca8b6L2-R2), [link](https://github.com/coronasafe/care_fe/pull/5720/files?diff=unified&w=0#diff-6624210f1e9cdff909251ba965fafd78918e3d0a95fb569b8f151e8528eca8b6L15-R16), [link](https://github.com/coronasafe/care_fe/pull/5720/files?diff=unified&w=0#diff-6624210f1e9cdff909251ba965fafd78918e3d0a95fb569b8f151e8528eca8b6L76-R83), [link](https://github.com/coronasafe/care_fe/pull/5720/files?diff=unified&w=0#diff-6624210f1e9cdff909251ba965fafd78918e3d0a95fb569b8f151e8528eca8b6L1117-R1120), [link](https://github.com/coronasafe/care_fe/pull/5720/files?diff=unified&w=0#diff-6624210f1e9cdff909251ba965fafd78918e3d0a95fb569b8f151e8528eca8b6L1214-R1215), [link](https://github.com/coronasafe/care_fe/pull/5720/files?diff=unified&w=0#diff-6624210f1e9cdff909251ba965fafd78918e3d0a95fb569b8f151e8528eca8b6L1509-R1618))
* Replace PageTitle component with Page component in FileUpload component and its subcomponents, to use a more consistent and flexible layout for the pages ([link](https://github.com/coronasafe/care_fe/pull/5720/files?diff=unified&w=0#diff-6624210f1e9cdff909251ba965fafd78918e3d0a95fb569b8f151e8528eca8b6L38-R35), [link](https://github.com/coronasafe/care_fe/pull/5720/files?diff=unified&w=0#diff-6624210f1e9cdff909251ba965fafd78918e3d0a95fb569b8f151e8528eca8b6L1496-R1497), [link](https://github.com/coronasafe/care_fe/pull/5720/files?diff=unified&w=0#diff-6624210f1e9cdff909251ba965fafd78918e3d0a95fb569b8f151e8528eca8b6L1634-R1708))
* Add conditional class name to DialogModal component, to allow customizing the background color by passing a `bg-` class name as a prop ([link](https://github.com/coronasafe/care_fe/pull/5720/files?diff=unified&w=0#diff-e6e4165d3f2ca6f2cad9355d41694f8e2002ef23fbecf3ef0350a25bbc766b55L57-R58))

### CODE REVIEW

File: src/Components/Common/Dialog.tsx [hunk 1]
```diff
@@ -54,7 +54,8 @@ const DialogModal = (props: DialogProps) => {
                   className={classNames(
                     className,
                     fixedWidth && "max-w-md w-full",
-                    "transform rounded-2xl bg-white p-6 text-left align-middle shadow-xl transition-all"
+                    className?.includes("bg-") || "bg-white",
```
Comment (rithviknishad) [inline src/Components/Common/Dialog.tsx]: Disallow overriding `bg-color`. This is to keep designs consistent.
```suggestion
```

File: src/Components/Patient/FileUpload.tsx [hunk 2]
```diff
@@ -1114,9 +1112,12 @@ export const FileUpload = (props: FileUploadProps) => {
 
   return (
     <div className={hideBack ? "py-2" : "p-4"}>
-      <Modal
-        open={file_state.open}
+      <DialogModal
```
Comment (rithviknishad) [inline src/Components/Patient/FileUpload.tsx]: Consider using a dedicated `Dialog` component say: `ImagePreviewDialog` with custom implementation for this instead of overriding the CareUI's Dialog component to have bg-transparent and all.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Patient/FileUpload.tsx [hunk 3]
```diff
@@ -1114,9 +1112,12 @@ export const FileUpload = (props: FileUploadProps) => {
 
   return (
     <div className={hideBack ? "py-2" : "p-4"}>
```
Comment (rithviknishad) [inline src/Components/Patient/FileUpload.tsx:1084]: Remove this div and padding. It is now handled by `Page` component

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@rithviknishad @print-Sathvik 
image

- make all the button in full width in mobile view

**Comment by print-Sathvik** [comment]
> @rithviknishad @print-Sathvik image
> 
> * make all the button in full width in mobile view

That was taken up by many others in the issue #5540 So I left that on purpose. Should I assign that issue to myself and continue with that @nihal467 ?

**Comment by rithviknishad** [comment]
@print-Sathvik you can do it along with this PR and link that issue too.

**Comment by print-Sathvik** [comment]
Ok @rithviknishad , that's done. I noticed one more issue. Those buttons are overflowing when width is decreased. I will fix that and create a commit evening after going home

**Comment by nihal467** [comment]
@print-Sathvik @rithviknishad 
image

reduce the space between the textbox and button, make sure before you push fix, it looks good in both views

**Comment by rithviknishad** [comment]
@nihal467 that space is for the error for that field. In existing staging when error comes, layout shift happens. But layout shift is not good, hence new components automatically keeps the spacing consistent to prevent layout shifts.

**Comment by rithviknishad** [comment]
@print-Sathvik maybe we can add some spacing above the field so that it looks good in all views

File: src/Components/Patient/FileUpload.tsx [hunk 4]
```diff
@@ -1507,43 +1386,39 @@ export const FileUpload = (props: FileUploadProps) => {
...
           {audio ? (
             <div className="bg-white border rounded-lg shadow p-4">
               <div>
                 <h4>Record and Upload Audio File</h4>
               </div>
-              <InputLabel id="spo2-label">
-                Enter Audio File Name (optional)
-              </InputLabel>
-              <LegacyTextInputField
+              <TextFormField
```
Comment (rithviknishad) [inline src/Components/Patient/FileUpload.tsx:1394]:
```suggestion
              <TextFormField
                className="mt-4"
```

File: src/Components/Patient/FileUpload.tsx [hunk 5]
```diff
@@ -1568,35 +1448,33 @@ export const FileUpload = (props: FileUploadProps) => {
...
           {unspecified ? (
-            <div className="mt-4 md:mt-0 bg-white border rounded-lg shadow p-4">
+            <div className="mt-4 md:mt-0 bg-white border rounded-lg shadow p-4 flex-wrap">
               <div>
                 <h4>Upload New File</h4>
               </div>
               <div>
-                <InputLabel id="spo2-label">Enter File Name*</InputLabel>
-                <LegacyTextInputField
+                <TextFormField
```
Comment (rithviknishad) [inline src/Components/Patient/FileUpload.tsx]:
```suggestion
                <TextFormField
                  className="mt-4"
```

**Comment by nihal467** [comment]
@rithviknishad @print-Sathvik 

image

the above image is a mockup I made, can we have something similar?

**Comment by print-Sathvik** [comment]
Ok @nihal467 , will do that tonight

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
