### PR TITLE
fixes overflow issues in consultation dashboard

### LINKED ISSUE #7929: multiple overlapping issues in patient consultation page
**Describe the bug**

- [ ] manage patient dropdown is clipping in with the prescription module
- [ ] the normal badge is overlapping with the IP days badges, again after fixing it

**To Reproduce**

**Expected behavior**

**Screenshots**

image

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Fixes #7929

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

File: src/Components/Common/components/Menu.tsx [hunk 1]
```diff
@@ -52,7 +52,7 @@ export default function DropdownMenu({
         </Menu.Button>
         <DropdownTransition>
           <Menu.Items
-            className={`absolute right-0 z-10 mt-2 min-w-full origin-top-right rounded-lg bg-white py-1 shadow-lg ring-1 ring-black/5 focus:outline-none sm:min-w-[250px] md:w-max ${props.itemClassName}`}
+            className={`absolute right-0 mt-2 min-w-full origin-top-right rounded-lg bg-white py-1 shadow-lg ring-1 ring-black/5 focus:outline-none sm:min-w-[250px] md:w-max ${props.itemClassName}`}
```
Comment (rithviknishad) [inline src/Components/Common/components/Menu.tsx]:
```suggestion
            className={`absolute right-0 z-10 mt-2 min-w-full origin-top-right rounded-lg bg-white py-1 shadow-lg ring-1 ring-black/5 focus:outline-none sm:min-w-[250px] md:w-max ${props.itemClassName}`}
```

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
