### PR TITLE
fixed department  description overflow properly

### LINKED ISSUE #11167: BUG:Department Description Overflows or Breaks Layout
**Describe the bug**
When the department description is too long, the UI does not handle it properly, leading to layout issues. This could cause elements to break, overlap, or become unreadable.

**To Reproduce**

1. Go to 'setting'
2. Click on 'department tab'
3. check the department with long description

**Expected behavior**
The text should be properly wrapped or truncated with a "Read More" option if necessary

**Screenshots**

https://github.com/user-attachments/assets/2c6725ea-af7b-43d2-b885-463b7744540a

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Vikaspal8923**
## Proposed Changes
 
- Fixes #11167
- Remove line-clamp-2 to prevent truncation and add break-all for proper wrapping.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [X] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
	- Minor adjustment to the rendering of organization descriptions by refining class attributes, ensuring consistent display without affecting functionality or visual presentation.

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]

File: src/pages/Facility/settings/organizations/components/FacilityOrganizationLayout.tsx [hunk 1]
```diff
@@ -138,7 +138,7 @@ export default function FacilityOrganizationLayout({
       >
         <div className="mt-2">
           {org.description && (
-            <p className="text-sm text-gray-500 line-clamp-2">
+            <p className="text-sm text-gray-500 break-all whitespace-normal ">
```
Comment (rithviknishad) [inline src/pages/Facility/settings/organizations/components/FacilityOrganizationLayout.tsx]:
```suggestion
            <p className="text-sm text-gray-500 break-all whitespace-normal">
```

**Review by rithviknishad — DISMISSED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
