### PR TITLE
displaying full names on hover for long names only

### LINKED ISSUE #7787: Lengthy asset name is not properly handled in asset list page
**Describe the bug**

When we have bigger asset names, they are hidden few characters, even if we have enough white space

**To Reproduce**

1. Go to asset tab
2. create asset with wider lengthy names
3. See error

**Expected behavior**

- [ ] if space is available, based on the screen size, show the full asset names
- [ ] in the cases, due to limited space, if we are hiding part of the asset name with "...", add a tooltip to the asset name, if user hover over it, they can view the full name of the asset in the tooltip

**Screenshots**

image

### PR DESCRIPTION
**Pull request by SwanandBhuskute**
## Proposed Changes

- Fixes #7787
- Displaying asset names for long names only
- asset.name > 18 seems logical considering w-48 remains constant, but if we change w-48 to some other value, we can increase 18 to something else, but don't think w-48 will change, even if it does, we can adjust 18 to some sensible mid-number like 15-16

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Introduced a tooltip for asset names that exceed 20 characters, providing full visibility without cluttering the interface.

- **Bug Fixes**
	- Improved error handling for QR code processing, ensuring consistent management of the loading state and clarity in error notifications.

### CODE REVIEW

**Comment by gigincg** [comment]
@SwanandBhuskute Can you add links to example assets where the feature can be seen in action? Also attach Before and After Screenshots

**Comment by SwanandBhuskute** [comment]
> @SwanandBhuskute Can you add links to example assets where the feature can be seen in action? Also attach Before and After Screenshots

https://care.ohc.network/assets
the feature can be seen into action on this route
currently this is how it works on localhost

Before hovering:
image

After hovering
image


optional working video

https://github.com/user-attachments/assets/491afe27-de5e-42ba-8840-e5a3331311ee

**Review by rithviknishad — CHANGES_REQUESTED** [review]
1. let's not use css when tailwind classes can achieve the same.
2. have a look at how tooltip's shown in other places in care. We have a custom CSS class defined to show tooltips. Utilise those classes instead.

https://github.com/ohcnetwork/care_fe/blob/5877d9b32c8f6e0d6c65d453e7d60ea8a8b3bba5/src/style/CAREUI.css#L36

**Comment by SwanandBhuskute** [comment]
> Member
> ###

so I should do changes in CAREUI.css file?

**Comment by rithviknishad** [comment]
> so I should do changes in CAREUI.css file?

No why? Just use those classes like how it's used in other places to show tooltips.

**Comment by SwanandBhuskute** [comment]
> > so I should do changes in CAREUI.css file?
> 
> No why? Just use those classes like how it's used in other places to show tooltips.



Using tooltip and tooltip-top classes
the hover doesn't position that good 
image

so using tailwind only, to achieve same effect as earlier without extra style attribute inside <span>

**Comment by rithviknishad** [comment]
@SwanandBhuskute you can use it in conjuction with `translate-*` classes to control where it's positioned like how it's done in most other usages of the tooltip classes.

**Comment by SwanandBhuskute** [comment]
> @SwanandBhuskute you can use it in conjuction with `translate-*` classes to control where it's positioned like how it's done in most other usages of the tooltip classes.

@rithviknishad i have done as you said, kindly review

File: src/components/Assets/AssetsList.tsx [hunk 1]
```diff
@@ -240,12 +240,19 @@ const AssetsList = () => {
                       className="text-2xl"
                     />
                   </span>
-                  <p
-                    className="w-48 truncate"
-                    data-testid="created-asset-list-name"
-                  >
-                    {asset.name}
-                  </p>
+                  <div className="tooltip group relative w-48">
```
Comment (rithviknishad) [inline src/components/Assets/AssetsList.tsx]:
```suggestion
                  <div className="tooltip w-48">
```

File: src/components/Assets/AssetsList.tsx [hunk 2]
```diff
@@ -240,12 +240,19 @@ const AssetsList = () => {
...
+                    <p
+                      className="truncate"
+                      data-testid="created-asset-list-name"
+                    >
+                      {asset.name}
+                    </p>
+                    {asset.name.length > 20 && (
+                      <span className="tooltip-text tooltip-top absolute z-10 -translate-x-1/2 whitespace-nowrap rounded bg-gray-700 px-2 py-1 text-xs text-white group-hover:block">
```
Comment (rithviknishad) [inline src/components/Assets/AssetsList.tsx]:
```suggestion
                      <span className="tooltip-text tooltip-top -translate-x-1/2">
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]
the tooltip classes already applies most of the classes required for you, skip repeating it.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
