### PR TITLE
Fix location search not working in Record Credit Note sheet

### LINKED ISSUE #15723: Bug: Location search is not working in the Record Credit Note sheet

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Proposed Changes

Fix #15723

image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **New Features**
  * Enhanced location picker search: typing now filters results using server-side search so relevant locations appear faster and more accurately.
  * Behavior unchanged for integration: how the picker is used in the UI remains the same, only search-driven result updates were added.

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

File: src/components/Location/LocationPicker.tsx [hunk 1]
```diff
@@ -69,13 +69,14 @@ export function LocationPicker({
...
   } = useQuery({
-    queryKey: ["locations", facilityId, currentParent, "kind"],
+    queryKey: ["locations", facilityId, currentParent, "kind", searchQuery],
     queryFn: query(locationApi.list, {
       pathParams: { facility_id: facilityId },
       queryParams: {
         parent: currentParent ? currentParent : undefined,
         mode: "kind",
         ordering: "sort_index",
+        name: searchQuery,
```
Comment (Jacobjeevan) [inline src/components/Location/LocationPicker.tsx]:
```suggestion
        name: searchQuery || undefined,
```

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Review by gigincg — APPROVED** [review]

**Review by bodhish — APPROVED** [review]
