### PR TITLE
fix: Add cancel button and disable save button

### LINKED ISSUE #10920: Updation and Creation of devices needs cancel button
**Describe the bug**
1. There is no cancel button in 'Edit Device' and 'Add Device' page.
2. Save button is enable even if we are not doing any chages.

**To Reproduce**

1. Go to [https://care.ohc.network/facility/c6f0c78e-6d22-405f-b45d-e34a4f0625ec/settings/devices/8a6ab1e0-29ee-4b61-b2fd-94a37a10e895/edit](url)
2. Check for cancel button and also save button is enabled
3. Go to [https://care.ohc.network/facility/c6f0c78e-6d22-405f-b45d-e34a4f0625ec/settings/devices/create](url)
4. There is no cancel button in this page also

**Expected behavior**
There should be cancel button for both pages and save button should be disabled if we don't do any changes

**Screenshots**

https://github.com/user-attachments/assets/166b6737-b236-48f3-9bc4-2a44e9e06d4b

### PR DESCRIPTION
**Pull request by Tanuj1718**
## Proposed Changes

- Fixes #10920
- Disable save button if user does not do any update
- Add cancel button for 'Add Device' and 'Edit Device'

https://github.com/user-attachments/assets/0b4475fe-60a6-45a5-bd9a-d9b9289215f2

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Introduced an enhanced device management form with a clearly styled cancel button that allows users to navigate back easily.
	- Improved the form submission experience by disabling the submit button when no changes have been made.

- **Refactor**
	- Replaced the native browser history method with a custom navigation hook for improved navigation logic.

### CODE REVIEW

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx [hunk 1]
```diff
@@ -458,10 +467,20 @@ export default function DeviceForm({ facilityId, device, onSuccess }: Props) {
...
             {isPending ? t("saving") : t("save")}
           </Button>
+          <Button
+            variant="outline"
+            className="m-4"
+            onClick={() =>
+              goBack(`/facility/${facilityId}/settings/devices/${deviceId}`)
+            }
+          >
+            <CareIcon icon="l-arrow-left" className="h-4 w-4" />
```
Comment (rithviknishad) [inline src/pages/Facility/settings/devices/components/DeviceForm.tsx]: let's not have icon

File: src/pages/Facility/settings/devices/UpdateDevice.tsx [hunk 2]
```diff
@@ -39,6 +39,7 @@ export default function UpdateDevice({ facilityId, deviceId }: Props) {
           <DeviceForm
             facilityId={facilityId}
             device={device}
+            deviceId={deviceId}
             onSuccess={() => {
               window.history.back();
             }}
```
Comment (rithviknishad) [inline src/pages/Facility/settings/devices/UpdateDevice.tsx]: let's use `goBack` from useAppHistory instead here

File: src/pages/Facility/settings/devices/UpdateDevice.tsx [hunk 3]
```diff
@@ -39,6 +39,7 @@ export default function UpdateDevice({ facilityId, deviceId }: Props) {
           <DeviceForm
             facilityId={facilityId}
             device={device}
+            deviceId={deviceId}
```
Comment (rithviknishad) [inline src/pages/Facility/settings/devices/UpdateDevice.tsx]: why pass `deviceId`? doesn't `device` object already have an `id`?

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx [hunk 4]
```diff
@@ -458,10 +467,19 @@ export default function DeviceForm({ facilityId, device, onSuccess }: Props) {
...
-          <Button type="submit" disabled={isPending}>
+        <div className="flex items-center justify-end">
+          <Button type="submit" disabled={isPending || !form.formState.isDirty}>
             {isPending ? t("saving") : t("save")}
           </Button>
+          <Button
+            variant="outline"
+            className="m-4"
+            onClick={() =>
+              goBack(`/facility/${facilityId}/settings/devices/${deviceId}`)
```
Comment (rithviknishad) [inline src/pages/Facility/settings/devices/components/DeviceForm.tsx]: this is invalid, if deviceId is undefined, it's going to navigate to an invalid URL

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — CHANGES_REQUESTED** [review]
i'd recommend adding a `onCancel` to the `DeviceForm` as prop instead.

This is a reusable component and hard to predict the fallback URL

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx (hunk 4 above)
Comment (Tanuj1718) [reply src/pages/Facility/settings/devices/components/DeviceForm.tsx]: yeah got it.

**Comment by Tanuj1718** [comment]
> i'd recommend adding a `onCancel` to the `DeviceForm` as prop instead.
> 
> This is a reusable component and hard to predict the fallback URL

Yeah I have updated in my code but not able to test since I am getting server error(404). It is also present in live url , not only in my localhost. 
EDIT: I have solved it with different approach, let we know if it needs some changes. I have added checks for deviceId so that it can not navigate to the invalid URL.

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx (hunk 4 above)
Comment (Tanuj1718) [reply src/pages/Facility/settings/devices/components/DeviceForm.tsx]: @rithviknishad Can we do it with this approach? Same is done in patient registration form but here I have added checks which will handle the undefined case.

Screenshot 2025-03-03 at 6 34 33 PM

**Comment by Jacobjeevan** [comment]
@Tanuj1718 What's the status here?

**Comment by Tanuj1718** [comment]
> @Tanuj1718 What's the status here?

I have solved it with different approach. I have added checks for deviceId so that it can not navigate to the invalid URL (we have done similar type in PatientRegistration) . Is it correct?

screenshot1

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx [hunk 5]
```diff
@@ -77,6 +79,7 @@ const formSchema = z
 interface Props {
   facilityId: string;
   device?: DeviceList;
+  deviceId?: string;
```
Comment (rithviknishad) [inline src/pages/Facility/settings/devices/components/DeviceForm.tsx]: why?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx (hunk 5 above)
Comment (Tanuj1718) [reply src/pages/Facility/settings/devices/components/DeviceForm.tsx]: i forgot to clean it

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx [hunk 6]
```diff
@@ -458,10 +461,23 @@ export default function DeviceForm({ facilityId, device, onSuccess }: Props) {
           ))}
         </div>
 
-        <div className="flex justify-end gap-4">
-          <Button type="submit" disabled={isPending}>
+        <div className="flex items-center justify-end">
+          <Button type="submit" disabled={isPending || !form.formState.isDirty}>
             {isPending ? t("saving") : t("save")}
           </Button>
+          <Button
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/devices/components/DeviceForm.tsx:475]: Cancel before submit button

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/devices/UpdateDevice.tsx [hunk 7]
```diff
@@ -40,7 +43,7 @@ export default function UpdateDevice({ facilityId, deviceId }: Props) {
             facilityId={facilityId}
             device={device}
             onSuccess={() => {
-              window.history.back();
+              goBack();
```
Comment (rithviknishad) [inline src/pages/Facility/settings/devices/UpdateDevice.tsx]: let's add a fallback url

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx [hunk 8]
```diff
@@ -458,8 +461,21 @@ export default function DeviceForm({ facilityId, device, onSuccess }: Props) {
...
         </div>
 
-        <div className="flex justify-end gap-4">
-          <Button type="submit" disabled={isPending}>
+        <div className="flex items-center justify-end">
+          <Button
+            variant="outline"
+            className="m-4"
+            onClick={() => {
+              if (device?.id) {
```
Comment (rithviknishad) [inline src/pages/Facility/settings/devices/components/DeviceForm.tsx]: why?

```suggestion
              if (device) {
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx (hunk 8 above)
Comment (Tanuj1718) [reply src/pages/Facility/settings/devices/components/DeviceForm.tsx]: My bad. I was testing something and forgot to change it.

File: src/pages/Facility/settings/devices/UpdateDevice.tsx (hunk 7 above)
Comment (Tanuj1718) [reply src/pages/Facility/settings/devices/UpdateDevice.tsx]: Done

Screenshot 2025-03-06 at 1 54 58 PM

**Review by Jacobjeevan — APPROVED** [review]
LGTM.

Modified bit of styling for smaller devices:

image

For larger devices, maintained the same look as before:

image
