### PR TITLE
fixed department layout

### LINKED ISSUE #13057: Add Resizable feature for Dept/team listing page
**Describe**

Image

**Expected behavior**
Refer to resizable feature present for organization subtabs in Admin Dashboard page

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by StephZam**
## Proposed Changes

Fixes #13057 

Changes requested - cc: @abhimanyurajeesh 
@nihal467 

image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Style**
  * Refined spacing, padding and container widths for improved layout and alignment
  * Adjusted search bar and navbar widths; reduced placeholder/skeleton sizes for a cleaner interface
  * Minor visual tweaks to action cell and loading/empty-state appearance

* **Behavior**
  * Increased items per page from 12 to 14, updating pagination and page counts
  * Top-level organization list capped at 100 items to limit initial results displayed

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by abhimanyurajeesh — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/pages/Facility/settings/organizations/FacilityOrganizationView.tsx [hunk 1]
```diff
@@ -187,7 +187,7 @@ export default function FacilityOrganizationView({
 }: Props) {
   const { t } = useTranslation();
   const { qParams, Pagination, resultsPerPage, updateQuery } = useFilters({
-    limit: 12,
+    limit: 9,
```
Comment (bodhish) [inline src/pages/Facility/settings/organizations/FacilityOrganizationView.tsx]: Why tho?

**Review by bodhish — DISMISSED** [review]

File: src/pages/Facility/settings/organizations/FacilityOrganizationView.tsx (hunk 1 above)
Comment (StephZam) [reply src/pages/Facility/settings/organizations/FacilityOrganizationView.tsx]: to make it similar to locations height

File: src/pages/Facility/settings/organizations/components/FacilityOrganizationNavbar.tsx [hunk 2]
```diff
@@ -130,6 +130,7 @@ export default function FacilityOrganizationNavbar({
         pathParams: { facilityId },
         queryParams: {
           parent: "",
+          limit: 100,
```
Comment (rithviknishad) [inline src/pages/Facility/settings/organizations/components/FacilityOrganizationNavbar.tsx]: let's not do this...

**Review by rithviknishad — APPROVED** [review]

File: src/pages/Facility/settings/organizations/FacilityOrganizationView.tsx (hunk 1 above)
Comment (amjithtitus09) [inline src/pages/Facility/settings/organizations/FacilityOrganizationView.tsx]: @StephZam Switch limit to our default of 14. For location as well

**Review by amjithtitus09 — CHANGES_REQUESTED** [review]

**Review by amjithtitus09 — APPROVED** [review]
@StephZam Merging, but location list still shows 9. Also check if the location nav shows 100. Follow up PR
