### PR TITLE
Hide delete facility option for users who dont have access

### LINKED ISSUE #6608: Hide the Delete Facility for user who don't have access to do it
**Describe the bug**

Currently district admin and above have a delete facility button shown in the manage facility dropdown, even though they don't have permission to delete it

**To Reproduce**

1. Go to any facility
2. Click on manage facility
3. See error

**Expected behavior**

Hide the delete facility button for users, who don't have permission to do it

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Pranshu1902**
## Proposed Changes

- Fixes #6608 
Hide delete facility option for users who don't have access

Admin View:
image

Non admin view:
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

File: src/Components/Facility/FacilityHome.tsx [hunk 1]
```diff
@@ -372,16 +376,18 @@ export const FacilityHome = (props: any) => {
...
-                  Delete Facility
-                </DropdownItem>
+                {hasPermissionToDeleteFacility && (
+                  <DropdownItem
+                    id="delete-facility"
+                    variant="danger"
+                    onClick={() => setOpenDeleteDialog(true)}
+                    className="flex items-center gap-3"
+                    icon={<CareIcon className="care-l-trash-alt text-lg" />}
+                    authorizeFor={AuthorizeFor(["DistrictAdmin", "StateAdmin"])}
```
Comment (rithviknishad) [inline src/Components/Facility/FacilityHome.tsx]: This is no longer required as it's a redundant no-op. We are hiding the button, no point in disabling based on same logic. Since when it's visible it'll never be enabled either.

```suggestion
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — COMMENTED** [review]
LGTM, but the lint checks and cypress tests are failing

**Comment by Pranshu1902** [comment]
Fixed cypress and lint tests :heavy_check_mark:

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
