### PR TITLE
Fix: Pinch for zooming for image/file preview and dragging for img 

### LINKED ISSUE #12735: Bug: Pan not working on image/file preview after zoom on mobile
**Describe the bug**
On mobile devices, when previewing an image or document, users are able to zoom in, but cannot pan the file afterward. This results in a frustrating user experience as they are unable to navigate the zoomed content.

**To Reproduce**
1. Open an image file preview on a mobile device
2. Pinch to zoom in.
3. Try to pan (move around) the zoomed content — nothing happens.

**Expected behavior**
Users should be able to zoom and then pan around the content smoothly.  Enable both pinch-to-zoom and pan interactions for image/file preview on mobile.

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #12735 
- Added handlers like onTouchMove and onWheel
- fix existing handlers
- add dialogdescription to avoid warning

https://www.loom.com/share/1e46d2f8588c4e33b12ecbc0fa06fd16

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **New Features**
  * Added a button to open PDFs in a new browser tab from the file preview dialog.

* **Improvements**
  * Replaced custom image zoom and pan logic with a third-party library for smoother interactions.
  * Simplified touch and drag handling for PDFs and images.
  * Unified zoom and rotation state management within the file preview dialog.
  * Streamlined PDF viewer layout and container styling for better responsiveness.

### CODE REVIEW

File: src/components/Common/FilePreviewDialog.tsx [hunk 1]
```diff
@@ -276,48 +306,136 @@ const FilePreviewDialog = (props: FilePreviewProps) => {
...
+      setPinchState({
+        isPinching: true,
+        initialDistance: distance,
+        initialScale: file_state.isImage ? file_state.zoom / 4 : scale,
+        center,
+      });
+
+      setDragState((prev) => ({
+        ...prev,
+        isDragging: false,
```
Comment (rithviknishad) [inline src/components/Common/FilePreviewDialog.tsx]: isn't there any package that we could use to achieve this instead of writing by ourselves? 🤔

Comment (AdityaJ2305) [reply src/components/Common/FilePreviewDialog.tsx]: there is a package for img but for pdf there is no package I could find for free so should we go ahead for img and handle pdf seperately ?

**Review by abhimanyurajeesh — DISMISSED** [review]
**desktop**
image


image

lets use the same design format used for pdf, just replace the zoom% with the zoom reset.


image

same for the mobile view 

Zoom In     reset      Zoom out
rot left.                      rot right

**Comment by AdityaJ2305** [comment]
Screenshot 2025-07-11 at 1 24 38 PM
Screenshot 2025-07-11 at 1 24 56 PM

File: src/components/Common/FilePreviewDialog.tsx [hunk 2]
```diff
@@ -598,10 +509,12 @@ const FilePreviewDialog = (props: FilePreviewProps) => {
...
-                        icon: null,
-                        action: () => {},
-                        disabled: false,
+                        label: t("reset"),
+                        icon: "l-minus-circle",
+                        action: () => {
+                          setScale(0.75);
+                        },
+                        disabled: scale == 0.75,
                       },
```
Comment (abhimanyurajeesh) [inline src/components/Common/FilePreviewDialog.tsx]: why was this changed ?

**Review by abhimanyurajeesh — COMMENTED** [review]
taking over this PR

File: src/components/Common/FilePreviewDialog.tsx (hunk 2 above)
Comment (AdityaJ2305) [reply src/components/Common/FilePreviewDialog.tsx]: > just replace the zoom% with the zoom reset

File: src/components/Common/FilePreviewDialog.tsx [hunk 3]
```diff
@@ -572,7 +479,11 @@ const FilePreviewDialog = (props: FilePreviewProps) => {
                         variant="ghost"
                         key={index}
                         onClick={button.action}
-                        className="z-50 rounded bg-white/60 text-black backdrop-blur-sm transition hover:bg-white/70"
+                        className={cn(
+                          "z-50 rounded bg-white/60 text-black backdrop-blur-sm transition hover:bg-white/70",
+                          index == 3 && "col-start-1 md:col-auto",
+                          index == 4 && "col-start-3 md:col-auto",
```
Comment (rithviknishad) [inline src/components/Common/FilePreviewDialog.tsx]: this is not a maintainable approach to write code!

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Common/FilePreviewDialog.tsx [hunk 4]
```diff
@@ -398,55 +312,58 @@ const FilePreviewDialog = (props: FilePreviewProps) => {
...
-                onMouseLeave={handleMouseUp}
-                onTouchStart={handleTouchStart}
-                onTouchEnd={handleTouchEnd}
-              >
+
+              <div className="flex h-[50vh] md:h-[70vh] w-full items-center justify-center overflow-hidden rounded-lg border border-secondary-200">
                 {file_state.isImage ? (
+                  <TransformWrapper
+                    ref={transformRef}
+                    initialScale={0.5}
```
Comment (abhimanyurajeesh) [inline src/components/Common/FilePreviewDialog.tsx]:
```suggestion
                    initialScale={1}
```

**Comment by AdityaJ2305** [comment]
@Jacobjeevan , switching to transformer for pdf disables the selection of text over pdf

I should've mentioned that before

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by amjithtitus09 — APPROVED** [review]
