### PR TITLE
Fix : Show only unselected options in repeatable choice questions

### LINKED ISSUE #12583: Repeatable Choice Question: 'Add Another' displays all options instead of remaining unselected options
**Description**
When filling out a questionnaire that includes a Repeatable Choice type question, users can select multiple options by clicking "Add Another". However, after selecting an option and adding a new one, the dropdown still shows all available options, including the ones already selected. This can lead to duplicate selections, which should be avoided.

**Steps to Reproduce:**

- Open a questionnaire that contains a Repeatable Choice type question.
- Select an option from the dropdown.
- Click "Add Another" to add another choice.
- Observe that the new dropdown includes options that have already been selected.

**Expected Behavior:**
The new dropdown should only display options that have not yet been selected in previous entries of the same repeatable field.

**Actual Behavior:**
All options, including those already selected, are shown again.

### PR DESCRIPTION
**Pull request by sindhureddy-6**
## Proposed Changes

- Fixes #12583 

- Updated logic in repeatable choice questions so that the "Add Another" field only shows unselected options instead of all available ones.
- Modified `QuestionnaireResponseList` to ensure all selected options are displayed correctly in the response view.

https://github.com/user-attachments/assets/47479594-d374-4276-bfbe-52811ac0f429

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Improved display of repeated questionnaire responses by showing all selected values as a comma-separated list.
  - Enhanced repeated choice questions to prevent users from selecting the same option more than once across repeated entries.

### CODE REVIEW

File: src/components/Facility/ConsultationDetails/QuestionnaireResponsesList.tsx [hunk 1]
```diff
@@ -310,8 +310,9 @@ function ResponseCardContent({ item }: { item: QuestionnaireResponse }) {
                       (r) => r.question_id === question.id,
                     );
                     if (!response) return null;
-
-                    const value = response.values[0]?.value;
+                    const value = question.repeats
+                      ? response.values?.map((v) => v.value).join(", ")
+                      : response.values[0]?.value;
```
Comment (rithviknishad) [inline src/components/Facility/ConsultationDetails/QuestionnaireResponsesList.tsx]: we can always simply do `map` and `join` right? regardless of `repeats` variable being set or not?

if it's not repeatable, only 1 value would exist and map and join would simply return the first value's value only right?

correct me if i am wrong.

File: src/components/Questionnaire/QuestionTypes/ChoiceQuestion.tsx [hunk 2]
```diff
@@ -45,6 +45,19 @@ export const ChoiceQuestion = memo(function ChoiceQuestion({
...
+    ? questionnaireResponse.values
+        .map((v) => v.value?.toString())
+        .filter((v, i) => i !== index && v)
+    : [];
+
+  const availableOptions = question.repeats
+    ? options.filter(
+        (option) => !selectedValues.includes(option.value.toString()),
+      )
+    : options;
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionTypes/ChoiceQuestion.tsx]: can we consider simplifying this logic to achieve this in a single iteration? 🤔

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Facility/ConsultationDetails/QuestionnaireResponsesList.tsx (hunk 1 above)
Comment (sindhureddy-6) [reply src/components/Facility/ConsultationDetails/QuestionnaireResponsesList.tsx]: yes, you're correct.
it works when the question repeats also.

File: src/components/Questionnaire/QuestionTypes/ChoiceQuestion.tsx (hunk 2 above)
Comment (sindhureddy-6) [reply src/components/Questionnaire/QuestionTypes/ChoiceQuestion.tsx]: yes .we can simplify it

**Review by abhimanyurajeesh — COMMENTED** [review]
LGTM

**Review by rithviknishad — APPROVED** [review]
