### PR TITLE
Fix : Button Refreshes Entire Organizations

### LINKED ISSUE #10974: Delete Button Refreshes Entire Organizations
**Describe the bug**
When clicking the delete button for a specific organization in the "Organization" selector, the entire organization refreshing.

**To Reproduce**

1. Go to the "Encounters" tab.
2. Click on "View Details".
3. Open the "Organization" selector.
4. Click the delete button for a specific organization.

**Expected behavior**
When the delete button is clicked for a specific organization, only that organization should be refresh from the list without causing other organization.

**Video Clip**

https://github.com/user-attachments/assets/6e41a777-24b4-4e10-8686-acad1ad1c87c

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #10974

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

   https://github.com/user-attachments/assets/e4bfdb0c-ed59-483c-b59e-80eb7a5ad3b0

## Summary by CodeRabbit

- **New Features**
  - Introduced a new `DeleteOrganizationButton` component for streamlined organization removal.
  - Enhanced the removal process with improved feedback: the removal button now displays a loading indicator and disables during processing, ensuring a smoother experience when managing organization removals.
  - Added success messages for organization addition and removal to improve user feedback.

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]

File: src/components/Patient/LinkDepartmentsSheet.tsx [hunk 1]
```diff
@@ -219,9 +223,9 @@ export default function LinkDepartmentsSheet({
...
                       size="icon"
                       onClick={() => removeOrganization(org.id)}
-                      disabled={isRemoving}
+                      disabled={removingOrgId === org.id}
                     >
-                      {isRemoving ? (
+                      {removingOrgId === org.id ? (
                         <Loader2 className="h-4 w-4 animate-spin" />
                       ) : (
                         <Trash2 className="h-4 w-4 text-destructive" />
```
Comment (rithviknishad) [inline src/components/Patient/LinkDepartmentsSheet.tsx]: i'd say wrap this button in a component and keep the useMutation there in that component, and use useMutation's `isPending` to show the loading state instead of creating a new state here;

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Patient/LinkDepartmentsSheet.tsx [hunk 2]
```diff
@@ -84,38 +84,44 @@ function getInvalidateQueries(
...
-      setOpen(false);
-      onUpdate?.();
+      const { queryKey } = getMutationParams(
+        entityType,
+        entityId,
+        facilityId,
+        false,
+      );
+      queryClient.invalidateQueries({ queryKey });
+      toast.success("Organization removed successfully");
```
Comment (Jacobjeevan) [inline src/components/Patient/LinkDepartmentsSheet.tsx]: translation here and below.

Comment (Jacobjeevan) [reply src/components/Patient/LinkDepartmentsSheet.tsx]: complete merge checklist.

**Review by Jacobjeevan — APPROVED** [review]

**Comment by Jacobjeevan** [comment]
@Jeffrin2005 Complete merge checklist.

**Comment by rithviknishad** [comment]
merge checklist not followed

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan Completed merge checklist, Can we re-open this PR ?

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
