### PR TITLE
Integrates useInfiniteQuery for data fetching and resolves Infinite Load issue in Notes.

### LINKED ISSUE #9188: Enhance Discussion Notes Chat History with Infinite Scrolling or Better Navigation Solution
**Describe the bug**

When scrolling from the bottom to the top of a discussion with 20 chat entries in the  any "Discussion Notes" section, the page reloads unexpectedly after reaching the 15th chat. This forces the user to start scrolling from the bottom again, disrupting the navigation experience.

**To Reproduce**

1. Navigate to the Patient tab and select any patient card.
2. Click on the Discussion Notes section.
3. Add 20 chat messages.
4. Attempt to scroll from the bottom to the top of the chat history.
5. See error

**Expected behavior**

The user should be able to smoothly scroll from the bottom to the top of the chat history without the page reloading or resetting the scroll position.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by JavidSumra**
## Proposed Changes  

- Fixes #9188  
- Updated state update position in the `fetchNote` function to resolve unexpected page reloads while scrolling.  
- Ensured smooth infinite scrolling for discussion notes by maintaining the scroll position correctly.  

@ohcnetwork/care-fe-code-reviewers  

---

## Merge Checklist  

- [ ] Add specs that demonstrate bug / test a new feature.  
- [ ] Update [[product documentation](https://docs.ohc.network/)](https://docs.ohc.network).  
- [x] Ensure that UI text is kept in I18n files.  
- [ ] Prep screenshot or demo video for changelog entry, and attach it to the issue.  
- [x] Request for Peer Reviews.  
- [ ] Completion of QA.  

## Release Notes

- **New Features**
	- Enhanced patient notes functionality with improved state management and pagination.
	- Introduced a new hook for adding patient notes, streamlining the note addition process.

- **Bug Fixes**
	- Adjusted loading state handling for better user experience during data fetching.

- **Refactor**
	- Simplified data fetching logic across multiple components.
	- Replaced manual pagination handling with a more efficient approach using hooks.
	- Updated component interfaces to reflect changes in state management and properties.
	- Removed unnecessary properties from state structures to streamline data handling.
	- Improved handling of note addition and state resets in various components.
	- Streamlined the interface of components by removing redundant props.
	- Enhanced re-rendering behavior by introducing unique keys based on patient ID and thread.

### CODE REVIEW

**Review by yash-learner — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
LGTM

File: src/components/Facility/PatientConsultationNotesList.tsx [hunk 1]
```diff
@@ -69,18 +67,20 @@
...
-    setReload?.(false);
   };
 
   useEffect(() => {
     if (reload) {
-      fetchNotes();
+      fetchNotes().then(() => {
+        setIsLoading(false);
+        setReload?.(false);
+      });
```
[the remark this answers is not in the document]
Comment (khavinshankar) [reply src/components/Facility/PatientConsultationNotesList.tsx]: @JavidSumra can u look into coderabbit comment, just check if when the fetch request fails with an error status, it's not loading infinitely.

File: src/components/Facility/PatientNotesList.tsx [hunk 2]
```diff
@@ -53,18 +52,20 @@ const PatientNotesList = (props: PatientNotesProps) => {
...
-    setReload(false);
   };
 
   useEffect(() => {
     if (reload) {
-      fetchNotes();
+      fetchNotes().then(() => {
+        setIsLoading(false);
+        setReload(false);
+      });
```
Comment (khavinshankar) [inline src/components/Facility/PatientNotesList.tsx]: This looks hacky to me, consider having setIsLoading and setReload in fetchNotes itself, wrap fetchNotes in useCallback, and handle error with try catch if needed.

cc: @rithviknishad can u comment on this

**Review by khavinshankar — CHANGES_REQUESTED** [review]

File: src/components/Facility/PatientNotesList.tsx (hunk 2 above)
Comment (rithviknishad) [reply src/components/Facility/PatientNotesList.tsx]: I agree with @khavinshankar. 

As an alternative I'd recommend sticking with what `useQuery` provides for managing the loading state. Consider building a `useInfiniteQuery` hook if necessary to manage merging queries across from multiple page responses.

File: src/components/Facility/PatientConsultationNotesList.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (bodhish) [reply src/components/Facility/PatientConsultationNotesList.tsx]: @JavidSumra can you update the status here?

[the remark this answers is not in the document]
Comment (JavidSumra) [reply src/components/Facility/PatientConsultationNotesList.tsx]: Yeah @bodhish I'm looking into it sorry for late response.
cc @khavinshankar

**Comment by nihal467** [comment]
@JavidSumra what is the status on this PR

**Comment by JavidSumra** [comment]
Hey @nihal467 I'm working on `useInfiniteQuery` hook so need some time.

**Review by rithviknishad — APPROVED** [review]
Nice work @JavidSumra 
LGTM

**Comment by rithviknishad** [comment]
@JavidSumra create an issue for adding docs about this to the docs repo: https://github.com/ohcnetwork/docs

https://docs.ohc.network/docs/care/development/data-fetching-in-care/

File: src/Utils/request/useInfiniteQuery.ts [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+    if (options?.prefetch ?? true) {
+      refetch().then((response) => {
+        if (response?.data) {
+          updateItems(response);
+          const total = Math.ceil(response.data.count / RESULTS_PER_PAGE_LIMIT);
+          setTotalPages(total);
+        }
+      });
+    }
+  }, [refetch, options?.prefetch, totalPages]);
```
[the remark this answers is not in the document]
Comment (rithviknishad) [reply src/Utils/request/useInfiniteQuery.ts]: Let's resolve this too

File: src/Utils/request/useInfiniteQuery.ts [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+}
+
+export function useInfiniteQuery<TItem>(
+  route: QueryRoute<PaginatedResponse<TItem>>,
+  options?: InfiniteQueryOptions<TItem>,
+) {
+  const [items, setItems] = useState<TItem[]>([]);
+  const [currentPage, setCurrentPage] = useState<number>(1);
+  const [totalCount, setTotalCount] = useState<number>(1);
+  const [offset, setOffset] = useState(0);
```
[the remark this answers is not in the document]
Comment (rithviknishad) [reply src/Utils/request/useInfiniteQuery.ts]: @JavidSumra

File: src/Utils/request/useInfiniteQuery.ts [hunk 5]
```diff
@@ -43,65 +39,27 @@ export function useInfiniteQuery<TData extends PaginatedResponse<TItem>, TItem>(
         : allItems;
```
Comment (Jacobjeevan) [inline src/Utils/request/useInfiniteQuery.ts]: Hmm, shouldn't we call Set here to get ensure unique items when deduplicateBy isn't specified 🤔

File: src/Utils/request/useInfiniteQuery.ts [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+  deduplicateBy?: (item: TItem) => string | number;
+}
+
+export function useInfiniteQuery<TItem>(
+  route: QueryRoute<PaginatedResponse<TItem>>,
+  options?: InfiniteQueryOptions<TItem>,
+) {
+  const [items, setItems] = useState<TItem[]>([]);
+  const [currentPage, setCurrentPage] = useState<number>(1);
+  const [totalCount, setTotalCount] = useState<number>(1);
```
Comment (rithviknishad) [inline src/Utils/request/useInfiniteQuery.ts]: the initial state of this would be undefined right? we do not know if its 1 initially right?

```suggestion
  const [totalCount, setTotalCount] = useState<number>();
```

File: src/Utils/request/useInfiniteQuery.ts [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+
+  return {
+    items,
+    loading,
+    fetchNextPage,
+    refetch,
+    setCurrentPage,
+    currentPage,
+    totalCount,
+    hasMore: totalCount / RESULTS_PER_PAGE_LIMIT > offset,
```
[the remark this answers is not in the document]
Comment (rithviknishad) [reply src/Utils/request/useInfiniteQuery.ts]: this looks lot cleaner @JavidSumra

File: src/Utils/request/useInfiniteQuery.ts (hunk 5 above)
Comment (rithviknishad) [reply src/Utils/request/useInfiniteQuery.ts]: doing Set on array of json objects won't result in de-duplication. This is because even if two identical JSON objects are added to a set, both the json objects would have different references.

Comment (rithviknishad) [reply src/Utils/request/useInfiniteQuery.ts]: image

Comment (rithviknishad) [reply src/Utils/request/useInfiniteQuery.ts]: we could either mandate the deDuplicateBy callback to be mandatory or not perform deduplication at all if undefined. I prefer the former.

**Review by rithviknishad — APPROVED** [review]

**Review by Jacobjeevan — DISMISSED** [review]

**Comment by nihal467** [comment]
image

@JavidSumra the latest send notes are only shown as we manually reload the entire page, do check the functionality of the components

File: src/components/Facility/ConsultationDoctorNotes/index.tsx [hunk 8]
```diff
@@ -79,9 +79,13 @@ const ConsultationDoctorNotes = (props: ConsultationDoctorNotesProps) => {
...
     });
 
-    if (res?.status === 201) {
+    if (res?.status === 201 && data) {
       Notification.Success({ msg: "Note added successfully" });
       setNoteField("");
+      setState((prevState) => ({
+        ...prevState,
+        notes: [data, ...prevState.notes],
+      }));
```
Comment (rithviknishad) [inline src/components/Facility/ConsultationDoctorNotes/index.tsx]: this is not the right way. This solves only the problem for the current user in the same tab. 

However another user (User A) who has this discussion notes opened won't be receiving the message from (User B)

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Facility/ConsultationDoctorNotes/index.tsx (hunk 8 above)
Comment (rithviknishad) [reply src/components/Facility/ConsultationDoctorNotes/index.tsx]: left: user A; right: user B who sent a message recently. notice that it's not reflected for user A even though user A is subscribed.

image

Comment (khavinshankar) [reply src/components/Facility/ConsultationDoctorNotes/index.tsx]: @rithviknishad this seems like a backend issue, checked push messaging the application tab in the inspector, did not receive any incoming notifications

cc: @JavidSumra

**Review by rithviknishad — CHANGES_REQUESTED** [review]
#9360 Has added support for using TanStack Query. Can we switch to using it's `useInfiniteQuery` instead after merging your branch with latest `develop` branch?

Refer [docs](https://tanstack.com/query/latest/docs/framework/react/reference/useInfiniteQuery#useinfinitequery).

File: src/components/Facility/ConsultationDoctorNotes/index.tsx [hunk 9]
```diff
@@ -81,12 +79,14 @@ const ConsultationDoctorNotes = (props: ConsultationDoctorNotesProps) => {
...
-    if (res?.status === 201) {
-      Notification.Success({ msg: "Note added successfully" });
-      setState({ ...state, cPage: 1 });
+    if (res?.status === 201 && data) {
       setNoteField("");
-      setReload(true);
+      setState((prevState) => ({
+        ...prevState,
+        notes: [data, ...prevState.notes],
+      }));
```
Comment (rithviknishad) [inline src/components/Facility/ConsultationDoctorNotes/index.tsx]: you can use tanstack's useMutation to add the note and perform perform query invalidations for the query that fetches the notes

File: src/components/Facility/PatientConsultationNotesList.tsx [hunk 10]
```diff
@@ -24,78 +25,54 @@ interface PatientNotesProps {
...
+        notes: deduplicatedNotes,
       }));
-      setReload?.(true);
     }
-  };
+  }, [data]);
+
+  useEffect(() => {
+    refetch();
+  }, [thread]);
```
Comment (rithviknishad) [inline src/components/Facility/PatientConsultationNotesList.tsx]: this can be done by query invalidations instead

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by rithviknishad** [comment]
Do correct the PR title btw

File: src/components/Facility/ConsultationDoctorNotes/index.tsx [hunk 11]
```diff
@@ -54,40 +55,52 @@ const ConsultationDoctorNotes = (props: ConsultationDoctorNotesProps) => {
...
+      setReplyTo(undefined);
+      Notification.Success({ msg: "Note added successfully" });
+
+      queryClient.invalidateQueries({
+        queryKey: ["notes"],
+      });
+    },
+    onError: () => {
+      Notification.Error({ msg: "Failed to add note" });
+    },
```
Comment (rithviknishad) [inline src/components/Facility/ConsultationDoctorNotes/index.tsx]: error messages need not be handled. We have a global handler for that, which describes the exact reason why it failed if detectable instead.

File: src/components/Facility/ConsultationDoctorNotes/index.tsx [hunk 12]
```diff
@@ -54,40 +55,52 @@ const ConsultationDoctorNotes = (props: ConsultationDoctorNotesProps) => {
...
-
-    if (res?.status === 201) {
-      Notification.Success({ msg: "Note added successfully" });
-      setState({ ...state, cPage: 1 });
-      setNoteField("");
-      setReload(true);
-      setReplyTo(undefined);
-    }
+    addNoteMutation.mutate(noteField);
+    setNoteField("");
```
Comment (rithviknishad) [inline src/components/Facility/ConsultationDoctorNotes/index.tsx]: pass this as `onSuccess` arg. for the useMutation instead.

File: src/components/Patient/PatientNotes.tsx [hunk 13]
```diff
@@ -47,37 +48,52 @@ const PatientNotes = (props: PatientNotesProps) => {
...
+      setReplyTo(undefined);
+      Notification.Success({ msg: "Note added successfully" });
+
+      queryClient.invalidateQueries({
+        queryKey: ["notes"],
+      });
+    },
+    onError: () => {
+      Notification.Error({ msg: "Failed to add note" });
+    },
```
Comment (rithviknishad) [inline src/components/Patient/PatientNotes.tsx]: same here

File: src/components/Patient/PatientNotes.tsx [hunk 14]
```diff
@@ -47,37 +48,52 @@ const PatientNotes = (props: PatientNotesProps) => {
...
-    });
-    if (res?.status === 201) {
-      Notification.Success({ msg: "Note added successfully" });
-      setNoteField("");
-      setReload(!reload);
-      setState({ ...state, cPage: 1 });
-      setReplyTo(undefined);
-    }
+    addNoteMutation.mutate(noteField);
+    setNoteField("");
```
Comment (rithviknishad) [inline src/components/Patient/PatientNotes.tsx]: here too

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Patient/PatientNotes.tsx [hunk 15]
```diff
@@ -47,37 +48,52 @@ const PatientNotes = (props: PatientNotesProps) => {
...
+      Notification.Success({ msg: "Note added successfully" });
+
+      queryClient.invalidateQueries({
+        queryKey: ["notes"],
+      });
+    },
+    onError: () => {
+      Notification.Error({ msg: "Failed to add note" });
+    },
+  });
```
[the remark this answers is not in the document]
Comment (JavidSumra) [reply src/components/Patient/PatientNotes.tsx]: @rithviknishad, what do you think about this?

File: src/components/Facility/ConsultationDoctorNotes/index.tsx (hunk 12 above)
Comment (JavidSumra) [reply src/components/Facility/ConsultationDoctorNotes/index.tsx:103]: Just setNoteField right?

File: src/components/Patient/PatientNotes.tsx (hunk 15 above)
[the remark this answers is not in the document]
Comment (rithviknishad) [reply src/components/Patient/PatientNotes.tsx]: yup

[the remark this answers is not in the document]
Comment (JavidSumra) [reply src/components/Patient/PatientNotes.tsx]: Okay, should I open a new follow-up PR or make the changes in the same PR?

[the remark this answers is not in the document]
Comment (rithviknishad) [reply src/components/Patient/PatientNotes.tsx]: same pr

**Comment by JavidSumra** [comment]
@rithviknishad can you please check the implementation of util function?

File: src/components/Patient/Utils.ts [hunk 16]
```diff
@@ -17,3 +22,38 @@ export function isPatientMandatoryDataFilled(patient: PatientModel) {
...
+  const queryClient = useQueryClient();
+
+  return useMutation({
+    mutationFn: async ({
+      noteField,
+      thread,
+      replyTo,
+    }: {
+      noteField: string;
+      thread: 10 | 20;
```
Comment (rithviknishad) [inline src/components/Patient/Utils.ts]: lgtm, just this: avoid duplicating type definitions. might break if things are changed in other places.

```suggestion
      thread: PatientNotesModel["thread"];
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by nihal467** [comment]
LGTM @rithviknishad can you review it

File: src/components/Patient/Utils.ts [hunk 17]
```diff
@@ -17,3 +25,38 @@ export function isPatientMandatoryDataFilled(patient: PatientModel) {
...
+      const { res, data } = await request(routes.addPatientNote, {
+        pathParams: { patientId: options.patientId },
+        body: {
+          note: noteField,
+          thread,
+          consultation: options.consultationId,
+          reply_to: replyTo?.id,
+        },
+      });
+      if (res?.status === 201 && data) return data;
```
Comment (rithviknishad) [inline src/components/Patient/Utils.ts]: use `mutate` function instead of `request`. `request` is deprecated. See docs.ohc.network

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Patient/Utils.ts [hunk 18]
```diff
@@ -17,3 +25,38 @@ export function isPatientMandatoryDataFilled(patient: PatientModel) {
...
+        pathParams: { patientId: options.patientId },
+      });
+
+      return performMutation({
+        note: noteField,
+        thread,
+        consultation: options.consultationId,
+        reply_to: replyTo?.id,
+      });
+    },
```
Comment (rithviknishad) [inline src/components/Patient/Utils.ts]: why complicate things?

```suggestion
    mutationFn: mutate(routes.addPatinetNote, {
      pathParams: { patientId: options.patientId }
    }),
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Facility/PatientConsultationNotesList.tsx [hunk 19]
```diff
@@ -24,80 +25,67 @@ interface PatientNotesProps {
...
+        pathParams: { patientId: state.patientId! },
+        query: { thread, offset: pageParam, consultation: consultationId },
+      });
+      setReload?.(false);
+      return {
+        results: response?.data?.results ?? [],
+        nextPage: pageParam + RESULTS_PER_PAGE_LIMIT,
+        totalResults: response?.data?.count ?? 0,
+      };
+    },
```
Comment (rithviknishad) [inline src/components/Facility/PatientConsultationNotesList.tsx]: `request` is deprecated. use [`query`](https://github.com/ohcnetwork/care_fe/blob/c1890ede160c58e7da768e2a377ab32d03b4d382/src/Utils/request/query.ts#L62) if possible, or use [`callApi`](https://github.com/ohcnetwork/care_fe/blob/develop/src/Utils/request/query.ts#L7) as an alternative.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/components/Patient/Utils.ts [hunk 20]
```diff
@@ -17,3 +23,18 @@ export function isPatientMandatoryDataFilled(patient: PatientModel) {
...
+
+export const useAddPatientNote = (options: { patientId: string }) => {
+  const queryClient = useQueryClient();
+
+  return useMutation({
+    mutationFn: mutate(routes.addPatientNote, {
+      pathParams: { patientId: options.patientId },
+    }),
+    onSuccess: (data) => {
+      queryClient.invalidateQueries({ queryKey: ["notes"] });
```
Comment (rithviknishad) [inline src/components/Patient/Utils.ts]:
```suggestion
      queryClient.invalidateQueries({ queryKey: ["notes", patientId] });
```

File: src/components/Facility/PatientNotesList.tsx [hunk 21]
```diff
@@ -23,57 +24,59 @@ interface PatientNotesProps {
...
-    setIsLoading(true);
-    const { data }: any = await request(routes.getPatientNotes, {
-      pathParams: { patientId: props.patientId },
-      query: {
-        offset: (state.cPage - 1) * RESULTS_PER_PAGE_LIMIT,
-        thread,
-      },
-    });
+  const { data, isLoading, fetchNextPage, hasNextPage } = useInfiniteQuery({
+    queryKey: ["notes"],
```
Comment (rithviknishad) [inline src/components/Facility/PatientNotesList.tsx]: add thread, patientId and consultationId (if present) to the query key.

refer: https://tkdodo.eu/blog/effective-react-query-keys

File: src/components/Facility/PatientNotesList.tsx [hunk 22]
```diff
@@ -23,57 +24,59 @@ interface PatientNotesProps {
...
+    queryFn: async ({ pageParam = 0 }) => {
+      const response = await callApi(routes.getPatientNotes, {
+        pathParams: { patientId },
+        queryParams: { thread, offset: pageParam },
+      });
+      setReload(false);
```
Comment (rithviknishad) [inline src/components/Facility/PatientNotesList.tsx]: why is abort signal not passed to the callApi? 🤔

File: src/components/Facility/PatientNotesList.tsx [hunk 23]
```diff
@@ -23,57 +24,59 @@ interface PatientNotesProps {
...
     }
-  };
+  }, [data]);
+
+  useEffect(() => {
+    setReload?.(true);
+    queryClient.invalidateQueries({
+      queryKey: ["notes"],
+    });
+  }, [thread]);
```
Comment (rithviknishad) [inline src/components/Facility/PatientNotesList.tsx]: these kind of hacks not needed if the thread name is present in the queryKey itself right?
```suggestion
```

File: src/components/Facility/PatientConsultationNotesList.tsx [hunk 24]
```diff
@@ -24,80 +25,71 @@ interface PatientNotesProps {
...
     }
-  };
+  }, [data]);
+
+  useEffect(() => {
+    setReload?.(true);
+    queryClient.invalidateQueries({
+      queryKey: ["notes"],
+    });
+  }, [thread]);
```
Comment (rithviknishad) [inline src/components/Facility/PatientConsultationNotesList.tsx]: use proper queryKeys so that this is not needed

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Patient/Utils.ts (hunk 20 above)
Comment (JavidSumra) [reply src/components/Patient/Utils.ts:35]: When adding patientId it's not working what should i do now?

Comment (rithviknishad) [reply src/components/Patient/Utils.ts]: define "not working"

File: src/components/Patient/Utils.ts [hunk 25]
```diff
@@ -17,3 +23,23 @@ export function isPatientMandatoryDataFilled(patient: PatientModel) {
...
+
+  return useMutation({
+    mutationFn: mutate(routes.addPatientNote, {
+      pathParams: { patientId },
+    }),
+    onSuccess: (data) => {
+      console.log("here");
+      queryClient.invalidateQueries({
+        queryKey: ["notes", patientId],
+        exact: false,
```
Comment (rithviknishad) [inline src/components/Patient/Utils.ts]: it is false by default
```suggestion
```

File: src/components/Patient/Utils.ts [hunk 26]
```diff
@@ -17,3 +23,23 @@ export function isPatientMandatoryDataFilled(patient: PatientModel) {
...
+export const useAddPatientNote = (options: { patientId: string }) => {
+  const queryClient = useQueryClient();
+  const { patientId } = options;
+
+  return useMutation({
+    mutationFn: mutate(routes.addPatientNote, {
+      pathParams: { patientId },
+    }),
+    onSuccess: (data) => {
+      console.log("here");
```
Comment (rithviknishad) [inline src/components/Patient/Utils.ts]:
```suggestion
```

File: src/components/Patient/Utils.ts [hunk 27]
```diff
@@ -17,3 +23,23 @@ export function isPatientMandatoryDataFilled(patient: PatientModel) {
...
+      queryClient.invalidateQueries({
+        queryKey: ["notes", patientId],
```
Comment (rithviknishad) [inline src/components/Patient/Utils.ts]: do add the thread and consultation id too to the keys. why do we need to invalidate all threads when message is sent only to one thread?

File: src/components/Patient/Utils.ts [hunk 28]
```diff
@@ -17,3 +23,23 @@ export function isPatientMandatoryDataFilled(patient: PatientModel) {
...
+        exact: false,
+      });
+      Notification.Success({ msg: "Note added successfully" });
```
Comment (rithviknishad) [inline src/components/Patient/Utils.ts]: let's skip the notification for success.

user will be aware that it's added by seeing the message move up to the message history.

File: src/components/Facility/PatientNoteCard.tsx [hunk 29]
```diff
@@ -75,14 +76,16 @@ const PatientNoteCard = ({
     });
     if (res?.status === 200) {
       Success({ msg: "Note updated successfully" });
+      queryClient.invalidateQueries({
+        queryKey: ["notes", patientId],
+        exact: false,
```
Comment (rithviknishad) [inline src/components/Facility/PatientNoteCard.tsx]: exact is false by default
```suggestion
        queryKey: ["notes", patientId],
```

File: src/components/Facility/PatientNoteCard.tsx [hunk 30]
```diff
@@ -44,6 +44,7 @@ const PatientNoteCard = ({
   const [showEditHistory, setShowEditHistory] = useState(false);
   const [editHistory, setEditHistory] = useState<PatientNotesEditModel[]>([]);
   const authUser = useAuthUser();
+  const queryClient = useQueryClient();
 
   const fetchEditHistory = async () => {
     const { res, data } = await request(routes.getPatientNoteEditHistory, {
```
Comment (rithviknishad) [inline src/components/Facility/PatientNoteCard.tsx]: let's get this switched to useQuery as well

File: src/components/Facility/ConsultationDoctorNotes/index.tsx [hunk 31]
```diff
@@ -54,40 +54,30 @@ const ConsultationDoctorNotes = (props: ConsultationDoctorNotesProps) => {
...
-      setState({ ...state, cPage: 1 });
-      setNoteField("");
-      setReload(true);
-      setReplyTo(undefined);
-    }
+    setReplyTo(undefined);
+    setNoteField("");
   };
 
   useTanStackQueryInstead(routes.getPatient, {
```
Comment (rithviknishad) [inline src/components/Facility/ConsultationDoctorNotes/index.tsx]: switch to useQuery

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Patient/Utils.ts [hunk 32]
```diff
@@ -1,5 +1,12 @@
+import { useMutation, useQueryClient } from "@tanstack/react-query";
+
 import { PatientModel } from "@/components/Patient/models";
 
+import routes from "@/Utils/request/api";
+import mutate from "@/Utils/request/mutate";
+
+import { PatientNotesModel } from "../Facility/models";
```
Comment (rithviknishad) [inline src/components/Patient/Utils.ts]: use relative imports

File: src/components/Facility/PatientNoteCard.tsx [hunk 33]
```diff
@@ -44,15 +45,17 @@ const PatientNoteCard = ({
...
+    queryKey: [patientId, note.id],
+    queryFn: async () => {
+      const response = await callApi(routes.getPatientNoteEditHistory, {
+        pathParams: { patientId, noteId: note.id },
+      });
+      return response;
+    },
+  });
 
   const onUpdateNote = async () => {
```
Comment (rithviknishad) [inline src/components/Facility/PatientNoteCard.tsx:68]: use useMutation for the request present in line 75

File: src/components/Facility/PatientNoteCard.tsx [hunk 34]
```diff
@@ -44,15 +45,17 @@ const PatientNoteCard = ({
...
-    }
-  };
+  const { data, refetch } = useQuery({
+    queryKey: [patientId, note.id],
+    queryFn: async () => {
+      const response = await callApi(routes.getPatientNoteEditHistory, {
+        pathParams: { patientId, noteId: note.id },
+      });
+      return response;
+    },
```
Comment (rithviknishad) [inline src/components/Facility/PatientNoteCard.tsx]: stick with how it's in docs. 

avoid calling callApi directly unless absolutely necessary. Stick with `query` or `mutate` wherever needed.

```suggestion
    queryFn: query(routes.getPatientNoteEditHistory, {
      pathParams: { patientId, noteId: note.id },
    },
```

File: src/components/Facility/ConsultationDoctorNotes/index.tsx [hunk 35]
```diff
@@ -54,53 +55,52 @@ const ConsultationDoctorNotes = (props: ConsultationDoctorNotesProps) => {
...
+  const { data } = useQuery({
+    queryKey: [patientId],
+    queryFn: async ({ signal }) => {
+      const response = await callApi(routes.getPatient, {
+        pathParams: { patientId },
+        queryParams: { thread, offset: thread },
+        signal,
+      });
+      return response;
     },
```
Comment (rithviknishad) [inline src/components/Facility/ConsultationDoctorNotes/index.tsx]: same here too. use `query` instead of `callApi`

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/components/Facility/ConsultationDoctorNotes/index.tsx [hunk 36]
```diff
@@ -54,53 +55,48 @@ const ConsultationDoctorNotes = (props: ConsultationDoctorNotesProps) => {
...
-    pathParams: { id: patientId },
-    onResponse: ({ data }) => {
-      if (data) {
-        setPatientActive(data.is_active ?? true);
-        setPatientName(data.name ?? "");
-        setFacilityName(data.facility_object?.name ?? "");
-      }
-    },
+  const { data } = useQuery({
+    queryKey: [patientId],
```
Comment (Jacobjeevan) [inline src/components/Facility/ConsultationDoctorNotes/index.tsx]: Let's add the route name and thread to the queryKey.

File: src/components/Patient/Utils.ts [hunk 37]
```diff
@@ -17,3 +23,24 @@ export function isPatientMandatoryDataFilled(patient: PatientModel) {
...
+  consultationId?: string;
+}) => {
+  const queryClient = useQueryClient();
+  const { patientId, thread, consultationId } = options;
+
+  return useMutation({
+    mutationFn: mutate(routes.addPatientNote, {
+      pathParams: { patientId },
+    }),
+    onSuccess: (data) => {
```
Comment (Jacobjeevan) [inline src/components/Patient/Utils.ts:39]: We can add the success notification back in here. 

Also, might as well add translations for the notifications while you are at it. Other than that, lgtm.

Comment (rithviknishad) [reply src/components/Patient/Utils.ts:39]: do we need a success notification for sending a message in the first place? 😅 
feels kinda weird.

Comment (Jacobjeevan) [reply src/components/Patient/Utils.ts:39]: 🤔  Hmm, yea you are right 😅  Let's skip the success message then.

File: src/components/Facility/ConsultationDoctorNotes/index.tsx [hunk 38]
```diff
@@ -54,53 +55,48 @@ const ConsultationDoctorNotes = (props: ConsultationDoctorNotesProps) => {
...
-    pathParams: { id: patientId },
-    onResponse: ({ data }) => {
-      if (data) {
-        setPatientActive(data.is_active ?? true);
-        setPatientName(data.name ?? "");
-        setFacilityName(data.facility_object?.name ?? "");
-      }
-    },
+  const { data } = useQuery({
+    queryKey: ["/patient", patientId, thread],
```
Comment (rithviknishad) [inline src/components/Facility/ConsultationDoctorNotes/index.tsx]: why do we need "thread" as a dependency for getting a patient record?
```suggestion
    queryKey: ["patient", patientId],
```

File: src/components/Facility/ConsultationDoctorNotes/index.tsx [hunk 39]
```diff
@@ -54,53 +55,48 @@ const ConsultationDoctorNotes = (props: ConsultationDoctorNotesProps) => {
...
+    queryFn: query(routes.getPatient, {
+      pathParams: { patientId },
+      queryParams: { thread, offset: thread },
```
Comment (rithviknishad) [inline src/components/Facility/ConsultationDoctorNotes/index.tsx]: do a self review of your code before requesting review. why would thread and offset: thread be query params for getting the patient object? makes no sense.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Facility/ConsultationDoctorNotes/index.tsx (hunk 38 above)
Comment (JavidSumra) [reply src/components/Facility/ConsultationDoctorNotes/index.tsx]: https://github.com/ohcnetwork/care_fe/pull/9190#discussion_r1897611135
Jacob suggested me this changes

Comment (rithviknishad) [reply src/components/Facility/ConsultationDoctorNotes/index.tsx]: You are always free to ask "why we need this" in-case if any requested changes didn't make sense. We might make mistakes at times, or sometimes contributors may not fully get an understanding.

Question things that doesn't make sense, instead of making changes as is requested without trying to understand. 😅 

cc: @Jacobjeevan

Comment (JavidSumra) [reply src/components/Facility/ConsultationDoctorNotes/index.tsx]: Rithvik I'll take care of it from next time so sorry about it

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by Jacobjeevan — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]
