### PR TITLE
Encounter Qustions dropdown values moved to constants and i18 applied for all strings

### LINKED ISSUE #9817: Failed to update encounters on selecting certain diet preference
**Describe the bug**
Failed to update encounters on selecting certain diet preference

**To Reproduce**

1. Select any Patient
2. Click on View Encounter
3. Click on Update Encounter
4. Select diet preference as Gluten free, Nut free or Dairy Free
5. Click on submit button
6. Error -> Failed to update Questionnaire

**Expected behavior**
Encounter should be updated

**Screenshots**
Image

**Desktop (please complete the following information):**

**Additional context**
I have debug the issue. The backend is expecting diet preference as kebab case: Ex 'diary-free', 'nut-free', 'gluten-free' 
From the UI we are providing diet payload as  snake case. Ex: 'diary_free', 'nut_free', 'gluten_free'

### PR DESCRIPTION
**Pull request by arhamathar**
## Proposed Changes

- Fixes #9817
- Move Diet Preference Value to constants as snake case

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Release Notes

- **New Features**
  - Added internationalization (i18n) support for encounter-related components.
  - Enhanced localization capabilities for encounter status, class, priority, and other fields.

- **Improvements**
  - Dynamically generated select options for encounter-related dropdowns.
  - Updated type definitions to improve type safety and maintainability.

- **Localization**
  - Added comprehensive translation support for encounter-related terminology.
  - Introduced new translation keys for various encounter attributes and selection prompts, including admit source, diet preference, and discharge disposition.

### CODE REVIEW

File: src/common/constants.tsx [hunk 1]
```diff
@@ -1757,3 +1757,19 @@ export const HEADER_CONTENT_TYPES = {
...
+export const DIET_PREFERENCE_OPTIONS = [
+  { label: "Vegetarian", value: "vegetarian" },
+  { label: "Dairy Free", value: "diary_free" },
+  { label: "Nut Free", value: "nut_free" },
+  { label: "Gluten Free", value: "gluten_free" },
+  { label: "Vegan", value: "vegan" },
+  { label: "Halal", value: "halal" },
+  { label: "Kosher", value: "kosher" },
+  { label: "None", value: "none" },
+] as const;
```
Comment (rithviknishad) [inline src/common/constants.tsx]: only the value list is needed, the label can be kept in i18n texts. Refer README for translation guidelines.

File: src/common/constants.tsx [hunk 2]
```diff
@@ -1757,3 +1757,19 @@ export const HEADER_CONTENT_TYPES = {
 } as const;
 
 export const ADMIN_USER_TYPES = ["DistrictAdmin", "StateAdmin"] as const;
+
+/**
+ * @deprecated use `LocalStorageKeys.patientTokenKey` instead
+ */
+export const CarePatientTokenKey = LocalStorageKeys.patientTokenKey;
```
Comment (rithviknishad) [inline src/common/constants.tsx]: ?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by rithviknishad** [comment]
Do the same for all things present in EncounterQuestion and not just diet preference. Also add i18n translations for all literal strings in the file

File: src/common/constants.tsx [hunk 3]
```diff
@@ -1757,3 +1757,78 @@ export const HEADER_CONTENT_TYPES = {
...
+  encounter_discharge_disposition__other_hcf: "other_hcf",
+  encounter_discharge_disposition__hosp: "hosp",
+  encounter_discharge_disposition__long: "long",
+  encounter_discharge_disposition__aadvice: "aadvice",
+  encounter_discharge_disposition__exp: "exp",
+  encounter_discharge_disposition__psy: "psy",
+  encounter_discharge_disposition__rehab: "rehab",
+  encounter_discharge_disposition__snf: "snf",
+  encounter_discharge_disposition__oth: "oth",
+} as const;
```
Comment (rithviknishad) [inline src/common/constants.tsx]: let's just keep an array instead of object

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/common/constants.tsx (hunk 3 above)
Comment (rithviknishad) [reply src/common/constants.tsx]: Refer how it's done on existing codebase

- https://github.com/ohcnetwork/care_fe/blob/rithviknishad/feat/schedule-validations/src/types/scheduling/schedule.ts#L7
- https://github.com/ohcnetwork/care_fe/blob/rithviknishad/feat/schedule-validations/public/locale/en.json#L197-L199

**Comment by arhamathar** [comment]
Hi @rithviknishad  I have moved the values to an array. Can you please check and confirm

File: src/common/constants.tsx [hunk 4]
```diff
@@ -1757,3 +1757,78 @@ export const HEADER_CONTENT_TYPES = {
...
+  "other_hcf",
+  "hosp",
+  "long",
+  "aadvice",
+  "exp",
+  "psy",
+  "rehab",
+  "snf",
+  "oth",
+] as const;
```
Comment (rithviknishad) [inline src/common/constants.tsx]: we already have most of these defined in https://github.com/ohcnetwork/care_fe/blob/develop/src/types/emr/encounter.ts#L6-L67

Let's convert that to array and update the type to be

```
export const ENCOUNTER_DISCHARGE_DISPOSITION = [...] as const;

export type EncounterDischargeDisposition = (typeof ENCOUNTER_DISCHARGE_DISPOSITION)[number];
```

Comment (rithviknishad) [reply src/common/constants.tsx]: let's move this to the types folder instead of keeping it in constants.tsx.

That's where we store the new things.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by rithviknishad** [comment]
Do update the PR title btw

File: src/types/emr/encounter.ts [hunk 5]
```diff
@@ -3,68 +3,94 @@ import { UserBase } from "@/types/user/user";
...
+export const ENCOUNTER_DIET_PREFERENCE = [
+  "vegetarian",
+  "diary_free",
+  "nut_free",
+  "gluten_free",
+  "vegan",
+  "halal",
+  "kosher",
+  "none",
+] as const;
```
[the remark this answers is not in the document]
Comment (Jacobjeevan) [reply src/types/emr/encounter.ts:37]: currently backend uses diary_free so it will need to be updated there first.

[the remark this answers is not in the document]
Comment (rithviknishad) [reply src/types/emr/encounter.ts:37]: yeah, go ahead

[the remark this answers is not in the document]
Comment (rithviknishad) [reply src/types/emr/encounter.ts:37]: oh i was talking to you @coderabbitai

[the remark this answers is not in the document]
Comment (Jacobjeevan) [reply src/types/emr/encounter.ts:37]: @coderabbitai create the issue as suggested above.
