### PR TITLE
Invoice Charge Item - Discount edit

### LINKED ISSUE #14232: Tax component gets deleted from invoice if discount is applied
**Describe the bug**
When a discount is applied to an item within an invoice, the tax component gets deleted and disappear. 

**To Reproduce**
Steps to reproduce the behavior

1. Create an invoice with an item with tax component
2. Apply Discount 

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by amjithtitus09**
Pick from applicable Charge Item Definition discounts only, and allow editing the value.
Added validations

- Fixes #14232 
- BE: https://github.com/ohcnetwork/care/pull/3344

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **New Features**
  * Per-row discount selector with dynamic add/remove and amount/percentage controls; saves discounts and tax details per line item.
  * No-charge-items fallback when an invoice has no line items.

* **UI/Style Improvements**
  * Wider invoice edit dialog and refreshed table layout to accommodate discount controls and clearer per-item UI.
  * Monetary inputs can hide currency when needed.

* **Localization**
  * Added "Select Discount" and "No discounts"; "Add Discount" capitalization updated.

### CODE REVIEW

**Comment by tasnimshaji** [comment]
LGTM @nihal467

**Comment by Jacobjeevan** [comment]
BE needed: https://github.com/ohcnetwork/care/pull/3344

File: src/components/Billing/Invoice/EditInvoiceTable.tsx [hunk 1]
```diff
@@ -69,17 +111,48 @@ const chargeItemSchema = z.object({
...
+          if (data.discountType === "amount") {
+            return discountValue <= baseAmount;
+          }
+          return true;
+        },
+        {
+          message: "Discount amount cannot be greater than unit price",
+          path: ["discountValue"],
+        },
+      ),
```
Comment (bodhish) [inline src/components/Billing/Invoice/EditInvoiceTable.tsx]: This should be a backend validation right, why are we doing it in FE?

File: src/components/Billing/Invoice/EditInvoiceTable.tsx [hunk 2]
```diff
@@ -94,18 +167,46 @@ export function EditInvoiceTable({
...
   const { t } = useTranslation();
   useShortcutSubContext("facility:billing:invoice:show");
+
+  // Helper function to create a unique key for discount component
+  const getDiscountComponentKey = (
+    component: MonetaryComponent | undefined,
+  ) => {
+    if (!component?.code?.code) return undefined;
+    return component.code.code;
+  };
```
Comment (bodhish) [inline src/components/Billing/Invoice/EditInvoiceTable.tsx]: How is it creating a unique key here 🤔; Code can be duplciate right?

File: src/components/Billing/Invoice/EditInvoiceTable.tsx [hunk 3]
```diff
@@ -94,18 +167,46 @@ export function EditInvoiceTable({
...
+
+  // Helper function to get available discount components for a charge item
+  const getAvailableDiscounts = (chargeItem: ChargeItemRead) => {
+    return (
+      chargeItem?.charge_item_definition?.price_components?.filter(
+        (component) =>
+          component.monetary_component_type === MonetaryComponentType.discount,
+      ) || []
+    );
+  };
```
Comment (bodhish) [inline src/components/Billing/Invoice/EditInvoiceTable.tsx]: I think we should move this to the type as I can see this getting reused accross.

File: src/components/Billing/Invoice/EditInvoiceTable.tsx [hunk 4]
```diff
@@ -94,18 +167,46 @@ export function EditInvoiceTable({
...
+
+  const getTaxComponents = (chargeItem: ChargeItemRead) => {
+    return (
+      chargeItem?.charge_item_definition?.price_components?.filter(
+        (component) =>
+          component.monetary_component_type === MonetaryComponentType.tax,
+      ) || []
+    );
+  };
+
```
Comment (bodhish) [inline src/components/Billing/Invoice/EditInvoiceTable.tsx]: Can we create a single function to extract the required component from ChargeItem?


```suggestion
  const getPriceComponents = (chargeItem: ChargeItemRead, tyep: MonetaryComponentType) => {
    return (
      chargeItem?.charge_item_definition?.price_components?.filter(
        (component) =>
          component.monetary_component_type === type,
      ) || []
    );
  };

```

File: src/components/Billing/Invoice/EditInvoiceTable.tsx [hunk 5]
```diff
@@ -181,12 +288,71 @@ export function EditInvoiceTable({
...
+      if (error && typeof error === "object" && "message" in error) {
+        const fieldLabel =
+          field === "baseAmount"
+            ? t("unit_price")
+            : field === "quantity"
+              ? t("quantity")
+              : field === "discountValue"
+                ? t("discount")
+                : field;
+        errorMessages.push(`${fieldLabel}: ${error.message}`);
```
Comment (bodhish) [inline src/components/Billing/Invoice/EditInvoiceTable.tsx]: OH NO!!!

File: src/components/Billing/Invoice/EditInvoiceTable.tsx [hunk 6]
```diff
@@ -206,9 +372,12 @@ export function EditInvoiceTable({
                 <TableHead className="border-r border-gray-200 font-semibold text-center min-w-[100px]">
                   {t("quantity")}
                 </TableHead>
-                <TableHead className="border-r border-gray-200 font-semibold text-center min-w-[200px]">
+                <TableHead className="border-r border-gray-200 font-semibold text-center min-w-[300px]">
                   {t("discount")}
                 </TableHead>
+                {hasAnyErrors && (
+                  <TableHead className="font-semibold text-center w-12" />
+                )}
```
Comment (bodhish) [inline src/components/Billing/Invoice/EditInvoiceTable.tsx]: Do we really need to do this? 🤔 
If yes why don't we add a title?

File: src/components/Billing/Invoice/EditInvoiceTable.tsx [hunk 7]
```diff
@@ -257,54 +425,189 @@ export function EditInvoiceTable({
...
+                                        <>
+                                          {currentDiscount.code?.display} @{" "}
+                                          {currentDiscount.factor ??
+                                            currentDiscount.amount ??
+                                            0}
+                                          {currentDiscount.factor != null
+                                            ? "%"
+                                            : "₹"}
+                                        </>
+                                      ) : (
```
Comment (bodhish) [inline src/components/Billing/Invoice/EditInvoiceTable.tsx]: Pure mess, we have a component to render money!
Also how do we know its INR always?

File: src/components/Billing/Invoice/EditInvoiceTable.tsx [hunk 8]
```diff
@@ -257,54 +398,185 @@ export function EditInvoiceTable({
...
+                                    </SelectItem>
+                                    {availableDiscounts.map((component) => {
+                                      const key =
+                                        getDiscountComponentKey(component);
+                                      const value =
+                                        component.factor ??
+                                        component.amount ??
+                                        0;
+                                      const suffix =
+                                        component.factor != null ? "%" : "₹";
```
[the remark this answers is not in the document]
Comment (bodhish) [reply src/components/Billing/Invoice/EditInvoiceTable.tsx]: +1 to Copilot

**Review by bodhish — CHANGES_REQUESTED** [review]

File: src/components/Billing/Invoice/EditInvoiceTable.tsx (hunk 2 above)
Comment (amjithtitus09) [reply src/components/Billing/Invoice/EditInvoiceTable.tsx]: We allow setting only one from a dicsount group to the CID, so there wouldn't be duplicates. Changing it anyway to a composite key

Comment (amjithtitus09) [reply src/components/Billing/Invoice/EditInvoiceTable.tsx]: Wait, we cannot create composite key since it won't match if the amount/factor is modified. Reverting to code

File: src/components/Billing/Invoice/EditInvoiceTable.tsx (hunk 1 above)
Comment (amjithtitus09) [reply src/components/Billing/Invoice/EditInvoiceTable.tsx]: Thought of having both. BE alone is better to keep things simple

File: src/components/Billing/Invoice/EditInvoiceTable.tsx (hunk 3 above)
Comment (amjithtitus09) [reply src/components/Billing/Invoice/EditInvoiceTable.tsx]: Done

File: src/components/Billing/Invoice/EditInvoiceTable.tsx (hunk 4 above)
Comment (amjithtitus09) [reply src/components/Billing/Invoice/EditInvoiceTable.tsx]: Done

File: src/components/Billing/Invoice/EditInvoiceTable.tsx (hunk 5 above)
Comment (amjithtitus09) [reply src/components/Billing/Invoice/EditInvoiceTable.tsx]: This seemed like the only way to help user identify validation errors easier after a quick branstorm. The usual way of showing FormMessage was having issues with leveling with other table columns. Anyways moving validation to BE

File: src/components/Billing/Invoice/EditInvoiceTable.tsx (hunk 6 above)
Comment (amjithtitus09) [reply src/components/Billing/Invoice/EditInvoiceTable.tsx]: Moved to BE

File: src/components/Billing/Invoice/EditInvoiceTable.tsx (hunk 7 above)
Comment (amjithtitus09) [reply src/components/Billing/Invoice/EditInvoiceTable.tsx]: True

**Comment by nihal467** [comment]
LGTM

When the backend applies multiple discounts to an item and we edit one of them, it overwrites all the existing discounts and applies only the edited one. As a result, users can’t select a combination of discounts in the invoice frontend. We need to handle this later.

**Comment by nihal467** [comment]
image

- hide the add discount button, if there any more discount left in the dropdown to add
- change the toggle to dropdown or something better to switch between % and Rupees
- in the dropdown showing none wont make sense, remove it

**Comment by amjithtitus09** [comment]
@nihal467 Done

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]

File: src/components/Billing/Invoice/EditInvoiceTable.tsx [hunk 9]
```diff
@@ -257,53 +367,248 @@ export function EditInvoiceTable({
...
+                                        MonetaryComponentType.discount,
+                                      );
+
+                                    const selectedDiscountKeys =
+                                      item.discounts
+                                        ?.filter(
+                                          (_, idx) => idx !== discountIndex,
+                                        )
+                                        .map((d) => getDiscountComponentKey(d))
+                                        .filter((key) => key) || [];
```
Comment (nihal467) [inline src/components/Billing/Invoice/EditInvoiceTable.tsx:424]:
```suggestion
const selectedDiscountKeys =
  item.discounts?.reduce((acc, d, idx) => {
    if (idx !== discountIndex) {
      const key = getDiscountComponentKey(d);
      if (key) acc.push(key);
    }
    return acc;
  }, []) || [];

```

File: src/components/Billing/Invoice/EditInvoiceTable.tsx [hunk 10]
```diff
@@ -257,53 +367,248 @@ export function EditInvoiceTable({
...
+                                                    getDiscountComponentKey(
+                                                      component,
+                                                    );
+                                                  return (
+                                                    <SelectItem
+                                                      key={key}
+                                                      value={key || ""}
+                                                    >
+                                                      {component.code?.display}{" "}
+                                                      @
```
Comment (nihal467) [inline src/components/Billing/Invoice/EditInvoiceTable.tsx:491]:
```suggestion
                                                      {component.code?.display} <span className="ml-1">@</span>
```

**Review by nihal467 — APPROVED** [review]

**Review by bodhish — APPROVED** [review]
