### PR TITLE
fixed auto collapse the DateFormField after user clicks on a date

### LINKED ISSUE #5280: Auto collapse the `DateFormField` after user clicks on a date
**Describe the bug**
The `DateFormField` picker is not collapsing after the user clicks on a date. The user has to click somewhere else to make it collapse.

**To Reproduce**

1. Go to anywhere where the new `DateFormField` picker is present (maybe date range filters in the Advanced Filters of Patients section)
2. Click on a date

**Expected behavior**
When the user clicks on a date, the picker should collapse.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by sachdevavaibhav**
### WHAT
Fixed auto collapse the DateFormField after user clicks on a date by using close prop given by Headless UI.

## Proposed Changes

- Fixes #5280 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

## Video
https://github.com/coronasafe/care_fe/assets/72242181/4796f3da-59bf-4359-b39e-32bd697f04be

### CODE REVIEW

File: src/Components/Common/DateInputV2.tsx [hunk 1]
```diff
@@ -310,7 +315,7 @@ const DateInputV2: React.FC<Props> = ({
                             className="aspect-square w-[14.26%]"
                           >
                             <div
-                              onClick={setDateValue(d)}
+                              onClick={setDateValue(d, close)}
```
Comment (rithviknishad) [inline src/Components/Common/DateInputV2.tsx:318]: You could've done something like this instead of passing the close function and requiring to add a type for it right?

```suggestion
                              onClick={() => {
                                setDateValue(d);
                                close();
                              }}
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Common/DateInputV2.tsx (hunk 1 above)
Comment (sachdevavaibhav) [reply src/Components/Common/DateInputV2.tsx:318]: @rithviknishad Initially I solved it the way you suggested. The problem with this approach is, the original code calls `setDateValue` function while passing to onClick: `onClick={setDateValue(d)}` which runs while the component is rendered. 

By doing this we get the green highlight on the previously mentioned date which is done with the help of 
` isSelectedDate(d)` function.
Screenshot 2023-05-26 134841

By using the way you suggested the green box will gray out initially when user will click the input.

Screenshot 2023-05-26 135252

Comment (rithviknishad) [reply src/Components/Common/DateInputV2.tsx:318]: Alright, thanks @sachdevavaibhav. Nice work!

**Review by rithviknishad — APPROVED** [review]

**Comment by sachdevavaibhav** [comment]
@rithviknishad Could you please guide me how can I contribute to testing?

**Comment by rithviknishad** [comment]
Hey @sachdevavaibhav 
@nihal467 is the QA and handles all of the testings of CARE.

We just add the need testing label once a PR is ready to be tested to check for bugs/responsiveness issues and all.

He'll test and either mark it as test failed with the reason or mark it as tested. Once tested it'll be reviewed and merged by @khavinshankar mostly.

**Comment by rithviknishad** [comment]
You can look into other good first issues meanwhile

**Comment by sachdevavaibhav** [comment]
@rithviknishad Thankyou for the information. Will look into solving other issues.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
