### PR TITLE
Fix : Patient search bar auto focus on visiting

### LINKED ISSUE #10718: Patient search should get autofocused upon visiting patient search tab
Description :

Patient search should get autofocused upon visiting patient search tab in facility

Image

### LINKED ISSUE #10723: Newly Added Patient Is Not Instantly Visible in the Patient List of patient dashboard
**Describe the bug**

When a new patient is added through Patient Registration, the dropdown in the Public Patient Page does not immediately display the newly added patient. The new entry only appears after manually reloading the entire page.

**To Reproduce**

1. Log in as a patient using a phone number.
2. Click on a schedule and register an appointment for a new patient.
3. After successful registration, go to the Patient Dashboard and attempt to switch to the newly added patient.
4. Notice that the new patient does not appear in the dropdown.

**Expected behavior**

The patient dropdown should automatically update to include the newly registered patient as soon as the registration process is completed.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by Mahendar0701**
## Proposed Changes

- Fixes #10718
- Fixed : Patient search bar auto focus on visiting 

https://github.com/user-attachments/assets/b8fadca7-78f3-4c5d-a2a9-d1fb66840b98

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Enhanced search inputs now automatically receive focus upon rendering, allowing users to start typing immediately for a smoother and more efficient experience.
  - Updated keyboard shortcut functionality to better handle input fields, improving user interaction and workflow efficiency.

### CODE REVIEW

File: src/components/Common/SearchByMultipleFields.tsx
Comment (rithviknishad) [inline src/components/Common/SearchByMultipleFields.tsx:1]: pass inputRef to the component instead. autoFocus behaviour is manually controlled based on other states and side effects.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — DISMISSED** [review]

File: src/components/ui/phone-input.tsx
Comment (Rishith25) [inline src/components/ui/phone-input.tsx:1]: @Mahendar0701 In the deploy preview I cannot enter any phone number in entire care

cc:@rithviknishad 
Screenshot_2025_0224_103514

**Comment by nihal467** [comment]
@Mahendar0701 @rithviknishad the entire patient creation is broken since patient number aren't allow to enter in your PR

File: src/components/ui/phone-input.tsx [hunk 1]
```diff
@@ -48,7 +49,9 @@ const PhoneInput: React.ForwardRefExoticComponent<PhoneInputProps> =
           )}
           flagComponent={FlagComponent}
           countrySelectComponent={CountrySelect}
-          inputComponent={InputComponent}
+          inputComponent={(inputProps) => (
+            <InputComponent {...inputProps} ref={inputRef} />
+          )}
```
Comment (rithviknishad) [inline src/components/ui/phone-input.tsx]: i don't think this is a good idea. Have you checked if inputComponent itself is passing the ref? if so, we can't override it.

Comment (Mahendar0701) [reply src/components/ui/phone-input.tsx]: And if i pass inputRef as prop in phone-input then a type mismatch error is coming

image


I think the below approach works fine, what you think? should i do this?

cc : @Jacobjeevan 

```tsx

            <PhoneInput
              id={id}
              name={selectedOption.key}
              placeholder={selectedOption.placeholder}
              value={searchValue}
              onChange={(value) => setSearchValue(value)}
              className={inputClassName}
              autoFocus={autoFocus}
            />
            
```

**Comment by Mahendar0701** [comment]
Moving issue https://github.com/ohcnetwork/care_fe/issues/10723  to PR https://github.com/ohcnetwork/care_fe/pull/10819. That is done and can be merged

**Comment by nihal467** [comment]
@Mahendar0701 what is the status of this PR

**Comment by Mahendar0701** [comment]
> @Mahendar0701 what is the status of this PR

Waiting for confirmation from @rithviknishad https://github.com/ohcnetwork/care_fe/pull/10736#discussion_r1969758234

Should i pass autofocus Prop to phone-input? becz on passing inputRef a type mismatch is occuring

**Comment by rithviknishad** [comment]
> > @Mahendar0701 what is the status of this PR
> 
> Waiting for confirmation from @rithviknishad [#10736 (comment)](https://github.com/ohcnetwork/care_fe/pull/10736#discussion_r1969758234)
> 
> Should i pass autofocus Prop to phone-input? becz on passing inputRef a type mismatch is occuring

Nah, let's ignore it... phone input is not passing any refs.

image

**Comment by nihal467** [comment]
@Mahendar0701 fix the cypress failure

**Comment by Jacobjeevan** [comment]
@Mahendar0701 Phone number is still broken.

**Comment by rithviknishad** [comment]
merge checklist not followed;

**Comment by Mahendar0701** [comment]
@rithviknishad @Jacobjeevan can you reopen this PR i followed merge checklist

**Comment by nihal467** [comment]
@Mahendar0701, the cypress is still not fixed. can you share the EOD for this PR?

**Comment by Mahendar0701** [comment]
@nihal467 all tests passing

Self review:
Used autofocus prop instead of inputRef as this is causing type mismatch error everytime

cc @rithviknishad 

End date : today itself if everything goes well

**Comment by nihal467** [comment]
image

- [ ] now the element is always focus on the search bar, the shift + P shortcut is not at all working, how are you planning to handle that issue caused by this PR ?

**Comment by Mahendar0701** [comment]
> image
> 
> * [ ]  now the element is always focus on the search bar, the shift + P shortcut is not at all working, how are you planning to handle that issue caused by this PR ?

@nihal467 SHIFT + P works when search bar gets unfocused by clicking outside.

If it is a requirement to get SHIFT+P work even on focus , then i will proceed to update this PR with that

Can you plz confirm it ??

**Comment by Jacobjeevan** [comment]
> > image
> > 
> > * [ ]   now the element is always focus on the search bar, the shift + P shortcut is not at all working, how are you planning to handle that issue caused by this PR ?
> 
> @nihal467 SHIFT + P works when search bar gets unfocused by clicking outside.
> 
> If it is a requirement to get SHIFT+P work even on focus , then i will proceed to update this PR with that
> 
> Can you plz confirm it ??

Since we are auto-focusing on the input, shortcut should work regardless, yes.

**Comment by Mahendar0701** [comment]
@rithviknishad @Jacobjeevan i have updated the PR can you once take a look. Now keyboard shortcut works even if search bar is focused

File: src/components/Patient/PatientIndex.tsx [hunk 2]
```diff
@@ -55,7 +54,19 @@ export default function PatientIndex({ facilityId }: { facilityId: string }) {
     });
   }, [facilityId, phoneNumber]);
 
-  useKeyboardShortcut(["shift", "p"], handleCreatePatient);
+  useEffect(() => {
```
Comment (abhimanyurajeesh) [inline src/components/Patient/PatientIndex.tsx]: Why don't we useKeyboardShortcut itself!?

look into the [docs](https://use-keyboard-shortcut.tyukayev.com/) this might help.

Comment (Mahendar0701) [reply src/components/Patient/PatientIndex.tsx]: I already checked out that, but it is not working with `ignoreInputFields: true,` i guess something is stopping it from propagating

Comment (Jacobjeevan) [reply src/components/Patient/PatientIndex.tsx]: @Mahendar0701 It should be set to false, not true :) Default is true.

Comment (Mahendar0701) [reply src/components/Patient/PatientIndex.tsx]: > @Mahendar0701 It should be set to false, not true :) Default is true.

Sry my bad 😢

**Review by rithviknishad — APPROVED** [review]
