### PR TITLE
Fixes Issue #11009:  Changes in the code to disable adding exceptions before date

### LINKED ISSUE #11009: Nurse Able to Add Schedule/Exception for Past Dates
The issue is that staff members can add exception days (unavailable days) for past dates, which should not be allowed. This could lead to inconsistencies in scheduling and affect availability tracking

Disable Past Dates in Date Picker: Modify the date picker component to allow selection only from the current date onward.This is the solution that can be done in UI side itself

Alternatively, we can add Validation Message – Display a tooltip or error message if a user manually enters a past date.

Image

### PR DESCRIPTION
**Pull request by sj11105**
## Related (but not required) backend PRs

- https://github.com/ohcnetwork/care/pull/2959

## Proposed Changes

- Fixes #11009 
-Made change in The calender component to not go previous month from today
-Made changes in the form schema to allow exceptions only from today 
-Giving message if tries to add exception before today
Screenshot 2025-03-05 170916

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Bug Fixes**
  - Enhanced scheduling validations to ensure dates are today or in the future and that time inputs follow a logical, sequential order.
  - Refined error messages now provide clearer guidance when inputs do not meet required criteria, including new messages for scheduling and exception creation for past dates.
  - Added validation to enforce start times in exceptions to be in the future when applicable.

- **Refactor**
  - Standardized date and time handling across scheduling forms by transitioning to the `dayjs` library for improved performance and simplicity.
  - Updated user-facing text to improve clarity and prevent scheduling errors, including the removal of outdated validation messages.

### CODE REVIEW

**Comment by NikhilA8606** [comment]
Complete the merge checklist

File: src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:1]: Hmm, actually let's not change the schedule templates - allow users to create them in case they need to back-fill in data.

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx [hunk 1]
```diff
@@ -73,26 +72,35 @@ export default function CreateScheduleExceptionSheet({
         .min(1, t("field_required")) as unknown as z.ZodType<Time>,
       unavailable_all_day: z.boolean(),
     })
+    .refine((data) => !isAfter(data.valid_from, data.valid_to), {
+      message: t("from date must be before to date"),
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: Why move this up? 🤔  Let's move it back down and add the new one below it (also check translation; changed the existing key, this one wouldn't work).

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx
Comment (sj11105) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:1]: @Jacobjeevan  okay ,so only they should not be able to add exceptional days before date?

File: src/CAREUI/interactive/Calendar.tsx
Comment (rithviknishad) [inline src/CAREUI/interactive/Calendar.tsx:1]: why was this file modified? 🤔 

this is a reusable component and i don't see any reason why we should be disabling moving to previous month here.

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx (hunk 1 above)
Comment (sj11105) [reply src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: @Jacobjeevan  okay , i will make the changes

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx [hunk 2]
```diff
@@ -73,26 +72,35 @@ export default function CreateScheduleExceptionSheet({
...
+      (data) => {
+        const today = new Date();
+        today.setHours(0, 0, 0, 0);
+        return !isBefore(data.valid_from, today);
+      },
+      {
+        message: t("from  date must be today or future"),
+        path: ["valid_from"],
+      },
+    )
```
Comment (rithviknishad) [inline src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: i don't see any reason or advantage on preventing `valid_from` being in the past.

let's not be too restrictive. 

the only restriction i'd bring is, `valid_to` being in the past.

Comment (sj11105) [reply src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: @rithviknishad okay so you just want the valid_to be the present date or future and not past dates from today?

**Comment by sj11105** [comment]
@rithviknishad, @Jacobjeevan  Hey i have made changes as per the requirement . Please do check

File: src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx
Comment (Jacobjeevan) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:1]: Refer to Rithvik's comment above - restrict only `valid_to` date for exception. Discard all other changes 👍

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by sj11105** [comment]
@Jacobjeevan  Yes i have made restrictions to only valid to date all other things were already present

**Comment by sj11105** [comment]
Screenshot 2025-03-10 131537

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx [hunk 3]
```diff
@@ -59,12 +59,15 @@ export default function CreateScheduleExceptionSheet({
...
-
   const formSchema = z
     .object({
       reason: z.string().min(1, t("field_required")),
       valid_from: z.date({ required_error: t("field_required") }),
-      valid_to: z.date({ required_error: t("field_required") }),
+      valid_to: z
+        .date({ required_error: t("field_required") })
+        .refine((date) => date > new Date(), {
+          message: t("date_must_be_future"),
```
Comment (abhimanyurajeesh) [inline src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: - [ ] Ensure that UI text is kept in I18n files.

Please add all the mssing translations in en.json

Comment (sj11105) [reply src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: @abhimanyurajeesh  Hey, I have added the translations

File: src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx
Comment (Jacobjeevan) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:1]: @sj11105  ☝️  Please discard other changes.

Comment (sj11105) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:1]: @Jacobjeevan  Hey, i have discarded all other changes and only the valid_to date has restriction now. I have even shared a screenshot regarding the same . Still if you find any changes please let me know.

Comment (Jacobjeevan) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:1]: > @Jacobjeevan Hey, i have discarded all other changes and only the valid_to date has restriction now. I have even shared a screenshot regarding the same . Still if you find any changes please let me know.

https://github.com/ohcnetwork/care_fe/pull/11044/files

@sj11105  Check this tab, only changes should be in en.json and in CreateScheduleExceptionSheet.tsx. Discard everything else.

Comment (sj11105) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:1]: @Jacobjeevan  yes the changes are in those two files only , in the calender one i deleted the changes thats why it is showing changes made. I made the calender component as it was before.

Comment (Jacobjeevan) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:1]: Did you check the link I sent? There are still 4 files in the commit, instead of 2.

Changes to CreateScheduleTemplateSheet are still present. You would need to reset the changes there (you can do so using `git checkout` command).

Comment (sj11105) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:1]: @Jacobjeevan  Please check now

**Review by Jacobjeevan — APPROVED** [review]

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx [hunk 4]
```diff
@@ -59,12 +59,15 @@ export default function CreateScheduleExceptionSheet({
...
+        }),
```
Comment (rithviknishad) [inline src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: this may not always work for "today" situation due to difference in time of the day;

use utility fns. to achieve it instead;

**Review by rithviknishad — CHANGES_REQUESTED** [review]
let's also prevent creating schedules in the past as well;

**Comment by sj11105** [comment]
> let's also prevent creating schedules in the past as well;

@rithviknishad  So you want it to be as it was done for the first time that the user can only make exceptions for the future date .Right?

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx (hunk 4 above)
Comment (sj11105) [reply src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: @rithviknishad Ok i will make changes accordingly

**Comment by sj11105** [comment]
@rithviknishad  I have made the changes. I hope this is what you required.

**Comment by nihal467** [comment]
LGTM

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx [hunk 5]
```diff
@@ -60,41 +60,60 @@ export default function CreateScheduleExceptionSheet({
...
       reason: z.string().min(1, t("field_required")),
-      valid_from: z.date({ required_error: t("field_required") }),
-      valid_to: z.date({ required_error: t("field_required") }),
+
+      // Ensure valid_from is today or future
+      valid_from: z
+        .date({ required_error: t("field_required") })
+        .refine((date) => dayjs(date).isAfter(dayjs().subtract(1, "day")), {
+          message: t("date_must_be_future"),
+        }),
```
Comment (rithviknishad) [inline src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: why complicate the logic? 🤔 

can't we simply use `.max` instead? 🤔 

refer docs: https://zod.dev/?id=dates-1

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx [hunk 6]
```diff
@@ -82,12 +82,20 @@ export default function CreateScheduleTemplateSheet({
...
-      valid_to: z.date({
-        required_error: t("field_required"),
-      }),
+      valid_from: z
+        .date({
+          required_error: t("field_required"),
+        })
+        .min(dayjs().startOf("day").toDate(), {
+          message: t("date_must_be_today_or_future"),
+        }),
```
Comment (rithviknishad) [inline src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx]: i think we should say: "A schedule cannot be created in the past.".

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx (hunk 6 above)
Comment (sj11105) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx]: @rithviknishad  i have changed the message

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx [hunk 7]
```diff
@@ -60,41 +60,63 @@ export default function CreateScheduleExceptionSheet({
...
-        path: ["start_time"], // This will show the error on the start_time field
+      (data) => {
+        const startTime = dayjs(data.start_time, "HH:mm");
+        const endTime = dayjs(data.end_time, "HH:mm");
+        return {
+          message: startTime.isBefore(endTime)
+            ? t("start_time_must_be_before_end_time")
+            : t("start_time_must_be_in_the_future"),
+          path: ["start_time"],
+        };
```
Comment (rithviknishad) [inline src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: can we maintain two separate refines for this? 🤔 

avoid mixing two validations into one.

**Review by rithviknishad — CHANGES_REQUESTED** [review]
i've made some improvements; do check them as well;

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx (hunk 7 above)
Comment (sj11105) [reply src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: @rithviknishad  Please check now

**Review by rithviknishad — DISMISSED** [review]
lgtm

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
image

the logic is incorrect

**Comment by sj11105** [comment]
> image
> 
> the logic is incorrect

I will check and correct this by today

File: src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx [hunk 8]
```diff
@@ -144,10 +148,13 @@ export default function CreateScheduleTemplateSheet({
         )
         .min(1, t("schedule_sessions_min_error")),
     })
-    .refine((data) => !isAfter(data.valid_from, data.valid_to), {
-      message: t("from_date_must_be_before_to_date"),
-      path: ["valid_from"],
-    });
+    .refine(
+      (data) => !dayjs(data.valid_to).isAfter(dayjs(data.valid_from), "day"),
```
Comment (NikhilA8606) [inline src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx]: this logic checks "valid_to must be on or before valid_from" which is incorrect

Comment (sj11105) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx]: @NikhilA8606  @rithviknishad  I have corrected the logic please check now

**Comment by NikhilA8606** [comment]
image
Why isn't there a validation check for this condition?

**Comment by sj11105** [comment]
> image Why isn't there a validation check for this condition?

@NikhilA8606  I changed only the exception creation files but i will make changes for schedules as well by eod

**Comment by sj11105** [comment]
> image Why isn't there a validation check for this condition?
@NikhilA8606  there are validations 
Screenshot 2025-04-05 122819

**Comment by NikhilA8606** [comment]
> > image Why isn't there a validation check for this condition?
> > @NikhilA8606  there are validations
> > Screenshot 2025-04-05 122819

Use the dates I mentioned for testing

**Comment by sj11105** [comment]
> > > image Why isn't there a validation check for this condition?
> > > @NikhilA8606  there are validations
> > > Screenshot 2025-04-05 122819
> 
> Use the dates I mentioned for testing

@NikhilA8606  I have made the changes Please check
Screenshot 2025-04-06 131043

File: src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx [hunk 9]
```diff
@@ -150,7 +150,7 @@ export default function CreateScheduleTemplateSheet({
     })
     .refine(
       (data) => dayjs(data.valid_to).isAfter(dayjs(data.valid_from), "day"),
-      { message: "valid_to must be after valid_from" },
+      { message: "to_date_equal_or_after_from_date", path: ["valid_to"] },
```
Comment (NikhilA8606) [inline src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx]: Add proper translation : ` { message: t("to_date_equal_or_after_from_date"), path: ["valid_to"] }`

Comment (sj11105) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx]: @NikhilA8606 Please check now

**Comment by nihal467** [comment]
image

@sj11105 the same date should be allowed, the validation is not working properly

**Comment by sj11105** [comment]
> image
> 
> @sj11105 the same date should be allowed, the validation is not working properly

@nihal467 Please check now, i have corrected the logic

**Review by NikhilA8606 — APPROVED** [review]

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx [hunk 10]
```diff
@@ -64,37 +64,60 @@ export default function CreateScheduleExceptionSheet({
...
+        }
+        return true;
+      },
+      {
+        message: t("start_time_must_be_in_the_future"),
+        path: ["start_time"],
+      },
+    )
+    .refine(
+      (data) => dayjs(data.valid_to).isAfter(dayjs(data.valid_from), "day"),
```
[the remark this answers is not in the document]
Comment (Jacobjeevan) [reply src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: Changes required.

image

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by sj11105** [comment]
@Jacobjeevan I have made the required changes. Please check now
Screenshot 2025-04-09 140304

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
