### PR TITLE
FIXED: Input Fields Overflow on Add Camera Device Page

### LINKED ISSUE #12321: Input Fields Overflow on Add Camera Device Page
**Describe the bug**
Input fields overflow horizontally on smaller screens, breaking the layout.

**To Reproduce**

**Expected behavior**
Input fields should remain fully visible and aligned within the form container without causing horizontal scroll.

**Screenshots**

https://github.com/user-attachments/assets/76e67b31-424f-43e6-b3eb-b3fa09091f9c

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes
add grid to the PluginDeviceConfigureForm main div

- Fixes #12321 

https://github.com/user-attachments/assets/c613fc89-06ce-4093-bb4d-cc765cd9ef0d

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Improved layout of the device configuration form for better spacing and alignment.

### CODE REVIEW

**Comment by rithviknishad** [comment]
@modamaan please follow merge checklist! PRs wont be reviewed without them!

**Comment by nihal467** [comment]
LGTM

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx [hunk 1]
```diff
@@ -573,7 +573,7 @@ export default function DeviceForm({ facilityId, device, onSuccess }: Props) {
               control={form.control}
               name="metadata"
               render={({ field }) => (
-                <FormItem className="space-y-0">
+                <FormItem className="space-y-0 grid grid-cols-1 gap-4">
```
Comment (rithviknishad) [inline src/pages/Facility/settings/devices/components/DeviceForm.tsx]: why should this be a grid? 🤔 
```suggestion
                <FormItem className="space-y-0 block">
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]
