### PR TITLE
fix: Mark as Discharge

### LINKED ISSUE #11811: Mark as Discharge
Image

1. On setting Encounter Status dropdown to Discharged

- Show a text area "Discharge Summary Advice" (encounter.discharge_summary_advice) after Hospital identifier
- If Hospitalization exists, show Discharge Disposition dropdown (https://build.fhir.org/valueset-encounter-discharge-disposition.html)
- Add a Date time field (encounter.period.end)

2. In Hospitalization, show a checkbox if encounter status isn't Discharged - Mark Patient for discharge (in your words). Checking this box should set status as discharged which would in turn trigger the fields in #1

### PR DESCRIPTION
**Pull request by abhimanyurajeesh**
## Proposed Changes

- BE https://github.com/ohcnetwork/care/pull/2988
- Fixes #11811 

    - Updated en.json to include translations for discharge summary advice and related fields.
    - Enhanced EncounterActions to handle discharge summary advice.
    - Implemented discharge summary advice input in EncounterQuestion component, displayed conditionally based on encounter status.
    - Updated structured handlers to include discharge summary advice in encounter data processing.
    - Modified Encounter interface and related request types to accommodate discharge summary advice.
    - Updated en.json to include translations for discharge summary advice and related fields.
    - Enhanced EncounterActions to handle discharge summary advice.
    - Implemented discharge summary advice input in EncounterQuestion component, displayed conditionally based on encounter status.
    - Updated structured handlers to include discharge summary advice in encounter data processing.
    - Modified Encounter interface and related request types to accommodate discharge summary advice.

@ohcnetwork/care-fe-code-reviewers

https://github.com/user-attachments/assets/2a4fdae5-57cf-4040-ab24-29e2b0730fe2

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
	- Enhanced patient discharge workflow with a dedicated section for entering and viewing discharge summary advice.
	- Added controls for marking patients for discharge, including setting discharge date and time.
	- Improved UI messaging and labels for clearer discharge-related actions.
	- Included new discharge-related properties in data structures to support discharge advice.
	- Introduced a discharge information section showing date, time, and summary advice with toggleable text visibility.
	- Added confirmation alert dialogs for discharge actions to improve user awareness.
	- Streamlined updating discharge details and managing patient status.

### CODE REVIEW

**Comment by amjithtitus09** [comment]
@abhimanyurajeesh 
1. Check box missing?
image

2. Prefill current date as well
image

3. Match the height of nearby fields in date and time fields

4. Hospitalization object not being reset when hidden from UI. Being sent in the request even when not shown in UI

5. Something's wrong with the Dischage Advice field while typing in. Cursor auto moves to the end

File: src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx [hunk 1]
```diff
@@ -295,50 +379,138 @@ export function EncounterQuestion({
...
+                              ? date < new Date(encounter.period.start)
+                              : false
+                          }
+                        />
+                      </PopoverContent>
+                    </Popover>
+                    <Input
+                      type="time"
+                      className="flex-1 border-t-0 sm:border-t text-sm border-gray-200 h-9"
+                      value={
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx]: not a huge fan of deviating away from the design system

File: src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx [hunk 2]
```diff
@@ -153,6 +174,15 @@ export function EncounterQuestion({
...
+                ...(value === "discharged" && {
+                  period: {
+                    ...encounter.period,
+                    end: new Date().toISOString(),
+                  },
+                }),
+                ...(value !== "discharged" && {
+                  discharge_summary_advice: null,
+                }),
               })
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx]: code would be more rigid if this was handled in a `useEffect` instead

**Review by rithviknishad — DISMISSED** [review]

File: src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx (hunk 2 above)
Comment (abhimanyurajeesh) [reply src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx]: yes done

File: src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx [hunk 3]
```diff
@@ -110,6 +141,11 @@ export function EncounterQuestion({
     }
   }, [questionnaireResponse]);
 
+  // Update local state when encounter data changes
+  useEffect(() => {
+    setDischargeAdvice(encounter.discharge_summary_advice || "");
+  }, [encounter.discharge_summary_advice]);
+
```
Comment (amjithtitus09) [inline src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx]: Is this necessary now that the BE is fixed?

File: src/types/emr/encounter.ts [hunk 4]
```diff
@@ -182,6 +183,7 @@ export interface EncounterEditRequest {
   priority: EncounterPriority;
   external_identifier?: string;
   facility: string;
+  discharge_summary_advice?: string | null;
```
Comment (amjithtitus09) [inline src/types/emr/encounter.ts:186]: Is "| null" needed if already optional?

**Review by amjithtitus09 — CHANGES_REQUESTED** [review]
Minor changes

**Comment by nihal467** [comment]
- UI need to be modified based on input from @amjithtitus09 
image
image

- when a patient is marked as discharge, don't auto-select "Other" -> Admit Source , "Home" -> Discharge Disposition and "None" -> Diet preference dropdown fields

image

- Same-day discharge is not working
- Add a display to show the discharge advice in the encounter
- Add a display to show the discharge disposition in the encounter

**Comment by nihal467** [comment]
-> Add the discharge advice in the treatment summary
-> When we select a admit source, the discharge disposition and diet preference are auto-fill, do fix the state

**Comment by abhimanyurajeesh** [comment]
> -> Add the discharge advice in the treatment summary -> When we select a admit source, the discharge disposition and diet preference are auto-fill, do fix the state



@nihal467 Okay ?

**Comment by nihal467** [comment]
LGTM

File: src/components/Facility/ConsultationDetails/QuickAccess.tsx [hunk 5]
```diff
@@ -124,55 +137,119 @@ export default function QuickAccess({ encounter, canEdit }: QuickAccessProps) {
...
+                          !showFullText[encounter.id] && "line-clamp-2",
+                        )}
+                      >
+                        {encounter.discharge_summary_advice}
+                      </p>
+                      {encounter.discharge_summary_advice.length > 100 && (
+                        <Button
+                          variant="link"
+                          className="p-0 h-auto font-sm text-gray-500 hover:text-gray-800"
+                          onClick={() => toggleShowMore(encounter.id)}
```
Comment (amjithtitus09) [inline src/components/Facility/ConsultationDetails/QuickAccess.tsx]: Not sure about the use of key value pair if we're gonna pass in encounter id here

File: src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx [hunk 6]
```diff
@@ -94,10 +117,34 @@ export function EncounterQuestion({
...
   // Update encounter state when data is loaded
   useEffect(() => {
     if (encounterData) {
-      handleUpdateEncounter(encounterData as unknown as EncounterEditRequest);
+      const updatedEncounterData = {
+        ...encounterData,
+        hospitalization: {
+          ...encounterData.hospitalization,
+          re_admission: encounterData.hospitalization?.re_admission ?? false,
```
Comment (amjithtitus09) [inline src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx]: Would there be a scenario where hospitalization exists with re_admission undefined?

**Review by amjithtitus09 — CHANGES_REQUESTED** [review]
Looks good, minor change

File: src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx (hunk 6 above)
Comment (abhimanyurajeesh) [reply src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx]: It happened while testing, but anyways this is not needed as we are hiding in overview.

**Comment by amjithtitus09** [comment]
@abhimanyurajeesh Existing end date isn't loading, shows the current date in discharge date & time field
image

File: src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx [hunk 7]
```diff
@@ -230,6 +274,75 @@ export function EncounterQuestion({
...
+            <Textarea
+              defaultValue={encounter.discharge_summary_advice || ""}
+              onChange={(e) => {
+                handleUpdateEncounter({
+                  discharge_summary_advice: e.target.value || null,
+                });
+              }}
+              disabled={disabled}
+              placeholder={t("enter_discharge_summary_advice")}
+            />
```
[the remark this answers is not in the document]
Comment (rithviknishad) [reply src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx:340]: not a priority, but we should be addressing this, feel free to create separate issue since this is a P1

**Comment by nihal467** [comment]
non related issue, you can work post this PR, as separate issue

image

- hide the update hospitalisation detail button for a discharge marked patient
- in the update encounter page, add a backend validation that incase users manually open the page, backend should reject it

File: src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx [hunk 8]
```diff
@@ -119,16 +119,22 @@ export function EncounterQuestion({
...
+      }
+    } else {
       handleUpdateEncounter({
+        discharge_summary_advice: null,
         period: {
           ...encounter.period,
-          end: new Date().toISOString(),
+          end: undefined,
         },
       });
```
Comment (amjithtitus09) [inline src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx]: image

Discharge disposition still going through when status changed from discharged to in-progress although hidden from UI.
@bodhish Is this a valid scenario?

Comment (amjithtitus09) [inline src/components/Questionnaire/QuestionTypes/EncounterQuestion.tsx]: Just realised something, while changing status from discharge to completed, we lose all the discharge specific data.

**Review by amjithtitus09 — CHANGES_REQUESTED** [review]
Need to decide on when to clear data and when not to. Keep this on hold until we reach a conclusion

**Comment by amjithtitus09** [comment]
@abhimanyurajeesh For discharge advice and discharge disposition, never reset existing data. Also when data exists in these fields, don't hide them. End date can be reset when status changes from discharged to other statuses(except completed). Don't lose any data while changing to completed (blunder we overlooked).

**Comment by nihal467** [comment]
LGTM

**Review by amjithtitus09 — APPROVED** [review]
