### PR TITLE
refactor: update terminology for questionnaire responses and forms + fixes questionnaire update issue

### LINKED ISSUE #14230: Unable to update a questionnaire status due to version issue
**Describe the bug**

When we are trying to update the status of an exist questionnaire to a new status in the questionnaire dashboard, the version error is thrown by the backend

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by abhimanyurajeesh**
## Proposed Changes

Fixes #14230
This issue
image

Let me know if i missed any

image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.

## Summary by CodeRabbit

- New Features
  - Added new translations: “Responses,” “No responses found,” and “Select Forms.”
  - Unified terminology from “Questionnaire” to “Forms/Responses” across lists, tabs, and history views.
  - Updated search placeholders to reference “Forms.”

- Style
  - Improved small-screen readability for the search input.

- Chores
  - Refreshed locale mappings and replaced outdated translation keys across relevant pages.

### CODE REVIEW

**Review by yash-learner — COMMENTED** [review]
Shouldn't  we also update the placeholder text on trigger button ?


image

**Comment by tasnimshaji** [comment]
LGTM @nihal467

**Comment by nihal467** [comment]
@abhimanyurajeesh Looks good to me, adjust the existing Cypress test since its breaking

**Comment by abhimanyurajeesh** [comment]
@nihal467 CY is been fixed.

**Comment by nihal467** [comment]
LGTM

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 1]
```diff
@@ -751,6 +751,7 @@ export default function QuestionnaireEditor({ id }: QuestionnaireEditorProps) {
     if (id) {
       updateQuestionnaire({
         ...form.getValues(),
+        version: String(questionnaire.version),
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]: this is not the right fix. why is it becoming number in the first place? fix the root cause instead

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/QuestionnaireEditor.tsx (hunk 1 above)
Comment (abhimanyurajeesh) [reply src/components/Questionnaire/QuestionnaireEditor.tsx]: Its actually a BE issue, Adding a TODO to remove this once that's fixed

**Review by rithviknishad — APPROVED** [review]
