### PR TITLE
Dosage heading is misaligned in the prescription module #8645

### LINKED ISSUE #8645: Dosage heading is misaligned in the prescription module
**Describe the bug**

When we create a PRN prescription with a large note, the dosage heading is misaligned in the normal view

**To Reproduce**

1. Go to patient consultation page
2. Click on medicine and add a medicine (PRN) with a long indicator
3. See error

**Expected behavior**

- [ ] the dosage heading in the prn prescription should be center aligned

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Sulochan-khadka**
## Proposed Changes

- Fixes #8645 
- added css (elipsis) for alignment

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Improved localization for the medicine administration table headers.
	- Introduced a new `DosageFrequencyInfo` component to enhance the display of dosage information based on prescription details.

- **Bug Fixes**
	- Simplified header structure for better clarity and maintainability.

### CODE REVIEW

**Comment by Sulochan-khadka** [comment]
Added elipsis as it seemed a bit clean and aligned.
Screenshot 2024-10-10 at 1 04 11 AM

Whereas with wrapping it in new line, the width adjustment seems somewhat wrong(alignment):
Screenshot 2024-10-10 at 1 04 53 AM

Do let me know in case of any changes.

**Comment by Sulochan-khadka** [comment]
@nihal467 @rithviknishad kindly review the PR .

File: src/Components/Medicine/MedicineAdministrationSheet/AdministrationTableRow.tsx [hunk 1]
```diff
@@ -222,7 +222,7 @@ export default function MedicineAdministrationTableRow({
                 </p>
               )}
 
-              <p>
+              <p className="max-w-[110px] truncate">
```
Comment (rithviknishad) [inline src/Components/Medicine/MedicineAdministrationSheet/AdministrationTableRow.tsx]: avoid hardcoding arbitrary pixel values. This will lead to different results in different browser zoom settings. Use rem values instead of a built-in class doesn't suffice

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Medicine/MedicineAdministrationSheet/AdministrationTableRow.tsx (hunk 1 above)
Comment (Sulochan-khadka) [reply src/Components/Medicine/MedicineAdministrationSheet/AdministrationTableRow.tsx]: 6 rem is working fine... Shall i add that? What do you think?

Comment (rithviknishad) [reply src/Components/Medicine/MedicineAdministrationSheet/AdministrationTableRow.tsx]: Yup

**Comment by nihal467** [comment]
image

- [ ] keep everything in the center , in your current solution heading , excess indicator medicine and medicine with limited indicator, all are in multiple alignment

**Comment by Sulochan-khadka** [comment]
> image
> 
> * [ ]  keep everything in the center , in your current solution heading , excess indicator medicine and medicine with limited indicator, all are in multiple alignment

@nihal467 the parts medicine and dosage are not separate table columns but a single div with "justify-between" . Do you want me to change them to separate table columns?

**Comment by rithviknishad** [comment]
Yup, let's try that.

**Comment by Sulochan-khadka** [comment]
Here is the improvement @nihal467 @rithviknishad 
Screenshot 2024-10-23 at 5 44 53 PM

Improvement:
Screenshot 2024-10-23 at 5 45 18 PM

**Comment by nihal467** [comment]
@Sulochan-khadka can you clear the merge conflict

CC: @rithviknishad

**Comment by Sulochan-khadka** [comment]
> @Sulochan-khadka can you clear the merge conflict
> 
> CC: @rithviknishad

While merging , it is showing error in this line :
"import { pluginMap } from "./pluginMap"; " Does this file exists. @nihal467 @rithviknishad

**Comment by Jacobjeevan** [comment]
> While merging , it is showing error in this line : "import { pluginMap } from "./pluginMap"; " Does this file exists. @nihal467 @rithviknishad

https://github.com/ohcnetwork/care_fe?tab=readme-ov-file#install-the-required-dependencies will create the file

**Comment by Sulochan-khadka** [comment]
@nihal467 @rithviknishad Let me know if anything else is required.

File: src/components/Medicine/MedicineAdministrationSheet/AdministrationTable.tsx [hunk 2]
```diff
@@ -27,17 +27,17 @@ export default function MedicineAdministrationTable({
...
-              </div>
+              <span className="text-sm">{t("medicine")}</span>
+            </th>
+            <th>
+              <span className="hidden px-2 text-center text-xs leading-none lg:block">
+                <p>Dosage &</p>
+                <p>
+                  {prescriptions[0]?.dosage_type !== "PRN"
+                    ? "Frequency"
+                    : "Indicator"}
```
Comment (rithviknishad) [inline src/components/Medicine/MedicineAdministrationSheet/AdministrationTable.tsx]: let's keep this in i18n

File: src/components/Medicine/MedicineAdministrationSheet/AdministrationTable.tsx [hunk 3]
```diff
@@ -27,17 +27,17 @@ export default function MedicineAdministrationTable({
...
-              </div>
+              <span className="text-sm">{t("medicine")}</span>
+            </th>
+            <th>
+              <span className="hidden px-2 text-center text-xs leading-none lg:block">
+                <p>Dosage &</p>
+                <p>
+                  {prescriptions[0]?.dosage_type !== "PRN"
+                    ? t("Frequency")
+                    : t("Indicator")}
```
Comment (rithviknishad) [inline src/components/Medicine/MedicineAdministrationSheet/AdministrationTable.tsx]: are you sure this is the correct keys?
```suggestion
                    ? t("frequency")
                    : t("indicator")}
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Medicine/MedicineAdministrationSheet/AdministrationTable.tsx (hunk 3 above)
Comment (Sulochan-khadka) [reply src/components/Medicine/MedicineAdministrationSheet/AdministrationTable.tsx]: 👍🏿

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image
image

@Sulochan-khadka 
- [ ] In mobile view, the indicator and dosage should be displayed below the medicine and other details, as seen on current develop. This behavior is breaking in your PR, so please ensure it remains consistent.

**Comment by Sulochan-khadka** [comment]
> image image
> 
> @Sulochan-khadka
> 
> * [ ]  In mobile view, the indicator and dosage should be displayed below the medicine and other details, as seen on current develop. This behavior is breaking in your PR, so please ensure it remains consistent.

made the necessary changes. The result is:

Screenshot 2024-11-09 at 5 34 03 AM

File: src/components/Medicine/MedicineAdministrationSheet/AdministrationTableRow.tsx [hunk 4]
```diff
@@ -59,6 +59,25 @@ export default function MedicineAdministrationTableRow({
       key: `${prescription.last_administration?.administered_date}`,
     },
   );
+  const TableContent = () => (
```
Comment (rithviknishad) [inline src/components/Medicine/MedicineAdministrationSheet/AdministrationTableRow.tsx]: proper names for components are appreciated. Also consider keeping this defined outside function and pass prescription as prop.

```suggestion
  const DosageFrequencyInfo = () => (
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Medicine/MedicineAdministrationSheet/AdministrationTable.tsx [hunk 5]
```diff
@@ -31,17 +31,17 @@ export default function MedicineAdministrationTable({
...
-                      ? "Frequency"
-                      : "Indicator"}
-                  </p>
-                </span>
-              </div>
+              <span className="text-sm">{t("medicine")}</span>
+            </th>
+            <th>
+              <span className="hidden px-2 text-center text-xs leading-none lg:block">
+                <p>Dosage &</p>
```
Comment (rithviknishad) [inline src/components/Medicine/MedicineAdministrationSheet/AdministrationTable.tsx]: use translations for the text "Dosage"

File: src/components/Medicine/MedicineAdministrationSheet/AdministrationTableRow.tsx [hunk 6]
```diff
@@ -216,24 +235,14 @@ export default function MedicineAdministrationTableRow({
...
-                </p>
-              )}
-
-              <p>
-                {prescription.dosage_type !== "PRN"
-                  ? t("PRESCRIPTION_FREQUENCY_" + prescription.frequency)
-                  : prescription.indicator}
-              </p>
+            <div className="block lg:hidden">
+              <TableContent />
```
Comment (rithviknishad) [inline src/components/Medicine/MedicineAdministrationSheet/AdministrationTableRow.tsx]:
```suggestion
              <DosageFrequencyInfo />
```

File: src/components/Medicine/MedicineAdministrationSheet/AdministrationTableRow.tsx [hunk 7]
```diff
@@ -216,24 +235,14 @@ export default function MedicineAdministrationTableRow({
...
             </div>
           </div>
         </td>
+        <td className="hidden lg:table-cell">
+          <TableContent />
```
Comment (rithviknishad) [inline src/components/Medicine/MedicineAdministrationSheet/AdministrationTableRow.tsx]:
```suggestion
          <DosageFrequencyInfo />
```

**Review by rithviknishad — APPROVED** [review]
