### PR TITLE
FIx :  Validation Messages Remain in Previous Language

### LINKED ISSUE #11540: Validation Messages Remain in Previous Language Until Second Submit
**Describe the bug**
Validation error messages in the login form do not immediately update when switching languages. The error messages remain in the previous language until the form is resubmitted.

**To Reproduce**

1. Go to 'Staff Login'.
2. Switch the language from English to Malayalam.
3. Click the login button without entering any credentials
4. Observe that the error message "This field is required" appears in English.
5. Click the login button again.
6. See that the error message now appears in Malayalam

https://github.com/user-attachments/assets/6ff5eafc-21d5-4fdf-a149-17cb413181fd

**Expected behavior**
The error messages should be displayed in the correct language without requiring an additional form submission

Expected Output.

https://github.com/user-attachments/assets/bd6b1961-7ddb-4f09-a8f3-9b919d26b43c

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #11540 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

 https://github.com/user-attachments/assets/bd6b1961-7ddb-4f09-a8f3-9b919d26b43c
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Refactor**
  - Improved error message handling on the login form to ensure proper localization.
  - Streamlined the login submission process, maintaining consistent functionality while enhancing clarity in error reporting.

### CODE REVIEW

File: src/components/Auth/Login.tsx [hunk 1]
```diff
@@ -278,6 +262,22 @@ const Login = (props: LoginProps) => {
     return form;
   };
 
+  const handleSubmit = async (e: React.FormEvent) => {
```
Comment (Jacobjeevan) [inline src/components/Auth/Login.tsx]: why move this down? You have done the same thing in the past 😅  When you make a commit, review them before opening a PR

**Review by rithviknishad — APPROVED** [review]
