### PR TITLE
Prevent GIF upload as profile avatar

### LINKED ISSUE #12897: GIF Upload : Uploaded as Static Image
**Describe the bug**
 The 'Profile' section displays a message suggesting that a GIF can be uploaded. 
 when we attempt to upload a GIF, it gets processed as a image. 
we can remove the GIF statement.

**To Reproduce**

1.  Go to 'Profile' and see the text below is showing GIF, but when we try to upload the GIF it is getting as picture.

https://github.com/user-attachments/assets/bc417f85-c8fb-4c56-a041-20ab63288a3a

**Expected behavior**
we can remove this text or any other changes can be done.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by LibinThankayathil**
## Proposed Changes

- Fixes #12897
- Added error message while uploading GIF as avatar
- Removed GIF from the text below the change avatar button

https://github.com/user-attachments/assets/34bc8f8d-ab46-402c-906d-3fe6ee6cb234

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **New Features**
  * Added a message to notify users that GIFs are not allowed as avatars.

* **Bug Fixes**
  * Updated avatar upload to explicitly reject GIF files during selection and drag-and-drop.

* **Documentation**
  * Updated avatar upload instructions to remove GIF as an allowed format.

### CODE REVIEW

File: src/components/Common/AvatarEditModal.tsx [hunk 1]
```diff
@@ -202,6 +202,10 @@ export default function AvatarEditModal({
       return;
     }
     const file = e.target.files[0];
+    if (file.type === "image/gif") {
+      toast.error(t("avatar_gif_not_allowed"));
+      return;
+    }
```
Comment (AdityaJ2305) [inline src/components/Common/AvatarEditModal.tsx:210]: I think instead we should make `isImage` check more strict to check since already throwing an error for `! isImage` 🤔 

wait for @Jacobjeevan or @rithviknishad  view

Comment (Jacobjeevan) [reply src/components/Common/AvatarEditModal.tsx:210]: we are using isImage to render errors when file isn't an image, so current approach is fine 👍

**Review by Jacobjeevan — APPROVED** [review]

**Comment by tasnimshaji** [comment]
LOOKS GOOD TO ME @nihal467 
image

**Comment by nihal467** [comment]
LGTM
