### PR TITLE
Combined ResourceCreate page and ResourceDetailsUpdate page

### LINKED ISSUE #10403: Consolidate Resource Forms
- Consolidate Resource Details Update and Resource Create forms (so that former also uses Zod)
- Add assigned user to resource create form

### LINKED ISSUE #10490: Assign to Field in Resource update details are randomly prefilled
**Describe the bug**

The "assign to" field in the resource update details is randomly prefilled

**To Reproduce**

**Expected behavior**

- [ ] remove the field since we don't have that data being recorded in the resource request page

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Consolidate Resource Details Update and Resource Create forms

- Fixes #10403
- Fixes #10490

Changes:
- Add assigned user to ResourceCreate form
- Renamed ResourceCreate  form to ResourceForm
- Removed ResourceDetailsUpdat page

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Added a localized prompt for user searches.
  - Enhanced the resource creation form with a new field for assigning users.
  - Introduced new options for updating resource requests.

- **Refactor**
  - Updated routing to utilize a new resource form component.

- **Bug Fixes**
  - Improved form reliability by ensuring username inputs consistently default to a valid string.

- **Chores**
  - Removed unused utility functions and components related to form field handling.
  - Eliminated several deprecated form components to streamline the codebase.
  - Removed components associated with autocomplete and dropdown functionalities.
  - Removed the user list API endpoint.
  - Updated localization for category descriptions.

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Did you forget to add "Status" field? Other than that LGTM

(left: PR; right: develop)
image

**Review by rithviknishad — APPROVED** [review]

File: src/components/Resource/ResourceForm.tsx [hunk 1]
```diff
@@ -0,0 +1,562 @@
...
+      navigate(`/facility/${facilityId}/resource/${data.id}`);
+    },
+  });
+
+  const { mutate: updateResource, isPending: isUpdatePending } = useMutation({
+    mutationFn: mutate(routes.updateResource, {
+      pathParams: { id: String(id) },
+    }),
+    onSuccess: (data: ResourceRequest) => {
+      toast.success(t("resource_updated_successfully"));
```
Comment (Jacobjeevan) [inline src/components/Resource/ResourceForm.tsx:160]: Add to en.json

**Review by Jacobjeevan — APPROVED** [review]
