### PR TITLE
Place buttons in new line in Search Facility Popup #5287

### LINKED ISSUE #5287: Place buttons in new line in Search Facility Popup
**Describe the bug**
The Cancel and Select button should be placed in new lines in mobile view

**To Reproduce**

1. Go to https://care.coronasafe.in/patients
2. Click on `Add patient details`
3. See error

**Expected behavior**
The buttons should be placed in a new line like this
image

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by AbhishekPSingh07**
- Fixes #5287 

Done the Neccesarry UI changes
Screenshot 2023-04-09 at 6 33 57 PM

### CODE REVIEW

File: src/Components/ExternalResult/FacilitiesSelectDialogue.tsx [hunk 1]
```diff
@@ -30,7 +30,7 @@ const FacilitiesSelectDialog = (props: Props) => {
         showAll={false}
         multiple={false}
       />
-      <div className="mt-4 flex justify-between">
+      <div className="mt-4 flex flex-col">
```
Comment (rithviknishad) [inline src/Components/ExternalResult/FacilitiesSelectDialogue.tsx]: @AbhishekPSingh07 in the issue it was mentioned it should be in new line only in mobile view. Also, I've added some spacing between the two buttons.

```suggestion
      <div className="mt-4 flex flex-col sm:flex-row gap-2">
```

**Review by rithviknishad — APPROVED** [review]

File: src/Components/ExternalResult/FacilitiesSelectDialogue.tsx [hunk 2]
```diff
@@ -30,7 +30,7 @@ const FacilitiesSelectDialog = (props: Props) => {
         showAll={false}
         multiple={false}
       />
-      <div className="mt-4 flex justify-between">
+      <div className="mt-4 flex flex-col sm:flex-row gap-2">
```
Comment (rithviknishad) [inline src/Components/ExternalResult/FacilitiesSelectDialogue.tsx]:
```suggestion
      <div className="mt-4 flex flex-col sm:flex-row gap-2 sm:justify-end">
```

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
