### PR TITLE
FIX: Facility Issues: Cover Not Functioning Properly and Minor Suggestions for the Facility Page

### LINKED ISSUE #10018: Facility Issues: Cover Not Functioning Properly and Minor Suggestions for the Facility Page
**Describe the bug**
- When hovering over the cover image, the gradient vanishes, which results in the facility name being invisible.

**To Reproduce**

1. Go to '[Facility](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1)'
2. Hover over facility cover page
3. See bug

- Before hovering
Image

- After
Image

**Screen Recording**
See the screen recording for better understanding : https://github.com/user-attachments/assets/d96e3915-6b78-4d2f-81dc-3bc11ff0ebbe

##
**Other Suggestions**
- Suggestion to add text justification to the facility description.

Image

- Add padding to the map icon to align with the address.

Image

- Suggestion to create a new common hint for the cover page, as we are not sticking to the 1:1 ratio for cover image.

Image

### PR DESCRIPTION
**Pull request by abhimanyurajeesh**
## Proposed Changes

- Fixes #10018 

## Summary by CodeRabbit

- **New Features**
  - Added optional hint prop to `AvatarEditModal` for customizable image upload guidance
  - Introduced cover image upload instructions with size and format recommendations

- **Style**
  - Adjusted `MapPin` vertical spacing
  - Updated text alignment for facility description
  - Modified button background and hover states in dropdown menu

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Added optional hint property to the AvatarEditModal component for customizable guidance messages.
  - Introduced cover image upload guidance hint in the Facility Home section.

- **Style**
  - Adjusted vertical spacing of the MapPin component.
  - Updated button background and hover states in the dropdown menu for improved visual consistency.

- **Localization**
  - Enhanced English localization with dynamic placeholders for image upload guidelines.
  - Removed specific localization entries regarding image upload guidelines in Hindi, Kannada, and Tamil. 
  - Updated Malayalam translations with new healthcare-related terms.

### CODE REVIEW

File: src/components/Facility/FacilityHome.tsx [hunk 1]
```diff
@@ -334,7 +344,7 @@ export const FacilityHome = ({ facilityId }: Props) => {
 
               {facilityData?.description && (
                 <Card>
-                  <CardContent className="mt-4">
+                  <CardContent className="mt-4 text-justify">
```
Comment (rithviknishad) [inline src/components/Facility/FacilityHome.tsx]: i don't think we should justify markdown content

```suggestion
                  <CardContent className="mt-4">
```

Comment (abhimanyurajeesh) [reply src/components/Facility/FacilityHome.tsx]: image

I felt this content justification looks better

image

Comment (abhimanyurajeesh) [reply src/components/Facility/FacilityHome.tsx]: But ya on moblie it looks a bit weird, removing it.

Comment (rithviknishad) [reply src/components/Facility/FacilityHome.tsx]: okiez

File: src/components/Facility/FacilityHome.tsx [hunk 2]
```diff
@@ -165,6 +165,15 @@ export const FacilityHome = ({ facilityId }: Props) => {
 
   const hasPermissionToEditCoverImage = true;
 
+  const coverImageHint = (
+    <>
+      {t("max_size_for_image_uploaded_should_be")} 1mb.
+      <br />
+      {t("allowed_formats_are")} jpg,png,jpeg.{" "}
+      {t("recommended_aspect_ratio_for")} the image is 16:9
```
Comment (rithviknishad) [inline src/components/Facility/FacilityHome.tsx]: i don't think mixing english with translation language is a good idea. pass it as variables. check how to pass variables to i18n's t function and other existing usages

**Review by rithviknishad — COMMENTED** [review]
lgtm; just minor suggestion

File: src/components/Facility/FacilityHome.tsx (hunk 2 above)
Comment (abhimanyurajeesh) [reply src/components/Facility/FacilityHome.tsx]: Ya even I thought of doing that, since code was already existing, I didn't wanna do that but If this `t` is not use anywhere else update it or else create a new one.

**Comment by abhimanyurajeesh** [comment]
> lgtm; just minor suggestion

No worries 😉 let's do that minor suggestion.

File: src/components/Facility/FacilityHome.tsx (hunk 2 above)
Comment (rithviknishad) [reply src/components/Facility/FacilityHome.tsx]: update it; update it in existing ones too if any;

File: src/components/Common/AvatarEditModal.tsx [hunk 3]
```diff
@@ -165,15 +167,21 @@ const AvatarEditModal = ({
     setIsDragging(false);
   };
 
-  const commonHint = (
+  const maxSize = "1MB";
+  const formats = "jpg, png, jpeg";
+  const aspectRatio = "1:1";
+
```
Comment (rithviknishad) [inline src/components/Common/AvatarEditModal.tsx]: can we keep this inline? i don't see much value extracting it out as a variable

File: src/components/Facility/FacilityHome.tsx [hunk 4]
```diff
@@ -165,6 +165,19 @@ export const FacilityHome = ({ facilityId }: Props) => {
 
   const hasPermissionToEditCoverImage = true;
 
+  const maxSize = "1MB";
+  const formats = "jpg, png, jpeg";
+  const aspectRatio = "16:9";
```
Comment (rithviknishad) [inline src/components/Facility/FacilityHome.tsx]: here too

**Review by rithviknishad — APPROVED** [review]
lgtm, just minor things

File: src/components/Common/AvatarEditModal.tsx (hunk 3 above)
Comment (abhimanyurajeesh) [reply src/components/Common/AvatarEditModal.tsx]: done

File: src/components/Facility/FacilityHome.tsx (hunk 4 above)
Comment (abhimanyurajeesh) [reply src/components/Facility/FacilityHome.tsx]: done

**Comment by abhimanyurajeesh** [comment]
@rithviknishad Just look at it once, I have made the changes. Thank you!

**Review by rithviknishad — APPROVED** [review]
