### PR TITLE
Resolves malfunctioning Add Doctor Capacity form

### LINKED ISSUE #5053: Add Doctor Capacity form malfunction
**Describe the bug**
When we just enter the `Area of Specialization` and click `Save Doctor Capacity` the popup just closes without any warning.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/6fa5e305-7eea-4b48-b973-e0679e30f63e
2. Click on `Add Doctor Types`
3. Click `Save Doctor Capacity` button

**Expected behavior**
The form should highlight the required fields with red and not close the popup

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #5053 
http://localhost:4000/facility/6fa5e305-7eea-4b48-b973-e0679e30f63e
- [x] Show error message on form submission
- [x] Change the border color of the dropdown to red for required fields on error

Before:
image

After:
image

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

File: src/Components/Facility/DoctorCapacity.tsx [hunk 1]
```diff
@@ -180,8 +180,8 @@ export const DoctorCapacity = (props: DoctorCapacityProps) => {
         }
       }
       handleUpdate();
+      if (btnType == "Save and Exit") handleClose();
```
Comment (khavinshankar) [inline src/Components/Facility/DoctorCapacity.tsx]: @Pranshu1902 can we make the button types as an enum, something like constants maybe

Comment (Pranshu1902) [reply src/Components/Facility/DoctorCapacity.tsx]: @khavinshankar done!

**Review by khavinshankar — APPROVED** [review]
