### PR TITLE
Fix: Nav Redirection from discharge summary file upload page is not working

### LINKED ISSUE #11147: Nav Redirection from discharge summary file upload page is not working
**Describe the bug**

When we try to access the nav bar and go to another section like Overview or Plots from the Discharge Summary section, it gets stuck, and the redirection does not work.

**To Reproduce**

1. Go to encounter page
2. Click on file and head to discharge summary
3. Now try to switch the tab using the nav

**Expected behavior**

The navigation should work smoothly, allowing users to switch between sections without getting stuck.

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by abhimanyurajeesh**
## Proposed Changes

- Fixes #11147 

- Modify file navigation to use query parameters instead of route segments
- Update Tabs component to use query-based file filtering
- Improve styling for Tabs and remove direct Link usage
- Simplify query key and file category filtering logic

## Screen recording 

https://github.com/user-attachments/assets/b83234dc-b811-4b4c-a2ce-eda58aec21a9

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Refactor**
	- Updated document access links to use a new query structure, ensuring a smoother navigation experience.
	- Streamlined file filtering and tab management with enhanced query parameter handling for more responsive interactions.
	- Removed unnecessary `subPage` parameters from various components, simplifying the component logic and improving clarity.
- **Style**
	- Improved the visual cues on the tabs, offering clearer active states for better navigation feedback.

### CODE REVIEW

File: src/components/Encounter/EncounterActions.tsx [hunk 1]
```diff
@@ -89,7 +89,7 @@ export default function EncounterActions({
           </DropdownMenuItem>
           <DropdownMenuItem asChild>
             <Link
-              href={`/facility/${encounter.facility.id}/patient/${encounter.patient.id}/encounter/${encounter.id}/files/discharge_summary`}
+              href={`/facility/${encounter.facility.id}/patient/${encounter.patient.id}/encounter/${encounter.id}/files?file=discharge_summary`}
```
Comment (rithviknishad) [inline src/components/Encounter/EncounterActions.tsx]: let's use relative navigates

File: src/components/Encounter/EncounterActions.tsx [hunk 2]
```diff
@@ -150,7 +150,7 @@ export default function EncounterActions({
           asChild
         >
           <Link
-            href={`/facility/${encounter.facility.id}/patient/${encounter.patient.id}/encounter/${encounter.id}/files/discharge_summary`}
+            href={`/facility/${encounter.facility.id}/patient/${encounter.patient.id}/encounter/${encounter.id}/files?file=discharge_summary`}
```
Comment (rithviknishad) [inline src/components/Encounter/EncounterActions.tsx]: here as well

**Review by rithviknishad — CHANGES_REQUESTED** [review]
although works; let's use relative navigates to keep it simple;

**Comment by abhimanyurajeesh** [comment]
https://github.com/user-attachments/assets/9ccc56f4-fcae-4593-aaef-f2373112200d

Both facility and organization view

**Review by rithviknishad — APPROVED** [review]

File: src/components/Files/FilesTab.tsx
Comment (Jacobjeevan) [inline src/components/Files/FilesTab.tsx:1]: Go ahead and remove the subPage variable here and as well as in ConsultationRoutes. It was only used for discharge summary anyways, so shouldn't be necessary anymore.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
