### PR TITLE
Fix: Disable submit/save buttons until changes are made on any Edit/Update details page

### LINKED ISSUE #10008: Feat Suggestion: Disable submit/save buttons until changes are made on any Edit/Update details page
**Description**
Currently, the Save/Submit buttons on the Edit Pages remains enabled even when no changes have been made. This can lead to unnecessary API calls or confusion for users. To improve the UX, the Save button should remain disabled until the user makes a change to any field.

**Some Examples**
https://care.ohc.network/resource/42fc1a5f-0942-4e50-aec9-ff7aa2250b3d/update
Image

https://care.ohc.network/facility/fbe69bf8-e0bb-4a01-854d-b756af80a3fd/patient/fbe69bf8-e0bb-4a01-854d-b756af80a3fd/update
Image

### PR DESCRIPTION
**Pull request by Rishith25**
## Proposed Changes

- Fixes #10008 
 
@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Enhanced form interactivity by ensuring submit buttons activate only when changes are made, preventing accidental submissions.
  
- **Refactor**
  - Streamlined field update and reset behaviors, including refined default value handling, to improve overall form responsiveness and user experience.

### CODE REVIEW

File: src/components/Patient/PatientRegistration.tsx [hunk 1]
```diff
@@ -262,26 +262,32 @@ export default function PatientRegistration(
         patientQuery.data.geo_organization as unknown as Organization,
       ]);
       form.reset({
-        ...patientQuery.data,
+        name: patientQuery.data.name || "",
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientRegistration.tsx:265]: why change this? 🤔  spread operator should have been fine here.

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
other than @Jacobjeevan 's comment, lgtm

File: src/components/Patient/PatientRegistration.tsx (hunk 1 above)
Comment (Rishith25) [reply src/components/Patient/PatientRegistration.tsx:265]: @Jacobjeevan @rithviknishad

Initially, the form was becoming dirty even without any changes. This happened because the spread operator (...) included extra fields that are not part of formSchema, causing unnecessary state updates. Additionally, some fields were undefined due to missing default values, leading to validation issues. Using the spread operator does not allow setting default values for properties that might be undefined.

**Comment by nihal467** [comment]
LGTM
