### PR TITLE
Care Loading icon in organization and facility users

### LINKED ISSUE #9714: Replace loading text with care loading icon
**Describe the bug**
Display care loading icon on clicking organization in homepage, and users in facility, 

**To Reproduce**

1. Go to  https://care.ohc.network/
2. Click on click on Kerala 
3. We can see the text: Loading.. instead of care icon

**Expected behavior**
Care Loading icon should be displayed

**Screenshots**
Image

Expected:

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by Rishith25**
## Proposed Changes

- Fixes #9714 
- Replace `Loading...` text with Care Loading icon

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced loading states with more detailed and visually appealing skeleton screens.
	- Improved loading experience across multiple components.
	- Added dynamic translation for various text elements, enhancing localization support.

- **UI Improvements**
	- Added more sophisticated loading placeholders with animated elements.
	- Refined visual feedback during data fetching.
	- Updated loading screen layouts to include additional loading indicators and improved structure.
	- Changed loading state titles for better consistency and clarity.

### CODE REVIEW

**Comment by bodhish** [comment]
Use skelton loading for loading instead of using the care logo one;

**Review by rithviknishad — COMMENTED** [review]
instead of reinventing things, let's use shadcn's skeleton instead

File: src/components/Facility/FacilityUsers.tsx [hunk 1]
```diff
@@ -12,6 +12,9 @@ import useFilters from "@/hooks/useFilters";
 import routes from "@/Utils/request/api";
 import query from "@/Utils/request/query";
 
+import { Card, CardContent } from "../ui/card";
+import { Skeleton } from "../ui/skeleton";
```
Comment (rithviknishad) [inline src/components/Facility/FacilityUsers.tsx]: use absolute imports. 

do check your setup, tab completions would've preferred auto imports first.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

File: src/pages/FacilityOrganization/FacilityOrganizationIndex.tsx
Comment (rithviknishad) [inline src/pages/FacilityOrganization/FacilityOrganizationIndex.tsx:1]: add i18n for all texts in this file

**Review by rithviknishad — CHANGES_REQUESTED** [review]
changes for the issue lgtm, but merge checklist not followed.
add i18n for all texts in the files that were changed

**Comment by Rishith25** [comment]
@rithviknishad Can you assign story points for this

**Comment by rithviknishad** [comment]
resolve conflicts btw

**Comment by Rishith25** [comment]
@rithviknishad Resolved the merge conflicts

File: public/locale/en.json [hunk 2]
```diff
@@ -1296,7 +1296,12 @@
   "oral_issue_for_non_oral_nutrition_route_error": "Can be specified only if nutrition route is set to Oral",
   "ordering": "Ordering",
   "organization": "Organization",
+  "organization_access": "You don't have access to any organizations yet.",
```
Comment (rithviknishad) [inline public/locale/en.json]:
```suggestion
  "organization_forbidden": "You don't have access to any organizations yet.",
```

File: public/locale/en.json [hunk 3]
```diff
@@ -1296,7 +1296,12 @@
...
+  "organization_facility": "Facility Organizations",
```
Comment (rithviknishad) [inline public/locale/en.json]:
```suggestion
  "facility_organizations": "Facility Organizations",
```

File: public/locale/en.json [hunk 4]
```diff
@@ -1296,7 +1296,12 @@
...
   "organization_for_care_support": "Organization for Care Support",
+  "organization_manage": "Organizations help you manage facilities, users, and resources efficiently. Contact your administrator to get access.",
```
Comment (rithviknishad) [inline public/locale/en.json]:
```suggestion
  "organization_access_help": "Organizations help you manage facilities, users, and resources efficiently. Contact your administrator to get access.",
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]
