### PR TITLE
Fix: unusual behaviour when removing selected Options

### LINKED ISSUE #7552: Unexpected Behaviour When Removing Multiple Selected Options
**Describe the bug**
When closing (deleting) multi-selected options, dropdown appear, which is a little annoying and impacts the user experience.

**To Reproduce**

1. Go to the Edit Consultation page.
2. Add multiple options to symptoms.
3. Click on the `x` and observe the behavior.
**Expected behavior**
Dropdown should not open upon removing a selected option

**Screenshots**
[Screencast from 06-04-24 12:10:51 PM IST.webm](https://github.com/coronasafe/care_fe/assets/111575806/292cab7f-03ad-4e39-b3ee-4dc48ddc579a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by UdaySagar-Git**
## Proposed Changes

- Fixes #7552 

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

File: src/Components/Form/MultiSelectMenuV2.tsx [hunk 1]
```diff
@@ -177,7 +178,7 @@ export default MultiSelectMenuV2;
 
 interface MultiSelectOptionChipProps {
   label: ReactNode;
-  onRemove?: () => void;
+  onRemove?: (e: any) => void;
```
Comment (khavinshankar) [inline src/Components/Form/MultiSelectMenuV2.tsx]:
```suggestion
  onRemove?: (e: React.MouseEvent<HTMLParagraphElement>) => void;
```

@UdaySagar-Git try to avoid `any` and `unknown` as much as possible. Also just apply this change and check if there any type error or a typo (just in case 😅 )

**Review by khavinshankar — APPROVED** [review]

File: src/Components/Form/MultiSelectMenuV2.tsx (hunk 1 above)
Comment (rithviknishad) [reply src/Components/Form/MultiSelectMenuV2.tsx]: I'd suggest do the `e.stopPropogation` in the multi select option chip component itself as as per the props type, argument `e` is not passed.

image

Comment (UdaySagar-Git) [reply src/Components/Form/MultiSelectMenuV2.tsx]: sure

**Review by rithviknishad — APPROVED** [review]
LGTM! Nice work

**Comment by nihal467** [comment]
LGTM

**Review by Ashesh3 — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]
