### PR TITLE
Fixed whitespace bypasses validation in config forms

### LINKED ISSUE #13312: Whitespace Bypasses Validation in Required Fields in Config Forms
**Describe the bug**
In the **Patient Identifier Config** form and **Tag Config** Form, required fields like `Display`, `Description`, `System` and `Slug` accept only whitespace as valid input. This results in entries that appear blank but still pass validation.

**To Reproduce**

1. Log in as Super admin
2. Go to Patient Identifier Config Form or Tag Config Form
3. Add whitespaces to required field

**Expected behavior**
Whitespace-only input should be treated as empty. These fields should trigger a **"Required"** validation error if the input contains only spaces.

**Screenshots**

https://github.com/user-attachments/assets/6df1a10f-c285-44a0-b62a-2a3d23340b8f

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by dilshad-knk**
## Proposed Changes

Fixes #13312 
- added .trim() so that any extra spaces at the start or end of the input are automatically removed before validation.
- added  added i18n translation for validation strings

[screen-capture.webm](https://github.com/user-attachments/assets/be081573-8bd9-4404-b50b-82edf5380df7)

[screen-capture (1).webm](https://github.com/user-attachments/assets/fa0b3601-9326-45ef-9a4d-c5263144a764)

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

* **New Features**
  * Added a new validation message ("Priority must be non-negative") to English locale.

* **Refactor**
  * Validation schemas moved into component scope and updated to trim inputs before checking.
  * All validation error messages now use localized translations.

* **Behavior**
  * Admin tag form now accepts an optional facility context, enabling facility-scoped behavior in the form.

### CODE REVIEW

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

File: src/pages/Admin/TagConfig/TagConfigForm.tsx [hunk 1]
```diff
@@ -75,6 +57,24 @@ export default function TagConfigForm({
   const isEditing = Boolean(configId);
   const isCreatingChild = Boolean(parentId);
 
+  const tagConfigSchema = z.object({
+    slug: z.string().trim().min(1, t("slug_required")),
+    display: z.string().trim().min(1, t("display_required")),
+    category: z.nativeEnum(TagCategory, {
+      required_error: t("category_required"),
```
Comment (Jacobjeevan) [inline src/pages/Admin/TagConfig/TagConfigForm.tsx]: let's not add individual ones, switch to using generic - "field_required" and discard those keys in en.json.

**Review by Jacobjeevan — DISMISSED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
