### PR TITLE
Fixed alignment in users page

### LINKED ISSUE #7807: Fix Alignment in Users page
**Describe the bug**
Alignment in users page is off

**Screenshots**
image

### PR DESCRIPTION
**Pull request by shivankacker**
## Proposed Changes

- Fixes #7807
- Fixes alignment in the users page

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

File: src/Components/Users/ManageUsers.tsx [hunk 1]
```diff
@@ -188,11 +188,7 @@ export default function ManageUsers() {
     (userList = userListData.results.map((user: any, idx) => {
       const cur_online = isUserOnline(user);
       return (
-        <div
-          key={`usr_${user.id}`}
-          id={`usr_${idx}`}
-          className=" mt-6 w-full md:px-4 lg:w-1/2 xl:w-1/3"
-        >
+        <div key={`usr_${user.id}`} id={`usr_${idx}`} className="">
```
Comment (khavinshankar) [inline src/Components/Users/ManageUsers.tsx]:
```suggestion
        <div key={`usr_${user.id}`} id={`usr_${idx}`}>
```

File: src/Components/Users/ManageUsers.tsx [hunk 2]
```diff
@@ -536,7 +534,7 @@ export default function ManageUsers() {
         </div>
       </div>
 
-      <div className="pb-2 pl-6">
+      <div className="">
```
Comment (khavinshankar) [inline src/Components/Users/ManageUsers.tsx]:
```suggestion
      <div>
```

File: src/Components/Users/ManageUsers.tsx [hunk 3]
```diff
@@ -559,7 +557,7 @@ export default function ManageUsers() {
         />
       </div>
 
-      <div className="px-3 md:px-6">
+      <div className="">
```
Comment (khavinshankar) [inline src/Components/Users/ManageUsers.tsx]:
```suggestion
      <div>
```

**Review by khavinshankar — APPROVED** [review]
