### PR TITLE
Ensure DialogContent Accessibility by Adding Description Support

### LINKED ISSUE #10617: Accessibility Warning: DialogContent Missing Description or aria-describedby
**Describe the bug**
When using DialogContent, the console logs a warning about a missing Description or aria-describedby={undefined}. This issue may affect accessibility by not providing a proper description for assistive technologies.

**To Reproduce**

[Click here to reproduce](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/settings/general)
See error

**Expected behavior**
DialogContent should not trigger accessibility warnings in the console. It should either automatically provide a valid aria-describedby attribute or allow users to specify a description to ensure proper accessibility compliance.

**Screenshots**

https://github.com/user-attachments/assets/0d010bc2-e726-4739-a050-a35d0b828f62

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [132.0.6834.111]

**Additional context**

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes

- Fixes #10617 
- Change 1

old

https://github.com/user-attachments/assets/fa69ecb4-b95c-426f-b934-05966e46281c

updated

https://github.com/user-attachments/assets/65d26411-6fea-436b-8b68-3d2e53519aec

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Enhanced mobile sidebar accessibility by adding a hidden descriptive element.
  - Introduced a description for the avatar editing modal, improving context for users relying on assistive technologies.
  - Added hidden descriptions to the mobile navigation in the Encounter Notes tab for better accessibility.
  - Included descriptions in the Create and Edit Schedule Template Sheets to enhance user context without altering existing functionality.
  - Updated localization files to provide clearer navigation options for the sidebar.

### CODE REVIEW

File: src/components/ui/sidebar.tsx [hunk 1]
```diff
@@ -197,6 +202,7 @@ const Sidebar = React.forwardRef<
     if (isMobile) {
       return (
         <Sheet open={openMobile} onOpenChange={setOpenMobile} {...props}>
+          <SheetDescription className="sr-only">sidebar sheet</SheetDescription>
```
Comment (rithviknishad) [inline src/components/ui/sidebar.tsx]: End user doesn't necessarily know what a sheet is.
```suggestion
          <SheetDescription className="sr-only">Sidebar</SheetDescription>
```

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx [hunk 2]
```diff
@@ -519,6 +525,12 @@ export const EncounterNotesTab = ({ encounter }: EncounterTabProps) => {
       {/* Mobile Sheet */}
       <Sheet open={isThreadsExpanded} onOpenChange={setIsThreadsExpanded}>
         <SheetContent side="left" className="w-[100%] sm:w-[380px] p-0">
+          <SheetDescription className="sr-only">
+            EncounterNote sidebar sheet
+          </SheetDescription>
+          <VisuallyHidden>
+            <SheetTitle>EncounterNote</SheetTitle>
+          </VisuallyHidden>
```
Comment (rithviknishad) [inline src/pages/Encounters/tabs/EncounterNotesTab.tsx]: purpose of accessibility is defeated

**Review by rithviknishad — CHANGES_REQUESTED** [review]
why was translations not added? Screen readers can read languages other than english too right?

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx (hunk 2 above)
Comment (modamaan) [reply src/pages/Encounters/tabs/EncounterNotesTab.tsx]: updated

File: src/components/ui/sidebar.tsx (hunk 1 above)
Comment (modamaan) [reply src/components/ui/sidebar.tsx]: updated

File: src/components/ui/sidebar.tsx [hunk 3]
```diff
@@ -197,6 +203,9 @@ const Sidebar = React.forwardRef<
     if (isMobile) {
       return (
         <Sheet open={openMobile} onOpenChange={setOpenMobile} {...props}>
+          <SheetDescription className="sr-only">
+            {t("sidebar_provides_navigation_to_different_sections")}
```
Comment (rithviknishad) [inline src/components/ui/sidebar.tsx]:
```suggestion
            {t("sidebar_description")}
```

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx [hunk 4]
```diff
@@ -519,6 +524,10 @@ export const EncounterNotesTab = ({ encounter }: EncounterTabProps) => {
       {/* Mobile Sheet */}
       <Sheet open={isThreadsExpanded} onOpenChange={setIsThreadsExpanded}>
         <SheetContent side="left" className="w-[100%] sm:w-[380px] p-0">
+          <SheetDescription className="sr-only">
+            {t("encounter_notes__all_discussions_sidebar")}
```
Comment (rithviknishad) [inline src/pages/Encounters/tabs/EncounterNotesTab.tsx]: is this a sidebar? 🤔

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/ui/sidebar.tsx (hunk 3 above)
Comment (modamaan) [reply src/components/ui/sidebar.tsx]: updated

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx (hunk 4 above)
Comment (modamaan) [reply src/pages/Encounters/tabs/EncounterNotesTab.tsx]: updated

**Review by rithviknishad — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
Cover image update works well

**Comment by modamaan** [comment]
@rithviknishad    image
It just automatically updated the positioning when I resolved the merge conflict. `show_on_map`

**Comment by rithviknishad** [comment]
keys are sorted by precommit hook, that's expected
