### PR TITLE
E-chart vitals precision problem fixed

### LINKED ISSUE #7429: Modify the E-chart preview to have consistency with user input
**Describe the bug**

We input the normal log update data with a maximum of one decimal point and in some cases with only an integer value, but all our preview charts have two decimal points **{DISCUSSION ISSUE FOR CORE TEAM}**

**To Reproduce**

### Things to discuss

- [ ] Decimal places
- [ ] Cypress test for data from canvas render

**Expected behavior**

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by hrit2773**
## Proposed Changes

- Fixes #7429 
Screenshot 2024-03-21 202657

### CODE REVIEW

**Comment by Ashesh3** [comment]
Lint check is failing

**Comment by hrit2773** [comment]
> Lint check is failing

@Ashesh3 how can I trace it is I think it's a line ending problem?

**Comment by Ashesh3** [comment]
> > Lint check is failing
> 
> @Ashesh3 how can I trace it is I think it's a line ending problem?

Try `npm run lint` to check the errors and `npm run lint-fix` to fix auto-fixable lint issues.

**Comment by hrit2773** [comment]
> > > Lint check is failing
> > 
> > 
> > @Ashesh3 how can I trace it is I think it's a line ending problem?
> 
> Try `npm run lint` to check the errors and `npm run lint-fix` to fix auto-fixable lint issues.

@Ashesh3 seems like my typescript version is 5.4.2 which is newer than the range specified which is till 5.2.0

**Comment by hrit2773** [comment]
@Ashesh3 lint issue fixed

**Comment by Ashesh3** [comment]
Why have you pushed a changed `package-lock.json` file?

**Comment by hrit2773** [comment]
> Why have you pushed a changed `package-lock.json` file?

@Ashesh3 I haven't made any changes in the package lock.json file no commit history found and I didn't install any new dependency I Just added a new function in utils.js and used it in lineplot component.

**Comment by Ashesh3** [comment]
Hey, could you recheck? It appears in the files changed tab.

https://github.com/coronasafe/care_fe/pull/7450/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519

Commit `E-chart preview precision problem fixed ( commit:  c126287b4311ad77f5a81e46db9182de05552325 )`
 https://github.com/coronasafe/care_fe/pull/7450/commits/c126287b4311ad77f5a81e46db9182de05552325#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519

**Comment by hrit2773** [comment]
> Hey, could you recheck? It appears in the files changed tab.
> 
> https://github.com/coronasafe/care_fe/pull/7450/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519
> 
> Commit `E-chart preview precision problem fixed ( commit: c126287b4311ad77f5a81e46db9182de05552325 )` [c126287#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519](https://github.com/coronasafe/care_fe/commit/c126287b4311ad77f5a81e46db9182de05552325#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519)

@Ashesh3 maybe some version changes occured in my system while running npm install but no package was installed explicitly and there is no change in package.json right

**Review by rithviknishad — CHANGES_REQUESTED** [review]
1. So many files unrelated to the issue are having changes, why? 
2. Discard the changes in package-lock file
3. You've not solved the second part of the issue, adding sr-only spans for cypress to be able to read chart data.

https://github.com/coronasafe/care_fe/issues/7429#issuecomment-2009891121

image

**Comment by hrit2773** [comment]
@rithviknishad fine I will solve them now

**Comment by Ashesh3** [comment]
> > Hey, could you recheck? It appears in the files changed tab.
> > https://github.com/coronasafe/care_fe/pull/7450/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519
> > Commit `E-chart preview precision problem fixed ( commit: c126287b4311ad77f5a81e46db9182de05552325 )` [c126287#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519](https://github.com/coronasafe/care_fe/commit/c126287b4311ad77f5a81e46db9182de05552325#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519)
> 
> @Ashesh3 maybe some version changes occured in my system while running npm install but no package was installed explicitly and there is no change in package.json right

Right, if there are no changes to package.json - there's no need to push an updated lock file. 😅

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Span tags are required for all the data that is rendered in the canvas and not just the latest values. 

cc: @nihal467

**Comment by hrit2773** [comment]
> Span tags are required for all the data that is rendered in the canvas and not just the latest values.
> 
> cc: @nihal467

@rithviknishad ohh do you mean that the sr-only tag should be applied to the whole chart again to get the chart DOM for cypress?

**Comment by hrit2773** [comment]
@rithviknishad or do you mean to say that span tags should be applied to all the previous log update values as well???

**Comment by rithviknishad** [comment]
Issue is, cypress currently has no way to validate the data being shown inside the charts since it is canvas-rendered.

So, the data shown in the canvas needs to be also present as span elements with sr-only.

**Comment by hrit2773** [comment]
@rithviknishad yes so I need to mention all the values starting from the first log update to the last log update right for example for pulse it starts from 97,94,93 so on all the way till latest 98 right... I need to wrap all these values also right in span tags?

File: src/Components/Facility/Consultations/components/LinePlot.tsx [hunk 1]
```diff
@@ -225,11 +228,18 @@ export const LinePlot = (props: any) => {
...
   return (
-    <ReactEchartsCore
-      echarts={echarts}
-      option={generalOptions}
-      className={props.classes}
-      lazyUpdate={props.type === "WAVEFORM"}
-    />
+    <>
+      {yData.map((value: any) => (
+        <span className="sr-only px-1">
```
Comment (rithviknishad) [inline src/Components/Facility/Consultations/components/LinePlot.tsx]: LGTM, Could you give the span an `id` too so that Cypress can uniquely identify the element to read?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Facility/Consultations/components/LinePlot.tsx (hunk 1 above)
Comment (hrit2773) [reply src/Components/Facility/Consultations/components/LinePlot.tsx]: ya sure

**Comment by hrit2773** [comment]
@rithviknishad check it now the id is unique for all the values in vitals like pulse1,pulse2,pulse3.... and temperature1,temperature2... I think it can be uniquely identified by cypress not just in a canvas but also in the whole vitals section. Any further requirements from your side?? @nihal467 @Ashesh3

File: src/Components/Facility/Consultations/components/LinePlot.tsx [hunk 2]
```diff
@@ -225,11 +228,18 @@ export const LinePlot = (props: any) => {
...
   return (
-    <ReactEchartsCore
-      echarts={echarts}
-      option={generalOptions}
-      className={props.classes}
-      lazyUpdate={props.type === "WAVEFORM"}
-    />
+    <>
+      {yData.map((value: any, idx: any) => (
+        <span id={`${title}${idx + 1}`} className="sr-only px-1">
```
Comment (rithviknishad) [inline src/Components/Facility/Consultations/components/LinePlot.tsx]:
```suggestion
        <span id={`${title}-${idx + 1}`} className="sr-only px-1">
```

**Review by rithviknishad — APPROVED** [review]
LGTM

**Comment by hrit2773** [comment]
@rithviknishad great 👍

**Comment by nihal467** [comment]
LGTM

**Review by Ashesh3 — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]
