### PR TITLE
changed the file name of exported file

### LINKED ISSUE #5524: Correct the CSV downloaded file name
**Describe the bug**

Currently, it is 3:15 PM , indian time, i export a CSV file from care, the file is " capacities_2023-05-25T09_45_24.151Z " , in which the file name shows current date , but the time is not my local time.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility
2. Click on Export on the top right
3. Check the downloaded file name

**Expected behavior**

- [ ]  add a "_" between date and time in the file name, for example from this name " capacities_2023-05-25T09_45_24.151Z " it changes to "" capacities_2023-05-25_T09_45_24.151Z ""
- [ ] change the time mentioned in the file name to my local time

**Screenshots**

image

### PR DESCRIPTION
**Pull request by MayaSatishRao**
### <samp>🤖 Generated by Copilot at 13d3f1a</samp>

Modified the `getTimestamp` function in `useExport` hook to use a more user-friendly date and time format for the exported CSV files. This was done to fix issue #1729 and improve the usability of the export feature.

## Proposed Changes

- Fixes #5524 
- Changed the date and time to the user locale
- Added '_' between date and time

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

File: src/Common/hooks/useExport.tsx [hunk 1]
```diff
@@ -22,7 +22,13 @@ export default function useExport() {
     return <CSVLink id={id} filename={filename} data={data} />;
   };
 
-  const getTimestamp = () => new Date().toISOString();
+  const getTimestamp = () => {
+    let d = new Date();
+    let date = d.toLocaleDateString();
+    let time = d.toLocaleTimeString();
```
Comment (rithviknishad) [inline src/Common/hooks/useExport.tsx]:
```suggestion
    const d = new Date();
    const date = d.toLocaleDateString();
    const time = d.toLocaleTimeString();
```

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
