### PR TITLE
fix: quantity field in medication billing

### LINKED ISSUE #15432: quantity field in medication field
When billing medications with volumetric units, the quantity field shouldn't be auto calculated.

### PR DESCRIPTION
**Pull request by StephZam**
## Proposed Changes

Fixes #15432
- Quantity field of medications with volumetric units is not auto calculated.

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Updates**
  * Medication quantity calculations were standardized across pharmacy forms: totals now account for timing/duration, frequency, and dose ranges (with proper rounding). PRN doses use the single-dose value. Non‑volumetric unit medications prompt empty quantity for manual entry. Missing dose data defaults to zero.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/pages/Facility/services/pharmacy/MedicationBillForm.tsx [hunk 1]
```diff
@@ -941,6 +941,13 @@ export default function MedicationBillForm({
       return "0";
     }
 
+    const unitCode = instruction.dose_and_rate?.dose_quantity?.unit?.code;
+    const volumetricUnitCodes = ["g", "mg", "ug", "mL", "[drp]"];
```
Comment (bodhish) [inline src/pages/Facility/services/pharmacy/MedicationBillForm.tsx]: When did we even add support for drop? is it even valid? 

CC @rithviknishad

**Review by bodhish — CHANGES_REQUESTED** [review]

File: src/pages/Facility/services/pharmacy/MedicationBillForm.tsx (hunk 1 above)
Comment (rithviknishad) [reply src/pages/Facility/services/pharmacy/MedicationBillForm.tsx]: @bodhish drop is there.

@StephZam I'd say whitelisting units for auto-calc would be more robust code than blacklisting. What if we add other units for support in the possible dosage units in the future?

Support for only tablets and count seems reasonable to me.

Also, can we move this auto-calc fn. to a utility file `medicationRequest.ts`?

File: src/types/emr/medicationRequest/medicationRequest.ts [hunk 2]
```diff
@@ -842,3 +844,82 @@ export function displayMedicationName(
     ""
   );
 }
+
+export function computeInitialQuantity(
```
Comment (rithviknishad) [inline src/types/emr/medicationRequest/medicationRequest.ts]:
```suggestion
export function computeMedicationDispenseQuantity(
```

**Review by rithviknishad — APPROVED** [review]

File: src/types/emr/medicationRequest/medicationRequest.ts [hunk 3]
```diff
@@ -842,3 +844,82 @@ export function displayMedicationName(
...
+      case "wk":
+        return multiply(value, 24 * 7);
+      case "mo":
+        return multiply(value, 24 * 30);
+      case "a":
+        return multiply(value, 24 * 365);
+      default:
+        return 0;
+    }
+  };
```
Comment (yash-learner) [inline src/types/emr/medicationRequest/medicationRequest.ts:892]: Why not just export this https://github.com/ohcnetwork/care_fe/blob/ffbb163f004ec03ae3abb48d849338ad12f402da/src/components/Medicine/utils.ts#L48 and reuse here or viceversa

File: src/types/emr/medicationRequest/medicationRequest.ts [hunk 4]
```diff
@@ -842,3 +844,82 @@ export function displayMedicationName(
     ""
   );
 }
+
+export function computeMedicationDispenseQuantity(
```
Comment (yash-learner) [inline src/types/emr/medicationRequest/medicationRequest.ts:848]: Should we not keep this as well in src/components/Medicine/utils.ts -> http://github.com/ohcnetwork/care_fe/blob/develop/src/components/Medicine/utils.ts

**Review by yash-learner — CHANGES_REQUESTED** [review]

**Review by bodhish — APPROVED** [review]
