### PR TITLE
 Fixes layout misalignment in Observation Definition form

### LINKED ISSUE #13073: Observation Definition form UI Issue on error message
**Describe the bug**

Image

**To Reproduce**

- Go to any facility 
- go to observation definition tab under setting main tab 
- go to form for the same 
- Add component 
- submit blank form 
- see error

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by LokeshsaiP**
## Proposed Changes

- Fixes #13073 
- Aligned data type and unit dropdowns in component form after submitting it blank.
- Applied consistent layout and spacing to fix UI.
- Fixed minor misalignments caused by ValueSetSelect component.

https://github.com/user-attachments/assets/51ff1865-14f0-4a11-afc0-dc53a161d90b

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **Style**
  * Improved form layout and spacing for component fields for clearer vertical alignment and preserved error-message space.
  * Simplified value-set selector trigger structure to remove an extra width constraint, improving alignment and truncation.

* **New Features**
  * UI text updated for localization: optional-field label and component numbering now use translated strings (new locale key added).

* **Bug Fixes**
  * Selecting a code now clears related code validation errors immediately.

### CODE REVIEW

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

**Comment by Jacobjeevan** [comment]
Minor things need to be adjusted:

image

In components:

image

image

Also check relevant items in merge checklist @LokeshsaiP

File: src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx [hunk 1]
```diff
@@ -628,7 +628,7 @@ function ObservationDefinitionFormContent({
                         </div>
 
                         <div className="mb-2 text-sm font-medium text-gray-700">
-                          Component {index + 1}
+                          {t("component")} {index + 1}
                         </div>
```
[the remark this answers is not in the document]
Comment (AdityaJ2305) [reply src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx:633]: @LokeshsaiP  👆

[the remark this answers is not in the document]
Comment (AdityaJ2305) [reply src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx]: @LokeshsaiP 👆

File: src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx [hunk 2]
```diff
@@ -665,28 +665,30 @@ function ObservationDefinitionFormContent({
...
-                                    defaultValue={field.value}
-                                  >
-                                    <FormControl>
-                                      <SelectTrigger>
+                                  <FormControl>
+                                    <Select
+                                      onValueChange={field.onChange}
+                                      defaultValue={field.value}
+                                    >
+                                      <SelectTrigger className="h-[44px]">
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx]: why h-[44px] ? 🤔

File: src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (LokeshsaiP) [reply src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx]: @AdityaJ2305 do you want me to add this translation key into en.json file?

File: src/components/Questionnaire/ValueSetSelect.tsx [hunk 3]
```diff
@@ -237,7 +237,7 @@ export default function ValueSetSelect({
       >
         {!hideTrigger && (
           <PopoverTrigger asChild disabled={disabled}>
-            <div className="w-full">
+            <div className="w-full !px-0">
```
Comment (AdityaJ2305) [inline src/components/Questionnaire/ValueSetSelect.tsx]: we can discard these changes here 
fixed in https://github.com/ohcnetwork/care_fe/pull/13136/files#diff-ba53f5b6127371a80d54a0ab4ec2d80af9fada2bd7d8c780cc73a7f9ad00e1e1R217 

(by removing unnecessary div wrapper)

Comment (LokeshsaiP) [reply src/components/Questionnaire/ValueSetSelect.tsx]: yeah I've checked it, will do the same way 👍

**Comment by nihal467** [comment]
image

- the alignment issue still exist

**Comment by LokeshsaiP** [comment]
> image
> * the alignment issue still exist

Resolved this by giving a fixed height to FormMessage field.

File: src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx [hunk 4]
```diff
@@ -424,7 +424,9 @@ function ObservationDefinitionFormContent({
                               ))}
                             </SelectContent>
                           </Select>
-                          <FormMessage />
+                          <div style={{ minHeight: "1.25rem" }}>
+                            <FormMessage />
+                          </div>
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx]: Not need of it 

add flex flex-col .... to FormItem

Comment (LokeshsaiP) [reply src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx]: Done, I got tunnel visioned and overlooked that, also added clearErrors to the loinc code section after the user populates it 👍.

File: src/components/Questionnaire/ValueSetSelect.tsx [hunk 5]
```diff
@@ -237,25 +237,23 @@ export default function ValueSetSelect({
...
-                  {value?.display && showCode && (
-                    <span className="text-xs ml-1">({value?.code})</span>
-                  )}
-                </span>
-                <CaretSortIcon className="ml-2 size-4 shrink-0 opacity-50" />
-              </Button>
-            </div>
+              </span>
+              <CaretSortIcon className="ml-2 size-4 shrink-0 opacity-50" />
+            </Button>
```
Comment (abhimanyurajeesh) [inline src/components/Questionnaire/ValueSetSelect.tsx:197]: why?

**Review by abhimanyurajeesh — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/ValueSetSelect.tsx (hunk 5 above)
Comment (abhimanyurajeesh) [reply src/components/Questionnaire/ValueSetSelect.tsx:197]: @LokeshsaiP if this is required make sure its not breaking in other place

Comment (LokeshsaiP) [reply src/components/Questionnaire/ValueSetSelect.tsx:197]: @abhimanyurajeesh I initially disabled horizontal padding with px-0 
and @AdityaJ2305 suggested to remove the div wrapper.
[here](https://github.com/ohcnetwork/care_fe/pull/13086#discussion_r2272357423)👆
I'll look further at other places where it causes issue 👍

**Comment by nihal467** [comment]
LGTM

File: src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx (hunk 4 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx]: ..... he said this <div style={{ minHeight: "1.25rem" }}> is not needed

**Review by abhimanyurajeesh — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
