### PR TITLE
Fix: AutoComplete not getting scroll and focused on error 

### LINKED ISSUE #12672: `AutoComplete` not getting scroll and focused on error
**Describe the bug**
Observed in Resource form where AutoComplete is used for Facility select, the autocomplete is not getting scroll to and focus (like red border) on validation error or any error thrown

**Expected behaviour**
AutoComplete should get focus on error like have red-border just like Select component got red-border in video shared  and scroll

**Screenshots**

https://github.com/user-attachments/assets/d5fcf2cd-69a6-4b23-94d0-fcf0362872f7

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #12672
- Added `ref ` to trigger button so it could get ref passed by field from form
- Used `aria-invalid` attibute injected  by FormControl to the child (here <autocomplete/>)

https://github.com/user-attachments/assets/ba173b82-2fef-4f27-8982-d18eff94e9cf

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Improved visual feedback for invalid form fields by highlighting buttons with a red border and ring when invalid.
- **Refactor**
  - Simplified form submission and error handling in the facility form for a smoother user experience.
  - Enhanced form field integration and accessibility by forwarding refs and using standard `aria-invalid` attributes in form components.
  - Improved synchronization and event handling for autocomplete and organization selector fields.
- **Accessibility**
  - Increased accessibility compliance by adopting `aria-invalid` attributes for form controls.

### CODE REVIEW

File: src/components/ui/autocomplete.tsx [hunk 1]
```diff
@@ -44,6 +44,10 @@ interface AutocompleteProps {
   freeInput?: boolean;
   closeOnSelect?: boolean;
   "data-cy"?: string;
+
+  ref?: React.RefCallback<HTMLButtonElement | null>;
+
+  isError?: boolean;
```
Comment (AdityaJ2305) [inline src/components/ui/autocomplete.tsx]: Hey team,
Technically, we should be using the aria-invalid attribute that’s already being passed via {...field} — that’s how Select  highlight fields on error. But right now, it’s only implemented for Select in our codebase. Ideally, we should apply the same CSS class for shadcn button component too (I checked, and ShadCN does have on their site).

Let me know your thoughts — I can update the things accordingly

Comment (AdityaJ2305) [reply src/components/ui/autocomplete.tsx]: doing this

File: src/pages/Organization/components/GovtOrganizationSelector.tsx [hunk 2]
```diff
@@ -16,6 +16,10 @@ interface GovtOrganizationSelectorProps {
   required?: boolean;
   authToken?: string;
   selected?: Organization[];
+
+  ref?: React.RefCallback<HTMLButtonElement | null>;
+
+  "aria-invalid"?: boolean;
```
Comment (Jacobjeevan) [inline src/pages/Organization/components/GovtOrganizationSelector.tsx:22]: who's passing value for this prop? 🤔

File: src/pages/PublicAppointments/PatientRegistration.tsx [hunk 3]
```diff
@@ -409,6 +409,7 @@ export function PatientRegistration(props: PatientRegistrationProps) {
                   <FormItem className="flex flex-col">
                     <FormControl>
                       <GovtOrganizationSelector
+                        {...field}
```
Comment (Jacobjeevan) [inline src/pages/PublicAppointments/PatientRegistration.tsx:412]: Because field doesn't have aria-invalid 🤔

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Organization/components/GovtOrganizationSelector.tsx (hunk 2 above)
Comment (AdityaJ2305) [reply src/pages/Organization/components/GovtOrganizationSelector.tsx:22]: FormControl passes / injects these attributes to child component in this case <Autocomplete/> 

ref:  https://github.com/ohcnetwork/care_fe/blob/9723c0ebfacb148d91d3afede2e2b2c664ea1f1f/src/components/ui/form.tsx#L122

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
