### PR TITLE
fix: ensure valid patient_preparation

### LINKED ISSUE #13056: Prevent Duplicate selection for Patient Preparation in Specimen definition form
**Describe the bug**
While adding patient preparation , it doesn't restrict duplicate entries which could lead to accidental duplication and while going through code I also realised we aren't using `useFieldArray` property for the same 

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Janetmaria**
## Proposed Changes

- Fixes #13056 
- Replaced existing FormField logic for patient_preparation with useFieldArray from react-hook-form.
- Prevents duplicate selections in patient_preparation using a validation check before update.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **New Features**
  * Dynamic management for patient preparation entries with per-item add/remove controls and improved placeholders.

* **Bug Fixes**
  * Prevents adding duplicate patient preparation entries with inline duplicate checks and shows an error toast.
  * Submission now filters out incomplete patient preparation entries.

* **Localization**
  * Added English message for duplicate patient preparation warnings.

### CODE REVIEW

File: src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx [hunk 1]
```diff
@@ -4,7 +4,9 @@ import { PlusCircle, XCircle } from "lucide-react";
 import { navigate } from "raviger";
 import React from "react";
 import { useForm } from "react-hook-form";
+import { useFieldArray } from "react-hook-form";
 import { useTranslation } from "react-i18next";
+import { toast } from "react-toastify";
```
[the remark this answers is not in the document]
Comment (AdityaJ2305) [reply src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx]: @Janetmaria , coderabbit is right although we don't want to install toastify here instead update it to  below 

```suggestion
import { toast } from "sonner";
```

File: src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx [hunk 2]
```diff
@@ -96,7 +98,7 @@ const formSchema = z.object({
     .url({ message: "Please enter a valid URL" })
     .optional(),
   type_collected: CodeSchema,
-  patient_preparation: z.array(CodeSchema).min(0),
+  patient_preparation: z.array(CodeSchema.optional()).min(0),
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx]: I know you did `optional` to pass `undefined` on append but this could create confusion instead pass empty object and filter it  before submitting like it was already filtering

File: src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx [hunk 3]
```diff
@@ -127,7 +129,9 @@ export function SpecimenDefinitionForm({
       description: initialData?.description,
       derived_from_uri: initialData?.derived_from_uri ?? undefined,
       type_collected: initialData?.type_collected,
-      patient_preparation: initialData?.patient_preparation ?? [],
+      patient_preparation: (initialData?.patient_preparation ?? []).filter(
+        Boolean,
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx]:
```suggestion
      patient_preparation: (initialData?.patient_preparation ?? []),
```

File: src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx [hunk 4]
```diff
@@ -217,11 +205,13 @@ export function SpecimenDefinitionForm({
...
 
-  const handleSubmit = (data: SpecimenDefinitionCreate) => {
+  const handleSubmit = (data: FormValues) => {
     onSubmit({
       ...data,
       patient_preparation:
-        data.patient_preparation?.filter((item) => item && item.code) || [],
+        data.patient_preparation?.filter(
+          (item): item is Code => !!item && !!item.code,
+        ) || [],
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx]: not make change here , reason is stated in above message alreaady

File: src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx [hunk 5]
```diff
@@ -411,42 +401,53 @@ export function SpecimenDefinitionForm({
...
+                          </FormControl>
+                          {fields.length > 1 && (
+                            <Button
+                              type="button"
+                              variant="ghost"
+                              size="icon"
+                              onClick={() => remove(index)}
+                              className="size-10"
+                            >
+                              <XCircle className="h-5 w-5" />
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx]: Do it at every place in this file 

```suggestion
                              <XCircle className="size-5" />
```

File: public/locale/en.json [hunk 6]
```diff
@@ -1560,6 +1560,8 @@
   "due_date": "Due Date",
   "duplicate": "Duplicate",
   "duplicate_contact_values_not_allowed": "Duplicate contact values are not allowed across different contact types",
+  "duplicate_patient_preparation": "This patient preparation has already been added",
+  "duplicate_patient_preparation_not_allowed": "Duplicate patient preparation is not allowed",
```
Comment (AdityaJ2305) [inline public/locale/en.json]: remove unused key 

```suggestion

```

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]
check and add translation for every place needed in the file

File: src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx [hunk 7]
```diff
@@ -411,42 +397,55 @@ export function SpecimenDefinitionForm({
...
-                              </Button>
-                            )}
-                          </div>
-                        ),
-                      )}
+                              }}
+                              disabled={isLoading}
+                            />
+                          </FormControl>
+                          {fields.length > 1 && (
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx]:
```suggestion
                          {fields.length > 0 && (
```

**Review by AdityaJ2305 — APPROVED** [review]

**Comment by AdityaJ2305** [comment]
@Janetmaria , May be we should have different flow to select patient preparation here instead of adding new field then selecting for each field 

Not related to this PR 👍  just sharing thoughts

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx [hunk 8]
```diff
@@ -4,7 +4,9 @@ import { PlusCircle, XCircle } from "lucide-react";
 import { navigate } from "raviger";
 import React from "react";
 import { useForm } from "react-hook-form";
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx]:
```suggestion
import { useFieldArray, useForm } from "react-hook-form";
```

File: src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx [hunk 9]
```diff
@@ -4,7 +4,9 @@ import { PlusCircle, XCircle } from "lucide-react";
...
+import { useFieldArray } from "react-hook-form";
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/specimen-definitions/SpecimenDefinitionForm.tsx]:
```suggestion

```

**Review by rithviknishad — APPROVED** [review]
