### PR TITLE
Fixed Add a better search UI for patients index page #8691

### LINKED ISSUE #8691: Add a better search UI for patients index page
In the current patient page, we have 4 independet search on patient, at any point in time you can only search by one practically.
Here is an how the current UI looks.  
image

Let upgrade it with a smart search compoent where the user can select what to search for. 
image

It should also support keyboard short cuts. 
image

The valid options would be Name | Phone Number | OP/IP number | Emergency Contact Number.

Also reduce the height of the count box to match the component.

### PR DESCRIPTION
**Pull request by i0am0arunava**
## Proposed Changes

- Fixes #8691

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Release Notes

- **New Features**
	- Introduced a `SearchByMultipleFields` component for enhanced search functionality across various fields.
	- Added a customizable dialog interface using Radix UI components.
	- Implemented a command interface with multiple components for improved user interaction.
	- Enhanced phone number input with better error handling and help text visibility.
	- Added new components for popover and scroll area functionalities.

- **Bug Fixes**
	- Updated selectors for patient and facility search inputs to ensure correct functionality.

- **Improvements**
	- Streamlined the layout and organization of the `ManagePatients` and `FacilityList` components.
	- Enhanced localization support for search functionalities.
	- Improved search input handling and added a debounce mechanism for performance.

- **Chores**
	- Updated dependencies in `package.json` for improved functionality and performance.

### CODE REVIEW

File: src/Components/Form/FormFields/FormField.tsx [hunk 1]
```diff
@@ -71,7 +71,9 @@ const FormField = ({
         )}
       </div>
       <div className={field?.className}>{props.children}</div>
-      <FieldErrorText error={field?.error} className={field?.errorClassName} />
+      {field?.error && (
+        <FieldErrorText error={field.error} className={field?.errorClassName} />
+      )}
```
Comment (rithviknishad) [inline src/Components/Form/FormFields/FormField.tsx]: use `errorClassName="hidden"` instead. This change will now cause layout shift everytime an error appears or disappears which is not ideal.

File: src/Components/Form/FormFields/PhoneNumberFormField.tsx
Comment (rithviknishad) [inline src/Components/Form/FormFields/PhoneNumberFormField.tsx:1]: Avoid changing this component as this affects the design in all other places too.

File: src/Components/Common/SearchByMultipleFields.tsx [hunk 2]
```diff
@@ -0,0 +1,220 @@
...
+    },
+    [selectedOption, onSearch],
+  );
+
+  const renderSearchInput = useMemo(() => {
+    const commonProps = {
+      ref: inputRef,
+      value: searchValue,
+      onChange: (e: any) =>
+        handleSearchChange(e.target ? e.target.value : e.value),
```
Comment (rithviknishad) [inline src/Components/Common/SearchByMultipleFields.tsx]: do not use `any` type.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Form/FormFields/PhoneNumberFormField.tsx
Comment (bodhish) [reply src/Components/Form/FormFields/PhoneNumberFormField.tsx:1]: @rithviknishad I made these changes, I checked how it looked in patient regestation page, can you recheck this is fine, trying to create a low profile input for the number field componenent.

File: src/Components/Form/FormFields/FormField.tsx (hunk 1 above)
Comment (bodhish) [reply src/Components/Form/FormFields/FormField.tsx]: I was just irritated with how it was talking up space under the input, hidden works;

File: src/Components/Common/SearchByMultipleFields.tsx [hunk 3]
```diff
@@ -0,0 +1,220 @@
...
+                <CommandGroup>
+                  {options.map((option) => (
+                    <CommandItem
+                      key={option.key}
+                      onSelect={() => handleOptionChange(option)}
+                    >
+                      <CareIcon icon="l-search" className="mr-2 h-4 w-4" />
+                      <span className="flex-1">{t(option.label)}</span>
+                      <kbd className="ml-auto text-xs text-gray-400">
+                        {option.label.charAt(0).toUpperCase()}
```
Comment (bodhish) [inline src/Components/Common/SearchByMultipleFields.tsx]: The shortcut in the config should be used here. Also does the kbd work? 🤔 (I rember writing a catach all logic at top, that needs to rechecked)

File: src/Components/Common/SearchByMultipleFields.tsx [hunk 4]
```diff
@@ -0,0 +1,220 @@
...
+  }, [
+    selectedOption,
+    searchValue,
+    handleSearchChange,
+    handleKeyDown,
+    t,
+    inputClassName,
+  ]);
+
+  return (
```
Comment (bodhish) [inline src/Components/Common/SearchByMultipleFields.tsx]: This component should have a default state where it says a simple help text. EG 
image

**Review by bodhish — CHANGES_REQUESTED** [review]
We should test it out as I am sure we haven't captured all edge cases here

**Comment by bodhish** [comment]
@nihal467 do test it

Also @i0am0arunava please add a good title for the PR

File: src/Components/Form/FormFields/PhoneNumberFormField.tsx
Comment (rithviknishad) [reply src/Components/Form/FormFields/PhoneNumberFormField.tsx:1]: Yup, looks fine.

File: src/Components/Form/FormFields/FormField.tsx (hunk 1 above)
Comment (rithviknishad) [reply src/Components/Form/FormFields/FormField.tsx]: then let's switch to `hidden`. looks like this currently

image

**Comment by vinutv** [comment]
Screenshot 2024-10-21 at 2 15 39 PM

It's great that shortcut keys are available to access the search type from the dropdown. The dropdown should also be navigable using the up and down arrow keys on the keyboard.

**Comment by vinutv** [comment]
Screenshot 2024-10-21 at 2 19 30 PM

The error message is hidden under the search buttons.

**Comment by vinutv** [comment]
Screenshot 2024-10-21 at 2 25 25 PM

Typed "/" and selected "Phone Number," but the phone number field didn't get focused. It should focus on the phone number input to make it typable when the search type is selected. However, the focus remains on the search button.

**Comment by nihal467** [comment]
@i0am0arunava can you fix the lint, resolve conflicts, and make the requested changes to get it ready for review

**Comment by i0am0arunava** [comment]
> @i0am0arunava can you fix the lint, resolve conflicts, and make the requested changes to get it ready for review

Yes, give me some time,

File: src/Components/Form/FormFields/FormField.tsx (hunk 1 above)
Comment (i0am0arunava) [reply src/Components/Form/FormFields/FormField.tsx]: > use `errorClassName="hidden"` instead. This change will now cause layout shift everytime an error appears or disappears which is not ideal.

added

File: src/Components/Common/SearchByMultipleFields.tsx (hunk 2 above)
Comment (i0am0arunava) [reply src/Components/Common/SearchByMultipleFields.tsx]: > do not use `any` type.

done, please check

**Comment by i0am0arunava** [comment]
> Screenshot 2024-10-21 at 2 25 25 PM
> Typed "/" and selected "Phone Number," but the phone number field didn't get focused. It should focus on the phone number input to make it typable when the search type is selected. However, the focus remains on the search button.

added 

https://github.com/user-attachments/assets/1109b57d-3254-4776-bcae-44d34cbf24d8

**Comment by i0am0arunava** [comment]
> @i0am0arunava can you fix the lint, resolve conflicts, and make the requested changes to get it ready for review

done

**Comment by i0am0arunava** [comment]
@rithviknishad,@bodhish ,@nihal467, I have made changes and raised pr please review .

**Comment by bodhish** [comment]
I don't see any of the changes Vinu requested implemented!

**Comment by bodhish** [comment]
Also did you break the mobile input its showing IN instead of the country logo 🤔

**Comment by i0am0arunava** [comment]
> I don't see any of the changes Vinu requested implemented!

I made the changes ,https://github.com/ohcnetwork/care_fe/pull/8834#issuecomment-2430049333

**Comment by i0am0arunava** [comment]
> Also did you break the mobile input its showing IN instead of the country logo 🤔

No ,okay I will check

**Comment by i0am0arunava** [comment]
@rithviknishad, @bodhish, @nihal467, please check. I have made the changes and fixed the issues as per the requirements. 
errorclassname="hidden", use custom type instead of using any, merge the develop branch resolving merge conflict

https://github.com/user-attachments/assets/176cf33f-65c0-4264-9ed1-d7fd9f745d12

**Comment by i0am0arunava** [comment]
> Also did you break the mobile input its showing IN instead of the country logo 🤔

No,I checked , it was previously like that.

**Comment by bodhish** [comment]
> > Also did you break the mobile input its showing IN instead of the country logo 🤔
> 
> 
> 
> No,I checked , it was previously like that.

No, It was showing the flag, check the screenshot from vinu on the same thread; 

Screenshot 2024-10-21 at 2 15 39 PM

**Comment by i0am0arunava** [comment]
> > > Also did you break the mobile input its showing IN instead of the country logo 🤔
> > 
> > 
> > No,I checked , it was previously like that.
> 
> No, It was showing the flag, check the screenshot from vinu on the same thread;
> 
> Screenshot 2024-10-21 at 2 15 39 PM

 Okay, I will fix that. Actually, I merged your /filter-component branch, which I think caused this

**Comment by bodhish** [comment]
> > > > Also did you break the mobile input its showing IN instead of the country logo 🤔
> > > 
> > > 
> > > No,I checked , it was previously like that.
> > 
> > 
> > No, It was showing the flag, check the screenshot from vinu on the same thread;
> > Screenshot 2024-10-21 at 2 15 39 PM
> 
> Okay, I will fix that. Actually, I merged your /filter-component branch, which I think caused this

@i0am0arunava Its working on the branch!, I just checked now. 

image

🤔 🤔 🤔 🤔 🤔

File: src/Components/Form/FormFields/FormField.tsx (hunk 1 above)
Comment (i0am0arunava) [reply src/Components/Form/FormFields/FormField.tsx]: > then let's switch to `hidden`. looks like this currently
> 
> image

@rithviknishad   from which page you have taken this screenshot ,actually in my system  flag emoji is not coming and it is showing 'IN' in the ph number input field

Comment (rithviknishad) [reply src/Components/Form/FormFields/FormField.tsx]: Assets > Select an asset > Update

**Comment by i0am0arunava** [comment]
> > > Also did you break the mobile input its showing IN instead of the country logo 🤔
> > 
> > 
> > No,I checked , it was previously like that.
> 
> No, It was showing the flag, check the screenshot from vinu on the same thread;
> 
> Screenshot 2024-10-21 at 2 15 39 PM

@bodhish , I checked ,that is not my fault ,actually this is not working in my system 

> > > > > Also did you break the mobile input its showing IN instead of the country logo 🤔
> > > > 
> > > > 
> > > > No,I checked , it was previously like that.
> > > 
> > > 
> > > No, It was showing the flag, check the screenshot from vinu on the same thread;
> > > Screenshot 2024-10-21 at 2 15 39 PM
> > 
> > 
> > Okay, I will fix that. Actually, I merged your /filter-component branch, which I think caused this
> 
> @i0am0arunava Its working on the branch!, I just checked now.
> 
> image
> 🤔 🤔 🤔 🤔 🤔

@bodhish ,I cloned your branch filter-component ,it is not working in my system

**Comment by i0am0arunava** [comment]
@rithviknishad, @bodhish, @nihal467, 
I searched it in google and found that in some browsers, emojis will not work properly. Flag Emoji is properly working in firefox but not in chrome browser
Screenshot 2024-10-24 214330

**Comment by nihal467** [comment]
@i0am0arunava 

image

- [ ] entire form spacing is effected, with your PR, revert it back

image

- [ ] the phone number filter badge is always present in the form
- [ ] unable to open new patient registration form through patient tab
- [ ] fix all the cypress failure issues


CC: @bodhish @gigincg

**Comment by i0am0arunava** [comment]
> @i0am0arunava
> 
> image
> 
> * [x]  entire form spacing is effected, with your PR, revert it back
> 
> image
> 
> * [x]  the phone number filter badge is always present in the form
> * [x]  unable to open new patient registration form through patient tab
> * [x]  fix all the cypress failure issues
> 
> CC: @bodhish @gigincg

@nihal467 ,from which page you have taken the 'FORM'  screenshot?

**Comment by nihal467** [comment]
New asset creation form

File: src/Components/Form/FormFields/FormField.tsx (hunk 1 above)
Comment (bodhish) [reply src/Components/Form/FormFields/FormField.tsx]: This issue is not resolved

Comment (i0am0arunava) [reply src/Components/Form/FormFields/FormField.tsx]: > This issue is not resolved

I'm sorry, I added errorClassName="hidden" but didn't check whether it works or not. I will fix that

**Comment by i0am0arunava** [comment]
> Screenshot 2024-10-21 at 2 19 30 PM
> The error message is hidden under the search buttons.

@bodhish @rithviknishad

**Comment by i0am0arunava** [comment]
> @i0am0arunava
> 
> image
> 
> * [ ]  entire form spacing is effected, with your PR, revert it back
> 
> image
> 
> * [ ]  the phone number filter badge is always present in the form
> * [ ]  unable to open new patient registration form through patient tab
> * [ ]  fix all the cypress failure issues
> 
> CC: @bodhish @gigincg

@nihal467 ,can you please share the cypress failed test cases ,it is not showing here

File: src/components/Form/FormFields/FormField.tsx [hunk 5]
```diff
@@ -71,7 +71,9 @@ const FormField = ({
         )}
       </div>
       <div className={field?.className}>{props.children}</div>
-      <FieldErrorText error={field?.error} className={field?.errorClassName} />
+      {field?.error && (
```
Comment (bodhish) [inline src/components/Form/FormFields/FormField.tsx]: Passing on hidden for hiding the state was the recommendation from @rithviknishad 

Please make that change.

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 6]
```diff
@@ -7,7 +7,7 @@ import {
   formatPhoneNumber as formatPhoneNumberUtil,
   getCountryCode,
   CountryData,
-  humanizeStrings,
+  // humanizeStrings,
```
Comment (bodhish) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx]: Clean up if you are not using the variable!

File: src/components/Form/FormFields/Utils.ts [hunk 7]
```diff
@@ -1,6 +1,6 @@
 import { FieldError } from "../FieldValidators";
 
-export type FieldChangeEvent<T> = { name: string; value: T };
+export type FieldChangeEvent<T> = { name: string; value: T; target?: any };
```
Comment (bodhish) [inline src/components/Form/FormFields/Utils.ts]: Lets define the type; 
Also is the target required?

File: src/components/Patient/ManagePatients.tsx [hunk 8]
```diff
@@ -12,8 +12,8 @@ import {
 } from "@/common/constants";
 import { FacilityModel, PatientCategory } from "../Facility/models";
 import { Link, navigate } from "raviger";
-import { ReactNode, useEffect, useState } from "react";
-import { parseOptionId } from "@/common/utils";
+import { ReactNode, useEffect, useState, useCallback } from "react";
+import { parseOptionId } from "../../common/utils";
```
Comment (bodhish) [inline src/components/Patient/ManagePatients.tsx]: why not sure at @/ 🤔

File: src/components/Patient/ManagePatients.tsx [hunk 9]
```diff
@@ -23,13 +23,13 @@ import CountBlock from "../../CAREUI/display/Count";
 import DoctorVideoSlideover from "../Facility/DoctorVideoSlideover";
 import { ExportMenu } from "@/components/Common/Export";
 import FacilitiesSelectDialogue from "../ExternalResult/FacilitiesSelectDialogue";
-import { FieldChangeEvent } from "../Form/FormFields/Utils";
+
```
Comment (bodhish) [inline src/components/Patient/ManagePatients.tsx]: empty line!

File: src/components/Patient/ManagePatients.tsx [hunk 10]
```diff
@@ -23,13 +23,13 @@ import CountBlock from "../../CAREUI/display/Count";
...
 import FilterBadge from "../../CAREUI/display/FilterBadge";
 import PatientFilter from "./PatientFilter";
-import PhoneNumberFormField from "../Form/FormFields/PhoneNumberFormField";
+
```
Comment (bodhish) [inline src/components/Patient/ManagePatients.tsx]: Another empty line!

File: src/components/Patient/ManagePatients.tsx [hunk 11]
```diff
@@ -23,13 +23,13 @@ import CountBlock from "../../CAREUI/display/Count";
...
 import RecordMeta from "../../CAREUI/display/RecordMeta";
-import SearchInput from "../Form/SearchInput";
-import SortDropdownMenu from "@/components/Common/SortDropdown";
+
+import SortDropdownMenu from "../Common/SortDropdown";
```
Comment (bodhish) [inline src/components/Patient/ManagePatients.tsx]: why do we have to make this change?

File: src/components/Patient/ManagePatients.tsx [hunk 12]
```diff
@@ -48,16 +48,18 @@ import {
...
-import request from "../../Utils/request/request";
-import { Avatar } from "@/components/Common/Avatar";
+} from "./DiagnosesFilter.js";
+import { ICD11DiagnosisModel } from "../Diagnosis/types.js";
+import { getDiagnosesByIds } from "../Diagnosis/utils.js";
+import Tabs from "../Common/components/Tabs.js";
+
+import { isPatientMandatoryDataFilled } from "./Utils.js";
+import request from "../../Utils/request/request.js";
+import { Avatar } from "../Common/Avatar.js";
```
Comment (bodhish) [inline src/components/Patient/ManagePatients.tsx]: Addition on `.js` in correct, all of those files are written in typescript. Also why this change?

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 13]
```diff
@@ -7,7 +7,7 @@ import {
   formatPhoneNumber as formatPhoneNumberUtil,
```
Comment (bodhish) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx]: Changes in this file needs to be extensively reviewed and tested.

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 14]
```diff
@@ -28,146 +28,133 @@ interface Props extends FormFieldBaseProps<string> {
...
-          }}
-        </Popover>
-      </div>
-    </FormField>
-  );
-}
-
-const PhoneNumberTypesHelp = (props: { types: PhoneNumberType[] }) => {
-  const { t } = useTranslation();
+    useEffect(() => {
```
Comment (bodhish) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx]: Is this required? 🤔 You are setting the default country in line :35, why would you want another effect 🤔

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 15]
```diff
@@ -200,7 +187,7 @@ const CountryCodesList = ({
   const [searchValue, setSearchValue] = useState<string>("");
 
   return (
-    <div className="absolute z-10 w-full rounded-md border border-secondary-300 bg-white shadow-lg transition-all duration-300">
+    <div className="absolute z-10 w-full rounded-md border border-gray-300 bg-white shadow-lg transition-all duration-300">
```
Comment (bodhish) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx]: I think we should use secondary instead of gray

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 16]
```diff
@@ -273,3 +260,4 @@ const CountryCodesList = ({
     </div>
   );
 };
+export default PhoneNumberFormField;
```
Comment (bodhish) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx:291]: Add it as part of the function itself? Like it was already written 🤔

File: package.json [hunk 17]
```diff
@@ -96,6 +101,7 @@
     "rehype-raw": "^6.1.1",
     "tailwind-merge": "^2.5.2",
     "tailwindcss-animate": "^1.0.7",
+    "twemoji": "^14.0.2",
```
Comment (bodhish) [inline package.json]: I couldn't find a usage of the package!
Where are we using it?

File: src/components/Common/SearchByMultipleFields.tsx [hunk 18]
```diff
@@ -0,0 +1,245 @@
...
+} from "@/components/ui/popover";
+
+interface SearchOption {
+  key: string;
+  label: string;
+  type: "text" | "phone";
+  placeholder: string;
+  value: string;
+  shortcut_key: string;
+  component?: React.ComponentType<any>;
```
Comment (bodhish) [inline src/components/Common/SearchByMultipleFields.tsx]: lets not use `any`

**Review by bodhish — CHANGES_REQUESTED** [review]
- `+91` filter is getting applied just by navigating to the patients page 🤔 
image
- Can see 3 highlights on the dropdown, not sure why
image'

- Default state mentioned on the previous comment is not implemented

**Comment by i0am0arunava** [comment]
> @i0am0arunava
> 
> image
> 
> * [ ]  entire form spacing is effected, with your PR, revert it back
> 
> image
> 
> * [ ]  the phone number filter badge is always present in the form
> * [ ]  unable to open new patient registration form through patient tab
> * [ ]  fix all the cypress failure issues
> 
> CC: @bodhish @gigincg

@nihal467 @bodhish @rithviknishad ,is this error showing part okay now?

https://github.com/user-attachments/assets/aee38d51-9650-4644-b25f-32c76c2f5dce

**Comment by i0am0arunava** [comment]
> Screenshot 2024-10-21 at 2 19 30 PM
> The error message is hidden under the search buttons.

@bodhish @rithviknishad ,is this okay now 

https://github.com/user-attachments/assets/a423460e-e71a-4870-b446-1b7ffa242284

**Comment by bodhish** [comment]
Error message looks fine

File: package.json (hunk 17 above)
Comment (i0am0arunava) [reply package.json]: > I couldn't find a usage of the package! Where are we using it?

no use ,I will remove it ,actually chrome browser is not showing flag emoji then I installed it, This is no longer of any use.I will remove it

**Comment by i0am0arunava** [comment]
> * `+91` filter is getting applied just by navigating to the patients page 🤔
> 
> image - Can see 3 highlights on the dropdown, not sure why image - Default state mentioned on the previous comment is not implemented

@bodhish ,I think now it is working fine 

https://github.com/user-attachments/assets/fc1d21b3-a21c-4ded-9c45-f0af42039af2

File: src/components/Form/FormFields/FormField.tsx (hunk 5 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/FormField.tsx]: I am passing the errorclassname=hidden as a props

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 16 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx:291]: I am using forwordref and if I add this export default in same line it will throw an error

**Comment by i0am0arunava** [comment]
@bodhish @rithviknishad I have tried my best to solve the issue , i would like to request you to test the changes and do the needful .

File: src/components/Form/FormFields/FormField.tsx (hunk 5 above)
Comment (rithviknishad) [reply src/components/Form/FormFields/FormField.tsx]: that also means to revert changes made here @i0am0arunava .

This change breaks the UI in most of the forms.

File: src/components/Form/FormFields/Utils.ts [hunk 19]
```diff
@@ -1,7 +1,13 @@
...
-
-export type FieldChangeEvent<T> = { name: string; value: T };
+interface targettype {
+  value: string;
+}
+export type FieldChangeEvent<T> = {
+  name: string;
+  value: T;
+  target?: targettype;
+};
```
Comment (rithviknishad) [inline src/components/Form/FormFields/Utils.ts]: 1. what is `targettype`? 
2. is this really needed? is there any other way to solve this without allowing target to be passed?

File: src/components/Facility/AssetCreate.tsx
Comment (rithviknishad) [inline src/components/Facility/AssetCreate.tsx:1]: why is asset create form changed in this PR?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Form/FormFields/Utils.ts (hunk 19 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/Utils.ts]: > 1. what is `targettype`?
> 2. is this really needed? is there any other way to solve this without allowing target to be passed?

@rithviknishad  1.-> Actually it was showing typecript error under e.target.value .and I tried to make it without using this process but this was causing some error in other compnent .

Comment (rithviknishad) [reply src/components/Form/FormFields/Utils.ts]: `FieldChangeEvent` is not expected to be used with HTML Elements, it's expected to be used by custom built FormField components only.

File: src/components/Facility/AssetCreate.tsx
Comment (i0am0arunava) [reply src/components/Facility/AssetCreate.tsx:1]: > why is asset create form changed in this PR?

@rithviknishad , nihal requsted me to make this chage --> https://github.com/ohcnetwork/care_fe/pull/8834#issuecomment-2437670768 . And I have just  added only spaces nothing else. And it looks like before

Comment (rithviknishad) [reply src/components/Facility/AssetCreate.tsx:1]: the solution to that is solving what's mentioned in https://github.com/ohcnetwork/care_fe/pull/8834#discussion_r1817999924 right? And not updating the spacing in the asset create form.

The mentioned issue is not just limited to asset create form actually. It's present in almost everywhere else too...

image

image

Comment (i0am0arunava) [reply src/components/Facility/AssetCreate.tsx:1]: @rithviknishad @bodhish  I merged Bodhi's branch and noticed that the space was already affected in his branch. What should I do?

File: src/components/Form/FormFields/FormField.tsx (hunk 5 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/FormField.tsx]: > that also means to revert changes made here @i0am0arunava .
> 
> This change breaks the UI in most of the forms.

done this

**Comment by i0am0arunava** [comment]
> @i0am0arunava
> 
> image
> 
> * [x]  entire form spacing is effected, with your PR, revert it back
> 
> image
> 
> * [x]  the phone number filter badge is always present in the form
> * [x]  unable to open new patient registration form through patient tab
> * [x]  fix all the cypress failure issues
> 
> CC: @bodhish @gigincg

fixed that

File: src/components/Form/FormFields/Utils.ts (hunk 19 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/Utils.ts:10]: @rithviknishad ,React.ChangeEvent<HTMLInputElement> will not work

Comment (i0am0arunava) [reply src/components/Form/FormFields/Utils.ts]: > `FieldChangeEvent` is not expected to be used with HTML Elements, it's expected to be used by custom built FormField components only.
this type is working properly .If I use any inbuilt types like .... ChangeEvent<HTMLInputElement>    
,will show error. what I can do

File: src/components/Facility/AssetCreate.tsx
Comment (i0am0arunava) [reply src/components/Facility/AssetCreate.tsx:1]: > the solution to that is solving what's mentioned in [#8834 (comment)](https://github.com/ohcnetwork/care_fe/pull/8834#discussion_r1817999924) right? And not updating the spacing in the asset create form.
> 
> The mentioned issue is not just limited to asset create form actually. It's present in almost everywhere else too...
> 
> image image

@rithviknishad ,done this please test my code

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 20]
```diff
@@ -17,157 +16,146 @@ import {
 } from "../FieldValidators";
 import CareIcon from "../../../CAREUI/icons/CareIcon";
 import { Popover, PopoverButton, PopoverPanel } from "@headlessui/react";
-import { useTranslation } from "react-i18next";
-
+import React from "react";
 const phoneCodes: Record<string, CountryData> = phoneCodesJson;
 
 interface Props extends FormFieldBaseProps<string> {
+  myfunc?: (er: FieldError) => void;
```
Comment (rithviknishad) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx]: what is `myfunc`? can we use proper names for the props so that it's understandable?

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 21]
```diff
@@ -17,157 +16,146 @@ import {
...
-        return;
+        setError(error);
+      },
+      [field, validate, error],
+    );
+    useEffect(() => {
+      if (field.value!.length > 3) {
+        if (props.myfunc) {
+          props.myfunc(error);
+        }
```
Comment (rithviknishad) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx]: not readable / understandable. what does this do? i don't think this logic needs to be kept here.

File: src/components/Form/FormFields/Utils.ts (hunk 19 above)
Comment (rithviknishad) [reply src/components/Form/FormFields/Utils.ts]: Let's not use types provided by FormField components along with Shadcn components. Revert this change.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 20 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: @rithviknishad it will show error when any error appear in phone number field or any serchfield in the serchbyfieldComponent

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 21 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: https://github.com/ohcnetwork/care_fe/pull/8834#issuecomment-2439930727

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 20 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: https://github.com/ohcnetwork/care_fe/pull/8834#issuecomment-2439930727

Comment (rithviknishad) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: you don't need to modify PhoneNumberFormField for that. Just check the value in the search by field component and show error from there.

Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: @rithviknishad  What is the problem?I tried to do this but 
To access value from phcompo to serchcompo using the ref  is creating problem and complexity

Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: @rithviknishad ,I have define a type of instead of this https://github.com/ohcnetwork/care_fe/pull/8834#discussion_r1822685003
, please check

**Comment by i0am0arunava** [comment]
@rithviknishad @nihal467 ,done this https://github.com/ohcnetwork/care_fe/pull/8834#discussion_r1822685003 ,is it ready for testing

File: src/components/Common/SearchByMultipleFields.tsx [hunk 22]
```diff
@@ -0,0 +1,260 @@
...
+  PopoverTrigger,
+} from "@/components/ui/popover";
+
+interface SearchOption {
+  key: string;
+  label: string;
+  type: "text" | "phone";
+  placeholder: string;
+  value: string;
+  shortcut_key: string;
```
Comment (rithviknishad) [inline src/components/Common/SearchByMultipleFields.tsx]: https://docs.aws.amazon.com/prescriptive-guidance/latest/best-practices-cdk-typescript-iac/typescript-best-practices.html#naming-conventions

File: src/components/Common/SearchByMultipleFields.tsx [hunk 23]
```diff
@@ -0,0 +1,260 @@
...
+interface SearchByMultipleFieldsProps {
+  options: SearchOption[];
+  onSearch: (key: string, value: string) => void;
+  initialOption?: SearchOption;
+  className?: string;
+  inputClassName?: string;
+  buttonClassName?: string;
+}
+
+export type eventType = {
```
Comment (rithviknishad) [inline src/components/Common/SearchByMultipleFields.tsx]: https://docs.aws.amazon.com/prescriptive-guidance/latest/best-practices-cdk-typescript-iac/typescript-best-practices.html#naming-conventions

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 24]
```diff
@@ -17,157 +16,148 @@ import {
...
+      },
+      [field, validate, error],
+    );
+    useEffect(() => {
+      if (field.value) {
+        if (field.value.length > 3) {
+          if (props.myfunc) {
+            props.myfunc(error);
+          }
+        }
```
Comment (rithviknishad) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx]: 1. why check for length > 3? what does 3 stand for?
2. what is `myfunc`? use readable names for callbacks.
3. why use multiple if blocks when it can be combined with `&&`?

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 25]
```diff
@@ -17,157 +16,148 @@ import {
...
+        if (field.value === "+") {
+          setCountry({ flag: "🌍", name: "Other", code: "+" });
+          return;
+        }
+        setCountry(phoneCodes[getCountryCode(field.value)!]);
+      }
+    }, [setValue]);
 
-const PhoneNumberTypesHelp = (props: { types: PhoneNumberType[] }) => {
```
Comment (rithviknishad) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx:162]: Why was `PhoneNumberTypesHelp` component removed? It is needed in other places?

When making a change to a reusable component like this, make sure it does not affect existing usages in other places.

File: src/components/Patient/ManagePatients.tsx [hunk 26]
```diff
@@ -776,17 +739,57 @@ export const PatientManager = () => {
...
+      shortcut_key: "u",
+    },
+    {
+      key: "emergency_contact_phone_number",
+      label: "Emergency Contact Phone Number",
+      type: "phone" as const,
+      placeholder: "Search by emergency contact phone number",
+      value: qParams.emergency_contact_phone_number || "",
+      shortcut_key: "e",
+    },
```
Comment (rithviknishad) [inline src/components/Patient/ManagePatients.tsx]: missing i18n translations for readable texts

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 24 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: @rithviknishad ,+91 in current state length is 3 ,

Comment (rithviknishad) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: so what about other country codes such as `+971`?

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 25 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx:162]: > Why was `PhoneNumberTypesHelp` component removed? It is needed in other places?
> 
> When making a change to a reusable component like this, make sure it does not affect existing usages in other places.

@rithviknishad ,it is not used in that file may be used any where else but if I add this it will throw eslint error.And if it is used anywhere else, I found an error, but I received no errors

Comment (rithviknishad) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx:162]: it is used; u just removed the usage too...

image

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 24 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: > so what about other country codes such as `+971`?

it is working as before ,sorry for that I built a wrong logic  now it is okay

useEffect(() => {
      if (props.myfunc) {
        props.myfunc(error);
      }
    }, [error]);

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 25 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx:162]: > it is used; u just removed the usage too...
> 
> image

@rithviknishad I have not done this after merging bodhis's branch it happened ,and after adding this I found a bad breaking ui 
Screenshot 2024-10-30 235503

File: src/components/Patient/ManagePatients.tsx (hunk 26 above)
Comment (i0am0arunava) [reply src/components/Patient/ManagePatients.tsx]: @rithviknishad , done this

**Comment by i0am0arunava** [comment]
@rithviknishad ,all the requested changes fixed ,type defined ,i18n defined

File: src/Locale/hi.json
Comment (rithviknishad) [inline src/Locale/hi.json:1]: translations only for `en` is to be added as mentioned in README https://github.com/ohcnetwork/care_fe#translations. discard changes for all other languages.

File: src/components/Patient/ManagePatients.tsx [hunk 27]
```diff
@@ -776,17 +739,57 @@ export const PatientManager = () => {
...
+    {
+      key: "emergency_contact_phone_number",
+      label: "Emergency Contact Phone Number",
+      type: "phone" as const,
+      placeholder: "Search_by_emergency_contact_phone_number",
+      value: qParams.emergency_contact_phone_number || "",
+      shortcutKey: "e",
+    },
+  ];
```
Comment (rithviknishad) [inline src/components/Patient/ManagePatients.tsx]: wrap i18n keys with `t`

File: src/components/Patient/ManagePatients.tsx [hunk 28]
```diff
@@ -973,7 +976,7 @@ export const PatientManager = () => {
         <div className="mt-2 flex h-full flex-col gap-3 xl:flex-row">
           <div className="flex-1" id="total-patientcount">
             <CountBlock
-              text="Total Patients"
+              text="Total_Patients"
```
Comment (rithviknishad) [inline src/components/Patient/ManagePatients.tsx]: wrap with `t` in the place where the key is being specified

```suggestion
              text={t("total_patients")}
```

File: src/CAREUI/display/Count.tsx [hunk 29]
```diff
@@ -18,7 +19,7 @@ export default function CountBlock(props: Props) {
         </div>
         <div>
           <dt className="mb-1 truncate text-sm font-semibold text-secondary-700">
-            {props.text}
+            {t(props.text)}
```
Comment (rithviknishad) [inline src/CAREUI/display/Count.tsx]: wrap with `t` where the key is being used; not a variable.

```suggestion
            {props.text}
```

File: src/Locale/en.json [hunk 30]
```diff
@@ -199,8 +199,13 @@
   "SORT_OPTIONS__name": "Patient name A-Z",
   "SORT_OPTIONS__review_time": "Oldest review date first",
   "SORT_OPTIONS__taken_at": "Oldest taken date first",
+  "Search_by_UHID": "Search by UHID",
+  "Search_by_emergency_contact_phone_number": "Search by Emergency Contact Phone Number",
+  "Search_by_patient_name": "Search by Patient Name",
+  "Search_by_phone_number": "Search by Phone Number",
   "Submit": "Submit",
   "TELEMEDICINE": "Telemedicine",
+  "Total_Patients": "Total Patients",
```
Comment (rithviknishad) [inline src/Locale/en.json]:
```suggestion
  "total_patients": "Total Patients",
```

File: src/Locale/en.json [hunk 31]
```diff
@@ -199,8 +199,13 @@
   "SORT_OPTIONS__name": "Patient name A-Z",
   "SORT_OPTIONS__review_time": "Oldest review date first",
   "SORT_OPTIONS__taken_at": "Oldest taken date first",
+  "Search_by_UHID": "Search by UHID",
+  "Search_by_emergency_contact_phone_number": "Search by Emergency Contact Phone Number",
+  "Search_by_patient_name": "Search by Patient Name",
```
Comment (rithviknishad) [inline src/Locale/en.json]: use consistent casing. 
```suggestion
  "search_by_patient_name": "Search by Patient Name",
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 25 above)
Comment (rithviknishad) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx:162]: we could conditionally hide it only for the search thing;

File: src/components/Patient/ManagePatients.tsx (hunk 27 above)
Comment (bodhish) [reply src/components/Patient/ManagePatients.tsx]: Also use smallcase for the I18N keys

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 25 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx:155]: @rithviknishad yeh I saw in the console it is coming only for phnuberinput and emergencyphnuminput I can use condition for this two only

Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx:162]: @rithviknishad ,yah only for the searchbymultifield compnent which is newly build,I am passing a props help={fasle} and for this compnent 
heplcomponenet means this " ? " will  be hidden and for other compnent it will be true .for this I used useffect and usestate inside formfield to check . Also declared the type help?boolean ,and it is working properly

File: src/components/Form/FormFields/FormField.tsx [hunk 32]
```diff
@@ -54,6 +55,16 @@ const FormField = ({
   field?: FormFieldBaseProps<any>;
   children: React.ReactNode;
 }) => {
+  const [phhelp, setPhhelp] = useState(false);
```
Comment (i0am0arunava) [inline src/components/Form/FormFields/FormField.tsx:58]: using this effect I am just checking which compnent I am using if it is coming from searchBymultified then help is false  and no need to show it ,excepting only this serchbymultifield other serch field will show this help section as previous
Screenshot 2024-10-31 034754
Screenshot 2024-10-31 034828

File: src/components/Form/FormFields/FormField.tsx [hunk 33]
```diff
@@ -54,6 +55,16 @@ const FormField = ({
...
+
+  useEffect(() => {
+    if ((field && field?.help == undefined) || (field && !("help" in field))) {
+      setPhhelp(true);
+    } else if (field?.help == false) {
+      setPhhelp(false);
+    }
+  }, []);
```
Comment (i0am0arunava) [inline src/components/Form/FormFields/FormField.tsx]: @rithviknishad  ,using this effect I am just checking which compnent I am using if it is coming from searchBymultified then help is false  and no need to show it ,excepting only this serchbymultifield other serch field will show this help section as previous, it is  working properly everywhere excepting the serchbymultifield as expected
Screenshot 2024-10-31 034754


Screenshot 2024-10-31 034828

Comment (i0am0arunava) [reply src/components/Form/FormFields/FormField.tsx]: @rithviknishad ,is it ready for merge ?

File: src/Locale/hi.json
Comment (i0am0arunava) [reply src/Locale/hi.json:1]: done

File: src/components/Form/FormFields/FormField.tsx [hunk 34]
```diff
@@ -54,6 +55,16 @@ const FormField = ({
...
+
```
Comment (rithviknishad) [inline src/components/Form/FormFields/FormField.tsx]: I don't see a reason why we need a useState and a useEffect to show help in sufix. Can't we keep it how it was before? And pass a prop to the `PhoneNumberFormField` directly instead?

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Also previous requested changes are incomplete.

File: src/components/Form/FormFields/FormField.tsx (hunk 34 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/FormField.tsx]: @rithviknishad ,no it will not work please try to understand,passing prop from phnumberfield will not show help icon fir other components ,for serchfield it will be false

**Comment by i0am0arunava** [comment]
> Also previous requested changes are incomplete.

@rithviknishad  , sir I have fixed all the changes you have mentioned , I am unable to understand what do I need to do next.

I am feeling very confused.

File: src/components/Form/FormFields/FormField.tsx (hunk 34 above)
Comment (bodhish) [reply src/components/Form/FormFields/FormField.tsx]: @i0am0arunava have you read about initalstate prop for a state? 

https://react.dev/reference/react/useState#parameters

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 35]
```diff
@@ -17,141 +17,151 @@ import {
...
+        field={{
+          ...field,
 
+          error: field.error || error,
+          labelSuffix:
+            field.labelSuffix ||
+            (props.help == undefined && (
+              <PhoneNumberTypesHelp types={props.types} />
+            )),
+        }}
```
Comment (i0am0arunava) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx:120]: @bodhish @rithviknishad ,is this changes okay ? I have removed unnecessary use of useeffect and usestate
and implement it https://github.com/ohcnetwork/care_fe/pull/8834#discussion_r1824032827 simply.

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 20 above)
Comment (rithviknishad) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: This is still unresolved...

File: src/Locale/en.json (hunk 31 above)
Comment (rithviknishad) [reply src/Locale/en.json]: still unresolved...

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 20 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: @rithviknishad ,I am doing this can ,you please check this https://rebuildearth.slack.com/archives/C010GQBMFJ9/p1730401644718869?thread_ts=1729245389.346939&cid=C010GQBMFJ9
And this

Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: > you don't need to modify PhoneNumberFormField for that. Just check the value in the search by field component and show error from there.

@rithviknishad ,inside the searchbyfield how I will add onblur if I put it inside phnubercomponent it will not work 

Screenshot 2024-11-01 141155

File: src/Locale/en.json (hunk 31 above)
Comment (i0am0arunava) [reply src/Locale/en.json]: > still unresolved...

@rithviknishad ,solved

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 20 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: > This is still unresolved...

@rithviknishad done

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 36]
```diff
@@ -17,141 +17,151 @@ import {
 } from "../FieldValidators";
 import CareIcon from "../../../CAREUI/icons/CareIcon";
 import { Popover, PopoverButton, PopoverPanel } from "@headlessui/react";
+import React from "react";
 import { useTranslation } from "react-i18next";
 
 const phoneCodes: Record<string, CountryData> = phoneCodesJson;
 
 interface Props extends FormFieldBaseProps<string> {
+  phoneFieldError?: (er: FieldError) => void;
```
Comment (rithviknishad) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx]:
```suggestion
  onError?: (error: FieldError) => void;
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Form/FormFields/Utils.ts [hunk 37]
```diff
@@ -32,6 +32,7 @@ export type FormFieldBaseProps<T> = {
   error?: FieldError;
   onFocus?: (event: FocusEvent<HTMLInputElement>) => void;
   onBlur?: (event: FocusEvent<HTMLInputElement>) => void;
+  help?: boolean;
```
Comment (rithviknishad) [inline src/components/Form/FormFields/Utils.ts]: forgot to remove this?

```suggestion
```

File: src/common/hooks/useFilters.tsx [hunk 38]
```diff
@@ -61,6 +61,11 @@ export default function useFilters({
     filter = hasPagination ? { page: 1, limit, ...filter } : filter;
     setQueryParams(Object.assign({}, qParams, filter), { replace: true });
   };
+  const updateSerchByField = (filter: FilterState) => {
+    filter = hasPagination ? { page: 1, limit, ...filter } : filter;
+    console.log(filter);
+    setQueryParams(Object.assign({}, filter), { replace: true });
+  };
```
Comment (i0am0arunava) [inline src/common/hooks/useFilters.tsx]: @ritviknishad , at a one time only one filter will be applied based one the chosen one from searchbymultifield component

Comment (rithviknishad) [inline src/common/hooks/useFilters.tsx]: i don't see a reason why `updateQuery` and `removeFilters` is not sufficient. Why duplicate the same implementation with another name?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/common/hooks/useFilters.tsx (hunk 38 above)
Comment (i0am0arunava) [reply src/common/hooks/useFilters.tsx]: @bodhish @rithviknishad ,No  that is not same implementaion
Object.assign({}, filter)
this is updating based on applied one filter at a time 
But inside update query 
Object.assign({}, qParams, filter)
It is taking all with previous

File: src/components/Form/FormFields/Utils.ts (hunk 37 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/Utils.ts]: > forgot to remove this?

@rithviknishad I am passing It with a false value from phnunberfield inside serchbymultifield compo

File: src/components/Patient/ManagePatients.tsx (hunk 27 above)
Comment (i0am0arunava) [reply src/components/Patient/ManagePatients.tsx]: > wrap i18n keys with `t`
@bodhish @rithviknishad ,if I wrap up this key like this----> key: t("phone_number")    the key will be converted to "Phone Number" and it will create issue in filtering and other issue also ,because in case of filtering phone_number is used  for checking.  so I am using translation at the part where it is used

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 36 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: > 

@rithviknishad ,commited this

File: src/Locale/mr.json [hunk 39]
```diff
@@ -63,4 +63,4 @@
   "sign_out": "साइन आउट",
   "something_wrong": "काहीतरी चूक झाली! पुन्हा प्रयत्न करा",
   "username": "युजरनेम"
-}
+}
```
Comment (bodhish) [inline src/Locale/mr.json]: A change in file that is unrelated to the PR

File: .env [hunk 40]
```diff
@@ -14,4 +14,4 @@ ESLINT_NO_DEV_ERRORS=true
 CARE_CDN_URL="https://egov-s3-facility-10bedicu.s3.amazonaws.com https://egov-s3-patient-data-10bedicu.s3.amazonaws.com http://localhost:4566"
 REACT_ALLOWED_LOCALES="en,hi,ta,ml,mr,kn"
 
-REACT_ENABLED_APPS="ohcnetwork/care_livekit_fe@main"
+REACT_ENABLED_APPS="ohcnetwork/care_livekit_fe@main"
```
Comment (bodhish) [inline .env]: A change in file that is unrelated to the PR

File: src/common/hooks/useFilters.tsx [hunk 41]
```diff
@@ -61,6 +61,11 @@ export default function useFilters({
     filter = hasPagination ? { page: 1, limit, ...filter } : filter;
     setQueryParams(Object.assign({}, qParams, filter), { replace: true });
   };
+  const updateSerchByField = (filter: FilterState) => {
+    filter = hasPagination ? { page: 1, limit, ...filter } : filter;
+    console.log(filter);
```
Comment (bodhish) [inline src/common/hooks/useFilters.tsx]: Logs in code! 
Lets not have log statements pushed

File: src/components/Common/SearchByMultipleFields.tsx [hunk 42]
```diff
@@ -0,0 +1,261 @@
...
+interface SearchByMultipleFieldsProps {
+  options: SearchOption[];
+  onSearch: (key: string, value: string) => void;
+  initialOption?: SearchOption;
+  className?: string;
+  inputClassName?: string;
+  buttonClassName?: string;
+}
+
+export type EventType = {
```
Comment (bodhish) [inline src/components/Common/SearchByMultipleFields.tsx]: This is a react event right, it should have its type already defined right 🤔

File: src/components/Common/SearchByMultipleFields.tsx [hunk 43]
```diff
@@ -0,0 +1,261 @@
...
+                </CommandGroup>
+              </CommandList>
+            </Command>
+          </PopoverContent>
+        </Popover>
+        {renderSearchInput}
+      </div>
+      {error && (
+        <div className="error-text ml-3 bg-white text-xs font-medium tracking-wide text-danger-500 transition-opacity duration-300">
+          Invalid phone number
```
Comment (bodhish) [inline src/components/Common/SearchByMultipleFields.tsx]: String that is not part of I18n

File: src/components/Common/SearchByMultipleFields.tsx [hunk 44]
```diff
@@ -0,0 +1,261 @@
...
+          </PopoverTrigger>
+          <PopoverContent className="w-[200px] p-0">
+            <Command>
+              <CommandList>
+                <CommandGroup>
+                  {options.map((option, index) => (
+                    <CommandItem
+                      key={option.key}
+                      onSelect={() => handleOptionChange(option)}
+                      className={`${
```
Comment (bodhish) [inline src/components/Common/SearchByMultipleFields.tsx]: Why not use cn function here?

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 45]
```diff
@@ -273,3 +282,4 @@ const CountryCodesList = ({
     </div>
   );
 };
+export default PhoneNumberFormField;
```
Comment (bodhish) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx:291]: Just export the default in the function itself

File: src/components/Form/FormFields/Utils.ts (hunk 37 above)
Comment (bodhish) [inline src/components/Form/FormFields/Utils.ts]: What does help mean? Did you mean showHelp? 

Let's make sure variable naming is always good.

**Review by bodhish — CHANGES_REQUESTED** [review]
Note to reviewers: This is a partial review I have not read the code fully

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 45 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx:291]: @bodhish ,I did this ,actually it is showing error and I am using forwardref that's why I can not write it in same line.It was showing kind of syntax error

File: src/components/Form/FormFields/Utils.ts (hunk 37 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/Utils.ts]: Yeh phnumber help

File: src/common/hooks/useFilters.tsx (hunk 38 above)
Comment (bodhish) [reply src/common/hooks/useFilters.tsx]: @i0am0arunava when you are resolving something without addressing add the reason and let the author resolve it

File: src/components/Common/SearchByMultipleFields.tsx (hunk 42 above)
Comment (i0am0arunava) [reply src/components/Common/SearchByMultipleFields.tsx]: @ bodhi using inbuilt react event type was showing some error

**Comment by i0am0arunava** [comment]
@rithviknishad  @bodhish @nihal467 , I don't know why the cypress test case (3) facilitylocation.ts, is failing in your github ci/cd ,
in my system it is running properly without throwing any error ,I am requesting you to re-run the test cases here is scrrenshot

Screenshot 2024-10-29 123643

Screenshot 2024-11-03 104354

File: src/components/Form/FormFields/Utils.ts (hunk 37 above)
Comment (i0am0arunava) [reply src/components/Form/FormFields/Utils.ts]: Done

File: src/components/Common/SearchByMultipleFields.tsx (hunk 43 above)
Comment (i0am0arunava) [reply src/components/Common/SearchByMultipleFields.tsx]: Done

File: src/components/Common/SearchByMultipleFields.tsx (hunk 44 above)
Comment (i0am0arunava) [reply src/components/Common/SearchByMultipleFields.tsx]: Done

**Review by i0am0arunava — COMMENTED** [review]
@rithviknishad @bodhish , please review my comment

File: src/components/Common/SearchByMultipleFields.tsx (hunk 42 above)
Comment (rithviknishad) [reply src/components/Common/SearchByMultipleFields.tsx]: 1. this is used only in this file; let's not export it.
2. type of target could be defined from one of the inbuilt types.

File: src/components/Form/FormFields/Utils.ts (hunk 37 above)
Comment (rithviknishad) [reply src/components/Form/FormFields/Utils.ts]: Not done 🙄

File: src/common/hooks/useFilters.tsx [hunk 46]
```diff
@@ -61,6 +61,10 @@ export default function useFilters({
     filter = hasPagination ? { page: 1, limit, ...filter } : filter;
     setQueryParams(Object.assign({}, qParams, filter), { replace: true });
   };
+  const updateSerchByField = (filter: FilterState) => {
+    filter = hasPagination ? { page: 1, limit, ...filter } : filter;
+    setQueryParams(Object.assign({}, filter), { replace: true });
+  };
```
Comment (rithviknishad) [inline src/common/hooks/useFilters.tsx]: It is doable without needing to make this change.

Also this causes issue when used along with advanced filters. The applied advanced filters gets unapplied when we switch the search criteria (phone number to name for example).

Use `removeFilters` in conjunction with `updateQuery` instead of implementing this.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/common/hooks/useFilters.tsx (hunk 46 above)
Comment (i0am0arunava) [reply src/common/hooks/useFilters.tsx]: @rithviknishad ,got it ,will fix the issue

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 47]
```diff
@@ -17,141 +17,151 @@ import {
...
-}
+    return (
+      <FormField
+        field={{
+          ...field,
 
+          error: field.error || error,
+          labelSuffix:
+            field.labelSuffix ||
+            (props.phoneNumberHelp == undefined && (
```
Comment (rithviknishad) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx]: shouldn't this be the opposite based on how it's read?

also keep the name `showHelp`. It's pretty obvious it's phone number help in this context as the prop is part of the phone number component.

```suggestion
            (props.showHelp && (
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Form/FormFields/Utils.ts (hunk 37 above)
Comment (rithviknishad) [reply src/components/Form/FormFields/Utils.ts]: but you can pass it directly to the PhoneNumberFormField instead right?

Comment (i0am0arunava) [reply src/components/Form/FormFields/Utils.ts]: > but you can pass it directly to the PhoneNumberFormField instead right?

yes I am doing

File: src/components/Patient/ManagePatients.tsx [hunk 48]
```diff
@@ -776,17 +739,68 @@ export const PatientManager = () => {
...
+              ? value
+              : undefined
+            : undefined,
+      };
+
+      updateQuery(updatedQuery);
+    },
+    [updateQuery],
+  );
+
```
Comment (i0am0arunava) [inline src/components/Patient/ManagePatients.tsx:809]: @rithviknishad ,Now it is working properly. I have used the ternary operator. When the key value matches the chosen one from the SearchByMultiFieldComponent, it will update the value, and the remaining three fields of the SearchByMultiFieldComponent will be set to undefined. Adding an additional Advanced filter now causes no problems.

**Review by i0am0arunava — COMMENTED** [review]
@rithviknishad I have made the changes, and now applying the filter is no longer causing problems.

File: src/common/hooks/useFilters.tsx (hunk 46 above)
Comment (i0am0arunava) [reply src/common/hooks/useFilters.tsx]: done

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 49]
```diff
@@ -17,141 +17,150 @@ import {
...
+    return (
+      <FormField
+        field={{
+          ...field,
+          error: field.error || error,
+          labelSuffix:
+            field.labelSuffix ||
+            (props.showHelp == false ? null : (
+              <PhoneNumberTypesHelp types={props.types} />
+            )),
```
Comment (rithviknishad) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx]: `undefined == false` evaluates to `false` indicating both are not same. prefer treating undefined as "falsey" to avoid surprises when later on building some other logic based on this prop.

Tip: `hideHelp` would be more preferable and cleaner.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 50]
```diff
@@ -17,141 +17,150 @@ import {
...
+    }, [setValue]);
 
+    return (
+      <FormField
+        field={{
+          ...field,
+          error: field.error || error,
+          labelSuffix:
+            field.labelSuffix ||
+            (props.hideHelp == false ? null : (
```
Comment (i0am0arunava) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx]: @rithviknishad  If I consider undefined as false, I need to set hideHelp to true for other components. It is quite complex to set hidehelp=true for other   component  where this phonenumberfield component is used.

**Review by i0am0arunava — COMMENTED** [review]
defining in each phonenuberfield componenet hidehelp ==true is quiet complex

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 50 above)
Comment (rithviknishad) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx]: we only need to hide help in search by multiple field component and not anywhere else right? So `hideHelp` needs to be set only in one place right?

File: src/components/Form/FormFields/PhoneNumberFormField.tsx [hunk 51]
```diff
@@ -17,141 +17,150 @@ import {
...
+    }, [setValue]);
 
+    return (
+      <FormField
+        field={{
+          ...field,
+          error: field.error || error,
+          labelSuffix:
+            field.labelSuffix ||
+            (props.hideHelp ? null : (
```
Comment (i0am0arunava) [inline src/components/Form/FormFields/PhoneNumberFormField.tsx:117]: @rithviknishad ,is it okay now, I am passing hidehelp=true as a prop  inside phnumbercoponenet from serchbyfield

**Review by i0am0arunava — COMMENTED** [review]
@rithviknishad ,is this changes okay?

**Review by rithviknishad — APPROVED** [review]
lgtm; do try to resolve pending review requested changes by @bodhish

File: src/components/Common/SearchByMultipleFields.tsx (hunk 42 above)
Comment (bodhish) [reply src/components/Common/SearchByMultipleFields.tsx]: Instead of using a custom EventType, we can easily use the `FieldChangeEvent` 
 from `@/components/Form/FormFields/Utils`

```ts
// For regular inputs
const commonInputProps = {
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => {
    handleSearchChange(e.target.value);
  },
  // ... other props
};

// For phone input
const phoneInputProps = {
  ...commonInputProps,
  onChange: (event: FieldChangeEvent<string>) => {
    handleSearchChange(event.value);
  },
};
```
This approach:
- This adds `phoneInputProps` which will solve the type error. 
- Removes the need for the custom EventType
- Properly types both regular input and phone input events
- Better follows React's event handling patterns

File: src/components/Common/SearchByMultipleFields.tsx [hunk 52]
```diff
@@ -0,0 +1,259 @@
...
+            </Command>
+          </PopoverContent>
+        </Popover>
+        {renderSearchInput}
+      </div>
+      {error && (
+        <div className="error-text ml-3 bg-white text-xs font-medium tracking-wide text-danger-500 transition-opacity duration-300">
+          {t("invalid_phone_number")}
+        </div>
+      )}
```
Comment (bodhish) [inline src/components/Common/SearchByMultipleFields.tsx]: The error state assumes that it will always be an error in the phone number field, every other field can also have a validation error.

File: src/components/Common/SearchByMultipleFields.tsx [hunk 53]
```diff
@@ -0,0 +1,259 @@
...
+        ) {
+          e.preventDefault();
+          handleOptionChange(option);
+        }
+      });
+    };
+
+    document.addEventListener("keydown", handleKeyDown);
+    return () => document.removeEventListener("keydown", handleKeyDown);
+  }, [focusedIndex, open]);
```
Comment (bodhish) [inline src/components/Common/SearchByMultipleFields.tsx]: Add all dependencies for the react hook
```suggestion
}, [focusedIndex, open, handleOptionChange, options]);
```

File: src/components/Common/SearchByMultipleFields.tsx [hunk 54]
```diff
@@ -0,0 +1,259 @@
...
+      if (e.key === "Escape") {
+        setSearchValue("");
+        onSearch(selectedOption.key, "");
+      }
+      if (e.key === "/") {
+        e.preventDefault();
+        setOpen(true);
+      }
+    },
+    [selectedOption, onSearch],
```
Comment (bodhish) [inline src/components/Common/SearchByMultipleFields.tsx:168]: `handleKeyDown` is recreated on every render due to missing dependencies. 

Please fix this issue for all hooks in this file.

File: src/components/Common/SearchByMultipleFields.tsx [hunk 55]
```diff
@@ -0,0 +1,259 @@
...
+    searchValue,
+    handleSearchChange,
+    handleKeyDown,
+    t,
+    inputClassName,
+  ]);
+
+  return (
+    <div className={className}>
+      <div className="flex items-center rounded-t-lg border-x border-t border-gray-200 bg-white">
```
Comment (bodhish) [inline src/components/Common/SearchByMultipleFields.tsx]:
```suggestion
      <div className="flex items-center rounded-t-lg border-x border-t border-gray-200 bg-white"
      role="searchbox"
      aria-expanded={open}
      aria-controls="search-options"
      aria-haspopup="listbox"
      >
```

File: src/components/Common/SearchByMultipleFields.tsx [hunk 56]
```diff
@@ -0,0 +1,259 @@
...
+          </PopoverContent>
+        </Popover>
+        {renderSearchInput}
+      </div>
+      {error && (
+        <div className="error-text ml-3 bg-white text-xs font-medium tracking-wide text-danger-500 transition-opacity duration-300">
+          {t("invalid_phone_number")}
+        </div>
+      )}
+      <div className="flex flex-wrap gap-2 rounded-b-lg border-x border-b border-gray-200 bg-gray-50 p-2 shadow">
```
Comment (bodhish) [inline src/components/Common/SearchByMultipleFields.tsx]:
```suggestion
      <div className="flex flex-wrap gap-2 rounded-b-lg border-x border-b border-gray-200 bg-gray-50 p-2 shadow"
      role="searchbox"
      aria-expanded={open}
      aria-controls="search-options"
      aria-haspopup="listbox"
      >
```

File: src/components/Form/FormFields/PhoneNumberFormField.tsx (hunk 51 above)
Comment (bodhish) [reply src/components/Form/FormFields/PhoneNumberFormField.tsx:117]:
```
(!props.hideHelp && <PhoneNumberTypesHelp types={props.types} />),
```

Also I would have actually called it `showHelp` with a default set in the component as `true`.

**Review by bodhish — CHANGES_REQUESTED** [review]
- [ ] When I key in the 1st number in the phone number filed, it fires a request, not an expected behaviour. 
image

- [ ] The casing for Phone number and emergency contact phone number looks messed up, follow one casing. 
image

- [ ] Initial state for the component is not implemented. 
image
- 1st mentioned in https://github.com/ohcnetwork/care_fe/pull/8834#discussion_r1807979306
- 2nd reminded on https://github.com/ohcnetwork/care_fe/pull/8834#pullrequestreview-2397423503
Please don't ignore review comments.

**Comment by nihal467** [comment]
**Functionality Bug**

image

- [ ] The platform currently filters results with every user input, which feels unusual; it would be more effective if it used debouncing to improve performance.

**Minor Bug**

image

- [ ] the " l-search-alt " icon which was present inside all search box in the platform is missing, revert that unwanted change

image

- [ ] the badges are overlapping with the search input component in mobile view

image

- [ ] keep the button which highlight the support of esc button to erase input as per our current UI

image

- [ ] when we removed the badge of applied filters, it should clear the input field as well 
- [ ] rename the emergency contact phone number to "Emergency Number"

**Enhancement For next version**

image

- [ ] The error message shown for an invalid number seems a bit odd. Think of a better way to display the error message for this search.

image

- [ ] Preserve the input when the user changes the filter option. For example, if "nihal" was entered after selecting "Name," retain this input when the user switches the filter to "UHID."

**Question**

image

- [ ] Either change IP/OP number badge to UHID or the vice-versa after taking a confirmation from @bodhish / @gigincg to avoid inconsistency

**Comment by bodhish** [comment]
Change to Ip number for now

**Comment by nihal467** [comment]
@i0am0arunava what is the status on this PR

**Comment by i0am0arunava** [comment]
> @i0am0arunava what is the status on this PR

@nihal467 , working,fixed the merge conflict,making the required changes

File: package.json [hunk 57]
```diff
@@ -172,5 +177,5 @@
   "engines": {
     "node": ">=22.11.0"
   },
-  "packageManager": "npm@10.9.0"
+  "packageManager": "npm@10.5.0"
```
Comment (sainak) [inline package.json]: revert this line

File: src/hooks/useFullscreen.ts
Comment (sainak) [inline src/hooks/useFullscreen.ts:1]: discard changes to this file

File: public/locale/mr.json
Comment (sainak) [inline public/locale/mr.json:1]: discard changes to this file

File: public/locale/en.json [hunk 58]
```diff
@@ -619,7 +619,7 @@
   "email_discharge_summary_description": "Enter your valid email address to receive the discharge summary",
   "email_success": "We will be sending an email shortly. Please check your inbox.",
   "emergency": "Emergency",
-  "emergency_contact_number": "Emergency Contact Number",
+  "emergency_phone_number": "emergency contact phone number",
```
Comment (sainak) [inline public/locale/en.json]: prefer sentence/title case for values

File: src/components/Patient/ManagePatients.tsx [hunk 59]
```diff
@@ -317,16 +292,10 @@ export const PatientManager = () => {
     return cleanedData;
   };
 
+  const [debouncedParams] = useDebounce(params, 1000); // Debounce time in milliseconds
```
Comment (i0am0arunava) [inline src/components/Patient/ManagePatients.tsx]: I found implementing import { debounce } from "lodash-es"; to be very complex and it wasn't working properly. After that, I switched to using import { useDebounce } from "use-debounce";, which worked properly.

**Review by i0am0arunava — COMMENTED** [review]
implemented debouncing,  I found implementing import { debounce } from "lodash-es"; to be very complex and it wasn't working properly. After that, I switched to using import { useDebounce } from "use-debounce";, which worked properly.

File: src/components/Patient/ManagePatients.tsx (hunk 59 above)
Comment (shivankacker) [reply src/components/Patient/ManagePatients.tsx]: If you verified it to be working as needed, it is fine.

File: src/hooks/useDebounce.ts [hunk 60]
```diff
@@ -0,0 +1,50 @@
...
+
+/**
+ * Custom hook to debounce a value.
+ *
+ * @param {any} value - The value to debounce.
+ * @param {number} delay - The debounce delay in milliseconds.
+ * @returns {any} - The debounced value.
+ */
+const useDebounce = (value: string, delay: number) => {
+  function compareObjects(obj1: string, obj2: string) {
```
Comment (i0am0arunava) [inline src/hooks/useDebounce.ts]: I observed that two parameters coming in differently but looking the same were being treated as different values. This was causing unnecessary API calls. Upon examining the previous parameter value and the current incoming parameter value, I found they were different. This issue was occurring not only when typing inside the phone number field but also when changing the option, causing unnecessary API calls.

```
{page: 1, limit: 12, name: undefined, patient_no: undefined, is_active: 'True', …}
{page: '1', limit: 12, name: undefined, patient_no: undefined, is_active: 'True', …}
```

If you observe the page key value, the previous one is a number, and the current one is a string. This was the problem. I solved it by comparing two objects while ignoring their value types, which now prevents unnecessary API calls

**Review by i0am0arunava — COMMENTED** [review]
Is it okay now ?

**Comment by nihal467** [comment]
@shivankacker can you review this PR

**Comment by i0am0arunava** [comment]
> @shivankacker can you review this PR

[@Nihal](https://rebuildearth.slack.com/team/U022THM4U2U)
 
[@Shivank Kacker](https://rebuildearth.slack.com/team/U02TB83Q5V0)
, I want to inform that some changes I have not done yet in my pr, I want some clarification,I will discuss about that in today's meeting

**Comment by nihal467** [comment]
@shivankacker can you clear the merge conflict

**Comment by nihal467** [comment]
@shivankacker  can you check the cypress failure

**Comment by nihal467** [comment]
image

- [ ] Whenever we enter a phone number, the pagination component keeps blinking with each input. Can you investigate the root cause?

Similar issue is visible for other search as well

**Comment by shivankacker** [comment]
Weird, can't replicate.

https://github.com/user-attachments/assets/26cc3071-10af-4fb6-90a8-536ddb0af6e6

Probably causing a re-render, will investigate

**Comment by nihal467** [comment]
@shivankacker is it ready for review

**Comment by shivankacker** [comment]
@nihal467 ready for review

**Comment by nihal467** [comment]
@shivankacker can you clear the merge conflict

**Comment by nihal467** [comment]
LGTM @khavinshankar @rithviknishad lets get it reviewed ASAP

**Review by rithviknishad — APPROVED** [review]
