### PR TITLE
Treatment and Discharge Summary for Completed Encounters

### LINKED ISSUE #11139: Hide action heading in encounter once its marked completed
**Describe the bug**

When an encounter is marked as completed, all actions are now hidden. Therefore, the heading should also be hidden, as it is no longer relevant.

**To Reproduce**

1. Mark a live encounter complete
2. See error

**Expected behavior**

[rebuildearth.slack.com/archives/C010GQBMFJ9/p1741385328945659](https://rebuildearth.slack.com/archives/C010GQBMFJ9/p1741385328945659)

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- **Mark as complete** action should only be available for not completed ones 
- Treatment and Discharge Summary for Completed Encounters
- Fixes: #11139 

@ohcnetwork/care-fe-code-reviewers
Screenshot 2025-03-08 at 4 01 25 PM

**Slack Thread**
https://rebuildearth.slack.com/archives/C010GQBMFJ9/p1741385328945659
## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Refactor**
	- Streamlined the class name assignment for alert dialog actions, simplifying the code.
	- Updated the consultation dropdown button label to display context-sensitive options ("actions" or "update") based on the encounter status, enhancing user interface relevance.

### CODE REVIEW

File: src/components/Encounter/EncounterActions.tsx [hunk 1]
```diff
@@ -155,41 +157,43 @@ export default function EncounterActions({
...
+
+              <PLUGIN_Component
+                __name="PatientInfoCardMarkAsComplete"
+                encounter={encounter}
+              />
+
+              <AlertDialogFooter>
+                <AlertDialogCancel>{t("cancel")}</AlertDialogCancel>
+                <AlertDialogAction
+                  className={cn(buttonVariants({ variant: "primary" }))}
```
Comment (abhimanyurajeesh) [inline src/components/Encounter/EncounterActions.tsx]: isn't this sufficient? 🤔 

```suggestion
                  className={buttonVariants({ variant: "primary" })}
```

Comment (AdityaJ2305) [reply src/components/Encounter/EncounterActions.tsx]: It is everywhere like this 😅 but yeah removed it ✅ 
Great, for noticing

File: src/components/Patient/PatientInfoCard.tsx [hunk 2]
```diff
@@ -425,30 +425,29 @@ export default function PatientInfoCard(props: PatientInfoCardProps) {
...
+            >
+              <DropdownMenu>
+                <DropdownMenuTrigger asChild>
+                  <Button variant="primary">
+                    {t("update")}
+                    <ChevronDown className="ml-2 h-4 w-4" />
+                  </Button>
+                </DropdownMenuTrigger>
+                <DropdownMenuContent align="end">
+                  <DropdownMenuLabel>{t("actions")}</DropdownMenuLabel>
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientInfoCard.tsx]: Let's remove menu label

File: src/components/Patient/PatientInfoCard.tsx [hunk 3]
```diff
@@ -425,30 +425,29 @@ export default function PatientInfoCard(props: PatientInfoCardProps) {
...
-            )}
+          {!disableButtons && (
+            <div
+              className="flex w-full flex-col gap-3 lg:w-auto 2xl:flex-row"
+              data-cy="update-encounter-button"
+            >
+              <DropdownMenu>
+                <DropdownMenuTrigger asChild>
+                  <Button variant="primary">
+                    {t("update")}
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientInfoCard.tsx]: for completed statuses, change this to actions.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM, dont mind the cypress failure, its non related

**Review by khavinshankar — APPROVED** [review]
