### PR TITLE
Fix: ValueSetSelect not getting focus and scroll on form errors

### LINKED ISSUE #13096: `ValueSetSelect` in forms not getting focus and scroll on Error
## Describe the bug

ValueSetSelect in forms are not getting scroll to and focus on any validation errors popping whereas other fields do that being in same form and on long form where submit button is at bottom where user needs to scroll  it creates confusion why form is not submitting and it is bad of UX

>[!NOTE]
It happening to every form which are using `ValueSetSelect` as field  

https://github.com/user-attachments/assets/ec116fee-c561-4c12-b921-c31c23a53b23

## Expected

https://github.com/user-attachments/assets/a363565c-05fe-4a4f-8cd1-e3b2282f7026

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #13096 
- Add `FormField` components wherever it is missing for changes files 
- Add props ref and aria-invalid which are responsible for focus and scroll on error 
- Update ValueSetSelect field according to above changes

Screenshot 2025-08-01 at 2 33 08 PM

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.

## Summary by CodeRabbit

* **Refactor**
  * Standardized form-field wiring and accessibility (aria-required) across multiple forms for consistent layout, validation messaging, and ValueSetSelect integration.

* **UX**
  * ValueSetSelect now forwards extra button attributes and no longer uses a separate disabled prop, improving flexibility and button behavior across triggers.

* **Tests**
  * Dropdown test selector updated to target combobox role for more robust selection testing.

### CODE REVIEW

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

**Comment by nihal467** [comment]
LGTM

File: src/pages/Facility/settings/productKnowledge/ProductKnowledgeForm.tsx [hunk 1]
```diff
@@ -841,13 +849,14 @@ function ProductKnowledgeFormContent({
                                           showCode={true}
                                         />
                                       </FormControl>
+                                      <FormMessage>
+                                        {form.formState.errors.definitional
+                                          ?.intended_routes?.[index] &&
+                                          t("required")}
+                                      </FormMessage>
```
Comment (rithviknishad) [inline src/pages/Facility/settings/productKnowledge/ProductKnowledgeForm.tsx]: are you sure this is how it is to be done? 🤔

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/productKnowledge/ProductKnowledgeForm.tsx (hunk 1 above)
Comment (AdityaJ2305) [reply src/pages/Facility/settings/productKnowledge/ProductKnowledgeForm.tsx]: oh, I didn't see it. It was already like this I just moved it inside `<formitem>`

Let me check

Comment (AdityaJ2305) [reply src/pages/Facility/settings/productKnowledge/ProductKnowledgeForm.tsx]: done

**Comment by AdityaJ2305** [comment]
@Jacobjeevan  @rithviknishad PTAL

File: src/pages/Facility/settings/productKnowledge/ProductKnowledgeForm.tsx [hunk 2]
```diff
@@ -159,6 +110,59 @@ function ProductKnowledgeFormContent({
...
+      .object({
+        dosage_form: CodeSchema.optional(),
+        intended_routes: z
+          .array(
+            CodeSchema.refine(
+              (data) => data.code && data.display && data.system,
+              {
+                message: t("field_required"),
+              },
+            ),
```
Comment (rithviknishad) [inline src/pages/Facility/settings/productKnowledge/ProductKnowledgeForm.tsx]: i believe this should be part of code schema itself. why this specific refine only here? it should be applicable for all code objects right?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/productKnowledge/ProductKnowledgeForm.tsx (hunk 2 above)
Comment (AdityaJ2305) [reply src/pages/Facility/settings/productKnowledge/ProductKnowledgeForm.tsx]: Yes Rithvik, but can I take this in separate PR since it would need some other changes as well since it's a type change and also this pr is opened from very long

File: src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx [hunk 3]
```diff
@@ -467,28 +467,32 @@ function ObservationDefinitionFormContent({
...
+                                system: code.system,
+                              });
+                            }}
+                            showCode={true}
+                          />
+                        </FormControl>
+                        <FormMessage />
+                      </FormItem>
+                    )}
+                  />
```
[the remark this answers is not in the document]
Comment (AdityaJ2305) [reply src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx:495]: not a big deal could be avoidable or will be made seperately

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
- add the validation for the base unit in the product knowledge creation form

**Comment by AdityaJ2305** [comment]
> * add the validation for the base unit in the product knowledge creation form

@nihal467 There is already a pull request opened for the same https://github.com/ohcnetwork/care_fe/pull/13858

**Review by khavinshankar — APPROVED** [review]
