### PR TITLE
prevent base price input overflow in mobile view

### LINKED ISSUE #13111: Mobile view: Base Price input overflows screen
**Describe the bug**
On mobile devices, the Base Price input field in the Pricing Components section overflows the screen horizontally. This causes layout-breaking behavior and may require horizontal scrolling, especially on smaller screen widths.

**To Reproduce**

1. Go to setting 
2. Click on  click charge item definations add definations
3. Scroll down to base price in mobile view 

**Expected behavior**
The Base Price input should be fully responsive and adjust to fit within the mobile screen without causing horizontal overflow.

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
To fix the mobile view issue, I will wrap the Base Price input field inside a styled container similar to how Discounts and Taxes are displayed. This means the Base Price will be stacked vertically above Discounts and Taxes, instead of appearing inline or disconnected.

**Expected Timeline:**
1day after assignment
**Additional Context:**
i will complete it please assign me this work

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Harishgouda06022004**
## Proposed Changes

- Fixes  #13111
-fixed overflow of base price in mobile view

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **Refactor**
  * Updated the layout and styling of the base price input section for improved clarity and simplicity.
  * Removed the MRP input field and its related information from the pricing components card.

* **Style**
  * Adjusted spacing and stacking of elements in the pricing section for a cleaner appearance.

### CODE REVIEW

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

**Comment by Tanuj1718** [comment]
@Harishgouda06022004 merge checklist??

File: src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx [hunk 1]
```diff
@@ -605,10 +605,10 @@ export function ChargeItemDefinitionForm({
           </CardHeader>
           <CardContent className="space-y-6">
             {/* Base Price and MRP */}
-            <div className="p-4 bg-gray-50 rounded-lg border">
+            {/* <div className="p-4 bg-gray-50 rounded-lg border">
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx:608]: Is there a corresponding closing div? What happens if someone uncomments this? Not an issue though, something to keep in mind for future.

**Review by Jacobjeevan — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
LGTM
