### PR TITLE
Fix : Delete Avatar Shows Uploading Transition Instead of Deleting

### LINKED ISSUE #12745: Delete Avatar Shows Uploading Transition Instead of Deleting
**Describe the bug**
When deleting a profile avatar, the UI shows an "Uploading..." loading state instead of a "Deleting..." state.

**To Reproduce**

1. Go to 'Profile' page.
2. Click on 'Change Avatar'. 
3. Click on 'Delete' button to remove current avatar.
4. Observe the loading spinner shows "Uploading..." text during deletion.

https://github.com/user-attachments/assets/97e91298-a997-4bf1-8791-466e436e91c3

**Expected behavior**
When deleting an avatar, the button should show a loading spinner with "Deleting...".

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #12745
- Showing deleting transition over the delete utton. 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

https://github.com/user-attachments/assets/32f83cd6-325c-489e-822a-1e8b6a638313

- [x] Request for Peer Reviews
- [] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **New Features**
  * Improved avatar modal with separate visual feedback for avatar deletion and other processing actions. The delete button and related UI elements now clearly indicate when an avatar is being deleted, enhancing user clarity during asynchronous operations.

### CODE REVIEW

File: src/components/Common/AvatarEditModal.tsx [hunk 1]
```diff
@@ -539,9 +541,11 @@ export default function AvatarEditModal({
...
                       {isProcessing
                         ? `${t("uploading")}...`
-                        : showCroppedPreview
-                          ? `${t("upload")}`
-                          : `${t("crop")}`}
+                        : isDeleting
+                          ? `${t("deleting")}...`
+                          : showCroppedPreview
+                            ? `${t("upload")}`
+                            : `${t("crop")}`}
```
Comment (AdityaJ2305) [inline src/components/Common/AvatarEditModal.tsx]: I'd say just disable this button while deleting and show `deleting` in delete button itself not here

Comment (Jeffrin2005) [reply src/components/Common/AvatarEditModal.tsx]: Hm👍. the transition uploading is showing over the upload button, so similarly i thought we can give the transition over the upload button. we can wait for their suggestion.
@rithviknishad @Jacobjeevan

Comment (Jacobjeevan) [reply src/components/Common/AvatarEditModal.tsx]: Go with Aditya's suggestion @Jeffrin2005.

**Comment by Jeffrin2005** [comment]
@Jacobjeevan @AdityaJ2305 
Now we are showing 'deleting' transtion on the delete button and also we disable the upload button.

https://github.com/user-attachments/assets/b588d343-cd73-4da9-bed1-9c1c23af0b9a

**Comment by AdityaJ2305** [comment]
Should we disable `all` buttons on isDeleting ? same for isProcessing ? 🤔

**Review by AdityaJ2305 — APPROVED** [review]

**Comment by Jeffrin2005** [comment]
@Jacobjeevan Ready for review.

**Comment by Jeffrin2005** [comment]
@Jacobjeevan Ready for review.

**Comment by Jeffrin2005** [comment]
@Jacobjeevan Can we change the label.

**Comment by Jeffrin2005** [comment]
@Jacobjeevan @rithviknishad Can we change the label.

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
