### PR TITLE
fix: make device name responsive and align icon properly

### LINKED ISSUE #13308: Bug: Device name is overflowing and needs responsiveness
**Describe the bug**
Refer the screenshot below:

Image

**To Reproduce**

1. Go to Devices
2. Create a device with long name
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by ama1t**
## Proposed Changes

Fixes #13308 
- Truncated long device names to prevent card overflow.
- Added tooltip on hover to display the full device name.
- Adjusted icon alignment to remain consistent with the first line of text.
Screenshot 2025-08-22 011013

Screenshot 2025-08-16 175411

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.

## Summary by CodeRabbit

* **New Features**
  * Hover tooltip shows the full device name when truncated in device cards.

* **Style**
  * Updated device header layout and typography for clearer presentation.
  * Improved text wrapping to handle long device names.

* **Bug Fixes**
  * Long device names no longer overflow in device details and cards.

* **Refactor**
  * Separated icon and title sections for improved alignment and readability.

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
- Instead of wrapping the entire text and increasing the height of the card, try truncating lengthy names after a certain length and show a tooltip on hover for viewing the full text. This way, the card height and width remain uniform across the page.

File: src/pages/Facility/settings/devices/components/DeviceCard.tsx [hunk 1]
```diff
@@ -25,6 +32,15 @@ interface Props {
 export default function DeviceCard({ device, encounter }: Props) {
   const { t } = useTranslation();
 
+  const textRef = useRef<HTMLDivElement>(null);
+  const [isTruncated, setIsTruncated] = useState(false);
+
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/devices/components/DeviceCard.tsx]: 🤔  why? let's use tailwind classes + width for truncate; let's not add a useEffect just for this.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/devices/components/DeviceCard.tsx (hunk 1 above)
Comment (ama1t) [reply src/pages/Facility/settings/devices/components/DeviceCard.tsx]: @Jacobjeevan ,I added useEffect so the tooltip appears only when the text is actually truncated. Should I change it to show only when the name exceeds a certain length, or is there another approach you’d suggest?

Comment (Jacobjeevan) [reply src/pages/Facility/settings/devices/components/DeviceCard.tsx]: Can just show tooltip for regardless 👍

**Review by Jacobjeevan — APPROVED** [review]
