### PR TITLE
fix: Avoid unnecessary re-renders and handle page crash in Header of Report Builder

### LINKED ISSUE #12428: Bug: Page getting crashed when we add new row after deleting all rows in Header of Report Builder
**Describe the bug**
When we are trying to add a new row after deleting all the rows of Header in Report builder, it get crashed

**To Reproduce**

1. Go to [link](http://localhost:4000/facility/2fbb0809-b62c-4c53-816e-f1404f096c5e/settings/reportbuilder/new)
2. Click on Header
3. Delete all rows and add a new row

**Expected behavior**
We should able to add a new row and page should not get crashed

**Screenshots**

https://github.com/user-attachments/assets/12cff37c-7ecd-40f4-a5b5-b9940ced0c7a

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Tanuj1718**
## Proposed Changes

- Fixes #12428
- Remove activeElements from the dependency array to avoid unnecessary re-renders

Before: 

https://github.com/user-attachments/assets/b0600994-21a0-4840-bad1-54f3b899428b

After:

https://github.com/user-attachments/assets/2459be39-c684-4de7-926b-ea34ed93d210

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved stability of header initialization in the Report Builder by updating how changes to rows are handled.
- **Refactor**
  - Streamlined header element management by localizing add/remove functionality and active element state within each header row for smoother interaction.

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

File: src/pages/Encounters/ReportBuilder/HeaderBuilder.tsx [hunk 1]
```diff
@@ -795,17 +890,19 @@ function HeaderRow({
...
-                      {activeElement}
-                      {". "}
-                      {t(`${column[activeElement].type}`)}
-                    </span>
-                  </SelectValue>
+                  {activeElement !== null && (
+                    <SelectValue placeholder={t("add_element")}>
+                      <CareIcon
+                        icon={getElementIcon(column[activeElement].type)}
+                        className="w-4 h-4 text-green-900"
```
Comment (AdityaJ2305) [inline src/pages/Encounters/ReportBuilder/HeaderBuilder.tsx:897]:
```suggestion
                        className="size-4 text-green-900"
```

**Comment by nihal467** [comment]
the rerender crashed is resolved

**Review by rithviknishad — APPROVED** [review]
