### PR TITLE
fix: enhance autoPrint hook by adding touch device check before navigating back

### LINKED ISSUE #16046: Auto Print in Prescriptions is causing Blank Pages on Mobile
Auto Print in Prescriptions causing Blank Pages on Mobile

### PR DESCRIPTION
**Pull request by abhimanyurajeesh**
## Proposed Changes

Fixes  #16046

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved auto-print behavior on touch devices to prevent automatic page navigation after printing.

### CODE REVIEW

File: src/hooks/useAutoPrint.ts [hunk 1]
```diff
@@ -30,7 +30,10 @@ export default function useAutoPrint({
         // Give some time for the print dialog to appear before navigating back
         await sleep(300);
         setIsProcessing(false);
-        window.history.go(-1);
+        // will figure out a better solution later
```
Comment (bodhish) [inline src/hooks/useAutoPrint.ts:33]: Create a issue for this @copilot

**Review by bodhish — APPROVED** [review]
