### PR TITLE
Fix: appointment structured question 'required' flag support

### LINKED ISSUE #11620: When appointment structured question is added to a questionnaire by default it is set as mandatory.
**Describe the bug**
When an appointment structured questionnaire is added to a questionnaire, by default it is set as a mandatory question and the questionnaire cannot be submitted without scheduling an appointment.

Expected behaviour 

Unless it is set as required , it should not be set mandatory

### PR DESCRIPTION
**Pull request by yadavshubham01**
## Proposed Changes

- Fixes #11620 
- Add logic to display the "Required" flag only when the required setting is enabled.
- Add support to allow submitting the questionnaire without scheduling an appointment

##  Screenshot 

https://github.com/user-attachments/assets/cc733b0c-810b-43a4-8473-398621d8ed78

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Required field indicators (red asterisks) for appointment questions now only appear if the question is marked as required.
- **Bug Fixes**
  - Validation for appointment questions now respects the required status dynamically.
  - Validation error messages for reason and appointment slot fields are no longer shown in the UI.

### CODE REVIEW

**Comment by yadavshubham01** [comment]
@rithviknishad @Jacobjeevan  need review

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
image

- unable to submit the questionnaire Appointment New , the slot API is being triggered unnecessary

**Comment by Jacobjeevan** [comment]
Try and get this fixed asap, we want to get this out for next release for Arike.

Cc: @nihal467

**Comment by yadavshubham01** [comment]
Just complete it before eod

**Comment by yadavshubham01** [comment]
Hey @Jacobjeevan, the reason questionnaire submission is failing is because If the user fills only the “Reason for Visit” and skips appointment scheduling, Then slot_id is null, And our appointment getRequests() returns an empty array,
Which causes the POST /batch_requests/ to fail with a 400 error.

Do we have (or can we add) a backend fallback that allows submission even if no appointment is scheduled? For example: Either by accepting empty requests gracefully as a no-op, Or by having a separate request that stores just the reason_for_visit without requiring slot_id.

**Comment by yadavshubham01** [comment]
Hi @nihal467,
I’ve implemented logic so that when a questionnaire contains multiple questions (including an appointment structured question), users can submit the questionnaire without scheduling an appointment (also empty reason for visit )" In this case, the slot API is not called, which works as expected.

However, if the questionnaire contains only the appointment structured question, and the user tries to submit it with just the "reason for visit" (without selecting a slot), the submission fails because the slot API is still called (since there’s no other structured request to send). This is due to the backend expecting at least one request, and our handler only generating a request if a slot is selected.

Please advise on how you’d like to handle this scenario:
- Should we create a generic appointment endpoint for "reason for visit" only?
- Or should we require a slot selection if the appointment question is the only question in the questionnaire?

**Comment by nihal467** [comment]
image

- @Jacobjeevan when we add some value in the reason of visit and remove it, then this frontend validation is triggered

**Comment by nihal467** [comment]
LGTM

File: src/components/Questionnaire/QuestionTypes/AppointmentQuestion.tsx [hunk 1]
```diff
@@ -67,8 +61,16 @@ const APPOINTMENT_FIELDS: FieldDefinitions = {
 export function validateAppointmentQuestion(
   value: CreateAppointmentQuestion,
   questionId: string,
+  required: boolean,
 ): QuestionValidationError[] {
-  return validateFields(value, questionId, APPOINTMENT_FIELDS);
+  const reasonRequired = required || (value && value.slot_id !== undefined);
```
Comment (gigincg) [inline src/components/Questionnaire/QuestionTypes/AppointmentQuestion.tsx]: You could rather write

```
return validateFields(value, questionId, {
  REASON: {
    ...APPOINTMENT_FIELDS.REASON,
    required: required || value?.slot_id !== undefined,
  },
  SLOT: {
    ...APPOINTMENT_FIELDS.SLOT,
    required: required || value?.reason_for_visit !== undefined,
  },
});
```

**Comment by nihal467** [comment]
@yadavshubham01 can you look into the comment

File: src/components/Questionnaire/QuestionTypes/AppointmentQuestion.tsx (hunk 1 above)
Comment (yadavshubham01) [reply src/components/Questionnaire/QuestionTypes/AppointmentQuestion.tsx]: done

**Comment by yadavshubham01** [comment]
@nihal467 Done

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTm

**Review by rithviknishad — APPROVED** [review]

**Comment by yadavshubham01** [comment]
@Jacobjeevan thanks for helping 🙌
