### PR TITLE
Fixed session-expired page view and minor improvments

### LINKED ISSUE #8932: Improper Session Expired Page - Image and Button Misaligned
**Describe the bug**
The contents present in **session-expired** page looks weird and the **Return to Login** button is misaligned

**To Reproduce**

1. Go to /session-expired route
2. You can see that the contents present in this page are not properly aligned.
**Note:** Check this in 100% view of Desktop

**Expected behavior**
The page should look clean, and the **Return to Login** button should be accessible easily

**Screenshots**

This is how it looks now:

Image

Image

Suggested/Expected look:

Image

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version Latest

### PR DESCRIPTION
**Pull request by nithish1018**
## Proposed Changes

- Fixes #8932 
- Adjusted svg size
- Adjusted button position

This is how it looks now:

Image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

File: src/components/ErrorPages/SessionExpired.tsx [hunk 1]
```diff
@@ -26,7 +26,7 @@ export default function SessionExpired() {
           <br />
           <div
             onClick={signOut}
-            className="hover:bg-primary- inline-block cursor-pointer rounded-lg bg-primary-600 px-4 py-2 text-white hover:text-white"
+            className="mt-5 inline-block cursor-pointer rounded-lg bg-primary-600 px-4 py-2 text-white hover:bg-primary-400"
```
Comment (rithviknishad) [inline src/components/ErrorPages/SessionExpired.tsx:29]: nice find btw
