### PR TITLE
Fix: Facility switcher and Organization switcher edge case handled

### LINKED ISSUE #10627: Able to view both facility switcher and org. switcher in sidebar for an edge case
**Describe the bug**
Able to view both facility switcher and org. switcher in sidebar for an edge case.

**To Reproduce**

1. Login and open any Organization that your linked facilities are part of.
2. Open the facilities tab and open one of the facility that you are linked with.
3. Go back
4. Observe that you now have both org. switcher and facility switcher.

**Expected behavior**
View Facility from Org's pages shouldn't ideally share the same route as Facility Home's page.

**Screenshots**

https://github.com/user-attachments/assets/dfcbd1da-3944-4ba2-9d64-727474b2f491

**Desktop (please complete the following information):**

### PR DESCRIPTION
**Pull request by Rishith25**
## Proposed Changes

- Fixes #10627 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Sidebar labels, including the dashboard view, now adapt to your selected language.
- **Bug Fixes**
	- Improved facility switcher visibility to appear only when all required information is available.
	- Enhanced logic for resetting selected facility based on availability.

### CODE REVIEW

File: src/components/ui/sidebar/app-sidebar.tsx [hunk 1]
```diff
@@ -60,6 +62,8 @@ export function AppSidebar({
   }, [user?.organizations, organizationId]);
 
   React.useEffect(() => {
+    setSelectedFacility(null);
+
     if (!user?.facilities || !facilityId || !facilitySidebar) return;
 
     const facility = user.facilities.find((f) => f.id === facilityId);
```
Comment (rithviknishad) [inline src/components/ui/sidebar/app-sidebar.tsx]:
```suggestion
    if (!user?.facilities || !facilityId || !facilitySidebar) {
      setSelectedFacility(null);
      return;
    }

    const facility = user.facilities.find((f) => f.id === facilityId);
    if (!facility) {
      setSelectedFacility(null);
      return;
    }
```

File: src/components/ui/sidebar/app-sidebar.tsx [hunk 2]
```diff
@@ -85,7 +89,7 @@ export function AppSidebar({
             selectedOrganization={selectedOrganization}
           />
         )}
-        {selectedFacility && hasFacilities && (
+        {facilityId && selectedFacility && hasFacilities && (
```
Comment (rithviknishad) [inline src/components/ui/sidebar/app-sidebar.tsx:91]: let's not change this, the above change is sufficient right?

File: src/components/ui/sidebar/app-sidebar.tsx
Comment (Jacobjeevan) [inline src/components/ui/sidebar/app-sidebar.tsx:1]: Do a self-review - with the new changes, the code should be adjusted a bit.

File: src/components/ui/sidebar/app-sidebar.tsx (hunk 2 above)
Comment (Rishith25) [reply src/components/ui/sidebar/app-sidebar.tsx:91]: @rithviknishad @Jacobjeevan  i think we need this, because useeffect is taking time to reset the selectedFacility to null. The component may still render with the old state for a brief moment before the next render cycle updates the UI.

File: src/components/ui/sidebar/app-sidebar.tsx [hunk 3]
```diff
@@ -85,7 +88,7 @@ export function AppSidebar({
...
```
Comment (Rishith25) [inline src/components/ui/sidebar/app-sidebar.tsx:91]: Self Review:
@rithviknishad @Jacobjeevan i think we need this, because useeffect is taking time to reset the selectedFacility to null. The component may still render with the old state for a brief moment before the next render cycle updates the UI.

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
