### PR TITLE
Handle exceptions raised by the addSourceBuffer method

### LINKED ISSUE #8200: InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the p...
Sentry Issue: [CARE-FE-3B9](https://coronasafe-network.sentry.io/issues/5015520076/?referrer=github_integration)

```
InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
  at pushPacket (../../src/Common/hooks/useMSEplayer.ts:114:25)
  at readPacket (../../src/Common/hooks/useMSEplayer.ts:141:18)
  at ws.onmessage (../../src/Common/hooks/useMSEplayer.ts:182:17)
```

### PR DESCRIPTION
**Pull request by sainak**
This pull request addresses an issue where exceptions raised by the `addSourceBuffer` method were not being handled properly. 
https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/addSourceBuffer#exceptions

fixes #8200

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

File: src/Common/hooks/useMSEplayer.ts [hunk 1]
```diff
@@ -171,9 +171,14 @@ export const useMSEMediaPlayer = ({
...
                 }
-                mseSourceBuffer = mse.addSourceBuffer(
-                  `video/mp4; codecs="${mimeCodec}"`,
-                );
+                try {
+                  mseSourceBuffer = mse.addSourceBuffer(
+                    `video/mp4; codecs="${mimeCodec}"`,
+                  );
+                } catch (error) {
+                  onError && onError(error);
```
Comment (rithviknishad) [inline src/Common/hooks/useMSEplayer.ts]:
```suggestion
                  onError?.(error);
```

**Review by shivankacker — APPROVED** [review]

**Comment by nihal467** [comment]
@sainak is this ready for testing

**Comment by nihal467** [comment]
camera feed looks good in laptop and iphones

**Review by khavinshankar — APPROVED** [review]
