### PR TITLE
Fix: Remove unnecessary validation thrown for edit in healthcare service form

### LINKED ISSUE #13989: Validation is malfunctioning in the healthcare service edit page
**Describe the bug**

Create a new healthcare service with no location and the custom icon, and try to edit the healthcare services in the facility, the validation error will be thrown for empty fields

**To Reproduce**

1. Go to a facility and create a healthcare services with location and icons as empty
2. edit the newly created healthcare services other than location or icon field
3. see the error message

**Expected behavior**

Only throw validation error on submission for mandatory field or whereever necessary

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #13989
- Put the default value for fields which were throwing unnecessary validations in edit form (i.e Internal type and styling_metadata)

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.

## Release Notes

* **Bug Fixes**
  * Resolved form data handling issues for healthcare service configurations
  * Fixed initialization and default values when editing or creating services
  * Improved preservation of existing service attributes during edits

* **Improvements**
  * Enhanced form submission control by requiring modifications before enabling submit button

### CODE REVIEW

**Comment by tasnimshaji** [comment]
LGTM @nihal467

**Comment by nihal467** [comment]
LGTM

**Comment by nihal467** [comment]
@AdityaJ2305 since the PR checklist have been updated, add playwright test

**Review by abhimanyurajeesh — APPROVED** [review]

File: src/pages/Facility/settings/healthcareService/HealthcareServiceForm.tsx [hunk 1]
```diff
@@ -143,9 +143,9 @@ function HealthcareServiceFormContent({
         ? {
             name: existingData.name,
             // service_type: existingData.service_type,
-            styling_metadata: existingData.styling_metadata,
+            styling_metadata: existingData.styling_metadata || { careIcon: "" },
```
Comment (bodhish) [inline src/pages/Facility/settings/healthcareService/HealthcareServiceForm.tsx]: Lets not have a empty value for a key, either we remove the value or keep the key only with a value.

**Review by bodhish — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/healthcareService/HealthcareServiceForm.tsx (hunk 1 above)
Comment (bodhish) [reply src/pages/Facility/settings/healthcareService/HealthcareServiceForm.tsx]: cc @abhimanyurajeesh @nihal467

**Comment by AdityaJ2305** [comment]
@nihal467 Test for healthcare service has been added in this [PR](https://github.com/ohcnetwork/care_fe/pull/14260) by @shivankacker

**Comment by nihal467** [comment]
LGTM

**Review by bodhish — APPROVED** [review]
