### PR TITLE
Added translations in encounter page and minor fixes in patient registration form

### LINKED ISSUE #10233: Fix typo in encounter, and some minor across platform
- [ ] Show Year of Birth inside the input field, when someone type age in the patient registration form

Image

### PR DESCRIPTION
**Pull request by Mahendar0701**
## Proposed Changes

- Fixes #10233 
- Added missing typo in the encounter page (binary, symptoms and diagnosis)

- Responsive patient form and added limit to DD MM YYYY 

image

- Added year of birth for age

image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Patient details now offer localized gender labels, enhancing language support.
  - The registration form dynamically calculates and displays the year of birth based on the age input.

- **UI Improvements**
  - Improved responsive layout for nationality and related fields to ensure optimal viewing on various screen sizes.

### CODE REVIEW

File: src/components/Patient/PatientRegistration.tsx [hunk 1]
```diff
@@ -566,7 +566,15 @@ export default function PatientRegistration(
                             data-cy="age-input"
                           />
                         </FormControl>
+
                         <FormMessage />
+                        {form.getValues("age") && (
+                          <div className="text-violet-600 text-sm font-bold">
+                            {t("year_of_birth")}:{" "}
+                            {new Date().getFullYear() -
```
Comment (AdityaJ2305) [inline src/components/Patient/PatientRegistration.tsx:562]: I think we can use `differenceInYears` from `date-fns`

cc: @Jacobjeevan

File: src/components/ui/phone-input.tsx [hunk 2]
```diff
@@ -105,7 +105,7 @@ const CountrySelect = ({
         <Button
           type="button"
           variant="outline"
-          className="flex gap-1 rounded-e-none rounded-s-md border-r-0 px-3 focus:z-10 h-[38px]"
+          className="flex gap-1 rounded-e-none rounded-s-md border-r-0 px-3 focus:z-10 h-[42px]"
```
Comment (rithviknishad) [inline src/components/ui/phone-input.tsx]: this is not correct, have you tested in desktop mode?

File: src/components/ui/date-field.tsx [hunk 3]
```diff
@@ -42,7 +42,7 @@ export default function DateField({
   }, [date]);
 
   const handleDayChange = (e: React.ChangeEvent<HTMLInputElement>) => {
-    const newDay = e.target.value;
+    const newDay = e.target.value.slice(0, 2);
```
Comment (rithviknishad) [inline src/components/ui/date-field.tsx]: this is not necessary right? i don't see any cases where it'll have more than 2 characters

File: src/components/ui/date-field.tsx [hunk 4]
```diff
@@ -63,7 +63,7 @@ export default function DateField({
   };
 
   const handleMonthChange = (e: React.ChangeEvent<HTMLInputElement>) => {
-    const newMonth = e.target.value;
+    const newMonth = e.target.value.slice(0, 2);
```
Comment (rithviknishad) [inline src/components/ui/date-field.tsx]: here too

File: src/components/ui/date-field.tsx [hunk 5]
```diff
@@ -85,7 +85,7 @@ export default function DateField({
   };
 
   const handleYearChange = (e: React.ChangeEvent<HTMLInputElement>) => {
-    const newYear = e.target.value;
+    const newYear = e.target.value.slice(0, 4);
```
Comment (rithviknishad) [inline src/components/ui/date-field.tsx]: this makes UX bad if they move their caret to left and start typing. numbers will start disappearing and carets start jumping here and there.

File: src/components/ui/date-field.tsx [hunk 6]
```diff
@@ -101,7 +101,7 @@ export default function DateField({
   };
 
   return (
-    <div className="flex items-center gap-2">
+    <div className="flex flex-wrap items-center gap-4 md:gap-2 ">
```
Comment (rithviknishad) [inline src/components/ui/date-field.tsx]: this doesn't look good. why not keep it in one line? day and month is two digits, we could reduce it's width.

image

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/ui/phone-input.tsx (hunk 2 above)
Comment (Mahendar0701) [reply src/components/ui/phone-input.tsx]: outdated

File: src/components/ui/date-field.tsx (hunk 3 above)
Comment (Mahendar0701) [reply src/components/ui/date-field.tsx]: @rithviknishad i used this to set limit for input length for fields DD MM YYYY, 
Earlier we can enter any number of digits in the fields DD MM YYYY

Another approach would be adding maxLength for input for that i have to change input type to "text"

**Comment by Mahendar0701** [comment]
@rithviknishad i used .slice() to set limit for input length for fields DD MM YYYY,
Earlier we can enter any number of digits in the fields DD MM YYYY

Another approach would be adding maxLength for input for that we need to change input type to "text"

Anyway the form validation handles incorrect year 

Added max for year field

File: src/components/ui/date-field.tsx [hunk 7]
```diff
@@ -113,12 +113,11 @@ export default function DateField({
           max={31}
           id={`${id}-day-input`}
           data-cy={`${id}-day-input`}
-          className="w-[10rem]"
           disabled={disabled}
         />
       </div>
 
-      <div className="flex flex-col gap-1">
+      <div className="flex flex-col gap-1 w-1/3">
```
Comment (rithviknishad) [inline src/components/ui/date-field.tsx]: this has already been solved

File: src/components/ui/date-field.tsx [hunk 8]
```diff
@@ -129,22 +128,21 @@ export default function DateField({
...
         <Label>{t("year")}</Label>
         <Input
           type="number"
           placeholder="YYYY"
           value={year}
           onChange={handleYearChange}
+          max={new Date().getFullYear()}
```
Comment (rithviknishad) [inline src/components/ui/date-field.tsx]: why?

File: src/components/Patient/PatientRegistration.tsx (hunk 1 above)
Comment (rithviknishad) [reply src/components/Patient/PatientRegistration.tsx:562]: yup, let's do that

Comment (AdityaJ2305) [reply src/components/Patient/PatientRegistration.tsx:562]: @Mahendar0701

Comment (Mahendar0701) [reply src/components/Patient/PatientRegistration.tsx:562]: here i am displaying the year of birth based on taking input age, `differenceInYears ` cant be be used here right? it can be used to show difference in years that is to display age?

**Review by rithviknishad — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
