### PR TITLE
Hiding the `Patient Home` button when in Patient Home page

### LINKED ISSUE #14009: Dummy button in patient details page
**Describe the bug**
In patient home page, there is a `Patient Home` which is redundant as user is already in patient home

**To Reproduce**

1. Go to 'Search Patient'
2. Click on 'any patient'
3. Scroll down to 'Patient Home'

**Expected behavior**
Remove the dummy button

**Screenshots**

https://github.com/user-attachments/assets/91356053-40b3-477c-ad60-0ca9aad3cc97

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by GSMPRANEETH**
## Proposed Changes

Fixes #14009 
- Hiding the button when the user is already in page that has `patients/verify` in the url

image_2025-10-14_214601297

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

* **New Features**
  * Patient info hover card now detects when you're already on a patient's verification page and hides the redundant primary action, simplifying available actions and preventing duplicate navigation options.

### CODE REVIEW

**Comment by tasnimshaji** [comment]
LGTM @nihal467

File: src/components/Patient/PatientInfoHoverCard.tsx [hunk 1]
```diff
@@ -36,7 +36,12 @@ export const PatientInfoHoverCard = ({
         </div>
       </div>
       <div className="flex items-center gap-2">
-        <Button variant="outline" className="text-gray-950" asChild>
+        <Button
+          variant="outline"
+          className="text-gray-950"
+          asChild
+          hidden={location.pathname.includes("/patients/verify")}
```
Comment (AdityaJ2305) [inline src/components/Patient/PatientInfoHoverCard.tsx]: Image

It still renders in dom

**Review by yash-learner — CHANGES_REQUESTED** [review]
Use raviger's `usePath`  which is common in the codebase or raviger's `useRoute`   instead of `location.pathname`

and 

Also as Aditya mentioned let's not even render that https://github.com/ohcnetwork/care_fe/pull/14053/files#r2431692181

File: src/components/Patient/PatientInfoHoverCard.tsx (hunk 1 above)
Comment (GSMPRANEETH) [reply src/components/Patient/PatientInfoHoverCard.tsx]: Only rendering it when not in the patients home page 👍

File: src/components/Patient/PatientInfoHoverCard.tsx [hunk 2]
```diff
@@ -36,20 +36,29 @@ export const PatientInfoHoverCard = ({
...
-                phone_number: patient.phone_number,
-                year_of_birth: patient.year_of_birth.toString(),
-                partial_id: patient.id.slice(0, 5),
-              },
-            ).toString()}`}
-          >
-            {t("patient_home")}
-          </Link>
-        </Button>
+        {!usePath()?.includes(
```
Comment (AdityaJ2305) [inline src/components/Patient/PatientInfoHoverCard.tsx]: Extract the path out in variable called path and use that instead. It would more cleaner 

`const path = usePath();`

File: src/components/Patient/PatientInfoHoverCard.tsx [hunk 3]
```diff
@@ -36,20 +36,29 @@ export const PatientInfoHoverCard = ({
...
+          `/facility/${facilityId}/patients/verify?${new URLSearchParams({
+            phone_number: patient.phone_number,
+            year_of_birth: patient.year_of_birth.toString(),
+            partial_id: patient.id.slice(0, 5),
+          }).toString()}`,
+        ) && (
```
[the remark this answers is not in the document]
Comment (AdityaJ2305) [reply src/components/Patient/PatientInfoHoverCard.tsx]: Hmm, kind of agree with @copilot here , query param could change and doesn't guarantee every time it would match 

so let's just go ahead with
`/facility/${facilityId}/patients/verify`


@yash-learner any comments on it ? 


PS: Honestly, I’m not a big fan of using the path to hide the button. I’d rather use an optional prop and conditionally render it. But after checking the code, doing that would cause prop drilling since there are too many parent levels involved.

[the remark this answers is not in the document]
Comment (yash-learner) [reply src/components/Patient/PatientInfoHoverCard.tsx]: @AdityaJ2305 @GSMPRANEETH 

I think just this is enough and will work

```ts
!path?.endsWith("/patients/verify")
```

----

```ts
        {!path?.endsWith("/patients/verify") && (
          <Button variant="outline" className="text-gray-950" asChild>
            <Link
              basePath="/"
              href={`/facility/${facilityId}/patients/verify?${new URLSearchParams(
                {
                  phone_number: patient.phone_number,
                  year_of_birth: patient.year_of_birth.toString(),
                  partial_id: patient.id.slice(0, 5),
                },
              ).toString()}`}
            >
              {t("patient_home")}
            </Link>
          </Button>
        )}
  ```

File: src/components/Patient/PatientInfoHoverCard.tsx (hunk 2 above)
Comment (GSMPRANEETH) [reply src/components/Patient/PatientInfoHoverCard.tsx]: Using only `"patients/verify"` so wont be needed 😄

File: src/components/Patient/PatientInfoHoverCard.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (GSMPRANEETH) [reply src/components/Patient/PatientInfoHoverCard.tsx]: 👍

File: src/components/Patient/PatientInfoHoverCard.tsx (hunk 2 above)
Comment (AdityaJ2305) [reply src/components/Patient/PatientInfoHoverCard.tsx]: @GSMPRANEETH Didn't get what you want to say ?

Comment (yash-learner) [reply src/components/Patient/PatientInfoHoverCard.tsx]: @GSMPRANEETH https://github.com/ohcnetwork/care_fe/pull/14053#discussion_r2435506370,  https://github.com/ohcnetwork/care_fe/pull/14053#discussion_r2435590598

and 

why did you preferred `includes`, instead of `endsWith` ?  https://github.com/ohcnetwork/care_fe/pull/14053/commits/a75128759e60a3f668e1363387c68480b0684874

Comment (GSMPRANEETH) [reply src/components/Patient/PatientInfoHoverCard.tsx]: @AdityaJ2305 
as now only using a short url `patients/verify`, i think there is no need to explicitly define a var for it
@yash-learner 
I was in the fog on the working of `endsWith` 😅 , thought only verifies the end of an url, but the patients home page has var  params in the end, so I prefered `includes`

Comment (yash-learner) [reply src/components/Patient/PatientInfoHoverCard.tsx]: @GSMPRANEETH 

> I was in the fog on the working of endsWith 😅 , thought only verifies the end of an url, but the patients home page has var params in the end, so I prefered includes

`usePath()` from Raviger gets **only the path** not params from the `URL` -> If you want you can test it in your local by doing a console.log of path via `const path = usePath()`

---

> as now only using a short url patients/verify, i think there is no need to explicitly define a var for it

It still violated rules of hook as pointed by copilot,  https://github.com/ohcnetwork/care_fe/pull/14053#discussion_r2435506370

---

Can you make above changes ?

**Review by yash-learner — APPROVED** [review]
Code looks good to me

File: src/components/Patient/PatientInfoHoverCard.tsx [hunk 4]
```diff
@@ -19,6 +19,9 @@ export const PatientInfoHoverCard = ({
 }) => {
   const { t } = useTranslation();
 
+  const path = usePath();
+  const isHome = path?.endsWith(`/facility/${facilityId}/patients/verify`);
```
[the remark this answers is not in the document]
Comment (AdityaJ2305) [reply src/components/Patient/PatientInfoHoverCard.tsx]:
```suggestion
  const isPatientHomePage = path?.endsWith(`/facility/${facilityId}/patients/verify`);
```

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

**Comment by AdityaJ2305** [comment]
@GSMPRANEETH Format the code which is causing build fail

**Review by AdityaJ2305 — APPROVED** [review]
LGTM

**Review by yash-learner — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/components/Patient/PatientInfoHoverCard.tsx [hunk 5]
```diff
@@ -19,6 +19,11 @@ export const PatientInfoHoverCard = ({
 }) => {
   const { t } = useTranslation();
 
+  const path = usePath();
+  const isPatientHomePage = path?.endsWith(
+    `/facility/${facilityId}/patients/verify`,
+  );
```
Comment (GSMPRANEETH) [inline src/components/Patient/PatientInfoHoverCard.tsx:25]: not gonna use includes

**Comment by nihal467** [comment]
@GSMPRANEETH since the PR checklist have been updated, add the playwright test as well to verify the functionality of the change made in your PR

**Review by bodhish — APPROVED** [review]
