### PR TITLE
fixed #14922: fixed Create Template Form

### LINKED ISSUE #14922: Template Builder doesn't follow proper ux
**Describe the bug**
In template builder page, the required fields are not properly shown, and also there isn't any form error messages for the required fields. The fields are name, slug and context. these aren't being shown as required properly with proper ux

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Templates'
3. Scroll down to 'Create Template'

**Expected behavior**
All required fields must be properly shown following ux

**Screenshots**

https://github.com/user-attachments/assets/29fe2ecf-1d69-4ae1-9ab6-cbf204a3985b

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Ishu813**
## Proposed Changes

Fixes #14922
- Adjusted Zod Schema.
- Fixed Validation error message not showing for fields.
- Added back button.

**Screen Recording**

https://github.com/user-attachments/assets/ead6af5e-c182-4dda-b4bc-ba59a9118a8c

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.
- [x] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **New Features**
  * Auto-selects the first available context when creating a new template.

* **Bug Fixes & Improvements**
  * Simplified header layout for a cleaner interface.
  * Enhanced form validation feedback with improved error messaging.
  * Improved context selection experience with better form integration.
  * Refined form labels and spacing for better usability.

### CODE REVIEW

File: src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx [hunk 1]
```diff
@@ -390,10 +398,7 @@ export default function TemplateBuilder({
               name="name"
               render={({ field }) => (
                 <FormItem>
-                  <FormLabel>
-                    {t("template_name")}
-                    <span className="text-destructive ml-1">*</span>
-                  </FormLabel>
+                  <FormLabel>{t("template_name")}</FormLabel>
```
Comment (AdityaJ2305) [inline src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx]: Add aria-required to FormLabel show * for required fields

File: package.json
Comment (AdityaJ2305) [inline package.json:1]: Looks unrelated to issue so discard changes from package.json

File: package-lock.json
Comment (AdityaJ2305) [inline package-lock.json:1]: same discard

File: src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx [hunk 2]
```diff
@@ -376,7 +379,12 @@ export default function TemplateBuilder({
             >
               {t("preview_template")}
             </Button>
-            <Button type="button" onClick={handleSaveTemplate}>
+            <Button
+              type="button"
```
Comment (AdityaJ2305) [inline src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx:394]: shouldn't be type="submit" ??

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

File: src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx [hunk 3]
```diff
@@ -103,13 +90,36 @@ export default function TemplateBuilder({
...
+  const templateBuilderSchema = z.object({
+    name: z.string().trim().min(1, t("field_required")),
+    slug_value: z
+      .string()
+      .trim()
+      .min(5, {
+        message: t("character_count_validation", { min: 5, max: 25 }),
+      })
+      .max(25, {
+        message: t("character_count_validation", { min: 5, max: 25 }),
```
Comment (bodhish) [inline src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx]: The current slug max size is not 25; we should create an issue to update it in codebase.

File: src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx [hunk 4]
```diff
@@ -201,14 +211,16 @@ export default function TemplateBuilder({
...
+      setSelectedContext(availableContexts[0]);
     }
   }, [template, availableContexts]);
 
   // Handle template save
   const handleSaveTemplate = async () => {
     const formData = form.getValues();
     const templateData = {
-      template_type: formData.template_type,
+      template_type: template?.template_type || "discharge_summary",
```
Comment (bodhish) [inline src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx]: Not sure why we need to default? 🤔

**Review by bodhish — DISMISSED** [review]

File: src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx (hunk 3 above)
Comment (Ishu813) [reply src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx]: > The current slug max size is not 25; we should create an issue to update it in codebase.

@bodhish What should be the current slug max size...?

Comment (Jacobjeevan) [reply src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx]: 36 is the max size.

File: src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx (hunk 4 above)
Comment (Jacobjeevan) [reply src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx]: Don't need here; User should be selecting that @Ishu813

File: src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx [hunk 5]
```diff
@@ -343,20 +355,11 @@ export default function TemplateBuilder({
     <div className="h-screen flex flex-col">
       <div className="border-b p-4">
         <div className="flex flex-col sm:flex-row gap-2 items-center justify-between mb-4">
```
Comment (Jacobjeevan) [inline src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx:368]: why remove back button?

File: src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx [hunk 6]
```diff
@@ -376,7 +379,12 @@ export default function TemplateBuilder({
             >
               {t("preview_template")}
             </Button>
-            <Button type="button" onClick={handleSaveTemplate}>
+            <Button
+              type="submit"
```
Comment (Jacobjeevan) [inline src/pages/Encounters/TemplateBuilder/TemplateBuilder.tsx]: can keep as is since button is outside of form/type submit doesn't matter here.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by Ishu813** [comment]
@bodhish @Jacobjeevan I have done the fixes and added a back button to the page. Pls review.

**Review by Jacobjeevan — APPROVED** [review]

**Review by nihal467 — APPROVED** [review]
