### PR TITLE
Resolved the unwanted hover effect and the text colour remains constant

### LINKED ISSUE #10118: Remove Unwanted Hover Effect After Field Selection
**Describe the bug**
An unwanted hover effect appears after selecting a field, making the text unclear and difficult to read. The text should remain clear and visible even after the field is selected.

This issue is present on both the "Book Appointment" page in the patient login and the staff login.

**To Reproduce**

1. Go to Encounter
2. View Details of anyone
3. Patient Details
4. Shedule Appointment
5. Book a slot

**Expected behavior**
Text should remain clear and readable after the field is selected.
**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Proposed Changes

- Fixes #10118
- The text is now clear and readable after the field is selected.

Here is the screenshot
image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced visual feedback for selected appointment slots.
	- Improved slot selection highlighting in the calendar component.

- **Bug Fixes**
	- Refined error handling for slot queries.
	- Corrected text color display for selected and available slots.

### CODE REVIEW

File: src/pages/Appointments/components/AppointmentSlotPicker.tsx [hunk 1]
```diff
@@ -212,13 +212,15 @@ export function AppointmentSlotPicker({
...
+                                selectedSlotId === slot.id
+                                  ? "text-white"
+                                  : percentage >= 1
+                                    ? "text-gray-400"
+                                    : percentage >= 0.8
+                                      ? "text-red-600"
+                                      : percentage >= 0.6
+                                        ? "text-yellow-600"
+                                        : "text-green-600",
                               )}
```
Comment (rithviknishad) [inline src/pages/Appointments/components/AppointmentSlotPicker.tsx]: let's simplify this logic.

File: src/pages/Appointments/components/AppointmentSlotPicker.tsx [hunk 2]
```diff
@@ -219,6 +219,7 @@ export function AppointmentSlotPicker({
                                     : percentage >= 0.6
                                       ? "text-yellow-600"
                                       : "text-green-600",
+                                selectedSlotId === slot.id ? "text-white" : "",
```
Comment (rithviknishad) [inline src/pages/Appointments/components/AppointmentSlotPicker.tsx]:
```suggestion
                                selectedSlotId === slot.id && "text-white",
```

File: src/pages/PublicAppointments/Schedule.tsx [hunk 3]
```diff
@@ -338,6 +338,9 @@ export function ScheduleAppointment(props: AppointmentsProps) {
                                         : percentage >= 0.6
                                           ? "text-yellow-600"
                                           : "text-green-600",
+                                    selectedSlot?.id === slot.id
+                                      ? "text-white"
+                                      : "",
```
Comment (rithviknishad) [inline src/pages/PublicAppointments/Schedule.tsx]:
```suggestion
                                    selectedSlotId === slot.id && "text-white",
```

**Review by rithviknishad — APPROVED** [review]
