### PR TITLE
Fixed the blank space at the bottom in ConsultationForm while updating

### LINKED ISSUE #3976: Consultation page bottom limit is extending to a white screen
**Describe the bug**

When we take the update page of existing patient consultation , there is an option to scroll a lot to the bottom that, it is creating a white space

**To Reproduce**

https://care.coronasafe.in/facility/c4463366-0e21-45c0-9da3-25457e7413e5/patient/82360c67-4380-4f72-9f1a-06bbf30aa496/consultation/70c4ff99-d11b-470c-8233-67e82580df41/update

**Expected behavior**

the bottom size of the page should be fixed

**Screenshots**

image

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #3976 

## Proposed Changes

- The label in the select menu was having an absolute position, thus causing an overflow, so made it relative

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by rithviknishad** [comment]
@khavinshankar the issue is still present. However, it's solved in #3977 
image

File: src/Components/Form/SelectMenuV2.tsx [hunk 1]
```diff
@@ -68,7 +68,7 @@ const SelectMenuV2 = <T, V>(props: SelectMenuProps<T, V>) => {
       >
         {({ open }) => (
           <>
-            <Listbox.Label className="sr-only">
+            <Listbox.Label className="sr-only !relative">
```
Comment (rithviknishad) [inline src/Components/Form/SelectMenuV2.tsx:71]: And, I don't think so this modification helps. Am I missing something?

Comment (khavinshankar) [reply src/Components/Form/SelectMenuV2.tsx:71]: `sr-only` gives absolute positioning for the label, which kinda causes this issue, to be more specific it is because of the select menus in the prescription and the medication builder.

**Comment by khavinshankar** [comment]
> @khavinshankar the issue is still present. However, it's solved in #3977 image

@rithviknishad the issue seems to be present in the pr that you mentioned 
https://deploy-preview-3977--care-net.netlify.app/facility/01810c32-ec26-494a-9e65-40e5547a7746/patient/9c6a4951-916e-439b-b41a-853b6980fefa/consultation/a8003ba0-9c0a-4d27-95b2-d3bd3139652f/update

**Comment by rithviknishad** [comment]
@khavinshankar got it, it wasn't reproducible in firefox consistently but it was reproducible in chrome consistently. my bad

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
test approved

**Review by gigincg — APPROVED** [review]
