### PR TITLE
fix : Replace <span> to Badge component 

### LINKED ISSUE #12711: Replace <span>(custom Badge) with Badge component across the code base
Many components in the codebase, including but not limited to the Medicine Administration module, currently use raw <span> elements to display status labels or tags. To ensure a consistent UI and improved maintainability, these <span> elements should be replaced with the standardized Badge component across the entire codebase.

Image

ref #12668

### PR DESCRIPTION
**Pull request by yadavshubham01**
## Proposed Changes

Fixes #12711

Tagging: @ohcnetwork/care-fe-code-reviewers 

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.

## Summary by CodeRabbit

- **Style**
  - Unified status and info chips across the app using consistent badge styling.
  - Medication Administration: Status, dosage route, and PRN now display as badges for clearer readability.
  - Resource Print Letter: Status shown as a subtle badge for improved visual hierarchy.
  - Report Builder: Error indicators render as small destructive badges for better visibility.
  - Scheduling Template Editor: Availability type displayed as a rounded blue badge for consistency.
  - Overall: Visual polish and consistency improvements without changing functionality.

### CODE REVIEW

File: src/pages/Facility/locations/LocationContent.tsx [hunk 1]
```diff
@@ -125,16 +126,17 @@ function LocationCard({ location, onClick }: LocationCardProps) {
...
-                  ? "text-green-600"
-                  : "text-gray-600",
-              )}
+                  ? "green"
+                  : "secondary"
+              }
+              className="capitalize"
+              size="sm"
             >
               {location.availability_status}
```
Comment (AdityaJ2305) [inline src/pages/Facility/locations/LocationContent.tsx]: add translation with prefix key

File: src/components/Resource/PrintResourceLetter.tsx [hunk 2]
```diff
@@ -89,9 +91,9 @@ export default function PrintResourceLetter({ id }: { id: string }) {
             {/* Status Section */}
             <div className="mb-4">
               <span className="font-semibold">{t("current_status")}: </span>
-              <span className="rounded bg-gray-100 px-2 py-1">
+              <Badge variant="secondary">
                 {t(`resource_status__${data.status}`)}
```
Comment (AdityaJ2305) [inline src/components/Resource/PrintResourceLetter.tsx:95]: like this

**Comment by yadavshubham01** [comment]
@rithviknishad while working on this PR I noticed an issue location.availability_status is not returning anything. It seems we’re not getting any value for availability_status from the backend. Could you please check this?

image

**Comment by yadavshubham01** [comment]
@rithviknishad waiting for review

File: src/pages/Facility/locations/LocationContent.tsx (hunk 1 above)
Comment (yadavshubham01) [reply src/pages/Facility/locations/LocationContent.tsx]: let dont not add translation  with prefix , i open new pr to remove the location.availability_status in codebase is not used now so i get update to remove it from codebase

**Comment by nihal467** [comment]
LGTM

**Comment by yadavshubham01** [comment]
@yash-learner @abhimanyurajeesh need review

**Review by abhimanyurajeesh — APPROVED** [review]

**Comment by abhimanyurajeesh** [comment]
@yadavshubham01 you have missed few files but letting it slide
