### PR TITLE
fixes the alignment issue of view detail button of encounter info card within the Beds card

### LINKED ISSUE #11888: BUG:Alignment issue  of view details button of encounter info card in Beds card
**Describe the bug**
The view detail button available in the encounter card does not align properly when the encounter info card is used inside the Beds card. This happens because the encounter card does not take up the full height of its parent container.

**To Reproduce**

1. Go to 'Encounters'
2. Click on 'locations'
3. Select  one of the  location 
4. See error in the beds card 

**Expected behavior**
The view detail button needs to align properly, just as it is aligned on the encounter  patient page. 

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Vikaspal8923**
## Proposed Changes

- Fixes #11888 
  Use the flex property in the bed card and ensure that the encounter info card takes up the full height  of its parent. 

@ohcnetwork/care-fe-code-reviewers
before change: 
Screenshot 2025-04-12 112819

after change :
image

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [X] Completion of QA in Mobile Devices
- [X] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
	- Updated the encounter card’s layout to ensure it consistently occupies the full height of its container.
	- Enhanced the facility’s bed card design by introducing a vertical stacking layout and applying full-height styling for a more balanced presentation.

### CODE REVIEW

File: src/components/Encounter/EncounterInfoCard.tsx [hunk 1]
```diff
@@ -62,7 +62,7 @@ export default function EncounterInfoCard(props: EncounterInfoCardProps) {
       data-status={encounter.status}
       key={props.encounter.id}
       className={cn(
-        "hover:shadow-lg transition-shadow group md:flex md:flex-col",
+        "hover:shadow-lg transition-shadow group md:flex md:flex-col h-full ",
```
Comment (rithviknishad) [inline src/components/Encounter/EncounterInfoCard.tsx]:
```suggestion
        "hover:shadow-lg transition-shadow group md:flex md:flex-col h-full",
```

File: src/pages/Facility/locations/LocationContent.tsx [hunk 2]
```diff
@@ -35,7 +35,7 @@ function BedCard({ location, facilityId }: BedCardProps) {
   return (
     <div
       className={cn(
-        "border rounded-lg overflow-hidden shadow-xs h-full",
+        "border rounded-lg overflow-hidden shadow-xs h-full flex flex-col ",
```
Comment (rithviknishad) [inline src/pages/Facility/locations/LocationContent.tsx]:
```suggestion
        "border rounded-lg overflow-hidden shadow-xs h-full flex flex-col",
```

**Review by rithviknishad — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
