### PR TITLE
Fix:Input area collapse with Save button in Drawings tab

### LINKED ISSUE #12374: Input Field and Save Button Overlap on Mobile View in Drawings Tab
**Describe the bug**
The input field for naming the drawing and the "Save" button are overlapping in Mobile View.

**To Reproduce**

1. Go to Encounters
2. Click on any Encounter
3. Go to Drawing tab
4. See the error

**Expected behavior**
The input field and the save button should be displayed clearly and separately, without overlapping.

**Screenshots**

Image

**Smartphone (please complete the following information):**

- Device: iphone 14
- Browser - Chrome

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by ashwinpraveengo**
## Proposed Changes

- Fixes #12374 
- Add flex-1 and min-w-0 to input for proper space distribution  
- Hide button text labels on mobile to save space while keeping icons
- Prevent button shrinking with shrink-0 clas

@ohcnetwork/care-fe-code-reviewers

**Mobile**
image

**Desktop**
image

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Improved the layout and spacing of the drawing editor header for better responsiveness and visual clarity.
  - Back and save buttons now display only icons on small screens, with text appearing on larger screens.
  - Drawing name input and title now scale better and handle long names with truncation.
  - Removed extra left margin from the search input container for a cleaner layout.

### CODE REVIEW

**Review by AdityaJ2305 — COMMENTED** [review]
Suggestion :- Should we move search bar to next row by maintaining back and save with text same as it is on end in first row ? 🤔 

cc: @rithviknishad @Jacobjeevan

File: src/components/Common/Drawings/ExcalidrawEditor.tsx [hunk 1]
```diff
@@ -155,31 +155,38 @@ export default function ExcalidrawEditor({
           </AlertDialogFooter>
         </AlertDialogContent>
       </AlertDialog>
-
-      <div className="flex flex-row items-center justify-between ml-0 mx-2 my-3">
-        <Button variant="ghost" size="sm" onClick={handleBack}>
+      <div className="flex flex-row items-center justify-between ml-0 mx-2 my-3 gap-2">
+        <Button
+          variant="ghost"
```
Comment (AdityaJ2305) [inline src/components/Common/Drawings/ExcalidrawEditor.tsx:160]:
```suggestion
          variant="white"
```

File: src/components/Common/Drawings/ExcalidrawEditor.tsx [hunk 2]
```diff
@@ -155,31 +155,38 @@ export default function ExcalidrawEditor({
...
+          size="sm"
+          onClick={handleBack}
+          className="shrink-0"
+        >
           <CareIcon icon="l-arrow-left" />
```
Comment (NikhilA8606) [inline src/components/Common/Drawings/ExcalidrawEditor.tsx]: Can we increase the arrow size? It's too small on mobile compared to the save button.

**Review by NikhilA8606 — CHANGES_REQUESTED** [review]
image
 Fix the responsiveness in each tab.

**Review by NikhilA8606 — CHANGES_REQUESTED** [review]
image
And also padding

**Comment by ashwinpraveengo** [comment]
> image And also padding

Fixed
image

**Review by sindhureddy-6 — CHANGES_REQUESTED** [review]
image
check here once

**Comment by ashwinpraveengo** [comment]
> image check here once

oh will fix it

**Review by Jacobjeevan — APPROVED** [review]
Buttons in Files Tab is being handled in a different PR 👍

**Comment by nihal467** [comment]
LGTM
