### PR TITLE
Fixed unresponsive bed delete dialog box

### LINKED ISSUE #3293: Bed Delete Dialog Unresponsive
image

### PR DESCRIPTION
**Pull request by naman114**
Fixes #3293 

- Fixed the unresponsive bed delete dialog box
- Improved the styling of the cancel button

image

### CODE REVIEW

File: src/Components/Facility/BedDeleteDialog.tsx [hunk 1]
```diff
@@ -34,28 +34,23 @@ const BedDeleteDialog = (
...
+          <p className="inline">Are you sure you want to delete bed</p>
+          <p className="inline mx-1 font-semibold capitalize break-words">
+            {name}
+          </p>
+          <p className="inline">?</p>
         </DialogContentText>
       </DialogContent>
       <DialogActions>
-        <Button onClick={handleCancel} color="primary">
+        <button onClick={handleCancel} className="btn btn-primary">
```
Comment (developedBySJ) [inline src/Components/Facility/BedDeleteDialog.tsx]: Make `cancel` button as default button
```suggestion
        <button onClick={handleCancel} className="btn btn-default">
```

**Review by developedBySJ — CHANGES_REQUESTED** [review]

**Review by patelaryan7751 — APPROVED** [review]

**Review by cp-Coder — APPROVED** [review]

**Review by developedBySJ — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]
