### PR TITLE
Fix Online Status Indicator in Organization Tab

### LINKED ISSUE #9726: User List in Organization Displays Incorrect Online Status for All Users
**Describe the bug**
The user list in the Organization section incorrectly displays all users as online.

**To Reproduce**

1. Go to 'Organization'
2. Click on 'Users'
3. See error where all users are shown as online

**Expected behavior**
The status of each user should be displayed correctly based on their actual online/offline status.

**Screenshots**
Image

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Firefox
- Version 133.0.3 (64-bit)

### PR DESCRIPTION
**Pull request by JavidSumra**
## Proposed Changes

- Fixes #9726 
- Updated the Logic to Display Online Status by Using `UserStatusIndicator` Component

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Release Notes

- **Internationalization**
	- Added support for multiple languages across various components
	- Updated user interface text to be dynamically translatable

- **User Management**
	- Improved user status display with new `UserStatusIndicator` component
	- Enhanced user role management interfaces

- **UI Improvements**
	- Refined user status representation
	- Updated labels and messages for better clarity

- **Localization**
	- Added new translation keys for user management and interface elements
	- Replaced hardcoded strings with translation function calls

### CODE REVIEW

**Review by bodhish — DISMISSED** [review]
Move all strings in this page to I18n

**Review by rithviknishad — APPROVED** [review]

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@JavidSumra ensure one's done in #9781 is also handled in this

File: src/pages/Organization/components/EditUserRoleSheet.tsx [hunk 1]
```diff
@@ -144,29 +147,31 @@ export default function EditUserRoleSheet({
...
+                <UserStatusIndicator user={userRole.user} />
               </div>
             </div>
           </div>
 
           <div className="space-y-2">
-            <label className="text-sm font-medium">Select New Role</label>
+            <label className="text-sm font-medium">
+              {t("select_new_role")}
+            </label>
```
Comment (rithviknishad) [inline src/pages/Organization/components/EditUserRoleSheet.tsx]: lets use shadcn's label instead

File: src/components/Users/UserListAndCard.tsx [hunk 2]
```diff
@@ -111,37 +97,45 @@ export const UserStatusIndicator = ({
...
+              const diffInHours = dayjs().diff(user.last_login, "hours");
+              const diffInDays = dayjs().diff(user.last_login, "days");
+
+              if (diffInMinutes < 60) {
+                return `${diffInMinutes} ${t("minutes_ago")}`;
+              } else if (diffInHours < 24) {
+                return `${diffInHours} ${t("hour")}${diffInHours > 1 ? "s" : ""} ${t("ago")}`;
+              } else {
+                return `${diffInDays} ${t("days") + t("ago")}`;
+              }
```
Comment (rithviknishad) [inline src/components/Users/UserListAndCard.tsx]: we already have a util called `relativeTime` that does this. re-use it instead of reinventing it

File: public/locale/en.json [hunk 3]
```diff
@@ -1022,7 +1026,7 @@
   "home_facility_cleared_success": "Home Facility cleared successfully",
   "home_facility_updated_error": "Error while updating Home Facility",
   "home_facility_updated_success": "Home Facility updated successfully",
-  "hours": "hours",
+  "hour": "hour",
```
Comment (rithviknishad) [inline public/locale/en.json]: follow:

https://www.i18next.com/translation-function/plurals#singular-plural

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

File: src/components/Users/UserListAndCard.tsx [hunk 4]
```diff
@@ -111,37 +96,32 @@ export const UserStatusIndicator = ({
...
+      {isUserOnline(user) || isAuthUser ? (
+        <Badge variant="secondary" className="bg-green-100 whitespace-nowrap">
+          <span className="inline-block h-2 w-2 shrink-0 rounded-full bg-green-500 mr-2" />
+          <span className="text-xs text-green-700">{t("online")}</span>
+        </Badge>
+      ) : user.last_login ? (
+        <Badge variant="secondary" className="bg-yellow-100 whitespace-nowrap">
+          <span className="inline-block h-2 w-2 shrink-0 rounded-full bg-yellow-500 mr-2" />
+          <span className="text-xs text-yellow-700">
+            {t("last_seen")} {relativeTime(user.last_login)}
```
Comment (Jacobjeevan) [inline src/components/Users/UserListAndCard.tsx]: Hmm, I don't think we need this last seen 🤔  The time alone is intuitive enough imo. Plus, it stretches the badge too much.

image

**Review by Jacobjeevan — APPROVED** [review]
~~Conditionally approving.~~

LGTM

File: src/components/Users/UserListAndCard.tsx (hunk 4 above)
Comment (JavidSumra) [reply src/components/Users/UserListAndCard.tsx]: So shall I remove it?

Comment (Jacobjeevan) [reply src/components/Users/UserListAndCard.tsx]: yes

**Comment by nihal467** [comment]
LGTM
