### PR TITLE
Fix patient name in transfer success notification

### LINKED ISSUE #6811: Patient transferred notification shows UUID instead of patient name
**Describe the bug**
Patient transferred notification shows UUID instead of patient name

**To Reproduce**

1. Add patient that already had a consultation
2. Transfer the patient to new facility

**Expected behavior**
Show name in place of UUID

**Screenshots**
image

### PR DESCRIPTION
**Pull request by konavivekramakrishna**
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 0016206</samp>

This pull request enhances the user experience and readability of the consultation page URL and the transfer patient dialog. It uses the patient name instead of the id in the URL and shows the patient name when transferring.

## Proposed Changes

- Fixes #6811 
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 0016206</samp>

* Add a variable `patientName` to store the patient name from the form state ([link](https://github.com/coronasafe/care_fe/pull/6829/files?diff=unified&w=0#diff-12a212ab8b86af3a4ce6dd25b6a304909a46ad8156446f1c065f88ee92de0242R128-R130))
* Use `patientName` instead of patient id in the URL when navigating to the consultation page after transferring the patient ([link](https://github.com/coronasafe/care_fe/pull/6829/files?diff=unified&w=0#diff-12a212ab8b86af3a4ce6dd25b6a304909a46ad8156446f1c065f88ee92de0242L135-R138))

### CODE REVIEW

File: src/Components/Facility/TransferPatientDialog.tsx [hunk 1]
```diff
@@ -125,14 +125,17 @@ const TransferPatientDialog = (props: Props) => {
...
+          patientOptions.find((p) => p.id === state.form.patient)?.text || "";
         Notification.Success({
           msg: `Patient ${res.data.patient} transferred successfully`,
         });
         const newFacilityId =
           res.data && res.data.facility_object && res.data.facility_object.id;
         if (newFacilityId) {
           navigate(
-            `/facility/${newFacilityId}/patient/${res.data.patient}/consultation`
+            `/facility/${newFacilityId}/patient/${patientName}/consultation`
```
Comment (rithviknishad) [inline src/Components/Facility/TransferPatientDialog.tsx]: Why pass patient's name to the URL's path param??

Comment (vivramkrishna) [reply src/Components/Facility/TransferPatientDialog.tsx]: 😅 my bad, while switching branch i made a mistake

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
