### PR TITLE
Move consents to tab

### LINKED ISSUE #11730: Move consent to tab under encounter
- [x] Rename Link Consent to Add Consent
- [x] In consent card - Rename Approved -> Permitted
- [x] In the Sheet while listing existing Consents, swap file name and category.
- [x] Fix the green border for search bar while in focus
- [x] Add notes for consent, display in the card itself while listing
- [x] Add pagination

----

[amjithtitus09](https://github.com/amjithtitus09) commented [last week](https://github.com/ohcnetwork/care_fe/pull/11740#issuecomment-2782959112) • 
@yash-learner Let's create a separate tab for Consents in an Encounter. A list screen with onClick to open the details of a consent, while being url accessible. Convert to Draft for the time being.

### LINKED ISSUE #12042: Verification details are not being populated
## Describe the bug
Verification details are being incorrectly sent as part of the consent creation payload in `LinkConsentDialog.tsx` instead of using the dedicated verification endpoint available in the API.

## To Reproduce
1. Go to a patient encounter page
2. Click on "Link Consent" button
3. Fill in the consent form details
4. Select a verification type
5. Submit the form
6. Inspect network requests in developer tools

## Expected behavior
1. The consent creation should happen via the `/api/v1/patient/{patientId}/consent/` endpoint
2. Verification details should be submitted separately through the verification-specific endpoint
3. The two resources should be properly linked

## Actual behavior
All verification details are being sent directly in the consent creation payload, which doesn't match the API's expected separation of concerns, https://careapi.ohc.network/swagger/#/consent

## Code analysis
In `LinkConsentDialog.tsx`, verification details are being included directly in the consent creation mutation:

```typescript
createConsent({
  // Other consent fields...
  verification_details: [
    {
      verified: true,
      verified_by: verifier,
      verification_date: new Date().toISOString(),
      verification_type: values.verification_type,
    },
  ],
});
```

## Potential solution
Modify the component to:
1. First create the consent record
2. Then use the dedicated verification endpoint to attach verification details
3. Update the success handler to manage both API calls properly

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by yash-learner**
## Proposed Changes

- Fixes #11730 
-  Move consents to tab
-  Make file-upload inline in form without a dialog
-  Add a consent detail.
   -  Display
   - Attach supporting documents
   - Edit
- Add pagination
- Clean up code related to consent verifcation 
- Move consent add from dialoag to a sheet

_Outdated changelog video_

https://github.com/user-attachments/assets/e47f40f5-6993-4f3a-ae58-3ebdc3640650

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Added a new Consents tab in encounter pages for managing patient consents with search and pagination.
  - Introduced a detailed consent view page with editing, file attachment management, and note display.
  - Launched a consent form sheet component for adding and editing consents with validation and localized UI.
  - Enabled uploading, previewing, and downloading supporting documents linked to consents.
  - Added a route for direct access to individual consent detail pages.

- **Improvements**
  - Enhanced English localization with expanded consent-related terminology, instructions, and error messages.
  - Consent cards now display richer information including decision, status, validity period, and attachments.
  - Added optional note field to consents for additional context.
  - Updated consent verification API to support verification status and notes.

- **Removals**
  - Removed previous consent management components and dialogs, consolidating functionality into new components.
  - Removed consent period start and end date localization keys.
  - Removed consent management UI from patient info card.

- **Bug Fixes**
  - Clarified consent-related UI messages and instructions for better user guidance.

### CODE REVIEW

**Comment by yash-learner** [comment]
@coderabbitai review

File: src/pages/Encounters/tabs/EncounterConsentsTab.tsx [hunk 1]
```diff
@@ -0,0 +1,261 @@
...
+  const { t } = useTranslation();
+  const navigate = useNavigate();
+  const { facilityId } = usePathParams("/facility/:facilityId/*") ?? {};
+  const encounterId = consent.encounter;
+  const consentId = consent.id;
+
+  const primaryAttachment = consent.source_attachments[0];
+  const totalAttachments = consent.source_attachments.length;
+
+  return (
```
[the remark this answers is not in the document]
Comment (yash-learner) [reply src/pages/Encounters/tabs/EncounterConsentsTab.tsx:65]: @coderabbitai, I think it is not necessary as BE API always returns [ ]

what do you think ?

File: src/pages/Encounters/ConsentDetail.tsx [hunk 2]
```diff
@@ -0,0 +1,376 @@
...
+                  </h3>
+                  <div className="flex rounded-md border border-gray-200">
+                    <Label
+                      htmlFor="file_upload_consent"
+                      className="cursor-pointer flex items-center px-4 py-2 rounded-l-md hover:bg-gray-50 transition-colors"
+                    >
+                      <PlusCircle className="size-4 mr-2" />
+                      {t("select")} {t("files")}
+                      {fileUpload.Input({ className: "hidden" })}
+                    </Label>
```
[the remark this answers is not in the document]
Comment (yash-learner) [reply src/pages/Encounters/ConsentDetail.tsx]: @coderabbitai 

I think it is not required

File: src/components/Consent/ConsentFormSheet.tsx [hunk 3]
```diff
@@ -0,0 +1,425 @@
...
+  })
+  .superRefine((data, ctx) => {
+    if (data.period.end && data.date > data.period.end) {
+      ctx.addIssue({
+        code: z.ZodIssueCode.custom,
+        message: t("consent_after_end"),
+        path: ["date"],
+      });
+    }
+  });
```
[the remark this answers is not in the document]
Comment (yash-learner) [reply src/components/Consent/ConsentFormSheet.tsx]: Thanks, @coderabbitai 

Fixed it

**Comment by yash-learner** [comment]
@nihal467 can you test this PR?

**Comment by nihal467** [comment]
Major Bug

image

- add the file upload with the create consent slideover
- file upload will be a optional thing
- post saving, they shouldn't be redirected to the view details page

image

- in the edit consent form, only the status and note should be allowed to be edited, hide the rest  of the fields marked cross in the SS

image

- Currently, the consent search functionality only supports searching by the name of the first uploaded file. However, consents can be created without any files or with multiple files. In such cases, the search becomes unreliable—consents without files are not searchable at all, and for those with multiple files, only the first file's name can be used for searching.

Minor Bug

image

- When we upload multiple files back-to-back to a single consent from the details page, an error message appears in the pop-up as shown in the screenshot. Sometimes, the file upload or file selection itself also fails.

image

- Remove the green border when the note is not in focus

**Comment by yash-learner** [comment]
@nihal467 Thanks for testing 

> Major Bug, add the file upload with the create consent slideover

Actually, it's not a bug, that was a deliberate change made after discussion on [slack](https://rebuildearth.slack.com/archives/C06KGMUAB0V/p1745269867137029?thread_ts=1744207192.430929&cid=C06KGMUAB0V)

> add the file upload with the create consent slideover & file upload will be a optional thing

Okay, will bring it back there

> post saving, they shouldn't be redirected to the view details page

Okay, previously it was done because we kept it separate, will fix it 

> in the edit consent form, only the status and note should be visible allow to edit, hide rest on field

Okay 👍

> Currently, the consent search functionality only supports searching by the name of the first uploaded file. However, consents can be created without any files or with multiple files.

@nihal467 search works when consent has multiple files and yes, currently search does not work when no files attached because consent does not have any title, the search is file-based and will fix that to show consents that don't have files attached.


> When we upload multiple files back-to-back to a single consent from the details page, an error message appears in the pop-up as shown in the screenshot. Sometimes, the file upload or file selection itself also fails.

I guess the issue with the file upload component, this issue is already present on `care.ohc.network`, will look into it and fix it.

image

> Remove the green border when the note is not in focus

👍

---

cc: @amjithtitus09

**Comment by nihal467** [comment]
@yash-learner the edit consent fields are still not hidden, once all the things are solved, do change the label to needs testing

File: src/components/Consent/ConsentFormSheet.tsx [hunk 4]
```diff
@@ -0,0 +1,578 @@
...
+              name="note"
+              render={({ field }) => (
+                <FormItem>
+                  <FormLabel>{t("note")}</FormLabel>
+                  <FormControl>
+                    <textarea
+                      className="w-full field-sizing-content focus:outline-none focus:ring-1 focus:ring-primary-500 focus:border-primary-500 rounded-md"
+                      rows={3}
+                      {...field}
+                    />
```
[the remark this answers is not in the document]
Comment (yash-learner) [reply src/components/Consent/ConsentFormSheet.tsx:495]: @coderabbitai

Previously it had a border, I just removed it.

**Comment by yash-learner** [comment]
@nihal467 I just realised that the search we are doing in for consent is client-side 😁

https://github.com/ohcnetwork/care_fe/blob/267e73b95c9c3cfacc1d1e298ee7203a210a413e/src/components/Consent/ConsentSheet.tsx#L87

So it is unreliable across paginated pages, and we do not have a backend support for filtering consents based on files attached 

---

I will get it as a follow-up PR, after backend support, so this would fix no files attached as well

cc: @amjithtitus09

**Comment by nihal467** [comment]
image

position the edit button properly

**Comment by nihal467** [comment]
LGTM

File: src/pages/Encounters/tabs/EncounterConsentsTab.tsx [hunk 5]
```diff
@@ -0,0 +1,248 @@
...
+import consentApi from "@/types/consent/consentApi";
+import { Encounter } from "@/types/emr/encounter";
+
+const CONSENTS_PER_PAGE = 12;
+
+export const EmptyState = () => {
+  const { t } = useTranslation();
+
+  return (
+    <div className="flex min-h-[200px] flex-col items-center justify-center gap-4 p-8 text-center">
```
Comment (rithviknishad) [inline src/pages/Encounters/tabs/EncounterConsentsTab.tsx]: use rem values or nearest tailwind's standard values. arbitrary pixel values doesn't play well with different DPI settings (such as display zoom)

File: src/pages/Encounters/tabs/EncounterConsentsTab.tsx [hunk 6]
```diff
@@ -0,0 +1,248 @@
...
+
+  if (isLoading) {
+    return <Loading />;
+  }
+
+  return (
+    <div className="py-4">
+      <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
+        <div className="relative flex-1 max-w-md">
+          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground size-4" />
```
Comment (rithviknishad) [inline src/pages/Encounters/tabs/EncounterConsentsTab.tsx]: is this even a valid class as per our tailwind config? 🤔 

```suggestion
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 size-4" />
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Encounters/tabs/EncounterConsentsTab.tsx (hunk 6 above)
Comment (yash-learner) [reply src/pages/Encounters/tabs/EncounterConsentsTab.tsx]: @rithviknishad 

> is this even a valid class as per our tailwind config? 🤔

I think no 

Will fix it

---

I just migrated that from https://github.com/ohcnetwork/care_fe/pull/12033/files#diff-7ea8fd0cf8f3235eda2a3a0da1d267386efc476e13807ffc1aa024d135bec4f5 (sheet to tab)

----

I see we are using it at multiple places 

image

---

is it coming from shadcn for shadcn components

Comment (rithviknishad) [reply src/pages/Encounters/tabs/EncounterConsentsTab.tsx]: > is it coming from shadcn for shadcn components

it is coming from some AI written code that doesn't know what it's doing!

Comment (rithviknishad) [reply src/pages/Encounters/tabs/EncounterConsentsTab.tsx]: @coderabbitai create an issue to clean other usages as well

AI creating mess, AI creating issues to clean up AI's mess :)

**Review by rithviknishad — APPROVED** [review]

**Comment by yash-learner** [comment]
@rithviknishad, I just added the `Tested` label back as these are tiny fixes and do not change any major behaviour

https://github.com/ohcnetwork/care_fe/pull/12033/commits/51cbbf667e8c27854d7dc8f78b58e2aaa0ad488a

is that okay ?

**Comment by yash-learner** [comment]
> @nihal467 I just realised that the search we are doing in for consent is client-side 😁
> 
> https://github.com/ohcnetwork/care_fe/blob/267e73b95c9c3cfacc1d1e298ee7203a210a413e/src/components/Consent/ConsentSheet.tsx#L87
> 
> So it is unreliable across paginated pages, and we do not have a backend support for filtering consents based on files attached
> 
> I will get it as a follow-up PR, after backend support, so this would fix no files attached as well
> 
> cc: @amjithtitus09


@nihal467 https://github.com/ohcnetwork/care/pull/3032#issuecomment-2871890393
