### PR TITLE
Fix cancel button in update encounter form

### LINKED ISSUE #9771: Cancel button not working in update encounter form
Cancel button not working in update encounter form

**Expected behaviour:**

On clicking cancel button it should navigate back to previous page

Expected

https://github.com/user-attachments/assets/3201ce0b-5814-4d24-aa1e-8536ef3a3dfb

### PR DESCRIPTION
**Pull request by Mahendar0701**
## Proposed Changes

- Fixes #9771 
- Change 1
- Change 2
- More?

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Localization**
	- Added new translations for questionnaire-related messages
	- Implemented localized error handling for questionnaire loading
	- Updated button labels with internationalization support

- **User Experience**
	- Improved error messaging for questionnaire interactions
	- Added more descriptive feedback when accessing non-existent questionnaires

### CODE REVIEW

File: src/components/Questionnaire/QuestionnaireForm.tsx [hunk 1]
```diff
@@ -107,10 +108,8 @@ export function QuestionnaireForm({
     console.log(questionnaireError);
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionnaireForm.tsx]: Remove the console.log here.

LGTM otherwise.

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
