### PR TITLE
Patients age is correctly defined

### LINKED ISSUE #9640: Patient age format is not working properly
Image

verifypatient.tsx (Line No: 95) , the format patient date is not working properly for patient data with age only,

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Proposed Changes

- Fixes #9640 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved patient age formatting by providing a direct return for known ages.
	- Enhanced display of patient age information for better clarity and conciseness.

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]
nice find!

File: src/Utils/utils.ts [hunk 1]
```diff
@@ -415,9 +414,7 @@ export const formatPatientAge = (
   // Skip representing as no. of months/days if we don't know the date of birth
   // since it would anyways be inaccurate.
   if (!obj.date_of_birth) {
-    return abbreviated
-      ? `Born ${obj.year_of_birth}`
-      : `Born on ${obj.year_of_birth}`;
+    return abbreviated ? `${obj.age} Y` : `Born on ${obj.year_of_birth}`;
```
Comment (rithviknishad) [inline src/Utils/utils.ts]: but if `year_of_birth` is undefined, and `abbreviated` is set to false, this would still have the same issue right?

instead let's check if `age` is null or not and show age if available, else fallback to year of birth

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Utils/utils.ts (hunk 1 above)
Comment (NikhilA8606) [reply src/Utils/utils.ts]: image
Is it correct?

Comment (rithviknishad) [reply src/Utils/utils.ts]: no, let's keep old year of birth if age is not present (same as before). if backend gives us age, let's show age directly before reaching there.

```suggestion
    if (age != null) return `${obj.age} Y`;
    return abbreviated ? `Born ${obj.year_of_birth}` : `Born on ${obj.year_of_birth}`;
```

Comment (NikhilA8606) [reply src/Utils/utils.ts]: image

Is it what you meant?

Comment (rithviknishad) [reply src/Utils/utils.ts]: yup! this one's better!

**Review by rithviknishad — APPROVED** [review]
