### PR TITLE
Fix : Refresh Button Refreshes Entire Button in Valuset (Questionnaire Dashboard)

### LINKED ISSUE #11935: Refresh Button Refreshes Entire Button
**Describe the bug**
In Questionnaire valueset, When clicking the refresh button , the entire button is refreshing.

**To Reproduce**

1. Go to 'Questionnaire Dashboard'
2. Go to 'Valuesets' Tab -> "Edit".
3. Click on 'refresh' button.
4. See error , Observe that all refresh buttons show loading state

https://github.com/user-attachments/assets/9038335e-de57-4d86-8523-d89c8dbbccc4

**Expected behavior**
Only the clicked refresh button should show the loading state.

**Expected Output**

https://github.com/user-attachments/assets/5ac5b5dc-9a59-44e8-a245-8bb26a8db87b

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #11935 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

https://github.com/user-attachments/assets/11fb8bb5-5757-4de5-869c-d69893f9b135

- [ ] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Improved code verification with clearer user feedback and dynamic button states.
  - Added automatic reset of verification status when code input changes.
- **Style**
  - Enhanced button styling to reflect verification status with dynamic icons and effects.

### CODE REVIEW

File: src/components/ValueSet/ValueSetForm.tsx [hunk 1]
```diff
@@ -161,15 +178,25 @@ function ConceptFields({
...
-            onClick={() => handleVerify(index)}
-            disabled={lookupMutation.isPending}
-          >
-            <UpdateIcon className="size-4" />
-          </Button>
+          {parentForm.getValues(
+            `compose.${type}.${nestIndex}.concept.${index}.isVerified` as any,
+          ) ? (
+            <span title="Verified">
+              <CareIcon icon="l-check" className="size-4 text-green-500" />
```
Comment (Jacobjeevan) [inline src/components/ValueSet/ValueSetForm.tsx]: adjust the size and the positioning (center?) of the icon here. Notice how due to the size difference, the input box moves rightward.

Also adjust the title - valuesets instead of questionnaire.

Comment (Jacobjeevan) [reply src/components/ValueSet/ValueSetForm.tsx]: Go ahead and adjust the mobile responsiveness for rules (try to maintain current design for desktops though).

**Review by Jacobjeevan — DISMISSED** [review]

**Comment by Jeffrin2005** [comment]
https://github.com/user-attachments/assets/21591a49-426c-4096-8616-0904d9562668

**Comment by Jacobjeevan** [comment]
Do a self review; still missing few things from previous feedback @Jeffrin2005

**Comment by Jeffrin2005** [comment]
@Jacobjeevan 
Now everything is good. The tick mark symbol is perfectly in center while marking it. 
for desktop,

https://github.com/user-attachments/assets/51e12543-8519-4c08-abc8-15a94bd2afb7

Mobile view, 



https://github.com/user-attachments/assets/0f5d727a-ca12-4dd3-8d38-401f03a82234

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan Now everything is good. The tick mark symbol is perfectly in center while marking it. for desktop,
> Error22.mp4
> 
> Mobile view,
> error222.mp4

Desktop is fine now, but does the mobile view look right to you? Is that readable?

**Comment by Jeffrin2005** [comment]
@Jacobjeevan Updated the changes in new file ( removed old file - for fixing merge conflicts ) . Now the mobile view and desktop is working fine .
Just for clarification - in the video for mobile view , the resolution is less than the usual mobile screens. Overall everything is good and compared with orginal website and care preview .

**Comment by Jeffrin2005** [comment]
@rithviknishad  @Jacobjeevan Updated the changes in new file ( removed old file - for fixing merge conflicts ) . Now the mobile view and desktop is working fine 
For clarification - in the video for mobile view , the resolution is less than the usual mobile screens. Overall everything is good and compared with orginal website and care preview .

File: src/components/ValueSet/CodingField.tsx [hunk 2]
```diff
@@ -27,19 +28,21 @@ export const CodingField = ({
   className,
 }: CodingFieldProps) => {
   const { t } = useTranslation();
-
+  const [isVerified, setIsVerified] = useState(false);
```
Comment (rithviknishad) [inline src/components/ValueSet/CodingField.tsx]: you don't need a state for this, you can use the `isSuccess` attribute from `useMutation`'s return value

```suggestion
```

File: src/components/ValueSet/CodingField.tsx [hunk 3]
```diff
@@ -27,19 +28,21 @@ export const CodingField = ({
...
   const lookupMutation = useMutation({
```
Comment (rithviknishad) [inline src/components/ValueSet/CodingField.tsx]:
```suggestion
  const { mutate: lookup, isSuccess: isVerified, isPending: isLookupPending, reset: resetVerified } = useMutation({
```

File: src/components/ValueSet/CodingField.tsx [hunk 4]
```diff
@@ -55,6 +58,10 @@ export const CodingField = ({
     lookupMutation.mutate({ system, code });
   };
 
+  const handleCodeChange = () => {
+    setIsVerified(false);
+    form.setValue(`${name}.display`, "", { shouldValidate: true });
+  };
```
Comment (rithviknishad) [inline src/components/ValueSet/CodingField.tsx]:
```suggestion
  const handleCodeChange = () => {
    resetVerified();
    form.setValue(`${name}.display`, "", { shouldValidate: true });
  };
```

File: src/components/ValueSet/CodingField.tsx [hunk 5]
```diff
@@ -83,7 +91,7 @@ export const CodingField = ({
               <Input
                 {...field}
                 placeholder={t("unverified")}
-                className={!field.value ? "text-gray-500" : undefined}
+                className={cn(!field.value ? "text-gray-500" : undefined)}
```
Comment (rithviknishad) [inline src/components/ValueSet/CodingField.tsx]: using `cn` is nice for conditional classes, but `cn` comes with a slight performance overhead. It's good practice to skip using for places where that's absolutely not needed.

`cn` is best used when you have multiple classes that could potentially need a smart way to resolve which classes would get preference when similar classes are present from multiple conditions.

I'd always avoid using it when it's only if multiple sets of classes are being applied. for example `cn("default classes", conditional classes)`

```suggestion
                className={!field.value && "text-gray-500"}
```

File: src/components/ValueSet/CodingField.tsx [hunk 6]
```diff
@@ -96,8 +104,22 @@ export const CodingField = ({
         size="icon"
         onClick={handleVerify}
         disabled={lookupMutation.isPending}
+        className={cn(
+          isVerified
+            ? "bg-transparent border-none shadow-none hover:bg-transparent hover:border-none hover:shadow-none"
+            : "hover:border-gray-400 hover:bg-gray-100",
+        )}
```
Comment (rithviknishad) [inline src/components/ValueSet/CodingField.tsx]:
```suggestion
        className={isVerified
            ? "bg-transparent border-none shadow-none hover:bg-transparent hover:border-none hover:shadow-none"
            : "hover:border-gray-400 hover:bg-gray-100"}
```

File: src/components/ValueSet/CodingField.tsx [hunk 7]
```diff
@@ -96,8 +104,22 @@ export const CodingField = ({
...
       >
-        <UpdateIcon className="size-4" />
+        {isVerified ? (
+          <CheckIcon className="size-4 text-green-500 transition-colors duration-300" />
+        ) : (
+          <UpdateIcon
+            className={cn(
+              "size-4 transition-colors duration-300",
```
Comment (rithviknishad) [inline src/components/ValueSet/CodingField.tsx]: is color changing here? 🤔

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
Nice work!
