### PR TITLE
Made the cards clickable

### LINKED ISSUE #13209: Bug: Service cards are not clickable outside of the 'View Details' button in the Services Page.
**Description**
The cards in the "Services" section are not clickable. This prevents users from easily navigating to the service details page and breaks the intended interaction pattern.

Image

**Steps to Reproduce**

- Navigate to the "Services" page.

- Locate any of the service cards (e.g., "Test Pharmacy," "Laboratory Service").

- Attempt to click anywhere on the card's background or text (other than the 'View Details' button).

- Observe that no action occurs.

**Expected Behaviour**
The entire service card should be a clickable area. When a user clicks anywhere on the card, it should navigate them to the details page for that specific service. The 'View Details' button should serve as a secondary, redundant clickable area.

**Actual Behavior**
Only the 'View Details' button is a clickable element. The rest of the card's area does not respond to clicks.

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Akhileswaran-K-R**
## Proposed Changes

Fixes #13209 
- Wrapped service and health card with `<Link>` component 
- Replaced `<BackButton>` component
- Replaced buttons inside Link with div

https://github.com/user-attachments/assets/8fd0163f-1d8f-4590-aeed-395c991d99d4

https://github.com/user-attachments/assets/bf7cc5ea-6988-4623-a638-3a808ee42db5

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

* **Refactor**
  * Converted programmatic navigation to declarative links so whole service cards and location rows are clickable.
  * Replaced ad-hoc navigation buttons with a consistent BackButton in headers and not-found flows.
  * Retained inline action labels and arrow indicators while improving keyboard focus and predictable navigation behavior.
  * Visual layout unchanged; navigation is smoother and more intuitive.

### CODE REVIEW

File: src/pages/Facility/services/HealthcareServiceShow.tsx
Comment (SiddanthNayak) [inline src/pages/Facility/services/HealthcareServiceShow.tsx]: Since you are working on this file, use the `<BackButton>` component for `back_to_abc` buttons

Comment (SiddanthNayak) [inline src/pages/Facility/services/HealthcareServiceShow.tsx:1]: Before:

Image

After:

Image

Margin between Cards that was previously there is gone. Please fix that

File: src/pages/Facility/services/HealthcareServiceShow.tsx [hunk 1]
```diff
@@ -55,37 +55,38 @@ function LocationCard({
...
-          <div className="min-w-0 flex-1">
-            <h3 className="font-semibold truncate text-gray-900 text-base">
-              {location.name}
-            </h3>
-            <p className="mt-0.5 text-xs text-gray-500 line-clamp-1">
-              {location.description}
-            </p>
+    <Link href={link} basePath="/">
+      <Card className="transition-all duration-200 hover:border-primary/50 hover:shadow-sm rounded-md">
+        <CardContent className="flex items-start gap-3 py-3 px-4">
```
Comment (SiddanthNayak) [inline src/pages/Facility/services/HealthcareServiceShow.tsx]: Instead of wrapping entire elements within `<Link ../>` we can just use navigate like `<Card onClick={() => navigate(link)}`

cc: @rithviknishad

Comment (rithviknishad) [reply src/pages/Facility/services/HealthcareServiceShow.tsx]: no, this would not allow right clicks on the element to do things like open in new tab

**Review by abhimanyurajeesh — CHANGES_REQUESTED** [review]
Make the. requested changes

**Comment by nihal467** [comment]
@Akhileswaran-K-R the LGTM, the PR checklist has been updated. Add the playwright test for the PR to verify the functionality of your fix
