### PR TITLE
[FIXED] Modified Notification related to Patient Log update successfully

### LINKED ISSUE #7619: Modify the Notification related to Patient Log update
**Describe the bug**

When we are creating normal log updates or critical care log updates, most of the notifications are "Consultation update created successfully" , which is generic and not specific to user actions.

**To Reproduce**

1. Go to patient consultation page
2. create a log update
3. See error

**Expected behavior**

All log update-related notification should be action specific for example , if a normal log update got created, it should be giving a notification "Normal Log update created successfully"

**Screenshots**

image

### PR DESCRIPTION
**Pull request by r-nikhilkumar**
- Fixes #7619
- All log update-related notification should be action specific for example , if a normal log update got created, it should be giving a notification "Normal Log update created successfully"✅

image

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

File: src/Components/Patient/DailyRounds.tsx [hunk 1]
```diff
@@ -294,9 +294,14 @@ export const DailyRounds = (props: any) => {
         setIsLoading(false);
 
         if (obj) {
+          const roundsType = obj.rounds_type
+            ? obj.rounds_type.charAt(0).toUpperCase() +
+              obj.rounds_type.slice(1).toLowerCase() +
```
Comment (rithviknishad) [inline src/Components/Patient/DailyRounds.tsx]: Not a very readable code. It'd be cleaner if done something like:

```jsx
Notification.Sucess({
  msg: `Updated ${obj.rounds_type === "CRITICAL" ? "Critical" : "Normal"} log update succesfully.`
})
```

File: src/Components/Patient/DailyRounds.tsx [hunk 2]
```diff
@@ -315,10 +320,14 @@ export const DailyRounds = (props: any) => {
         });
         setIsLoading(false);
         if (obj) {
+          const roundsType = obj.rounds_type
+            ? obj.rounds_type.charAt(0).toUpperCase() +
+              obj.rounds_type.slice(1).toLowerCase() +
+              " Log"
+            : "Consultation";
```
Comment (rithviknishad) [inline src/Components/Patient/DailyRounds.tsx]: Here too

**Review by rithviknishad — CHANGES_REQUESTED** [review]
LGTM, just minor suggestions

File: src/Components/Patient/DailyRounds.tsx (hunk 1 above)
Comment (r-nikhilkumar) [reply src/Components/Patient/DailyRounds.tsx]: image
here its saying this comparison is unintentional and critical is not even exist there, there's ventilator type instead of critical, also there are other round types available like telemedicine and automated, I can't use this directly , otherwise if automated type would be created then the relevent notification wouldn't be shown there

**Comment by nihal467** [comment]
@r-nikhilkumar can you please make the requested changes ASAP

**Comment by r-nikhilkumar** [comment]
@nihal467 okay

File: src/Components/Patient/DailyRounds.tsx (hunk 1 above)
Comment (rithviknishad) [reply src/Components/Patient/DailyRounds.tsx]: Then you can use text transforms.

Maybe: https://tailwindcss.com/docs/text-transform#transforming-text
Or some utility function from loadash.

Comment (r-nikhilkumar) [reply src/Components/Patient/DailyRounds.tsx]: done

File: src/Components/Patient/DailyRounds.tsx (hunk 2 above)
Comment (r-nikhilkumar) [reply src/Components/Patient/DailyRounds.tsx]: done

**Comment by r-nikhilkumar** [comment]
@rithviknishad done, now you can finalize it

**Review by rithviknishad — COMMENTED** [review]
LGTM

**Review by rithviknishad — APPROVED** [review]

**Comment by rithviknishad** [comment]
@r-nikhilkumar lint checks and cypress tests failing

**Comment by r-nikhilkumar** [comment]
@rithviknishad okay I'm resolving cypress test, lint is done

**Comment by r-nikhilkumar** [comment]
@rithviknishad why this error comming in cypress? this is something related to cy.contains(), can you plz guide
image

**Review by Ashesh3 — APPROVED** [review]

**Comment by rithviknishad** [comment]
> why this error comming in cypress? this is something related to cy.contains(), can you plz guide

The cypress test needs to be modified. Notification message is being verified in cypress. So the updated notification message needs to be used in cypress test.

**Comment by r-nikhilkumar** [comment]
@rithviknishad I modified it already but this is showing another error, kindly check, I already modified and 2 of the 3 test cases are passing bcz I modified notification, please check

**Comment by r-nikhilkumar** [comment]
@rithviknishad all test passed, now you can finalize this PR

**Comment by nihal467** [comment]
@r-nikhilkumar 
image

- [ ] When we create a critical care log update, it is shown as a "Ventilator" log update created successfully, replace the ventilator with "Critical Care" in the notification

**Comment by nihal467** [comment]
LGTM

**Comment by nihal467** [comment]
LGTM

**Comment by nihal467** [comment]
LGTM

**Review by nihal467 — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]
