### PR TITLE
Disable button when loading on Configure Assets page

### LINKED ISSUE #4666: Configure Assets page button bugs
**Describe the bug**
The `Set Configuration` and `Add Preset` buttons should be disabled when loading and after adding, the value of Bed should be cleared

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/fe5f5b3c-16ba-48cd-b62b-a24f58f64190/assets/c6f84485-a78f-4740-9871-8b3dec1c792f/configure
2. Add a preset
3. See error

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #4666 
Disabled buttons when loading
image

Clear the value of the `Bed` field after Preset is added
image

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

File: src/Components/Assets/AssetType/ONVIFCamera.tsx [hunk 1]
```diff
@@ -111,10 +116,12 @@ const ONVIFCamera = (props: ONVIFCameraProps) => {
           )
         )
       );
+      setLoadingAddPreset(false);
       if (res?.status === 201) {
         Notification.Success({
           msg: "Preset Added Successfully",
         });
+        setBed({});
```
Comment (khavinshankar) [inline src/Components/Assets/AssetType/ONVIFCamera.tsx:129]: @Pranshu1902 why are we resetting the bed here?

Comment (Pranshu1902) [reply src/Components/Assets/AssetType/ONVIFCamera.tsx:129]: @khavinshankar So that after adding a Preset, the `Bed` input field of the form is cleared just like the `Preset Name` field.
image

**Review by khavinshankar — APPROVED** [review]
