### PR TITLE
fixed address display responsiveness in patient detail page

### LINKED ISSUE #12015: BUG:Ui breakout  in the patient detail page  when permanent address is too long
**Describe the bug**
If the permanent address becomes too long, it will lead to UI breakout on screens between  640 px and 748 px.

**To Reproduce**

1. Go to 'patient detail page '
2. make permanent address too long and see error

**Expected behavior**
it should  need to be responsive properly

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Vikaspal8923**
## Proposed Changes

- Fixes #12015 
   change the sm to lg inside the emergency component which causing the layout breakout between 640px to 768 px because sm:col-span-2    conflicting with grid-cols-1  b/w   640px to 768 px.
image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Updated the layout of the Emergency Contact section to improve its appearance on larger screens. The section now spans two columns starting at the large screen size breakpoint.
  - Enhanced the patient details layout to display in two columns on smaller screen sizes for better readability.

### CODE REVIEW

File: src/components/Patient/PatientDetailsTab/Demography.tsx [hunk 1]
```diff
@@ -56,7 +56,7 @@ export const Demography = (props: PatientProps) => {
   };
 
   const EmergencyContact = (props: { number?: string; name?: string }) => (
-    <div className="sm:col-span-2">
+    <div className="lg:col-span-2">
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientDetailsTab/Demography.tsx]: Let's no do this, adjust the grid cols in line 270 instead.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Patient/PatientDetailsTab/Demography.tsx (hunk 1 above)
Comment (Vikaspal8923) [reply src/components/Patient/PatientDetailsTab/Demography.tsx]: I have changed the change md to sm in line 270. This is how the layout looks now :
image

File: src/components/Patient/PatientDetailsTab/Demography.tsx [hunk 2]
```diff
@@ -267,7 +267,7 @@ export const Demography = (props: PatientProps) => {
                       </Button>
                     )}
                   </div>
-                  <div className="mb-8 mt-2 grid grid-cols-1 gap-x-4 gap-y-2 md:grid-cols-2 md:gap-y-8 lg:grid-cols-2">
+                  <div className="mb-8 mt-2 grid grid-cols-1 gap-x-4 gap-y-2 sm:grid-cols-2 md:gap-y-8 lg:grid-cols-2">
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientDetailsTab/Demography.tsx]: lg:grid-cols-2 is redundant here since you are already specifying 2 columns for sm.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Review by Jacobjeevan — APPROVED** [review]
