### PR TITLE
Keep search text

### LINKED ISSUE #5412: Not able to view all facilities on users page
**Describe the bug**
On clicking the open dropdown option of the add skill feature to a user, all facilities aren't listed.

**To Reproduce**

1. Go to 
2. Click on `Linked Facilities` of any user
3. Search `ba` in the searchbox
4. Change the focus away from the box
5. Now open the dropdown, only facilities containing "ba" are visible.

**Expected behavior**
When the focus is shifted, the search box gets cleared but the text should still be there

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by MayaSatishRao**
### <samp>🤖 Generated by Copilot at 0b82667</samp>

This pull request improves the user interface and functionality of the CSV export feature and the `AutoCompleteAsync` component. It changes the format of the export filenames to include the date and time, and it fixes a bug where the input field would not display the typed query.

## Proposed Changes

- Fixes #5412 ?
- When the focus is out of input, search query is still present in the input feild

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

File: src/Common/hooks/useExport.tsx [hunk 1]
```diff
@@ -22,7 +22,13 @@ export default function useExport() {
...
   };
 
-  const getTimestamp = () => new Date().toISOString();
+  const getTimestamp = () => {
+    let d = new Date();
+    let date = d.toLocaleDateString();
+    let time = d.toLocaleTimeString();
+
+    return date+"_"+time;
+}
```
Comment (rithviknishad) [inline src/Common/hooks/useExport.tsx]: Why is this here? Ensure changes from your other branches are not present in other PRs.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by rithviknishad** [comment]
@MayaSatishRao your solution still doesn't solve the problem

File: src/Common/hooks/useExport.tsx (hunk 1 above)
Comment (MayaSatishRao) [reply src/Common/hooks/useExport.tsx]: ok, will do

**Comment by MayaSatishRao** [comment]
@rithviknishad  I have removed the changes from old branch and made new changes. Hope this solves the problem

**Review by rithviknishad — CHANGES_REQUESTED** [review]
The issue is still present. Are you not testing it yourself? Kindly test from your local before requesting a review.

image

**Comment by MayaSatishRao** [comment]
In the expected behavior of the issue, only 1 thing was mentioned: the search text in the input box must not be cleared. According to your last comment, I understood that the problem is all facilities are not listed even the search text is empty. Am I right?
Since I do not have the backend setup, I cannot test it on my machine. Should I set the backend as well?

**Comment by MayaSatishRao** [comment]
@rithviknishad ⬆️

**Comment by rithviknishad** [comment]
@MayaSatishRao but even the expected behaviour is not working. Either one should work.

Also, you don't need to setup the backend to run the front-end. By default, it'll use the staging backend.

**Comment by MayaSatishRao** [comment]
ok i will look into it

**Comment by MayaSatishRao** [comment]
@rithviknishad, now I have made changes such that all options are displayed instead of making the previous query displayed in the text input. Is that fine?
when searched for "ba":
infocus
when out of focus and then again search with empty query:
outfocus

**Comment by rithviknishad** [comment]
Nice! This should be fine

**Comment by MayaSatishRao** [comment]
ok, I will make the changes!!

**Comment by MayaSatishRao** [comment]
@rithviknishad I have made the changes! I have tested it as well.

**Comment by MayaSatishRao** [comment]
are the changes working? @rithviknishad

File: src/Components/Form/AutoCompleteAsync.tsx [hunk 2]
```diff
@@ -89,7 +89,10 @@ const AutoCompleteAsync = (props: Props) => {
               }
               onChange={({ target }) => setQuery(target.value)}
               onFocus={props.onFocus}
-              onBlur={props.onBlur}
+              onBlur={() => {
+                setQuery("");
+              }}
```
Comment (rithviknishad) [inline src/Components/Form/AutoCompleteAsync.tsx]: So what happens when I pass an `onBlur` prop to the `AutoCompleteAsync` component? It'll not work, right?
This might break some desired behaviours of other existing usages.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Form/AutoCompleteAsync.tsx (hunk 2 above)
Comment (MayaSatishRao) [reply src/Components/Form/AutoCompleteAsync.tsx]: onblur prop will be a function right? I will just add passed prop as well in the arrow function?

Comment (rithviknishad) [reply src/Components/Form/AutoCompleteAsync.tsx]: Yes!

Comment (MayaSatishRao) [reply src/Components/Form/AutoCompleteAsync.tsx]: ok

Comment (MayaSatishRao) [reply src/Components/Form/AutoCompleteAsync.tsx]: I had the onblur prop in the arrow function in the previous commit, but sonarcloud indicated that line as bug. What should I do? @rithviknishad

Comment (rithviknishad) [reply src/Components/Form/AutoCompleteAsync.tsx]: You can either remove the support of having `onBlur` from the props if it's not used anywhere, or you can ignore sonarcloud and still call the `onBlur` passed via the props.

Comment (MayaSatishRao) [reply src/Components/Form/AutoCompleteAsync.tsx]: i have added the onblur that is passed from the props.

**Review by rithviknishad — APPROVED** [review]
Nice work @MayaSatishRao

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
