### PR TITLE
Adjust the width of 'Remove Row' button in Report Template Builder 

### LINKED ISSUE #12476: Adjust the width of 'Remove Row' button in Report Template Builder to improve UI
**Describe the bug**
'Remove Row' button has asymmetric width as compared to other buttons (like Remove Text)

**To Reproduce**

1. Go to [link](https://care.ohc.network/facility/2fbb0809-b62c-4c53-816e-f1404f096c5e/settings/reportbuilder/new)
2. Click on Header tab
3. Click on any row and see in mobile view

**Expected behavior**
'Remove Row' should have full width just like the 'Remove Text' button which will improve the UI

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Priyadharshini0101**
## Proposed Changes
- Fixes #12476 
Adjust the width of 'Remove Row' button in Report Template Builder

Screenshot (697)
Screenshot (700)

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [X] Completion of QA in Mobile Devices
- [X] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Simplified the label on the button for removing elements in the report builder.
  - Adjusted the icon placement and styling of the button used to remove a header row for a cleaner appearance.

### CODE REVIEW

**Review by AdityaJ2305 — COMMENTED** [review]
One more change - Can you shift icon to left for `Remove Text` line no. 829

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
Let's remove the text from remove element (i.e text, separator etc) button and have just the trash can. That should allow all the buttons to stay consistently on one row; right now, it can overflow for separators.

image

**Comment by Priyadharshini0101** [comment]
@Jacobjeevan  @AdityaJ2305 I have updated the request changes. Please review

**Review by Jacobjeevan — APPROVED** [review]
Not what I meant, but this works 🤔

File: src/pages/Encounters/ReportBuilder/HeaderBuilder.tsx [hunk 1]
```diff
@@ -823,27 +823,23 @@ function HeaderRow({
                 variant="secondary"
                 onClick={() => onRemoveElement(rowIndex, activeElement)}
               >
-                <span className="text-sm">
-                  {t(`remove_${column[activeElement].type}`)}
-                </span>
+                <span className="text-sm">{t(`remove`)}</span>
```
Comment (NikhilA8606) [inline src/pages/Encounters/ReportBuilder/HeaderBuilder.tsx]:
```suggestion
                <span className="text-sm">{t("remove")}</span>
```

**Review by NikhilA8606 — CHANGES_REQUESTED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
