### PR TITLE
Referral letter preview desktop

### LINKED ISSUE #8884: Fix: referral letter responsiveness
**Describe the bug**
The referral letter has a responsive issue and looks messy

**To Reproduce**

1. Go to 'shifting'
2. Click on 'all details button on any card'
3. Click on 'referral button'

**Expected behavior**
The referral letter should be responsive and clean

**Screenshots**
Image

Image

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [129.0.6668.101]

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes
Referral letter preview desktop and responsive

- Fixes #8884 

Before
Image

After
Screenshot 2024-10-29 064626

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Release Notes

- **New Features**
	- Enhanced print functionality for referral letters with improved layout and visual appeal.
	- Introduced a new UI card system, including components for headers, titles, descriptions, content, and footers.

- **Improvements**
	- QR code rendering updated for better presentation using QRCodeSVG.
	- Patient information now displayed in a structured grid layout.

- **User Interface**
	- Minor adjustments to print mode toggle and button layout for improved usability.

### CODE REVIEW

**Comment by modamaan** [comment]
@bodhish   should i update anything?

**Comment by modamaan** [comment]
Screenshot 2024-10-29 192122

**Comment by modamaan** [comment]
@rithviknishad can you check

File: src/CAREUI/misc/PrintPreview.tsx [hunk 1]
```diff
@@ -14,31 +13,57 @@ type Props = {
...
+      }
+    };
+
+    handleResize();
+    window.addEventListener("resize", handleResize);
+
+    return () => {
+      window.removeEventListener("resize", handleResize);
+    };
+  }, []);
```
Comment (rithviknishad) [inline src/CAREUI/misc/PrintPreview.tsx]: Let's not do this. A mobile will not magically transform to a desktop or vice-versa.

Even if needed, this should be logic part of the `ZoomProvider` component and not `PrintPreview`.

If this is needed, create a separate issue and PR, as this would affect couple of other usages too and has to be tested. Avoid any changes to this component unless absolutely necessary to solve the linked issue.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/CAREUI/misc/PrintPreview.tsx (hunk 1 above)
Comment (modamaan) [reply src/CAREUI/misc/PrintPreview.tsx]: @rithviknishad removed mobile, we can create another PR for that, check desktop version and ui

File: src/CAREUI/misc/PrintPreview.tsx
Comment (rithviknishad) [inline src/CAREUI/misc/PrintPreview.tsx:1]: are changes to this file needed? You should be able to achieve without changing anything to this reusable component.

Comment (modamaan) [reply src/CAREUI/misc/PrintPreview.tsx:1]: No, component changes removed

**Comment by nihal467** [comment]
image
@modamaan 
- [ ] the close and print buttons in the mobile responsive view is not properly aligned

**Comment by bodhish** [comment]
@coderabbitai full review

**Comment by modamaan** [comment]
@nihal467  now only focus on desktop view, phone size i have facing issues

File: src/components/Shifting/ShiftDetails.tsx [hunk 2]
```diff
@@ -485,12 +429,8 @@
...
     <div>
       {isPrintMode ? (
-        <div className="my-4">
-          <div className="my-4 flex justify-end gap-3">
-            <ButtonV2 onClick={(_) => window.print()}>
-              <CareIcon icon="l-print" className="mr-2 text-base" />{" "}
-              {t("print_referral_letter")}
-            </ButtonV2>
+        <div className="my-4 xl:relative">
+          <div className="relative top-[190px] my-5 mr-[100px] flex justify-end gap-3 xl:absolute xl:right-6 xl:top-7 xl:justify-end">
```
[the remark this answers is not in the document]
Comment (modamaan) [reply src/components/Shifting/ShiftDetails.tsx]: print button inside the `PrintPreview` and clos button outside the `PrintPreview` component, so flex is not working properly

**Comment by nihal467** [comment]
@modamaan is the PR ready for review, did you fixed the issue ?

**Comment by modamaan** [comment]
@nihal467  Desktop View is done,  responsiveness facing issues, now go with Desktop View

**Comment by nihal467** [comment]
@modamaan what is the status on the PR, did you fix the mobile responsive issue ?

**Comment by nihal467** [comment]
@modamaan can you fix the responsive issue

**Comment by modamaan** [comment]
updated

https://github.com/user-attachments/assets/464c5485-7ec2-4d7d-881c-208c71f4dc92

**Comment by modamaan** [comment]
@nihal467 can you check,  sorry for being late I have an exam

**Comment by nihal467** [comment]
LGTM, @khavinshankar can you clear the merge conflict and get it merged

**Comment by modamaan** [comment]
@khavinshankar can you check

**Comment by rithviknishad** [comment]
@modamaan could you resolve conflicts

File: src/CAREUI/misc/PrintPreview.tsx [hunk 3]
```diff
@@ -12,24 +12,35 @@ type Props = {
   disabled?: boolean;
   className?: string;
   title: string;
+  onClose?: boolean;
+  closeFeature?: (value: boolean) => void;
 };
 
 export default function PrintPreview(props: Props) {
-  const normalScale = useBreakpoints({ default: 0.44, md: 1 });
+  const normalScale = useBreakpoints({ default: 1, md: 1 });
```
Comment (rithviknishad) [inline src/CAREUI/misc/PrintPreview.tsx]: @modamaan changes to this file is discouraged unless it's actually solving something. This affects all usages of the Print Preview component such as Prescriptions Print Page, etc...

The default scale set to 0.44 was intentional for previewing it in mobile.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/CAREUI/misc/PrintPreview.tsx (hunk 3 above)
Comment (rithviknishad) [reply src/CAREUI/misc/PrintPreview.tsx]: You should be able to achieve all the requirements to solve the issue without needing to modify the PrintPreview component ideally.

Comment (modamaan) [reply src/CAREUI/misc/PrintPreview.tsx]: scale updated,
If we are wrapping using the PrintPreview component, enabling the close feature is necessary to handle responsiveness

**Comment by modamaan** [comment]
@rithviknishad  Create a new ReferralLetterPreview component that wraps PrintPreview, shall i do it like this

**Comment by modamaan** [comment]
The problem is that we need both the print button and the close button in a single div to manage responsiveness. However, the print button is inside the PrintPreview component, while the close button is outside the component.

**Comment by rithviknishad** [comment]
The breadcrumbs providing back button is equivalent of having the close button as both does the same thing. So we can remove the close button since it's redundant.

**Comment by modamaan** [comment]
@rithviknishad @nihal467

File: src/components/Shifting/ShiftDetails.tsx [hunk 4]
```diff
@@ -273,182 +277,135 @@ export default function ShiftDetails(props: { id: string }) {
...
-            {formatDateTime(data.created_date) || "--"}
-          </div>
-          <div className="mt-2 text-left">
-            <span className="font-semibold leading-relaxed">
-              {" "}
-              {t("unique_id")} :
-            </span>
-            {data.id}
-          </div>
+      // deploytest
```
Comment (rithviknishad) [inline src/components/Shifting/ShiftDetails.tsx]:
```suggestion
```

File: src/components/ui/separator.tsx [hunk 5]
```diff
@@ -0,0 +1,3 @@
+export default function Separator() {
+  return <div className="my-4 border-t border-gray-300"></div>;
+}
```
Comment (rithviknishad) [inline src/components/ui/separator.tsx]: This implementation conflicts with original shadcn's implementation of Separator. Let's stick to using shadcn's implementation instead of custom one as when installing other shadcn's components, those components may end up using `Separator` from here, and it'd potentially break those as those components expect shadcn's implementation atleast in terms of API (props) wise 


image

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/ui/separator.tsx (hunk 5 above)
Comment (modamaan) [reply src/components/ui/separator.tsx]: I tried adding the `Shadcn Separator` , but it caused deployment issues
Screenshot 2024-10-28 213226

Comment (rithviknishad) [reply src/components/ui/separator.tsx]: When installing shadcn's separator, it'd also install an additional package from radix-ui. I don't see any package.json changes in the commit where you've originally attempted to install shadcn's separator

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image

- [ ] patient information is missing the type
- [ ] Make the label such as Date of Admission, Unique ID, etc... as bold, so its easily readable
- [ ] Arrange the data Properly with proper spacing, in the current UI, its like all the data are put together and its hard to read.

**Comment by modamaan** [comment]
updated @nihal467 
Screenshot 2024-11-30 145334

**Comment by modamaan** [comment]
@Jacobjeevan

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/components/Shifting/ShiftDetails.tsx [hunk 6]
```diff
@@ -5,8 +5,12 @@ import { useState } from "react";
 import { CopyToClipboard } from "react-copy-to-clipboard";
 import { useTranslation } from "react-i18next";
 
+import Card from "@/CAREUI/display/Card";
 import RecordMeta from "@/CAREUI/display/RecordMeta";
 import CareIcon from "@/CAREUI/icons/CareIcon";
+import PrintPreview from "@/CAREUI/misc/PrintPreview";
+
+import { CardContent, CardHeader, CardTitle } from "@/components/ui/card";
```
Comment (rithviknishad) [inline src/components/Shifting/ShiftDetails.tsx]: Use shadcn-ui's card instead. Let's not mix both.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Shifting/ShiftDetails.tsx (hunk 6 above)
Comment (modamaan) [reply src/components/Shifting/ShiftDetails.tsx]: @rithviknishad  updated

**Review by rithviknishad — CHANGES_REQUESTED** [review]
We do not have a shadow with border in other print previews used in care. Let's keep the design consistent with other usages too.

| Existing Prescriptions Print | Referral Letter Print  |
|---|---|
| image | image |
| image | image |

**Comment by modamaan** [comment]
@rithviknishad what change should I make, please ?

**Review by rithviknishad — APPROVED** [review]
