### PR TITLE
Fixed : Newly Added Patient Is Not Instantly Visible in the patient-switcher 

### LINKED ISSUE #10723: Newly Added Patient Is Not Instantly Visible in the Patient List of patient dashboard
**Describe the bug**

When a new patient is added through Patient Registration, the dropdown in the Public Patient Page does not immediately display the newly added patient. The new entry only appears after manually reloading the entire page.

**To Reproduce**

1. Log in as a patient using a phone number.
2. Click on a schedule and register an appointment for a new patient.
3. After successful registration, go to the Patient Dashboard and attempt to switch to the newly added patient.
4. Notice that the new patient does not appear in the dropdown.

**Expected behavior**

The patient dropdown should automatically update to include the newly registered patient as soon as the registration process is completed.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by Mahendar0701**
## Proposed Changes

- Fixes  #10723 
- Fixed newly added patient not instantly visible in patient-switcher
- Removed seletectedPatientData from local storage

image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced the patient registration process to ensure the patient list reflects the latest additions immediately.
- **Bug Fixes**
	- Removed the functionality that persisted the selected patient information in local storage, streamlining the patient selection process.

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

File: src/pages/PublicAppointments/PatientRegistration.tsx [hunk 1]
```diff
@@ -178,7 +178,11 @@ export function PatientRegistration(props: PatientRegistrationProps) {
       })(body),
     onSuccess: (data: Patient) => {
       toast.success(t("patient_created_successfully"));
+      queryClient.invalidateQueries({
+        queryKey: ["patients"],
+      });
       publish("patient:upsert", data);
+      localStorage.setItem("selectedPatient", JSON.stringify(data));
```
Comment (bodhish) [inline src/pages/PublicAppointments/PatientRegistration.tsx]: Why should we store the patient data in localstorage? @Jacobjeevan @rithviknishad ?
If its for the ID we should probably add patient id to the routes. The data would be avilable in the context right 🤔

Comment (rithviknishad) [reply src/pages/PublicAppointments/PatientRegistration.tsx]: I assumed this was a requirement, since I've been seeing caching things to local storage for all public patient related workflow since the beginning 😬

**Comment by nihal467** [comment]
@rithviknishad is it ready for review, seem like a discussion going on !

**Comment by Mahendar0701** [comment]
@rithviknishad let me know if I need to modify anything in this PR

**Comment by rithviknishad** [comment]
@Jacobjeevan

File: src/pages/PublicAppointments/PatientRegistration.tsx (hunk 1 above)
Comment (Jacobjeevan) [reply src/pages/PublicAppointments/PatientRegistration.tsx]: We can remove this local storage.

@Mahendar0701 go ahead and do that here, patient-switcher and in PatientUserProvider.

**Comment by rithviknishad** [comment]
merge checklist not followed

**Comment by Vikaspal8923** [comment]
@rithviknishad   is this issue resolved or not . Or anyone still working on it

**Comment by Mahendar0701** [comment]
> @rithviknishad   is this issue resolved or not . Or anyone still working on it

I worked on it, currently on leave will complete it by Saturday

**Comment by Mahendar0701** [comment]
@rithviknishad @Jacobjeevan can you reopen this PR , i followed merge checklist

**Review by rithviknishad — APPROVED** [review]

File: src/pages/PublicAppointments/PatientRegistration.tsx (hunk 1 above)
Comment (Mahendar0701) [reply src/pages/PublicAppointments/PatientRegistration.tsx]: @Jacobjeevan done with the changes can you once take a look

**Review by bodhish — APPROVED** [review]
LGTM
