### PR TITLE
#7308 fix : use "hidden" css property to toggle b/w Login & Forgot Password

### LINKED ISSUE #7308: Back to Login button in forget password overlapping with CARE Icon
**Describe the bug**

In mobile view, the 'Back to login' button in a language other than English is overlapping with the care icon.

**To Reproduce**

1. Go to https://care.coronasafe.in/
2. Click on forgot password button
3. switch to mobile view

**Expected behavior**

the back to login button shouldn't overlap with the CARE Icon in mobile view

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Vibhu1710**
## Proposed Changes
- Fixed #7308
- Tailwind CSS Property "visible" and "invisible" was being used to toggle between Main Login & Forgot Password Screens, this has now been replaced by "hidden" property
- Unnecessary absolute positioning of Forgot Password Screen has also been removed

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

Screenshot 2024-03-02 at 17 36 55
Screenshot 2024-03-02 at 17 36 38

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
LGTM, could have used the `classNames` utility method though for code to be more readable.

File: src/Components/Auth/Login.tsx [hunk 1]
```diff
@@ -277,10 +277,7 @@ export const Login = (props: { forgot?: boolean }) => {
             <div className="relative flex h-full w-full items-center">
               <div
                 className={
-                  "w-full transition-all " +
-                  (!forgotPassword
-                    ? "visible -translate-x-0 opacity-100"
-                    : "invisible -translate-x-5 opacity-0")
+                  "w-full transition-all " + (!forgotPassword ? "" : "hidden")
```
Comment (khavinshankar) [inline src/Components/Auth/Login.tsx]: instead of string concatenation, use the classNames utility which makes it easy to format and read
```suggestion
                  classNames("w-full transition-all", forgotPassword && "hidden")
```

File: src/Components/Auth/Login.tsx [hunk 2]
```diff
@@ -354,10 +351,7 @@ export const Login = (props: { forgot?: boolean }) => {
 
               <div
                 className={
-                  "absolute w-full transition-all " +
-                  (forgotPassword
-                    ? "visible translate-x-0 opacity-100"
-                    : "invisible translate-x-5 opacity-0")
+                  "w-full transition-all " + (forgotPassword ? "" : "hidden")
```
Comment (khavinshankar) [inline src/Components/Auth/Login.tsx]: use classNames utility

**Review by khavinshankar — CHANGES_REQUESTED** [review]
@Vibhu1710 just some minor refactors

**Review by khavinshankar — APPROVED** [review]
