### PR TITLE
Hide Power Bar for Discharged Encounters

### LINKED ISSUE #14414: Hide the AppointmentEncounterHeader when the encounter status is discharged
**Describe the bug**
The AppointmentEncounterHeader is still visible even when the encounter is discharged, so hide the power bar when the encounter status is discharged

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Proposed Changes
Fix : #14414 
The AppointmentEncounterHeader is showing even when the encounter is discharged, so hide that power bar when the encounter status is discharged.

https://github.com/user-attachments/assets/cbe65cf6-861f-4be0-84cd-09a2505ac1d2

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.
- [x] Add or update Playwright tests for related changes

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

File: src/pages/Encounters/EncounterShow.tsx [hunk 1]
```diff
@@ -208,7 +208,8 @@ export const EncounterShow = (props: Props) => {
     >
       {primaryEncounter &&
         primaryEncounter.appointment?.id &&
-        canWritePrimaryEncounter && (
+        canWritePrimaryEncounter &&
+        primaryEncounter.status !== "discharged" && (
```
Comment (gigincg) [inline src/pages/Encounters/EncounterShow.tsx:212]: Wouldn't this show up even when the encounter is completed or entered in error?

Comment (gigincg) [reply src/pages/Encounters/EncounterShow.tsx:212]: @rithviknishad @NikhilA8606

Comment (rithviknishad) [reply src/pages/Encounters/EncounterShow.tsx:212]: `canWritePrimaryEncounter` already does those checks.

https://github.com/ohcnetwork/care_fe/blob/bfc4ea8df52a55e1dfba5e2260acd9615eac5755/src/pages/Encounters/utils/EncounterProvider.tsx#L163-L167


https://github.com/ohcnetwork/care_fe/blob/bfc4ea8df52a55e1dfba5e2260acd9615eac5755/src/types/emr/encounter/encounter.ts#L258-L262

Comment (gigincg) [reply src/pages/Encounters/EncounterShow.tsx:212]: @rithviknishad This is a large chain of flags, I'm definitely not a fan of it. Do add a TODO to consider a better way to handle this.

I think the StartEncounter should show up only when it's a Planned Encounter, and shouldn't be shown in all other cases. But that's something that needs more thought

Comment (rithviknishad) [reply src/pages/Encounters/EncounterShow.tsx:212]: https://github.com/ohcnetwork/care_fe/issues/14424

Comment (NikhilA8606) [reply src/pages/Encounters/EncounterShow.tsx:212]: The condition is not only for Start Encounter, but also used for marking as complete, closing an appointment , and closing a token, hence all non-completed status needs to be checked @gigincg
