### PR TITLE
[FIXED] Improved the change password handling in profile edit page

### LINKED ISSUE #7605: Improve the change password handling in profile edit page
**Describe the bug**

- [ ] The password change input box on the profile update page lacks the same conditional checks found on the user creation page.
- [ ] When the wrong password is entered, there are multiple errors thrown at the same time
- [ ] we can input current password in the new password column and submit the form

**To Reproduce**

1. click on the profile name in the bottom right 
2. in the profile page, update the password
3. See error

**Expected behavior**

- [ ] password change input box on the profile update page should have the same condition check as the new user creation page
- [ ] Show the specific notification only " the old password - wrong password entered. Please check your password "
- [ ] add a validation for the new password column checking the current password inputted data and new password column are not having the same text

image
image
---
**Screenshots below are the bugs**
image

image
image

### PR DESCRIPTION
**Pull request by r-nikhilkumar**
- Fixes #7605
- password change input box on the profile update page should have the same condition check as the new user creation page✅
image
image
image
image

- Show the specific notification only " the old password - wrong password entered. Please check your password "✅
image

- add a validation for the new password column checking the current password inputted data and new password column are not having the same text✅
image

- Something extra done for making it more robust, I'm showing notification if new password criteria doesn't match while clicking "change password"
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

File: src/Components/Form/FormFields/FormField.tsx [hunk 1]
```diff
@@ -71,7 +71,19 @@ const FormField = ({
         )}
       </div>
       <div className={field?.className}>{children}</div>
-      <FieldErrorText error={field?.error} className={field?.errorClassName} />
+      {field?.error && field?.error?.split("\n").length > 1 ? (
+        field?.error?.split("\n").map((err) => (
+          <div key={err.length}>
+            <FieldErrorText error={err} className={field?.errorClassName} />
+            <br />
+          </div>
```
Comment (rithviknishad) [inline src/Components/Form/FormFields/FormField.tsx]: use `<ul>` and `<li>` instead of div

File: src/Components/Form/FormFields/FormField.tsx [hunk 2]
```diff
@@ -71,7 +71,19 @@ const FormField = ({
         )}
       </div>
       <div className={field?.className}>{children}</div>
-      <FieldErrorText error={field?.error} className={field?.errorClassName} />
+      {field?.error && field?.error?.split("\n").length > 1 ? (
```
Comment (rithviknishad) [inline src/Components/Form/FormFields/FormField.tsx]:
```suggestion
      {field?.error && field?.error?.split("\n").length ? (
```

File: src/Components/Form/FormFields/FormField.tsx [hunk 3]
```diff
@@ -71,7 +71,19 @@ const FormField = ({
...
+            <FieldErrorText error={err} className={field?.errorClassName} />
+            <br />
+          </div>
+        ))
+      ) : (
+        <FieldErrorText
+          error={field?.error}
+          className={field?.errorClassName}
+        />
+      )}
```
Comment (rithviknishad) [inline src/Components/Form/FormFields/FormField.tsx]:
```suggestion
```

File: src/Components/Users/UserProfile.tsx [hunk 4]
```diff
@@ -181,6 +183,45 @@ export default function UserProfile() {
...
+      return;
+    } else {
+      setChangePasswordErrors((prev) => ({
+        ...prev,
+        password_confirmation:
+          "Confirm password should match the new password!",
+      }));
+    }
+  };
+
```
Comment (rithviknishad) [inline src/Components/Users/UserProfile.tsx]: both the functions seems to be complicated to read than necessary. try to simplify the code and make it more readable.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Form/FormFields/FormField.tsx (hunk 2 above)
Comment (r-nikhilkumar) [reply src/Components/Form/FormFields/FormField.tsx]: done

File: src/Components/Form/FormFields/FormField.tsx (hunk 3 above)
Comment (r-nikhilkumar) [reply src/Components/Form/FormFields/FormField.tsx]: done

File: src/Components/Form/FormFields/FormField.tsx (hunk 1 above)
Comment (r-nikhilkumar) [reply src/Components/Form/FormFields/FormField.tsx]: done

File: src/Components/Users/UserProfile.tsx (hunk 4 above)
Comment (r-nikhilkumar) [reply src/Components/Users/UserProfile.tsx]: done

File: src/Components/Form/FormFields/FormField.tsx [hunk 5]
```diff
@@ -71,7 +71,16 @@ const FormField = ({
...
+      <ul>
+        {field?.error &&
+          field?.error?.split("\n").length &&
+          field?.error?.split("\n").map((err) => (
+            <li key={err.length}>
+              <FieldErrorText error={err} className={field?.errorClassName} />
+              <br />
+            </li>
+          ))}
+      </ul>
```
Comment (rithviknishad) [inline src/Components/Form/FormFields/FormField.tsx]: The `ul` need not be present if there is no errors.

File: src/Components/Users/UserProfile.tsx [hunk 6]
```diff
@@ -400,25 +422,38 @@ export default function UserProfile() {
...
         new_password: changePasswordForm.new_password_1,
       };
-      const { res, data } = await request(routes.updatePassword, {
+      const { res, data, error } = await request(routes.updatePassword, {
         body: form,
       });
       if (res?.ok && data?.message === "Password updated successfully") {
         Notification.Success({
           msg: "Password changed!",
         });
```
Comment (rithviknishad) [inline src/Components/Users/UserProfile.tsx]:
```suggestion
      if (res?.ok) {
        Notification.Success({ msg: data?.message });
```

**Review by rithviknishad — COMMENTED** [review]
LGTM, just some minor changes

File: src/Components/Form/FormFields/FormField.tsx (hunk 5 above)
Comment (r-nikhilkumar) [reply src/Components/Form/FormFields/FormField.tsx]: done

**Comment by r-nikhilkumar** [comment]
@rithviknishad I made all the changes, now you can finalize it

File: src/Components/Form/FormFields/FormField.tsx [hunk 7]
```diff
@@ -71,7 +71,18 @@ const FormField = ({
...
+      {field?.error && (
+        <ul>
+          {(typeof field.error === "string" ? field.error : String(field.error))
+            .split("\n")
+            .map((err, index) => (
+              <li key={index}>
+                <FieldErrorText error={err} className={field?.errorClassName} />
+              </li>
+            ))}
+        </ul>
```
Comment (rithviknishad) [inline src/Components/Form/FormFields/FormField.tsx]: This change broke the spacing in the entire platform...


image

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Form/FormFields/FormField.tsx (hunk 7 above)
Comment (r-nikhilkumar) [reply src/Components/Form/FormFields/FormField.tsx]: image

It is because I'm checking before rendering
but after removing that condition, it fixed
image
image

**Comment by r-nikhilkumar** [comment]
@rithviknishad I solved it... now you can review

**Comment by nihal467** [comment]
@r-nikhilkumar 
image

- [ ] Once you click the "edit profile" button, the condition for a new password is always present there. It should only be shown when the user clicks on the "new password" column to input the data.

image

- [ ] As per the issue, it is expected to behave similarly to the new user creation form. But in your PR, when the condition passes, they disappear. It shouldn't be the case; it should turn the condition to green.

Note: understand the existing behavior in the new user creation form password input column then replicate that behavior in the edit profile page

**Comment by r-nikhilkumar** [comment]
@nihal467 done

**Comment by r-nikhilkumar** [comment]
@rithviknishad can you add need testing label, all done...!

**Review by rithviknishad — APPROVED** [review]
Nice work!

**Comment by nihal467** [comment]
LGTM

File: src/Components/Users/UserProfile.tsx [hunk 8]
```diff
@@ -774,35 +802,74 @@ export default function UserProfile() {
...
+                              setChangePasswordForm({
+                                ...changePasswordForm,
+                                new_password_1: e.value,
+                              });
+                            }}
+                            required
+                            onFocus={() => setNewPasswordInputInFocus(true)}
+                            onBlur={() => setNewPasswordInputInFocus(false)}
+                          />
+                          {newPasswordInputInFocus && (
```
Comment (khavinshankar) [inline src/Components/Users/UserProfile.tsx]: @r-nikhilkumar consider using CSS instead of creating a state 

https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-sibling-state

Please do the same for confirm password too

**Review by khavinshankar — CHANGES_REQUESTED** [review]

**Review by shivankacker — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/Components/Users/UserProfile.tsx [hunk 9]
```diff
@@ -139,7 +140,6 @@ export default function UserProfile() {
   });
 
   const [showEdit, setShowEdit] = useState<boolean | false>(false);
```
Comment (khavinshankar) [inline src/Components/Users/UserProfile.tsx]:
```suggestion
  const [showEdit, setShowEdit] = useState<boolean>(false);
```

**Review by khavinshankar — APPROVED** [review]
