### PR TITLE
Fix: TypeError in notification list

### LINKED ISSUE #8006: TypeError in NotificationsList Component on Service Worker Subscription Fetch
## Summary
A TypeError occurred within the NotificationsList component of our application, specifically during the execution of the initialSubscriptionState function. This error impacts users on the Chrome Mobile iOS browser, as seen in a recent log from our production environment.

## Description
When the function initialSubscriptionState tries to fetch the subscription status from the service worker, it fails because the subscription object returned by pushManager.getSubscription() is unexpectedly undefined. This indicates that the service worker might not be properly initialized or the pushManager is not available in the current browser context at the time of invocation.

## Steps to Reproduce
- Open the application using any device.
- Navigate to the Notifications area of the application.
- The error occurs during the loading process of this component.

## Expected Behavior
The application should safely check for the availability of the service worker and gracefully handle cases where the push manager's subscription object is undefined.

## Actual Behavior
The application encounters a TypeError and may impact the user experience by halting subsequent JavaScript execution, potentially leading to a partially rendered or non-responsive page.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #8006 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Request for Peer Reviews

## Note
I noticed there was an existing PR addressing this issue, but it seems inactive with unresolved conflicts. I’ve resolved the issue here to help move things forward.

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved subscription and unsubscription logic to prevent errors when service workers are not supported.
	- Enhanced error handling during the unsubscribe process to ensure issues are captured.

- **Refactor**
	- Simplified logic for determining subscription status for better readability.
	- Minor formatting adjustments for improved code clarity without affecting functionality.

### CODE REVIEW

**Comment by bodhish** [comment]
@AdityaJ2305 we would really try to merge the 1st PR for any issue, unless its super inactive for long. 

Note to Reviewers: See if we can savage #8686, if we are going ahead with #8935 close the other and let the author know the reason.

**Comment by AdityaJ2305** [comment]
@coderabbitai  full review

**Comment by AdityaJ2305** [comment]
Hey @bodhish , This PR is labeled as “blocked.” I’ve made the requested changes requested by `coderabbit` and resolved the conflicts. Could you clarify how blocked PRs are typically handled and if there’s anything specific I should do?

File: src/components/Notifications/NotificationsList.tsx [hunk 1]
```diff
@@ -286,49 +289,44 @@ export default function NotificationsList({
...
+              pf_auth: "",
+            },
           });
-      })
-      .catch(function (_e) {
-        Sentry.captureException(_e);
-      });
-  };
 
+          setIsSubscribed("NotSubscribed");
```
Comment (Jacobjeevan) [inline src/components/Notifications/NotificationsList.tsx:318]: Any reason why unsubscribed successfully notification was removed? If not, let's add it back.

Otherwise, LGTM.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by nihal467** [comment]
@AdityaJ2305 can you push the requested changes

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
