### PR TITLE
Redesigned public page as per the figma design

### LINKED ISSUE #11015: Redesign the Public Page as per the new Figma design
**Describe the bug**

Redesign the public page as per the new Figma design ( https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=9900-14259&t=YHHDkQltmZ2bBTJK-1 ) 

Screenshot

Image

URL to the public page: https://care.coronasafe.in/

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by cherish2003**
## Proposed Changes

- Fixes #11015
- Redesigned public page as per the [figma design](https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=9900-14259&t=YHHDkQltmZ2bBTJK-1)

## Screen shot
Screenshot 2025-03-07 at 1 07 36 AM

## Demo video

https://github.com/user-attachments/assets/083d12a9-9a1a-4222-8a02-efa5a6983865

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for change log entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Introduced a dedicated login section offering distinct options for staff and patients.
  - Added new localization entries to enhance user guidance and search functionality.

- **Style & Layout Enhancements**
  - Streamlined the landing page with improved padding and responsive design.
  - Redesigned the search area with a refreshed placeholder and updated button styling.
  - Added a new centered dots image below the search section.
  - Introduced a new icon representation for "d-health-worker".

### CODE REVIEW

File: src/pages/Landing/LandingPage.tsx [hunk 1]
```diff
@@ -96,110 +94,187 @@ export function LandingPage() {
...
-                    <CareIcon
-                      icon="l-times"
-                      className="h-4 w-4 text-gray-400"
-                    />
-                  </button>
-                )}
+        <div className="w-full max-w-[620px] mx-auto px-4 sm:px-6 py-4 bg-gray-100 rounded-md">
+          <div className="text-center mb-4">
+            <span className="text-sm md:text-base block sm:inline">
+              Search for available facilities to book an appointment
```
Comment (AdityaJ2305) [inline src/pages/Landing/LandingPage.tsx]: i18n translation missing for all text

Comment (cherish2003) [reply src/pages/Landing/LandingPage.tsx]: For the public page by default their is no translation

Comment (AdityaJ2305) [reply src/pages/Landing/LandingPage.tsx]: add it for en.json , rest will be handled by crowdin

**Comment by cherish2003** [comment]
@AdityaJ2305 once check it out i have added i18n translation for all the texts in the public page

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/pages/Landing/LandingPage.tsx [hunk 2]
```diff
@@ -96,110 +100,189 @@ export function LandingPage() {
...
+            </div>
+            <div
+              className="flex flex-col items-center justify-center gap-5 p-3 rounded-xl shadow bg-white hover:shadow-md transition-all"
+              style={{
+                backgroundImage: 'url("/images/patient_background.png")',
+                backgroundSize: "auto",
+                backgroundPosition: "center",
+                backgroundRepeat: "no-repeat",
+              }}
+            >
```
Comment (rithviknishad) [inline src/pages/Landing/LandingPage.tsx]: use tailwind classes instead

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by nihal467** [comment]
non related cypersss failure , LGTM

**Review by nihal467 — APPROVED** [review]

File: src/pages/Landing/LandingPage.tsx [hunk 3]
```diff
@@ -43,6 +43,10 @@ export function LandingPage() {
     organization.name.toLowerCase().includes(searchQuery.toLowerCase()),
   );
 
+  const orgType = t(
+    `SYSTEM__govt_org_type__${organizations[0]?.metadata?.govt_org_type || "district"}`,
+  ).toLowerCase();
```
Comment (rithviknishad) [inline src/pages/Landing/LandingPage.tsx]: we can't hardcode any fallbacks such as "district"/"state" etc. in our codebase; these terms may not exist in all territories;

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]
