### PR TITLE
fix: extra padding on external results page

### LINKED ISSUE #2369: Padding issue in external_results page mobile view
URL: https://care.coronasafe.in/external_results

Missing Padding between export button and filter in external results page mobile view (width < 768px) causes sometimes touch navigation problems.

image

### PR DESCRIPTION
**Pull request by kunatastic**
fixes #2369 

Updated UI 
image

### CODE REVIEW

**Comment by nihal467** [comment]
wefiewf

@kunatastic @gigincg test failed, the filter and the buttons are still close

**Comment by kunatastic** [comment]
Fixed the button's padding 

image

**Comment by nihal467** [comment]
test approved

**Comment by khavinshankar** [comment]
@kunatastic please do work on the merge conflict

**Comment by kunatastic** [comment]
@khavinshankar @nihal467 fixed the merge conflict. Apologies for long delay

**Comment by nihal467** [comment]
test appproved

File: src/Components/ExternalResult/ResultList.tsx [hunk 1]
```diff
@@ -390,36 +388,34 @@ export default function ResultList() {
...
+              className="btn btn-primary"
               onClick={(_) => navigate("external_results/upload")}
             >
               Upload List
             </div>
             <div
-              className={`btn mt-8 ml-4 gap-2 btn-primary ${
+              className={`btn btn-primary ${
                 downloadLoading ? "pointer-events-none" : ""
               }`}
```
Comment (khavinshankar) [inline src/Components/ExternalResult/ResultList.tsx]:
```suggestion
              className={clsx("btn btn-primary", downloadLoading && "pointer-events-none")}
```

_can you please use clsx here, it improves the readability and don't forget to import clsx if not already done so_

**Review by khavinshankar — CHANGES_REQUESTED** [review]
please do make the recommended changes

**Comment by kunatastic** [comment]
@khavinshankar worked on suggested changes

**Review by cp-Coder — APPROVED** [review]

**Comment by nihal467** [comment]
@kunatastic test failed, the button is not responsive

**Comment by kunatastic** [comment]
made required changes

**Comment by nihal467** [comment]
@kunatastic check the conflict file !

**Comment by kunatastic** [comment]
@nihal467 this pr is good for testing

**Comment by nihal467** [comment]
test approved

File: src/Components/ExternalResult/ResultList.tsx [hunk 2]
```diff
@@ -254,7 +252,7 @@ export default function ResultList() {
 
   let resultList: any[] = [];
   if (data && data.length) {
-    resultList = data.map((result: any) => {
+    resultList = data.map((result: any, _idx: number) => {
```
Comment (khavinshankar) [inline src/Components/ExternalResult/ResultList.tsx]:
```suggestion
    resultList = data.map((result: any) => {
```

`_idx` is an optional parameter, so I think we can just avoid it when we don't use it, this keeps the code clean

File: src/Components/ExternalResult/ResultList.tsx [hunk 3]
```diff
@@ -239,7 +237,7 @@ export default function ResultList() {
           {value.name}
           <i
             className="fas fa-times ml-2 rounded-full cursor-pointer hover:bg-gray-500 px-1 py-0.5"
-            onClick={() =>
+            onClick={(_) =>
```
Comment (khavinshankar) [inline src/Components/ExternalResult/ResultList.tsx]:
```suggestion
            onClick={() =>
```

If event (`_`) is an optional one, so its better to be avoided when we don't use them

File: src/Components/ExternalResult/ResultList.tsx [hunk 4]
```diff
@@ -220,7 +218,7 @@ export default function ResultList() {
           {value}
           <i
             className="fas fa-times ml-2 rounded-full cursor-pointer hover:bg-gray-500 px-1 py-0.5"
-            onClick={() => removeFilter(paramKey)}
+            onClick={(_) => removeFilter(paramKey)}
```
Comment (khavinshankar) [inline src/Components/ExternalResult/ResultList.tsx]:
```suggestion
            onClick={() => removeFilter(paramKey)}
```
If event (_) is an optional one, so its better to be avoided when we don't use them

**Review by khavinshankar — CHANGES_REQUESTED** [review]

**Comment by khavinshankar** [comment]
@kunatastic there are some minor changes, can you please address them

**Comment by khavinshankar** [comment]
@kunatastic please do work on the merge conflict

**Review by khavinshankar — APPROVED** [review]
