### PR TITLE
Disable switching to "Refer to another facility"/"Declare Death" in Decision after consultation in edit consultation form

### LINKED ISSUE #7939: Hide "Refer to another facility" and "Declare Death" in the edit consultation
**Describe the bug**

When a user creates a patient record as admitted and later edits the consultation, selecting the decision as "Refer to another facility," then without completing the shifting patient flow, they cancel it. Now, keeping the decision as "Refer to another facility," the origin facility staff tries to discharge the patient from the origin facility with the reason "Recovered," which causes a data integrity issue.

**To Reproduce**

**Expected behavior**

- [ ] Hide "Declare Death" and "Refer to Another Facility" in the edit consultation, since they are having specific flow users can use in the discharge reason pop-up

**Screenshots**

image

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Fixes #7939
- Adds support for disabling individual options in dropdown menu

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad 

image

the text color is not properly visible

**Comment by nihal467** [comment]
LGTM

File: src/Components/Facility/ConsultationForm.tsx [hunk 1]
```diff
@@ -1148,6 +1148,14 @@ export const ConsultationForm = ({ facilityId, patientId, id }: Props) => {
                       options={CONSULTATION_SUGGESTION.filter(
                         (option) => !("deprecated" in option),
                       )}
+                      optionDisabled={(option) =>
+                        isUpdate && "editDisabled" in option
+                      }
+                      optionDescription={(option) =>
+                        isUpdate && "editDisabled" in option
+                          ? "Not allowed to switch to this option in edit consultation"
```
Comment (khavinshankar) [inline src/Components/Facility/ConsultationForm.tsx]: let's add internationalization

**Review by khavinshankar — APPROVED** [review]
