### PR TITLE
Fix : Validation Error Messages Persist After Fixing Input Values

### LINKED ISSUE #11791: Validation Error Messages Persist After Fixing Input Values
**Describe the bug**
Validation error messages persist even after the input values are corrected. Error messages should disappear once valid values are entered.

**To Reproduce**

1. Go to 'Search Patients'.
2. Click on 'Add Patients".
3. Click the save button without filling any fields.
4. Error messages appear.
5. Start typing in input field.
6. Error messages remain visible after entered.

https://github.com/user-attachments/assets/941f6205-9521-403d-8424-afc315fd0663

**Expected behavior**
Error messages should clear automatically when the form becomes valid.
**Expected Output**

https://github.com/user-attachments/assets/ab5cc2fe-6c3b-4f96-9737-cc7c4f22658a

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #11791

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

https://github.com/user-attachments/assets/ab5cc2fe-6c3b-4f96-9737-cc7c4f22658a

- [ ] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Enhanced registration form validation to trigger in real-time as users interact with form fields.
  - Updated default behavior for address confirmation to improve user experience.

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
is this really needed? how does all other forms work without needing this?

**Comment by Jeffrin2005** [comment]
@rithviknishad Yes, In other forms also the validation will be removed after entering the input,

In this for creating the schedule template, the validation is removing when entering the input

https://github.com/user-attachments/assets/350c6781-40f2-490f-b466-a80e756f2397

So for adding patient form , validation is needed right ?

**Comment by rithviknishad** [comment]
I mean, is the useEffect really needed? 🤔 All other forms doesn't have such useEffects to achieve this

**Comment by Jeffrin2005** [comment]
Removed UseEffect.

File: src/components/Patient/PatientRegistration.tsx [hunk 1]
```diff
@@ -179,6 +179,9 @@ export default function PatientRegistration(
       same_phone_number: false,
       same_address: true,
     },
+    mode: "all",
+    criteriaMode: "all",
+    reValidateMode: "onChange",
```
Comment (rithviknishad) [inline src/components/Patient/PatientRegistration.tsx]: isn't this sufficient? 🤔 

```suggestion
    mode: "onChange",
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by Jeffrin2005** [comment]
@rithviknishad  The issue persists when using " mode: onChange  "only, and also for checkbox it is not working (validation errors showing when we click the checkbox ) , But using useEffect it is working for all .

**Comment by rithviknishad** [comment]
figure out the root cause, shadcn's checkbox does not require such hacks to be done in order for it to work as per the docs

https://ui.shadcn.com/docs/components/checkbox

**Comment by rithviknishad** [comment]
there seems to be some other issue hidden beneath i suppose.

recently checkbox's onchange started failing and we had to make the following quick fix: https://github.com/ohcnetwork/care_fe/pull/11659/files

cc: @Jacobjeevan

**Comment by hrit2773** [comment]
@Jeffrin2005  there are same default behaviors with the shadcn components also as they trigger this onChange without even mentioning onChange also. I feel sticking to the default behavior only would be better

**Comment by Jacobjeevan** [comment]
> there seems to be some other issue hidden beneath i suppose.
> 
> recently checkbox's onchange started failing and we had to make the following quick fix: https://github.com/ohcnetwork/care_fe/pull/11659/files
> 
> cc: @Jacobjeevan

I checked against react v19 deployment, everything else apart from checkbox seems fine 😅  Same for phone number as well.

image

I unchecked and typed in, that cleared error for permanent address, but not address. Same for phone number.

image

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan 
Any Changes ? Now including checkbox is working.

https://github.com/user-attachments/assets/4b817503-d19c-473d-91c6-a91507175605

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan 
Any Changes ? Now including checkbox is working.

https://github.com/user-attachments/assets/4b817503-d19c-473d-91c6-a91507175605

File: src/components/Patient/PatientRegistration.tsx [hunk 2]
```diff
@@ -769,14 +782,13 @@ export default function PatientRegistration(
...
-                              ? Number(e.target.value)
-                              : (undefined as unknown as number), // intentionally setting to undefined, when the value is empty to avoid 0 in the input field
-                          )
-                        }
+                        onChange={(e) => {
+                          const value = e.target.value
+                            ? Number(e.target.value)
+                            : undefined;
+                          field.onChange(value);
+                          form.trigger("pincode");
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientRegistration.tsx]: trigger should be unnecessary.

File: src/components/Patient/PatientRegistration.tsx [hunk 3]
```diff
@@ -726,7 +734,12 @@ export default function PatientRegistration(
                                     form.setValue(
                                       "permanent_address",
                                       form.getValues("address"),
+                                      { shouldValidate: true },
                                     );
+                                  } else {
+                                    form.setValue("permanent_address", "", {
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientRegistration.tsx]: minor thing, no need to clear the permanent address here. After all, if perm add is in same city etc, can save some typing for user.

**Review by Jacobjeevan — APPROVED** [review]
lgtm, minor comments.

Edit: resolve merge conflict as well, can re-approve after.

**Comment by nihal467** [comment]
image

- it is expected to have the permanent address checkbox by default selected, since for most of the real world case, the current and permanent address are entered as same only, so revert the behavior change , and keep it same as current develop

image

- in  your PR, when i click the checkbox on a fresh patient registration form, instantly validation error is thrown, seem off, because this validation are only intended to trigger on submission of the form
- post all the fix pushed, max sure the cypress passed

**Comment by Jeffrin2005** [comment]
@nihal467 Now everything is working correctly and fixed cypress test. Marked checkbox as defult. 


https://github.com/user-attachments/assets/91fc40e0-7fe9-407a-b2f5-2981a641a833

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
