### PR TITLE
Display live monitoring button to only State Admin, District Admin and Doctor.

### LINKED ISSUE #7021: Restrict Live monitoring button in facility details page to Certain users
**Describe the bug**

Live monitoring button in the facility detail page is visible to all users

**To Reproduce**

1. Go to facility detail page with staff user credentials
2. See error

**Expected behavior**

Live monitoring button in the facility detail page should be visible to state admin, district admin and doctor only

**Screenshots**

image

### PR DESCRIPTION
**Pull request by AshrafMd-1**
## Proposed Changes

- Fixes #7021 
- Display live monitoring button to specific users only

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by AshrafMd-1** [comment]
@rithviknishad can u review once

**Review by rithviknishad — CHANGES_REQUESTED** [review]
This just hides the button. Users could still go to the URL directly and open the page right?

I think we could add a reusable component called: `AuthorizedRoute` which accepts `user_type: UserRole[]; children` and show Page Not Found / Forbidden if unauthorized, else the children.

This wrapper would be used directly in the raviger router's routes like:

```jsx
const routes = {
  ...
  "/path/to/page": (props) => (
    <AuthorizedRoute userTypes={["StateAdmin", ...]}>
      <LiveMonitoring {...props} />
    </AuthorizedRoute>
  )
};
```

**Comment by AshrafMd-1** [comment]
@rithviknishad is this okay ?

File: src/Utils/AuthorizeFor.tsx [hunk 1]
```diff
@@ -26,3 +35,16 @@ export const Anyone = () => true;
...
   return (userType: UserRole) => userTypes.includes(userType);
 }
+
+export const AuthorizeUserRoute: React.FC<AuthorizeUserRouteProps> = ({
+  userTypes,
+  children,
+}) => {
+  const userData = useAuthUser();
+
+  if (userData && userTypes.includes(userData.user_type)) {
```
Comment (rithviknishad) [inline src/Utils/AuthorizeFor.tsx]: the truthy check for `userData` is not required as the `useAuthUser` would always return a `UserModel` object and would always evaluate to true.

```suggestion
  const authUser = useAuthUser();
  if (userTypes.includes(authUser.user_type)) {
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

File: src/Components/Facility/FacilityHome.tsx [hunk 2]
```diff
@@ -475,15 +475,21 @@ export const FacilityHome = (props: any) => {
 const LiveMonitoringButton = () => {
   const facilityId = useSlug("facility");
   const [location, setLocation] = useState<string>();
+  const authUser = useAuthUser();
+
+  const userRoles = ["StateAdmin", "DistrictAdmin", "Doctor"];
```
Comment (Ashesh3) [inline src/Components/Facility/FacilityHome.tsx]: Just a small suggestion to use more descriptive variable names in future. Here `userRoles` does not convey the purpose as to why we have these 3 roles here in a list. Something like `allowedUserRoles` or `permittedRoles` would make more sense. Also seems like in most places we refer to these as user *types* and not *roles*. 

No issues, just small scopes of improvements!

File: src/Utils/AuthorizeFor.tsx [hunk 3]
```diff
@@ -26,3 +35,15 @@ export const Anyone = () => true;
...
+
+export const AuthorizeUserRoute: React.FC<AuthorizeUserRouteProps> = ({
+  userTypes,
+  children,
+}) => {
+  const authUser = useAuthUser();
+  if (userTypes.includes(authUser.user_type)) {
+    return <>{children}</>;
+  } else {
+    return <Error404 />;
```
Comment (Ashesh3) [inline src/Utils/AuthorizeFor.tsx:47]: `In future,` maybe we can consider having a 403 Forbidden page, to better represent the error in case they do not have permissions but are shared with a URL. In case someone thinks they should have access but does not, they will get to a 404 page which indicates that the issue is with the page itself, it does not exist. In this case, if the error page was 403, they would be able to communicate to the proper channel that they do not have permissions for the page, instead of the page simply not existing.

**Review by Ashesh3 — APPROVED** [review]

File: src/Components/Facility/FacilityHome.tsx (hunk 2 above)
Comment (AshrafMd-1) [reply src/Components/Facility/FacilityHome.tsx]: done
can u check once @Ashesh3

Comment (Ashesh3) [reply src/Components/Facility/FacilityHome.tsx]: @AshrafMd-1 Great work! Looks good now.

File: src/Utils/AuthorizeFor.tsx (hunk 3 above)
Comment (AshrafMd-1) [reply src/Utils/AuthorizeFor.tsx:47]: It would be better if we create a separate PR for this
as for a 403 page, we also need an icon etc

image
something like this

Comment (Ashesh3) [reply src/Utils/AuthorizeFor.tsx:47]: @AshrafMd-1 Yep, let's do it separately in a different issue and PR.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
