### PR TITLE
Fix Translations Not Loading for Global Zod Validators Error Messages and Improve Patient Registration Error Messages

### LINKED ISSUE #10555: Improper Error handling in Patient Registration Form
**Describe the bug**
- User is unable to edit a Patient's age which is below 9 to any other age below 9, only possible using PgDn/PgUp key

Click  [here](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/patient/3dc92e19-510d-40d5-ab8d-73aece656108/update?section=general-info) to reproduce.

Image

- Prevent negative Y.O.B values to display on UI

Image

- 'invalid uuid' could be made more user-friendly

Image

**To Reproduce**

1. Go to Encounters > Click on Any Patient > Patient details > Edit > Scroll Down to Age Section

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #10584: Global Zod Validators Error Messages for Phone Number and Geo-Coordinates are not displaying
**Describe the bug**
The translations set inside validators file are not being displayed as form field errors as expected in FacilityForm, ResourceCreate Form and PatientRegistration Form

Image

Image

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by rajku-dev**
## Proposed Changes

- Fixes #10555
- Fixes #10584

Before 

image
image

After

image
image
image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Enhanced error feedback for age and location inputs, leading to more precise validation messages.

- **Refactor**
  - Streamlined the form validation process across the application by dynamically generating validation rules, ensuring a more consistent and flexible user experience.
  - Removed the validation message for phone number length requirement.

### CODE REVIEW

File: src/Utils/validators.ts [hunk 1]
```diff
@@ -2,27 +2,32 @@ import { t } from "i18next";
 import { isValidPhoneNumber } from "react-phone-number-input";
 import { z } from "zod";
 
-export default {
+export default () => ({
   phoneNumber: {
     optional: z
```
Comment (rajku-dev) [inline src/Utils/validators.ts:7]: Before: Translations were fetched too early (when the module was imported).

Now: Translations are fetched dynamically when the function is called inside a component.

i18next is asynchronous → must ensure translations are available when needed.

File: src/components/Facility/FacilityForm.tsx [hunk 2]
```diff
@@ -57,6 +57,7 @@ export default function FacilityForm({
   const queryClient = useQueryClient();
   const [isGettingLocation, setIsGettingLocation] = useState(false);
   const [selectedLevels, setSelectedLevels] = useState<Organization[]>([]);
+  const validators = getValidationSchema();
```
Comment (rithviknishad) [inline src/components/Facility/FacilityForm.tsx]: this dx does not feel right, let's simply do:

validators().phoneNumber.....

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Facility/FacilityForm.tsx (hunk 2 above)
Comment (rajku-dev) [reply src/components/Facility/FacilityForm.tsx]: made the changes as requested 👍

File: src/Utils/validators.ts [hunk 3]
```diff
@@ -2,27 +2,32 @@ import { t } from "i18next";
...
       .refine((val) => !val || isValidPhoneNumber(val), {
         message: t("phone_number_validation_error"),
       }),
-    required: z.string().refine((val) => isValidPhoneNumber(val), {
-      message: t("phone_number_validation_error"),
-    }),
+
+    required: z
+      .string()
+      .min(1, { message: t("phone_number_must_be_10_digits") })
```
Comment (rithviknishad) [inline src/Utils/validators.ts]: phone number is not always 10 digits; let's remove the misleading key as well in translations.

let's simply show "field_required" instead here.

**Review by rithviknishad — CHANGES_REQUESTED** [review]
overlooked this thing earlier, other than that LGTM

File: src/Utils/validators.ts (hunk 3 above)
Comment (rajku-dev) [reply src/Utils/validators.ts]: made the changes

File: public/locale/en.json [hunk 4]
```diff
@@ -1616,7 +1616,7 @@
   "phone_number": "Phone Number",
   "phone_number_at_current_facility": "Phone Number of Contact person at current Facility",
   "phone_number_min_error": "Phone number must be at least 10 characters long",
-  "phone_number_must_be_10_digits": "Phone number must be a 10-digit mobile number",
+  "phone_number_required": "Phone number is required",
```
Comment (rithviknishad) [inline public/locale/en.json]: like i said already, `field_required` is sufficient. this validator might be used in Fax/SMS and other purposes as well (as per FHIR) in future (already there in a parallel PR for Devices), so let's use the generic one

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]
