### PR TITLE
Fixed the overflow in appointments section

### LINKED ISSUE #12046: Appointment page overflow
**Describe the bug**
Overflow of parent div in AppointmentsPage (/facility/:facilityId/appointments)

**To Reproduce**
Go to [link](http://localhost:4000/facility/7fa37fb6-91e8-4638-9a76-145062ba91f7/appointments?date_from=2025-04-22&date_to=2025-04-29)

1. Go to '/facility/:facilityId/appointments'
2. Scroll horizontally along the page to see the error (do not scroll on the cards ,that is normal behaviour)

**Expected behavior**
Overflow is not required and is a bug which needs to be fixed

**Screenshots**
[See Issue Video](https://jam.dev/c/aea8ebc4-b1d8-448a-92c9-d8b235963ed0)

**Desktop (please complete the following information):**

- Browser [ chrome]

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Spandan-Mishra**
## Proposed Changes

- Fixes #12046 
- By default `ScrollArea` has min-width:100%. So, I added tailwind classes to restrict it from growing outside container in medium devices. Smaller devices don't face the issue.

@ohcnetwork/care-fe-code-reviewers

https://github.com/user-attachments/assets/e8d8c5b8-943c-4df7-82f7-a81534f627af

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Improved the layout of the appointment board on medium and larger screens for better visual consistency and smoother transitions when toggling the sidebar.

### CODE REVIEW

**Comment by Spandan-Mishra** [comment]
@rithviknishad now it is working correctly for larger and smaller devices.

**Review by yash-learner — CHANGES_REQUESTED** [review]
This issue exists when the sidebar is opened 

image


---

import the useSidebar from shadcn sidebar and use state or open variable and do trail and error to know how to subtract when sidebar is opened may be `24rem` 

may be trail and error better units

File: src/pages/Appointments/AppointmentsPage.tsx [hunk 1]
```diff
@@ -556,7 +558,12 @@ export default function AppointmentsPage({
       </div>
 
       {activeTab === "board" ? (
-        <ScrollArea>
+        <ScrollArea
+          className={cn(
+            `transition-all duration-200 ease-${isSidebarOpen ? "out" : "in"}`,
+            `md:w-[calc(100vw-${isSidebarOpen ? "21.5" : "8"}rem)]`,
+          )}
```
Comment (yash-learner) [inline src/pages/Appointments/AppointmentsPage.tsx]: > The purpose of cn utility is more readability and avoiding the string interpolation

The following is more readable and should work
```suggestion
          className={cn(
            "transition-all duration-200",
            isSidebarOpen 
              ? "ease-out md:w-[calc(100vw-21.5rem)]" 
              : "ease-in md:w-[calc(100vw-8rem)]"
          )}
```

**Review by yash-learner — DISMISSED** [review]
@Spandan-Mishra Did you test your PR before requesting the review?

Looks like because of use of string interpolation inside the `cn` utility did not apply the styles correctly 


image


----


image

File: src/pages/Appointments/AppointmentsPage.tsx (hunk 1 above)
Comment (rithviknishad) [reply src/pages/Appointments/AppointmentsPage.tsx]: not just about readability, this wouldn't work!

https://tailwindcss.com/docs/detecting-classes-in-source-files#dynamic-class-names

**Comment by Spandan-Mishra** [comment]
@yash-learner I had tested the changes and it was working correctly, but as you and @rithviknishad suggested, that approach wasn't correct.
I didn't know about string interpolation issues 😅, it is fixed now

**Comment by yash-learner** [comment]
> @yash-learner I had tested the changes and it was working correctly

@Spandan-Mishra, did you test after fixing for sidebar?

---

> but as you and @rithviknishad suggested, that approach wasn't correct.

Which approach 🤔  ---> String interpolation ?

**Comment by Spandan-Mishra** [comment]
@yash-learner yes it was working fine after fixing for sidebar too.

Using string interpolation was incorrect, according to the tailwind docs. I don't know how, but it was working locally 😅

**Review by rithviknishad — APPROVED** [review]

**Comment by rithviknishad** [comment]
> Using string interpolation was incorrect, according to the tailwind docs. I don't know how, but it was working locally 😅

so how tailwind works is, tailwind's JIT compiler compiles all the vaid tailwind classes detected by scanning your codebase. If similar classes were used elsewhere in the codebase, that'd work cause it to work here by string interpolation. But that does not guarantee it to work here always. If the other thing was ever changed, it'd start breaking here as tailwind would omit compiling it as it assumes it's no longer there in the codebase.

Tailwinds tool cannot detect classes if string interpolated.

**Comment by Spandan-Mishra** [comment]
@rithviknishad thanks! this was helpful
