### PR TITLE
Fixed responsive issue in resource page and user page

### LINKED ISSUE #6045: Responsive issue in resource page and user page
**Describe the bug**

- transportation to be arranged card in the resource tab, is overflowing in the normal view
- contents in the card and the buttons of the user tab is overflowing in the normal view

**note:**
It is happening only in laptop with 150% display scale (recommended settings for all new windows laptop) and having a 14 inch screen size

**To Reproduce**

1. Go to https://care.ohc.network/users?page=1&limit=18&first_name=&last_name=&phone_number=&alt_phone_number=&user_type=&district_id
2. Go to https://care.ohc.network/resource
3. See error

**Expected behavior**

- both places, the dates should not overflow the boarders

**Screenshots**

image

image

### PR DESCRIPTION
**Pull request by GokulramGHV**
### <samp>🤖 Generated by Copilot at cc164a0</samp>

This pull request enhances the responsiveness and adaptability of the user card and resource board components by using container-based media queries with Tailwind CSS. It adds the `@tailwindcss/container-queries` dependency and updates the `className` props and `@container` classes in `ManageUsers.tsx`, `ResourceBoard.tsx`, and `ResourceBoardView.tsx`.

## Proposed Changes

- Fixes #6045 
- Added `container-queries` taliwind plugin
- Fixed responsiveness issue in resource page and user page

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at cc164a0</samp>

*  Add `@tailwindcss/container-queries` dependency to enable container-based media queries in Tailwind CSS ([link](https://github.com/coronasafe/care_fe/pull/6067/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R114))
*  Apply `@container` class to `ScrollingComponent` elements that wrap resource board and resource board view components ([link](https://github.com/coronasafe/care_fe/pull/6067/files?diff=unified&w=0#diff-72363d4a4cc81142bd2db278c3c1e17ee14614fc4be0af317cc60db25f4be79cL82-R82), [link](https://github.com/coronasafe/care_fe/pull/6067/files?diff=unified&w=0#diff-1e7c872c4cfd3f62fe97afd8a5d429b463efb0371560b9d1c78d1f10b80af64dL237-R237))
*  Replace fixed width classes with container-based width classes for resource board component to make it more responsive and adaptive to different screen sizes and resolutions ([link](https://github.com/coronasafe/care_fe/pull/6067/files?diff=unified&w=0#diff-1e7c872c4cfd3f62fe97afd8a5d429b463efb0371560b9d1c78d1f10b80af64dL237-R237))
*  Replace fixed flex direction classes with container-based flex direction classes for user card component and its child elements to make them more responsive and adaptive to different screen sizes and resolutions ([link](https://github.com/coronasafe/care_fe/pull/6067/files?diff=unified&w=0#diff-a6a7ab3af39c9e2846bc2d69312a095aa77957d33c31ea4c0a70c034dfdfa121L223-R227), [link](https://github.com/coronasafe/care_fe/pull/6067/files?diff=unified&w=0#diff-a6a7ab3af39c9e2846bc2d69312a095aa77957d33c31ea4c0a70c034dfdfa121L408-R411))
*  Remove redundant `div` element that adds unnecessary space between buttons for linked facilities and skills in user card component ([link](https://github.com/coronasafe/care_fe/pull/6067/files?diff=unified&w=0#diff-a6a7ab3af39c9e2846bc2d69312a095aa77957d33c31ea4c0a70c034dfdfa121L420-R422))

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

File: src/Components/Resource/ResourceBoardView.tsx [hunk 1]
```diff
@@ -79,7 +79,7 @@ export default function BoardView() {
       </div>
 
       <BadgesList {...{ appliedFilters, FilterBadges }} />
-      <ScrollingComponent className="mt-4 flex flex-1 items-start overflow-x-scroll px-4 pb-2">
+      <ScrollingComponent className="mt-4 flex flex-1 items-start overflow-x-scroll px-4 pb-2 @container">
```
Comment (khavinshankar) [inline src/Components/Resource/ResourceBoardView.tsx:82]: why are we using a container here, we are not using any queries in the child! 🤔

Comment (GokulramGHV) [reply src/Components/Resource/ResourceBoardView.tsx:82]: this `@container` is for the div inside `src/Components/Resource/ResourceBoard.tsx`
check here: https://github.com/coronasafe/care_fe/pull/6067/files#:~:text=%3Cdiv-,%3Cdiv,className%3D%7BclassNames(,-%22mr%2D2%20h

**Review by khavinshankar — APPROVED** [review]
