### PR TITLE
FIXED:- Improve Visibility of Status, Role, and Contact numbers on User Management Page List View for Mobile Screens

### LINKED ISSUE #10396: Improve Visibility of Status, Role, and Contact numbers on User Management Page List View for Mobile Screens
**Describe the bug**
On the User Management page in list view, the status, role, and contact number of users are not clearly visible on mobile screens. leading to poor readability and user experience.

**To Reproduce**

[Click here to reproduce](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/users)

 See error

**Expected behavior**
The status, role, and contact numbers of users should be clearly visible on mobile screen

**Screenshots**

https://github.com/user-attachments/assets/96ee494d-457d-4d2e-93f1-ce283a3b4587

Expected behaviour

https://github.com/user-attachments/assets/493693a8-1a92-4cd5-92da-a91b423e09c8

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [132.0.6834.111]

**Additional context**

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes

- Fixes #10396 
- Change 1
- 

https://github.com/user-attachments/assets/c6747414-71ad-429f-973f-1d51320e8285

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style**
  - Updated the visual presentation of user list headers and cells by simplifying their design.
  - Adjusted the table layout, removing the sticky positioning and background highlights, which may affect scrolling behavior.

### CODE REVIEW

File: src/components/Users/UserListAndCard.tsx [hunk 1]
```diff
@@ -133,9 +133,7 @@ const UserListHeader = () => {
   return (
     <thead>
       <tr className="bg-gray-50 text-sm font-medium text-gray-500">
-        <th className="sticky left-0 z-10 bg-gray-50 px-4 py-3 text-left">
-          {t("name")}
-        </th>
+        <th className=" bg-gray-50 px-4 py-3 text-left">{t("name")}</th>
```
Comment (Jacobjeevan) [inline src/components/Users/UserListAndCard.tsx]: rm the bg here as well

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
