### PR TITLE
Fix UI misalignment in Appointment Details card (#12100)

### LINKED ISSUE #12100: UI in the Appointment Details section breaks when the card is saved, affecting fields like Phone, Token No., and Gender.
**Describe the bug**
UI in the Appointment Details section breaks when the card is saved, affecting fields like Phone, Token No., and Gender.

**To Reproduce**

1. Go to the Appointment Details section.
2. Click on Save.
3. In the saved image, some UI elements are misaligned or mismatched.

**Expected behavior**

Image

**Screenshots**
The Phone, Token, and Gender fields are mismatched and misaligned.

Image

**Desktop (please complete the following information):**

- OS: Ubuntu 24.04.2 LTS x86_64
- Browser: Brave
- Version Latest

**Smartphone (please complete the following information):**

- Device: Realme C11
- OS: Android
- Browser: Chrome
- Version Latest

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by prajapatiomkar**
## Proposed Changes

- Fixes #12100
- Added the css property in the respective element

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Improved text display in appointment cards by preventing line breaks for phone numbers, patient details, and token labels, ensuring these elements remain on a single line.
  - Updated token number label to support localization for better language adaptability.

### CODE REVIEW

File: src/pages/Appointments/components/AppointmentTokenCard.tsx [hunk 1]
```diff
@@ -51,15 +51,15 @@ const AppointmentTokenCard = ({ id, appointment, facility }: Props) => {
...
               {formatPatientAge(patient, true)},{" "}
               {t(`GENDER__${patient.gender}`)}
             </p>
           </div>
 
           <div className="flex items-center gap-2">
             <div>
-              <Label className="text-black font-semibold text-sm/none">
+              <Label className="text-black font-semibold text-sm/none whitespace-nowrap">
                 Token No.
```
Comment (AdityaJ2305) [inline src/pages/Appointments/components/AppointmentTokenCard.tsx]: Hey , Could you please i18n for Token No. and give a check if it is missing on other places in same file

Comment (prajapatiomkar) [reply src/pages/Appointments/components/AppointmentTokenCard.tsx]: Sure.

**Review by rithviknishad — APPROVED** [review]
