### PR TITLE
Fix: Add a new map view to the locations section of a facility settings

### LINKED ISSUE #10377: Add a new map view to the locations section of a facility settings
**Describe the Issue**

Add a new map view to the location section in the facility settings

**Link to Figma**

https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=7769-8270&t=lATfj2xH4or01kbE-1

*Existing Design*

Image

*New Design*

Image

### PR DESCRIPTION
**Pull request by abhimanyurajeesh**
## Proposed Changes

- Fixes #10377 

## Key Features
1. Hierarchical Display
2. Interactive Navigation
3. Dynamic Search
4. Expandable/Collapsible Nodes
5. Drag and Drop Support
6. Auto-fit View

##

- I have created a facility **PHC Location Map/List** for the testing and demo purpose.

https://github.com/user-attachments/assets/bb05107a-961b-4461-a643-895f0583c723

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Introduced an interactive mapping interface for visualizing facility locations, allowing users to switch between a list view and a map view.
  - Added a new localized label ("Level Inside") to enhance language consistency within the application.
  - Introduced a new component for displaying location information in a responsive card format.

- **Refactor**
  - Enhanced location filtering and data refresh mechanisms for a smoother user experience.
  - Streamlined icon display for location types to ensure a consistent and intuitive visual presentation.
  - Added a new dependency for improved interactive UI capabilities.

### CODE REVIEW

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 1]
```diff
@@ -60,6 +64,13 @@ export default function LocationList({ facilityId }: Props) {
     topLevelLocations: LocationListType[];
   }>({ childrenMap: new Map(), topLevelLocations: [] });
 
+  const { data: facilityData } = useQuery<FacilityData>({
```
Comment (rithviknishad) [inline src/pages/Facility/settings/locations/LocationList.tsx]:
```suggestion
  const { data: facilityData } = useQuery({
```

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 2]
```diff
@@ -192,10 +232,72 @@ export default function LocationList({ facilityId }: Props) {
...
+                      className="h-4 w-4 mx-1"
+                    />
+                  ),
+                  PenLine: <PenLine className="h-4 w-4 mx-1" />,
+                }}
+              />
+            </div>
+          </div>
+        </div>
+      </div>
```
Comment (rithviknishad) [inline src/pages/Facility/settings/locations/LocationList.tsx]: let's not inline define react components inside a react component

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 3]
```diff
@@ -242,72 +342,16 @@ export default function LocationList({ facilityId }: Props) {
...
-                        PenLine: <PenLine className="h-4 w-4 mx-1" />,
-                      }}
-                    />
-                  </div>
-                </div>
-              </div>
-            </div>
+          {activeTab === "list" ? (
+            renderListView()
+          ) : (
```
Comment (rithviknishad) [inline src/pages/Facility/settings/locations/LocationList.tsx]: do similar to how location map is done;

File: src/types/location/location.ts [hunk 4]
```diff
@@ -59,3 +71,21 @@ export const LocationFormOptions = [
...
+  co: Building2, // corridor
+  ro: Home, // room
+  ve: Car, // vehicle
+  ho: Home, // house
+  ca: Car, // carpark
+  rd: Car, // road
+  area: Map, // area
+  jdn: Map, // garden
+  vi: Eye, // virtual
+} as const;
```
Comment (rithviknishad) [inline src/types/location/location.ts]:
```suggestion
} as const satisfies Record<LocationForm, ReactNode>;
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/locations/LocationList.tsx (hunk 1 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: done

File: src/pages/Facility/settings/locations/LocationList.tsx (hunk 2 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: done changing it

File: src/pages/Facility/settings/locations/LocationList.tsx (hunk 3 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx]: yap done

File: src/types/location/location.ts (hunk 4 above)
Comment (abhimanyurajeesh) [reply src/types/location/location.ts]: okayyyy

File: src/pages/Facility/settings/locations/LocationMap.tsx [hunk 5]
```diff
@@ -0,0 +1,489 @@
...
+  }, [
+    locations,
+    expandedNodes,
+    toggleNode,
+    onLocationClick,
+    t,
+    nodePositions,
+    rootLocations,
+    facilityName,
+  ]);
```
[the remark this answers is not in the document]
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationMap.tsx]: done

**Review by rithviknishad — APPROVED** [review]
quick pass, lgtm

File: src/pages/Facility/settings/locations/components/LocationCard.tsx [hunk 6]
```diff
@@ -32,41 +23,9 @@ interface Props {
...
-      case "area": // area
-        return <Map className="h-5 w-5" />;
-      case "jdn": // garden
-        return <Map className="h-5 w-5" />;
-      case "vi": // virtual
-        return <Eye className="h-5 w-5" />;
-      default:
-        return <Folder className="h-5 w-5" />;
-    }
+  const getLocationTypeIcon = (form: LocationForm) => {
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/locations/components/LocationCard.tsx]: move to location.ts since it's used in multiple files

File: src/pages/Facility/settings/locations/LocationMap.tsx [hunk 7]
```diff
@@ -0,0 +1,572 @@
...
+      {hasChildren && (
+        <>
+          <div className="absolute -bottom-2 left-1/2 -translate-x-1/2 w-[93%] h-full border-2 border-gray-200 rounded-lg bg-white" />
+          <div className="absolute -bottom-1 left-1/2 -translate-x-1/2 w-[97%] h-full border-2 border-gray-200 rounded-lg bg-white" />
+        </>
+      )}
+      <div
+        onClick={() => data.onClick({ id: data.id })}
+        className={cn(
+          "relative w-[240px] bg-white rounded-lg border-2 overflow-hidden shadow-sm cursor-pointer",
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/locations/LocationMap.tsx:75]: There's a few instances of width being specified explicitly like this, see if you can use relative widths instead.

**Review by Jacobjeevan — DISMISSED** [review]
Overall, looks good so far.

The behavior on expanding a node isn't ideal 🤔  Right now, it zooms out and focuses on the entire tree; it would be better if it focuses on the node that is being expanded (zooming in if needed).

File: src/pages/Facility/settings/locations/LocationMap.tsx (hunk 7 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationMap.tsx:75]: we can but it would look a bit odd.

**Comment by abhimanyurajeesh** [comment]
> The behavior on expanding a node isn't ideal 🤔 Right now, it zooms out and focuses on the entire tree; it would be better if it focuses on the node that is being expanded (zooming in if needed).

Just focus on the node that is being expanded or did you mean the child nodes of the parent?

**Comment by abhimanyurajeesh** [comment]
> > The behavior on expanding a node isn't ideal 🤔 Right now, it zooms out and focuses on the entire tree; it would be better if it focuses on the node that is being expanded (zooming in if needed).
> 
> Just focus on the node that is being expanded or did you mean the child nodes of the parent?

@Jacobjeevan did you mean like this?

https://github.com/user-attachments/assets/2cd62b9b-3048-4f5b-aede-b5aa118dde3c

File: src/pages/Facility/settings/locations/LocationMap.tsx [hunk 8]
```diff
@@ -0,0 +1,572 @@
...
+
+const CustomNode = ({ data }: NodeProps) => {
+  const { t } = useTranslation();
+  const hasChildren = data.childCount > 0;
+
+  const handleToggle = (e: React.MouseEvent) => {
+    e.stopPropagation();
+    data.onToggle(data.id);
+  };
+
```
Comment (rithviknishad) [inline src/pages/Facility/settings/locations/LocationMap.tsx:51]:
```suggestion
  const Icon = LocationTypeIcons[form] || Folder;
```

File: src/pages/Facility/settings/locations/LocationMap.tsx [hunk 9]
```diff
@@ -0,0 +1,572 @@
...
+          "relative w-[240px] bg-white rounded-lg border-2 overflow-hidden shadow-sm cursor-pointer",
+          "border-gray-200",
+          "hover:border-primary/50 hover:shadow-lg",
+          "transition-all duration-200",
+        )}
+      >
+        <div className="p-4">
+          <div className="flex items-center gap-3">
+            <div className="p-2 bg-primary/10 rounded-md shrink-0">
+              {getLocationTypeIcon(data.form)}
```
Comment (rithviknishad) [inline src/pages/Facility/settings/locations/LocationMap.tsx]:
```suggestion
              <Icon className="h-5 w-5" />
```

File: src/pages/Facility/settings/locations/components/LocationCard.tsx (hunk 6 above)
Comment (rithviknishad) [reply src/pages/Facility/settings/locations/components/LocationCard.tsx]: @abhimanyurajeesh i'd say do https://github.com/ohcnetwork/care_fe/pull/10821#pullrequestreview-2655919025 here instead

Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/components/LocationCard.tsx]: Thank you, will try that

File: src/pages/Facility/settings/locations/LocationMap.tsx (hunk 9 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationMap.tsx]: thank you

File: src/pages/Facility/settings/locations/LocationMap.tsx (hunk 8 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationMap.tsx:51]: thank you

**Comment by Jacobjeevan** [comment]
> > > The behavior on expanding a node isn't ideal 🤔 Right now, it zooms out and focuses on the entire tree; it would be better if it focuses on the node that is being expanded (zooming in if needed).
> > 
> > 
> > Just focus on the node that is being expanded or did you mean the child nodes of the parent?
> 
> @Jacobjeevan did you mean like this?
> Screen.Recording.2025-03-04.at.9.01.33.AM.mov

Somewhat 🤔  On expansion, it still zooms out for a second there (0:08 onwards..instead of just zooming in directly to focus on the node that's expanded).

On collapse, focus on node's (that's being collapsed) parent.

**Comment by abhimanyurajeesh** [comment]
> > > > The behavior on expanding a node isn't ideal 🤔 Right now, it zooms out and focuses on the entire tree; it would be better if it focuses on the node that is being expanded (zooming in if needed).
> > > 
> > > 
> > > Just focus on the node that is being expanded or did you mean the child nodes of the parent?
> > 
> > 
> > @Jacobjeevan did you mean like this?
> > Screen.Recording.2025-03-04.at.9.01.33.AM.mov
> 
> Somewhat 🤔 On expansion, it still zooms out for a second there (0:08 onwards..instead of just zooming in directly to focus on the node that's expanded).
> 
> On collapse, focus on node's (that's being collapsed) parent.

Oh ya got it.

**Comment by abhimanyurajeesh** [comment]
https://github.com/user-attachments/assets/d0b0bbce-8f53-4405-b974-0e34ba16ea5a

@Jacobjeevan can you please check this out? I hope this will do 🫡

**Comment by Jacobjeevan** [comment]
> Screen.Recording.2025-03-04.at.4.34.00.PM.mov
> 
> @Jacobjeevan can you please check this out? I hope this will do 🫡

Great 👍 

- Root doesn't allow expansion/collapse..is that intended? 🤔  If so, we should disable the button and hide the chevron.
- Since we are allowing users to move the nodes around, expand/collapse should preserve their current position, no? Instead it resets it 🤔 

Well, not a big deal per say, depends on what we want product side.

**Comment by abhimanyurajeesh** [comment]
> Great 👍
> 
>  1. Root doesn't allow expansion/collapse..is that intended? 🤔  If so, we should disable the button and hide the chevron.
> 
> 2. Since we are allowing users to move the nodes around, expand/collapse should preserve their current position, no? Instead it resets it 🤔
> 
> 
> Well, not a big deal per say, depends on what we want product side.


1. Yeah, the root doesn’t allow expansion/collapse, so I’ll hide the chevron.
2. Good point it depends on what we want from the product side. If needed, we could add a button to reset the node, though it’s not mandatory.

I guess for now, I’ll quickly hide the chevron for the root.

**Comment by nihal467** [comment]
Issue need to taken as a separate PR

image

- [ ] Preserve the current map view after updating a location via the SlideOver. Currently, the view resets to the default state after an update.

image

- [ ] Display the full name of the facility whenever there is enough space based on the viewport. If truncation is necessary, show a tooltip on hover to reveal the full facility name.
- [ ] Update the folder icon next to the facility name to use the facility icon for design consistency.

Product Enhancement (Post User requirement after understanding scope)

image
image

- The custom-set card location on the map is not preserved, and the user loses it upon refreshing the page.

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 10]
```diff
@@ -77,20 +87,48 @@ export default function LocationList({ facilityId }: Props) {
...
+        while (current.parent?.id) {
+          matchedLocations.add(current.parent.id);
+          const parent = data?.results?.find(
+            (loc) => loc.id === current.parent?.id,
+          );
+          if (!parent) break;
+          current = parent;
+        }
+      }
+    });
```
Comment (khavinshankar) [inline src/pages/Facility/settings/locations/LocationList.tsx:125]: what is this doing; isn't this redundant?

File: src/pages/Facility/settings/locations/LocationList.tsx [hunk 11]
```diff
@@ -77,20 +87,48 @@ export default function LocationList({ facilityId }: Props) {
...
+
+    return (
+      data?.results?.filter((location) => matchedLocations.has(location.id)) ||
+      []
```
Comment (khavinshankar) [inline src/pages/Facility/settings/locations/LocationList.tsx:129]: why are we filtering, we could directly return the matchedLocations as an array?

**Review by khavinshankar — COMMENTED** [review]
need clarification @abhimanyurajeesh

**Review by khavinshankar — APPROVED** [review]

File: src/pages/Facility/settings/locations/LocationList.tsx (hunk 10 above)
Comment (abhimanyurajeesh) [reply src/pages/Facility/settings/locations/LocationList.tsx:125]: resolved.
