### PR TITLE
Patient Detail Tabs: Org List Access

### LINKED ISSUE #10109: Facility ID is undefined in Patient Details for Staff
Describe the bug 

- `Appointments` tab shows loading even after requests have failed to fetch the data, it should be more user-friendly 

Image

- facilityId is undefined in the URL

Image

Steps to reproduce

- Go to Dashboard > Staff > Patients > Click on any Patient > Appointments

Click [here](https://care.ohc.network/facility/undefined/patient/6f45380f-0f50-40ce-a0e2-13c4e7706280/appointments) to reproduce

### PR DESCRIPTION
**Pull request by Jacobjeevan**
## Proposed Changes

- Fixes #10109 
   - Use a sep list to render tabs for patient page when accessed directly (i.e. without related facility Id, from an org listing page, i.e.: url would be patient/id rather than facility/facilityId/patient/id).
   -  Allowing patient detail edit on above access (i.e. edit button on patient details page used to be facility specific).
   - Hides appointments tab for direct patient listing (appointments are facility specific).
   - All the other tabs are not facility exclusive, so keeping them but let me know if I missed something.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Release Notes

- **New Features**
  - Added a new route for patient updates.
  - Enhanced patient tab navigation with facility-specific routing.

- **Improvements**
  - Updated patient registration process to handle optional facility ID.
  - Improved localization with a new "No updates found" message.
  - Refined patient home and details tab navigation logic.

- **Bug Fixes**
  - Resolved routing inconsistencies in patient-related components.

### CODE REVIEW

File: src/components/Patient/PatientDetailsTab/index.tsx [hunk 1]
```diff
@@ -50,3 +46,14 @@ export const patientTabs = [
...
 ];
+
+export const facilityPatientTabs = [
+  commonTabs[0],
+  {
+    route: "appointments",
+    component: Appointments,
+  },
+  ...commonTabs.slice(1),
+];
```
Comment (rithviknishad) [inline src/components/Patient/PatientDetailsTab/index.tsx]: works, but not a fan of this :)

**Review by rithviknishad — APPROVED** [review]
