### PR TITLE
Fixed routes for edit and cancel in Product Knowledge

### LINKED ISSUE #13932: Edit button in product knowledge list and cancel in product knowledge form does not navigate correctly
**Describe the bug**
In Product Knowledge page, when clickinig `Edit Product Knowledge` button in the table, user is navigated to `Product Knowledge Detials` page rather than the edit form. 
When clicking on `cancel` button in the Product Knowledge form, user is redirected back to a invalid route

**To Reproduce**

1. Go to 'Product Knowledge'
2. Click on 'Edit Product Knowledge'
3. Scroll down to 'Cancel'

**Expected behavior**
Must be redirected to correct paths

**Screenshots**

https://github.com/user-attachments/assets/f56f734a-e406-4183-8bb8-7427c2fcb3f4
https://github.com/user-attachments/assets/495ed417-bc7e-43a4-b19e-20ee243ccab8

**Desktop (please complete the following information):**

- OS: Win 10
- Browser Opera
- Version latest

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by GSMPRANEETH**
## Proposed Changes

Fixes #13932
- Changed route in PKListComps for edit to take to edit page
- Changed route in PKForm for cancel to take back to PKDetails when editing else back to categories while creating

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

* **New Features**
  * Product Knowledge form cancel is now context-aware: when editing it returns to the item details; when creating it returns to the relevant category list.
  * From the Product Knowledge list, the Edit action now opens a dedicated edit page so viewing and editing are separate.
* **Behavior Change**
  * Edit action on mobile cards uses a compact icon-only interaction; “See details” remains unchanged.

### CODE REVIEW

File: src/pages/Facility/settings/productKnowledge/ProductKnowledgeListComponent.tsx [hunk 1]
```diff
@@ -172,7 +172,7 @@ function ProductKnowledgeTableRow({
                   size="sm"
                   onClick={() =>
                     navigate(
-                      `/facility/${facilityId}/settings/product_knowledge/${product.slug}`,
+                      `/facility/${facilityId}/settings/product_knowledge/${product.slug}/edit`,
                     )
                   }
```
Comment (rithviknishad) [inline src/pages/Facility/settings/productKnowledge/ProductKnowledgeListComponent.tsx]: let's try to follow this convention whenever we are doing anything related to button's that are simply always performing navigations directly to a link and nothing else. this way users would be able to right click and open in new tab as well if needed.

refer: https://ui.shadcn.com/docs/components/button

Image

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/productKnowledge/ProductKnowledgeListComponent.tsx (hunk 1 above)
Comment (GSMPRANEETH) [reply src/pages/Facility/settings/productKnowledge/ProductKnowledgeListComponent.tsx]: implemented as suggested

**Review by rithviknishad — APPROVED** [review]
