### PR TITLE
Remove duplicate age

### LINKED ISSUE #9922: Incorrect Patient Age displayed on Appointment page
Click [here](https://care.ohc.network/facility/03560a09-121e-451a-a73a-64240cbfb1ae/patient/77cfd623-b402-47e8-af48-3e66810fdb3a/appointments/dbfb3204-0a1d-4375-9a0e-26ea9689652a) to reproduce
Image
Age can be correctly displayed using existing data.

### PR DESCRIPTION
**Pull request by rajku-dev**
## Proposed Changes

- Fixes #9922 
- Removed rendering age two times 

BEFORE
image

AFTER
image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **UI/UX Improvements**
	- Simplified patient information display in Appointment Details
	- Updated age and date of birth presentation to be more concise and readable

### CODE REVIEW

File: src/pages/Appointments/AppointmentDetail.tsx [hunk 1]
```diff
@@ -291,22 +291,13 @@ const AppointmentDetails = ({
...
                   <>
-                    {format(appointment.patient.date_of_birth, "MMMM d, yyyy")}{" "}
+                    {format(appointment.patient.date_of_birth, "MMMM d, yyyy")}
+                    {" | "}
                     {differenceInYears(
                       new Date(),
                       appointment.patient.date_of_birth!,
                     )}
                   </>
-                )}
```
Comment (Jacobjeevan) [inline src/pages/Appointments/AppointmentDetail.tsx:300]: So, patient can register with either year of birth or date of birth. If they fill out date of birth, BE will automatically populate year of birth as well.

If they only provide year of birth, date of birth will be unpopulated. So you will have to add this back and only trigger it if date of birth isn't available.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Appointments/AppointmentDetail.tsx (hunk 1 above)
Comment (rajku-dev) [reply src/pages/Appointments/AppointmentDetail.tsx:300]: made the changes as requested

**Review by rithviknishad — CHANGES_REQUESTED** [review]
code is not readable. use ternary operator instead

**Comment by rajku-dev** [comment]
> code is not readable. use ternary operator instead

note taken, will take care of that,
Also i think 

we are keeping both fields(`year_of_birth` and `date_of_birth`) optional in type
though we know at least one of the fields will definitely be present
in this case we should use discriminated union

**Comment by rithviknishad** [comment]
doesn't backend always give you the year_of_birth? (correct me if im wrong)

**Comment by rajku-dev** [comment]
> doesn't backend always give you the year_of_birth? (correct me if im wrong)

I created a patient with just `date_of_birth` and found that backend always provides the `year_of_birth`.

**Comment by rithviknishad** [comment]
so does the discriminated union makes sense anymore?

File: src/pages/Appointments/AppointmentDetail.tsx [hunk 2]
```diff
@@ -289,16 +289,16 @@ const AppointmentDetails = ({
...
                     {format(appointment.patient.date_of_birth, "MMMM d, yyyy")}{" "}
+                    |{" "}
                     {differenceInYears(
                       new Date(),
                       appointment.patient.date_of_birth!,
                     )}
                   </>
-                )}
-                {appointment.patient.year_of_birth && (
+                ) : appointment.patient.year_of_birth ? (
```
Comment (rithviknishad) [inline src/pages/Appointments/AppointmentDetail.tsx]: wouldn't year of birth always be present? do we need to check if null?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Appointments/AppointmentDetail.tsx (hunk 2 above)
Comment (rajku-dev) [reply src/pages/Appointments/AppointmentDetail.tsx]: Sorry, I forgot to push it, i fixed(commited) that already

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
