### PR TITLE
Fixed scroll issue in Shifting and Resource

### LINKED ISSUE #7487: Scroll issue in shifting in facilities.
**Issue**
In shifting in facilities, the scroll is common for all the fields like destination approved, transportation arranged, transferin progress , etc. This leads to an issue that if one field has more patients than others, the scroll for others goes below the max no if patients in that. If any one has 100 patients, others have 2 each, after viewing 100th patient of one, you need to scroll back up for the entire to view the ones for other fields. This is a UI issue and needs to be addressed.
@rithviknishad @nihal467 

issue

**Solution**
Separate scroll for each field like destination approved, transportation arranged, transfer-in progress , etc.

### LINKED ISSUE #9334: Infinite Scrolling on Resource Page
**Describe the bug**
On Resources page there is repeated rendering of resource cards, although the counted is a finite number

**To Reproduce**

1. Go to '/resource/board'
2. Scroll down
3. See error

**Expected behavior**
This repeated rendering needs to be fixed

**Screenshots**
https://github.com/user-attachments/assets/f7435dcd-431d-42cd-8e10-01a563f2835b

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser - Chrome
- Version 131.0.6778.86 (Official Build) (64-bit)

**Additional context**

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #7487
- Fixes #9334

- Fetches all set of cards 

@ohcnetwork/care-fe-code-reviewers

https://github.com/user-attachments/assets/a0b81435-e5bf-482b-a063-ba98d8c837e7

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced horizontal scrolling for the Kanban board.
	- Improved pagination with infinite scrolling functionality.

- **Bug Fixes**
	- Streamlined error handling for data fetching.

- **Refactor**
	- Simplified state management and rendering logic in the Kanban components.

### CODE REVIEW

**Comment by Jeffrin2005** [comment]
@rithviknishad I have made the changes. Please Let me know if any further modification needs.

File: src/components/Kanban/Board.tsx [hunk 1]
```diff
@@ -9,10 +9,14 @@ import { useTranslation } from "react-i18next";
...
 import CareIcon from "@/CAREUI/icons/CareIcon";
 
+import { ScrollArea } from "@/components/ui/scroll-area";
+
 import request from "@/Utils/request/request";
 import { QueryRoute } from "@/Utils/request/types";
 import { QueryOptions } from "@/Utils/request/useQuery";
 
+// Adjust the path if necessary
+
```
Comment (rithviknishad) [inline src/components/Kanban/Board.tsx]:
```suggestion
```

**Review by rithviknishad — APPROVED** [review]

**Comment by AdityaJ2305** [comment]
Hey @Jeffrin2005, it’s not fetching beyond the default limit on scroll anymore, which it was doing previously.

cc: @rithviknishad

File: src/components/Kanban/Board.tsx [hunk 2]
```diff
@@ -159,7 +156,7 @@ export function KanbanSection<T extends { id: string }>(
               </div>
             </div>
           </div>
-          <div ref={sectionRef}>
+          <ScrollArea className="h-[calc(100vh-250px)]">
```
Comment (rithviknishad) [inline src/components/Kanban/Board.tsx:159]:
```suggestion
          <ScrollArea className="h-[calc(100vh-250px)]" ref={sectionRef}>
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]
fix the issue mentioned before requesting review

**Comment by Jeffrin2005** [comment]
> fix the issue mentioned before requesting review

@rithviknishad I have committed the changes, but due to some errors, the commits are not showing up. I will close this PR and raise a new one with the updated changes.

**Comment by Jacobjeevan** [comment]
> > fix the issue mentioned before requesting review
> 
> @rithviknishad I have committed the changes, but due to some errors, the commits are not showing up. I will close this PR and raise a new one with the updated changes.

Try to salvage this rather than opening a new PR  - since you haven't force pushed yet, you should be able to use git revert to rollback recent changes and then merge/and push once more.

**Comment by Jeffrin2005** [comment]
@Jacobjeevan I've encountered some errors while trying to update my PR. Unfortunately, it led to the PR being closed unexpectedly from my Git. While trying to revert and delete the commit, it caused the PR to close. Sorry for stretching the time. I'll close it and raise a new one with the updated changes.

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan, can we reopen this PR?

**Comment by rithviknishad** [comment]
contributors do have permissions to re-open PRs. It maybe disabled if the branch is deleted.

image

**Comment by rithviknishad** [comment]
a

**Comment by Jacobjeevan** [comment]
> contributors do have permissions to re-open PRs. It maybe disabled if the branch is deleted.
> 
> image



Since I've seen a few contributors have this issue where branch is being deleted - not sure what they are doing there 😅 - want to check if [this](https://dev.to/mreigen/how-to-restore-recreated-a-deleted-remote-git-branch-1o1f) works.

@Jeffrin2005  Create a new branch with the same name and SHA of the most recent commit (`e1c61d65b8ad3dd5b895f105286109921858d4e0` in your case) and push to it. Let's see if it allows you to reopen the PR.

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan, as per the issue raised by @AdityaJ2305, I've updated board.tsx. Now, all sets of cards are being fetched. I've also updated the video. Any errors in this?

File: src/components/Kanban/Board.tsx [hunk 3]
```diff
@@ -96,44 +94,42 @@ export function KanbanSection<T extends { id: string }>(
...
+          ...options.options?.query,
+          offset: offsetToUse,
+          limit: defaultLimit,
+        },
+      });
+      const newPages = refresh ? [] : [...pages];
+      const page = Math.floor(offsetToUse / defaultLimit);
+      if (res.error) {
+        console.error("Error fetching data:", res.error);
+        return;
```
Comment (rithviknishad) [inline src/components/Kanban/Board.tsx]: let's use [useInfiniteQuery](https://tanstack.com/query/latest/docs/framework/react/reference/useInfiniteQuery#useinfinitequery)

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by Jeffrin2005** [comment]
@rithviknishad Hi, Used useInfiniteQuery, but there is a slight issue while fetching. A slight delay is occurring, as you can see in this clip. 

https://github.com/user-attachments/assets/e14e6dfc-debd-42bc-82c1-8f4b9dd1ad49

**Comment by rithviknishad** [comment]
That's fine, it's just time spent on fetching the data right. And we are showing the loading state. Expected.

File: src/components/Kanban/Board.tsx [hunk 4]
```diff
@@ -74,114 +75,123 @@ export default function KanbanBoard<T extends { id: string }>(
...
+    const options = section.fetchOptions(section.id);
+    try {
+      const response = await request(options.route, {
+        ...options.options,
+        query: {
+          ...options.options?.query,
+          offset: pageParam,
+          limit: defaultLimit,
+        },
+      });
```
Comment (rithviknishad) [inline src/components/Kanban/Board.tsx]: can we switch to using `callApi` or `query` instead? This will do the handling of errors for you and appropriately show notifications if needed using the queryClient declared globally.

File: package.json
Comment (rithviknishad) [inline package.json:1]: can we not change the packages and package-lock file in this PR?

**Review by rithviknishad — CHANGES_REQUESTED** [review]
lgtm, some minor things

**Comment by Jeffrin2005** [comment]
@rithviknishad Used "callApi" instead of "request". Any changes needed ?

**Comment by Jeffrin2005** [comment]
@rithviknishad Used "callApi" instead of "request". Any changes needed ?

**Comment by rithviknishad** [comment]
not done: https://github.com/ohcnetwork/care_fe/pull/9475/files#r1893836229

**Comment by Jeffrin2005** [comment]
@rithviknishad Since I tried to revert the package. json file and re-update it, which led to the deployment failing, I updated it and committed the updated package-lock. from the latest branch. Can you review it?

**Comment by rithviknishad** [comment]
the deploy failed coz the package.json was deleted. instead of deleting, just revert the changes.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Comment by nihal467** [comment]
LGTM, @rithviknishad @khavinshankar you can ignore the failure
