### PR TITLE
Fixed the unresponsive behaviour of UI in sample test page

### LINKED ISSUE #2482: Ui of "sample test" page unresponsive in mobile
# Bugs

## 1)  Ui of "sample test" page seems to be unresponsive in mobile a bit.

https://user-images.githubusercontent.com/59426397/169697577-603d93f9-89b4-413e-9919-ead7b7ff6af0.mp4

## 2)  "Update sample test status" modal unresponsive in mobile
Screenshot from 2022-05-22 13-29-01

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #2482 

# Bugs Fixed

## 1) Fixed Ui of "sample test" page unresponsive behaviour in mobile

https://user-images.githubusercontent.com/59426397/169698041-8294ba25-4c36-469d-9876-c27fcf951a24.mp4

## 2) Fixed "Update sample test status" modal unresponsive behaviour in mobile
Screenshot from 2022-05-22 18-06-40

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

File: src/Components/Patient/UpdateStatusDialog.tsx [hunk 1]
```diff
@@ -40,9 +36,9 @@ const styles = {
   },
 };
 
-interface URLS {
-  [id: string]: string;
-}
+// interface URLS {
+//   [id: string]: string;
+// }
```
Comment (khavinshankar) [inline src/Components/Patient/UpdateStatusDialog.tsx]: _If this is an unused interface or variable, removing them would be better instead of commenting them out_

File: src/Components/Patient/UpdateStatusDialog.tsx [hunk 2]
```diff
@@ -56,7 +52,7 @@ const resultTypes = [
   ...SAMPLE_TEST_RESULT,
 ];
 
-const roleStatusMap = { ...ROLE_STATUS_MAP };
+// const roleStatusMap = { ...ROLE_STATUS_MAP };
```
Comment (khavinshankar) [inline src/Components/Patient/UpdateStatusDialog.tsx]: _If this is an unused interface or variable, removing them would be better instead of commenting them out_

**Review by khavinshankar — COMMENTED** [review]
please remove the unused interfaces, variables and functions if they are trivial and tightly coupled (very context specific)

**Comment by patelaryan7751** [comment]
Hey, @khavinshankar I have removed all commented unused variables.

**Review by khavinshankar — APPROVED** [review]
