### PR TITLE
Fix validation messages in discount forms and update zod schema for better user feedback

### LINKED ISSUE #13234: Validation errors not appearing and translation issues in discount forms
**Describe the bug**

**1. Raw translation keys showing instead of translated text**
- Form displays raw translation keys like "**field_required**" instead of actual translated messages in both `DiscountCodeForm.tsx` and `DiscountMonetaryComponentForm.tsx`

**2. Validation messages not appearing for factor/amount fields in `DiscountMonetaryComponentForm.tsx`**
- When factor or amount fields are left empty, no validation error message is displayed even though error message exist.
- Only the name field shows validation errors, factor/amount fields show no feedback 

**3. HTML5 default validation messages**
-  We can use our custom validation message instead of HTML5 default validation messages for better Localization & Internationalization

**To Reproduce**

1. Go to Billings
2. Click on Discount Codes and Discount Components
3. Leave all the field and submit

**Expected behavior**
- Form should display proper translated messages like "This field is required" instead of raw keys like "field_required"
-  When factor or amount fields are empty, validation error message "Either factor or amount must be provided" should appear below the respective field
-  Custom validation messages should display instead of browser default messages

**Screenshots**

https://github.com/user-attachments/assets/82d2293b-2bc5-490f-8f76-b17de2bfa490

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Denyme24**
## Proposed Changes

Fixes #13234 
- Form now display proper translated messages like "This field is required" instead of raw keys like "field_required"
- Add button disable logic, when no valid changes are made.

https://github.com/user-attachments/assets/e999a6dd-e98b-4bbc-9327-36ed2436bc34

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [X] Ensure that UI text is placed in I18n files.
- [X] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [X] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.

## Summary by CodeRabbit

- New Features
  - Validation messages fully localized (adds missing message for custom-code display).
  - Submit buttons disabled until form changes are made.
  - Improved selector and guidance for choosing percentage vs amount discounts.

- Refactor
  - Form validation rebuilt per-language at render for accurate messages.
  - Cleaner input behavior for percentage and amount (handles cleared values gracefully).
  - Updated form layout with consistent field wrappers and messages for better readability.

### CODE REVIEW

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

File: src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx [hunk 1]
```diff
@@ -87,7 +94,13 @@ export function DiscountCodeForm({
         />
 
         <div className="pt-2">
-          <Button type="submit" className="w-full">
+          <Button
+            type="submit"
+            className="w-full"
+            disabled={
+              isEditMode ? !form.formState.isDirty : !form.formState.isValid
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx]: Not needed, isDirty check alone is enough.

File: src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx [hunk 2]
```diff
@@ -242,7 +270,15 @@ export function DiscountMonetaryComponentForm({
         </div>
 
         <div className="pt-2">
-          <Button type="submit" className="w-full">
+          <Button
+            type="submit"
+            className="w-full"
+            disabled={
+              isEditMode
+                ? !(form.formState.isDirty || hasValueTypeChanged)
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx]: discard other changes, incorporate Select into FormField (prefix with _ for silent variable)

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx (hunk 1 above)
Comment (Denyme24) [reply src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx]: have made the changes

File: src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx [hunk 3]
```diff
@@ -69,8 +41,60 @@ export function DiscountMonetaryComponentForm({
...
+            // If there's a code, it must have a display value
+            return data.code == null || data.code.display.length > 0;
+          },
+          {
+            message: t("display_text_required_for_custom_codes"),
+            path: ["code"],
+          },
+        ),
+    [t, valueType],
   );
```
[the remark this answers is not in the document]
Comment (Denyme24) [reply src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx]: reverted to the previous approach

File: src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx (hunk 2 above)
Comment (Denyme24) [reply src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx]: have discarded all the changes, just kept the button disabling logic and incorporated Select into FormField

**Comment by Denyme24** [comment]
Hey @Jacobjeevan, i have made the changes as you suggested, discarded all the changes, kept the button disabled changes, and incorporated Select into FormField, please review it once.

File: src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx [hunk 4]
```diff
@@ -73,6 +45,38 @@ export function DiscountMonetaryComponentForm({
...
+          amount: z
+            .string()
+            .refine((val) => !val || Number(val) >= 0, {
+              message: "Amount must be greater than or equal to 0",
+            })
+            .optional(),
+          title: z.string().min(1, { message: t("field_required") }),
+        })
+        .refine((data) => data.factor != null || data.amount != null, {
+          message: "Either factor or amount must be provided",
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx]: add missing translations here as well.

File: src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx [hunk 5]
```diff
@@ -73,6 +45,38 @@ export function DiscountMonetaryComponentForm({
...
+          path: ["factor", "amount"],
+        })
+        .refine(
+          (data) => {
+            // If there's a code, it must have a display value
+            return data.code == null || data.code.display.length > 0;
+          },
+          {
+            message: "Display text is required for custom codes",
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx]: here as well.

**Review by Jacobjeevan — APPROVED** [review]
Conditionally approving (some translations need to be added).

File: src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx (hunk 4 above)
Comment (Denyme24) [reply src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx]: added missing translations

File: src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx (hunk 5 above)
Comment (Denyme24) [reply src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx]: done

**Comment by nihal467** [comment]
LGTM

**Comment by Denyme24** [comment]
Hey team @Jacobjeevan @rithviknishad , could you please give a final review as it is tested

File: src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx [hunk 6]
```diff
@@ -73,6 +45,38 @@ export function DiscountMonetaryComponentForm({
...
+            // If there's a code, it must have a display value
+            return data.code == null || data.code.display.length > 0;
+          },
+          {
+            message: t("display_text_is_required_for_custom_codes"),
+            path: ["code"],
+          },
+        ),
+    [t],
+  );
```
Comment (khavinshankar) [inline src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx]: No need to bring the form schema inside the component if your only goal is to use translation, consider using `import { t } from "i18next"` directly.

File: src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx [hunk 7]
```diff
@@ -73,6 +45,38 @@ export function DiscountMonetaryComponentForm({
...
+    () =>
+      z
+        .object({
+          monetary_component_type: z.literal(MonetaryComponentType.discount),
+          code: CodeSchema.optional(),
+          factor: z.number().min(0).max(100).optional(),
+          amount: z
+            .string()
+            .refine((val) => !val || Number(val) >= 0, {
+              message: "Amount must be greater than or equal to 0",
```
Comment (khavinshankar) [inline src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx]: missed i18n

**Review by khavinshankar — DISMISSED** [review]

File: src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx (hunk 6 above)
Comment (Denyme24) [reply src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx]: @khavinshankar , should i do this change for both `DiscountCodeForm.tsx `and `DiscountMonetaryComponentForm.tsx`?

Comment (AdityaJ2305) [reply src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx]: @khavinshankar Translations through `import { t } from "i18next"` doesn't work most of the time. Ref issue: https://github.com/ohcnetwork/care_fe/issues/11206 

cc: @rithviknishad @Denyme24

Comment (Denyme24) [reply src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx]: @khavinshankar , i tried with your suggested approach that is directly using `import { t } from "i18next"`, but as @AdityaJ2305 told , it didn't worked.

cc: @Jacobjeevan @rithviknishad

File: src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx (hunk 7 above)
Comment (Denyme24) [reply src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx]: @khavinshankar , have made the changes. PTAL.

File: src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx [hunk 8]
```diff
@@ -73,6 +45,38 @@ export function DiscountMonetaryComponentForm({
...
+              message: t("amount_must_be_greater_than_or_equal_to_0"),
+            })
+            .optional(),
+          title: z.string().min(1, { message: t("field_required") }),
+        })
+        .refine((data) => data.factor != null || data.amount != null, {
+          message: t("either_amount_or_factor_required"),
+          path: ["factor", "amount"],
+        })
+        .refine(
```
[the remark this answers is not in the document]
Comment (Denyme24) [reply src/pages/Facility/settings/billing/discount/discount-components/DiscountMonetaryComponentForm.tsx:67]: have made these changes earlier, but was not approved by the maintainers.
so stick to the current approach

**Review by Jacobjeevan — APPROVED** [review]
