### PR TITLE
fix: Trigger expiration date validation on manufacture date change

### LINKED ISSUE #12504: Expiration Date Validation Requires Additional Click After Correcting Manufacture Date
**Describe the bug**
After correcting a Manufacture Date, the Expiration Date validation error doesn't clear automatically.

**To Reproduce**

1.  Go to 'Devices'
2.  Click on 'Add device'.
4.   The Expiration Date validation error  doesn't clear automatically after correcting the manufacture date.

**Expected behavior**
The Expiration Date validation should re check automatically and needs to remove the validation errors instantly.

https://github.com/user-attachments/assets/fce16529-bb04-4f08-80b3-8481a6f694bd

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Denyme24**
## Proposed Changes

- Fixes #12504 
- Triggers expiration date validation immediately when manufacture date is updated to provide instant feedback to users.

https://github.com/user-attachments/assets/ddf0a098-995c-4b7c-aec7-e25fe99a6d5a

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved real-time validation in the device form, ensuring that changes to the manufacture date immediately update validation for the expiration date field.
  - Enhanced date selection in device form by enabling calendar-based input for manufacture and expiration dates.
  - Added readiness check to the save button to prevent premature form submission.
  - Refined input handling for the device name field to improve form interaction consistency.

### CODE REVIEW

**Review by AdityaJ2305 — APPROVED** [review]
Just a minor thing - it’s better to keep a single line space between fields, so please revert that change back 👍

**Comment by Denyme24** [comment]
> Just a minor thing - it’s better to keep a single line space between fields, so please revert that change back 👍

will do that

**Comment by Denyme24** [comment]
@rithviknishad @Jeffrin2005 , review it once.

**Comment by AdityaJ2305** [comment]
@Denyme24 , could you please see the reason of cypress failing and fix it

**Comment by AdityaJ2305** [comment]
@Denyme24 , in first place test shouldn't fail because u haven't made any test failing changes ? 🤔

**Comment by Denyme24** [comment]
> @Denyme24 , in first place test shouldn't fail because u haven't made any test failing changes ? 🤔

yeah right.

File: cypress/pageObject/facility/FacilityDevices.ts
Comment (AdityaJ2305) [inline cypress/pageObject/facility/FacilityDevices.ts:1]: Discard these changes, these have nothing to do with test failing

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx [hunk 1]
```diff
@@ -334,7 +335,11 @@ export default function DeviceForm({ facilityId, device, onSuccess }: Props) {
                 <FormLabel>{t("manufacture_date")}</FormLabel>
                 <DatePicker
                   date={field.value}
-                  onChange={(date) => field.onChange(date)}
+                  onChange={(date) => {
+                    field.onChange(date);
+                    form.trigger("expiration_date");
+                  }}
+                  data-cy="manufacture-date-input"
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/devices/components/DeviceForm.tsx]:
```suggestion

```

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx [hunk 2]
```diff
@@ -350,6 +355,7 @@ export default function DeviceForm({ facilityId, device, onSuccess }: Props) {
                 <DatePicker
                   date={field.value}
                   onChange={(date) => field.onChange(date)}
+                  data-cy="expiration-date-input"
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/devices/components/DeviceForm.tsx]:
```suggestion

```

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]
check the failing log of test and do changes accordingly

File: cypress/pageObject/facility/FacilityDevices.ts
Comment (Denyme24) [reply cypress/pageObject/facility/FacilityDevices.ts:1]: > Discard these changes, these have nothing to do with test failing

done

**Review by Jacobjeevan — APPROVED** [review]

**Comment by Jacobjeevan** [comment]
@nihal467 Not sure why the test is failing 🤔  Button isn't disabled for me, also ran test locally and passing fine.

Here's the summary screenshot for ref:

image

**Comment by nihal467** [comment]
@Jacobjeevan it was missing a focus, adjusted the test

**Comment by nihal467** [comment]
LGTM
