### PR TITLE
Fixes Issue  #11008 : Changes  to close the issue of Alignment of User Login Status 

### LINKED ISSUE #11008: Inconsistent Line Break in "Never Logged In" Status Label
The "Never Logged In" status label is displayed inconsistently across different user cards. In some cards, it appears in a single line, while in others, it is split into two lines. This inconsistency affects the UI alignment and readability.

Navigate to the user list or dashboard.
Observe the "Never Logged In" status labels on different user cards.
Notice that in some cases, the text is on a single line, while in others, it wraps into two lines.

The "Never Logged In" status should always be displayed in a single line, maintaining uniformity across all cards.
If space constraints cause wrapping, the card size or text styling should be adjusted to ensure consistency.

Image

**Desktop (please complete the following information):**

- OS: [ Windows]
- Browser [ chrome]
- Version [22]

### PR DESCRIPTION
**Pull request by sj11105**
#11008
## Proposed Changes
The  alignment of the user's login status was not aligned , the status "never logged in" was taking a line break making it unaligned

- Fixes #11008 
- Changes in the CSS of the status "never logged in "
Screenshot 2025-03-05 081142

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style**
	- Enhanced the appearance of the user status badge for users who have never logged in, improving alignment and spacing for a more consistent, visually appealing interface.
	- Adjusted the layout of the user name and status indicator for better visual presentation and responsiveness, including text handling improvements for different screen sizes.
	- Updated the display text for users who have never logged in to show "Never Logged In" on larger screens and "Never" on smaller screens.

- **Chores**
	- Updated Cypress dependency from version `^14.0.0` to `^14.2.0`, ensuring access to the latest features and improvements.

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]

**Comment by Jacobjeevan** [comment]
@sj11105 Complete the merge checklist please.

**Comment by nihal467** [comment]
image

its breaking of medium screens

**Comment by sj11105** [comment]
@nihal467 ok I will make the changes accordingly

**Comment by sj11105** [comment]
@nihal467 
Screenshot 2025-03-06 183511
I have changed the status to "never" for smaller and medium screens to make it correctly visible

File: src/components/Users/UserListAndCard.tsx [hunk 1]
```diff
@@ -49,10 +49,12 @@ export const UserStatusIndicator = ({
...
         <Badge
           variant="secondary"
-          className="bg-gray-100 whitespace-nowrap text-wrap"
+          className="bg-gray-100 inline-flex items-center gap-1 px-2 py-1 rounded-lg text-xs sm:text-sm text-gray-700 
+        max-w-full truncate overflow-hidden whitespace-nowrap"
         >
-          <span className="inline-block h-2 w-2 shrink-0 rounded-full bg-gray-500 mr-2" />
-          <span className="text-xs text-gray-700">{t("never_logged_in")}</span>
+          <span className="h-2 w-2 shrink-0 rounded-full bg-gray-500"></span>
+          <span className="hidden lg:inline-block">Never Logged In</span>
```
Comment (Jacobjeevan) [inline src/components/Users/UserListAndCard.tsx]: translations

https://github.com/ohcnetwork/care_fe?tab=readme-ov-file#translations

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Users/UserListAndCard.tsx (hunk 1 above)
Comment (sj11105) [reply src/components/Users/UserListAndCard.tsx]: @Jacobjeevan hey, sorry for the mistake, now i have made changes to the code

File: src/components/Users/UserListAndCard.tsx [hunk 2]
```diff
@@ -49,10 +49,12 @@ export const UserStatusIndicator = ({
       ) : (
         <Badge
           variant="secondary"
-          className="bg-gray-100 whitespace-nowrap text-wrap"
+          className="bg-gray-100 inline-flex items-center gap-1 px-2 py-1 rounded-lg text-xs sm:text-sm text-gray-700 
+        max-w-full truncate overflow-hidden whitespace-nowrap"
```
Comment (bodhish) [inline src/components/Users/UserListAndCard.tsx]: I pretty sure a few classes here are not required!

Also why do we have new line in the className?

File: src/components/Users/UserListAndCard.tsx [hunk 3]
```diff
@@ -49,10 +49,12 @@ export const UserStatusIndicator = ({
...
         >
-          <span className="inline-block h-2 w-2 shrink-0 rounded-full bg-gray-500 mr-2" />
-          <span className="text-xs text-gray-700">{t("never_logged_in")}</span>
+          <span className=" h-2 w-2 shrink-0 rounded-full bg-gray-500 " />
+          <span className="hidden:lg:inline block">{t("never_logged_in")}</span>
+          <span className="inline-block lg:hidden">{t("Never")}</span>
```
Comment (bodhish) [inline src/components/Users/UserListAndCard.tsx]: Missed I18n!!!

File: src/components/Users/UserListAndCard.tsx [hunk 4]
```diff
@@ -49,10 +49,12 @@ export const UserStatusIndicator = ({
       ) : (
         <Badge
           variant="secondary"
-          className="bg-gray-100 whitespace-nowrap text-wrap"
+          className="bg-gray-100 inline-flex items-center gap-1 px-2 py-1 rounded-lg text-xs sm:text-sm text-gray-700 
+        max-w-full truncate overflow-hidden whitespace-nowrap"
         >
-          <span className="inline-block h-2 w-2 shrink-0 rounded-full bg-gray-500 mr-2" />
-          <span className="text-xs text-gray-700">{t("never_logged_in")}</span>
+          <span className=" h-2 w-2 shrink-0 rounded-full bg-gray-500 " />
```
Comment (bodhish) [inline src/components/Users/UserListAndCard.tsx]:
```suggestion
          <span className="h-2 w-2 shrink-0 rounded-full bg-gray-500" />
```
Lets not have spaces for no reason

File: src/components/Users/UserListAndCard.tsx [hunk 5]
```diff
@@ -63,7 +65,7 @@ const UserCard = ({ user }: { user: UserBase }) => {
   return (
     <Card key={user.id} className="h-full">
       <CardContent className="p-4 sm:p-6 flex flex-col h-full justify-between">
-        <div className="flex items-start gap-3">
+        <div className="flex items-start gap-3 ">
```
Comment (bodhish) [inline src/components/Users/UserListAndCard.tsx]: why?
```suggestion
        <div className="flex items-start gap-3">
```

**Review by bodhish — DISMISSED** [review]

File: src/components/Users/UserListAndCard.tsx (hunk 5 above)
Comment (sj11105) [reply src/components/Users/UserListAndCard.tsx]: @bodhish  I have made the required  changes please check them once

Comment (Jacobjeevan) [reply src/components/Users/UserListAndCard.tsx]: Are you sure? @sj11105 Check https://github.com/ohcnetwork/care_fe/pull/11022/files

Still has space.

Comment (sj11105) [reply src/components/Users/UserListAndCard.tsx]: @Jacobjeevan  Please check now

File: src/components/Users/UserListAndCard.tsx [hunk 6]
```diff
@@ -49,10 +49,11 @@ export const UserStatusIndicator = ({
       ) : (
         <Badge
           variant="secondary"
-          className="bg-gray-100 whitespace-nowrap text-wrap"
+          className="bg-gray-100 flex items-center gap-1 px-2 py-1 rounded-lg text-xs sm:text-sm text-gray-700 max-w-full truncate"
```
Comment (Jacobjeevan) [inline src/components/Users/UserListAndCard.tsx]: Recheck/test which of these are really needed and make sure the styles are consistent. Adding text-sm here for example would make it different from other badges.

image

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Users/UserListAndCard.tsx (hunk 6 above)
Comment (sj11105) [reply src/components/Users/UserListAndCard.tsx]: @Jacobjeevan Hey i hope the changes i made now resolves the issue.
Screenshot 2025-03-15 082640

File: src/components/Users/UserListAndCard.tsx [hunk 7]
```diff
@@ -74,14 +75,13 @@ const UserCard = ({ user }: { user: UserBase }) => {
 
           <div className="flex flex-col min-w-0 flex-1">
             <div className="flex flex-col gap-1">
-              <div className="flex items-start justify-between">
-                <h1 className="text-base font-bold break-words pr-2 w-[50%] text-wrap">
+              <div className="flex items-center justify-between gap-2 w-full overflow-hidden">
+                <h1 className="text-base font-bold truncate pr-2 max-w-[60%]">
```
Comment (Jacobjeevan) [inline src/components/Users/UserListAndCard.tsx]: If you are adding truncate, you should add tool tip as well.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Users/UserListAndCard.tsx (hunk 7 above)
Comment (sj11105) [reply src/components/Users/UserListAndCard.tsx]: @Jacobjeevan Please check

Comment (Jacobjeevan) [reply src/components/Users/UserListAndCard.tsx]: Should add the breakwords back in as well 👍

Comment (sj11105) [reply src/components/Users/UserListAndCard.tsx]: @Jacobjeevan  I have added the breakwords

**Review by Jacobjeevan — APPROVED** [review]
