### PR TITLE
Fix: Responsiveness issue in the Update button dropdown for Encounter Action

### LINKED ISSUE #11576: Right-Aligned Modal Hurts Usability - Should Be Centered
# Issue: Right-Aligned Modal Hurts Usability - Should Be Centered

**Problem**  
The "Manage Consents" modal opens anchored to the right side of the screen (as shown in the screenshot). This non-standard implementation creates several UX issues:
- Forces users to visually "travel" across the screen
- Obscures contextual information on the right
- Feels unbalanced on desktop and breaks on mobile
- Violates established modal patterns (Google/Material Design, Apple HIG)

**Current Implementation**  

Image

*Modal clings to right edge, creating awkward empty space on left*

**Why Center is Better**  
✅ **Focus**: Centers attention naturally in the user's gaze path  
✅ **Responsive**: Scales better across devices  
✅ **Consistency**: Matches platform conventions (85% of modals are centered)  
✅ **Accessibility**: Better for screen magnifiers and reduced motion  

**Proposed Solution**  
```diff
- Right-anchored modal (current)
+ Centered modal with:
+  - 80% max-width on desktop
+  - 90% width on mobile
+  - Semi-transparent backdrop
+  - Smooth zoom-in animation

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #11576 

https://github.com/user-attachments/assets/c07de1f5-32ee-4f41-a02f-d5aa8abc026a

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Improved the responsive layout and spacing of patient consultation badges and action buttons.
  - Enhanced the dropdown menu structure and styling for a more consistent user experience.

### CODE REVIEW

**Comment by Jacobjeevan** [comment]
image


Does this look right to you? It's in the video as well 😅

**Comment by AdityaJ2305** [comment]
@Jacobjeevan done with changes


https://github.com/user-attachments/assets/c07de1f5-32ee-4f41-a02f-d5aa8abc026a

**Comment by poonamsoni25** [comment]
@coderabbitai plan

File: src/components/Patient/PatientInfoCard.tsx [hunk 1]
```diff
@@ -458,44 +459,48 @@ export default function PatientInfoCard(props: PatientInfoCardProps) {
...
+                          <Button variant="primary">
+                            {inactiveEncounterStatus.includes(
+                              encounter.status,
+                            ) || !facilityIdExists
+                              ? t("actions")
+                              : t("update")}
+                            <ChevronDown className="ml-2 size-4" />
+                          </Button>
+                        </DropdownMenuTrigger>
+                        <DropdownMenuContent className="w-(--radix-dropdown-menu-trigger-width) sm:w-auto">
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientInfoCard.tsx]: let's preserve the align property (it's center by default, which works for smaller screens, but not for larger ones). So adjust accordingly - end for bigger and center for smaller screens.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
