### PR TITLE
Fixed:Show more monitors in CNS on very large displays #6503

### LINKED ISSUE #6503: Show more monitors in CNS on very large displays
**Describe the bug**
When CNS is opened in large 4K displays, 75% of the screen space is wasted. 

**To Reproduce**

1. Visit https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/cns on a 4K display

**Expected behavior**
On large displays, render more vitals monitors into view per page.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by i0am0arunava**
## Proposed Changes

- Fixes #6503

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

 Screenshot 2024-11-06 141324
   ]

## Summary by CodeRabbit

- **New Features**
	- Enhanced responsive design for the Central Nursing Station component, allowing dynamic pagination limits based on screen size.
	- Support for new screen sizes "4xl" and "4k" in the application.

- **Bug Fixes**
	- Improved pagination logic to adapt to various screen sizes, ensuring a better user experience.

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
I don't see how this adds value compared to how it was before.

Before:
image


After:

image

**Comment by bodhish** [comment]
@i0am0arunava please close the previous PR before picking something else.

**Comment by i0am0arunava** [comment]
> @i0am0arunava please close the previous PR before picking something else.

@bodhish ,But I am working on the previous issue 
You required some changes....I am working on that

**Comment by i0am0arunava** [comment]
@rithviknishad @bodhish  ,why the deployment is failing .But in my local system build is working properly

**Comment by i0am0arunava** [comment]
now this look like this is it okay now?
Screenshot 2024-11-06 195148

**Comment by rithviknishad** [comment]
issue talks about "4K" displays right. could you show how it looks in 4K?

**Comment by i0am0arunava** [comment]
> issue talks about "4K" displays right. could you show how it looks in 4K?

should I increse the column

**Comment by i0am0arunava** [comment]
> issue talks about "4K" displays right. could you show how it looks in 4K?

should I increase the column
When I was working, Chrome was showing 2560 px as 4K, but when I googled it, it showed that 4K is 4000 px.  this is the screenshot for 4000,should I increase the column
Screenshot 2024-11-07 143516

**Comment by i0am0arunava** [comment]
> > issue talks about "4K" displays right. could you show how it looks in 4K?
> 
> should I increase the column When I was working, Chrome was showing 2560 px as 4K, but when I googled it, it showed that 4K is 4000 px. this is the screenshot for 4000,should I increase the column Screenshot 2024-11-07 143516

is it okay if I increase grid col for 4000px 4k display and all the monitors are rendered in the 1st page
Screenshot 2024-11-07 190449

**Comment by rithviknishad** [comment]
Yup we can. I think 6 column 4 rows should be right for 4K.

File: src/hooks/useBreakpoints.ts [hunk 1]
```diff
@@ -10,6 +18,8 @@ const BREAKPOINT_WIDTH: Record<Breakpoints, number> = {
   xl: 1280,
   "2xl": 1536,
   "3xl": 1920,
+  largedisplay: 2080,
+  fourK: 3000,
 };
```
Comment (i0am0arunava) [inline src/hooks/useBreakpoints.ts:15]: defined the type of largeddisplay and fourk breakpoint  and added the width of display

File: tailwind.config.js [hunk 2]
```diff
@@ -15,11 +15,16 @@ const secondary = {
...
+
 module.exports = {
   important: true,
   darkMode: ["class"],
   theme: {
     extend: {
+      screens: {
+        largedisplay: "130rem",
+        fourk: "187rem", // rem is used insted of pixel
+      },
```
Comment (i0am0arunava) [inline tailwind.config.js]: used rem insted of pixel for largedisplay and fourk

**Review by i0am0arunava — COMMENTED** [review]
is these changes ok ?

File: src/components/Facility/CentralNursingStation.tsx [hunk 3]
```diff
@@ -41,6 +40,12 @@ interface Props {
 }
 
 export default function CentralNursingStation({ facilityId }: Props) {
+  const breakpointValues = {
```
Comment (i0am0arunava) [inline src/components/Facility/CentralNursingStation.tsx]: use usebreakpointhook instead of useeffect and usestate default will render 6 monitor and in big screen it will render 24

**Review by i0am0arunava — COMMENTED** [review]
added usebreakpoint  instead of useeffect and usstate

File: src/hooks/useBreakpoints.ts [hunk 4]
```diff
@@ -10,6 +18,8 @@ const BREAKPOINT_WIDTH: Record<Breakpoints, number> = {
   xl: 1280,
   "2xl": 1536,
   "3xl": 1920,
+  largedisplay: 2080,
+  fourK: 3000,
```
Comment (rithviknishad) [inline src/hooks/useBreakpoints.ts]: use standard values and consistent namings

```suggestion
  "4xl": 2560,
  "4k": 3840,
```

File: tailwind.config.js (hunk 2 above)
Comment (rithviknishad) [inline tailwind.config.js]: same here too

File: src/components/Facility/CentralNursingStation.tsx [hunk 5]
```diff
@@ -41,6 +40,12 @@ interface Props {
...
+    default: 6,
+    largedisplay: 9,
+    fourK: 24,
+  };
+  const PER_PAGE_LIMIT = useBreakpoints(breakpointValues);
```
Comment (rithviknishad) [inline src/components/Facility/CentralNursingStation.tsx]: 1. use proper naming conventions
2. inline the breakpoint values so that type-aware autocomplete is available

```suggestion
  const perPageLimit = useBreakpoints({
    default: 6,
    "4xl": 9,
    "4k": 24,
  });
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Facility/CentralNursingStation.tsx [hunk 6]
```diff
@@ -41,31 +40,34 @@ interface Props {
 }
 
 export default function CentralNursingStation({ facilityId }: Props) {
+  const perPageLimit = useBreakpoints({
```
Comment (i0am0arunava) [inline src/components/Facility/CentralNursingStation.tsx:43]: used proper naming conventions
inline the breakpoint values so that type-aware autocomplete is available

**Review by i0am0arunava — COMMENTED** [review]
commited as per the request

File: tailwind.config.js [hunk 7]
```diff
@@ -15,11 +15,16 @@ const secondary = {
...
 /** @type {import('tailwindcss').Config} */
+
 module.exports = {
   important: true,
   darkMode: ["class"],
   theme: {
     extend: {
+      screens: {
+        "4xl": "160rem",
+        "4k": "240rem", // rem is used insted of pixel
```
Comment (rithviknishad) [inline tailwind.config.js]:
```suggestion
        "4k": "240rem",
```

File: tailwind.config.js [hunk 8]
```diff
@@ -15,11 +15,16 @@ const secondary = {
 };
 
 /** @type {import('tailwindcss').Config} */
+
```
Comment (rithviknishad) [inline tailwind.config.js]:
```suggestion
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]
can you check why facility list page is broken only in this PR

image

**Comment by i0am0arunava** [comment]
> can you check why facility list page is broken only in this PR
> 
> image

yeh found it ,due to adding screen: in tailwind config

**Comment by i0am0arunava** [comment]
> > can you check why facility list page is broken only in this PR
> > image
> 
> yeh found it ,due to adding screen: in tailwind config
Using pixels instead of rem in the Tailwind config solved the problem

**Comment by rithviknishad** [comment]
We can use container queries without modifying the tailwind config instead.

Refer: https://github.com/tailwindlabs/tailwindcss-container-queries#named-containers

We already have this configured in care. Let's use that instead

File: tailwind.config.js [hunk 9]
```diff
@@ -20,6 +20,10 @@ module.exports = {
   darkMode: ["class"],
   theme: {
     extend: {
+      screens: {
```
Comment (i0am0arunava) [inline tailwind.config.js]: Using pixels instead of rem in the Tailwind config solved the problem of ui breaking

**Review by i0am0arunava — COMMENTED** [review]
now it will not cause ui breaking

File: tailwind.config.js (hunk 9 above)
Comment (rithviknishad) [reply tailwind.config.js]: https://github.com/ohcnetwork/care_fe/pull/9013#issuecomment-2466112422

**Comment by i0am0arunava** [comment]
> We can use container queries without modifying the tailwind config instead.
> 
> Refer: https://github.com/tailwindlabs/tailwindcss-container-queries#named-containers
> 
> We already have this configured in care. Let's use that instead

okay

**Comment by i0am0arunava** [comment]
> We can use container queries without modifying the tailwind config instead.
> 
> Refer: https://github.com/tailwindlabs/tailwindcss-container-queries#named-containers
> 
> We already have this configured in care. Let's use that instead

@rithviknishad I read the readme
and added as mentioned but not working 
Can you please help?

**Comment by rithviknishad** [comment]
1. You'll have to add `@container` class to the parent element (eg: https://github.com/ohcnetwork/care_fe/blob/develop/src/components/Facility/LocationManagement.tsx#L111)
2. And then you'll have to adjust the grid's elements classes to use the container query modifiers (eg: https://github.com/ohcnetwork/care_fe/blob/develop/src/components/Facility/LocationManagement.tsx#L119)

**Comment by i0am0arunava** [comment]
> 1. You'll have to add `@container` class to the parent element (eg: https://github.com/ohcnetwork/care_fe/blob/develop/src/components/Facility/LocationManagement.tsx#L111)
> 2. And then you'll have to adjust the grid's elements classes to use the container query modifiers (eg: https://github.com/ohcnetwork/care_fe/blob/develop/src/components/Facility/LocationManagement.tsx#L119)

not working 
Screenshot 2024-11-09 151032

I also checked by adding custom value inside 
Extend 
As mentioned in the docs

**Comment by rithviknishad** [comment]
use standard modifiers instead of arbitrary values. they are sufficient.

**Comment by i0am0arunava** [comment]
> use standard modifiers instead of arbitrary values. they are sufficient.

Means @6xl @7xl right?but that's not also working 
I checked it also

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image
image

- [ ] whenever i click on the setting button in the cns page, it going to a loading state before showing the dropdown, fix it

File: src/components/Facility/CentralNursingStation.tsx [hunk 10]
```diff
@@ -85,6 +85,7 @@ export default function CentralNursingStation({ facilityId }: Props) {
       noImplicitPadding
       breadcrumbs={false}
       collapseSidebar
+      className="@container"
```
Comment (i0am0arunava) [inline src/components/Facility/CentralNursingStation.tsx]: @rithviknishad ,@nihal  ,this   className="@container"  is causing this bug https://github.com/ohcnetwork/care_fe/pull/9013/#issuecomment-2473293072

**Review by i0am0arunava — COMMENTED** [review]
creating a new parent instead of  placing    className="@container" inside <Page .../> will not cause the bug and work properly

File: src/components/Facility/CentralNursingStation.tsx (hunk 10 above)
Comment (i0am0arunava) [reply src/components/Facility/CentralNursingStation.tsx]: however, like this creating a new parent for this  will not cause this bug and work properly 
Screenshot 2024-11-14 221551

File: src/components/Facility/CentralNursingStation.tsx [hunk 11]
```diff
@@ -216,21 +218,23 @@ export default function CentralNursingStation({ facilityId }: Props) {
...
-                    ?.start_date
-                }
-                key={`${props.patientAssetBed?.bed.id}-${hash}`}
-                patientAssetBed={props.patientAssetBed}
-                socketUrl={props.socketUrl || ""}
-                config={config}
-              />
-            </div>
-          ))}
+        <div className="@container">
```
Comment (i0am0arunava) [inline src/components/Facility/CentralNursingStation.tsx:221]: instead of adding container inside <Page..../> I created a new class as parent because previous implementation was causing this bug   https://github.com/ohcnetwork/care_fe/pull/9013#issuecomment-2473293072

**Review by i0am0arunava — COMMENTED** [review]
@nihal467 @rithviknishad fixed the issue https://github.com/ohcnetwork/care_fe/pull/9013#issuecomment-2473293072

**Comment by i0am0arunava** [comment]
> image image
> 
> * [ ]  whenever i click on the setting button in the cns page, it going to a loading state before showing the dropdown, fix it

@nihal467 ,fixed it

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
