### PR TITLE
fixed manage charges

### LINKED ISSUE #14173: fix `Manage Charges` in Appointments
**Describe the bug**
While selecting Charge Item Definitions in Appointments, if Re-visit allowed days is set to 0,
 - save button gets disabled.
 - Re-visit Consultation Charge button remains selectable.

**To Reproduce**

1. Go to 'Schedules'
2. Click on 'Manage Charges'
3. Set 'Re-visit allowed days' as 0

**Expected behavior**
- Save button should remain enabled even if revisit allowed days is set to 0.
- Re-visit Consultation Charge should be disabled when revisit days is 0.

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by StephZam**
## Proposed Changes

Fixes #14173 

If re-visit allowed days is set to 0,
- enabled save button
- disabled re-visit consultation charge

Screenshot 2025-10-29 190255

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **New Features**
  * Added a form-based editor for schedule charge items with integrated Save/Cancel, validation, and auto-close on submit.

* **Improvements**
  * Enforced non-negative revisit-day validation; dependent revisit selection auto-clears and becomes disabled/styled when days = 0.
  * Form resets to original values when the editor closes.
  * Charge item picker now correctly clears selection and respects disabled state.

* **Bug Fixes**
  * Fixed typo in consultation charge label and added a locale message for non-negative revisit days.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
when revisit days is 0, we should also reset the state of revisit charge item definition as well.

**Review by rithviknishad — COMMENTED** [review]
can we disallow negative numbers in form validation?

Image

**Comment by rithviknishad** [comment]
scroll is not working... :/ 

image

File: src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx [hunk 1]
```diff
@@ -37,35 +47,63 @@ export default function ScheduleChargeItemDefinitionSelector({
...
-  const handleSubmit = () => {
-    onChange({
-      charge_item_definition_slug: selectedCSlug!,
-      re_visit_allowed_days: reVisitDays,
-      re_visit_charge_item_definition_slug: reVisitCSlug || null,
+  const scheduleChargeItemSchema = z
+    .object({
+      charge_item_definition_slug: z
+        .string()
+        .min(1, "Consultation charge is required"),
```
Comment (rithviknishad) [inline src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx]: use translations

```suggestion
        .min(1, t("field_required")),
```

**Review by rithviknishad — APPROVED** [review]

**Comment by StephZam** [comment]
Backend fixtures are not available right now. So temporarily deleted the test file.

File: src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx [hunk 2]
```diff
@@ -37,35 +47,59 @@ export default function ScheduleChargeItemDefinitionSelector({
...
-      re_visit_allowed_days: reVisitDays,
-      re_visit_charge_item_definition_slug: reVisitCSlug || null,
+  const scheduleChargeItemSchema = z
+    .object({
+      charge_item_definition_slug: z.string().min(1, t("field_required")),
+      re_visit_allowed_days: z.number().min(0, t("revisit_days_non_negative")),
+      re_visit_charge_item_definition_slug: z.string().nullable(),
+    })
+    .refine((data) => {
+      if (data.re_visit_allowed_days === 0) {
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx]: This refine is unnecessary, no? 🤔  Since we are resetting reset charge item when allowed days is 0.

File: src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx [hunk 3]
```diff
@@ -85,77 +119,99 @@ export default function ScheduleChargeItemDefinitionSelector({
...
+                <FormItem>
+                  <FormLabel>{t("re_visit_allowed_days")}</FormLabel>
+                  <FormControl>
+                    <Input
+                      type="number"
+                      min={0}
+                      value={field.value}
+                      onChange={(e) => {
+                        const value =
+                          e.target.value === "" ? 0 : parseInt(e.target.value);
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx]: This needs tweaking; check the behavior when you have 0 and try to change it. It won't allow resetting to empty value and then typing in something new.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx (hunk 3 above)
Comment (Jacobjeevan) [reply src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx]: We can use onBlur instead to force 0 in case user decides to leave input empty 🤔

**Comment by nihal467** [comment]
image

- show proper error message
- keep the revisit field a required field
- shouldn't allow form submit, if there is a error shown in the ui

**Comment by nihal467** [comment]
LGTM

**Comment by adarsh-priydarshi-5646** [comment]
@StephZam Please squash all your commits into a single clean commit.

**Review by rithviknishad — APPROVED** [review]

File: public/locale/en.json [hunk 4]
```diff
@@ -1271,9 +1271,9 @@
   "consent_verification_type__validation": "Validation",
   "consent_verification_type__validation_description": "Confirmation provided by the individual themselves.",
   "consents": "Consents",
-  "consulation charge": "Consultation Charge",
   "consult": "Consult",
   "consultation": "Consultation",
+  "consultation charge": "Consultation Charge",
   "consultation_history": "Consultation History",
   "consultation_missing_warning": "You have not created a consultation for the patient in",
```
Comment (abhimanyurajeesh) [inline public/locale/en.json:1278]: can you fix the key

**Review by abhimanyurajeesh — CHANGES_REQUESTED** [review]

File: public/locale/en.json [hunk 5]
```diff
@@ -1271,9 +1271,9 @@
   "consent_verification_type__validation": "Validation",
   "consent_verification_type__validation_description": "Confirmation provided by the individual themselves.",
   "consents": "Consents",
-  "consulation charge": "Consultation Charge",
   "consult": "Consult",
   "consultation": "Consultation",
+  "consultation charge": "Consultation Charge",
```
Comment (abhimanyurajeesh) [inline public/locale/en.json]:
```suggestion
  "consultation_charge": "Consultation Charge",
```

File: src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx [hunk 6]
```diff
@@ -93,103 +121,115 @@ export default function ScheduleChargeItemDefinitionSelector({
...
+          <form
+            onSubmit={form.handleSubmit(onSubmit)}
+            className="mt-6 flex flex-col gap-6"
+          >
+            <FormField
+              control={form.control}
+              name="charge_item_definition"
+              render={({ field }) => (
+                <FormItem>
+                  <FormLabel>{t("consultation charge")}</FormLabel>
```
Comment (abhimanyurajeesh) [inline src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx]:
```suggestion
                  <FormLabel>{t("consultation_charge")}</FormLabel>
```

**Review by abhimanyurajeesh — APPROVED** [review]

File: src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx [hunk 7]
```diff
@@ -37,43 +47,61 @@ export default function ScheduleChargeItemDefinitionSelector({
...
+      re_visit_allowed_days: scheduleTemplate.revisit_allowed_days ?? undefined,
+      re_visit_charge_item_definition:
+        scheduleTemplate.revisit_charge_item_definition,
+    },
+  });
+
+  const reVisitDays = form.watch("re_visit_allowed_days");
+
+  useEffect(() => {
+    if (reVisitDays === 0) {
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx]: this needs to account for reVisitDays being empty.

File: src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx [hunk 8]
```diff
@@ -93,103 +121,115 @@ export default function ScheduleChargeItemDefinitionSelector({
...
+              name="re_visit_allowed_days"
+              render={({ field }) => (
+                <FormItem>
+                  <FormLabel>{t("re_visit_allowed_days")}</FormLabel>
+                  <FormControl>
+                    <Input
+                      type="number"
+                      min={0}
+                      value={field.value ?? ""}
+                      onChange={(e) => {
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx:170]: Hmm, retest the behavior -  if I already have a saved value, it's not allowing to reset it fully.

Also check behavior when you have 0 and changing it. Might be enough to use watch and then set that to value instead of field.value.

File: src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx [hunk 9]
```diff
@@ -93,103 +121,115 @@ export default function ScheduleChargeItemDefinitionSelector({
...
+                    className={reVisitDays === 0 ? "text-gray-400" : ""}
+                  >
+                    {t("re_visit_consultation_charge")}
+                  </FormLabel>
+                  <FormControl>
+                    <div className="mt-2 flex gap-2 flex-col sm:flex-row">
+                      <ChargeItemDefinitionPicker
+                        facilityId={facilityId}
+                        value={
+                          reVisitDays === 0
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx]: Should be unnecessary given the useEffect.

File: src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx [hunk 10]
```diff
@@ -93,103 +121,115 @@ export default function ScheduleChargeItemDefinitionSelector({
...
+                        }
+                        onValueChange={(def) => {
+                          if (reVisitDays === 0) return;
+                          const selected = Array.isArray(def) ? def[0] : def;
+                          field.onChange(selected ?? null);
+                        }}
+                        placeholder={t("select_charge_item_definition")}
+                        className="grow-1"
+                        showCreateButton
+                        disabled={reVisitDays === 0}
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx]: Do add empty check for reVisitDays

File: src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx [hunk 11]
```diff
@@ -93,103 +121,115 @@ export default function ScheduleChargeItemDefinitionSelector({
...
+                    <div className="mt-2 flex gap-2 flex-col sm:flex-row">
+                      <ChargeItemDefinitionPicker
+                        facilityId={facilityId}
+                        value={
+                          reVisitDays === 0
+                            ? undefined
+                            : (field.value ?? undefined)
+                        }
+                        onValueChange={(def) => {
+                          if (reVisitDays === 0) return;
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx]: Also unnecessary since we are disabling it :)

File: src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx [hunk 12]
```diff
@@ -93,103 +121,115 @@ export default function ScheduleChargeItemDefinitionSelector({
...
+            <div className="flex justify-end gap-4 border-t pt-4 sticky bottom-0 bg-white">
+              <Button
+                variant="outline"
+                type="button"
+                onClick={() => setIsOpen(false)}
+                className="w-full sm:w-auto"
+              >
+                {t("cancel")}
+              </Button>
+              <Button type="submit" className="w-full sm:w-auto">
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/ScheduleChargeItemDefinitionSelector.tsx]: Let's disable save button if charge item definition is empty.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by Jacobjeevan — APPROVED** [review]
