### PR TITLE
[FIX] fixed responsiveness issue on various pages

### LINKED ISSUE #12960: Remove unnecessary scroll for patient detail page on medium screen
**Describe the bug**
Unnecessary whole page scroll is coming up for medium screen despite having enough space and it is fine for smaller and large screen 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to any facility
2. Go to Encounters tab
3. Click on View Patient for any encounter

**Expected behaviour**
Remove this unnecessary scrolling

**Screenshots**

https://github.com/user-attachments/assets/b317823c-9d8d-4d47-95df-e81f28b23edd

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by JavidSumra**
## Proposed Changes

- Fixes #12960 
- Fixed CSS on various pages

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Patient Dashboard layout now adjusts responsively to the sidebar state, dynamically resizing the content area for improved readability.
  - Payment Reconciliation list page container now adapts width when the sidebar is opened or closed, yielding a more consistent viewing experience.
  - No changes to data fetching, permissions, workflows, or public/exported interfaces; visual/layout adjustments only.

### CODE REVIEW

**Comment by AdityaJ2305** [comment]
It is not fixed for the page specifically mentioned in the issue

**Comment by JavidSumra** [comment]
> It is not fixed for the page specifically mentioned in the issue PatientIndex 

Hey @AdityaJ2305 can you please share a screenshot?

**Comment by AdityaJ2305** [comment]
https://github.com/user-attachments/assets/2a5c15f4-fd75-467a-a4f6-12965679490d

**Comment by JavidSumra** [comment]
Hey @AdityaJ2305  done with changes check once

**Comment by JavidSumra** [comment]
Hey @Jacobjeevan need you review.

**Comment by nihal467** [comment]
LGTM

File: src/pages/Encounters/EncounterShow.tsx [hunk 1]
```diff
@@ -124,8 +124,8 @@ export const EncounterShow = (props: Props) => {
       <EncounterHeader />
       <div className="flex flex-col lg:flex-row gap-6 lg:gap-2 mt-4 sm:h-[calc(100vh-10rem)]">
         <EncounterHistorySelector />
-        <div className="w-full overflow-x-auto">
-          <div className="w-full border-b-2 border-secondary-200 ">
+        <div className="w-full lg:w-auto lg:flex-1  md:w-[calc(100vw-8rem)] overflow-x-auto">
+          <div className="w-full border-b-2 border-secondary-200">
```
Comment (abhimanyurajeesh) [inline src/pages/Encounters/EncounterShow.tsx]: @JavidSumra lets not make changes in this file, remove this and resolve the conflict

**Review by abhimanyurajeesh — DISMISSED** [review]

**Comment by nihal467** [comment]
LGTM

**Comment by Jacobjeevan** [comment]
@JavidSumra Clear merge conflicts, let's get this merged.

**Comment by JavidSumra** [comment]
> @JavidSumra Clear merge conflicts, let's get this merged.


Hey @Jacobjeevan sorry for late but due to festival of Navaratri and weekend I'm not able to give time, I'll do it by next is that ok?

**Comment by yash-learner** [comment]
Before

image

---

After https://github.com/ohcnetwork/care_fe/pull/13074/commits/6671da96847152f75982a85ee6f4d149ba3a8359

image

**Comment by yash-learner** [comment]
Before 


image


---

After https://github.com/ohcnetwork/care_fe/pull/13074/commits/da7e1690e197517cd111403e16a0957a9e687d28

image

**Review by yash-learner — APPROVED** [review]
LGTM 

--

Made some additional changes so that it works even when sidebar is open 

https://github.com/ohcnetwork/care_fe/pull/13074#issuecomment-3389229794

https://github.com/ohcnetwork/care_fe/pull/13074#issuecomment-3389310513

**Review by yash-learner — APPROVED** [review]

File: package-lock.json
Comment (shivankacker) [inline package-lock.json:1]: Remove changes from here

**Review by shivankacker — CHANGES_REQUESTED** [review]

File: package-lock.json
Comment (yash-learner) [reply package-lock.json:1]: Fixed https://github.com/ohcnetwork/care_fe/pull/13074/commits/ba782d757d5e448ebc53376c75012cf1bf861128

**Review by shivankacker — APPROVED** [review]
