### PR TITLE
Fix: Overflow for switchers in sidebar, Avatar size in notes tab, Textbox expansion in Add Facility

### LINKED ISSUE #9998: Add Vertical Scrolling for Overflowing Facilities/Organizations & Reduce Avatar Size in Notes Tab & Textbox not expanding in Add Facility Form
Task 1 : Vertical Scrolling for Overflowing Data

When the number of facilities or organizations exceeds the container height, the data is being cut off and not fully visible.

Expected : Vertical scrolling should be enabled to ensure that all facilities or organizations are accessible.
Image

Task 2 : Reduce avatar size in notes tab in encounter page

Image

Task 3 : TextBox is not expanding in Add Facility.

Image

### PR DESCRIPTION
**Pull request by Rishith25**
## Proposed Changes

- Fixes #9998 
- Fixed the scroll issue if more facilities/organizations are present and showing the active facility or organization which is selected and textbox expansion in add facility.

image

image

image

image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Release Notes

- **Localization**
  - Added new translations for organization-related interface elements
  - Introduced internationalization support in organization and facility switchers

- **UI Improvements**
  - Enhanced dropdown menus with scrollable content
  - Updated avatar component styling for better layout and centering
  - Adjusted facility creation form text area styling

- **User Experience**
  - Improved organization selection and navigation
  - Added visual feedback for selected facilities

### CODE REVIEW

File: src/components/ui/sidebar/facility-switcher.tsx [hunk 1]
```diff
@@ -72,7 +72,11 @@ export function FacilitySwitcher({
                     setOpenMobile(false);
                   }
                 }}
-                className="gap-2 p-2"
+                className={`gap-2 p-2 ${
+                  facility.name === selectedFacility?.name
+                    ? "bg-primary-500 text-white"
+                    : ""
+                }`}
```
Comment (rithviknishad) [inline src/components/ui/sidebar/facility-switcher.tsx]: use `cn` utility fn. for conditional classes

File: src/components/ui/sidebar/organization-switcher.tsx [hunk 2]
```diff
@@ -75,6 +77,11 @@ export function OrganizationSwitcher({
                 setOpenMobile(false);
               }
             }}
+            className={`gap-2 p-2 ${
+              org?.name === selectedOrganization?.name
+                ? "bg-primary-500 text-white"
+                : ""
+            }`}
```
Comment (rithviknishad) [inline src/components/ui/sidebar/organization-switcher.tsx]: here too

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx [hunk 3]
```diff
@@ -153,11 +153,11 @@ const MessageItem = ({ message }: { message: Message }) => {
         <TooltipProvider>
           <Tooltip>
             <TooltipTrigger asChild>
-              <div className="flex-shrink-0">
+              <div className="flex-shrink-0 w-8 h-8 bg-secondary-300 rounded-full">
                 <Avatar
                   name={message.created_by.username}
                   imageUrl={message.created_by.profile_picture_url}
-                  className="w-8 h-8 rounded-full object-cover"
+                  className="object-cover"
```
Comment (rithviknishad) [inline src/pages/Encounters/tabs/EncounterNotesTab.tsx]: let's keep the size and rounded-full defined in avatar's classname itself like how it's done everywhere else. also why apply bg color? Doesn't avatar already apply a randomized bg-color automatically?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Common/Avatar.tsx [hunk 4]
```diff
@@ -57,7 +57,7 @@ const Avatar = React.forwardRef<
   return (
     <AvatarPrimitive.Root
       ref={ref}
-      className={cn("w-full h-full", className)}
+      className={cn(className, "flex items-center justify-center")}
```
Comment (rithviknishad) [inline src/components/Common/Avatar.tsx]: why was the order changed? className should be last element since it should "override" existing classes right?

Comment (Rishith25) [inline src/components/Common/Avatar.tsx]: @rithviknishad due to `w-full h-full` the avatar size is increased or occupying full container now i have change it as the above.
With these changes all other avatars in the entire care are working well

File: src/components/ui/sidebar/organization-switcher.tsx [hunk 5]
```diff
@@ -75,6 +79,10 @@ export function OrganizationSwitcher({
                 setOpenMobile(false);
               }
             }}
+            className={cn("gap-2 p-2", {
+              "bg-primary-500 text-white":
+                org?.name === selectedOrganization?.name,
+            })}
```
Comment (rithviknishad) [inline src/components/ui/sidebar/organization-switcher.tsx]: let's follow consistent pattern for conditional classes. mixing patterns is not desired.

```suggestion
            className={cn("gap-2 p-2", org?.name === selectedOrganization?.name && "bg-primary-500 text-white")}
```

File: src/components/Common/Avatar.tsx [hunk 6]
```diff
@@ -66,15 +66,15 @@ const Avatar = React.forwardRef<
         <AvatarPrimitive.Image
           src={imageUrl}
           alt={name}
-          className="aspect-square h-full w-full object-cover"
+          className="aspect-square object-cover"
```
Comment (rithviknishad) [inline src/components/Common/Avatar.tsx]: it should take the full height and width of the parent element right? (i.e. AvatarPrimitive)

File: src/components/Common/Avatar.tsx [hunk 7]
```diff
@@ -66,15 +66,15 @@ const Avatar = React.forwardRef<
...
         />
       ) : (
         <AvatarPrimitive.Fallback className="flex h-full w-full select-none items-center justify-center text-center">
           <svg
             xmlns="http://www.w3.org/2000/svg"
             version="1.1"
             viewBox="0 0 100 100"
-            className="aspect-square h-full w-full object-cover"
+            className="aspect-square object-cover"
```
Comment (rithviknishad) [inline src/components/Common/Avatar.tsx]: here too. i don't think anything in this file needs to be modified in order to achieve what you want.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Common/Avatar.tsx (hunk 4 above)
Comment (rithviknishad) [reply src/components/Common/Avatar.tsx]: you can pass it to className and it should override those classes

File: src/components/Facility/CreateFacilityForm.tsx [hunk 8]
```diff
@@ -305,7 +304,6 @@ export default function CreateFacilityForm({
                     {...field}
                     data-cy="facility-address"
                     placeholder="Enter complete address"
-                    className="h-20"
```
Comment (rithviknishad) [inline src/components/Facility/CreateFacilityForm.tsx:308]: This was desired behaviour right? Address is a textarea field

File: src/components/Facility/CreateFacilityForm.tsx [hunk 9]
```diff
@@ -218,7 +218,6 @@ export default function CreateFacilityForm({
                     {...field}
                     data-cy="facility-description"
                     placeholder="Describe your facility (Markdown supported)"
-                    className="h-24"
```
Comment (rithviknishad) [inline src/components/Facility/CreateFacilityForm.tsx:221]: This too, descriptive field, was desired height.

**Review by rithviknishad — APPROVED** [review]

**Comment by Rishith25** [comment]
@Jacobjeevan @rithviknishad Can you assign story points for this

**Comment by Rishith25** [comment]
@Jacobjeevan i spent a good amount of time on this PR , can you please assign 1 story point 🙂

**Comment by rithviknishad** [comment]
Story points are not a measure of time, they are measure of effort and complexity involved.
