### PR TITLE
Fix Layout Overflow on Appointment and Patient Details Pages for Mobile Screens

### LINKED ISSUE #10262: Layout Overflow on Appointment and Patient Details Pages for Mobile Screens
**Describe the bug**
On the Appointment and Add Patient Details pages, layout overflow occurs on mobile screens, causing certain sections of the content to be clipped or hidden beyond the visible area. This affects usability and readability on smaller devices

**To Reproduce**

[Click here to reproduce 1](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/patient/create?)

[Click here to reproduce 2](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/appointments?practitioner=devdistrictadmin&date_from=2025-01-28&date_to=2025-02-04)

 See error

**Expected behavior**
The layout should be fully responsive on mobile screens, ensuring that all content and UI elements are properly visible without overflow

**Screenshots**

Image

Image

Galaxy Z Fold 5
Image

Image

Image

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [132.0.6834.111]

**Additional context**

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes

- Fixes #10262 
- Change 1
Screenshot 2025-01-29 004256

- Change 2

Screenshot 2025-01-29 003912

- Change 3

Screenshot 2025-01-29 003839

- Change 4

Screenshot 2025-01-29 003816

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style**
	- Updated button and layout styling in multiple components to improve responsiveness.
	- Added horizontal scrolling for tabs in the Appointments page.
	- Adjusted button heights for larger screens and widths for better screen adaptation.
	- Enhanced layout flexibility across different screen sizes.

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

File: src/components/ui/phone-input.tsx [hunk 1]
```diff
@@ -105,7 +105,7 @@ const CountrySelect = ({
         <Button
           type="button"
           variant="outline"
-          className="flex gap-1 rounded-e-none rounded-s-md border-r-0 px-3 focus:z-10 h-[38px]"
+          className="flex gap-1 rounded-e-none rounded-s-md border-r-0 px-3 focus:z-10 h-[41px] md:h-[38px]"
```
Comment (rithviknishad) [inline src/components/ui/phone-input.tsx]:
```suggestion
          className="flex gap-1 rounded-e-none rounded-s-md border-r-0 px-3 focus:z-10 h-[42px] md:h-[38px]"
```
