### PR TITLE
fix: Auto-close country codes dropdown when clicking outside the component

### LINKED ISSUE #7557: Auto-close country codes dropdown when clicking outside the component
**Describe the bug**
The country code dropdown of the phone number field is not closing when clicking outside the component.

**To Reproduce**
1. Go to the Patients tab.
2. Click on the country select in the phone number field.
3. Click outside and observe the issue.

**Expected behavior**
The country code dropdown of the phone number field should automatically close when clicking outside the component.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by UdaySagar-Git**
## Proposed Changes

- Fixes #7557  

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

File: src/Components/Form/FormFields/PhoneNumberFormField.tsx [hunk 1]
```diff
@@ -96,6 +97,23 @@ export default function PhoneNumberFormField(props: Props) {
...
+      }
+    };
+
+    document.addEventListener("mousedown", handleClickOutside);
+
+    return () => {
+      document.removeEventListener("mousedown", handleClickOutside);
+    };
+  }, []);
+
```
Comment (khavinshankar) [inline src/Components/Form/FormFields/PhoneNumberFormField.tsx]: why not separate this into its own hook, make it as a reusable hook.

**Review by khavinshankar — CHANGES_REQUESTED** [review]
just a small refactor required

File: src/Components/Form/FormFields/PhoneNumberFormField.tsx (hunk 1 above)
Comment (UdaySagar-Git) [reply src/Components/Form/FormFields/PhoneNumberFormField.tsx]: sure

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Would it be possible to use one of the headlessui component to handle the dropdown/popover? So that we won't need a custom hook to handle click outside to begin with?

**Comment by UdaySagar-Git** [comment]
> Would it be possible to use one of the headlessui component to handle the dropdown/popover? So that we won't need a custom hook to handle click outside to begin with?

will give it a try

File: src/Components/Form/FormFields/PhoneNumberFormField.tsx [hunk 2]
```diff
@@ -107,46 +107,60 @@ export default function PhoneNumberFormField(props: Props) {
...
-        />
-        {isOpen && (
-          <CountryCodesList handleCountryChange={handleCountryChange} />
-        )}
+        <Popover>
+          {({ open }: { open: boolean }) => {
+            // eslint-disable-next-line react-hooks/rules-of-hooks
+            useEffect(() => {
+              setIsOpen(open);
+            }, [open]);
```
Comment (rithviknishad) [inline src/Components/Form/FormFields/PhoneNumberFormField.tsx]:
```suggestion
```

File: src/Components/Form/FormFields/PhoneNumberFormField.tsx [hunk 3]
```diff
@@ -33,8 +34,7 @@ export default function PhoneNumberFormField(props: Props) {
     name: "India",
     code: "91",
   });
-  const [isOpen, setIsOpen] = useState<boolean>(false);
-
+  const [isOpen, setIsOpen] = useState(false);
```
Comment (rithviknishad) [inline src/Components/Form/FormFields/PhoneNumberFormField.tsx]:
```suggestion
```

File: src/Components/Form/FormFields/PhoneNumberFormField.tsx [hunk 4]
```diff
@@ -107,46 +107,60 @@ export default function PhoneNumberFormField(props: Props) {
...
+                  onChange={(e) => setValue(e.target.value)}
+                  disabled={field.disabled}
+                  onBlur={() => setError(validate(field.value, "blur"))}
+                />
+                {isOpen && (
+                  <Popover.Panel className="w-full">
+                    <CountryCodesList
+                      handleCountryChange={handleCountryChange}
+                    />
+                  </Popover.Panel>
```
Comment (rithviknishad) [inline src/Components/Form/FormFields/PhoneNumberFormField.tsx]: needs to be modified as mentioned.

**Review by rithviknishad — CHANGES_REQUESTED** [review]
You can use the `close` method provided by headlessui to avoid hacks and using an additional useState.

image

https://headlessui.com/react/popover#closing-popovers-manually

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by Ashesh3 — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]
