### PR TITLE
Fixed facility cover photo

### LINKED ISSUE #4755: Cover photo in the facility homepage is not properly reflected
**Describe the bug**

The cover photo of all the facility in the home page, is having a grey empty space in the top and bottom.

**To Reproduce**

https://care.coronasafe.in/facility

**Expected behavior**

The cover photo should be shown properly , without grey spacing

**Screenshots**

image

### PR DESCRIPTION
**Pull request by GokulramGHV**
## Proposed Changes

- Fixes #4755 
- Removed gray padding in the facility cover images

### Screenshot
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by Pranshu1902** [comment]
@GokulramGHV The card height is irregular for different facilities now
image

**Review by Pranshu1902 — APPROVED** [review]

**Comment by nihal467** [comment]
@GokulramGHV 
image

the existing staging card size looks good, rather than the size in the deploy preview, can we keep it that way?

File: src/Components/Facility/FacilityCard.tsx [hunk 1]
```diff
@@ -47,7 +47,7 @@ export const FacilityCard = (props: { facility: any; userType: any }) => {
 
   return (
     <div key={`usr_${facility.id}`} className="w-full">
-      <div className="block rounded-lg h-full overflow-clip bg-white shadow hover:border-primary-500">
+      <div className="block rounded-lg h-64 overflow-clip bg-white shadow hover:border-primary-500">
```
Comment (rithviknishad) [inline src/Components/Facility/FacilityCard.tsx:50]:
```suggestion
      <div className="block rounded-lg h-full overflow-clip bg-white shadow hover:border-primary-500">
```

File: src/Components/Facility/FacilityCard.tsx [hunk 2]
```diff
@@ -57,7 +57,7 @@ export const FacilityCard = (props: { facility: any; userType: any }) => {
               <img
                 src={facility.read_cover_image_url}
                 alt={facility.name}
-                className="w-full h-[210px] object-cover"
+                className="object-cover w-full h-full"
```
Comment (rithviknishad) [inline src/Components/Facility/FacilityCard.tsx:60]:
```suggestion
                className="object-cover h-full"
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@GokulramGHV try these changes, it seems to have solved it

**Comment by nihal467** [comment]
@GokulramGHV once you make the changes, mark it for testing

File: src/Components/Facility/FacilityCard.tsx (hunk 1 above)
Comment (GokulramGHV) [reply src/Components/Facility/FacilityCard.tsx:50]: @rithviknishad making this change makes the facility cards' heights not uniform as @Pranshu1902 mentioned above

File: src/Components/Facility/FacilityCard.tsx (hunk 2 above)
Comment (GokulramGHV) [reply src/Components/Facility/FacilityCard.tsx:60]: @khavinshankar

**Comment by GokulramGHV** [comment]
@nihal467 as this pr was discussed with gigin, he apporved the changes and asked me to mark it for testing

**Comment by nihal467** [comment]
LGTM

**Comment by khavinshankar** [comment]
@rithviknishad  can you rereview this

**Review by rithviknishad — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]
