### PR TITLE
Patient Tabs Fixes

### LINKED ISSUE #10597: Patient Tabs Modifications
**Describe the bug**

### Encounters
Encounter History currently uses old consultation related verbiage, as well as leads to the old link when there are no encounters.

### Requests
Add create requests button doesn't work

### Updates
Add patient updates doesn't work

**To Reproduce**

1. Login and navigate to any facility
2. Click on Search Patients and add a new patient
3. Register a Patient
4. Skip adding an encounter after registration
5. Navigate to the Patient profile page (you can search for the patient by going back to dashboard > Org (Kerala) > Patients)

Alternatively:

A sample patient: https://care.ohc.network/patient/1895fd57-cbbe-4804-afba-ef5d63194423/encounters

**Expected behavior**

## All Patient Tabs

- Modify facility Id in patient props to be optional, you need to adjust all the patient tabs appropriately.

### Encounters Tab

- Replace the verbiage (No encounter history, Add Encounter)
      - add any keys to en.json where necessary
      - remove the old keys from all language files 
             - no_consultation_history, add_consultation
- Replace button link with CreateEncounterForm (see usage in VerifyPatient.tsx).

### Updates Tab

- Hide add patient updates button where there's no facility Id

### Requests Tab

- Hide add create requests button when there's no facility Id

Feel free to reach out if you need any additional clarifications.

### LINKED ISSUE #10699: Hide the discharge summary from file upload section on patient details page
**Describe the bug**

When attempting to access the Discharge Summary in the Files section of the Patient Details page, the API request is not being sent correctly to the backend. This results in a 400 error being displayed on the frontend.

**To Reproduce**

1. Go to patient details page of any patient
2. Click on files
3. select the discharge summary

**Expected behavior**

The Discharge Summary should be hidden from the file upload section on the Patient Details page.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by Jacobjeevan**
## Proposed Changes

- Fixes #10597 
  - consultation -> encounter verbiage
  - used CreateEncounterForm in patient page when no encounter was present
  - removed add updates and navigation in patient updates page (only used here; facility/patient page uses different component)
  - made create resource button only viewable from facility/patient page
  - discharge summary should only be accessible on encounter files
      - Fixes #10699

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Updated user interface text now focuses on patient encounters instead of consultations—for example, labels like "Add Encounter" and messages such as "No encounter history available" have been introduced.
  - Enhanced multilingual support enables dynamic translation of encounter-related forms and messages.
  - Encounter actions and options now adapt based on facility availability, streamlining the user experience.

- **Bug Fixes**
  - Improved rendering logic ensures that certain buttons and messages display correctly based on the presence of facility identifiers.

- **Chores**
  - Removed unnecessary props and navigation options to simplify components and enhance clarity in displayed information.

### CODE REVIEW

File: src/components/Files/FilesTab.tsx [hunk 1]
```diff
@@ -651,27 +650,29 @@ export const FilesTab = (props: FilesTabProps) => {
...
-            <Link
-              className="text-gray-600"
-              href={`/facility/${encounter?.facility.id}/encounter/${encounter?.id}/files/discharge_summary`}
-            >
-              {t("discharge_summary")}
-            </Link>
-          </TabsTrigger>
-        </TabsList>
+        {type === "encounter" && (
+          <TabsList className="grid w-auto grid-cols-2 w-fit">
```
Comment (rithviknishad) [inline src/components/Files/FilesTab.tsx]: aren't the two classes `w-auto` and `w-fit` conflicting? 🤔

Comment (Jacobjeevan) [reply src/components/Files/FilesTab.tsx]: yep, adjusted 👍

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
