### PR TITLE
Fixed: Bed assign malfunction in consultation form

### LINKED ISSUE #3274: Bed Assign Malfunction : Consultation Page
https://care.coronasafe.in/facility/bd466cf6-0fde-46b1-9591-0acf9d955dd1/patient/c4c9bddc-8764-463c-a0fd-dc3c6a322e04/consultation/78c3d426-9e2e-477a-9e1a-a17e62953004

image

image

- [ ] the patient is already assigned to bed 2, but when we click update consultation details and check it, we can't see the bed in there 
- [ ] when we are submitting the consultation by selecting an already in-use bed in the consultation form, it is getting accepted

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #3274
- [x] Updated bed to store `BedModel` instead of storing `bed's id`
- [x] Used state function to set initial bed

### CODE REVIEW

**Comment by nihal467** [comment]
@cp-Coder 
image

iam not able to assign bed in the consultation page

**Comment by aeswibon** [comment]
@nihal467 I have discussed this issue with Gigin. The conclusion was to make this field disabled.

**Comment by nihal467** [comment]
test approved

File: src/Components/Facility/ConsultationForm.tsx [hunk 1]
```diff
@@ -275,9 +275,10 @@ export const ConsultationForm = (props: any) => {
             special_instruction: res.data.special_instruction || "",
             weight: res.data.weight ? res.data.weight : "",
             height: res.data.height ? res.data.height : "",
-            bed: res.data?.current_bed?.bed_object?.id || null,
+            bed: res.data?.current_bed?.bed_object || null,
```
Comment (khavinshankar) [inline src/Components/Facility/ConsultationForm.tsx:278]: don't forget to make the respective changes like, types, also check other places

**Comment by cp-Coder** [comment]
@khavinshankar I have checked the types of consultation form. In consultation model,  has type of , so I have set that type in consultation form too.

**Comment by aeswibon** [comment]
@khavinshankar I have checked the types of consultation form. In consultation model, `bed` has type of `BedModel`, so I have set that type in consultation form too.

**Review by khavinshankar — APPROVED** [review]
