### PR TITLE
Enhanced Patient Sorting + Adds reusable component: `SortDropdownMenu` with locale support

### LINKED ISSUE #5118: enhancement of sort by filter & badges
**Describe the bug**

- instead of space in between words, the badges are using "_" in the text for all the sort by filters in the patient tab
-  bed number sort by filter badges is difficult to understand.
-  ascending and descending filters are mentioned as "-" inside the badges
- Sort by ordering is not intuitive

**To Reproduce**

1. Go to patient tab
2. https://care.coronasafe.in/patients?page=1&limit=12&ordering=facility__name%2Clast_consultation__current_bed__bed__name
3. See error

**Expected behavior**

- [ ] rename options in sort by dropdown as:
- Created date Ascending to "Oldest created date",
- Created date Descending to "Latest created date",
- Modified date Ascending to "Oldest updated date",
- Modified date Descending to "Latest updated date",
- Review time Ascending to "Oldest review time",
- Review Time Descending to "Latest review time",
- Patient Name Ascending to "Patient name (A to Z)",
- Patient Name Descending to "Patient name (Z to A)",
- Bed No Ascending to "Bed No. (1 to n)",
- Bed No Descending to "Bed No. (n to 1)",

- [ ] rearrange sort by dropdown as below:
- Latest created date
- Oldest created date
- Latest updated date
- Oldest updated date
- Bed No. (1 to n)
- Bed No. (n to 1)
- Latest review time
- Oldest review time
- Patient name (A to Z)
- Patient name (Z to A)

- [ ] make the bed number sort by filter badge and other badges user-readable eg: "Ordering: Bed No (1 to n)"

**Screenshots**

image

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Fixes #5118
- Adds `SortDropdownMenu`
- `useFilter`'s badges to support ordering badges to use labels from locale.

#### Example Usage:

Ensure the sort option values are present in the `SortOptions.json` locale file.
Display label is obtained from the ordering filter's value via locale.

```jsx
<SortDropdownMenu
  onSelect={({ ordering }) => updateQuery({ ordering })}
  options={[
    { isAscending: false, value: "-created_date" },
    { isAscending: true, value: "created_date" },
    { isAscending: false, value: "-modified_date" },
    { isAscending: true, value: "modified_date" },
  ]}
/>
```

**Locale File:**
image

### Screenshots
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

File: src/Locale/en/index.js [hunk 1]
```diff
@@ -22,4 +23,5 @@ export default {
   ...Hub,
   ...Notifications,
   ...Shifting,
+  SortOptions,
```
Comment (rithviknishad) [inline src/Locale/en/index.js:26]: voluntarily scoping to prevent name conflicts. (eg: "created_date" sort option conflicts with "created_date": "Created Date")

cc: @khavinshankar

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
