### PR TITLE
Fix transfer error message display

### LINKED ISSUE #2712: Failed patient transfer shows an additional success message
When transferring a patient, if an error happens, a malformed success box is also shown. This should not appear when the transfer has failed.

image

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #2712 

Before:
image

After:
image

### CODE REVIEW

File: src/Components/Facility/TransferPatientDialog.tsx [hunk 1]
```diff
@@ -130,7 +130,7 @@ const TransferPatientDialog = (props: Props & WithStyles<typeof styles>) => {
         transferPatient(data, { id: state.form.patient })
       );
       setIsLoading(false);
-      if (res && res.data) {
+      if (res && res.data && res.status === 200) {
```
Comment (arpancodes) [inline src/Components/Facility/TransferPatientDialog.tsx:133]: do we need `res.data` here?

Comment (Ashesh3) [reply src/Components/Facility/TransferPatientDialog.tsx:133]: Maybe if body is empty but response code is 200? Not sure, but it's checked everywhere else in the care_fe repo

Comment (arpancodes) [reply src/Components/Facility/TransferPatientDialog.tsx:133]: I believe `res.data` is checked where we are using the response... here only `res` and `res.status` should do...

Comment (arpancodes) [reply src/Components/Facility/TransferPatientDialog.tsx:133]: But in JS empty object will return `true` anyways 😕

Comment (Ashesh3) [reply src/Components/Facility/TransferPatientDialog.tsx:133]: > But in JS empty object will return `true` anyways 😕

That's right! But in case of axios, it does not return an empty object instead an empty string. 
So when the response is empty, `res.data` becomes `''`
and when it has data, it's an object of key value pairs representing the response. 

image

So I think checking for `res.data` makes sense here?

**Review by arpancodes — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]
