### PR TITLE
Removed close button and fixed clicking outside issues in Duplicate Warning Message

### LINKED ISSUE #11417: Duplicate Patient Warning Message can be bypassed
**Describe the bug**
When a pre-existing number is given while adding a new patient, a duplicate warning message is shown. But the user can select neither option and just close the modal to suppress the warning.

**To Reproduce**
Go to any facility -> Search Patients -> Add new patient -> Enter duplicate phone number -> Close the warning message and submit the details

**Expected behavior**
The user should only be able to choose from one of the two options. Otherwise it results in duplicate patients being added.

**Screenshots**

https://github.com/user-attachments/assets/2b13b1ff-3d27-4afb-b0f8-90164425500a

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Spandan-Mishra**
## Proposed Changes

- Fixes #11417 
- Removed the close button
- Made the Dialog into a modal, so that it doesn't close when user clicks outside

## Video showing changes

https://github.com/user-attachments/assets/05d7cc76-ae68-457c-a3b1-87cb73e10299

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - The duplicate patient alert dialog now behaves as a modal, requiring users to explicitly confirm their actions.

- **Refactor**
  - Enhanced interaction handling for the dialog by managing outside interactions and removing the direct close option, leading to a more controlled user experience.

### CODE REVIEW

**Comment by Spandan-Mishra** [comment]
@rithviknishad @Jacobjeevan made changes which fix the issue
The Dialog still has a close button (X) which is non functional, as shown in the video.
Should we change that too? I think its a shadCN problem though.

File: src/components/Facility/DuplicatePatientDialog.tsx [hunk 1]
```diff
@@ -35,7 +35,11 @@ const DuplicatePatientDialog = (props: Props) => {
   const [action, setAction] = useState("");
 
   return (
-    <Dialog open={open} onOpenChange={onOpenChange}>
+    <Dialog
+      open={open}
+      onOpenChange={(open) => open && onOpenChange(open)}
```
Comment (rithviknishad) [inline src/components/Facility/DuplicatePatientDialog.tsx]: what does this even do? 🤔 

```suggestion
```

Comment (Spandan-Mishra) [reply src/components/Facility/DuplicatePatientDialog.tsx]: In the previous implementation, when a user clicked outside the dialog, it would close it. But by using this logic, it ensures that this doesn't happen. 

- When open === true, the dialog shows as expected.
- Even when open === false, the openOnChange isn't triggered (as false && false, would give result false, and handleDialogClose isn't triggered)

Only when the user selects second option and clicks on continue, handleDialogClose is triggered and the Dialog is closed. 

I tried other methods, but this was the one which seemed to work. I think it would be better to just use a modal, instead of changing a dialog into a modal.

Comment (Spandan-Mishra) [reply src/components/Facility/DuplicatePatientDialog.tsx]: Do we need this modal like behaviour, or any other implementation is required? : )
@rithviknishad

Comment (rithviknishad) [reply src/components/Facility/DuplicatePatientDialog.tsx:40]: code that's readable only will be accepted :)

Comment (rithviknishad) [reply src/components/Facility/DuplicatePatientDialog.tsx]: isn't that equivalent of NOT having that line in the first place? 🤔

Comment (Spandan-Mishra) [reply src/components/Facility/DuplicatePatientDialog.tsx]: That's also true. This defeats the purpose of passing the variable. 😅
So should we allow the user to click outside and close the dialog? But that would cause the same problem as mentioned in the issue.

Comment (Jacobjeevan) [reply src/components/Facility/DuplicatePatientDialog.tsx]: No, check Shadcn's documentation for dialog; there's a way to do so.

As for (x) button, you can hide it with class (`[&>button]:hidden`).

🤔  On click outside, maybe good to add a pulse animate effect for the dialog.

Comment (Spandan-Mishra) [reply src/components/Facility/DuplicatePatientDialog.tsx]: I'll make these changes by EOD 👍🏻

**Comment by Spandan-Mishra** [comment]
@rithviknishad @Jacobjeevan 
- Clicking outside dialog doesn't close it (correct approach).
- Removed close button
- Added red border on clicking outside the dialog

File: src/components/Facility/DuplicatePatientDialog.tsx [hunk 2]
```diff
@@ -33,10 +33,27 @@ const DuplicatePatientDialog = (props: Props) => {
...
   const [action, setAction] = useState("");
+  const [isOutside, setIsOutside] = useState(false);
+  const dialogRef = useRef<HTMLDivElement | null>(null);
 
   return (
     <Dialog open={open} onOpenChange={onOpenChange}>
-      <DialogContent className="w-3/4 md:w-1/2">
+      <DialogContent
+        ref={dialogRef}
+        className={`[&>button:last-child]:hidden w-3/4 md:w-1/2 ${isOutside ? "border-4 border-red-500" : "border-none"}`}
```
Comment (rithviknishad) [inline src/components/Facility/DuplicatePatientDialog.tsx]: let's not add red-border and all. just keep things simple.

Comment (Spandan-Mishra) [reply src/components/Facility/DuplicatePatientDialog.tsx]: @rithviknishad done 👍🏻

File: src/components/Facility/DuplicatePatientDialog.tsx [hunk 3]
```diff
@@ -36,7 +36,12 @@ const DuplicatePatientDialog = (props: Props) => {
 
   return (
     <Dialog open={open} onOpenChange={onOpenChange}>
-      <DialogContent className="w-3/4 md:w-1/2">
+      <DialogContent
+        className="[&>button:last-child]:hidden w-3/4 md:w-1/"
```
Comment (rithviknishad) [inline src/components/Facility/DuplicatePatientDialog.tsx]: there are invalid classes here

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

File: src/components/Facility/DuplicatePatientDialog.tsx [hunk 4]
```diff
@@ -36,7 +36,12 @@ const DuplicatePatientDialog = (props: Props) => {
 
   return (
     <Dialog open={open} onOpenChange={onOpenChange}>
-      <DialogContent className="w-3/4 md:w-1/2">
+      <DialogContent
+        className="[&>button:last-child]:hidden w-3/4 md:w-1/2"
+        onInteractOutside={(e) => {
```
Comment (Jacobjeevan) [inline src/components/Facility/DuplicatePatientDialog.tsx:41]: also add onEscapeKeyDown

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Review by Jacobjeevan — APPROVED** [review]

**Review by shivankacker — APPROVED** [review]
