### PR TITLE
Fixes: Removing remove Button for the Selected Form Page

### LINKED ISSUE #10310: Remove the remove button the edit question page
**Describe the bug**

When a user accidently click on the remove button, there is no way to add them back

**To Reproduce**

**Expected behavior**

We should hide the remove button for structure question edit page (@amjithtitus09 can you take a confirmation from @gigincg or @bodhish before executing it)

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by Sulochan-khadka**
## Proposed Changes

- Fixes #10310 
- Removed the remove button for structured types.
@ohcnetwork/care-fe-code-reviewers

https://github.com/user-attachments/assets/f96b0e9a-5d99-4cdb-b8c2-bc23b0648911

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Enhanced the questionnaire form by refining when the removal option appears.
  - The removal button is now hidden based on the questionnaire slug, ensuring a more consistent and streamlined user experience.

### CODE REVIEW

File: src/components/Questionnaire/QuestionnaireForm.tsx [hunk 1]
```diff
@@ -76,6 +79,18 @@ export function QuestionnaireForm({
...
+    return [
+      "allergy_intolerance",
+      "medication_request",
+      "medication_statement",
+      "symptom",
+      "diagnosis",
+      "encounter",
+      "appointment",
+      "location_association",
+    ].includes(slug);
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireForm.tsx]: let's not redefine the array; hard to maintain as more and more structured questions comes up; 

reuse the existing array

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/QuestionnaireForm.tsx (hunk 1 above)
Comment (Sulochan-khadka) [reply src/components/Questionnaire/QuestionnaireForm.tsx]: That is what i thought , that building the array again would be inefficient, but do we have the existing array? All i can see is the StructuredQuestionType array.

**Comment by Sulochan-khadka** [comment]
@rithviknishad could you please answer the question asked above, i would really like to get this PR merged as soon as possible. @Jacobjeevan

File: src/components/Questionnaire/QuestionnaireForm.tsx (hunk 1 above)
Comment (Jacobjeevan) [reply src/components/Questionnaire/QuestionnaireForm.tsx]: You can use StructuredQuestionType in question.ts.

Comment (Sulochan-khadka) [reply src/components/Questionnaire/QuestionnaireForm.tsx]: done

File: src/components/Questionnaire/QuestionnaireForm.tsx [hunk 2]
```diff
@@ -76,6 +79,12 @@ export function QuestionnaireForm({
 
   const [activeGroupId, setActiveGroupId] = useState<string>();
   const [isInitialized, setIsInitialized] = useState(false);
+  const isStructuredSlug = (
+    slug: string | undefined,
+  ): slug is StructuredQuestionType => {
+    if (!slug) return false;
+    return Object.keys(FIXED_QUESTIONNAIRES).includes(slug);
+  };
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireForm.tsx]: i don't like the naming of this

**Review by rithviknishad — DISMISSED** [review]

File: src/components/Questionnaire/QuestionnaireForm.tsx (hunk 2 above)
Comment (Sulochan-khadka) [reply src/components/Questionnaire/QuestionnaireForm.tsx]: i am really unable to comprehend what exactly are you indicating the name to be. I hope the "StructuredQuestion" is suitable.

Comment (Jacobjeevan) [reply src/components/Questionnaire/QuestionnaireForm.tsx]: 🤔  What does that convey really? isStructuredQuestion would make more sense 👍

Comment (Sulochan-khadka) [reply src/components/Questionnaire/QuestionnaireForm.tsx]: will do! 😁

**Comment by bodhish** [comment]
remove button should not be shown for the selected form, be it structured or non

**Comment by Sulochan-khadka** [comment]
> remove button should not be shown for the selected form, be it structured or non

So all i need to do is to check if the id==slug right @bodhish

**Comment by Sulochan-khadka** [comment]
> remove button should not be shown for the selected form, be it structured or non

you mean , we should not have remove button for the first question, right? Or remove the remove-button altogether?
Screenshot 2025-03-10 at 8 35 51 PM

cc: @Jacobjeevan @rithviknishad @nihal467

**Comment by amjithtitus09** [comment]
> > remove button should not be shown for the selected form, be it structured or non
> 
> you mean , we should not have remove button for the first question, right? Or remove the remove-button altogether? Screenshot 2025-03-10 at 8 35 51 PM
> 
> cc: @Jacobjeevan @rithviknishad @nihal467

@Sulochan-khadka Shouldn't have for the first question

**Comment by Sulochan-khadka** [comment]
@amjithtitus09 could you kindly check if this works?

**Comment by amjithtitus09** [comment]
> @amjithtitus09 could you kindly check if this works?

@Sulochan-khadka Can you explain the change you have done? What do you think about removing the button for the ones with the slug equal to slug in the url?

**Review by amjithtitus09 — APPROVED** [review]
