### PR TITLE
fix: update payment reconciliation validations and translations

### LINKED ISSUE #13437: Record payment not working when the tender amount is not same as the payable amount (in invoice)
**Describe the bug**
Record payment not working when the tender amount is not same as the payable amount in invoice payment

**To Reproduce**

1. Go to Patients
2. Click on Encounters -> View encounter -> Accounts 
3. After creating an invoice, add different amount in payment and tender amount
4. Click record payment. Unable to submit

**Expected behavior**
Should be able to submit the form

**Desktop (please complete the following information):**

- iOS

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by abhimanyurajeesh**
## Proposed Changes
- Made `returned_amount` optional in the form schema.
- Added validation to ensure `tendered_amount` is not less than the payment amount.
- Updated translation key for recording payment to use invoice number instead of ID.
- Enhanced styling for returned amount display in the UI.

image
image

Fixes #13437

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

- New Features
  - Client-side validation prevents tendered amount being less than the payment amount.

- Bug Fixes
  - Recording payment message now shows invoice number without a leading “#”.
  - Sheet description uses the invoice number instead of an internal ID.

- Localization
  - Added key: tender_amount_cannot_be_less_than_payment_amount.
  - Updated recording_payment_for_invoice text (removed “#”).
  - Reordered a key without changing its text.

- Chores
  - Form submission normalizes monetary fields to two decimals.

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

File: src/pages/Facility/billing/PaymentReconciliationSheet.tsx [hunk 1]
```diff
@@ -212,6 +204,14 @@ export function PaymentReconciliationSheet({
...
 
   const handleSubmit = form.handleSubmit((data) => {
+    if (Number(data.tendered_amount) < Number(data.amount)) {
+      form.setError("tendered_amount", {
+        type: "manual",
+        message: t("tender_amount_cannot_be_less_than_payment_amount"),
+      });
+      return;
+    }
+
```
Comment (rithviknishad) [inline src/pages/Facility/billing/PaymentReconciliationSheet.tsx]: move this to refine...

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]
