### PR TITLE
Fix: Valueset Search working during symptom dropdown

### LINKED ISSUE #12840: Valueset search is not working with synonyms
-> Search for "part hurt" in symptoms dropdown. Backend returns "Pain", but frontend does not show it.

### PR DESCRIPTION
**Pull request by yadavshubham01**
## Proposed Changes

- Fixes #12840 

## Screenshot

https://github.com/user-attachments/assets/b74c0fa6-30b3-43a8-8945-ea7e38efef21

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved filtering of recent items in search results to show more relevant matches based on the search input.

* **Refactor**
  * Enhanced the logic for combining recent and search result items for better accuracy and maintainability.

### CODE REVIEW

File: src/components/Questionnaire/ValueSetSearchContent.tsx [hunk 1]
```diff
@@ -144,15 +144,20 @@ export default function ValueSetSearchContent({
   });
 
   // Combine recents and search results, but only show each result once
+  const filteredRecents =
+    recentsQuery.data?.filter((recent) =>
+      search.length < 3
```
Comment (AdityaJ2305) [inline src/components/Questionnaire/ValueSetSearchContent.tsx]: what's the purpose behind  checking `search.length < 3` ? 🤔

Comment (yadavshubham01) [reply src/components/Questionnaire/ValueSetSearchContent.tsx]: Should continue showing all Recents if search length < 3.

Comment (AdityaJ2305) [reply src/components/Questionnaire/ValueSetSearchContent.tsx]: why 3 ??

Comment (yadavshubham01) [reply src/components/Questionnaire/ValueSetSearchContent.tsx]: yeah ,because prevent executing search-based results if the user has typed too little (usually 1 or 2 characters) like 
backend require at least 3 characters before returning relevant match

**Comment by nihal467** [comment]
The issue has already been resolved, closing this PR

**Comment by yadavshubham01** [comment]
Hey @nihal467 @shivankacker  , Can you try adding "pain" once so that it appears in recents, and then search for "part hurt" again?
Did you notice the issue that shows up in that flow?

https://github.com/user-attachments/assets/ad1cc723-7075-466b-9214-1115cffb09dd

**Comment by nihal467** [comment]
LGTM @yadavshubham01 thanks for pinpointing the method

File: src/components/Questionnaire/ValueSetSearchContent.tsx [hunk 2]
```diff
@@ -144,15 +144,20 @@ export default function ValueSetSearchContent({
...
+        ? true
+        : recent.display?.toLowerCase().includes(search.toLowerCase()) ||
+          recent.code?.toLowerCase().includes(search.toLowerCase()),
```
Comment (rithviknishad) [inline src/components/Questionnaire/ValueSetSearchContent.tsx]: i'd consider optimizing this logic to return everything if search length is less than 3 directly without needing to traverse....

**Review by rithviknishad — DISMISSED** [review]

File: src/components/Questionnaire/ValueSetSearchContent.tsx (hunk 2 above)
Comment (yadavshubham01) [reply src/components/Questionnaire/ValueSetSearchContent.tsx]: done @rithviknishad 👍

**Review by Jacobjeevan — APPROVED** [review]
