### PR TITLE
Fix : Change Payment Page Cancel/Error Buttons to Use Cancel API Endpoint

### LINKED ISSUE #13872: Change Payment Page Cancel/Error Buttons to Use Cancel API Endpoint
**Describe the bug**
On the payment page, the "Mark as Cancelled" and "Mark as entered in error" buttons are currently using the update API endpoint to mark payments as cancelled or in error. These actions should instead use the dedicated cancel API endpoint for proper functionality and consistency.

**To Reproduce**
1. Go to the payment page for a completed transaction.
2. Click on "Mark as Cancelled" or "Mark as entered in error" in the Actions panel.
3. Observe that the update API is called instead of the cancel API endpoint.

**Expected behavior**
Clicking "Mark as Cancelled" or "Mark as entered in error" should trigger the cancel API endpoint, not the update API endpoint.

**Screenshots**
Payment page actions panel

**Desktop (please complete the following information):**
- OS: Any
- Browser: Any
- Version: Any

**Smartphone (please complete the following information):**
- Device: Any
- OS: Any
- Browser: Any
- Version: Any

**Additional context**
- The cancel API endpoint should be used for payment status changes related to cancellation or error.
- This change improves API consistency and may help downstream reporting and auditability.

### PR DESCRIPTION
**Pull request by yadavshubham01**
## Proposed Changes

Fixes #13872 

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.

## Summary by CodeRabbit

* **New Features**
  * You can now cancel a payment reconciliation directly from its detail page, selecting a reason: “Cancelled” or “Entered in error.”
  * Action buttons display progress and are temporarily disabled while the request processes, helping prevent duplicate submissions.
  * The detail view updates immediately after cancellation to reflect the selected reason and current state.

### CODE REVIEW

**Comment by yadavshubham01** [comment]
@rithviknishad @abhimanyurajeesh need review

File: src/pages/Facility/billing/paymentReconciliation/PaymentReconciliationShow.tsx [hunk 1]
```diff
@@ -75,16 +75,19 @@ export function PaymentReconciliationShow({
     enabled: !!paymentReconciliationId,
   });
 
-  const updatePaymentMutation = useMutation({
-    mutationFn: mutate(paymentReconciliationApi.updatePaymentReconciliation, {
+  const { mutate: cancelPayment, isPending } = useMutation({
```
Comment (AdityaJ2305) [inline src/pages/Facility/billing/paymentReconciliation/PaymentReconciliationShow.tsx:78]:
```suggestion
  const { mutate: cancelPayment, isCancelling } = useMutation({
```

File: src/pages/Facility/billing/paymentReconciliation/PaymentReconciliationShow.tsx [hunk 2]
```diff
@@ -75,16 +75,19 @@ export function PaymentReconciliationShow({
...
     onSuccess: () => {
-      toast.success(t("payment_status_updated"));
+      toast.success(t("payment_cancelled"));
       queryClient.invalidateQueries({
         queryKey: ["paymentReconciliation", paymentReconciliationId],
       });
     },
+    onError: () => {
+      toast.error(t("failed_to_cancel_payment"));
+    },
```
Comment (AdityaJ2305) [inline src/pages/Facility/billing/paymentReconciliation/PaymentReconciliationShow.tsx]: It is being handled by global error handler so we can remove it

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

File: src/pages/Facility/billing/paymentReconciliation/PaymentReconciliationShow.tsx (hunk 1 above)
Comment (yadavshubham01) [reply src/pages/Facility/billing/paymentReconciliation/PaymentReconciliationShow.tsx:78]: we get isPending from usemutation if use isCancelling then it gives type errors i think isPendiing is good instead using like this isPending : isCancelling

**Comment by yadavshubham01** [comment]
@rithviknishad @abhimanyurajeesh need review

**Comment by yadavshubham01** [comment]
@rithviknishad @abhimanyurajeesh @yash-learner need review

**Comment by nihal467** [comment]
LGTM

File: src/types/billing/paymentReconciliation/paymentReconciliation.ts [hunk 3]
```diff
@@ -89,3 +89,7 @@ export interface PaymentReconciliationRead extends PaymentReconciliationBase {
   account: AccountRead;
   is_credit_note: boolean;
 }
+
+export interface PaymentReconciliationCancel {
+  reason: string;
```
Comment (yash-learner) [inline src/types/billing/paymentReconciliation/paymentReconciliation.ts]:
```suggestion
  reason: PaymentReconciliationStatus;
```

**Review by yash-learner — CHANGES_REQUESTED** [review]

File: src/types/billing/paymentReconciliation/paymentReconciliation.ts (hunk 3 above)
Comment (yadavshubham01) [reply src/types/billing/paymentReconciliation/paymentReconciliation.ts]: @yash-learner done

**Review by yash-learner — APPROVED** [review]
https://github.com/ohcnetwork/care_fe/pull/13914/commits/a52ea98f77e4d4ab4c6f3fa44c1b9ab9b7c02e19

@yadavshubham01 commit message needs to be meaningful 

Something like 

```
Add proper type to reason instead of string
```

instead of `fixing`

**Review by bodhish — APPROVED** [review]
