### PR TITLE
fix: Reset form on cancel button click in schedule template sheet

### LINKED ISSUE #12224: Schedule Template value clears only on reload
**Describe the bug**
When we enter values in the Create Schedule Template, and click on the cancel button or outside the Sheet, the values are still present. The user has to manually clear all values or reload the page to get a fresh sheet.

**To Reproduce**

1.Go to Users page in any facility
2. Select any user and create template for them
3. Click the cancel button or outside the sheet 
4. Again click on create template, the same values will be present

**Expected behavior**
When the user clicks on cancel button or outside the sheet and then again clicks on Create Template, they must get a new sheet rather than the old one. This should happen without them having to refresh the page.

**Screenshots**

https://github.com/user-attachments/assets/d75c07b1-70a0-4855-98e3-5c12ba0a9525

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by siva222003**
## Proposed Changes

- Fixes #12224 
- Added form reset on cancel to prevent stale data when reopening the schedule template form.

[Screencast from 2025-05-12 23-00-52.webm](https://github.com/user-attachments/assets/aefc79cf-883f-4e9e-89c3-71c08217647a)

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved the "Cancel" button in the schedule template creation sheet to clear form fields when clicked, ensuring the form resets to its default state.
  - Enhanced cancel buttons across multiple forms to reset input fields and UI states upon cancellation.
  - Updated form sheets to separate form reset logic from sheet open/close events, triggering resets only on user-initiated cancel actions.
  - Added clearing of search inputs and selections when closing relevant sheets.
  - Ensured device selection is cleared when opening or closing the associate device sheet.
- **New Features**
  - Introduced explicit cancel buttons alongside submit buttons in various forms for clearer user control.
  - Improved button layouts with grouped cancel and submit buttons for better usability.

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Please do this for other such form sheets as well (such as schedule exception) along with this PR wherever applicable!

image

File: src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx [hunk 1]
```diff
@@ -700,7 +700,12 @@ export default function CreateScheduleTemplateSheet({
 
               <SheetFooter className="absolute inset-x-0 bottom-0 border-t border-gray-200 bg-white p-6">
                 <SheetClose asChild>
-                  <Button variant="outline" type="button" disabled={isPending}>
+                  <Button
+                    variant="outline"
+                    type="button"
+                    disabled={isPending}
+                    onClick={() => form.reset()}
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:707]: handle within sheet state instead (onOpenChange), since user can close by clicking elsewhere on screen.

Comment (rithviknishad) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:707]: Let's not do this, this was intentionally not done so that sheet's state can be restored.

What if user accidentally closes the sheet? They can restore it.

But if they voluntarily clicked cancel, form state would be discarded.

ref: https://github.com/ohcnetwork/care_fe/issues/12224#issuecomment-2870923191

Comment (siva222003) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:707]: @Jacobjeevan But here the form should reset only when we click `cancel`, right?

Comment (siva222003) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:707]: @rithviknishad There are some sheets that already manage state using `onOpenChange` to reset the form. So, do you want me to keep them as they are, or should they also reset only when `cancel` is clicked?

And also, sheets like `CreateEncounter`, which don’t have a cancel button, are also using this approach.

- My idea is to remove the reset logic from `onOpenChange` for the sheets that have a Cancel button and reset the form only when Cancel is clicked.

- And for the sheets that don’t have a cancel option, I’ll keep the current behavior as is ,resetting on `onOpenChange` (or remove it).

What do you think?

Comment (Jacobjeevan) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:707]: > @rithviknishad There are some sheets that already manage state using `onOpenChange` to reset the form. So, do you want me to keep them as they are, or should they also reset only when `cancel` is clicked?
> 
> And also, sheets like `CreateEncounter`, which don’t have a cancel button, are also using this approach.
> 
>     * My idea is to remove the reset logic from `onOpenChange` for the sheets that have a Cancel button and reset the form only when Cancel is clicked.
> 
>     * And for the sheets that don’t have a cancel option, I’ll keep the current behavior as is ,resetting on `onOpenChange` (or remove it).
> 
> 
> What do you think?

(1) Yep
(2) This seems fine, but check if the reset is expensive for the user. All form sheets should have a cancel button, so let's add it if it's missing. For other things, we can keep the behavior as is 🤔

Comment (rithviknishad) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:707]: @siva222003 could you update the status and give an updated ETA on this?

Comment (siva222003) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:707]: @rithviknishad Sorry, I was occupied with the GSoC task and couldn't complete this. I'll make the changes by EOD tomorrow.
I've also updated the ETA in the issue.

Comment (rithviknishad) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:707]: Cool, no worries! It's okay to take time, just make sure you add a new comment every time you think you'd need more time to get things wrapped...

Comment (siva222003) [reply src/pages/Scheduling/components/CreateScheduleTemplateSheet.tsx:707]: yeah, I'll keep that in mind 🙂

**Comment by siva222003** [comment]
@rithviknishad @Jacobjeevan
I have added the reset on the sheets where I felt it was needed.  
Also, I added a `Cancel` button in two sheets to handle the state reset when clicking `Cancel` instead of relying on `onOpenChange`.

Please review and let me know if any changes are needed.

**Review by Jacobjeevan — APPROVED** [review]

File: src/pages/Encounters/AssociateDeviceSheet.tsx [hunk 2]
```diff
@@ -57,7 +57,13 @@ export default function AssociateDeviceSheet({
   };
 
   return (
-    <Sheet open={open} onOpenChange={setOpen}>
+    <Sheet
+      open={open}
+      onOpenChange={() => {
+        setOpen((prev) => !prev);
+        setSelectedDevice(null);
+      }}
```
Comment (rithviknishad) [inline src/pages/Encounters/AssociateDeviceSheet.tsx]:
```suggestion
      onOpenChange={(open) => {
        setOpen(open);
        setSelectedDevice(null);
      }}
```

**Review by rithviknishad — APPROVED** [review]
minor thing

**Comment by nihal467** [comment]
LGTM
