### PR TITLE
activity definition page ui

### LINKED ISSUE #13573: activity definition page ui breaking on medium and small screen
**Describe the bug**
card ui is breaking on mobile and the category section is overflowing on medium screens.

**To Reproduce**

1. Go to any facility
2. Click on Settings and go to Activity Definitions
3. switch to Mobile View and tablet view
4. see the issue

**Expected behavior**

**Screenshots**

ImageImage

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by nikh022**
## Proposed Changes

Fixes #13573 

Screenshot 2025-08-31 102831
Screenshot 2025-08-31 102844

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

* **Refactor**
  * Redesigned ActivityDefinitionCard: larger title, right-aligned status badge, new details row showing category and kind; action button now full-width.
  * Filter labels now use translations for status and category.

* **Style**
  * Narrowed search input for improved alignment.
  * Improved icon spacing in details/action elements for clearer readability.

### CODE REVIEW

File: src/pages/Facility/settings/activityDefinition/ActivityDefinitionList.tsx [hunk 1]
```diff
@@ -154,7 +161,7 @@ export default function ActivityDefinitionList({
                   onChange={(e) =>
                     updateQuery({ search: e.target.value || undefined })
                   }
-                  className="w-full md:w-[300px] pl-10"
+                  className="w-full md:w-[280px] pl-10"
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/activityDefinition/ActivityDefinitionList.tsx]: let's switch to using tailwind classes or rem instead.

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

**Review by Jacobjeevan — APPROVED** [review]
