### PR TITLE
Fix: Facility Creation Form: Pincode Autofill Overwrites Pre-filled Geographic Data & Added Similar Approach in User Creation Form

### LINKED ISSUE #10145: Facility Creation Form: Pincode Autofill Overwrites Pre-filled Geographic Data & Add Similar Approach in User Creation Form
**Issue**

1. When the facility creation form is pre-filled based on the organization’s location (e.g., State: Kerala, District: Ernakulam, Local Body: Aluva), and then a pincode (e.g., 682001) is entered, the entire autofill based on the organization’s location is erased. Only the state and district autofill based on the pincode remain, and other fields are cleared.
2. Organisation geo location autofill is missing for user creation page

**Steps to Open User Page**

1. Open the link: [User Page](https://care.ohc.network/organization/76f8a81d-04e7-43ee-852f-1757c538b295/children/57cfdeca-37d9-4fe7-9cd2-12db285e4695/users?page=1&limit=15).
2. Click on the "Add User" button.

**Steps to Open Facility Page**

1. Open the Link : [Facility Page](https://care.ohc.network/organization/76f8a81d-04e7-43ee-852f-1757c538b295/children/57cfdeca-37d9-4fe7-9cd2-12db285e4695/facilities)
2. Click on "Add Facility" Button

**Expected behavior**

- [ ] If the pincode autofill matches the existing state and district data, the dropdown fields should not be reset.
- [ ] The user creation form should prefill geographic details (similar to the facility creation form) based on the current page’s context

**Screenshots**

Image

Image

### PR DESCRIPTION
**Pull request by Rishith25**
## Proposed Changes

- Fixes #10145 
- Pincode autofill matches the existing state and district data, the dropdown fields should not be reset.
- The user creation form prefill geographic details (similar to the facility creation form) based on the current page’s context

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Release Notes

- **New Features**
  - Enhanced organization hierarchy handling in facility and user forms
  - Added support for organization-specific user creation and management

- **Improvements**
  - Refined organization level selection logic
  - Improved form integration with organization data
  - Added organization context to user creation process

- **Technical Updates**
  - Introduced new prop `organizationId` across multiple components to support more granular organization-level interactions

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/components/Facility/FacilityForm.tsx [hunk 1]
```diff
@@ -193,7 +202,11 @@ export default function FacilityForm(props: FacilityProps) {
...
   useEffect(() => {
     if (facilityId) return;
+    const orgLevels = extractHierarchyLevels(org);
+    const districtMatch =
+      districtOrg && orgLevels.some((level) => level.name === districtOrg.name);
     const levels: Organization[] = [];
+    if (districtMatch) return;
     if (stateOrg) levels.push(stateOrg);
     if (districtOrg) levels.push(districtOrg);
     if (!stateOrg && !districtOrg && org) levels.push(org);
```
Comment (rithviknishad) [inline src/components/Facility/FacilityForm.tsx:212]: let's keep the namings agnostic of state/district/etc. some countries use different namings altogether.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by Rishith25** [comment]
@rithviknishad Can you assign story points to this
