### PR TITLE
Fix : Letter Avatar Displays When Updating Profile Image

### LINKED ISSUE #12769: Letter Avatar Displays When Updating Profile Image
**Describe the bug**
When uploading a new profile image over an existing one, it renders letter based avatar, after that it displays the new uploaded image.

**To Reproduce**

1. Go to 'Profile' and upload another profile over the existing profile
2. See error , the letter-based avatar appears briefly before the new image is displayed

https://github.com/user-attachments/assets/98e2e519-9be2-4fb0-8abb-7e797d458f49

**Expected behavior**
The letter-based avatar should not appear during this transition. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #12769

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature 
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

https://github.com/user-attachments/assets/31c426f2-a6c7-4308-8f0b-600ffb860126

- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **New Features**
  * Improved avatar image handling to better detect and respond to image load errors.
  * Enhanced fallback avatar display logic to show initials only when the image is missing or fails to load.

### CODE REVIEW

File: src/components/Common/Avatar.tsx [hunk 1]
```diff
@@ -64,18 +65,25 @@ function Avatar({
...
-      <AvatarPrimitive.Image
-        data-slot="avatar-image"
-        src={imageUrl}
-        alt={name}
-        className={cn(
-          "aspect-square size-full object-cover rounded-md",
-          className,
-        )}
-      />
+      {imageUrl && (
```
Comment (Jacobjeevan) [inline src/components/Common/Avatar.tsx]: Let's keep AvatarPrimitive.Image, check Radix UI's docs, you should be able to make use of existing props for this.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by Jeffrin2005** [comment]
@Jacobjeevan Now, We are using the onLoadingStatusChange prop from Radix UI’s Avatar to track the image loading status and used AvatarPrimitive.Image.

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
