### PR TITLE
Fix: update search parameter to display and Trim whitespace from description fields in RoleForm and TagConfigForm

### LINKED ISSUE #13021: Status filter is not working for Patient Indenfier config
**Describe the bug**

https://github.com/user-attachments/assets/5bb03086-076c-4d02-9c50-0f3394fe66a8

**To Reproduce**

- login as superadmin
- click on admin dashboard
- in sidebar , click on Patient Indenfier config
- See error

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### LINKED ISSUE #13044: Search Function Not Working in Patient Identifier Config Page
**Describe the bug**
On the Patient Identifier Config page, the search input meant to filter patient identifier configs is not working. When a user types in a specific config to search, the page continues to display all configs, instead of filtering or returning matching results.

**To Reproduce**

1. login as superadmin
2. click on admin dashboard
3. in sidebar , click on Patient Indenfier config
4. Search a config
5. see the error

**Expected behavior**
Typing in the search field should filter the configs list in real-time, showing only matching results or "No results found" if none match.

**Screenshots**

https://github.com/user-attachments/assets/9afa292a-96c3-43fd-99bb-7e308674c89f

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### LINKED ISSUE #13085: Description Field Accepts Whitespaces in Roles and Tag Config Page
**Describe the bug**
In both the Tag Config and Roles (RBAC) sections, the description field accepts input that contains only whitespace characters. 
This leads to:

- **Empty-looking description fields being saved and displayed**.

Image

- **Inconsistent UI sometimes the description field is blank, and other times it shows a dash (-) when left empty.**

Image

**To Reproduce**
Steps to reproduce For Tag Config:

1. Go to Tag Config → Click Add Tag.
2. In the Description field, input only spaces
3. Click Create Tag.
4. Tag gets created and on viewing it, the description appears blank instead of not appearing

Steps to reproduce for Roles:
1. Go to Roles (RBAC) → Click Add Role.
2. In the Description field, input only spaces.
3. Click Create Role
4. The role gets created and on viewing it, the description shows an empty space instead of the fallback dash (`-`).

**Expected behavior**
When whitespace is entered, it should be treated as empty space

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Denyme24**
## Proposed Changes

Fixes #13021
- Made Changes to patientIdentifierConfigList by updating the search param to display as per the BE change - [check](https://github.com/ohcnetwork/care/pull/3162)
 (no changes were required for status param)
- Trim whitespace from description fields in RoleForm and TagConfigForm

https://github.com/user-attachments/assets/b9200cfe-3952-4d24-aa97-348e40aa65dd

Required BE:

- https://github.com/ohcnetwork/care/pull/3162

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [X] Ensure that UI text is placed in I18n files.
- [X] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.

## Summary by CodeRabbit

* **Bug Fixes**
  * Patient Identifier Configurations: Text filtering now uses the display field; the search input correctly reflects and updates the active filter.
  * Tag Configuration Form: Description input now trims leading/trailing whitespace before validation/submission, preventing space-only entries and improving data cleanliness.

### CODE REVIEW

File: src/pages/Admin/Roles/RoleForm.tsx [hunk 1]
```diff
@@ -55,7 +55,7 @@ export default function RoleForm({
     e.preventDefault();
     const payload = {
       name: formData.name,
-      description: formData.description,
+      description: (formData.description ?? "").trim(),
```
Comment (Jacobjeevan) [inline src/pages/Admin/Roles/RoleForm.tsx]: #13139 will handle this as it's a rewrite of the component; discard changes.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Admin/Roles/RoleForm.tsx (hunk 1 above)
Comment (Denyme24) [reply src/pages/Admin/Roles/RoleForm.tsx]: did the changes

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
Check updateQuery call on line 213.

You should pull BE [PR](https://github.com/ohcnetwork/care/pull/3162) and ensure everything works first 😅 

Also update the PR desc.

**Comment by Denyme24** [comment]
> Check updateQuery call on line 213.
> 
> You should pull BE [PR](https://github.com/ohcnetwork/care/pull/3162) and ensure everything works first 😅
> 
> Also update the PR desc.

have made the necessary changes in `updateQuery` call to make sure it properly resonates with BE.
also, can't check if it is working fine, not until BE [PR](https://github.com/ohcnetwork/care/pull/3162) gets merged 😅.

**Comment by Denyme24** [comment]
> Check updateQuery call on line 213.
> 
> You should pull BE [PR](https://github.com/ohcnetwork/care/pull/3162) and ensure everything works first 😅
> 
> Also update the PR desc.

Hey @Jacobjeevan, now that the BE PR is merged, i have checked the changes locally, and its working

https://github.com/user-attachments/assets/66b49ddb-d991-4372-8ad1-95e175b21d2e

**Comment by Jacobjeevan** [comment]
> also, can't check if it is working fine, not until BE [PR](https://github.com/ohcnetwork/care/pull/3162) gets merged 😅.

For future reference, you can pull the PR locally and test.

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
@Denyme24 recheck the issue relevance and discard all unwanted changes

**Comment by Denyme24** [comment]
> @Denyme24 recheck the issue relevance and discard all unwanted changes

@nihal467, i have checked the issue relevance and it still persist, so the changes that i did is still relevant.

original one (without my changes) ⬇️

https://github.com/user-attachments/assets/da3211a0-e546-48bb-a2c7-54c3120e53fe

my branch ⬇️

https://github.com/user-attachments/assets/eed3d4ed-c824-4f87-aea8-3de8776205d5

i think you might be confused with the issue that this PR is linked with , this PR originally solves this [issue](https://github.com/ohcnetwork/care_fe/issues/13044) and [issue](https://github.com/ohcnetwork/care_fe/issues/13085) (i was told to incorporate these two issues together in the FE) , the status filter was already fixed in the BE (no changes were supposed to be done in the FE for that, so made no changes for that) .
it just fixes the search issue and the tag config form `desc` trim issue.

**Comment by Denyme24** [comment]
Hey @abhimanyurajeesh, PTAL.

**Review by rithviknishad — DISMISSED** [review]
i still don't know how this fixes #13021

**Comment by Denyme24** [comment]
> i still don't know how this fixes #13021 

status filter issue was fixed in BE solely by @nandkishorr. I was supposed to make changes for search function only in the FE.

**Comment by Jacobjeevan** [comment]
> i still don't know how this fixes #13021

Had asked him to combine #13085 with 13021. PR content is basically addressing the former as latter just involves a BE change.

**Review by Jacobjeevan — APPROVED** [review]
