### PR TITLE
Bug : fixed the Resposiveness of facility card(#10911)

### LINKED ISSUE #10911: Facility Card responsive issue
**Facility card is not properly responsive**
Below are some screenshots

Image

Image

### PR DESCRIPTION
**Pull request by Yashgupta9330**
## Proposed Changes

- Fixes #10911 
- Changes src/pages/Organization/OrganizationFacilities.tsx

@ohcnetwork/care-fe-code-reviewers

https://github.com/user-attachments/assets/d479123b-b521-42fe-ba1e-4186426cd0d5

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style/UI Enhancements**
	- Refined the layout of facility cards on the organization page for better responsiveness across various device sizes.
  
- **Bug Fixes**
	- Restored the date validation message to ensure users receive clear guidance when entering dates.

### CODE REVIEW

**Comment by Yashgupta9330** [comment]
@rithviknishad can you review this pr?

File: src/pages/Organization/OrganizationFacilities.tsx [hunk 1]
```diff
@@ -117,53 +115,57 @@ export default function OrganizationFacilities({
...
+                          className={`text-md font-medium text-gray-900 ${
+                            facilities.results.length === 1 ? "text-lg" : ""
+                          }`}
+                        >
                           {facility.name}
                         </h3>
-                        <div className="font-medium">
+                        <div
+                          className={`text-sm font-medium ${
+                            facilities.results.length === 1 ? "text-base" : ""
```
Comment (Jacobjeevan) [inline src/pages/Organization/OrganizationFacilities.tsx]: 🤔  why?

**Review by Jacobjeevan — APPROVED** [review]
~~lgtm otherwise~~

File: src/pages/Organization/OrganizationFacilities.tsx [hunk 2]
```diff
@@ -93,16 +93,14 @@ export default function OrganizationFacilities({
           {isFetching ? (
             <CardGridSkeleton count={6} />
           ) : facilities?.results?.length === 0 ? (
-            <Card className="col-span-full">
-              <CardContent className="p-6 text-center text-gray-500">
-                {t("no_facilities_found")}
-              </CardContent>
-            </Card>
+            <div className="text-center text-gray-500">
```
Comment (Jacobjeevan) [inline src/pages/Organization/OrganizationFacilities.tsx]: Add the card container back in.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
image

File: src/pages/Organization/OrganizationFacilities.tsx (hunk 2 above)
Comment (Yashgupta9330) [reply src/pages/Organization/OrganizationFacilities.tsx]: sorry i forgot to add it

File: src/pages/Organization/OrganizationFacilities.tsx
Comment (Jacobjeevan) [inline src/pages/Organization/OrganizationFacilities.tsx:1]: Let's modify the grid to:

`lg:grid-cols-2 xl:grid-cols-3`

Do the same for OrganizationUsers and OrganizationPatients.

For OrganizationUsers, grid is mentioned twice (one for loader and one for the data, modify that to be similar to what's in OrganizationFacilities and OrganizationPatients, i.e. the grid wrapping all conditions - loader, no data, and cards).

Make sure to modify the description when changes are ready.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by Yashgupta9330** [comment]
@Jacobjeevan can you look into this?

**Comment by nihal467** [comment]
@Jacobjeevan can you look into it

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
image

The text and size are smaller compared to the current develop. Keep the size as it is since  that size seem good to read properly
