### PR TITLE
fix: use AbortSignal from TanStack Query in queryFn functions

### LINKED ISSUE #14866: Fix incorrect AbortController usage in TanStack Query queries
**Describe the bug**
Multiple components are creating new `AbortController` instances instead of using the `signal` parameter provided by TanStack Query's `useInfiniteQuery` and `useQuery`. This breaks request cancellation, meaning network requests continue running even after components unmount or when queries are invalidated, leading to wasted network traffic and potential memory leaks.

**To Reproduce**

1. Open browser DevTools and go to the Network tab
2. Navigate to a page that uses infinite queries (e.g., Observation History, Vitals List, Charge Items list)
3. Quickly navigate away from the page or trigger a query invalidation
4. Observe in the Network tab that requests continue running even though the component unmounted
5. Check that requests cannot be cancelled properly when they should be

**Expected behavior**
When a component unmounts or a query is invalidated, TanStack Query should automatically cancel in-flight requests using the `AbortSignal` it provides. The requests should stop immediately, preventing unnecessary network traffic and memory usage.

**Screenshots**
Not applicable - this is a code-level issue that affects request cancellation behavior.

**Desktop:**

- OS: macOS
- Browser: Chrome
- Version: Latest

**Smartphone:**

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

**Additional context**
This issue affects 16+ files across the codebase. The problem is that `queryFn` functions are not destructuring the `signal` parameter from TanStack Query, and instead creating new `AbortController().signal` instances. 

The correct pattern should be:
queryFn: async ({ pageParam = 0, signal }) => {
  const response = await query(api, {...})({ signal });
}
Instead of:ypescript
queryFn: async ({ pageParam = 0 }) => {
  const response = await query(api, {...})({ signal: new AbortController().signal });
}
Affected files include:
- `ObservationHistoryTable.tsx`
- `VitalsList.tsx`
- `CreateInvoice.tsx`
- `NoteManager.tsx`
- `MedicationRequestQuestion.tsx`
- And 11+ more files

This prevents proper request cancellation and can cause performance issues, especially with infinite scroll queries that fetch multiple pages.

### PR DESCRIPTION
**Pull request by harsh04044**
## Proposed Changes

Fixes #14866 
- Replace `new AbortController().signal` with `signal` parameter from queryFn in all affected files
- Update queryFn signatures to accept `signal` parameter: `async ({ pageParam = 0, signal }) => {}`
- Update HistoricalRecordSelector interface to support signal parameter in custom queryFn implementations
- This enables proper request cancellation when components unmount or queries are invalidated, preventing unnecessary network traffic and potential memory leaks

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature. _(N/A - Code-level fix with no user-facing behavior changes)_
- [ ] Update [product documentation](https://docs.ohc.network). _(N/A - Internal code improvement, no API or feature changes)_
- [ ] Ensure that UI text is placed in I18n files. _(N/A - No UI text changes)_
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue. _(N/A - No visual changes, this is a code-level improvement)_
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices. _(N/A - Code-level fix, no UI or behavior changes visible to users)_
- [ ] Complete QA on desktop devices. _(N/A - Code-level fix, no UI or behavior changes visible to users)_
- [ ] Add or update Playwright tests for related changes. _(Optional - Request cancellation behavior is difficult to test with Playwright, but existing tests should still pass)_

## Summary by CodeRabbit

* **Improvements**
  * Propagate cancellation signals into list and paginated queries for consistent request aborting and more responsive UI.
  * Standardized paginated response typing for observation lists to reduce inconsistencies.
  * Improved handling of missing measurement values for more reliable display.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/components/Common/Charts/ObservationHistoryTable.tsx [hunk 1]
```diff
@@ -15,13 +15,19 @@ import {
...
+import { ObservationWithUser } from "@/types/emr/observation";
+import patientApi from "@/types/emr/patient/patientApi";
 import { useTranslation } from "react-i18next";
 
+interface PaginatedResponse<T> {
+  count: number;
+  next: string | null;
+  previous: string | null;
+  results: T[];
+}
```
[the remark this answers is not in the document]
Comment (harsh04044) [reply src/components/Common/Charts/ObservationHistoryTable.tsx]: i will fix  this in upcoming commit

File: src/components/Patient/vitals/list.tsx [hunk 2]
```diff
@@ -9,9 +9,9 @@ import { EncounterAccordionLayout } from "@/components/Patient/EncounterAccordio
 import query from "@/Utils/request/query";
 import { PaginatedResponse } from "@/Utils/request/types";
 import { Code } from "@/types/base/code/code";
-import { ObservationListRead } from "@/types/emr/observation/observation";
+import { Observation, ObservationWithUser } from "@/types/emr/observation";
```
[the remark this answers is not in the document]
Comment (harsh04044) [reply src/components/Patient/vitals/list.tsx]: i will address it upcoming commit

File: src/components/Patient/vitals/list.tsx [hunk 3]
```diff
@@ -62,10 +59,10 @@ function extractVitals(
     vitalCodes.forEach((code) => {
       if (code.display) {
         const vitalField = ob.find(
-          (fields) => fields.main_code?.code === code.code,
+          (fields) => fields.main_code.code === code.code,
```
[the remark this answers is not in the document]
Comment (harsh04044) [reply src/components/Patient/vitals/list.tsx]: i will address this in upcoming commit

File: src/components/Patient/vitals/list.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (harsh04044) [reply src/components/Patient/vitals/list.tsx]: check this i have solved this in my latest commit

File: src/types/emr/observation/index.ts [hunk 4]
```diff
@@ -0,0 +1,16 @@
+import type { ObservationListRead } from "./observation";
+
+/**
+ * Base observation type for general observation data.
+ * Use this type when user attribution (created_by, updated_by) is not the primary concern.
+ */
+export type Observation = ObservationListRead;
```
[the remark this answers is not in the document]
Comment (harsh04044) [reply src/types/emr/observation/index.ts]: i will address this in my latest commit

File: src/types/emr/observation/index.ts
Comment (Jacobjeevan) [inline src/types/emr/observation/index.ts:1]: why? Discard type changes.

File: src/pages/Encounters/tabs/observations.tsx [hunk 5]
```diff
@@ -156,16 +156,22 @@ export const EncounterObservationsTab = () => {
...
                       {item.note && (
                         <div className="mt-1 text-sm text-gray-500">
                           {item.note}
                         </div>
                       )}
                       <div className="font-medium text-sm text-gray-600">
-                        {item.main_code?.display ||
-                          item.main_code?.code ||
-                          t("unknown")}
+                        {item.main_code?.display || item.main_code?.code}
```
Comment (Jacobjeevan) [inline src/pages/Encounters/tabs/observations.tsx]: let's keep unknown

File: src/components/Common/Charts/ObservationHistoryTable.tsx [hunk 6]
```diff
@@ -49,15 +49,15 @@ export const ObservationHistoryTable = ({
   const { t } = useTranslation();
 
   const { data, isLoading, hasNextPage, fetchNextPage } = useInfiniteQuery<
-    PaginatedResponse<ObservationListRead>
+    PaginatedResponse<ObservationWithUser>
```
Comment (Jacobjeevan) [inline src/components/Common/Charts/ObservationHistoryTable.tsx]: keep types as is

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/types/emr/observation/index.ts
Comment (harsh04044) [reply src/types/emr/observation/index.ts:1]: Thanks for your review , i have correccted it in my latest commit

File: src/pages/Encounters/tabs/observations.tsx (hunk 5 above)
Comment (harsh04044) [reply src/pages/Encounters/tabs/observations.tsx]: okay

File: src/components/Common/Charts/ObservationHistoryTable.tsx (hunk 6 above)
Comment (harsh04044) [reply src/components/Common/Charts/ObservationHistoryTable.tsx]: Thanks for your review , i have correccted it in my latest commit

**Review by nihal467 — CHANGES_REQUESTED** [review]
Image

- the values are shown twice in observation section once we submit the progress note questionnaire

**Comment by harsh04044** [comment]
> Image
> * the values are shown twice in observation section once we submit the progress note questionnaire

i will address this in my upcoming commit

**Comment by harsh04044** [comment]
Screenshot 2026-01-02 at 2 30 20 AM

@nihal467   i have addressed your suggestion

**Review by nihal467 — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
