### PR TITLE
Fixed malfunction in user management regarding add user form

### LINKED ISSUE #3170: user management malfunction
image

a wayanad district admin should not be seeing option to create users for other state and district

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #3170
- [x] Removed other states from dropdown for StateAdmin and lower
- [x] Removed other districts from dropdown for DistrictAdmin and lower
- [x] Removed other localbodies from dropdown for LocalBodyAdmin and lower

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

File: src/Components/Users/UserAdd.tsx [hunk 1]
```diff
@@ -245,7 +264,17 @@ export const UserAdd = (props: UserProps) => {
...
+          setStates([
+            ...initialStates,
+            {
+              id: currentUser.data.state,
+              name: currentUser.data.state_object.name,
+            },
+          ]);
+        } else {
+          setStates([...initialStates, ...statesRes.data.results]);
+        }
```
Comment (rithviknishad) [inline src/Components/Users/UserAdd.tsx:277]: @cp-Coder @gigincg wouldn't the condition always be true and hence the else block is never executed.

`userIndex` is an index within `USER_TYPES`, and StateAdmin is the last element in `USER_TYPES` and hence it has the highest index. so...
