### PR TITLE
Fix: Tab key does not navigate correctly across form fields in user create form

### LINKED ISSUE #11799: Tab key does not navigate correctly across form fields in user create form
**Describe the bug**
When trying to jump to next field using tab key, it's not jumping in certain fields.

Noticed in username and password fields.

**To Reproduce**

1. Try filling the user create form

**Expected behavior**
The focus should move sequentially through all the input fields correctly (e.g., from input A → B → C → Submit button).

**Screenshots**

https://github.com/user-attachments/assets/fcf307f0-0cfb-4698-b527-50fcff8f099c

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #11799 
- Replaced conditional rendering with block/hidden class t
- tabIndex={-1} for toggle button so don't to focus on it 
- Tab skips the eye icon and go to the next field
- More?

https://github.com/user-attachments/assets/49f02afa-3689-4e1d-a5ff-b82e551ed14a

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Refactor**
  - Improved how validation feedback is displayed in the user form by toggling visibility with CSS instead of conditional rendering, resulting in a smoother and more consistent user experience.
  - Updated styling logic for password setup options for better maintainability.

- **Style**
  - The password visibility toggle button is now excluded from keyboard tab navigation, reducing unnecessary tab stops for keyboard users.

### CODE REVIEW

File: src/components/ui/input-password.tsx
Comment (AdityaJ2305) [inline src/components/ui/input-password.tsx:1]: I think for this issue, the changes need to be made in this component — since it’s inside the ui folder but isn’t purely a ShadCN import, it’s custom-made. So I guess it’s okay to make changes here, right? 😅

File: src/components/ui/input-password.tsx [hunk 1]
```diff
@@ -22,6 +22,7 @@ function PasswordInput({
       />
       <button
         type="button"
+        tabIndex={-1}
```
Comment (AdityaJ2305) [inline src/components/ui/input-password.tsx:25]: I think for this issue, the changes need to be made in this component — since it’s inside the ui folder but isn’t purely a ShadCN import, it’s custom-made. So I guess it’s okay to make changes here, right? 😅

**Comment by bodhish** [comment]
This was super painful, thanks a lot @AdityaJ2305

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
