### PR TITLE
Fixed Styling issues on Login Page

### LINKED ISSUE #2818: Login Page : Alignment and Border Issues
- [ ] Around the language selection button, there is always a blue border, remove the colour, then someone hovers over the button to use it, give some effect like a black border or effects in the button, whichever feels good for the UI

- [ ] make the alignment proper for the forget password & login button when checking with the password input box

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #2818
- [x] Added `Padding` to `Login` button
- [x] Removed `blue border` from `Language Selector` button

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@cp-Coder how about using the pointer cursor instead of the default one for the language selector.
image

File: src/Components/Auth/Login.tsx [hunk 1]
```diff
@@ -190,7 +190,7 @@ export const Login = (props: any) => {
                 )}
               </div>
             </CardContent>
-            <CardActions className="padding16">
+            <CardActions style={{ padding: "16px" }}>
```
Comment (kunatastic) [inline src/Components/Auth/Login.tsx]: As an alternative to inline css, Can we use tailwind classes??

Comment (aeswibon) [reply src/Components/Auth/Login.tsx]: Nope, We can't use tailwind classes for MUI components. 
If we want to use tailwind classes, then we need to replace `mui` with `material-tailwind` package

**Comment by aeswibon** [comment]
@rithviknishad I have now added the pointer cursor on the Language selector

**Comment by aeswibon** [comment]
@nihal467 This PR is good for testing

**Comment by nihal467** [comment]
@cp-Coder the forget password button is misaligned, make it aligned to login button

**Review by naman114 — APPROVED** [review]
LGTM

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@cp-Coder the spacing between forgot button and password is having more space, can you reduce it and make everything uniformly spaced !

**Comment by nihal467** [comment]
@cp-Coder status of the PR

**Comment by aeswibon** [comment]
@nihal467 Is this okay??
image

**Comment by nihal467** [comment]
@cp-Coder 

image

make it responsive

**Comment by nihal467** [comment]
@cp-Coder what is the status

**Comment by aeswibon** [comment]
@nihal467 Updated view:
image

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]
