### PR TITLE
Fixed typo in pathParams of ConfigureHealthFacility and replaced useDispatch in ConfigureFacility

### LINKED ISSUE #6469: health facility id is missing
image

the health facility id is missing facility page

### PR DESCRIPTION
**Pull request by khavinshankar**
### <samp>🤖 Generated by Copilot at b3e4d98</samp>

Refactored some components related to facility configuration to use a new data fetching hook, a helper function, and updated API routes. Improved type safety, readability, and performance by removing unused code and typing props. Updated the facility data model to match the API change.

## Proposed Changes

- Fixes #6469
- fixed typos in health facility API calls _(changed the pathParams from facility__external_id to facility_id)_
- refactor FacilityConfigure to use request and useQuery

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at b3e4d98</samp>

*  Refactor the `ConfigureHealthFacility` and `FacilityConfigure` components to use the `useQuery` hook for fetching facility data and the `request` helper for making API requests ([link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-82ab3a1b124e696b6416145151d2a8c2e3883275674526de3a812d431ce801f3L1-R1), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-82ab3a1b124e696b6416145151d2a8c2e3883275674526de3a812d431ce801f3R10), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-82ab3a1b124e696b6416145151d2a8c2e3883275674526de3a812d431ce801f3L45-R63), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-82ab3a1b124e696b6416145151d2a8c2e3883275674526de3a812d431ce801f3L86-R83), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-82ab3a1b124e696b6416145151d2a8c2e3883275674526de3a812d431ce801f3L100-R97), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-82ab3a1b124e696b6416145151d2a8c2e3883275674526de3a812d431ce801f3L154-R151), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-82ab3a1b124e696b6416145151d2a8c2e3883275674526de3a812d431ce801f3L167-R164), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-82ab3a1b124e696b6416145151d2a8c2e3883275674526de3a812d431ce801f3L218-R215), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-05f8278e8ee0b31929e50092dbc9336b93dc17b69dcc36a7d4cb9f72c413a927L1-R1), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-05f8278e8ee0b31929e50092dbc9336b93dc17b69dcc36a7d4cb9f72c413a927R8-R11), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-05f8278e8ee0b31929e50092dbc9336b93dc17b69dcc36a7d4cb9f72c413a927R22), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-05f8278e8ee0b31929e50092dbc9336b93dc17b69dcc36a7d4cb9f72c413a927L49-R74), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-05f8278e8ee0b31929e50092dbc9336b93dc17b69dcc36a7d4cb9f72c413a927L111-R111), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-05f8278e8ee0b31929e50092dbc9336b93dc17b69dcc36a7d4cb9f72c413a927L124-R124), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-05f8278e8ee0b31929e50092dbc9336b93dc17b69dcc36a7d4cb9f72c413a927L139-R131), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-05f8278e8ee0b31929e50092dbc9336b93dc17b69dcc36a7d4cb9f72c413a927L152-R144), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-05f8278e8ee0b31929e50092dbc9336b93dc17b69dcc36a7d4cb9f72c413a927L160-R152))
* Update the `FacilityModel` interface and the API routes to reflect the changes in the facility data model and the parameters ([link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfL31), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfR55-R58), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cL244-R250))
* Move the `FacilityConfigure.tsx` file from `src/Components/Facility` to `src/Components/ABDM` as part of the refactoring of the ABDM module ([link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-05f8278e8ee0b31929e50092dbc9336b93dc17b69dcc36a7d4cb9f72c413a927L1-R1))
* Remove unused imports and improve formatting in `api.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cL20), [link](https://github.com/coronasafe/care_fe/pull/6470/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cL31-R35))

### CODE REVIEW

File: src/Components/Facility/FacilityConfigure.tsx [hunk 1]
```diff
@@ -46,44 +44,34 @@ const FormReducer = (state = initialState, action: any) => {
...
-          dispatch({ type: "set_form", form: formData });
-        } else {
-          navigate(`/facility/${facilityId}`);
-        }
-        setIsLoading(false);
+  const { loading } = useQuery(routes.getPermittedFacility, {
+    pathParams: { id: facilityId },
+    onResponse: (res) => {
+      if (res.data) {
+        console.log(res.data);
```
Comment (rithviknishad) [inline src/Components/Facility/FacilityConfigure.tsx]:
```suggestion
```

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by gigincg — APPROVED** [review]
