### PR TITLE
UI Fix: Move See Details button to bottom in Product Knowledge page

### LINKED ISSUE #13381: Badges text breaking for mobile screen product knowledge listing page
Image

### Steps to Reproduce
- Go to any facility 
- Go to sidebar setting tab 
- Go to pk subtab 
- See the ui error on mobile screen size (use dev tool)

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by LibinThankayathil**
## Proposed Changes

Fixes #13381  
- Moved the `See Details` button to bottom right using tailwind classes

image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

- **Style**
  - Repositioned the “See Details” button in Product Knowledge cards to its own row below the product header, improving visual hierarchy and readability.
  - Enhanced alignment and spacing for a cleaner layout, especially on smaller screens, reducing header crowding.

- **Bug Fixes**
  - Standardized the “See Details” control across card, mobile and table views and updated its target to a unified product knowledge page, ensuring consistent navigation.

- **Refactor**
  - Simplified product card usage by removing the facility context requirement, streamlining component invocation.

### CODE REVIEW

File: src/pages/Facility/settings/productKnowledge/ProductKnowledgeList.tsx [hunk 1]
```diff
@@ -66,19 +66,20 @@ function ProductKnowledgeCard({
...
+          className="ml-auto block"
+          onClick={() =>
+            navigate(
+              `/facility/${facilityId}/settings/product_knowledge/${product.id}`,
+            )
+          }
+        >
+          <CareIcon icon="l-edit" className="size-4" />
+          {t("see_details")}
+        </Button>
```
Comment (rithviknishad) [inline src/pages/Facility/settings/productKnowledge/ProductKnowledgeList.tsx]: let's wrap with `Link` and use asChild for the button. 

Currently this does not allow users to right click and open in new tab and couple other things... All buttons with simply navigate onClick needs to be changed to button wrapped in link component ideally!

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

File: src/pages/Facility/settings/productKnowledge/ProductKnowledgeList.tsx (hunk 1 above)
Comment (LibinThankayathil) [reply src/pages/Facility/settings/productKnowledge/ProductKnowledgeList.tsx]: Wrapped the `Button` inside `Link`. But when adding asChild in `Button` the page shows couldn't load error

Comment (rithviknishad) [reply src/pages/Facility/settings/productKnowledge/ProductKnowledgeList.tsx]: mind sharing what's the error?

**Review by rithviknishad — APPROVED** [review]

File: src/pages/Facility/settings/productKnowledge/ProductKnowledgeList.tsx (hunk 1 above)
Comment (LibinThankayathil) [reply src/pages/Facility/settings/productKnowledge/ProductKnowledgeList.tsx]: https://github.com/user-attachments/assets/067ce7cf-b579-4eee-beaf-f9539b1f2ba4

**Comment by nihal467** [comment]
LGTM

File: src/pages/Facility/settings/productKnowledge/ProductKnowledgeList.tsx [hunk 2]
```diff
@@ -251,18 +244,12 @@ export default function ProductKnowledgeList({
...
-                          >
-                            <CareIcon icon="l-edit" className="size-4" />
-                            {t("see_details")}
-                          </Button>
+                          <Link href={`/product_knowledge/${product.id}`}>
+                            <Button variant="outline" size="sm">
+                              <CareIcon icon="l-edit" className="size-4" />
+                              {t("see_details")}
+                            </Button>
+                          </Link>
```
[the remark this answers is not in the document]
Comment (rithviknishad) [reply src/pages/Facility/settings/productKnowledge/ProductKnowledgeList.tsx]: @LibinThankayathil check this out

[the remark this answers is not in the document]
Comment (LibinThankayathil) [reply src/pages/Facility/settings/productKnowledge/ProductKnowledgeList.tsx]: `href={`/facility/${facilityId}/settings/product_knowledge/${product.id}`}` isn't redirecting to the required page

**Review by Jacobjeevan — APPROVED** [review]
