### PR TITLE
Redesigned the dashboard for the user organisation page

### LINKED ISSUE #11016: Redesign the users organisation dashboard based on new figma design
**Describe the bug**

Redesign the user's organisation dashboard based on the new Figma design (https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=9717-2482&t=YHHDkQltmZ2bBTJK-1)

Note: The views for my facility, association, and administration sections should be included in the related PR

Screenshot

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Spandan-Mishra**
## Proposed Changes
Redesigned the user's organization page which was assigned to me in issue #11016.

- Fixes #11016 
- Moved buttons for editing profile and signing out to the right, added vertical ellipsis.
- Added a banner for users who are signed in as doctors
- Added a tab where users can switch between their facilities, associations and administrations.
- Added more localization keys in en.json

**Video which shows the changes made:**

https://github.com/user-attachments/assets/9057a1cf-3eb4-4bdb-a704-32da714f2269

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Introduced a tabbed dashboard interface that organizes user-related information into sections: Facilities, Associations, and Governance.
  - Enhanced welcome messages with more personalized greetings, including specific messages for doctors.
  - Added new contextual information regarding affiliations and healthcare facilities in the dashboard.
  - Added new entries for displaying messages when no associations or governance are found.
- **Bug Fixes**
  - Improved filtering logic for displaying organizations based on user roles and governance types.
- **Style**
  - Refined the layout and visual presentation across dashboard sections for improved clarity and consistency, including adjustments to text alignment and avatar size.

### CODE REVIEW

**Comment by bodhish** [comment]
Lets rename `administration` to `governance`

**Comment by Spandan-Mishra** [comment]
any other changes needed? @bodhish

**Comment by nihal467** [comment]
@Spandan-Mishra can you look into code rabbit comments

**Comment by Spandan-Mishra** [comment]
@nihal467 should I make the changes mentioned by coderabbit and make another commit?

**Comment by Jacobjeevan** [comment]
> @nihal467 should I make the changes mentioned by coderabbit and make another commit?

If the suggestion makes sense yes

File: src/pages/UserDashboard.tsx [hunk 1]
```diff
@@ -19,144 +26,281 @@ export default function UserDashboard() {
...
-            <LogOut className="h-4 w-4" />
-            {t("sign_out")}
-          </Button>
+            <Button
+              variant="outline"
+              size="sm"
+              className="w-full sm:w-auto"
+              asChild
+            >
+              <EllipsisVerticalIcon className="h-4 w-4" />
```
Comment (yash-learner) [inline src/pages/UserDashboard.tsx]: You can use `care icon` here https://care.ohc.network/icons `<CareIcon icon="l-ellipsis-v" />`

File: src/pages/UserDashboard.tsx [hunk 2]
```diff
@@ -19,144 +26,281 @@ export default function UserDashboard() {
...
+                        </CardContent>
+                      </Card>
+                    </Link>
+                  ))}
+                </div>
+              )}
+            </section>
+          )}
+
+          {/*Associations Section*/}
```
Comment (yash-learner) [inline src/pages/UserDashboard.tsx]: We can remove comments like these. Use only when necessary

**Review by yash-learner — CHANGES_REQUESTED** [review]
As per the [Figma design](https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=9717-2482&t=cueXLL157eEEV4OE-0), the `Sign out` button is expected to move inside the ` kebab menu` .

cc: @vinutv

**Comment by Spandan-Mishra** [comment]
@nihal467 @Jacobjeevan 
Implemented the changes given by coderabbit. Except moving the tab contents to another component, as it was making the code more complex, and did not reduce code redundancy.

@yash-learner 
Moved Sign Out under the menu, used CareIcon and removed unnecessary comments.

**Comment by AdityaJ2305** [comment]
@Spandan-Mishra , do "Mark as Resolved" with comment or acknowledgement after changes are done or unnecessary ones by coderabbitai

**Comment by Spandan-Mishra** [comment]
Resolved all useful as well as unnecessary changes @AdityaJ2305

File: src/pages/UserDashboard.tsx [hunk 3]
```diff
@@ -12,151 +21,301 @@ import useAuthUser, { useAuthContext } from "@/hooks/useAuthUser";
...
+                            </p>
+                          </div>
+                          <ChevronRight className="h-4 w-4 md:h-5 md:w-5 text-gray-500" />
+                        </CardContent>
+                      </Card>
+                    </Link>
+                  ))}
+                </div>
+              )}
+            </section>
```
Comment (yash-learner) [inline src/pages/UserDashboard.tsx]: You can extract this into a separate component, repeating the same type of structure for all three tabs

**Review by yash-learner — CHANGES_REQUESTED** [review]
image


I think we can make this card better by moving `Admin Dashboard` and `Edit profile` button as well inside the `kekab menu` for  mobile devices 


---

Also align the Avatar and text below it properly on mobile devices

---


I think we can change the `My Facilities` to `Facilities` cc: @ohcnetwork/care-fe-code-reviewers

**Comment by yash-learner** [comment]
@Spandan-Mishra 

Adding for context. here is the discussion on slack regarding UI/UX of 
 card on mobile https://rebuildearth.slack.com/archives/C080225HC6B/p1741346917485939

**Comment by Spandan-Mishra** [comment]
made the card mobile responsive and reduced code redundancy
@yash-learner @Jacobjeevan

File: public/locale/en.json [hunk 4]
```diff
@@ -2575,8 +2580,10 @@
   "we_ve_sent_you_a_code_to": "We've sent you a code to",
   "weekly_schedule": "Weekly Schedule",
   "weekly_working_hours_error": "Average weekly working hours must be a number between 0 and 168",
-  "welcome_back_name": "Welcome Back {{name}} !",
+  "welcome_back": "Welcome back,",
   "welcome_back_to_hospital_dashboard": "Welcome back to the overview ",
+  "welcome_dr": "Dr. {{name}}",
+  "welcome_dr_banner": "You are logged in as a doctor!",
```
Comment (Jacobjeevan) [inline public/locale/en.json]: what about other user types? 🤔 

Let's change it to accept the user type (similar welcome_dr).

File: src/pages/UserDashboard.tsx [hunk 5]
```diff
@@ -12,151 +21,319 @@ import useAuthUser, { useAuthContext } from "@/hooks/useAuthUser";
...
+  TAB_ASSOCIATIONS = "Associations",
+  TAB_GOVERNANCE = "Governance",
+}
+
+type Item = {
+  id: string | number;
+  [key: string]: any;
+};
+
+type RenderLinkFunction = (item: Item) => JSX.Element;
```
Comment (Jacobjeevan) [inline src/pages/UserDashboard.tsx]: Let's inline this instead of defining a separate type.

File: src/pages/UserDashboard.tsx [hunk 6]
```diff
@@ -12,151 +21,319 @@ import useAuthUser, { useAuthContext } from "@/hooks/useAuthUser";
...
+                  </DropdownMenuItem>
+                )}
+                <DropdownMenuItem
+                  className="cursor-pointer flex items-center gap-2 text-xs w-full sm:w-auto"
+                  onClick={signOut}
+                >
+                  <LogOut className="h-4 w-4" />
+                  {t("sign_out")}
+                </DropdownMenuItem>
+                <DropdownMenuItem className="cursor-pointer flex sm:hidden items-center gap-2 text-xs w-full sm:w-auto">
```
Comment (Jacobjeevan) [inline src/pages/UserDashboard.tsx]: let's move edit profile above sign out (don't forget to adjust the visibility attribute once you remove button outside of the dropdown menu).

File: src/pages/UserDashboard.tsx [hunk 7]
```diff
@@ -12,151 +21,319 @@ import useAuthUser, { useAuthContext } from "@/hooks/useAuthUser";
...
+                <Button
+                  variant="outline"
+                  size="sm"
+                  className="px-2 w-full sm:w-auto"
+                >
+                  <CareIcon icon="l-ellipsis-v" className="text-inherit" />
+                </Button>
+              </DropdownMenuTrigger>
+              <DropdownMenuContent align="end" className="w-40">
+                {user.is_superuser && (
```
Comment (Jacobjeevan) [inline src/pages/UserDashboard.tsx:116]: let's remove admin dashboard in drop down, redundant anyways.

File: src/pages/UserDashboard.tsx [hunk 8]
```diff
@@ -12,151 +21,319 @@ import useAuthUser, { useAuthContext } from "@/hooks/useAuthUser";
...
             >
               <Link
-                href="/admin/questionnaire"
+                href={`/users/${user.username}`}
                 className="gap-2 text-inherit flex items-center"
               >
-                <User2Icon className="h-4 w-4" />
-                {t("admin_dashboard")}
+                <SquarePen className="h-4 w-4" />
+                {t("edit_profile")}
```
Comment (Jacobjeevan) [inline src/pages/UserDashboard.tsx]: let's also remove the edit profile button outside the kebab menu

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: public/locale/en.json (hunk 4 above)
Comment (Spandan-Mishra) [reply public/locale/en.json]: The user_type field either had 'doctor' value or none. So what should I implement?

File: src/pages/UserDashboard.tsx (hunk 8 above)
Comment (Spandan-Mishra) [reply src/pages/UserDashboard.tsx]: So which buttons should the kebab menu have in desktop and mobile views? Please do specify

File: src/pages/UserDashboard.tsx (hunk 7 above)
Comment (Spandan-Mishra) [reply src/pages/UserDashboard.tsx:116]: This will only be visible in mobile view. In desktop mode it is hidden. Should I change it or let it be?

File: public/locale/en.json (hunk 4 above)
Comment (Spandan-Mishra) [reply public/locale/en.json]: the welcome message will display for all kinds of users. doctors have a different format
the banner will be visible to only those with a doctor role.

Comment (rithviknishad) [reply public/locale/en.json]: there's plans to add prefix field for users to include this case. let's not render based on user_type. user_type is likely to be removed soon in favour of the new RBAC.

**Comment by Spandan-Mishra** [comment]
@Jacobjeevan made all the changes which were requested.
this is how it looks rn:


https://github.com/user-attachments/assets/bd4c1299-3c02-43e7-8ff0-736bae5b40a0

File: src/pages/UserDashboard.tsx [hunk 9]
```diff
@@ -12,151 +21,303 @@ import useAuthUser, { useAuthContext } from "@/hooks/useAuthUser";
...
+              imageUrl={user.read_profile_picture_url}
+              className="h-20 w-20 md:h-24 md:w-24 rounded-full"
+            />
+            <div className="space-y-1 text-center sm:text-left">
+              <div>
+                <p className="text-sm md:text-base text-gray-500">
+                  {t("welcome_back")}
+                </p>
+                <h1 className="text-xl md:text-2xl">
+                  {user.user_type === "doctor"
```
Comment (Jacobjeevan) [inline src/pages/UserDashboard.tsx:73]: Let's remove the banner for now, as Rithvik said, prefixes will be added soonish, we can add the banner then. Make sure to remove the key from en.json.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/UserDashboard.tsx (hunk 9 above)
Comment (Jacobjeevan) [reply src/pages/UserDashboard.tsx:73]: image

Adjust for smaller devices as well.

Comment (Spandan-Mishra) [reply src/pages/UserDashboard.tsx:73]: Custom breakpoint xs needs to be added to make flex-col for a screen of that size. Should I do it?

**Comment by Spandan-Mishra** [comment]
@Jacobjeevan I'll remove the banner. Should I keep the welcome_dr message or remove it and make it the same for all users?

PS: Please do let me know when you want to implement the banner 😅. I'd like to work on it

File: src/pages/UserDashboard.tsx (hunk 9 above)
Comment (Jacobjeevan) [reply src/pages/UserDashboard.tsx:73]: No, that's not the solution; you would need to adjust the entire page, it's not just the cards that are overflowing.

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan I'll remove the banner. Should I keep the welcome_dr message or remove it and make it the same for all users?
> 
> PS: Please do let me know when you want to implement the banner 😅. I'd like to work on it

Just remove the banner 👍

File: src/pages/UserDashboard.tsx (hunk 9 above)
Comment (Spandan-Mishra) [reply src/pages/UserDashboard.tsx:73]: Fixed this and removed the banner

File: src/pages/UserDashboard.tsx [hunk 10]
```diff
@@ -148,18 +148,13 @@ export default function UserDashboard() {
...
-          </div>
-        )}
       </div>
 
       {/* Tabs Section */}
       <div className="w-full">
         {/* Tabs Headings */}
         <div
-          className="flex border-b border-gray-200"
+          className="flex flex-wrap justify-center border-b border-gray-200"
```
Comment (Jacobjeevan) [inline src/pages/UserDashboard.tsx]: don't need justify-center here.

**Review by yash-learner — CHANGES_REQUESTED** [review]
**Expected design for mobile based on figma**

image



https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=10481-1260&t=fe2eOLdMvNGFjTlE-0



**current** 



image


----


image


**Tab names:** Add horizontal overflow scroll  and make text size as `text-sm` for mobiles.

File: src/pages/UserDashboard.tsx (hunk 10 above)
Comment (Spandan-Mishra) [reply src/pages/UserDashboard.tsx]: I'll look into it 👍🏻

**Comment by Spandan-Mishra** [comment]
@yash-learner I'll work on it.
Options like admin dashboard, edit profile etc., will still be in the kebab menu right? (figma file has a different design)

**Comment by Spandan-Mishra** [comment]
@Jacobjeevan @yash-learner made the changes.
For smaller screens, a swipe or arrow feature for tab names could be added, current one shows little overflow at the end (manageable)

**Review by Jacobjeevan — APPROVED** [review]

File: src/pages/UserDashboard.tsx [hunk 11]
```diff
@@ -19,144 +43,276 @@ export default function UserDashboard() {
...
+                              association.org_type,
+                              association.metadata,
+                            )}
+                        </p>
+                      </div>
+                      <ChevronRight className="h-4 w-4 md:h-5 md:w-5 text-gray-500" />
+                    </CardContent>
+                  </Card>
+                </Link>
+              ),
```
Comment (yash-learner) [inline src/pages/UserDashboard.tsx:243]: We can extract this into a separate component and reuse for all three tabs, structure is same, the only difference is data we are passing

Comment (Spandan-Mishra) [reply src/pages/UserDashboard.tsx:243]: fixed this @yash-learner

**Comment by Spandan-Mishra** [comment]
@Jacobjeevan one of the commits caused some kind of merge conflict, how to fixt it?

**Review by bodhish — APPROVED** [review]
LGTM
