### PR TITLE
Fix cursor pointer issue in Settings page - prevent pointer symbol on hover

### LINKED ISSUE #10748: Hand Cursor Appears on Non-Clickable Elements
**Describe the bug**
The hand cursor (pointer) appears when hovering. 

**To Reproduce**

1. Go to 'Settings'
2. Click on 'General'
3. See error cursor changes to a hand symbol

**Expected behavior**
The cursor should remain as the default arrow cursor when hovering over .

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by michael-020**
## Proposed Changes

- Fixes #10748
- Updated cursor style to default to make sure the cursor is not of type pointer while hovering on the avatar.

@ohcnetwork/care-fe-code-reviewers

Here's a video of the fix:

https://github.com/user-attachments/assets/7563eea9-e251-40c7-8ded-de92169ed830

## Summary by CodeRabbit

- **Refactor**
  - Revised the container structure for avatar display in the facility view to achieve improved layout consistency and smoother visual alignment.

- **Style**
  - Adjusted the avatar's dimensions for responsiveness while maintaining its overall appearance, ensuring a seamless and familiar user experience. All underlying behavior remains unchanged to deliver a more polished design, providing enhanced visual continuity across the interface.

- **Chores**
  - Removed a comment related to TypeScript ESLint rules in the `ResetHistoryContext` declaration, streamlining the code without affecting functionality.

### CODE REVIEW

**Comment by michael-020** [comment]
this property: `[&_svg]:size-4` is used to make sure the svg inside the avatar is of size-4

File: src/components/Facility/FacilityHome.tsx [hunk 1]
```diff
@@ -191,12 +191,12 @@ export const FacilityHome = ({ facilityId }: Props) => {
                 <div className="relative rounded-3xl  h-full w-full bg-[radial-gradient(circle_at_50%_120%,rgba(255,255,255,0.2),transparent)]" />
               )}
               <div className="absolute bottom-0 left-0 translate-x-0 translate-y-1/3">
-                <Button variant="link">
+                <div className="px-4 inline-flex rounded-md [&_svg]:size-4">
```
Comment (rithviknishad) [inline src/components/Facility/FacilityHome.tsx]: why?

```suggestion
                <div className="px-4 inline-flex rounded-md">
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]
let's also fix the mobile display. avatar seems to be taking lot of screen space in mobile.

**Comment by rithviknishad** [comment]
@michael-020 link issues to the PR as per:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue

How you've linked right now doesn't work;

File: src/components/Facility/FacilityHome.tsx (hunk 1 above)
Comment (rithviknishad) [reply src/components/Facility/FacilityHome.tsx]: > this property: `[&_svg]:size-4` is used to make sure the svg inside the avatar is of size-4

idea is to solve anything that feels wrong... even if it means it was wrong previously 😅 

the svg avatar looks so tiny with size-4; let's not have such classes, let Avatar take care of handling it's size as needed;

File: src/Providers/HistoryAPIProvider.tsx
Comment (michael-020) [inline src/Providers/HistoryAPIProvider.tsx:1]: This file was changed by eslint.

**Comment by michael-020** [comment]
@rithviknishad Please review the PR now. I removed the svg class, and added responsiveness to avatar for mobile displays.
I hope its alright now.

File: src/components/Facility/FacilityHome.tsx [hunk 2]
```diff
@@ -191,12 +191,12 @@ export const FacilityHome = ({ facilityId }: Props) => {
                 <div className="relative rounded-3xl  h-full w-full bg-[radial-gradient(circle_at_50%_120%,rgba(255,255,255,0.2),transparent)]" />
               )}
               <div className="absolute bottom-0 left-0 translate-x-0 translate-y-1/3">
-                <Button variant="link">
+                <div className="sm:px-4 px-8 inline-flex rounded-md">
                   <Avatar
                     name={facilityData.name}
-                    className="h-24 w-24 rounded-md border-4 border-white shadow-lg"
+                    className="h-16 w-16 sm:h-20 sm:w-20 md:h-24 md:w-24 rounded-md border-4 border-white shadow-lg"
```
Comment (rithviknishad) [inline src/components/Facility/FacilityHome.tsx]: use size-* class instead of manually specifying h and w for each breakpoint

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by michael-020** [comment]
This is how it looks for mobile displays:
Screenshot 2025-02-21 at 11 35 56 PM

File: src/components/Facility/FacilityHome.tsx (hunk 2 above)
Comment (michael-020) [reply src/components/Facility/FacilityHome.tsx]: done!

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by amjithtitus09 — APPROVED** [review]
