### PR TITLE
fix: Fixed print invoice layout and mobile view scaling

### LINKED ISSUE #14176: Bug: Tax invoice layout issues on detail view and print
Description:
The tax invoice layout on the detail page and the printed version has unnecessary scrolling and the data is not structured in the same order as displayed on screen. This causes misalignment and readability issues 

Image
Image

Image

Expected:
	•	No scrolling required while printing
	•	Data should appear in a clean, structured layout

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Ishu813**
## Proposed Changes

Fixes #14176
- Updated `PrintInvoice.tsx` to fix spacing and overflowing issues and misalignment.

**Screen Recording**

https://github.com/user-attachments/assets/92c0df2e-83b5-4fc1-8386-40d1a1e07f3c

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.
- [x] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Style**
  * Invoice header layout updated so invoice number stays left and date aligns right, adapting to narrow screens.
  * Customer details reworked into a clearer two-column layout separating name and age/sex from address with minimum-width rules.
  * Single-row blocks converted into wrapped, gap-aware layout to improve responsiveness and prevent overflow on small screens.
  * Increased vertical spacing and section separation for better readability.

### CODE REVIEW

File: src/CAREUI/misc/PrintPreview.tsx [hunk 1]
```diff
@@ -24,7 +24,7 @@ type Props = {
 };
 
 export default function PrintPreview(props: Props) {
-  const initialScale = useBreakpoints({ default: 0.44, md: 1 });
+  const initialScale = useBreakpoints({ default: 1 });
```
Comment (abhimanyurajeesh) [inline src/CAREUI/misc/PrintPreview.tsx]: lets bring this back as its used in other places

File: src/pages/Facility/billing/invoice/PrintInvoice.tsx [hunk 2]
```diff
@@ -132,39 +107,41 @@ export function PrintInvoice({ facilityId, invoiceId }: PrintInvoiceProps) {
...
-                      )
-                    : "-"
-                }
-              />
+        <CardContent className="px-2 py-4 border-b border-gray-200">
+          <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-4">
+            <div className="flex flex-col space-y-1 mb-2 sm:mb-0">
+              <h2 className="text-sm font-semibold text-gray-700">
+                {t("bill_to")}
+              </h2>
```
Comment (abhimanyurajeesh) [inline src/pages/Facility/billing/invoice/PrintInvoice.tsx]: the invoice details missing

**Review by abhimanyurajeesh — CHANGES_REQUESTED** [review]
Lets stick with the same layout as before, just fix what's breaking.

**Comment by Ishu813** [comment]
@abhimanyurajeesh,  have made some changes.....pls take a look.

File: src/pages/Facility/billing/invoice/PrintInvoice.tsx [hunk 3]
```diff
@@ -135,33 +135,47 @@ export function PrintInvoice({ facilityId, invoiceId }: PrintInvoiceProps) {
...
-                    ? format(
-                        new Date(invoice.issue_date),
-                        "dd MMM, yyyy h:mm a",
-                      )
-                    : "-"
-                }
-              />
+          <div className="space-y-6">
+            <div className="flex flex-wrap justify-between gap-2">
+              <div className="flex-1 min-w-[140px]">
```
Comment (Jacobjeevan) [inline src/pages/Facility/billing/invoice/PrintInvoice.tsx]: let's not specific px values, other options like container scales or fraction

https://tailwindcss.com/docs/width

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Facility/billing/invoice/PrintInvoice.tsx [hunk 4]
```diff
@@ -135,33 +135,47 @@ export function PrintInvoice({ facilityId, invoiceId }: PrintInvoiceProps) {
...
+                    label={`${t("age")} / ${t("sex")}`}
+                    value={
+                      patient
+                        ? `${formatPatientAge(patient, true)}, ${t(`GENDER__${patient.gender}`)}`
+                        : undefined
+                    }
+                  />
+                </div>
+              </div>
+              <div className="flex-1 min-w-[140px] break-words whitespace-pre-wrap overflow-hidden">
```
Comment (AdityaJ2305) [inline src/pages/Facility/billing/invoice/PrintInvoice.tsx]: can we use relative min-w ?

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]
other places as well

**Comment by nihal467** [comment]
image

@Ishu813 the right side of the row where address are present is creating empty space, where the current develop looks fine, can you look into it

**Comment by nihal467** [comment]
LGTM

**Review by bodhish — APPROVED** [review]
LGTM
