### PR TITLE
Fix: Make Update Location Dialog Fully Responsive on Mobile Devices

### LINKED ISSUE #11709: Update Location Dialog Not Fully Responsive on Mobile Devices
**Describe the bug**
The "Update Location" dialog is not fully responsive on mobile devices, causing layout issues.

**To Reproduce**

1. Go to 'Encounters then click any encounter'
2. Click on 'Add location button'
3. See error

**Expected behavior**
The "Update Location" dialog should adapt properly to mobile screens without layout issues.

**Screenshots**

Image

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [135.0.6834.111]

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes

- updated the responsiveness by tailwindcss

- Fixes #11709 
- Change 1
- Change 2
- More?

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
	- Enhanced responsive layouts for location interfaces, allowing elements to wrap and display optimally across device sizes.
	- Improved button sizing and alignment, ensuring consistent spacing and full-width behavior on smaller screens.
	- Adjusted content alignment for better responsiveness on various screen sizes.
	- Increased height and added padding to the scroll area for improved visual presentation.
	- Refined overall spacing and presentation for a polished user experience.

### CODE REVIEW

**Comment by modamaan** [comment]
https://github.com/user-attachments/assets/e2f279d8-8ab8-4a6f-941f-58a85f63f914

File: src/components/Location/BedStatusLegend.tsx [hunk 1]
```diff
@@ -27,7 +27,7 @@ export function BedStatusLegend({ className }: BedStatusLegendProps) {
   ];
 
   return (
-    <div className={`flex items-center gap-4 ${className}`}>
+    <div className={`flex flex-wrap items-center gap-4 ${className}`}>
```
Comment (rithviknishad) [inline src/components/Location/BedStatusLegend.tsx]: use `cn` utility fn

File: src/components/Location/LocationActionButtons.tsx [hunk 2]
```diff
@@ -77,21 +77,27 @@ export function LocationActionButtons({
...
-        </Button>
-      ))}
+    <div className="flex flex-wrap gap-2 items-center">
+      <div className="flex flex-wrap gap-2 flex-1">
+        {buttons.map((button, index) => (
+          <Button
+            key={index}
+            variant={button.variant}
+            onClick={button.onClick}
+            className={`sm:w-auto w-full ${button.className}`}
```
Comment (rithviknishad) [inline src/components/Location/LocationActionButtons.tsx]: use `cn` utility fn pls!

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
Almost there, scrollbar still overlaps the beds on mobile (not just the beds). You will probably have to adjust padding/margin for the parent component in the sheet.

image

**Comment by modamaan** [comment]
image

image

**Comment by nihal467** [comment]
image

- the buttons in the location management page is clipping in the safari browser

**Comment by modamaan** [comment]
Screenshot 2025-04-11 204242

**Comment by modamaan** [comment]
Screenshot 2025-04-11 204002

https://github.com/user-attachments/assets/bee037a9-bcaa-48a6-86f0-156ef7cf6169

**Comment by modamaan** [comment]
@nihal467 @rithviknishad

**Comment by modamaan** [comment]
Screenshot_20250411_205653_Chrome

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
