### PR TITLE
Disable Unnecessary Browser Pop-up on Patient Registration Form

### LINKED ISSUE #10246: Disable Unnecessary Browser Pop-up on Patient Registration Form in Public Portal Post Phone Number Login
**Describe the bug**

After logging in with a phone number and creating a new patient on the public page, an unnecessary browser warning is displayed. This warning should only appear if the user attempts to leave the form without completing it.

**To Reproduce**

1. Go to the /login page
2. Enter a valid phone number; the static OTP is 45612
3. Select any random facility with a hospital (Ernakulam District, MNHS facility)
4. Book an appointment for a user
5. Create a new patient
6. Observe the error

**Expected behavior**

The browser pop-up should only appear if the user tries to navigate away after partially filling out the form.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #10246 
- Change 1
- Change 2
- More?

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced patient registration form with submission state management.
	- Added protection against unintended navigation during appointment creation.

- **Bug Fixes**
	- Improved form submission handling to prevent multiple submissions.
	- Added state tracking to manage form submission process more reliably.

### CODE REVIEW

File: src/pages/PublicAppointments/PatientRegistration.tsx [hunk 1]
```diff
@@ -208,13 +211,14 @@ export function PatientRegistration(props: PatientRegistrationProps) {
...
     };
+    setIsSubmitting(true);
     createPatient(formattedData);
   });
 
   // TODO: Use useBlocker hook after switching to tanstack router
   // https://tanstack.com/router/latest/docs/framework/react/guide/navigation-blocking#how-do-i-use-navigation-blocking
   useNavigationPrompt(
-    form.formState.isDirty && !isCreatingPatient,
+    form.formState.isDirty && !isCreatingPatient && !isSubmitting,
```
Comment (Jacobjeevan) [inline src/pages/PublicAppointments/PatientRegistration.tsx]: Swap out isCreatingPatient with isCreatingAppointment; removes the need for an extra state 👍

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
