### PR TITLE
fix(medication): add indication for inactive medication requests

### LINKED ISSUE #11304: No Clear Indication for Removed Medication In Edit form
**Describe the bug**
Even though the medication has been removed, it still appears as if it hasn’t been removed.

**To Reproduce**

1. Go to 'Medication Request' 
2. Click add a Medication and edit. 
3. See issue

**Expected behavior**
The removed medication should either be displayed with a strikethrough or in a different color to indicate its removal. Additionally, the Edit and Remove buttons should be hidden.

**Screenshots**
https://github.com/user-attachments/assets/a9227679-0f14-42aa-b1ef-f3fdb9ca15fa

**Smartphone (please complete the following information):**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by siva222003**
## Proposed Changes

- Fixes #11304 
- Added a clear indication for inactive medication requests.
- Replaced direct status checks with a reusable isInactive variable for better consistency.

[Screencast from 2025-03-15 22-48-38.webm](https://github.com/user-attachments/assets/e758b77d-f58e-4d56-8c65-0a8c0da85cd2)

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
	- Inactive medications now feature reduced opacity, strike-through text, and updated background colors for clear visual distinction.
- **New Features**
	- Actions such as removal are now disabled for inactive medications, ensuring a consistent and intuitive user experience.
	- Introduced a new constant to determine inactive medication statuses, enhancing visual representation and interaction logic.

### CODE REVIEW

**Comment by siva222003** [comment]
Hey @rithviknishad @Jacobjeevan, 

Please review this and let me know if any changes are required.  

- In the `EncounterQuestionnaire` page, should we display the active medications at the top and then show the inactive ones like we are showing in the other pages, or should we leave it as it is?  
- When I try to navigate to the `EncounterQuestionnaire` page from the organization view, it's showing a 404 not found error since this page is currently set up only for the Facility View, similar to the Treatment Summary Page. Should I add this page to the Organization View, or should we hardcode the facility view URL like the Treatment Summary Page?  

Please let me know your thoughts on the above two questions.

**Review by abhimanyurajeesh — CHANGES_REQUESTED** [review]
Do we really need these many changes !? Please look into it.

Also please follow the merge check list.

**Comment by siva222003** [comment]
Hey @abhimanyurajeesh, I just added 4-5 lines in `MedicationRequestQuestion.tsx` page, but I think the changes are due to some formatting.

File: src/components/Medicine/MedicationsTable.tsx [hunk 1]
```diff
@@ -77,9 +77,11 @@ export const MedicationsTable = ({ medications }: MedicationsTableProps) => {
             return (
               <TableRow
                 key={medication.id}
-                className={`divide-x font-medium ${isInactive ? "bg-gray-100" : ""}`}
+                className={`divide-x font-medium ${isInactive ? "bg-gray-200 opacity-40" : ""}`}
```
Comment (abhimanyurajeesh) [inline src/components/Medicine/MedicationsTable.tsx]:
```suggestion
                className={`divide-x font-medium ${isInactive ? "bg-gray-200 opacity-40 line-through" : ""}`}
```

File: src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx [hunk 2]
```diff
@@ -612,14 +620,15 @@ const MedicationRequestGridRow: React.FC<MedicationRequestGridRowProps> = ({
       className={cn(
         "grid grid-cols-1 lg:grid-cols-[280px,180px,170px,160px,300px,180px,250px,180px,160px,200px,180px,48px] border-b hover:bg-gray-50/50",
         {
-          "opacity-40 pointer-events-none":
-            medication.status === "entered_in_error",
+          "opacity-40 pointer-events-none": disabled,
```
Comment (abhimanyurajeesh) [inline src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx:632]: any reason for removing this !?

Comment (abhimanyurajeesh) [reply src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx:632]: correct me if I'm wrong, shouldn't this be inactive?? 

cc: @rithviknishad

**Review by abhimanyurajeesh — COMMENTED** [review]
- [ ] Can we sort by INACTIVE_MEDICATION_STATUSES?



- [ ] And is hover required for removed medication !?

File: src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx (hunk 2 above)
Comment (siva222003) [reply src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx:632]: disabled has that inactice status included with it, I haven't removed anything.

Comment (siva222003) [reply src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx:632]: I haven't added hover effects to the removed requests.
I've also suggested sorting by inactive statuses. Should I add that, @abhimanyurajeesh, or wait for confirmation?

**Review by Jacobjeevan — APPROVED** [review]

**Comment by abhimanyurajeesh** [comment]
Code changes looks fine,but can you please follow the merge checklist.
image

Also cant see the deploy preview to test the changes.

**Comment by nihal467** [comment]
image

- Show a strikethrough only for medicines marked as "Removed" on the Edit Medication page, but do not apply a strikethrough for medicines marked as "Discontinued" in the Medication Administration section.

**Comment by siva222003** [comment]
> image
> 
> * Show a strikethrough only for medicines marked as "Removed" on the Edit Medication page, but do not apply a strikethrough for medicines marked as "Discontinued" in the Medication Administration section.


Hey @nihal467, on the Edit Medication page, I'm showing a strike-through for all inactive medications, including those that are ended, completed, canceled, and removed. Do you want me to apply the strike-through only to removed medications and only in the Edit Medication list? 

Currently, I'm also showing a strike-through in the Medicines tab and the Medicine Administration tab for all inactive medicines.

**Comment by nihal467** [comment]
you can show strike-through for all statuses except ended medicine

**Comment by siva222003** [comment]
@nihal467 I have made the chages, please review it.

[Screencast from 2025-03-24 14-24-06.webm](https://github.com/user-attachments/assets/36888eab-7a0c-45bf-aa9a-8a88ce324955)

File: src/components/Medicine/MedicationAdministration/AdministrationTab.tsx [hunk 3]
```diff
@@ -215,8 +215,12 @@ const MedicationRow: React.FC<MedicationRowProps> = ({
 
   return (
     <React.Fragment>
-      <div className={`p-4 border-t ${isInactive ? "bg-gray-100" : ""}`}>
-        <div className="font-semibold truncate">
+      <div
+        className={`p-4 border-t ${isInactive ? "bg-gray-100 opacity-80" : ""}`}
```
Comment (khavinshankar) [inline src/components/Medicine/MedicationAdministration/AdministrationTab.tsx]: use cn util instead of string interpolation, the cn util makes it easy to read

File: src/components/Medicine/MedicationAdministration/AdministrationTab.tsx [hunk 4]
```diff
@@ -215,8 +215,12 @@ const MedicationRow: React.FC<MedicationRowProps> = ({
...
+      >
+        <div
+          className={`font-semibold truncate ${isInactive ? "line-through" : ""}`}
```
Comment (khavinshankar) [inline src/components/Medicine/MedicationAdministration/AdministrationTab.tsx]: use cn util

File: src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx [hunk 5]
```diff
@@ -355,103 +356,113 @@ export function MedicationRequestQuestion({
...
-                              ? "bg-gray-50"
-                              : "bg-gray-100",
-                          )}
+                {medications.map((medication, index) => {
+                  const isInactive = INACTIVE_MEDICATION_STATUSES.includes(
+                    medication.status as (typeof INACTIVE_MEDICATION_STATUSES)[number],
+                  );
+
+                  return (
+                    <React.Fragment key={index}>
```
Comment (khavinshankar) [inline src/components/Questionnaire/QuestionTypes/MedicationRequestQuestion.tsx]: prefer using ids for keys over indexes, indexes tends to change when the array changes, here, use medication.id as key

**Review by khavinshankar — CHANGES_REQUESTED** [review]

**Review by khavinshankar — CHANGES_REQUESTED** [review]
minor change

**Comment by siva222003** [comment]
hey @khavinshankar , I have used cn everywhere please check the latest code.

**Review by khavinshankar — APPROVED** [review]

**Comment by siva222003** [comment]
@nihal467 Could you test this PR, and let me know if any changes are required.

**Comment by nihal467** [comment]
LGTM

File: src/components/Medicine/MedicationAdministration/AdministrationTab.tsx [hunk 6]
```diff
@@ -218,11 +220,17 @@ const MedicationRow: React.FC<MedicationRowProps> = ({
   );
 
   return (
-    <React.Fragment>
+    <React.Fragment key={medication.id}>
       <div
-        className={`p-4 border-t border-gray-200 ${isInactive ? "bg-gray-100" : ""}`}
+        className={cn("p-4 border-t border-gray-200", {
+          "opacity-40 bg-gray-200": isInactive,
```
Comment (khavinshankar) [inline src/components/Medicine/MedicationAdministration/AdministrationTab.tsx]:
```suggestion
          isInactive && "opacity-40 bg-gray-200",
```

This technically works, but rewrite it so it is more readable

**Review by khavinshankar — DISMISSED** [review]

**Comment by siva222003** [comment]
@khavinshankar Could you please review the new changes?

**Comment by rithviknishad** [comment]
@siva222003 refrain from force pushing after the PR has been reviewed or tested once. Hard to track what's changed.

File: src/components/Medicine/MedicationAdministration/AdministrationTab.tsx [hunk 7]
```diff
@@ -218,11 +220,19 @@ const MedicationRow: React.FC<MedicationRowProps> = ({
   );
 
   return (
-    <React.Fragment>
+    <React.Fragment key={medication.id}>
```
Comment (rithviknishad) [inline src/components/Medicine/MedicationAdministration/AdministrationTab.tsx]: does this solve anything? 🤔 

```suggestion
    <React.Fragment>
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by siva222003** [comment]
@rithviknishad I missed the key attribute earlier, but I've removed it now! Please review.

**Review by rithviknishad — APPROVED** [review]
