### PR TITLE
Fix Notification Subscription Loading and Messaging Errors

### LINKED ISSUE #9021: Notification Subscription Error Handling and Unsubscribe Message Mismatch
**Describe the bug**
In the notification section, when the Subscribe button is clicked, the site requests user permission. If the user closes the permission prompt by clicking 'X', an error message stating "permission denied" should be displayed. Currently, instead of showing this error, the subscribe button continues to load indefinitely, even after the API rejection response is received. Additionally, when the Unsubscribe button is clicked, the notification message displayed is not relevant to the action.

**To Reproduce**

1. Go to 'Notifications'
2. Click on 'Subscribe'
3. Close the permission prompt by clicking the 'X' button.
4. Observe that the error message "permission denied" is not displayed; instead, the subscribe button continues to load.
5. Click on Unsubscribe and notice that the notification message displayed is not relevant.

**Expected behavior**
1. When the permission prompt is closed by the user, an error message saying "permission denied" should be shown.
2. The Subscribe button should stop loading once the API rejection response is received.
3. When Unsubscribe is clicked, an appropriate and relevant notification message should be displayed.

**Screenshots**

Subscribe issue
Image

Image

Irrelevant Notification Message on clicking unsubscribe:
Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Mahendar0701**
## Proposed Changes

- Fixes #9021 
- Change 1: Resolved the infinite loading state on the Subscribe button when the notification permission prompt is closed by clicking 'X'.
- Change 2: Updated messages for subscribing and unsubscribing actions to display relevant and accurate information.

Before :
Subscribe issue
Image

Image

Irrelevant Notification Message on clicking unsubscribe:
Image

After:
image

image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Added clear notification messages for subscription actions, including success and failure confirmations.
  
- **Bug Fixes**
	- Improved error handling for notification subscriptions, providing immediate feedback if permission is denied or if the subscription fails.

- **User Experience Enhancements**
	- Streamlined user feedback during notification management, ensuring users are informed of their subscription status effectively.

### CODE REVIEW

File: src/components/Notifications/NotificationsList.tsx [hunk 1]
```diff
@@ -342,43 +329,73 @@ export default function NotificationsList({
...
-      setIsSubscribed("SubscribedOnThisDevice");
+      if (permission === "denied") {
+        Warn({
+          msg: t("notification_permission_denied"),
+        });
+        setIsSubscribing(false);
+        return;
+      } else if (permission === "default") {
+        Warn({
+          msg: t("notification_cancelled"),
```
Comment (shivankacker) [inline src/components/Notifications/NotificationsList.tsx]: Let this give the permission denied error only.

**Review by shivankacker — CHANGES_REQUESTED** [review]

File: src/components/Notifications/NotificationsList.tsx (hunk 1 above)
Comment (Mahendar0701) [reply src/components/Notifications/NotificationsList.tsx]: Ok

**Review by shivankacker — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
