### PR TITLE
Fix: Dropdown Hover Highlights Multiple Items with Same Display Name

### LINKED ISSUE #12740: Dropdown Hover Highlights Multiple Items with Same Display Name
**Describe the bug**
When hovering over one item in the dropdown (Select Practitioner), both duplicate entries (with the same display name Aditya Jindal) are getting hovered/highlighted at the same time. This causes confusion and incorrect UI behavior.

**To Reproduce**
Go to the Select Practitioner dropdown.
Hover over either of the duplicate Aditya Jindal entries.
Observe that both entries get the hover highlight.

**Expected behavior**
Only the item being hovered on should be visually highlighted. Each dropdown entry should act independently, regardless of duplicate names or avatars.

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date:1day after assignment

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Akhileswaran-K-R**
## Proposed Changes

- Fixes #12740 
- Changed the value in CommandItem to user.id

Screenshot (51)

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **Refactor**
  * Improved practitioner selection to better handle users with identical names, ensuring more reliable selection without changing the visible interface.

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
the search is broken

**Comment by Jacobjeevan** [comment]
> the search is broken

Fixed 👍

**Comment by nihal467** [comment]
LGTM

File: src/pages/Appointments/components/PractitionerSelector.tsx [hunk 1]
```diff
@@ -104,10 +104,10 @@ export const PractitionerSelector = ({
                   </div>
                 </CommandItem>
               )}
-              {practitioners?.users.map((user) => (
+              {practitioners?.users.map((user, index) => (
                 <CommandItem
                   key={user.id}
-                  value={formatName(user)}
+                  value={formatName(user) + " - " + index}
```
Comment (rithviknishad) [inline src/pages/Appointments/components/PractitionerSelector.tsx:110]: lets pass the user's id instead? 🤔

Comment (rithviknishad) [inline src/pages/Appointments/components/PractitionerSelector.tsx]: not a huge fan of passing index to the value.

the value prop passed is whats used for searching items by the command component.

so if user types a number, it'd also include in the filtered results right? which is not expected.

Comment (khavinshankar) [reply src/pages/Appointments/components/PractitionerSelector.tsx]: ➕

**Review by khavinshankar — DISMISSED** [review]

File: src/pages/Appointments/components/PractitionerSelector.tsx (hunk 1 above)
Comment (Akhileswaran-K-R) [reply src/pages/Appointments/components/PractitionerSelector.tsx]: > not a huge fan of passing index to the value.
> 
> the value prop passed is whats used for searching items by the command component.
> 
> so if user types a number, it'd also include in the filtered results right? which is not expected.

When I gave value as user.id, the search was working, so can I proceed with that

https://github.com/user-attachments/assets/a9cff461-b258-49fd-92a6-9d937c453875

Comment (AdityaJ2305) [reply src/pages/Appointments/components/PractitionerSelector.tsx]: Can we do this 
value={`${formatName(user)} ${user.username ?? ""}`}

if approved , please do it for multipractitioner

Comment (AdityaJ2305) [reply src/pages/Appointments/components/PractitionerSelector.tsx]: > When I gave value as user.id, the search was working, so can I proceed with that

are u sure ??

Comment (Akhileswaran-K-R) [reply src/pages/Appointments/components/PractitionerSelector.tsx]: > > When I gave value as user.id, the search was working, so can I proceed with that
> 
> are u sure ?? 

Yes, I have attached the video

Comment (AdityaJ2305) [reply src/pages/Appointments/components/PractitionerSelector.tsx]: You made the change in PractitionerSelector and testing on MultiPractitionerSelector 😅

Comment (rithviknishad) [reply src/pages/Appointments/components/PractitionerSelector.tsx]: @AdityaJ2305 's suggestion is nice. Any updates on this?

Comment (Akhileswaran-K-R) [reply src/pages/Appointments/components/PractitionerSelector.tsx]: > @AdityaJ2305 's suggestion is nice. Any updates on this?

updated

**Review by Jacobjeevan — APPROVED** [review]

File: src/pages/Appointments/components/PractitionerSelector.tsx [hunk 2]
```diff
@@ -107,7 +107,7 @@ export const PractitionerSelector = ({
               {practitioners?.users.map((user) => (
                 <CommandItem
                   key={user.id}
-                  value={formatName(user)}
+                  value={`${formatName(user)} ${user.username ?? ""}`}
```
Comment (AdityaJ2305) [inline src/pages/Appointments/components/PractitionerSelector.tsx]:
```suggestion
                  value={`${formatName(user)} ${user.username}`}
```

File: src/pages/Appointments/components/MultiPractitionerSelect.tsx [hunk 3]
```diff
@@ -64,7 +64,7 @@ export const MultiPractitionerSelector = ({
   );
 
   const getItemValue = (user: UserBase) => {
-    return formatName(user) + " " + user.id;
+    return formatName(user) + " " + (user.username ?? "");
```
Comment (AdityaJ2305) [inline src/pages/Appointments/components/MultiPractitionerSelect.tsx]: We can directly use ``` value={`${formatName(user)} ${user.username}`} ```

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

File: src/pages/Appointments/components/MultiPractitionerSelect.tsx (hunk 3 above)
Comment (Jacobjeevan) [reply src/pages/Appointments/components/MultiPractitionerSelect.tsx]: @Akhileswaran-K-R We don't need to change anything for multi practitioner, works as is. Go ahead and make the change for Practitioner select and discard changes in multi.

Comment (AdityaJ2305) [reply src/pages/Appointments/components/MultiPractitionerSelect.tsx]: @Jacobjeevan , this would cause this issue reported by rithvik originally since id includes number

 > so if user types a number, it'd also include in the filtered results right? which is not expected.
 
 

https://github.com/user-attachments/assets/98c3e00b-3c0f-4678-a40c-7b1335c53fdd

Comment (Akhileswaran-K-R) [reply src/pages/Appointments/components/MultiPractitionerSelect.tsx]: > We can directly use `` value={`${formatName(user)} ${user.username}`} ``

The method is used for selected and non-selected practitioners

**Review by Jacobjeevan — APPROVED** [review]

File: src/pages/Appointments/components/MultiPractitionerSelect.tsx [hunk 4]
```diff
@@ -66,7 +66,7 @@ export const MultiPractitionerSelector = ({
   );
 
   const getItemValue = (user: UserBase) => {
-    return formatName(user) + " " + user.id;
+    return formatName(user) + " " + user.username;
```
Comment (AdityaJ2305) [inline src/pages/Appointments/components/MultiPractitionerSelect.tsx]:
```suggestion
    return `${formatName(user)} ${user.username}`;
```

pointing out the same again 😅

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
