### PR TITLE
Fix : Avatar Camera Capture Shows Old Crop on Second Attempt

### LINKED ISSUE #12941: Avatar Camera Capture Shows Old Crop on Second Attempt
**Describe the bug**
After taking camera capture and uploading, opening the camera again and taking another photo shows the old cropped picture instead of the newly captured photo.

**To Reproduce**

1. Go to 'Profile.'
2. Click Change Avatar ➜ Open Camera.
3. Capture a photo, crop it, and upload it.
4. Again click Change Avatar ➜ Open Camera.
5. Capture another photo, see error captured photo is not showing in the preview to crop.
It shows the old cropped preview.

https://github.com/user-attachments/assets/ba9ed107-2522-4e06-a5a1-e7f648c21f2a

**Expected behavior**
After each capture, It should open the cropper with the newly-captured image.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #12941

- Resetting the crop and preview states right after capturing a new image from the camera.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

https://github.com/user-attachments/assets/0b3edce7-c8ac-431d-93f5-208fb1743cfa

- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **Bug Fixes**
  * Resolved an issue where previous cropping settings were retained after capturing a new image from the webcam. Now, cropping options are reset for each new capture, ensuring a smoother editing experience.
  * Improved modal behavior to better reset states when closing or canceling, providing a more consistent and reliable avatar editing experience.

### CODE REVIEW

File: src/components/ui/phone-input.tsx
Comment (AdityaJ2305) [inline src/components/ui/phone-input.tsx:1]: ?

Comment (Jeffrin2005) [reply src/components/ui/phone-input.tsx:1]: I accidently pushed this.
Now updated with the new file.( will take some time to show File changed as 1)

Comment (AdityaJ2305) [reply src/components/ui/phone-input.tsx:1]: will take some time to show File changed  
 
 why ? 
 yeah, change is not showing up , changes in ui/phone-input.tsx is still there

Comment (Jeffrin2005) [reply src/components/ui/phone-input.tsx:1]: @AdityaJ2305 Now ,  it is single file 👍

**Review by Jacobjeevan — DISMISSED** [review]
Check what happens if user clicks outside of the dialog (closing it) after cropping and not uploading.

We need to retain the image so they can continue cropping (only clear if they click cancel).

**Comment by Jeffrin2005** [comment]
@Jacobjeevan I have a doubt, currently Now in the current commit if we are capturing the image and closing dialog ,it will show the preview of capture image with cropping area, (only clicking the cancel button will reset - like will not show the preview) similarly after clicking the crop button , if we are clicking outside it will show the preview of cropped image.

Do we need to show the preview only after clicking the cropping button or do we need to show the capture image, if we are closing outside the dialog  ? 

https://github.com/user-attachments/assets/338d3b12-d4e3-49b1-9a62-4c1516800b53

**Comment by Jacobjeevan** [comment]
> Do we need to show the preview only after clicking the cropping button or do we need to show the capture image, if we are closing outside the dialog ?

Video preview looks correct 👍

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

**Comment by nihal467** [comment]
LGTM

File: src/components/Common/AvatarEditModal.tsx [hunk 1]
```diff
@@ -67,18 +67,20 @@ export default function AvatarEditModal({
...
+      setIsProcessing(false);
+      setIsDeleting(false);
+      setSelectedFile(undefined);
+      setIsCameraOpen(false);
+      setCroppedAreaPixels(null);
+      setCroppedPreview(null);
+      setShowCroppedPreview(false);
+      setShowCameraPreview(false);
+      setCrop({ x: 0, y: 0 });
+      setZoom(1);
```
Comment (rithviknishad) [inline src/components/Common/AvatarEditModal.tsx]: code doesn't seem readable this way... somethings off...

why not move this to a difference function called `resetState` and call it instead of passing an arg? 🤔 

closeModal should be responsible only on closing the modal right? 🤔

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
