### PR TITLE
Fix: Correct query key invalidation for organization mutations

### LINKED ISSUE #16236: Responsibility description not updating after edit - requires manual refresh
## Description

When editing a responsibility's description in the Organization admin panel, clicking **Update Responsibility** saves the change successfully, but the updated description is not reflected on the page. The user has to manually refresh the browser to see the new value.

## Steps to Reproduce

1. Go to **Admin → Organizations → Responsibilities**
2. Select a responsibility (e.g., "QA Lead")
3. Click to edit the responsibility
4. Change the description field
5. Click **Update Responsibility**
6. Observe that the description shown on the left panel and the detail view still shows the old value

## Expected Behavior

After clicking **Update Responsibility**, the description should immediately update on the page without requiring a manual browser refresh.

## Actual Behavior

The old description persists on the page until the user manually refreshes.

## Root Cause (Likely)

The mutation that updates the responsibility is not invalidating the relevant TanStack Query cache, so stale data continues to display. The onSuccess callback of the mutation likely needs to invalidate or refetch the responsibilities query.

## Environment

- URL: care.ohc.network
- Page: `/admin/organizations/role/{id}`

Image

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #16236

https://github.com/user-attachments/assets/8233fe9b-0f2b-44bb-a1b2-10febe3d325b

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Refactor**
  * Updated organization data refresh behavior after create and update operations to ensure consistent cache updates.

### CODE REVIEW

File: src/pages/Admin/organizations/components/AdminOrganizationFormSheet.tsx [hunk 1]
```diff
@@ -97,7 +97,7 @@ export default function AdminOrganizationFormSheet({
       })(body),
     onSuccess: () => {
       queryClient.invalidateQueries({
-        queryKey: ["organization", "list", organizationType, parentId],
+        queryKey: ["organization"],
```
Comment (Jacobjeevan) [inline src/pages/Admin/organizations/components/AdminOrganizationFormSheet.tsx:100]:
```suggestion
        queryKey: ["organization", organizationType],
```

File: src/pages/Admin/organizations/components/AdminOrganizationFormSheet.tsx [hunk 2]
```diff
@@ -113,10 +113,7 @@ export default function AdminOrganizationFormSheet({
       })(body),
     onSuccess: () => {
       queryClient.invalidateQueries({
-        queryKey: ["organization", "list", organizationType, parentId],
-      });
-      queryClient.invalidateQueries({
-        queryKey: ["organization", org?.id],
+        queryKey: ["organization"],
```
Comment (Jacobjeevan) [inline src/pages/Admin/organizations/components/AdminOrganizationFormSheet.tsx:116]:
```suggestion
        queryKey: ["organization", organizationType, organizationId],
```

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
We can make the query keys specific; do test w/ the diff types though.

**Review by bodhish — APPROVED** [review]
