### PR TITLE
Enhance Comment Section UI with Redesigned User Icon and Styling

### LINKED ISSUE #10428: Redesign Comment Section User Icon and Style for Improved UI
**Describe the bug**
The current comment section user icon and layout do not align with the desired design expectations

**To Reproduce**

[Click here to reproduce](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/resource/b3c703ec-3c96-4591-959e-d7e4a0900f81)

 See error

**Expected behavior**
The comment section should display user icons and styles with a modern, visually appealing design

**Screenshots**

Image

Expecting

similar to

Image

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [132.0.6834.111]

**Additional context**

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes

- Fixes #10428 
- Change 1

- Old
Screenshot 2025-02-05 222927

updated
Screenshot 2025-02-08 002808

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Added tooltips on avatars to show the creator’s name on hover.
  - Enabled Markdown formatting for comment text.
  - Updated comment ordering to display the most recent first.

- **Style**
  - Enhanced layout with improved alignment for a cleaner structure.
  - Updated date presentation for better accessibility and semantic clarity.
  - Refined overall styling of the comment section for a polished look.

### CODE REVIEW

**Review by modamaan — COMMENTED** [review]
self reviewed
comment order updated, latest comment should be first

File: src/components/Resource/ResourceCommentSection.tsx [hunk 1]
```diff
@@ -130,23 +139,43 @@ export const Comment = ({
...
+        </Tooltip>
+      </TooltipProvider>
+
+      <div className="flex flex-col items-start flex-grow">
+        <p className="text-xs space-x-2 mb-1">
+          <span className="text-gray-700 font-medium">
+            {formatName(created_by)}
+          </span>
+        </p>
+        <div>{comment.replace(/\n+/g, "\n")}</div>
```
Comment (rithviknishad) [inline src/components/Resource/ResourceCommentSection.tsx]: let's use markdown renderer for the comment? 🤔

Comment (modamaan) [reply src/components/Resource/ResourceCommentSection.tsx]: markdown added

**Comment by modamaan** [comment]
@rithviknishad should I push package.json and lock file

**Comment by rithviknishad** [comment]
we don't need any new packages. we already have a markdown component

**Comment by rithviknishad** [comment]
https://github.com/ohcnetwork/care_fe/blob/develop/src/components/ui/markdown.tsx

**Comment by modamaan** [comment]
@rithviknishad i removed the package.json and lock.json file, now it shows cypress issue. can you help me resolve it?

**Comment by Jacobjeevan** [comment]
image

Not the right way to remove a file from commit.

**Comment by modamaan** [comment]
@Jacobjeevan  can you please reopen it

File: src/components/Resource/ResourceCommentSection.tsx [hunk 2]
```diff
@@ -130,23 +140,45 @@ export const Comment = ({
...
-    <div className="flex w-full items-center">
-      <div className="mr-auto flex items-center rounded-md border bg-secondary-100 py-1 pl-2 pr-3">
-        <Avatar
-          name={`${created_by.first_name} ${created_by.last_name}`}
-          className="h-8 w-8 "
-        />
-        <span className="pl-2 text-sm text-secondary-700">
-          {formatName(created_by)}
-        </span>
+  <div
```
Comment (Jacobjeevan) [inline src/components/Resource/ResourceCommentSection.tsx:137]: image

I'd suggest having the avatar, username and time as one row in the flexbox and the content as the 2nd row.

Maybe also reduce the size of the time 🤔  well, experiment and see what works.

File: src/components/Resource/ResourceCommentSection.tsx [hunk 3]
```diff
@@ -130,23 +140,45 @@ export const Comment = ({
...
+    className={cn(
+      "mt-4 flex w-full flex-col rounded-lg border border-secondary-300 bg-white p-4 text-secondary-800",
+    )}
+  >
+    <div className="flex items-start gap-3">
+      <TooltipProvider>
```
Comment (Jacobjeevan) [inline src/components/Resource/ResourceCommentSection.tsx]: Let's switch to using TooltipComponent; it handles importing the provider/trigger etc.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Resource/ResourceCommentSection.tsx (hunk 3 above)
Comment (modamaan) [reply src/components/Resource/ResourceCommentSection.tsx]: updated

File: src/components/Resource/ResourceCommentSection.tsx (hunk 2 above)
Comment (modamaan) [reply src/components/Resource/ResourceCommentSection.tsx:137]: added

**Comment by modamaan** [comment]
Screenshot 2025-02-12 002853

**Review by Jacobjeevan — APPROVED** [review]

File: src/components/Resource/ResourceCommentSection.tsx [hunk 4]
```diff
@@ -91,11 +93,14 @@ const CommentSection = (props: { id: string }) => {
                 </div>
               ) : (
                 <ul>
-                  {resourceComments?.results?.map((comment) => (
-                    <li key={comment.id} className="w-full">
-                      <Comment {...comment} />
-                    </li>
-                  ))}
+                  {resourceComments?.results
+                    ?.slice()
```
Comment (rithviknishad) [inline src/components/Resource/ResourceCommentSection.tsx]: why are we doing `.slice` here?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Resource/ResourceCommentSection.tsx (hunk 4 above)
Comment (modamaan) [reply src/components/Resource/ResourceCommentSection.tsx]: https://github.com/user-attachments/assets/47bb8a0f-cd31-4ed1-8b60-ff1944f8b0c5

Comment (modamaan) [reply src/components/Resource/ResourceCommentSection.tsx]: How .slice() Fixes This?
slice() creates a new copy of the array, keeping the original order intact.
reverse() then acts on this new copy, preventing unintended mutations.

Comment (rithviknishad) [reply src/components/Resource/ResourceCommentSection.tsx]: use spread `[...array]` to create copy instead

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
