### PR TITLE
Fixed update button in bed management.

### LINKED ISSUE #6837: Need to click on update button twice when updating bed in Bed Management.
**Describe the bug**
When you create a bed in and edit it the update button needs to be clicked twice.

**To Reproduce**

1. Go to facility
2. Click on a facility 
3. Click on manage facility 
4. Click on location management 
5. Create assets and bed
6. Now edit the bed and click on update
8. See error

**Expected behavior**
The update button must only be clicked once.

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by AshrafMd-1**
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 7d85ef0</samp>

This pull request enhances the `AddBedForm` component to support both adding and updating beds in a facility. It also fixes the `number_of_beds` property to match the API expectations.

## Proposed Changes

- Fixes #6837 
- Change logic so that the update button is only clicked once.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 7d85ef0</samp>

*  Pass `headerText` prop from `BedTypeCard` to `AddBedForm` to indicate whether the form is for adding or updating a bed ([link](https://github.com/coronasafe/care_fe/pull/6841/files?diff=unified&w=0#diff-c3725e9874032f1cdb18f7c6b15f978b17a7306d49ce27104377ac1ccaaa4b8cR21))
*  Use `headerText` prop to conditionally render the label and placeholder of the `TextInputField` for `numberOfBeds` ([link](https://github.com/coronasafe/care_fe/pull/6841/files?diff=unified&w=0#diff-c3725e9874032f1cdb18f7c6b15f978b17a7306d49ce27104377ac1ccaaa4b8cR77))
*  Set `number_of_beds` in the API payload to 1 if updating an existing bed, otherwise use the value of `numberOfBeds` state variable ([link](https://github.com/coronasafe/care_fe/pull/6841/files?diff=unified&w=0#diff-c3725e9874032f1cdb18f7c6b15f978b17a7306d49ce27104377ac1ccaaa4b8cL128-R130))

### CODE REVIEW

File: src/Components/Facility/AddBedForm.tsx [hunk 1]
```diff
@@ -125,7 +127,7 @@ export const AddBedForm = (props: BedFormProps) => {
       name,
       description,
       bed_type: bedType,
-      number_of_beds: numberOfBeds,
+      number_of_beds: headerText === "Update Bed" ? 1 : numberOfBeds,
```
Comment (rithviknishad) [inline src/Components/Facility/AddBedForm.tsx]: Avoid depending on visual texts when possible.

```suggestion
      number_of_beds: bedId ? 1 : numberOfBeds,
```

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
