### PR TITLE
 fix: questionnaire title in Responses tab

### LINKED ISSUE #14342: Questionnaire title disappears after refreshing
**Describe the bug**
When users refresh the page or navigate away and return, the selected questionnaire title disappears from the dropdown selector.

**To Reproduce**

1. Go to 'Encounters'
2. Click on 'Responses' tab
3. Select a form
4. Refresh the page or navigate away and return

**Expected behavior**
Selected questionnaire title should persist in the dropdown after page refreshes and navigation.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by StephZam**
## Proposed Changes

Fixes #14342 
- In responses tab, the selected questionnaire title persists in the dropdown selector after refreshing the page or navigating away and returning.

image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Refactor**
  * Switched questionnaire identifiers from IDs to slugs across the UI (editors, properties, organization management, response lists, and responses tab), and updated related selection, navigation, and data fetching to use slugs for consistent display and behavior.
* **Tests**
  * Updated test data generation for category titles to use alphabetic strings and adjusted a UI test to target a "Back" link instead of a button.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/pages/Encounters/tabs/responses.tsx [hunk 1]
```diff
@@ -165,17 +164,23 @@ export const EncounterResponsesTab = ({
...
-    useState<string>("");
   const [isDrawerOpen, setIsDrawerOpen] = useState(false);
   const isMobile = useBreakpoints({ default: true, md: false });
 
+  const { data: questionnaireData } = useQuery({
+    queryKey: ["questionnaire", questionnaireSlug],
+    queryFn: query(questionnaireApi.get, {
+      pathParams: { slug: questionnaireSlug! },
+    }),
+    enabled: !!questionnaireSlug,
```
Comment (Jacobjeevan) [inline src/pages/Encounters/tabs/responses.tsx]: hmm, not a fan of adding another query 🤔  since we are already fetching questionnaire data inside questionnaire responses list.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Review by Jacobjeevan — APPROVED** [review]

File: src/pages/Encounters/tabs/responses.tsx [hunk 2]
```diff
@@ -254,12 +246,13 @@ export const EncounterResponsesTab = ({
...
-                        showTitle={!questionnaireId}
-                        onTitleClick={(qid) => {
-                          setQueryParams({ questionnaireId: qid });
-                          setSelectedQuestionnaireTitle(
-                            response.questionnaire?.title || "",
-                          );
+                        showTitle={!questionnaireSlug}
+                        onTitleClick={() => {
+                          setQueryParams({
+                            ...qParams,
```
Comment (Jacobjeevan) [inline src/pages/Encounters/tabs/responses.tsx:252]: We might not need to retain the responseId here, well depends on behavior. If user selects an item from panel and were to click on its title will retain styling.

cc: @nihal467 Check if that behavior is fine 🤔

**Review by nihal467 — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
