### PR TITLE
Disabled exception creation for non schedulable users

### LINKED ISSUE #11222: Exception creation is enabled for a user who is not a schedulable resource.
Bug Description:
- Exception creation is currently allowed for users who are not schedulable resources.
- If an exception is created for a user without an associated schedule, the backend rejects the request.
- The rejection reason returned by the backend is unclear and confusing

Solution:
-  The system should prevent exception creation at the API level if the user is not listed as a schedulable resource in the Practitioner API.

Image

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Proposed Changes

- Fixes #11222 
- Disabled the Exception button for the non schedulable users
- Enable the Exception button only after the creation of schedule 
- Here is the demo screenshot

Screenshot from 2025-03-13 13-33-54

- Also exceptions in the popover section of the calendar have been arranged in ascending order, ensuring a more structured and organized display for better readability and usability.

Screenshot from 2025-03-13 22-01-36

@rithviknishad 

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
	- Enhanced user availability interface to conditionally display scheduling information and exception options based on available resources.
	- Added informative messaging indicating that exceptions can only be created after a schedule has been established.

- **Bug Fixes**
	- Updated messaging for scenarios with no scheduled exceptions to clarify prerequisite conditions for creating exceptions.

### CODE REVIEW

File: src/components/Users/UserAvailabilityTab.tsx [hunk 1]
```diff
@@ -85,6 +85,17 @@ export default function UserAvailabilityTab({ userData: user }: Props) {
...
+  const schedulableUsersQuery = useQuery({
+    queryKey: ["practitioners", facilityId],
+    queryFn: query(scheduleApis.appointments.availableUsers, {
+      pathParams: { facility_id: facilityId },
+    }),
+  });
+
+  const availableUserId = schedulableUsersQuery.data?.users.find(
+    (f) => f.id == user.id,
+  );
```
Comment (rithviknishad) [inline src/components/Users/UserAvailabilityTab.tsx]: this can be simplified further by leveraging `select` option of `useQuery` and by switching to using `Array.some` instead of `Array.find`

```suggestion
  const { data: isSchedulableResource } = useQuery({
    queryKey: ["practitioners", facilityId],
    queryFn: query(scheduleApis.appointments.availableUsers, {
      pathParams: { facility_id: facilityId },
    }),
    select: (data) => data.users.some(({ id }) => user.id === id ),
  });
```

File: src/components/Users/UserAvailabilityTab.tsx [hunk 2]
```diff
@@ -163,12 +174,14 @@ export default function UserAvailabilityTab({ userData: user }: Props) {
...
-                setQParams={setQParams}
-              />
+              {availableUserId && (
+                <DayDetailsPopover
+                  date={date}
+                  templates={templates}
+                  unavailableExceptions={unavailableExceptions}
+                  setQParams={setQParams}
+                />
+              )}
```
Comment (rithviknishad) [inline src/components/Users/UserAvailabilityTab.tsx]: wouldn't this still make the mouse pointer to be hand on the calendar? 🤔 although the popover won't open.

let's instead disable the popover trigger itself directly

File: src/components/Users/UserAvailabilityTab.tsx [hunk 3]
```diff
@@ -187,16 +200,18 @@ export default function UserAvailabilityTab({ userData: user }: Props) {
...
+                variant={view === "exceptions" ? "outline" : "ghost"}
+                onClick={() => setQParams({ tab: "exceptions" })}
+                className={cn(
+                  view === "exceptions" && "shadow",
+                  "hover:bg-white text-xs sm:text-sm px-2 md:px-4",
+                )}
+              >
+                {t("exceptions")}
+              </Button>
+            )}
```
Comment (rithviknishad) [inline src/components/Users/UserAvailabilityTab.tsx]: let's not hide the exceptions tab;

it'd be better to disable the create exception button instead and instead of showing "No exceptions created", let's say that exceptions can be created only if the condition is satisfied

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Users/UserAvailabilityTab.tsx (hunk 1 above)
Comment (NikhilA8606) [reply src/components/Users/UserAvailabilityTab.tsx]: React Query treats data as unknown ,so can we manually cast data Inside select like this
select: (data) => (data as { users: UserBase[] }).users.some(({ id }) => user.id === id),

Comment (rithviknishad) [reply src/components/Users/UserAvailabilityTab.tsx]: Yes!

Comment (rithviknishad) [reply src/components/Users/UserAvailabilityTab.tsx]: you can do this:

```
select: (data: { users: UserBase[] }) => data.users.some(({ id }) => user.id === id)
```

File: src/components/Users/UserAvailabilityTab.tsx [hunk 4]
```diff
@@ -170,6 +179,37 @@ export default function UserAvailabilityTab({ userData: user }: Props) {
...
+                      <ColoredIndicator
+                        key={template.id}
+                        id={template.id}
+                        className="size-1.5 rounded-full"
+                      />
+                    ))}
+                </div>
+              </div>
+              <div />
+            </div>
```
Comment (rithviknishad) [inline src/components/Users/UserAvailabilityTab.tsx]: let's not duplicate code; we can simply disable the Popover's trigger instead if not schedulable resource.

File: src/components/Users/UserAvailabilityTab.tsx [hunk 5]
```diff
@@ -311,24 +351,27 @@ function DayDetailsPopover({
...
-                    {t("exception")}: {exception.reason}
-                  </p>
-                  <p className="text-sm text-gray-600">
-                    <span>{formatTimeShort(exception.start_time)}</span>
-                    <span className="px-2 text-gray-300">-</span>
-                    <span>{formatTimeShort(exception.end_time)}</span>
-                  </p>
+            {unavailableExceptions
+              .slice()
+              .sort((a, b) => a.start_time.localeCompare(b.start_time))
```
Comment (rithviknishad) [inline src/components/Users/UserAvailabilityTab.tsx]: correct me if i'm wrong; instead of sorting and slicing here; can't we directly keep it sorted from where `unavailableExceptions` array is created? 🤔 

https://github.com/ohcnetwork/care_fe/blob/8e2dc9391e03a2bb0f7d6332f4768471c9124a40/src/components/Users/UserAvailabilityTab.tsx#L109-L112

File: src/pages/Scheduling/ScheduleExceptions.tsx [hunk 6]
```diff
@@ -52,7 +52,7 @@ export default function ScheduleExceptions({
     return (
       <div className="flex flex-col items-center text-center text-gray-500 py-16">
         <CareIcon icon="l-calendar-slash" className="size-10 mb-3" />
-        <p>{t("no_scheduled_exceptions_found")}</p>
+        <p>{t("exceptions_can_be_created_only_after_creating_a_schedule")}</p>
```
Comment (rithviknishad) [inline src/pages/Scheduling/ScheduleExceptions.tsx]: this would be so wrong when a user already has a schedule but no exceptions right?

we should conditionally show it;

File: src/components/Users/UserAvailabilityTab.tsx [hunk 7]
```diff
@@ -85,6 +85,15 @@ export default function UserAvailabilityTab({ userData: user }: Props) {
     }),
   });
 
+  const { data: isSchedulableResource } = useQuery({
+    queryKey: ["practitioners", facilityId],
```
Comment (rithviknishad) [inline src/components/Users/UserAvailabilityTab.tsx]: the key is now no longer correct; `["practicioners", facilityId]` is meant for practicioners search and hence conflicting usages; here we are selecting only if the user is schedulable resource;

let's have a different key;

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx [hunk 8]
```diff
@@ -132,6 +134,15 @@ export default function CreateScheduleExceptionSheet({
...
   });
 
+  const { data: isSchedulableResource } = useQuery({
+    queryKey: ["practitioners", facilityId],
+    queryFn: query(scheduleApis.appointments.availableUsers, {
+      pathParams: { facility_id: facilityId },
+    }),
+    select: (data) =>
+      (data as { users: UserBase[] }).users.some(({ id }) => userId === id),
+  });
```
Comment (rithviknishad) [inline src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: since this useQuery is duplicated, let's create a new hook `useIsUserSchedulableResource` that returns the useQuery directly with appropriate `queryKey`

File: src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx [hunk 9]
```diff
@@ -168,7 +179,7 @@ export default function CreateScheduleExceptionSheet({
     >
       <SheetTrigger asChild>
         {trigger ?? (
-          <Button variant="primary" disabled={isPending}>
+          <Button variant="primary" disabled={!isSchedulableResource}>
```
Comment (rithviknishad) [inline src/pages/Scheduling/components/CreateScheduleExceptionSheet.tsx]: why was `isPending` removed? 🤔 we still need that as well

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Users/UserAvailabilityTab.tsx (hunk 5 above)
Comment (NikhilA8606) [reply src/components/Users/UserAvailabilityTab.tsx]: yes, you are right it is more efficient to sort the array at the source

File: src/pages/Scheduling/ScheduleExceptions.tsx [hunk 10]
```diff
@@ -44,15 +47,36 @@ export default function ScheduleExceptions({
...
+  };
+
+  const message = getMessage();
+
+  if (message) {
     return (
       <div className="flex flex-col items-center text-center text-gray-500 py-16">
         <CareIcon icon="l-calendar-slash" className="size-10 mb-3" />
-        <p>{t("no_scheduled_exceptions_found")}</p>
+        <p>{message}</p>
```
Comment (rithviknishad) [inline src/pages/Scheduling/ScheduleExceptions.tsx]: instead of doing this, we can make the code more readable like this:

```tsx
if (!isSchedulableResource) {
  return <div ...>
    ...
    {t("exceptions_can_be_created_only_after_creating_a_schedule")}
  </div>
}

if (items.length === 0) {
  return <div ...> same as old one...</div>
}
...
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]
Nice work!

File: src/pages/Scheduling/ScheduleExceptions.tsx [hunk 11]
```diff
@@ -44,10 +45,24 @@ export default function ScheduleExceptions({
...
+
   if (items == null) {
     return <Loading />;
   }
 
+  if (!isSchedulableResource) {
+    return (
+      <div className="flex flex-col items-center text-center text-gray-500 py-16">
+        <CareIcon icon="l-calendar-slash" className="size-10 mb-3" />
+        <p>{t("exceptions_can_be_created_only_after_creating_a_schedule")}</p>
```
Comment (Jacobjeevan) [inline src/pages/Scheduling/ScheduleExceptions.tsx]: minor thing, can we shorten this key?

**Review by Jacobjeevan — APPROVED** [review]
lgtm otherwise.
