### PR TITLE
Monthly filtering in Schedule and Exception

### LINKED ISSUE #12461: Month-based filtering in the schedule
**Describe the bug**
Currently, the schedule does not support filtering by month. Implementing a month-wise filter would improve usability by allowing users to view and manage schedules for specific time periods more efficiently.

**To Reproduce**

1. Go to Schedule
2. Switch months

**Expected behavior**
Month wise filtration

**Screenshots**

Image

**Additional context**
This should need Backend changes also

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Proposed Changes
- Fixes #12461 
- Added queryParms : valid_from and valid_to  

Demo :

[Screencast from 2025-06-05 11-12-21.webm](https://github.com/user-attachments/assets/cae94970-9552-4262-93d9-79c0586b4ff8)

- Associated BE PR : [ Monthly filtering in Schedules and Exceptions #3064 ](https://github.com/ohcnetwork/care/pull/3064)

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
	- Added date range filtering for user schedule templates and exceptions, allowing users to view data scoped to a selected month.
	- Calendar navigation and tab switching now preserve and apply the current date range, ensuring consistent filtering across views.

### CODE REVIEW

File: src/components/Users/UserAvailabilityTab.tsx [hunk 1]
```diff
@@ -73,22 +74,42 @@ export default function UserAvailabilityTab({
   const { hasPermission } = usePermissions();
   const { canViewSchedule } = getPermissions(hasPermission, permissions ?? []);
 
+  const from_date =
+    qParams.valid_from ??
+    format(startOfMonth(new Date()), "yyyy-MM-dd'T'HH:mm");
+  const to_date =
+    qParams.valid_to ?? format(endOfMonth(new Date()), "yyyy-MM-dd'T'HH:mm");
```
Comment (rithviknishad) [inline src/components/Users/UserAvailabilityTab.tsx]: follow js naming conventions please

edit: won't be needed as per next review comment

File: src/components/Users/UserAvailabilityTab.tsx [hunk 2]
```diff
@@ -107,7 +128,12 @@ export default function UserAvailabilityTab({
       <Calendar
         className="lg:order-last"
         month={month}
-        onMonthChange={setMonth}
+        onMonthChange={(newMonth) => {
+          setMonth(newMonth);
+          const start = format(startOfMonth(newMonth), "yyyy-MM-dd'T'HH:mm");
+          const end = format(endOfMonth(newMonth), "yyyy-MM-dd'T'HH:mm");
+          setQParams({ valid_from: start, valid_to: end });
```
Comment (rithviknishad) [inline src/components/Users/UserAvailabilityTab.tsx]: let's not store this in query params. we can derive the `valid_from` and `valid_to` filter values from the existing `month` state.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Users/UserAvailabilityTab.tsx [hunk 3]
```diff
@@ -198,7 +213,11 @@ export default function UserAvailabilityTab({
           <div className="flex bg-gray-100 rounded-lg p-0 md:p-1 gap-1 max-w-min">
             <Button
               variant={view === "schedule" ? "outline" : "ghost"}
-              onClick={() => setQParams({ tab: "schedule" })}
+              onClick={() =>
+                setQParams({
+                  tab: "schedule",
+                })
+              }
```
Comment (rithviknishad) [inline src/components/Users/UserAvailabilityTab.tsx]:
```suggestion
              onClick={() => setQParams({ tab: "schedule" })}
```

File: src/components/Users/UserAvailabilityTab.tsx [hunk 4]
```diff
@@ -208,7 +227,11 @@ export default function UserAvailabilityTab({
             </Button>
             <Button
               variant={view === "exceptions" ? "outline" : "ghost"}
-              onClick={() => setQParams({ tab: "exceptions" })}
+              onClick={() =>
+                setQParams({
+                  tab: "exceptions",
+                })
+              }
```
Comment (rithviknishad) [inline src/components/Users/UserAvailabilityTab.tsx]:
```suggestion
              onClick={() => setQParams({ tab: "exceptions" })}
```

**Review by rithviknishad — APPROVED** [review]
