### PR TITLE
Fix: Ensure structured_type is set for structured questions

### LINKED ISSUE #11390: Structure Type Dropdown State Not Managed Properly in Questionnaire Creation Form
**Describe the bug**

When creating a new questionnaire, clicking "Add Question" and selecting the type as "Structured" automatically selects "Allergy Intolerance" by default. However, this selection is not sent to the backend when the form is submitted. As a result, on the patient encounter page, the Allergy Structured Question appears in the questionnaire dropdown, but the actual structured questionnaire is not accessible.

**To Reproduce**

1. Go to admin dashboard 
2. Click on create questionnaire
3. Click add question
4. select the type "structure" and don't touch the dropdown of the structured type
5. create the question
6. Now go to the facility page and head to encounter page
7. open any live encounter and click update encounter
8. access the newly created allergy form by you
9. see the error

**Expected behavior**

The default-selected Allergy Structured type in the Create Questionnaire form should be sent to the backend properly.

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by yadavshubham01**
## Proposed Changes

- Fixes #11390
### Changes
- Updated the [updateField](http://_vscodecontentref_/3) function to set the default [structured_type](http://_vscodecontentref_/4).

## Screenshot

Screenshot 2025-04-04 194915

Screenshot 2025-04-04 195708

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
	- Enhanced the questionnaire editor experience with improved validation for structured question types.
	- Now displays inline error messages when structured question selections are missing, guiding users to correct issues before saving.

### CODE REVIEW

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 1]
```diff
@@ -889,7 +889,15 @@ function QuestionEditor({
...
     additionalFields?: Partial<Question>,
   ) => {
-    onChange({ ...question, [field]: value, ...additionalFields });
+    const updateQuestion = { ...question, [field]: value, ...additionalFields };
+    if (
+      field === "type" &&
+      value === "structured" &&
+      !updateQuestion.structured_type
+    ) {
+      updateQuestion.structured_type = "allergy_intolerance";
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireEditor.tsx:898]: why does this generic component have to set the stuctured_type to a very specific "allergy intolerance"? 🤔

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — CHANGES_REQUESTED** [review]
The right solution here is to not default the selector to allergy intolerance in the first place instead of hacking the update logic;

**Comment by yadavshubham01** [comment]
Hey @rithviknishad ,
You mean we should approach it like this, right?

- The structured_type field no longer defaults to "allergy_intolerance".

- Instead, a placeholder ("Select structured type") is shown until the user makes a selection.

- If the user doesn't select any value, an error message like "Structured type is required" is displayed.

Just wanted to confirm that this is the direction you're suggesting?

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 2]
```diff
@@ -387,11 +390,34 @@ export default function QuestionnaireEditor({ id }: QuestionnaireEditorProps) {
...
   };
 
+  const validateStructuredType = (): boolean => {
+    let hasError = false;
+    const updatedErrors: Record<string, string | undefined> = {};
+
+    questionnaire.questions.forEach((q) => {
+      if (q.type === "structured" && !q.structured_type) {
+        updatedErrors[q.id] =
+          "Please select a structured type for this question.";
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]: PRs will be closed without reviews if merge checklist is checked without following them!

image

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/QuestionnaireEditor.tsx (hunk 2 above)
Comment (yadavshubham01) [reply src/components/Questionnaire/QuestionnaireEditor.tsx]: @rithviknishad  Sorry about that I’ll make sure to follow the merge checklist properly next time

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 3]
```diff
@@ -889,7 +927,8 @@ function QuestionEditor({
     value: Question[K],
     additionalFields?: Partial<Question>,
   ) => {
-    onChange({ ...question, [field]: value, ...additionalFields });
+    const updateQuestion = { ...question, [field]: value, ...additionalFields };
+    onChange(updateQuestion);
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]:
```suggestion
    onChange({ ...question, [field]: value, ...additionalFields });
```

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 4]
```diff
@@ -387,11 +390,33 @@ export default function QuestionnaireEditor({ id }: QuestionnaireEditorProps) {
     return true;
   };
 
+  const validateStructuredType = (): boolean => {
+    let hasError = false;
+    const updatedErrors: Record<string, string | undefined> = {};
+
+    questionnaire.questions.forEach((q) => {
+      if (q.type === "structured" && !q.structured_type) {
+        updatedErrors[q.id] = t("select_structure_type");
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]: let's keep it consistent; it's simply a required field, and all required field errors in care shows this instead of having a dedicated error message specific for each field.

```suggestion
        updatedErrors[q.id] = t("field_required");
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 5]
```diff
@@ -387,11 +390,33 @@ export default function QuestionnaireEditor({ id }: QuestionnaireEditorProps) {
...
+      if (q.type === "structured" && !q.structured_type) {
+        updatedErrors[q.id] = t("field_required");
+        hasError = true;
+      } else {
+        updatedErrors[q.id] = undefined;
+      }
+    });
+
+    setStructuredTypeErrors((prev) => ({
+      ...prev,
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]: this wouldn't make any difference here, no? setting to updatedErrors should be enough.

Comment (yadavshubham01) [reply src/components/Questionnaire/QuestionnaireEditor.tsx]: Okay, fixed this now

**Review by Jacobjeevan — APPROVED** [review]
