### PR TITLE
Fix for slug field validation error

### LINKED ISSUE #13366: Clear error message for slug when auto filled for Charge item and Tag Config form
https://github.com/user-attachments/assets/cd5cfe15-bd9a-4902-8c73-5b838fa0908a

https://github.com/user-attachments/assets/21ec7d18-a3de-4ee8-8b7e-80fd4ea862f3

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Bichu0077**
## Proposed Changes

Fixes #13366 
-Error message on slug field is cleared when title is entered

https://github.com/user-attachments/assets/e85cac67-878f-43eb-945b-bf020d310d4e

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

- **Bug Fixes**
  - Slug now revalidates automatically when the title/display value changes in create mode for charge item and tag configuration forms, reducing invalid or stale slugs and ensuring required slug validation runs during entry.

### CODE REVIEW

File: src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx [hunk 1]
```diff
@@ -376,13 +379,7 @@ export function ChargeItemDefinitionForm({
...
       newComponents = [
         ...currentComponents,
-        {
-          ...component,
-          monetary_component_type: type,
-          factor: component.factor != null ? component.factor : undefined,
-          amount:
-            component.factor != null ? undefined : String(component.amount),
-        },
+        { ...component, monetary_component_type: type },
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx]: why ? 🤔

File: src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx [hunk 2]
```diff
@@ -407,10 +404,10 @@ export function ChargeItemDefinitionForm({
     if (componentIndex === -1) return;
 
     const newComponents = [...currentComponents];
+    const isFactor = component.factor != null;
     newComponents[componentIndex] = {
       ...component,
-      factor: component.factor != null ? value : undefined,
-      amount: component.factor != null ? undefined : String(value),
+      [isFactor ? "factor" : "amount"]: isFactor ? value : String(value),
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx]: why ??

File: src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx [hunk 3]
```diff
@@ -300,7 +300,10 @@ export function ChargeItemDefinitionForm({
 
     const subscription = form.watch((value, { name }) => {
       if (name === "title") {
-        form.setValue("slug", generateSlug(value.title || ""));
+        form.clearErrors("slug");
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx]: Why are we manually clearing the error? 🤔 Doesn’t shouldValidate handle that automatically?

File: src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx (hunk 2 above)
Comment (Bichu0077) [reply src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx]: suggested by code rabbit. should I revert?

File: src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx (hunk 3 above)
Comment (Bichu0077) [reply src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx]: coderabbit wasn't detecting that the issue is resolved. so I tried this thing. Will fix it 👍

File: src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx (hunk 2 above)
Comment (AdityaJ2305) [reply src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx]: Code rabit suggested changes because you had made some changesalready in these lines 

Unrelated to issue right 

Feel free to file separate issue and PR

Comment (Bichu0077) [reply src/pages/Facility/settings/chargeItemDefinitions/ChargeItemDefinitionForm.tsx]: okay

**Review by AdityaJ2305 — COMMENTED** [review]
tag config form is pending

**Comment by Bichu0077** [comment]
> tag config form is pending

Done 👍

**Review by AdityaJ2305 — APPROVED** [review]

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

**Review by rithviknishad — APPROVED** [review]
