### PR TITLE
Username validation added in Create user form

### LINKED ISSUE #9769: Add username validation in user creation form
**Describe the bug**
`Username already taken error ` coming after submitting the form

**To Reproduce**

1. Go to 'organization'
2. Click on 'users tab'
3. add user
4. enter existing username

**Expected behavior**
while entering username it should display the corresponding validation error

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Rishith25**
## Proposed Changes

- Fixes #9769 
- Added validation check for username
- Checking the availability of username

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Introduced additional localization keys for user roles and contact information.
	- Enhanced username availability check with real-time feedback in the user creation form.

- **Bug Fixes**
	- Improved form validation feedback mechanisms.

- **Documentation**
	- Updated localization strings for better user guidance.

### CODE REVIEW

**Comment by rithviknishad** [comment]
PR's that are using the old deprecated methods, will be closed without review.

**Comment by Rishith25** [comment]
@Jacobjeevan @rithviknishad I have done the changes and I have remove deprecated methods
Can you reopen the PR

File: src/components/Users/CreateUserForm.tsx [hunk 1]
```diff
@@ -92,9 +100,131 @@ interface Props {
...
+    idle: 0,
+    checking: 1,
+    exists: 2,
+    available: 3,
+  };
+
+  const [usernameExists, setUsernameExists] = useState<number>(
+    userExistsEnums.idle,
+  );
+  const [usernameInput, setUsernameInput] = useState("");
```
Comment (rithviknishad) [inline src/components/Users/CreateUserForm.tsx]: i don't see any reason why we need this enum for each stage of processing

File: src/components/Users/CreateUserForm.tsx [hunk 2]
```diff
@@ -92,9 +100,131 @@ interface Props {
...
+      } else {
+        toast.error(
+          "Some error occurred while checking username availability. Please try again later.",
+        );
+        setUsernameExists(userExistsEnums.idle);
+      }
+    } else {
+      setUsernameExists(userExistsEnums.available);
+    }
+  }, [data, error, isLoading, usernameInput]);
```
Comment (rithviknishad) [inline src/components/Users/CreateUserForm.tsx]: i don't see any reason for complicating a simple username check to this level. can't we simply do a useQuery and check if data (available) or error (not available) is present and isLoading (processing stage)?

File: src/components/Users/CreateUserForm.tsx [hunk 3]
```diff
@@ -92,9 +100,131 @@ interface Props {
...
+      default:
+        return null;
+    }
+  };
+
+  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
+    const value = e.target.value;
+    setUsernameInput(value);
+    setUsernameExists(userExistsEnums.idle);
+  };
```
Comment (rithviknishad) [inline src/components/Users/CreateUserForm.tsx]: to access zod's state, you can use `form.watch` instead of introducing a state variable.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Users/CreateUserForm.tsx [hunk 4]
```diff
@@ -92,9 +100,131 @@ interface Props {
   onSubmitSuccess?: (user: UserBase) => void;
 }
 
+export const validateRule = (
```
Comment (Jacobjeevan) [inline src/components/Users/CreateUserForm.tsx]: validateRule is already present in the codebase (UserFormValidations).

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Users/CreateUserForm.tsx [hunk 5]
```diff
@@ -313,7 +363,9 @@ export default function CreateUserForm({ onSubmitSuccess }: Props) {
                 />
               </FormControl>
               <div className="space-y-1 leading-none">
-                <FormLabel>WhatsApp number is same as phone number</FormLabel>
+                <FormLabel>
+                  {t("whataapp_number_same_as_phone_number")}
+                </FormLabel>
```
[the remark this answers is not in the document]
Comment (Jacobjeevan) [reply src/components/Users/CreateUserForm.tsx]: @Rishith25 Minor thing, but fix the typo as well.

File: src/components/Users/CreateUserForm.tsx [hunk 6]
```diff
@@ -107,14 +114,52 @@ export default function CreateUserForm({ onSubmitSuccess }: Props) {
...
+  const { error, isLoading } = useQuery({
+    queryKey: ["checkUsername", usernameInput],
+    queryFn: query(userApi.checkUsername, {
+      pathParams: { username: usernameInput },
+      silent: true,
+    }),
+    enabled: usernameInput?.length >= 4,
+  });
+
+  const renderUsernameFeedback = (usernameInput: string) => {
```
Comment (Jacobjeevan) [inline src/components/Users/CreateUserForm.tsx:139]: Have isLoading as the first check; ask yourself what ordering makes sense when writing code :)

File: src/components/Users/CreateUserForm.tsx [hunk 7]
```diff
@@ -107,14 +114,52 @@ export default function CreateUserForm({ onSubmitSuccess }: Props) {
...
+            className="text-xl text-gray-500 animate-spin"
+          />
+          <span className="text-gray-500 text-sm">
+            {t("checking_availability")}
+          </span>
+        </div>
+      );
+    } else if (error) {
+      return validateRule(false, <>{t("username_not_available")}</>);
+    } else if (usernameInput && !form.formState.errors.username && !isLoading) {
```
Comment (Jacobjeevan) [inline src/components/Users/CreateUserForm.tsx]: Shouldn't need to check !isLoading since you are already checking whether isLoading is true earlier.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Users/CreateUserForm.tsx (hunk 6 above)
Comment (Rishith25) [reply src/components/Users/CreateUserForm.tsx:139]: @Jacobjeevan I think the correct order of checks make sense as at first we have to display the validity of the username and if it is valid then we have to display the availability.

is this correct

Comment (Jacobjeevan) [reply src/components/Users/CreateUserForm.tsx:139]: yep, makes sense 👍

**Review by Jacobjeevan — APPROVED** [review]
image

Adjust the font size as well (though check other places that call validateRule once you have changed it).

Other than that, lgtm.

**Review by rithviknishad — APPROVED** [review]

**Comment by Rishith25** [comment]
> image
> Adjust the font size as well (though check other places that call validateRule once you have changed it).
> 
> Other than that, lgtm.

@Jacobjeevan ✅Done

**Comment by nihal467** [comment]
LGTM
