### PR TITLE
fixed the console key prop error

### LINKED ISSUE #13551: Add unique 'key' prop to list items in NavMain component
**Describe the bug**
"Each child in a list should have a unique 'key' prop" appears in the browser console. The warning is specific to the component's render method in NavMain component.

**To Reproduce**

1. Go to any page with sidebar navigation
2. Click on Open browser developer tools (F12)
3. Check console
4. See warning about missing key prop in list children

**Expected behavior**
1. No console warnings should appear
2. Each child element in mapped lists should have a unique key prop
3. React should properly track and update list items

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
The warning occurs in the sidebar navigation component where we're mapping over the Fragment wrapper (<>) also needs a unique key since it's the direct child of the map function.

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by vara-prasad-07**
## Proposed Changes
Fixed the console issue by adding the key prop to the fragment tag and removing the key prop at the "SidebarMenuSubItem" tag. 
Fixes #13551
- added the key prop to the fragment tag
- removed the key prop at the "SidebarMenuSubItem" tag.

View (no key prop error in console):

WhatsApp Image 2025-08-30 at 18 48 30_df5473e3

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

- **Refactor**
  - Improved sidebar navigation rendering to reduce visual flicker and improve stability when nested menu items update.
  - No functional or API changes expected for end users; behavior and navigation remain the same.

### CODE REVIEW

**Comment by vara-prasad-07** [comment]
Hi @Jacobjeevan @rithviknishad 
I made changes and fixed issue #13551 . Could anyone review this pr
Thank you

**Review by NikhilA8606 — APPROVED** [review]

**Review by NikhilA8606 — COMMENTED** [review]
Solve merge conflicts

File: src/components/ui/sidebar/nav-main.tsx [hunk 1]
```diff
@@ -99,43 +99,41 @@ export function NavMain({ links }: { links: NavigationLink[] }) {
...
-                                  </div>
-                                )}
-                                <SidebarMenuSubItem key={subItem.name}>
-                                  <SidebarMenuSubButton
-                                    asChild
-                                    data-cy={`nav-${subItem.name.toLowerCase().replace(/\s+/g, "-")}`}
-                                    className={
-                                      "text-gray-600 transition font-normal hover:bg-gray-200 hover:text-green-700"
-                                    }
+                          {link.children.map((subItem) => (
```
Comment (NikhilA8606) [inline src/components/ui/sidebar/nav-main.tsx]: Why you deleted the existing code?

**Review by NikhilA8606 — CHANGES_REQUESTED** [review]

File: src/components/ui/sidebar/nav-main.tsx (hunk 1 above)
Comment (vara-prasad-07) [reply src/components/ui/sidebar/nav-main.tsx]: sorry while i was removing conflicts i removed base branch. i thought it was correct, i will fix it and push changes again with in 15min

Comment (vara-prasad-07) [reply src/components/ui/sidebar/nav-main.tsx]: @NikhilA8606 , once check the latest commit.

**Review by NikhilA8606 — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
