### PR TITLE
Fix : Form Validation Error Messages Not Displaying

### LINKED ISSUE #11145: Validation Messages Not Displaying as Intended
**Describe the bug**

Validation error messages for form fields in `DeviceForm`, `CreateEncounterForm`, and potentially other forms are not displaying as intended.

Image

Image

Image

**To Reproduce**

1. Go to Settings > Devices >  Edit
2. Go to Patients > Search Patient > Create Encounter

**Expected behavior**

Image

Image

Image

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by rajku-dev**
## Proposed Changes

- Fixes #11145

Image

Image

Image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Enhanced localization support with new entries for outpatient care, encounter creation, home health services, and more.
  - Added a localized success message for copying icons to the clipboard.
  - Introduced a new function for encounter classes with translatable labels and descriptions.

- **Bug Fixes**
  - Updated character count validation message for clarity and specificity.

- **Refactor**
  - Improved form validation by providing consistent, localized error notifications (e.g., for pager number length) across various user interfaces.
  - Moved schema and default values declarations within form components to improve accessibility to translation functions.

### CODE REVIEW

File: src/components/Encounter/CreateEncounterForm.tsx [hunk 1]
```diff
@@ -143,6 +112,36 @@ export default function CreateEncounterForm({
...
+  const encounterFormSchema = z.object({
+    status: z.enum(["planned", "in_progress", "on_hold"] as const),
+    encounter_class: z.enum([
+      "imp",
+      "amb",
+      "obsenc",
+      "emer",
+      "vr",
+      "hh",
+    ] as const),
```
Comment (abhimanyurajeesh) [inline src/components/Encounter/CreateEncounterForm.tsx]: shall we optimize it reusing the `ENCOUNTER_CLASS` from types constants!? 

cc: @rithviknishad

Comment (rajku-dev) [reply src/components/Encounter/CreateEncounterForm.tsx]: nice suggestion, applied.

File: src/components/Encounter/CreateEncounterForm.tsx [hunk 2]
```diff
@@ -48,79 +48,52 @@ import routes from "@/Utils/request/api";
...
-    label: "Home Health",
-    icon: Home,
-    description: "Care provided at patient's home",
-  },
-] as const;
+const encounterClasses = () =>
+  [
+    {
+      value: "imp",
+      label: "Inpatient",
```
Comment (rithviknishad) [inline src/components/Encounter/CreateEncounterForm.tsx]: i18n

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Encounter/CreateEncounterForm.tsx (hunk 2 above)
Comment (rajku-dev) [reply src/components/Encounter/CreateEncounterForm.tsx]: added new translations.

File: src/components/Encounter/CreateEncounterForm.tsx [hunk 3]
```diff
@@ -48,79 +48,52 @@ import routes from "@/Utils/request/api";
...
-    description: "Virtual/telehealth consultation",
-  },
-  {
-    value: "hh",
-    label: "Home Health",
-    icon: Home,
-    description: "Care provided at patient's home",
-  },
-] as const;
+const encounterClasses = () =>
```
Comment (Jacobjeevan) [inline src/components/Encounter/CreateEncounterForm.tsx]: why make this an arrow function? 🤔 

Let's move this to encounter.ts

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx
Comment (Jacobjeevan) [inline src/pages/Facility/settings/devices/components/DeviceForm.tsx:1]: What exactly is the change here, apart from moving the schema and default values inside the component 🤔

File: src/types/common/contactPoint.ts [hunk 4]
```diff
@@ -24,50 +25,51 @@ export interface ContactPoint {
...
-    use: z.enum(ContactPointUses),
-  }),
-  // Other (catch-all with basic validation)
-  z.object({
-    system: z.literal("other"),
-    value: z.string().min(1, { message: "Required" }),
-    use: z.enum(ContactPointUses),
-  }),
-]);
+export const contactPointSchema = () =>
```
Comment (Jacobjeevan) [inline src/types/common/contactPoint.ts:28]: why an arrow function?

**Review by Jacobjeevan — DISMISSED** [review]

File: src/components/Encounter/CreateEncounterForm.tsx (hunk 3 above)
Comment (rajku-dev) [reply src/components/Encounter/CreateEncounterForm.tsx]: > why make this an arrow function? 🤔

Here → https://github.com/ohcnetwork/care_fe/pull/10581#discussion_r1953671656

Comment (rajku-dev) [reply src/components/Encounter/CreateEncounterForm.tsx]: > Let's move this to encounter.ts

made the change as requested.

File: src/pages/Facility/settings/devices/components/DeviceForm.tsx
Comment (rajku-dev) [reply src/pages/Facility/settings/devices/components/DeviceForm.tsx:1]: translations don't load outside component rendering no text or zod internal messages

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image

the issue still persist, do recheck your PR

**Comment by rajku-dev** [comment]
> the issue still persist, do recheck your PR

fixed
image
