### PR TITLE
Fixed bed number coming up two time in patients page.

### LINKED ISSUE #6525: Bed number coming up two time in patients page
**Describe the bug**
In Assam CARE website in the patients page/view patients page in any facility where the list of all the patients comes up the bed number is coming up two time like "Bed 5 Bed 5" "Bed 4 Bed 4".

**To Reproduce**

1. Go to 'CARE website'
2. Click on 'Click on patients or view patients for any facility'
3. The patients list will come up there you see the same bed nos are coming up twice.

**Expected behavior**
It should show "ICU Bed 1"  "ICU Bed 4" "ICU Bed 5"

**Screenshots**
WhatsApp Image 2023-10-30 at 18 32 15_1fb8618b

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [chrome]
- Version [Version 118.0.5993.118 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**

- Device: [Mi Note 10]
- OS: [Android]
- Browser [Chrome]
- Version [118.0.5993.1111]

**Additional context**
In computer system you might not see the issue bcoz in computer system it will show "ICU BED 1..." "ICU BED 2..." "ICU Bed 4..." but those "...." is the repeated bed numbers but in mobile devices it is clear.

### PR DESCRIPTION
**Pull request by AshrafMd-1**
### <samp>🤖 Generated by Copilot at 5289ad2</samp>

Removed current bed name from patient manager component. This is part of a UI/UX improvement for the patient dashboard and consultation details.

## Proposed Changes

- Fixes #6525
- Just removed a duplicate copy of bed data component which is causing the patients page to display the bed data 2 times.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 5289ad2</samp>

* Remove display of current bed name in patient manager component ([link](https://github.com/coronasafe/care_fe/pull/6526/files?diff=unified&w=0#diff-6a60fce2df893cf91c0457f6445b903c1d6667b6a86fc21c38a9e8fc385c7575L536))

### CODE REVIEW

File: src/Components/Patient/ManagePatients.tsx [hunk 1]
```diff
@@ -533,7 +533,6 @@ export const PatientManager = () => {
                     </span>
                   </span>
                   <span className="w-full truncate px-1 text-center text-base font-bold">
-                    {patient?.last_consultation?.current_bed?.bed_object.name}
                     <span className="tooltip-text tooltip-bottom">
                       {
                         patient?.last_consultation?.current_bed?.bed_object
```
Comment (rithviknishad) [inline src/Components/Patient/ManagePatients.tsx]: Shouldn't you remove this duplicate tooltip too?

Delete the entire duplicate span node.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Patient/ManagePatients.tsx (hunk 1 above)
Comment (AshrafMd-1) [reply src/Components/Patient/ManagePatients.tsx:538]: so should i remove the tooltip ??

Comment (AshrafMd-1) [reply src/Components/Patient/ManagePatients.tsx]: image

currently, I edited the code for the tooltip to look like this when the mouse hovers.
previously the tooltip was not working

The code is 
```
<div className="tooltip flex h-full flex-col items-center justify-center">
                  <span className="w-full truncate px-1 text-center text-sm text-gray-900">
                    {
                      patient?.last_consultation?.current_bed?.bed_object
                        ?.location_object?.name
                    }
                  </span>
                  <span className="w-full truncate px-1 text-center text-base font-bold">
                    {patient?.last_consultation?.current_bed?.bed_object?.name}
                  </span>
                  <span className="tooltip-text tooltip-bottom">
                    {
                      patient?.last_consultation?.current_bed?.bed_object
                        ?.location_object?.name
                    }
                    <br />
                    {patient?.last_consultation?.current_bed?.bed_object?.name}
                  </span>
                </div>
```
so should I keep the tooltip or do I entirely remove it?

Comment (rithviknishad) [reply src/Components/Patient/ManagePatients.tsx]: Sure!

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
