### PR TITLE
Fix: Profile Syncing

### LINKED ISSUE #9960: Profile Not Syncing with Sidebar Navigation
**Describe the bug**
 When updating or deleting a user's profile picture, the changes are not immediately reflected in the sidebar navigation.

**To Reproduce**

1. Go to "Profile" section
2. Click on "Change Avatar"
3. Upload a new image or delete existing image
4. The profile page updates immediately, the sidebar avatar remains unchanged

**Expected behavior**
When a user updates or deletes their profile picture , the change should be immediately visible in main profile and sidebar avatar

**Screenshots**

https://github.com/user-attachments/assets/136026dd-69a7-451c-855d-cc6c3874d7ae

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #9960

- used  invalidateQueries

https://github.com/user-attachments/assets/4373cb18-06d9-4c6e-a93f-44004f8c5770

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved data synchronization for user avatar updates and deletions
	- Ensured immediate cache refresh after profile picture changes
- **New Features**
	- Enhanced query management for user data using the latest library integration

### CODE REVIEW

**Comment by Jeffrin2005** [comment]
@rithviknishad Any changes required  ?

File: src/components/Users/UserAvatar.tsx [hunk 1]
```diff
@@ -74,8 +77,9 @@ export default function UserAvatar({
       pathParams: { username },
     });
     if (res?.ok) {
-      toast.success(t("profile_picture_deleted"));
       refetchUserData?.();
+      await queryClient.invalidateQueries({ queryKey: ["currentUser"] });
```
Comment (rithviknishad) [inline src/components/Users/UserAvatar.tsx]: we can skip awaiting the query invalidation. toast can be shown right after the mutation has upload/delete has completed without waiting for invalidation to complete.
```suggestion
      queryClient.invalidateQueries({ queryKey: ["currentUser"] });
```

File: src/components/Users/UserAvatar.tsx [hunk 2]
```diff
@@ -58,6 +60,7 @@ export default function UserAvatar({
         if (xhr.status === 200) {
           await sleep(1000);
           refetchUserData?.();
+          await queryClient.invalidateQueries({ queryKey: ["currentUser"] });
```
Comment (rithviknishad) [inline src/components/Users/UserAvatar.tsx]: here too

File: src/components/Users/UserAvatar.tsx [hunk 3]
```diff
@@ -58,6 +60,7 @@ export default function UserAvatar({
         if (xhr.status === 200) {
           await sleep(1000);
           refetchUserData?.();
```
Comment (rithviknishad) [inline src/components/Users/UserAvatar.tsx]: now that we are invalidating the query, do we need to call `refetchUserData`?
check what the callees are doing with it and see if we can remove this.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]
LGTM
