### PR TITLE
Fixed Navigation from Table Cell in Diagnostic Report resulting in 404 error

### LINKED ISSUE #13581: Navigation in Diagnostic Reports is broken - Error 404
**Describe the bug**
Navigating from table cell of diagnostic reports routes the user to 404 page.

**To Reproduce**

1. Go to Diagnostic Reports
2. Click on the table cell (not view details action)
3. See error

**Expected behavior**
Navigation should work as intended i.e navigate to the correct diagnostic reports page.

**Screenshots**

https://github.com/user-attachments/assets/d05c5ca3-4f39-4511-925a-3e4d4670d166

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by SiddanthNayak**
## Proposed Changes

Fixes #13581 
- Added patient + patient identifier to route when navigating from table cell
- Earlier diagnostic_report route was being appended to facility and hence navigating to a 404 page. 

Tagging: @ohcnetwork/care-fe-code-reviewers

https://github.com/user-attachments/assets/870da150-91fd-449e-b556-18895c255d4c

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

* **Bug Fixes**
  * Diagnostic report titles now open the correct patient-specific page, preventing broken links and preserving context.

* **Style**
  * Report status display updated to a standardized badge component for a cleaner, more consistent visual in the Diagnostic Reports list.

### CODE REVIEW

**Review by abhimanyurajeesh — APPROVED** [review]

**Review by abhimanyurajeesh — CHANGES_REQUESTED** [review]
Since you’re already making changes in this file, could you replace the status span with the Badge component?

**Comment by SiddanthNayak** [comment]
> Since you’re already making changes in this file, could you replace the status span with the Badge component?

@abhimanyurajeesh made the requested changes, please review

File: src/pages/Encounters/tabs/diagnostic-reports.tsx [hunk 1]
```diff
@@ -107,13 +108,14 @@ export const EncounterDiagnosticReportsTab = () => {
...
                           </TableCell>
                           <TableCell>
-                            <span
-                              className={`inline-flex rounded-full px-2 py-0.5 text-xs font-medium ${
+                            <Badge
+                              variant={
                                 DIAGNOSTIC_REPORT_STATUS_COLORS[report.status]
-                              }`}
+                              }
+                              className="inline-flex rounded-full px-2 py-0.5 text-xs font-medium"
```
Comment (abhimanyurajeesh) [inline src/pages/Encounters/tabs/diagnostic-reports.tsx]:
```suggestion
```

i feel we don't need this

Comment (SiddanthNayak) [reply src/pages/Encounters/tabs/diagnostic-reports.tsx]: Yep, the legacy classnames which was used for span is no longer required for the Badge component.

Removed them.

cc: @abhimanyurajeesh

**Review by abhimanyurajeesh — APPROVED** [review]
