### PR TITLE
fix no data issue in notice borad on hard reload

### LINKED ISSUE #3449: notice board is not showing any notification send to the facility
**Describe the bug**

- [x] when we are sending a notification to the facility using a district admin access and view the notification received to the facility as a staff user, unable to see the notification received in the notice board
- [x] when we hard refresh ( Ctrl + F5 ) the notice board page, it says no notice available 

**To Reproduce**

1. Go to the facility page using a district admin access
2. Click on any facility, and send a notification to the facility 
3. re-login using a staff id linked to that facility
4. go to the notice board
5. see the error that nothing is been reflected there

**Expected behavior**

the notice sent to the facility using a district admin should appear on the notice board of the staff linked to the facility

**Screenshots**

image

- above image shows that the notification is sent to the facility

image

- above image shows that the notification is not reflected in the staff login notice board

image

- above image shows that after the hard refresh ( Ctrl +F5 ), the notice board become blank

### PR DESCRIPTION
**Pull request by khavinshankar**
### <samp>🤖 Generated by Copilot at e537978</samp>

This pull request improves the `NoticeBoard` component by using a regular function instead of a type declaration, and fixes the caching issue of the `getNotifications` action by passing a timestamp as the cache key. These changes enhance the code quality and the user experience of the notifications feature.

## Proposed Changes

- Fixes #3449 
- fix no data issue in notice borad on hard reload

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at e537978</samp>

*  Invalidate cache and fetch latest notifications by passing timestamp to `fireRequest` ([link](https://github.com/coronasafe/care_fe/pull/6025/files?diff=unified&w=0#diff-a0c88ccc2116ceb542bc9be228c54ed98b0bc89e2d9daf66c941f1a0305e626eL688-R694))
* Simplify `NoticeBoard` component by using regular function instead of type declaration ([link](https://github.com/coronasafe/care_fe/pull/6025/files?diff=unified&w=0#diff-33552eee109f3cbc88f165a1053317d2af34c789d901afe14c866b5d1977a144L10-R10))

### CODE REVIEW

File: src/Redux/actions.tsx [hunk 1]
```diff
@@ -685,7 +685,13 @@ export const partialUpdateExternalResult = (id: number, params: object) => {
 
 // Notifications
 export const getNotifications = (params: object) => {
-  return fireRequest("getNotifications", [], params);
+  return fireRequest(
+    "getNotifications",
+    [],
+    params,
+    {},
+    new Date().getTime().toString()
```
Comment (rithviknishad) [inline src/Redux/actions.tsx]: but the point of having a key is that we prevent redundant calls in the first place right?

maybe we can pass key to the action function itself? (similar to how provisional diagnosis and diagnosis works?

```suggestion
    altKey
```

Comment (khavinshankar) [reply src/Redux/actions.tsx]: makes sense 👍

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]

**Review by gigincg — APPROVED** [review]
