### PR TITLE
Fix : Rotation Functionality in "Files" Section

### LINKED ISSUE #10786: Rotation Functionality in "Files" Section
**Describe the bug**

**To Reproduce**
The rotation functionality in the "Files" section is not working as expected. When clicking "Rotate left" or "Rotate right", the image only rotates 90 degrees to the right

1. Go to the "Encounters".
2. Click on "View Details" 
3. Click on "Files" 
4. View an image.
5. Click either "Rotate left" or "Rotate right".
6. Observe that the image only rotates 90 degrees to the right.

**Expected behavior**
A single button should be implemented to handle rotation, allowing the image to rotate 360 degrees in 90-degree increments with each click. 

**Video clip**
Currently

https://github.com/user-attachments/assets/251cecae-ca1b-47c1-aa7b-fa77d4d0356a

Expected

https://github.com/user-attachments/assets/ffba4a60-eb8e-4ec8-8c73-6e7b5c7b53bf

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #10786 

https://github.com/user-attachments/assets/71827e15-8c3e-4504-ad9b-81fcc9e33fea

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced the file preview rotation control to accept angle parameters for more precise rotations.
	- Simplified the logic for determining the CSS class based on normalized rotation values.
	- Updated UI elements for rotation to streamline user interaction.

### CODE REVIEW

**Review by Jacobjeevan — COMMENTED** [review]
Let's add it as clockwise and counterclockwise rotate.

**Comment by Jeffrin2005** [comment]
@Jacobjeevan 


https://github.com/user-attachments/assets/343d8785-d6c1-464d-9a7f-5015499dd3ba

File: src/components/Common/FilePreviewDialog.tsx [hunk 1]
```diff
@@ -125,6 +125,32 @@ const FilePreviewDialog = (props: FilePreviewProps) => {
...
+        ...prev,
+        rotation: newRotation,
+      };
+    });
+  };
+
+  function getRotationClass(rotation: number) {
+    const normalizedRotation = rotation % 360;
+    switch (normalizedRotation) {
+      case 0:
```
Comment (Jacobjeevan) [inline src/components/Common/FilePreviewDialog.tsx]: minor thing; we can remove case 0.

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Comment by nihal467** [comment]
LGTM
