### PR TITLE
Adds utility CSS class `cui-form-button-group`; Fix button responsiveness in Doctor and Bed capacity forms

### LINKED ISSUE #6038: Save doctor capacity is malfunctioning
**Describe the bug**

the save doctor capacity section during the facility creation flow, is showing the buttons in two rows

**To Reproduce**

1. Go to https://care.ohc.network/facility/create
2. Fill all the details until the save doctor capacity
3. See error

**Expected behavior**

all the buttons should be ideally in a single row

**Screenshots**

image

### PR DESCRIPTION
**Pull request by rithviknishad**
### <samp>🤖 Generated by Copilot at c153b8b</samp>

This pull request fixes a bug in the doctor capacity form, refactors the button styles for the bed and doctor capacity forms, and adds a custom CSS class for the button layout. These changes improve the data accuracy, the user interface, and the code quality of the facility management feature.

## Proposed Changes

- Fixes #6038
- Adds utility CSS class `cui-form-button-group`
- Fix button responsiveness in **Doctor and Bed capacity** forms

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at c153b8b</samp>

*  Fix typo in finding doctor capacity data by area ([link](https://github.com/coronasafe/care_fe/pull/6046/files?diff=unified&w=0#diff-6ecf3e8854de3cbfb407d68fad0e6a0c43d2aee9ae994fef7832c3b5ac60a2f5L84-R84))
*  Refactor button rendering in bed and doctor capacity forms to use custom CSS class `cui-form-button-group` ([link](https://github.com/coronasafe/care_fe/pull/6046/files?diff=unified&w=0#diff-ca49d2c12115053a336cf12a96437c052fbf2467d342662e0ae8417ba1c7b13aL284-R298), [link](https://github.com/coronasafe/care_fe/pull/6046/files?diff=unified&w=0#diff-6ecf3e8854de3cbfb407d68fad0e6a0c43d2aee9ae994fef7832c3b5ac60a2f5L252-R261))
*  Add `cui-form-button-group` class definition to `src/style/CAREUI.css` file ([link](https://github.com/coronasafe/care_fe/pull/6046/files?diff=unified&w=0#diff-745b128294a716ac5806ad2ce4bc1537c4205eb3a906d1d28f1b56d30db09eb5L167-R169))

### CODE REVIEW

File: src/Components/Facility/DoctorCapacity.tsx [hunk 1]
```diff
@@ -81,7 +81,7 @@ export const DoctorCapacity = (props: DoctorCapacityProps) => {
             const updatedDoctorTypes = initDoctorTypes.map(
               (type: OptionsType) => {
                 const isExisting = existingData.find(
-                  (i: DoctorModal) => i.area === type.id
+                  (i: DoctorModal) => i.area === type.idnpm
```
Comment (rithviknishad) [inline src/Components/Facility/DoctorCapacity.tsx]:
```suggestion
                  (i: DoctorModal) => i.area === type.id
```

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
