### PR TITLE
Fix: prevent new tags from being deleted from dropdowns

### LINKED ISSUE #13423: Removing newly created Tag Deletes It from Both Selected and Tag List Dropdowns
**Describe the bug**
During Create Questionnaire if the user creates a tag and deletes the newly created tag from selected tag, it gets removed from the dropdown list aswell. User will have to refresh the page to see the tag again.

**To Reproduce**

1. Go to Create Questionnaire
2. Create Tag
3. Remove the newly created tag from selected tags.
4. Notice it gets removed from Select Tags dropdown

**Expected behavior**
Tag should only be removed from selected list and not Tag List dropdown (Currently it requires user to refresh the page to see the tag again)

**Screenshots**

**Desktop (please complete the following information):**

https://github.com/user-attachments/assets/b352259b-42d9-4fd3-9c24-4ddb51bcec32

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by SiddanthNayak**
## Proposed Changes

Fixes #13423
- changed invalidateQueries queryKey from `questionnaire_tags` to `tags`
- Additional context: The wrong queryKey was being passed when new tags were created which is why the oldTags were not being invalidated and refetched. With this change, the correct key is being passed and values are being refetched when creating new tags.

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.

https://github.com/user-attachments/assets/c039319f-e80c-403a-879b-e108554e2251

- [ ] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

* **Refactor**
  * Standardized internal identifiers for questionnaire tag caching to improve consistency; no UI or behavior changes.

* **Bug Fix**
  * Fixed tag-list refresh so newly created tags reliably appear after creation.

### CODE REVIEW

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

**Review by yash-learner — APPROVED** [review]
Nice work!

LGTM

---

ps: I failed to find the correct key yesterday somehow

**Comment by nihal467** [comment]
LGTM]p

File: src/components/Questionnaire/CreateQuestionnaireTagSheet.tsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ export default function CreateQuestionnaireTagSheet({
     onSuccess: (data: unknown) => {
       const tagData = data as QuestionnaireTagModel;
       queryClient.invalidateQueries({
-        queryKey: ["questionnaire_tags"],
+        queryKey: ["tags"],
       });
```
[the remark this answers is not in the document]
Comment (AdityaJ2305) [reply src/components/Questionnaire/CreateQuestionnaireTagSheet.tsx]: @SiddanthNayak  👆 

Instead update the query at the place of fetching to `questionnaire_tags ` since these are the tags specific to questionnaire checkout this 👇 

https://github.com/ohcnetwork/care_fe/blob/develop/src/types/questionnaire/questionnaireApi.ts#L84


cc: @yash-learner

Comment (rithviknishad) [inline src/components/Questionnaire/CreateQuestionnaireTagSheet.tsx]: this query key conflicts with generic tags used by tag config api's. we should consider renaming query keys of questionnaire tags to be specific to questionnaire

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/CreateQuestionnaireTagSheet.tsx (hunk 1 above)
Comment (yash-learner) [reply src/components/Questionnaire/CreateQuestionnaireTagSheet.tsx]: Nice find @AdityaJ2305 @rithviknishad @coderabbitai

----

> this query key conflicts with generic tags used by tag config api's.

@rithviknishad Nope 

it is `queryKey: ["tags", resource, "parent", parentId]` and `queryKey: ["tags", resource, search]`

> we should consider renaming query keys of questionnaire tags to be specific to questionnaire

Yes, we should rename it more meaningful

Comment (rithviknishad) [reply src/components/Questionnaire/CreateQuestionnaireTagSheet.tsx]: so when we ever do `invalidateQueries` of `"tags"` this would invalidate both tag config results and questionnaire tags right?

Comment (AdityaJ2305) [reply src/components/Questionnaire/CreateQuestionnaireTagSheet.tsx]: > this query key conflicts with generic tags used by tag config api's.
> 
> @rithviknishad Nope
> 
> it is queryKey: ["tags", resource, "parent", parentId] and queryKey: ["tags", resource, search]

this works on the basis of prefix 

so here, every query will get invalidate which has prefix "tags"

checkout this https://tanstack.com/query/v5/docs/framework/react/guides/query-invalidation#query-matching-with-invalidatequeries

**Comment by SiddanthNayak** [comment]
@rithviknishad @yash-learner made the changes required.

Here's what I did:
- Reverted queryKey from `tags` to `questionnaire_tags` in `CreateQuestionnaireTagSheet.tsx`
- Changed queryKey from `tags` to `questionnaire_tags` in `QuestionnaireEditor.tsx`

This way, the key remains consistent across Questionnaire Create/Manage.

What was happening before:
- Tags were being fetched based on the queryKey `tags` in `QuestionnaireEditor.tsx` and being invalidated based on the queryKey `questionnaire_tags` after a new tag was created. This mismatch was causing the issue #13423

**Review by rithviknishad — APPROVED** [review]

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 2]
```diff
@@ -347,7 +347,7 @@ export default function QuestionnaireEditor({ id }: QuestionnaireEditorProps) {
   });
 
   const { data: availableTags, isLoading: isLoadingAvailableTags } = useQuery({
-    queryKey: ["tags", tagSearchQuery],
+    queryKey: ["questionnaire_tags", tagSearchQuery],
```
Comment (yash-learner) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]: @SiddanthNayak 

Let's use camelCase `questionnaireTags`. 

I know we can see different cases for query keys right now in codebase

Let's start using the camelCase which was decided after discussion with @rithviknishad yesterday and bought up by @AdityaJ2305

**Review by yash-learner — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/QuestionnaireEditor.tsx (hunk 2 above)
Comment (SiddanthNayak) [reply src/components/Questionnaire/QuestionnaireEditor.tsx]: @yash-learner made the changes you requested.

- Updated the key to be `questionnaireTags` in all places where questionnaire tags are being fetched.

**Review by yash-learner — APPROVED** [review]
LGTM
