### PR TITLE
Fix `PatientUsers` card | Dialog | AddUserSheet | UserSelector Overflow | Change Remove-button background | Modify Translation

### LINKED ISSUE #10158: Username Overflow and Button Hover Effect in Patient Users
**Describe the bug**
- [x] Username is overflowing from the users card in `Users` tab of [Patient Details](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/patient/b87b9165-4d1b-423e-ad14-76acf4afb0bb/users) Page

Image

- [x] There is no red-bg hover effect on `Remove` button as expected when unassigning a user from Patient

https://github.com/user-attachments/assets/7ab30cca-cb29-4130-8b89-99d46632c6f6

**To Reproduce**

 Click [here](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/patient/b87b9165-4d1b-423e-ad14-76acf4afb0bb/users) to reproduce

### PR DESCRIPTION
**Pull request by rajku-dev**
## Proposed Changes

- Fixes #10158

| Before (Please zoom in)  | After|
|-------|-----|
| image|  image|
| image|  image|
| image|  image|
| image|  image |
| image|image |
| No Tooltip |image
| No Tooltip |image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **UI Improvements**
	- Enhanced username and display name presentation with hover tooltips for better visibility.
	- Refined styling for the remove user button to improve visual clarity.
	- Simplified layout for the user information section by removing redundant classes.
	- Updated confirmation message to display the user's name in bold for better emphasis.
	- Improved tooltip functionality with configurable positioning options.

### CODE REVIEW

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
image

image

This one works, but doesn't look great.

image

**Comment by rajku-dev** [comment]
DESKTOP
image

MOBILE
image
does this look good? @Jacobjeevan

**Comment by Jacobjeevan** [comment]
> DESKTOP image
> 
> MOBILE image does this look good? @Jacobjeevan

aravindtestnurse is cutoff in the first image, but seems fine otherwise. Commit the changes though, only then can we test and confirm.

**Comment by rajku-dev** [comment]
> > DESKTOP image
> > MOBILE image does this look good? @Jacobjeevan
> 
> aravindtestnurse is cutoff in the first image, but seems fine otherwise. Commit the changes though, only then can we test and confirm.

made the changes.

**Comment by Jacobjeevan** [comment]
> > > DESKTOP image
> > > MOBILE image does this look good? @Jacobjeevan
> > 
> > 
> > aravindtestnurse is cutoff in the first image, but seems fine otherwise. Commit the changes though, only then can we test and confirm.
> 
> made the changes.

Do a self-review, check multiple device dimensions through the responsive design mode/device mode.

image

**Comment by rajku-dev** [comment]
this alignment of trash icon look better now.

before
image
after
image

**Comment by rajku-dev** [comment]
result - responsive for all viewports


https://github.com/user-attachments/assets/92b16683-610f-4537-acf9-390a7c7656ee

**Comment by Jacobjeevan** [comment]
> result - responsive for all viewports
> Recording.2025-01-31.181154.mp4

The name is still cut off.

image

image

**Comment by Jacobjeevan** [comment]
image

File: src/components/Patient/PatientDetailsTab/PatientUsers.tsx [hunk 1]
```diff
@@ -287,7 +311,7 @@ export const PatientUsers = (props: PatientProps) => {
                     <AlertDialogAction
                       data-cy="patient-user-remove-confirm-button"
                       onClick={() => removeUser(user.id)}
-                      className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
+                      className="bg-red-500 text-white hover:bg-red-600"
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientDetailsTab/PatientUsers.tsx]: Let's not make this change for now. We shouldn't be overriding styles like this anyways, instead relying on variants.

Comment (Jacobjeevan) [reply src/components/Patient/PatientDetailsTab/PatientUsers.tsx]: @rajku-dev You can use

```suggestion
                      className="cn(buttonVariants({ variant: "destructive" }))"
```
instead

Comment (rajku-dev) [reply src/components/Patient/PatientDetailsTab/PatientUsers.tsx]: made the changes as requested

**Comment by Jacobjeevan** [comment]
Adjust the text:

image

**Comment by rajku-dev** [comment]
> Adjust the text:
> 
> image

adjusted the text 👍

File: src/components/Patient/PatientDetailsTab/PatientUsers.tsx [hunk 2]
```diff
@@ -259,10 +265,26 @@ export const PatientUsers = (props: PatientProps) => {
                   imageUrl={user.profile_picture_url}
                 />
                 <div>
-                  <h3 className="text-sm font-medium text-gray-900">
-                    {formatDisplayName(user)}
+                  <h3 className="inline-flex">
+                    <Tooltip>
```
Comment (Jacobjeevan) [inline src/components/Patient/PatientDetailsTab/PatientUsers.tsx]: Let's switch to using TooltipComponent here; keeps it simpler as the component takes care of importing ToolTip, ToolTipTrigger etc.

Same below.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Patient/PatientDetailsTab/PatientUsers.tsx (hunk 2 above)
Comment (rajku-dev) [reply src/components/Patient/PatientDetailsTab/PatientUsers.tsx]: made the changes.

**Comment by rajku-dev** [comment]
fixed overflow is `AddUserSheet`  and `UserSelector` also.

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

File: src/components/Common/UserSelector.tsx [hunk 3]
```diff
@@ -69,7 +70,11 @@ export default function UserSelector({
                 name={formatName(selected)}
                 className="size-6 rounded-full"
               />
-              <span>{formatName(selected)}</span>
+              <TooltipComponent content={formatName(selected)}>
+                <p className="font-medium text-gray-900 truncate max-w-56 sm:max-w-48 md:max-w-64 lg:max-w-64 xl:max-w-36">
+                  {formatName(selected)}
+                </p>
+              </TooltipComponent>
```
Comment (rithviknishad) [inline src/components/Common/UserSelector.tsx]: let's keep the tooltip positioned below

image

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Common/UserSelector.tsx (hunk 3 above)
Comment (rajku-dev) [reply src/components/Common/UserSelector.tsx:77]: - can we customize `TooltipComponent` to accept a `side` prop, currently it doesn't support that, 
or we can use combination of `Tooltip`, `TooltipTrigger` and `TooltipContent`  as well.

image

- also do i have to reposition all tooltip or just this `UserSelector` tooltip.

Comment (rajku-dev) [reply src/components/Common/UserSelector.tsx]: made the changes as requested,

File: src/components/ui/tooltip.tsx [hunk 4]
```diff
@@ -30,7 +30,7 @@ TooltipContent.displayName = TooltipPrimitive.Content.displayName;
 const TooltipComponent = React.forwardRef<
   React.ElementRef<typeof TooltipContent>,
   React.ComponentPropsWithoutRef<typeof TooltipPrimitive.Content>
->(({ children, content, sideOffset = 4, className }, ref) => {
+>(({ children, content, sideOffset = 4, className, side }, ref) => {
   const [open, setOpen] = React.useState(false);
   return (
```
Comment (rajku-dev) [inline src/components/ui/tooltip.tsx:35]: image

**Review by rithviknishad — APPROVED** [review]
