### PR TITLE
Remove Accordion for Questionnaire Response Print Preview and Add Border around 

### LINKED ISSUE #12275: Bug:  Remove Accordion for  Questionnaire Response in Treatment Summary
**Describe*
Remove Accordion for  Questionnaire Response in Treatment Summary

**To Reproduce**

1. Go to any active encounter 
2. If there is no questionnaire response add one 
3. Click on Treatment Summary from Action list dropdown

**Screenshots**

https://github.com/user-attachments/assets/ad1eaa39-aafa-4bc6-97b4-367ac66c6b13

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #12275 
- Remove Accordion for Print Preview for questionnarieResponse
- Add border around

Screenshot 2025-05-13 at 6 24 26 PM

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Introduced a new card layout for questionnaire responses in print preview mode for clearer printing.
  - Added a print button consistently available outside of print preview mode.

- **Refactor**
  - Centralized questionnaire response rendering logic for consistency and easier maintenance.

- **Style**
  - Enhanced visual presentation in print preview for improved readability.

### CODE REVIEW

File: src/components/Facility/ConsultationDetails/QuestionnaireResponsesList.tsx [hunk 1]
```diff
@@ -271,63 +271,72 @@ function ResponseCard({
       ? properCase(structuredType.replace(/_/g, " "))
       : item.questionnaire?.title || "";
 
-  return (
+  const content = (
```
Comment (Jacobjeevan) [inline src/components/Facility/ConsultationDetails/QuestionnaireResponsesList.tsx]: Don't inline, move out as it's own component for performance/component memoization.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
