### PR TITLE
Fix: Retired options showing in picker for AD form

### LINKED ISSUE #15225: Options with Retired status showing in definition picker while creating Activity Definition
**Describe the bug**
Retired status options showing up in picker for definitions in AD create form

**To Reproduce**

1. Go to 'Activity Definition'
2. Click on 'Add Activity Definition'
3. For Observation Definition picker, options with retired status shows up.

**Expected behavior**
Only options with Active status should be visible in the picker.

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by SiddanthNayak**
## Proposed Changes

Fixes #15225 
- Filtering observation definition picker by active status
- Retired status options no longer shows up in the picker for AD form

Screenshot 2026-01-21 at 10 46 26 AM
Screenshot 2026-01-21 at 10 46 59 AM

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Bug Fixes**
  * Observation definitions list now shows only active definitions.
  * Activity definition form retrieves and displays only active observation items to reduce clutter and prevent selecting inactive items.
  * Observation definition form defaults new/edited entries to active status and uses a consistent, standardized status selector for clearer choices.

### CODE REVIEW

File: src/pages/Facility/settings/activityDefinition/ActivityDefinitionForm.tsx [hunk 1]
```diff
@@ -229,6 +230,7 @@ function ActivityDefinitionFormContent({
             facility: facilityId,
             limit: 100,
             title: observationSearch,
+            status: "active" as ObservationDefinitionStatus,
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/activityDefinition/ActivityDefinitionForm.tsx]: Hmm, we should changing it from type to enum, like we have for Specimen Definition Status. Go ahead and do that 👍

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx [hunk 2]
```diff
@@ -338,6 +338,7 @@ function ObservationDefinitionFormContent({
     } else {
       const payload: ObservationDefinitionCreateSpec = {
         ...cleanData,
+        status: ObservationDefinitionStatus.active,
```
[the remark this answers is not in the document]
Comment (SiddanthNayak) [reply src/pages/Facility/settings/observationDefinition/ObservationDefinitionForm.tsx]: resolved. accidentally added it. 

have removed the override.

**Review by nihal467 — APPROVED** [review]

File: src/types/emr/observationDefinition/observationDefinition.ts [hunk 3]
```diff
@@ -78,19 +78,15 @@ export interface ObservationDefinitionReadSpec extends BaseObservationDefinition
...
-  "active",
-  "retired",
-  "unknown",
-] as const;
-
+export enum ObservationDefinitionStatus {
+  draft = "draft",
+  active = "active",
+  retired = "retired",
+  unknown = "unknown",
```
Comment (bodhish) [inline src/types/emr/observationDefinition/observationDefinition.ts:85]: Do we need unknown 🤔

**Review by bodhish — CHANGES_REQUESTED** [review]

File: src/types/emr/observationDefinition/observationDefinition.ts (hunk 3 above)
Comment (bodhish) [reply src/types/emr/observationDefinition/observationDefinition.ts:85]: Can we make it a new issue.

Comment (yash-learner) [reply src/types/emr/observationDefinition/observationDefinition.ts:85]: image


Backend has it 🤷‍♂️ and even  FHIR https://build.fhir.org/valueset-publication-status.html

so Do we need unknown 🤔  @bodhish, @SiddanthNayak
