### PR TITLE
fix: service request tags not updating without page refresh

### LINKED ISSUE #14526: Tags are not reflecting without refresh in service req table
**Describe the bug**
Refer to the video attached, the tag's column is supposed to fill live when choosing any tag from the dropdown instead user needs to refresh the page to see the tags in the column 

https://github.com/user-attachments/assets/2e2137f1-f480-4841-9015-e72a142141af

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by atif09**
## Proposed Changes

Fixes #14526
- Restructured queryKey from `["serviceRequests", facilityId, locationId, qParams]` to `["serviceRequests", facilityId, { ...qParams, locationId }]` to consolidate parameters into a single object
- Updated all `invalidateQueries` calls to use `["serviceRequests", facilityId]` prefix for proper cache invalidation when tags are added or removed.
- Additional context if needed: N/A

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Refactor**
  * Improved service request caching and query key composition to make data fetching and invalidation more consistent across facility and encounter views.
* **Bug Fixes**
  * Corrected tag handling so current tags are consistently passed and reflected when assigning or updating tags on service requests.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/components/ServiceRequest/ServiceRequestTable.tsx [hunk 1]
```diff
@@ -109,7 +109,7 @@ export default function ServiceRequestTable({
                     currentTags={request.tags ?? []}
                     onUpdate={() => {
                       queryClient.invalidateQueries({
-                        queryKey: ["serviceRequests", facilityId, locationId],
+                        queryKey: ["serviceRequests", facilityId],
```
Comment (AdityaJ2305) [inline src/components/ServiceRequest/ServiceRequestTable.tsx:112]: why `locationId` is removed ?

Comment (atif09) [reply src/components/ServiceRequest/ServiceRequestTable.tsx:112]: removed locationId to match `queryKey` prefix pattern because query uses `["serviceRequests", facilityId, {...params}]` so invalidation needs `["serviceRequests", facilityId]` for proper cache matching

Comment (AdityaJ2305) [reply src/components/ServiceRequest/ServiceRequestTable.tsx:112]: but `["serviceRequests", facilityId, {...params}]` has prefix `["serviceRequests", facilityId]` right ? so it will invalidate this query right ?

Comment (atif09) [reply src/components/ServiceRequest/ServiceRequestTable.tsx:112]: yes, the 2 element prefix `["serviceRequests", facilityId]` will match and invalidate `["serviceRequests", facilityId, {...params}]`
which ensures tags update immediately across all service request views

**Comment by atif09** [comment]
Also @AdityaJ2305 
ik i said I would attach screenshots/videos to compare the BEFORE  and AFTER in the PR but i didn't because, when I created a new service request (since i didn't have one), and clicked on `Add Tag` button, i wasnt able to see any tags

So then, I tried to create new tags in the `Tag Config` section but no credential (not even the facility admin) allowed me to create any tags for service requests (if theres another way, please let me know)

So ultimately I wasn't able to confirm it through the UI but I've followed the guidelines given under the issue and made the changes according to that

File: src/components/ServiceRequest/ServiceRequestTable.tsx (hunk 1 above)
Comment (AdityaJ2305) [reply src/components/ServiceRequest/ServiceRequestTable.tsx:112]: @atif09  👆  you haven't pushed the changes

Comment (atif09) [reply src/components/ServiceRequest/ServiceRequestTable.tsx:112]: hi @AdityaJ2305, may i know what changes you're referring to? i double checked my local branch and the changes we have discussed so far are all present in the commit history

Comment (AdityaJ2305) [reply src/components/ServiceRequest/ServiceRequestTable.tsx:112]: locationId needs to be added here

Comment (AdityaJ2305) [inline src/components/ServiceRequest/ServiceRequestTable.tsx:112]: ☝️

Comment (atif09) [reply src/components/ServiceRequest/ServiceRequestTable.tsx:112]: noted, should i add locationId conditionally since its optional like this 
`queryKey: locationId 
  ? ["serviceRequests", facilityId, { locationId }]
  : ["serviceRequests", facilityId]`
  
 so that this way it works for both location based lists and encounter based lists

**Review by nihal467 — CHANGES_REQUESTED** [review]
PR functionality is good. Add a playwright test to check the same changes

**Comment by atif09** [comment]
noted, will commit the changes as soon as possible 
> PR functionality is good. Add a playwright test to check the same changes
