### PR TITLE
Fix: Minor Questionnaire Edit bugs

### LINKED ISSUE #11275: Minor bugs in Questionnaire Edit
1. Updating the slug doesn't redirect to the new slug URL
2. Question index in the error starts with 0 Value Error: 'questions.3.questions.0.questions.0'
3. Clicking on a nested question in the navigation doesn't expand the parent question

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes  #11275
- Navigate to new slug id edit form when slug id is edited
- Open Parent question when children or nested question is selected from the navigation
- Hover effect was missing for children question in navigation bar so added that (not in video since added in 2nd commit 😅 )

@ohcnetwork/care-fe-code-reviewers

1st Bug (Sovled) 

https://github.com/user-attachments/assets/29a9fbe3-aba3-4a25-ae74-3bd55cc4c7e9

3rd Bug (Solved)

https://github.com/user-attachments/assets/c9c2ea50-ece8-4c43-8a61-5571597c2bab

2nd bug
Screenshot 2025-04-14 at 3 25 26 PM

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
	- After saving a questionnaire, users are now seamlessly redirected to the appropriate edit page for a smoother workflow.
	- The scrolling experience has been enhanced: when targeting sub-questions, the related section expands if needed before smoothly scrolling, ensuring that all content is clearly visible.
	- New success and error messages for questionnaire operations have been added to improve user feedback.
- **Bug Fixes**
	- Improved error handling for questionnaire creation and updates, providing detailed error messages to users, enhancing user feedback during operations.

### CODE REVIEW

**Comment by amjithtitus09** [comment]
@AdityaJ2305 Can you post screenshot of the validation error displayed?

**Comment by AdityaJ2305** [comment]
Screenshot 2025-03-20 at 11 39 19 PM
@amjithtitus09

**Comment by amjithtitus09** [comment]
@AdityaJ2305 What if there are multiple choice questions? Shouldn't it indicate which question failed the validation in some way?

**Comment by AdityaJ2305** [comment]
@amjithtitus09, wouldn’t this make the code more complex with multiple if-else conditions? Should I reach out to Prafful to check how backend errors are handled?

**Comment by amjithtitus09** [comment]
> @amjithtitus09, wouldn’t this make the code more complex with multiple if-else conditions? Should I reach out to Prafful to check how backend errors are handled?

@AdityaJ2305 Which part exactly? The error includes the index of the question failing the validation. Won't that be useful?

```
{
    "errors": [
        {
            "type": "value_error",
            "loc": [
                "questions",
                1
            ],
            "msg": "Value error, Either answer options or a value set must be provided for choice type questions",
            "input": {
                "id": "a75d5aa0-5d03-49d6-8642-fa4677b9e75b",
                "link_id": "2",
                "text": "New Question",
                "type": "choice",
                "questions": [],
                "enable_when": [
                    {
                        "question": "",
                        "operator": "equals",
                        "answer": ""
                    }
                ]
            },
            "ctx": {
                "error": "Either answer options or a value set must be provided for choice type questions"
            },
            "url": "https://errors.pydantic.dev/2.9/v/value_error"
        }
    ]
}
```

**Comment by AdityaJ2305** [comment]
> > @amjithtitus09, wouldn’t this make the code more complex with multiple if-else conditions? Should I reach out to Prafful to check how backend errors are handled?
> 
> @AdityaJ2305 Which part exactly? The error includes the index of the question failing the validation. Won't that be useful?
> 
> ```
> {
>     "errors": [
>         {
>             "type": "value_error",
>             "loc": [
>                 "questions",
>                 1
>             ],
>             "msg": "Value error, Either answer options or a value set must be provided for choice type questions",
>             "input": {
>                 "id": "a75d5aa0-5d03-49d6-8642-fa4677b9e75b",
>                 "link_id": "2",
>                 "text": "New Question",
>                 "type": "choice",
>                 "questions": [],
>                 "enable_when": [
>                     {
>                         "question": "",
>                         "operator": "equals",
>                         "answer": ""
>                     }
>                 ]
>             },
>             "ctx": {
>                 "error": "Either answer options or a value set must be provided for choice type questions"
>             },
>             "url": "https://errors.pydantic.dev/2.9/v/value_error"
>         }
>     ]
> }
> ```
@amjithtitus09, wouldn’t this affect error messages for other fields? I was thinking in that direction. Or should I add an if-else condition to check if the value error includes “question text” and handle it accordingly?

**Comment by amjithtitus09** [comment]
> > > @amjithtitus09, wouldn’t this make the code more complex with multiple if-else conditions? Should I reach out to Prafful to check how backend errors are handled?
> > 
> > 
> > @AdityaJ2305 Which part exactly? The error includes the index of the question failing the validation. Won't that be useful?
> > ```
> > {
> >     "errors": [
> >         {
> >             "type": "value_error",
> >             "loc": [
> >                 "questions",
> >                 1
> >             ],
> >             "msg": "Value error, Either answer options or a value set must be provided for choice type questions",
> >             "input": {
> >                 "id": "a75d5aa0-5d03-49d6-8642-fa4677b9e75b",
> >                 "link_id": "2",
> >                 "text": "New Question",
> >                 "type": "choice",
> >                 "questions": [],
> >                 "enable_when": [
> >                     {
> >                         "question": "",
> >                         "operator": "equals",
> >                         "answer": ""
> >                     }
> >                 ]
> >             },
> >             "ctx": {
> >                 "error": "Either answer options or a value set must be provided for choice type questions"
> >             },
> >             "url": "https://errors.pydantic.dev/2.9/v/value_error"
> >         }
> >     ]
> > }
> > ```
> 
> @amjithtitus09, wouldn’t this affect error messages for other fields? I was thinking in that direction. Or should I add an if-else condition to check if the value error includes “question text” and handle it accordingly?

@AdityaJ2305 Wouldn't posting an example error of "other fields" provide more context to what you're asking given that I've already pasted one above? Using loc and msg is what I was referring to.

**Comment by AdityaJ2305** [comment]
@amjithtitus09 , I'll give a try and let you know

**Comment by AdityaJ2305** [comment]
@amjithtitus09 Ready for review and testing 
Screenshot 2025-03-24 at 3 15 40 PM

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 1]
```diff
@@ -603,27 +603,75 @@ export default function QuestionnaireEditor({ id }: QuestionnaireEditorProps) {
...
+            ) {
+              questionPath.push(`Question ${Number(er.loc[i + 1]) + 1}`);
+            }
+          }
+          fieldPath = questionPath.join(" > ");
+        }
+
+        const message = fieldPath ? `Error in ${fieldPath}: ${er.msg}` : er.msg;
+
+        toast.error(message);
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]: make this s a reusable fn?

why duplicate this logic?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/QuestionnaireEditor.tsx (hunk 1 above)
Comment (AdityaJ2305) [reply src/components/Questionnaire/QuestionnaireEditor.tsx]: Done

**Comment by AdityaJ2305** [comment]
@rithviknishad , could you review and update the label

**Comment by AdityaJ2305** [comment]
Hey Team, Could you please look into this PR , It has more merge branch commits than commit for changes 😅 

cc: @rithviknishad @amjithtitus09 @Jacobjeevan

**Review by rithviknishad — APPROVED** [review]

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 2]
```diff
@@ -256,28 +287,28 @@ export default function QuestionnaireEditor({ id }: QuestionnaireEditorProps) {
...
+    }),
     onSuccess: (data: QuestionnaireDetail) => {
       toast.success("Questionnaire created successfully");
       queryClient.invalidateQueries({ queryKey: ["questionnaireDetail", id] });
       navigate(`/admin/questionnaire/${data.slug}/edit`);
     },
-    onError: (_error) => {
-      toast.error("Failed to create questionnaire");
-    },
+    onError: (error) => handleOnErrors(error, "Failed to Create Questionnaire"),
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]: translation?

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 3]
```diff
@@ -256,28 +287,28 @@ export default function QuestionnaireEditor({ id }: QuestionnaireEditorProps) {
...
-    onSuccess: () => {
+    onSuccess: (data: QuestionnaireDetail) => {
       toast.success("Questionnaire updated successfully");
+      navigate(`/admin/questionnaire/${data.slug}/edit`);
       queryClient.invalidateQueries({ queryKey: ["questionnaireDetail", id] });
     },
-    onError: (_error) => {
-      toast.error("Failed to update questionnaire");
-    },
+    onError: (error) => handleOnErrors(error, "Failed to Update Questionnaire"),
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]: same here

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
image

- show the nested question in a . format, for example rather than showing Question 2 > Question 1 > Question 1 , show them as 2.1.1

**Comment by AdityaJ2305** [comment]
>  show the nested question in a . format, for example rather than showing Question 2 > Question 1 > Question 1 , show them as 2.1.1

@nihal467, wouldn’t this still be a bit confusing? The main goal here is to make the error message more readable for the user. moreover, backend is returning similar message (just index starts with 0 instead of 1 and question text)
Screenshot 2025-04-08 at 6 14 27 PM

**Comment by bodhish** [comment]
@AdityaJ2305 Can't the UI make sure that these validations are done before we make the request? 🤔

**Comment by AdityaJ2305** [comment]
@bodhish 
Screenshot 2025-04-12 at 2 05 55 AM

**Comment by AdityaJ2305** [comment]
@bodhish, can I take that as a separate PR/issue? Already shared the reason in the screenshot 😅 Also, there is hritesh pr hich is adding zod validations to editor for codes purpose once that complete then I think i can take it up .
PS:  this PR is almost hitting its 1-month birthday on 14th April

**Comment by AdityaJ2305** [comment]
Screenshot 2025-04-14 at 3 25 26 PM

@nihal467 , made the changes
