### PR TITLE
Replaced ButtonV2's with Button in entire codebase

### LINKED ISSUE #9710: Uniform button variant in patient details page tabs and replace ButtonV2's with Button in entire codebase
We have different variants of buttons in each tab. A uniform variant would be more appropiate

Image

Image

Image

Image

### LINKED ISSUE #9714: Replace loading text with care loading icon
**Describe the bug**
Display care loading icon on clicking organization in homepage, and users in facility, 

**To Reproduce**

1. Go to  https://care.ohc.network/
2. Click on click on Kerala 
3. We can see the text: Loading.. instead of care icon

**Expected behavior**
Care Loading icon should be displayed

**Screenshots**
Image

Expected:

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.

### LINKED ISSUE #9718: Button misalignment.
**Describe the bug**
Create organization button not aligned properly on mobile screens.

**To Reproduce**

1. Go to 'Organization'
2. See error

**Expected behavior**
It should be aligned properly.

**Screenshots**
Image

**Desktop (please complete the following information):**

**Smartphone **

- Device: [e.g. iPhone12 pro]

**Additional context**

### PR DESCRIPTION
**Pull request by Mahendar0701**
## Proposed Changes

- Fixes #9710 
- Fixes #9718 
- Replaced Buttonv2 with Button and removed ButtonV2
- Removed Chip
- Button misalignment fixed
- uniform variants in Patients detail page 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Release Notes

- **Localization**
  - Added new localization key for patient updates: "Add Patient Updates"

- **UI Components**
  - Replaced `ButtonV2` with a new `Button` component across multiple components
  - Added new button variants: `warning` and `alert`
  - Updated button styling and internationalization support

- **Button Variants**
  - Changed some button variants from `danger` to `destructive`
  - Introduced more consistent button styling across the application

- **Layout Improvements**
  - Refined button and component alignments in various screens
  - Improved responsive design for buttons and layout elements

- **Deprecation**
  - Removed `ButtonV2` component and associated type definitions
  - Deprecated `Chip` component in favor of `Badge`

### CODE REVIEW

File: src/components/Common/AuthorizedButton.tsx [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+      {({ isAuthorized }) => (
+        <Button {...props} disabled={props.disabled || !isAuthorized}>
+          {props.children}
+        </Button>
+      )}
+    </AuthorizedChild>
+  );
+};
+
+export default AuthorizedButton;
```
Comment (rithviknishad) [inline src/components/Common/AuthorizedButton.tsx]: Delete this. This was recently deleted as it was unnecessary. Let's not maintain weird things when there are "normal" approaches possible to achieve the same what this used to do. Do not bring new usages back again.

File: src/components/ui/button.tsx
Comment (rithviknishad) [inline src/components/ui/button.tsx:1]: Do not change anything in this file. It's hard to maintain when we want to update the shadcn's button through cli

File: src/components/ui/button.tsx [hunk 2]
```diff
@@ -50,6 +69,10 @@ export interface ButtonProps
   asChild?: boolean;
 }
 
+export interface CommonButtonProps extends ButtonProps {
+  label?: string;
+}
+
```
Comment (rithviknishad) [inline src/components/ui/button.tsx]: I see 0 advantages on this.

File: src/CAREUI/display/Callout.tsx [hunk 3]
```diff
@@ -2,7 +2,7 @@ import React from "react";
 
 import { cn } from "@/lib/utils";
 
-import { ButtonVariant } from "@/components/Common/ButtonV2";
+import { ButtonVariant } from "@/components/ui/button";
```
Comment (rithviknishad) [inline src/CAREUI/display/Callout.tsx]: Callout is not a button. I'd rather define fresh variants for this instead of reusing ButtonVariant. Let's not import unrelated things even though they may seem similar.

File: src/components/Users/UserAvatar.tsx [hunk 4]
```diff
@@ -99,21 +101,32 @@ export default function UserAvatar({
...
-                {t("change_avatar")}
-              </ButtonV2>
+              {!showAvatarEdit(authUser, userData) ? (
+                <TooltipComponent
+                  content={t("edit_avatar_permission_error")}
+                  className="w-full"
+                >
+                  <Button
+                    variant="white"
+                    onClick={(_) => setEditAvatar(!editAvatar)}
```
Comment (rithviknishad) [inline src/components/Users/UserAvatar.tsx]: You could ignore `_` if you ain't gonna use it anyways.

```suggestion
                    onClick={() => setEditAvatar(!editAvatar)}
```

File: src/components/Users/UserResetPassword.tsx [hunk 5]
```diff
@@ -192,16 +192,16 @@ export default function UserResetPassword({
...
     <div className="mb-4 flex justify-start">
-      <ButtonV2
+      <Button
+        variant="outline_primary"
         onClick={() => setIsEditing(!isEditing)}
         type="button"
         id="change-edit-password-button"
-        className="flex items-center gap-2 rounded-sm border border-gray-100 bg-white px-3 py-1.5 text-sm text-[#009D48] shadow-sm hover:bg-gray-50"
-        shadow={false}
+        className="flex items-center gap-2 px-3 py-1.5  shadow-sm "
```
Comment (rithviknishad) [inline src/components/Users/UserResetPassword.tsx]: I don't recommend applying such classes to the button. Especially do not override shadow's and all. Let's stick with what the common designs configured by variant provides.

As for the spacing between the icon, use `ml-2` in the icon's classname instead

```suggestion
```

File: src/components/Users/UserSummary.tsx [hunk 6]
```diff
@@ -172,17 +172,17 @@ export default function UserSummaryTab({
               </div>
             </div>
             <div className="w-3/4">
-              <ButtonV2
+              <AuthorizedButton
```
Comment (rithviknishad) [inline src/components/Users/UserSummary.tsx]: Use `AuthorizedChild` instead or refactor to write the permissions logic to a `permissions.ts` (the newer way we started following recently and use that fn. here along with `useAuthUser`

File: src/hooks/useFileManager.tsx [hunk 7]
```diff
@@ -384,7 +394,13 @@ export default function useFileManager(
           ))}
         </div>
         <div className="mt-10 flex justify-end">
-          <Cancel onClick={(_) => setArchiveDialogueOpen(null)} />
+          <Button
+            type="button"
+            variant="outline"
+            onClick={(_) => setArchiveDialogueOpen(null)}
```
Comment (rithviknishad) [inline src/hooks/useFileManager.tsx]: adjust this in all other places too...

```suggestion
            onClick={() => setArchiveDialogueOpen(null)}
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]
lgtm, some minor changes

File: src/components/ui/button.tsx
Comment (Mahendar0701) [reply src/components/ui/button.tsx:1]: @rithviknishad  I have added `warning ` and alert `variant`  in `button.tsx` as they are being use in 4 files. Should i keep them or remove it from `button.tsx`? if removed should i use className to make variant in corresponding buttons?

**Comment by Mahendar0701** [comment]
@rithviknishad   I have added `warning ` and `alert ` variant  in `button.tsx` as they are being used in 4 files. Should i keep them or remove it from `button.tsx`? if removed should i use className to make variant in corresponding buttons?

**Comment by rithviknishad** [comment]
> @rithviknishad I have added `warning ` and `alert ` variant in `button.tsx` as they are being used in 4 files. Should i keep them or remove it from `button.tsx`? if removed should i use className to make variant in corresponding buttons?

yup, that should be fine

File: src/CAREUI/display/PopupModal.tsx
Comment (rithviknishad) [inline src/CAREUI/display/PopupModal.tsx:1]: Delete this file too, not used anywhere currently.

**Comment by Mahendar0701** [comment]
> > @rithviknishad I have added `warning ` and `alert ` variant in `button.tsx` as they are being used in 4 files. Should i keep them or remove it from `button.tsx`? if removed should i use className to make variant in corresponding buttons?
> 
> yup, that should be fine

I should keep alert and warning variants in button.tsx right? 👀

File: src/components/Common/Menu.tsx [hunk 8]
```diff
@@ -3,13 +3,14 @@ import { DetailedHTMLProps, HTMLAttributes, ReactNode } from "react";
...
 
-import { ButtonSize, ButtonVariant } from "@/components/Common/ButtonV2";
-
 import { useIsAuthorized } from "@/hooks/useIsAuthorized";
 
 import { Anyone, AuthorizedElementProps } from "@/Utils/AuthorizeFor";
 import { classNames } from "@/Utils/utils";
 
+type ButtonVariant = "primary" | "secondary" | "danger" | "warning";
+type ButtonSize = "small" | "default" | "large";
```
Comment (rithviknishad) [inline src/components/Common/Menu.tsx]: let's remove these. and hardcode it directly and remove it from props too. Also mark the Dropdown Menu component as deprecated in jsdoc comments. The only usage for this is the `ExportMenu` component right now, which we can rebuild using shadcn's dropdown eventually in a later PR.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by rithviknishad** [comment]
> I should keep alert and warning variants in button.tsx right? 👀

yup

File: src/components/Common/ConfirmDialog.tsx [hunk 9]
```diff
@@ -1,6 +1,21 @@
...
+  | "primary"
+  | "secondary"
+  | "ghost"
+  | "link"
+  | "outline_primary"
+  | "primary_gradient"
+  | "white"
+  | "warning"
+  | "alert";
+
```
Comment (rithviknishad) [inline src/components/Common/ConfirmDialog.tsx]: let's not redefine button variants here. here the situation is different from callout since callout's variant prop defined how the callout would look like. but here the variant prop directly is passed to the submit button's prop, which is "ButtonVariant" itself. import it instead

File: src/components/Common/AvatarEditModal.tsx [hunk 10]
```diff
@@ -255,7 +256,7 @@ const AvatarEditModal = ({
                 <div>
                   <label
                     id="upload-cover-image"
-                    className="button-size-default button-shape-square button-primary-default inline-flex h-min w-full cursor-pointer items-center justify-center gap-2 whitespace-pre font-medium shadow outline-offset-1 transition-all duration-200 ease-in-out enabled:hover:shadow-md disabled:cursor-not-allowed disabled:bg-secondary-200 disabled:text-secondary-500"
+                    className="button-size-default rounded-md bg-primary-700 text-white  hover:bg-primary-700/90 dark:bg-primary-100 dark:text-primary-900 dark:hover:bg-primary-100/90 inline-flex h-min w-full cursor-pointer items-center justify-center gap-2 whitespace-pre font-medium shadow outline-offset-1 transition-all duration-200 ease-in-out enabled:hover:shadow-md disabled:cursor-not-allowed disabled:bg-secondary-200 disabled:text-secondary-500"
                   >
                     <CareIcon icon="l-cloud-upload" className="text-lg" />
                     {t("upload_an_image")}
```
Comment (rithviknishad) [inline src/components/Common/AvatarEditModal.tsx]: switch this to button instead.

File: src/components/Common/Menu.tsx (hunk 8 above)
Comment (rithviknishad) [reply src/components/Common/Menu.tsx]: let's also remove the `button-**` classes defined in CAREUI.css file which originally belonged to `ButtonV2`'s implementation. Do ensure it's not used anywhere else and delete it. If used else where, do remove them from there too.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/ui/button.tsx [hunk 11]
```diff
@@ -44,6 +48,19 @@ const buttonVariants = cva(
...
+  | "outline"
+  | "secondary"
+  | "destructive"
+  | "primary_gradient"
+  | "ghost"
+  | "link"
+  | "white"
+  | "alert"
+  | "warning"
+  | "outline_primary";
```
Comment (Mahendar0701) [inline src/components/ui/button.tsx:62]: Added type `ButtonVariant `  in `button.tsx` as this can be imported in [src/components/Common/ConfirmDialog.tsx](https://github.com/ohcnetwork/care_fe/pull/9736/files/bf327a09d9c6178f83126fe636c160dbe91def94#diff-cedca62bbb74627f3748c68b30a53d4302b3cc70196439191ef952b08e1d2ad6)

**Review by rithviknishad — CHANGES_REQUESTED** [review]
you missed removing these

image

File: src/CAREUI/interactive/FiltersSlideover.tsx [hunk 12]
```diff
@@ -35,18 +33,13 @@ export default function FiltersSlideover({
...
-              onClick={onClear}
-              id="clear-filter"
-            >
+            <Button variant="warning" onClick={onClear} id="clear-filter">
               <CareIcon icon="l-filter-slash" className="text-lg" />
               <span>{t("clear")}</span>
-            </ButtonV2>
-            <ButtonV2 ghost onClick={onApply} id="apply-filter">
+            </Button>
+            <Button variant="alert" onClick={onApply} id="apply-filter">
```
Comment (rithviknishad) [inline src/CAREUI/interactive/FiltersSlideover.tsx]: This was primary, why was it changed to alert?

```suggestion
            <Button variant="primary_outline" onClick={onApply} id="apply-filter">
```

File: src/CAREUI/interactive/FiltersSlideover.tsx [hunk 13]
```diff
@@ -35,18 +33,13 @@ export default function FiltersSlideover({
         <div className="flex items-center justify-between">
           <span className="text-lg font-bold">{t("filters")}</span>
           <div className="mr-2 flex items-center justify-end gap-1">
-            <ButtonV2
-              variant="danger"
-              ghost
-              onClick={onClear}
-              id="clear-filter"
-            >
+            <Button variant="warning" onClick={onClear} id="clear-filter">
```
Comment (rithviknishad) [inline src/CAREUI/interactive/FiltersSlideover.tsx]: let's keep it as ghost 
```suggestion
            <Button variant="ghost" onClick={onClear} id="clear-filter">
```

**Comment by Mahendar0701** [comment]
> you missed removing these
> 
> image

@rithviknishad Done

File: src/components/Common/AvatarEditModal.tsx [hunk 14]
```diff
@@ -253,49 +254,59 @@ const AvatarEditModal = ({
...
                 <div>
-                  <label
+                  <Button
                     id="upload-cover-image"
-                    className="button-size-default button-shape-square button-primary-default inline-flex h-min w-full cursor-pointer items-center justify-center gap-2 whitespace-pre font-medium shadow outline-offset-1 transition-all duration-200 ease-in-out enabled:hover:shadow-md disabled:cursor-not-allowed disabled:bg-secondary-200 disabled:text-secondary-500"
+                    variant="primary"
+                    type="button"
+                    onClick={() =>
+                      document.getElementById("file-input")?.click()
+                    }
```
Comment (rithviknishad) [inline src/components/Common/AvatarEditModal.tsx]: have you tried using asChild approach instead?

File: src/components/Patient/PatientDetailsTab/patientUpdates.tsx [hunk 15]
```diff
@@ -24,7 +24,10 @@ export const Updates = (props: PatientProps) => {
         <Link
           href={`/facility/${facilityId}/patient/${patientId}/questionnaire`}
         >
-          <Button>Add Patient Updates</Button>
+          <Button variant="outline_primary">
+            <CareIcon icon="l-plus" className="mr-2" />
+            {t("add_patient_updates")}
+          </Button>
         </Link>
```
Comment (rithviknishad) [inline src/components/Patient/PatientDetailsTab/patientUpdates.tsx]: Shouldn't this be composed in reverse?

https://ui.shadcn.com/docs/components/button

image

File: src/components/Common/AvatarEditModal.tsx (hunk 14 above)
Comment (Mahendar0701) [reply src/components/Common/AvatarEditModal.tsx]: @rithviknishad  even after using asChild still we need to keep onclick event to trigger file input, without that the input is not triggering . is this acceptable?

```js
                <Button
                    id="upload-cover-image"
                    variant="primary"
                    type="button"
                    asChild
                    onClick={() =>
                      document.getElementById("file-input")?.click()
                    }
                  >
                    <div className="cursor-pointer">
                      <CareIcon icon="l-cloud-upload" className="text-lg" />
                      {t("upload_an_image")}
                      <input
                        id="file-input"
                        title="changeFile"
                        type="file"
                        accept="image/*"
                        className="hidden"
                        onChange={onSelectFile}
                      />
                    </div>
                  </Button>
  ```

File: src/components/Patient/PatientDetailsTab/patientUpdates.tsx (hunk 15 above)
Comment (Mahendar0701) [reply src/components/Patient/PatientDetailsTab/patientUpdates.tsx]: yup

File: src/components/Common/AvatarEditModal.tsx [hunk 16]
```diff
@@ -258,20 +258,23 @@ const AvatarEditModal = ({
...
-                      id="file-input"
-                      title="changeFile"
-                      type="file"
-                      accept="image/*"
-                      className="hidden"
-                      onChange={onSelectFile}
-                    />
+                    <div className="cursor-pointer">
+                      <CareIcon icon="l-cloud-upload" className="text-lg" />
+                      {t("upload_an_image")}
```
Comment (rithviknishad) [inline src/components/Common/AvatarEditModal.tsx]: the reason why i suggested `asChild` was, you could skip doing document.getElementBy id by:

wrap this in <Label /> and pass htmlFor and drop `onClick` doing document.getElementById thing.

**Review by rithviknishad — COMMENTED** [review]
lgtm, last thing

File: src/components/Common/AvatarEditModal.tsx (hunk 16 above)
Comment (Mahendar0701) [reply src/components/Common/AvatarEditModal.tsx]: Done , wrapped input inside label

**Review by rithviknishad — APPROVED** [review]
Yay! We are now one step towards cleaner codebase...

**Comment by Mahendar0701** [comment]
Hey @rithviknishad i want to work on further cleaning up of code base. 

We have 10 deprecated utilities such as Notification.Error, useTanStackQueryInstead, CarePatientTokenKey and others.

Please assign some of them to me if needed.

**Comment by rithviknishad** [comment]
go ahead and handle notification first 🚀
