### PR TITLE
Resolved crashing Edit Triage page

### LINKED ISSUE #4240: Edit Triage form is crashing
**Describe the bug**
The `Entry Date`  is being entered in an invalid format which is causing the page to crash

**To Reproduce**
Steps to reproduce the behaviour:
https://care.coronasafe.in/facility/caaab916-e877-4153-a0a4-d0afc69f4c1a/triage/7420e8a2-e954-4506-8d43-f230be57b6c0

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #4240 
Resolved the invalid `entry_date` format in the form.
http://localhost:4000/facility/caaab916-e877-4153-a0a4-d0afc69f4c1a/triage/7420e8a2-e954-4506-8d43-f230be57b6c0
image

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

File: src/Components/Facility/TriageForm.tsx [hunk 1]
```diff
@@ -75,12 +75,17 @@ export const TriageForm = (props: triageFormProps) => {
           getTriageDetails({ facilityId: facilityId, id: id })
         );
         if (!status.aborted && res && res.data) {
+          // getting the entry date in new Date() format
+          const month = parseInt(res.data.entry_date.substring(5, 7)) - 1;
+          const date = parseInt(res.data.entry_date.substring(8, 10));
+          const year = parseInt(res.data.entry_date.substring(0, 4));
+          const entryDate = new Date();
+          entryDate.setFullYear(year, month, date);
+
```
Comment (khavinshankar) [inline src/Components/Facility/TriageForm.tsx]: @Pranshu1902 why not use the formatDate function from utils?

Comment (Pranshu1902) [reply src/Components/Facility/TriageForm.tsx]: @khavinshankar how about now, I found a way to do it with `moment`

**Review by khavinshankar — APPROVED** [review]
