### PR TITLE
fixing back button for camera asset

### LINKED ISSUE #9233: Back Button is not working proper in the camera configuration page
**Describe the bug**

The back button on the Camera Configuration page does not take the user to the previously accessed page.

**To Reproduce**

1. Go to the Assets section.
2. Click on any camera asset.
3. Click on the Configuration button, then click on the back button in the breadcrumbs.

**Expected behavior**

The back button in the breadcrumbs should navigate the user to the previously accessed page.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by SwanandBhuskute**
## Proposed Changes

- Fixes #9233
- removed useEffect hook that was adding query param in link 
- firstBed is fallback for selectedAssetBed and selectedUnlinkedBed

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Introduced a suggestion display feature in the text input field, allowing users to select suggestions to populate the field.
- **Enhancements**
	- Improved styling of the input field with added right padding for better layout.
	- Simplified logic for managing selected bed ID in the camera configuration component.
- **Bug Fixes**
	- Retained error handling for input constraints, ensuring consistent validation.

### CODE REVIEW

File: src/components/Form/FormFields/TextFormField.tsx [hunk 1]
```diff
@@ -90,7 +90,7 @@ const TextFormField = forwardRef((props: TextFormFieldProps, ref) => {
         ref={ref as React.Ref<HTMLInputElement>}
         id={field.id}
         className={classNames(
-          "cui-input-base peer",
+          "cui-input-base peer pr-9",
```
Comment (rithviknishad) [inline src/components/Form/FormFields/TextFormField.tsx]: revert this change as it's unrelated to this pr
```suggestion
          "cui-input-base peer",
```

**Review by rithviknishad — APPROVED** [review]
