### PR TITLE
Fix Responsive issue for Questionnaire Editor 

### LINKED ISSUE #13062: Responsive issue for Questionnaire Editor
## Describe 

issue due to this PR: https://github.com/ohcnetwork/care_fe/pull/12776

Image
Image

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #13062 

https://github.com/user-attachments/assets/9b47c11e-e197-453c-b2a8-da89b204dbbd

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **Style**
  * Updated the layout and visibility of side panels in the questionnaire editor for improved responsiveness across screen sizes. Sidebars and property panels now adjust their display based on smaller screen breakpoints, enhancing usability on mobile and tablet devices.

### CODE REVIEW

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
Hmm, let's adjust the tablet view as well:

image

**Comment by AdityaJ2305** [comment]
> Hmm, let's adjust the tablet view as well:
> 
> image

Should navigation bar be hidden for tablet view like it is hidden for mobile ? 🤔

**Comment by AdityaJ2305** [comment]
@Jacobjeevan 
I have checked with this [site](https://gs.statcounter.com/screen-resolution-stats/tablet/india) and tested on first two resolutions and it is working fine for them. could you give a check as well ?

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
the issue is already solved

**Comment by AdityaJ2305** [comment]
We can reopen this pr since it already solved the updated issue

**Comment by Jacobjeevan** [comment]
Be sure to discard any changes that are not relevant 👍

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 1]
```diff
@@ -936,79 +939,75 @@ export default function QuestionnaireEditor({ id }: QuestionnaireEditorProps) {
...
+                          </div>
+                        )}
+                      </div>
+                    );
+                  })}
+                </nav>
+              </CardContent>
+            </Card>
+            {isMobile && (
+              <div className="space-y-4 md:hidden">
```
Comment (AdityaJ2305) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]:
```suggestion
              <div className="space-y-4">
```

**Comment by AdityaJ2305** [comment]
https://github.com/user-attachments/assets/9b47c11e-e197-453c-b2a8-da89b204dbbd

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
