### PR TITLE
Fix: Hide the zone and milli seconds in the time date component of questionnaire

### LINKED ISSUE #12565: Hide the zone and time in the date component of questionnaire
**Describe the bug**

Hide the time in the date component of the questionnaire

**To Reproduce**

1. Go to patient encounter
2. Fill the Feedback form (NCG-nurse)
3. submit it 

**Expected behavior**

show only the date in the date component in questionnaire

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by perpetrator1**
## Proposed Changes

- Fixes #12565

This pull request refines the `formatValue` function in `src/components/Facility/ConsultationDetails/QuestionnaireResponsesList.tsx` to improve date formatting, simplify numeric value handling, and enhance boolean value interpretation.

### Improvements to date formatting:
* Updated the `dateTime` case to include a specific format (`"hh:mm A; DD/MM/YYYY"`) for better readability.
* Added a new `date` case to handle date values separately using `formatDateTime`.

### Simplification of numeric value handling:
* Removed redundant type checks for `decimal` and `integer` cases, simplifying the logic to directly convert values to strings.

### Enhanced boolean value interpretation:
* Adjusted the `boolean` case to correctly interpret both `true` (boolean) and `"true"` (string) as `t("yes")`.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved formatting of questionnaire response values, including enhanced handling of date and date-time types for clearer and more consistent display.
	- Enhanced validation and serialization of date and date-time responses during questionnaire submission to ensure accurate and simplified date formatting.
- **New Features**
	- Added support for a distinct "date" response type in questionnaires, enabling users to submit and view date-only values separately from date-time entries.

### CODE REVIEW

File: src/components/Facility/ConsultationDetails/QuestionnaireResponsesList.tsx [hunk 1]
```diff
@@ -58,15 +58,17 @@ export function formatValue(
...
+      return formatDateTime(value.toString());
     case "choice":
       return properCase(value.toString());
     case "decimal":
     case "integer":
-      return typeof value === "number" ? value.toString() : value.toString();
+      return value.toString();
     case "boolean":
-      return value === "true" ? t("yes") : t("no");
+      return value === true || value === "true" ? t("yes") : t("no");
```
Comment (Jacobjeevan) [inline src/components/Facility/ConsultationDetails/QuestionnaireResponsesList.tsx]: don't change this, it's being reworked anyways.

**Review by sindhureddy-6 — COMMENTED** [review]
please check the related merge checklist.

**Review by Jacobjeevan — DISMISSED** [review]
Date question is currently sending timezone to BE, so modify it accordingly 👍

**Comment by perpetrator1** [comment]
It should be fine now

**Comment by nihal467** [comment]
LGTM

File: src/components/Questionnaire/QuestionnaireForm.tsx [hunk 2]
```diff
@@ -659,7 +659,17 @@ export function QuestionnaireForm({
...
               question_id: response.question_id,
               values: response.values.map((value) => {
-                if (value.type === "dateTime" && value.value) {
+                if (value.type === "date" && value.value) {
+                  const date = new Date(value.value);
+                  if (isNaN(date.getTime())) {
+                    return { ...value, value: "" };
+                  }
+                  const formattedDate = date.toISOString().split("T")[0];
+                  return {
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireForm.tsx]: you are not allowed to perform `toISOString().split('T')`. this will lead to incorrect dates in edge cases where timezone is different!

use formatting utilities instead!

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/QuestionnaireForm.tsx (hunk 2 above)
Comment (Jacobjeevan) [reply src/components/Questionnaire/QuestionnaireForm.tsx]: Fixed 👍

**Review by rithviknishad — APPROVED** [review]
