### PR TITLE
fix: cancel plan button to delete the locations of the Encounter section.

### LINKED ISSUE #10850: Add Deletion Support for Manage Location in Encounter
Below items will be taken as a separate issue, so conditionally approving it

- Add a delete option in the manage location sidebar, to remove unwanted data

_Originally posted by @nihal467 in https://github.com/ohcnetwork/care_fe/issues/10810#issuecomment-2687972491_

### PR DESCRIPTION
**Pull request by YourBroCode**
## Proposed Changes

- Fixes #10850

https://github.com/user-attachments/assets/99883c2f-8f39-4101-90d2-7cfd3de32916

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Introduced confirmation dialogs for canceling planned bed assignments and marking active assignments as errors.
  - Added success and error notifications for bed assignment removal actions.
  - Enabled cancel and error marking actions for both active and planned bed assignments.
  - Updated action buttons with dynamic labels and a destructive style to improve clarity and user experience.

### CODE REVIEW

File: src/components/Location/LocationSheet.tsx [hunk 1]
```diff
@@ -347,11 +352,51 @@ export function LocationSheet({
...
+          location_external_id: location,
+          external_id: id,
+        },
+      })({ encounter: encounter.id, status: "completed" });
+    },
+    onSuccess: () => {
+      toast.success(t("location_deleted_successfully"));
+      queryClient.invalidateQueries({ queryKey: ["encounter", encounter.id] });
+    },
+    onError: (error: {
```
Comment (Jacobjeevan) [inline src/components/Location/LocationSheet.tsx]: Are you sure onError is necessary here? It shouldn't be necessary in most cases.

File: src/components/Location/LocationSheet.tsx [hunk 2]
```diff
@@ -838,6 +892,29 @@ export function LocationSheet({
...
+          <AlertDialogFooter>
+            <AlertDialogCancel
+              onClick={() => {
+                setShowDeleteDialog(false);
+                setLocationToDelete(null);
+              }}
+            >
+              {t("cancel")}
+            </AlertDialogCancel>
+            <AlertDialogAction onClick={confirmDeletePlan}>
```
Comment (Jacobjeevan) [inline src/components/Location/LocationSheet.tsx]: add  `className={cn(buttonVariants({ variant: "destructive" }))}` so button is shown as a destructive action.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
You would also need to adjust the cancel button in LocationActionButtons so it shows us for all scenarios (not just planned).

cc: @amjithtitus09

**Comment by YourBroCode** [comment]
@Jacobjeevan 

> You would also need to adjust the cancel button in LocationActionButtons so it shows us for all scenarios (not just planned).
> 
> cc: @amjithtitus09

I wanted to ask some clarifying questions, right now in modified component, we only have two scenarios (active / planned ). since we can not delete the active location, so there is only one case remains (planned) !

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan
> 
> > You would also need to adjust the cancel button in LocationActionButtons so it shows us for all scenarios (not just planned).
> > cc: @amjithtitus09
> 
> I wanted to ask some clarifying questions, right now in modified component, we only have two scenarios (active / planned ). since we can not delete the active location, so there is only one case remains (planned) !

Why can't we delete active location? 🤔  What if user accidentally marks a bed as active and wants to delete it? Let's allow it unless backend rejects it.

File: src/components/Location/LocationSheet.tsx (hunk 1 above)
Comment (Jacobjeevan) [reply src/components/Location/LocationSheet.tsx]: @YourBroCode If you are marking a comment as resolved, you need to either make changes accordingly or respond (in this case justifying the onError) 😅

Comment (YourBroCode) [reply src/components/Location/LocationSheet.tsx]: Okay, I shall make the changes.

**Comment by YourBroCode** [comment]
> > @Jacobjeevan
> > > You would also need to adjust the cancel button in LocationActionButtons so it shows us for all scenarios (not just planned).
> > > cc: @amjithtitus09
> > 
> > 
> > I wanted to ask some clarifying questions, right now in modified component, we only have two scenarios (active / planned ). since we can not delete the active location, so there is only one case remains (planned) !
> 
> Why can't we delete active location? 🤔 What if user accidentally marks a bed as active and wants to delete it? Let's allow it unless backend rejects it.


@Jacobjeevan , Okay, I will implement this feature for active session too, I studied LocationSheet.tsx file thoroughly and found that many functions are desgined to handle `cancel-plan` for planned session only . I need to do many modifications to acoomplish this.
right now the bed location of  Encounter section is crashing that's why i am unable to work on this issue.
I will make necessary changes in the PR after the issue will be fixed.

**Comment by Jacobjeevan** [comment]
> > > @Jacobjeevan
> > > > You would also need to adjust the cancel button in LocationActionButtons so it shows us for all scenarios (not just planned).
> > > > cc: @amjithtitus09
> > > 
> > > 
> > > I wanted to ask some clarifying questions, right now in modified component, we only have two scenarios (active / planned ). since we can not delete the active location, so there is only one case remains (planned) !
> > 
> > 
> > Why can't we delete active location? 🤔 What if user accidentally marks a bed as active and wants to delete it? Let's allow it unless backend rejects it.
> 
> @Jacobjeevan , Okay, I will implement this feature for active session too, I studied LocationSheet.tsx file thoroughly and found that many functions are desgined to handle `cancel-plan` for planned session only . I need to do many modifications to acoomplish this. right now the bed location of Encounter section is crashing that's why i am unable to work on this issue. I will make necessary changes in the PR after the issue will be fixed.

🤔  What's the crash issue here? Is there an issue/PR associated for it?

**Comment by YourBroCode** [comment]
> > > > @Jacobjeevan
> > > > > You would also need to adjust the cancel button in LocationActionButtons so it shows us for all scenarios (not just planned).
> > > > > cc: @amjithtitus09
> > > > 
> > > > 
> > > > I wanted to ask some clarifying questions, right now in modified component, we only have two scenarios (active / planned ). since we can not delete the active location, so there is only one case remains (planned) !
> > > 
> > > 
> > > Why can't we delete active location? 🤔 What if user accidentally marks a bed as active and wants to delete it? Let's allow it unless backend rejects it.
> > 
> > 
> > @Jacobjeevan , Okay, I will implement this feature for active session too, I studied LocationSheet.tsx file thoroughly and found that many functions are desgined to handle `cancel-plan` for planned session only . I need to do many modifications to acoomplish this. right now the bed location of Encounter section is crashing that's why i am unable to work on this issue. I will make necessary changes in the PR after the issue will be fixed.
> 
> 🤔 What's the crash issue here? Is there an issue/PR associated for it?

@Jacobjeevan 
This was the related issue https://github.com/ohcnetwork/care_fe/issues/11750 

still the issue persists, That's why i am not able to test my code.

https://github.com/user-attachments/assets/bfdec861-5e2d-4d87-b4f1-5f6fc6f081ee

**Comment by amjithtitus09** [comment]
@YourBroCode Did you see why that issue was closed?

**Comment by YourBroCode** [comment]
> @YourBroCode Did you see why that issue was closed?

@amjithtitus09 yes sir, It says it will work with new data. But sir i am not getting  the option for adding new bed in any encounter
sir, could you please help me in which case i will get the option for choosing bed (for assigning now or to schedule ) in Encounter section ? 
Here, how i am trying ->
Login as staffdev -> SK medical Facilities -> create new patient -> add New Encounter .

**Comment by amjithtitus09** [comment]
@YourBroCode You'll have to create new beds from Facility Settings -> Locations tab

**Comment by YourBroCode** [comment]
@Jacobjeevan , I have made the requested changes. Kindly review.

https://github.com/user-attachments/assets/8cab5b7c-ed40-4621-818d-339a5aef9940

File: public/locale/en.json [hunk 3]
```diff
@@ -1618,6 +1620,7 @@
   "location_association_updated_successfully": "Location association updated successfully",
   "location_beds_empty": "No beds available in this location",
   "location_created": "Location Created",
+  "location_deleted_successfully": "Location deleted successfully",
```
Comment (bodhish) [inline public/locale/en.json]: Well you are not deleting a location right? Make the error messages friendly.

**Review by bodhish — DISMISSED** [review]

File: public/locale/en.json (hunk 3 above)
Comment (YourBroCode) [reply public/locale/en.json]: ok sir

**Comment by YourBroCode** [comment]
@Jacobjeevan Kindly review the requested changes and let me know if any further modification is required.

https://github.com/user-attachments/assets/d8d892ee-578a-4776-97cf-ee3435c118d6

**Review by Jacobjeevan — APPROVED** [review]

File: public/locale/en.json [hunk 4]
```diff
@@ -1308,6 +1310,7 @@
   "error": "Error",
   "error_404": "Error 404",
   "error_creating_consent": "Error creating consent",
+  "error_deleting_location": "Error while deleting bed location",
```
Comment (rithviknishad) [inline public/locale/en.json]: the key and text is confusing!

location is not limited to beds in care. 

if this key were to be ever re-used elsewhere referring to non-bed locations, this wouldn't make sense.

File: src/components/Location/LocationSheet.tsx [hunk 5]
```diff
@@ -352,23 +360,58 @@ export function LocationSheet({
...
+        },
+      })({ encounter: encounter.id, status: "completed" });
+    },
+    onSuccess: () => {
+      toast.success(t("location_deleted_successfully"));
+      queryClient.invalidateQueries({ queryKey: ["encounter", encounter.id] });
+    },
+    onError: () => {
+      toast.error(t("error_deleting_location"));
+    },
```
Comment (rithviknishad) [inline src/components/Location/LocationSheet.tsx]: Like @bodhish already said previously, this is not deleting location!

File: src/components/Location/LocationSheet.tsx [hunk 6]
```diff
@@ -352,23 +360,58 @@ export function LocationSheet({
       timeConfig,
     });
   };
+  const deleteMutation = useMutation({
```
Comment (rithviknishad) [inline src/components/Location/LocationSheet.tsx]:
```suggestion
  const { mutate: unlinkLocation } = useMutation({
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: public/locale/en.json (hunk 4 above)
Comment (YourBroCode) [reply public/locale/en.json]: ok sir, I will change it to more relevent keys.

File: src/components/Location/LocationSheet.tsx (hunk 6 above)
Comment (YourBroCode) [reply src/components/Location/LocationSheet.tsx]: I've made the required changes.

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
