### PR TITLE
Fix: Spo2 twice rendering and wrong thresholds 

### LINKED ISSUE #9181: Duplicate and Incorrect SpO2 Field Behaviour in Log Update Form
**Describe the bug**

In the Log Update Form, the fields rendered vary based on the selected round type. However, there are inconsistencies with the SpO2 field

	1.  For round types other than “Nurse Log Update”, two SpO2 fields are rendered
	
	 	* One as a TextFormField
	 	* One as a RangeAutocompleteFormField with different thresholds.
	 	
	2.  For the rest of the round types, the RangeAutocompleteFormField is rendered but with incorrect thresholds.

**To Reproduce**

Steps to reproduce the behaviour:

1.	Navigate to the Log Update Form.
2.	Select any round type other than “Nurse Log Update”.
3.	Observe the duplicate SpO2 fields (TextFormField and RangeAutocompleteFormField).
4.	Select any round type again and verify the thresholds in the RangeAutocompleteFormField SpO2 field.

**Expected behaviour**

	•	Only a single SpO2 field should be rendered across all round types.
	•	The SpO2 field should always be a RangeAutocompleteFormField with the correct thresholds based on the round type.

**Screenshots**
Image

**Desktop (please complete the following information):**

- Browser [e.g. chrome]

**Additional context**
@Jacobjeevan I would like to work on this issue. Please assign it to me.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #9181 

@ohcnetwork/care-fe-code-reviewers
@Jacobjeevan 

## Merge Checklist

- [x] Ensure that UI text is kept in I18n files.
- [x] Request for Peer Reviews

## Summary by CodeRabbit

- **New Features**
	- Updated the `ventilator_spo2` input field to a number type with defined min/max values (0 to 100).
	- Enhanced label display for `ventilator_spo2` based on severity levels using dynamic translations.

- **Bug Fixes**
	- Improved rendering logic for the `ventilator_spo2` field based on selected `rounds_type`.

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]

File: src/components/Patient/DailyRounds.tsx [hunk 1]
```diff
@@ -790,36 +795,6 @@ export const DailyRounds = (props: any) => {
                 ]}
               />
 
-              <TextFormField
```
Comment (shivankacker) [inline src/components/Patient/DailyRounds.tsx:793]: @AdityaJ2305 The Spo2 field was changed to be a number field because there is no need for it to be a rangeautocomplete field. Can you instead keep that version?

**Review by shivankacker — CHANGES_REQUESTED** [review]

File: src/components/Patient/DailyRounds.tsx (hunk 1 above)
Comment (AdityaJ2305) [reply src/components/Patient/DailyRounds.tsx:793]: Sure

**Review by shivankacker — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
