### PR TITLE
Fix : User Detail Responsiveness 

### LINKED ISSUE #10365: Mobile View UI : User detail responsiveness issue
**Describe the bug**
Long Username and user Status gets cut off at medium width. Specifically around 769 - 800 pixels.

**To Reproduce**

1. Go to Any Facility -> Settings -> Departments
2. Select any department team and go to users
3. Reduce screen size to 769 to 800 pixels

**Expected behavior**
Long usernames should still be contained inside the card along with the User status box.

**Screenshots**

Image

Image

### PR DESCRIPTION
**Pull request by DonXavierdev**
## Proposed Changes

- Fixes #10365 
- Add word breaks 
- Remove extra padding 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style**
	- Adjusted the responsive grid layout in the organization users view by shifting the column breakpoint, enhancing display consistency on larger screens.
	- Added margin-left styling to the add user button for improved layout. 
	- Enhanced username display by allowing long text to break onto a new line.

### CODE REVIEW

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx [hunk 1]
```diff
@@ -115,7 +115,7 @@ export default function FacilityOrganizationUsers({ id, facilityId }: Props) {
                             {userRole.user.first_name} {userRole.user.last_name}
                           </h1>
                           <span className="text-sm text-gray-500">
-                            <span className="mr-2">
+                            <span className="mr-2 md:break-words">
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx]: Let's modify the grid for card container, so that we switch to 2 containers for lg, rather than md.

File: src/components/Users/UserListAndCard.tsx [hunk 2]
```diff
@@ -57,7 +57,10 @@ export const UserStatusIndicator = ({
           <span className="text-xs text-green-700">{t("online")}</span>
         </Badge>
       ) : user.last_login ? (
-        <Badge variant="secondary" className="bg-yellow-100 whitespace-nowrap">
+        <Badge
+          variant="secondary"
+          className="bg-yellow-100 whitespace md:px-0 md:py-0 "
```
Comment (Jacobjeevan) [inline src/components/Users/UserListAndCard.tsx]: image

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by Jacobjeevan** [comment]
Try to think ahead 👍  Since you are adjusting this page for responsiveness anyways, check if any other elements need to be adjusted as well.

In this case, the add/link user buttons are too close to the text for mobile.

image

**Review by rithviknishad — APPROVED** [review]

**Comment by DonXavierdev** [comment]
Screenshot 2025-02-03 at 10 28 50 PM
@Jacobjeevan  Adding back break-word classname due to long username overflow

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
