### PR TITLE
Fixed discussion notes input being hidden at bottom

### LINKED ISSUE #12605: Medication Notes message input hidden at bottom, requires scrolling
**Describe the bug**
First-time users miss the text box in the Medication Notes screen because it’s anchored at the very bottom. They have to scroll down before they can even see where to type, which leads to confusion and dropped usage.

Image

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by nandkishorr**
## Proposed Changes

- Fixes #12605 
- Adjusted the main page layout
- Adjusted the message input height
- Fixed the scroll in the desktop sidebar

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Improved layout responsiveness and scrolling for the notes section on large screens.
  - Reduced the initial height of the message input area for a more compact appearance.

### CODE REVIEW

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx [hunk 1]
```diff
@@ -518,7 +518,7 @@ export const EncounterNotesTab = ({
           </div>
         </div>
 
-        <ScrollArea className="flex-1">
+        <ScrollArea className="flex-1 overflow-y-auto">
```
Comment (AdityaJ2305) [inline src/pages/Encounters/tabs/EncounterNotesTab.tsx:521]: You do not need to add `overflow-y-auto` manually in ScrollArea right ? 

```suggestion
        <ScrollArea className="flex-1">
```

**Review by NikhilA8606 — APPROVED** [review]

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx (hunk 1 above)
Comment (NikhilA8606) [reply src/pages/Encounters/tabs/EncounterNotesTab.tsx:521]: > You do not need to add `overflow-y-auto` manually in ScrollArea right ?

It is invalid

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

non-related issue

image

- keep the max height of the component text area to the red mark in the ss, and any excess text, show the scroller>

image

- remove the extra gap between the last message and the text area box
