### PR TITLE
Fix : Questionnaire Navigation main section not working

### LINKED ISSUE #10906: Questionnaire main section navigation not working
**Describe the bug**
Main section headers in the questionnaire form are not navigating to their respective sections when clicked, while sub-section navigation works correctly.

**To Reproduce**

1. Go to 'Encounters' Tab.
2. Click on 'View Details' .
3. Click on "Overview" Tab.
4. Click on "Edit" button.
5. In the questionnaire form:
    Click on main section header - Does not navigate.
    Click on sub-section - Navigates correctly.

https://github.com/user-attachments/assets/d48f6ca9-53c2-4941-aa01-3232c7076139

**Expected behavior**
Clicking on main section headers should scroll to their respective sections.

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #10906

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

https://github.com/user-attachments/assets/a1793d5e-7fae-450b-977e-310bf20a9c3c

## Summary by CodeRabbit

- **New Features**
	- Improved navigation experience with smooth scrolling that automatically focuses on specific questionnaire sections based on user interactions.
	- Added functionality to manage active questionnaire and group IDs for enhanced user navigation.
	- Introduced a new method to facilitate scrolling to relevant questions or groups within the questionnaire.
	- Enhanced button interactions to trigger smooth scrolling to the appropriate questionnaire sections.
	- Enhanced localization for bed management functionalities with new validation messages and options for creating and customizing beds.
	- Introduced a tabbed interface for organization selection, allowing users to view all organizations or their own.
	- Added bulk creation functionality for beds, enhancing user experience in managing bed-related data.

- **Bug Fixes**
	- Resolved issues with the disabled state of form submission buttons based on selection criteria.

- **Chores**
	- Updated API references for facility organization management to streamline functionality and improve code organization.

### CODE REVIEW

File: src/components/Questionnaire/QuestionnaireForm.tsx [hunk 1]
```diff
@@ -328,6 +328,25 @@ export function QuestionnaireForm({
     submitBatch({ requests });
   };
 
+  const scrollToQuestion = (questionnaireId: string, groupId?: string) => {
+    setActiveQuestionnaireId(questionnaireId);
+    setActiveGroupId(groupId);
+
+    if (groupId) {
+      const element = document.querySelector(`[data-group-id="${groupId}"]`);
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionnaireForm.tsx]: define element as let above this condition.

So we can move element check + scroll outside the conditionals.

**Comment by rithviknishad** [comment]
merge checklist not followed

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan Completed merge checklist, Can we re-open this PR ?

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
