### PR TITLE
fixed User Card Layout Issue – Improper Text Overflow

### LINKED ISSUE #10977: User Card Layout Issue – Improper Text Overflow
**Describe the bug**
User Card Layout Issue – Improper Text Overflow

**To Reproduce**
[Click here to reproduce](https://care.ohc.network/facility/605215bd-6215-45dd-bc20-aaeceb474ca1/users?page=2)
 See error

**Expected behavior**
User card text should be properly aligned and should not overflow

**Screenshots**

Image

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [132.0.6834.111]

**Additional context**

### PR DESCRIPTION
**Pull request by Fredrick2503**
## Proposed Changes

- Fixes #10977
- Fixed the text overflow in user card in facility page

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA

## Summary by CodeRabbit

- **Style**
  - Refined the user display header styling by setting its width to 50% and enabling text wrapping for improved layout and readability.

### CODE REVIEW

File: src/components/Users/UserListAndCard.tsx [hunk 1]
```diff
@@ -75,7 +75,7 @@ const UserCard = ({ user }: { user: UserBase }) => {
           <div className="flex flex-col min-w-0 flex-1">
             <div className="flex flex-col gap-1">
               <div className="flex items-start justify-between">
-                <h1 className="text-base font-bold break-words pr-2">
+                <h1 className="text-base font-bold break-words pr-2 w-[50%] text-wrap ">
```
Comment (rithviknishad) [inline src/components/Users/UserListAndCard.tsx]:
```suggestion
                <h1 className="text-base font-bold break-words pr-2 w-[50%] text-wrap">
```

**Review by rithviknishad — APPROVED** [review]
