### PR TITLE
Addressing some bugs in the Encounter manage consents

### LINKED ISSUE #11473: Some bugs in Encounter manage consents
**Describe the bug**
Bug1- The consent period end date is allowed to be entered before consent date

Image

Bug2- No empty state if consents are not found while searching

Image

Bug3- After uploading a file and then cancelling the upload by clicking on the cross mark, this leads to a misleading error message Consent created successfully

https://github.com/user-attachments/assets/7725c050-7c31-4be7-b122-5a16cca24771

**To Reproduce**

1. Go to Encounters
2. Click on manage consents
3. See errors

**Expected behavior**
1. Backend validation is needed to address bug1
2. Bug2 and Bug3 should be resolved in the frontend

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by hrit2773**
## Proposed Changes

- Fixes #11473
### Solved Bug-1

Screenshot 2025-03-26 161623

### Solved Bug-2

Screenshot 2025-03-26 161226

### Solved Bug-3

https://github.com/user-attachments/assets/df2f899f-48c1-4d2c-bd4f-638accf74847

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Added localized UI messages to guide users on date validations and consent availability.
  - Introduced a dynamic empty state view in the consent management section when no records exist.
  - Enhanced validations to ensure consents are submitted with proper date ranges.
  - Refined success notifications for clearer feedback during consent creation.

### CODE REVIEW

**Comment by hrit2773** [comment]
Can I get a review on this

**Comment by hrit2773** [comment]
@praffq to add backend validation for bug-1

**Comment by hrit2773** [comment]
cypress failure not related to this PR

File: src/components/Consent/ConsentSheet.tsx [hunk 1]
```diff
@@ -102,17 +118,26 @@ export function ConsentSheet({
...
-                  consent.source_attachments[0]?.name
-                    ?.toLowerCase()
-                    .includes(searchQuery.toLowerCase()),
-                ) // TODO: move this to the backend in the next iteration
-                .map((consent) => (
-                  <ConsentCard key={consent.id} consent={consent} />
-                ))}
-            </div>
+            {existingConsents?.results &&
+            existingConsents?.results?.filter((consent) =>
```
Comment (Jacobjeevan) [inline src/components/Consent/ConsentSheet.tsx:122]: should be able to map this to a variable instead, since we are calling it again below.

Comment (Jacobjeevan) [inline src/components/Consent/ConsentSheet.tsx]: should be able to map this to a variable instead, since we are calling it again below.

File: src/components/Consent/ConsentSheet.tsx [hunk 2]
```diff
@@ -102,17 +118,26 @@ export function ConsentSheet({
...
+              consent.source_attachments[0]?.name
+                ?.toLowerCase()
+                .includes(searchQuery.toLowerCase()),
+            ).length > 0 ? (
+              <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-6 items-stretch">
```
Comment (Jacobjeevan) [inline src/components/Consent/ConsentSheet.tsx:127]: Also keep the todo.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Consent/ConsentSheet.tsx (hunk 1 above)
Comment (hrit2773) [reply src/components/Consent/ConsentSheet.tsx]: addressed the change

File: src/components/Consent/ConsentSheet.tsx (hunk 2 above)
Comment (hrit2773) [reply src/components/Consent/ConsentSheet.tsx:127]: Added the todo back

**Comment by hrit2773** [comment]
@Jacobjeevan @rithviknishad made the changes can you review once again

**Review by Jacobjeevan — APPROVED** [review]

File: src/components/Consent/ConsentSheet.tsx [hunk 3]
```diff
@@ -66,6 +81,12 @@ export function ConsentSheet({
     enabled: open,
   });
 
+  const consents = existingConsents?.results?.filter((consent) =>
+    consent.source_attachments[0]?.name
+      ?.toLowerCase()
+      .includes(searchQuery.toLowerCase()),
+  ); // TODO: move this to the backend in the next iteration
```
Comment (khavinshankar) [inline src/components/Consent/ConsentSheet.tsx:88]: This is fine, but as a practice, consider using useMemo when doing any computation (that is not constant time) inside a component

**Review by khavinshankar — APPROVED** [review]

File: src/components/Consent/ConsentSheet.tsx (hunk 3 above)
Comment (hrit2773) [reply src/components/Consent/ConsentSheet.tsx:88]: Yup its a good practice

**Comment by hrit2773** [comment]
@nihal467 can you plz test this PR

**Comment by nihal467** [comment]
image

- If the consent is for today only, the validation is throwing error in the frontend condition

**Comment by hrit2773** [comment]
@nihal467 I guess the consent also cannot be issued on the day of expiry cc @rithviknishad that's why I wrote the condition for end date equal to consent date also.

**Comment by hrit2773** [comment]
should I include the equal to condition or not is my question??

**Comment by hrit2773** [comment]
@nihal467 You can test this again now changed the condition

**Comment by hrit2773** [comment]
@nihal467 I have updated the condition can you test this again. Yet to be merged

**Comment by hrit2773** [comment]
@nihal467 I made the required changes can you test it and confirm if its okay or any further proceedings required

**Comment by nihal467** [comment]
LGTM
