### PR TITLE
Fix: Allow administering medicine at the same time as it was added #12693

### LINKED ISSUE #12693: Modify the medicine administration validation to be on or after date of medicine added
**Describe the bug**

A validation error is thrown when trying to administer a medicine at the same time it is added.

**To Reproduce**

1. Go to live encounter
2. Medicine
3. Add a medicine and administor it on the same time

**Expected behavior**

The medicine should be successfully administered if the administration time matches the time it was added, without triggering a validation error.

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by geyamrutha16**
…2693

## Proposed Changes

- Fixes #12693 
- Round occurrence_period_start and authored_on to the nearest minute before comparing
- Prevent false validation errors when administering at the same time as prescribing

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved date and time validation to ensure consistency by ignoring seconds and milliseconds during comparisons. This prevents minor discrepancies from affecting medication administration form validation.

### CODE REVIEW

File: src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx [hunk 1]
```diff
@@ -63,22 +63,35 @@ export const MedicineAdminForm: React.FC<MedicineAdminFormProps> = ({
   const [startTimeError, setStartTimeError] = useState("");
   const [endTimeError, setEndTimeError] = useState("");
 
+  const roundToNearestMinute = (date: Date) => {
+    const rounded = new Date(date);
+    rounded.setSeconds(0);
+    rounded.setMilliseconds(0);
+    return rounded;
+  };
```
Comment (AdityaJ2305) [inline src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: just check instead of this can we use any utility from date-fns or dayjs  🤔

Comment (geyamrutha16) [reply src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: Yeah! Since **date-fns** is already in use in the codebase [ especially this component ], we can simplify this with its built-in **startOfMinute()** utility

Will update accordingly.

**Comment by geyamrutha16** [comment]
Hi @AdityaJ2305 , I’ve addressed the suggested changes and pushed the updated code. Could you please review - Open to any further feedback!

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx [hunk 2]
```diff
@@ -64,21 +64,26 @@ export const MedicineAdminForm: React.FC<MedicineAdminFormProps> = ({
...
-    const authoredOn = new Date(medication.authored_on);
-    const startTime = new Date(administrationRequest.occurrence_period_start);
-
-    if (date > now) {
+    const now = startOfMinute(new Date());
+    const authoredOn = startOfMinute(new Date(medication.authored_on));
+    const startTime = startOfMinute(
+      new Date(administrationRequest.occurrence_period_start),
+    );
+    const roundedDate = startOfMinute(date);
```
Comment (rithviknishad) [inline src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: you could just re-assign the value and skip many other changes below right? 🤔 

```suggestion
    date = startOfMinute(date);
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]

**Review by abhimanyurajeesh — APPROVED** [review]
