### PR TITLE
fix: broken ui in encounter page in mobile view

### LINKED ISSUE #13691: Improve UI of View Encounter Page in Mobile View
**Description**: The UI can be improved in the Mobile View

Image

Image

**Steps To Reproduce:**
- Go to Patients from the sidebar
- All encounter -> View Encounter of any patient

### PR DESCRIPTION
**Pull request by shiv7shukla**
## Proposed Changes

Fixes #13691
- Aligned "- Ongoing" and chevron icon horizontally with the "Virtual" title.
- Moved the status badge to a separate row aligned under the date/chevron.
- improved spacing and responsiveness to prevent overflow and cramped UI on small screens.
Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [ x ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ x ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes
image

## Summary by CodeRabbit

* **Style**
  * Increased padding and spacing in the encounter history cards for cleaner layout
  * Reorganized rows: date range on first row, status badge moved to a dedicated second row
  * Chevron moved into a compact button for clearer affordance
  * Date range now shows " - ongoing" when no end date is present for clarity

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/pages/Encounters/EncounterHistorySelector.tsx [hunk 1]
```diff
@@ -439,39 +439,48 @@ const EncounterSheetTrigger = () => {
               {encounter.facility.name}
             </span>
           </div>
-          <div className="flex gap-1 items-center justify-center">
-            <div className="flex flex-col gap-1 items-end ">
+          <div className="flex flex-col items-start">
+            {/* TOP ROW Ongoing Chevron */}
+            <div className="flex items-center gap-1 -mt-2">
```
[the remark this answers is not in the document]
Comment (shiv7shukla) [reply src/pages/Encounters/EncounterHistorySelector.tsx:443]: your suggestion is not working

File: src/pages/Encounters/EncounterHistorySelector.tsx [hunk 2]
```diff
@@ -439,39 +439,46 @@ const EncounterSheetTrigger = () => {
...
                     {format(new Date(encounter.period.end), "dd MMM")}
                   </span>
                 ) : (
-                  <span>
-                    {" - "}
-                    {t("ongoing")}
-                  </span>
+                  <span> - {t("ongoing")}</span>
                 )}
               </span>
```
[the remark this answers is not in the document]
Comment (shiv7shukla) [reply src/pages/Encounters/EncounterHistorySelector.tsx:460]: This PR is only for fixing the UI and I did not modify the date logic

File: src/components/Patient/PatientHeader.tsx [hunk 3]
```diff
@@ -31,7 +31,7 @@ export function PatientHeader({
   return (
     <Card
       className={cn(
-        "p-2 rounded-none shadow-none border-none md:p-4 flex flex-col md:flex-row md:justify-between bg-transparent gap-6",
```
Comment (abhimanyurajeesh) [inline src/components/Patient/PatientHeader.tsx]: This is a reusable component. Consider adding sm:gap-6 if not needed in mobile.

**Review by abhimanyurajeesh — CHANGES_REQUESTED** [review]
Remove the unnecessary comments and look into code rabbit review.

File: src/pages/Encounters/EncounterHistorySelector.tsx [hunk 4]
```diff
@@ -439,39 +439,46 @@ const EncounterSheetTrigger = () => {
               {encounter.facility.name}
             </span>
           </div>
-          <div className="flex gap-1 items-center justify-center">
-            <div className="flex flex-col gap-1 items-end ">
+          <div className="flex flex-col items-start">
+            {/* TOP ROW Ongoing Chevron */}
+            <div className="flex items-center gap-1 -mt-2">
```
[the remark this answers is not in the document]
Comment (shiv7shukla) [reply src/pages/Encounters/EncounterHistorySelector.tsx:443]: Without `-mt-2` or using some other flex arrangement the components inside the care are spreading. 
{5A9DD574-B578-45E4-9D99-1D16E3BF1958}
On using `-mt-2` the components remain aligned.
image

File: src/pages/Encounters/EncounterHistorySelector.tsx [hunk 5]
```diff
@@ -439,39 +439,41 @@ const EncounterSheetTrigger = () => {
...
               </span>
-              <Badge
-                variant={ENCOUNTER_STATUS_COLORS[encounter.status]}
-                size="sm"
-                className=" whitespace-nowrap"
+              <div
+                className={cn(
+                  buttonVariants({ variant: "ghost", size: "icon" }),
+                )}
+                aria-hidden="true"
```
Comment (AdityaJ2305) [inline src/pages/Encounters/EncounterHistorySelector.tsx:465]: why aria-hidden true ? 🤔

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

File: src/pages/Encounters/EncounterHistorySelector.tsx (hunk 5 above)
Comment (shiv7shukla) [reply src/pages/Encounters/EncounterHistorySelector.tsx:465]: @AdityaJ2305 In the last PR which got closed when default branch got changed coderabbit suggested to use aria-hidden true

**Comment by nihal467** [comment]
@shiv7shukla seem like a discussion going on, once its ready for review, tag me

File: src/pages/Encounters/EncounterHistorySelector.tsx (hunk 5 above)
Comment (shiv7shukla) [reply src/pages/Encounters/EncounterHistorySelector.tsx:465]: @AdityaJ2305 Should I remove the aria-label or not?

Comment (AdityaJ2305) [reply src/pages/Encounters/EncounterHistorySelector.tsx:465]: Nope it's fine

**Comment by builtby-SHIV** [comment]
> @shiv7shukla seem like a discussion going on, once its ready for review, tag me

@nihal467 Discussion has resolved please review it

**Review by Jacobjeevan — APPROVED** [review]

**Review by AdityaJ2305 — APPROVED** [review]
