### PR TITLE
Tailwinds / Migrates all usages of `RoleButton` to `ButtonV2` with `authorizedFor`

### LINKED ISSUE #4370: Goodbye to Rolebtn component from CARE
**Describe the bug**
All Existing Rolebtn would be replaced by ButtonV2

### PR DESCRIPTION
**Pull request by rithviknishad**
### <samp>🤖 Generated by Copilot at 8e7b5cb</samp>

Refactored several components in the `Facility` module to use new common components `ButtonV2` and `CareIcon` for improved UI and code quality. Deleted unused component `RoleButton`.

## Proposed Changes

- Fixes #4370
- Replaces `RoleButton` with `ButtonV2` in Doctor Capacity Count Card
- Replaces `RoleButton` with `ButtonV2` in Inventoy Management: Min. Quantity Page
- Replaces `RoleButton` with `ButtonV2` in Location Management
- Adds authorization for buttons in Bed Management Page

### Screenshots

image

image

image

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 8e7b5cb</samp>

*  Refactor `BedManagement`, `DoctorsCountCard`, `LocationManagement`, and `MinQuantityList` components to use the new `ButtonV2` component instead of the old `RoleButton` component ([link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-53ec6fe91fcb892cb08c1ff573b13dea07d1bee5b9f5f269b808a0b12e26abdaL112-R138), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-53ec6fe91fcb892cb08c1ff573b13dea07d1bee5b9f5f269b808a0b12e26abdaL276-R280), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-7d963d4eef081bc1fb2bfd17738bbc0ee6963688cb306de6ddbe14d51075372fL64-R84), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-042c54113f687e89c2429ff1d97fe7dfcccfa3818279170a82ea1286684a53cdL39-R57), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-042c54113f687e89c2429ff1d97fe7dfcccfa3818279170a82ea1286684a53cdL172-R170), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-3fc40e79463bf9abd721537b95b0cebb523690997997a70908afc220d91792c8L129-R132), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-3fc40e79463bf9abd721537b95b0cebb523690997997a70908afc220d91792c8L143-R142), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-3fc40e79463bf9abd721537b95b0cebb523690997997a70908afc220d91792c8L228-R229))
* Use the `CareIcon` component to display icons instead of the `i` element with font-awesome classes in `BedManagement` and `LocationManagement` components ([link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-53ec6fe91fcb892cb08c1ff573b13dea07d1bee5b9f5f269b808a0b12e26abdaL112-R138), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-53ec6fe91fcb892cb08c1ff573b13dea07d1bee5b9f5f269b808a0b12e26abdaL276-R280), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-042c54113f687e89c2429ff1d97fe7dfcccfa3818279170a82ea1286684a53cdL39-R57), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-042c54113f687e89c2429ff1d97fe7dfcccfa3818279170a82ea1286684a53cdL172-R170))
* Remove the import of `React` from `react` in `LocationManagement` and `MinQuantityList` components, as it is no longer needed with the new JSX transform ([link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-042c54113f687e89c2429ff1d97fe7dfcccfa3818279170a82ea1286684a53cdL1-R11), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-3fc40e79463bf9abd721537b95b0cebb523690997997a70908afc220d91792c8L7-R9))
* Remove the import of `navigate` from `raviger` in `BedManagement`, `LocationManagement`, and `MinQuantityList` components, as it is no longer used in the files ([link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-53ec6fe91fcb892cb08c1ff573b13dea07d1bee5b9f5f269b808a0b12e26abdaL11), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-042c54113f687e89c2429ff1d97fe7dfcccfa3818279170a82ea1286684a53cdL1-R11), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-3fc40e79463bf9abd721537b95b0cebb523690997997a70908afc220d91792c8L7-R9))
* Add the import of `NonReadOnlyUsers` from `../../Utils/AuthorizeFor` in `BedManagement`, `DoctorsCountCard`, `LocationManagement`, and `MinQuantityList` components, as it is used in the new `ButtonV2` component ([link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-53ec6fe91fcb892cb08c1ff573b13dea07d1bee5b9f5f269b808a0b12e26abdaR18-R19), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-7d963d4eef081bc1fb2bfd17738bbc0ee6963688cb306de6ddbe14d51075372fR11-R12), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-042c54113f687e89c2429ff1d97fe7dfcccfa3818279170a82ea1286684a53cdL1-R11), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-3fc40e79463bf9abd721537b95b0cebb523690997997a70908afc220d91792c8L7-R9))
* Add the import of `ButtonV2` from `../Common/components/ButtonV2` in `BedManagement`, `DoctorsCountCard`, `LocationManagement`, and `MinQuantityList` components, as it is used to replace the old `RoleButton` component ([link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-53ec6fe91fcb892cb08c1ff573b13dea07d1bee5b9f5f269b808a0b12e26abdaR18-R19), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-7d963d4eef081bc1fb2bfd17738bbc0ee6963688cb306de6ddbe14d51075372fR11-R12), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-042c54113f687e89c2429ff1d97fe7dfcccfa3818279170a82ea1286684a53cdL1-R11), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-3fc40e79463bf9abd721537b95b0cebb523690997997a70908afc220d91792c8L7-R9))
* Add the import of `CareIcon` from `../../CAREUI/icons/CareIcon` in `BedManagement` and `LocationManagement` components, as it is used to display icons ([link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-53ec6fe91fcb892cb08c1ff573b13dea07d1bee5b9f5f269b808a0b12e26abdaR18-R19), [link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-042c54113f687e89c2429ff1d97fe7dfcccfa3818279170a82ea1286684a53cdL1-R11))
* Remove the import of `RoleButton` from `../Common/RoleButton` in `DoctorsCountCard` component, as it is no longer used in the file ([link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-7d963d4eef081bc1fb2bfd17738bbc0ee6963688cb306de6ddbe14d51075372fL4))
* Delete the file `src/Components/Common/RoleButton.tsx`, as it is no longer used in the project ([link](https://github.com/coronasafe/care_fe/pull/5649/files?diff=unified&w=0#diff-9808259a0c9aec4b973de14390e562ec09820e95e251961e9bc7ced47a8ef4e6))

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad 
image

- [ ] make all the three above button, full width in mobile view

image

- [ ] make the above buttons, right most aligned

image

- [ ] make the above content name, left aligned in mobile view

File: src/Components/Facility/LocationManagement.tsx [hunk 1]
```diff
@@ -36,33 +37,24 @@ const LocationRow = (props: LocationRowProps) => {
...
+          href={`/facility/${facilityId}/location/${id}/update`}
+          authorizeFor={NonReadOnlyUsers}
+        >
+          <CareIcon className="care-l-pen text-lg" />
+          Edit
+        </ButtonV2>
+        <ButtonV2
+          variant="secondary"
+          border
+          href={`/facility/${facilityId}/location/${id}/beds`}
```
Comment (rithviknishad) [inline src/Components/Facility/LocationManagement.tsx:53]:
```suggestion
          href={`/facility/${facilityId}/location/${id}/beds`}
          className="w-full lg:w-auto"
```

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
