### PR TITLE
Fixes Login Mode parameter not changing when switching tabs #12767

### LINKED ISSUE #12767: Login tab switching doesn't update browser URL mode parameter
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the Landing Page.
2. Click on either Login as Staff or Login as Patient.
3. Once the user is on the Login page, switch to the other login tab option available.
4. See that the mode in the URL does not change according to the tab selected.

**Expected behavior**
Mode parameter in URL should change based on the tab the user has selected.

**Screenshots**
Mode parameter in URL is staff, but the user has selected Login as Patient tab.
Image

Mode parameter in URL is patient, but the user has selected Login as Staff tab.

Image

**Desktop (please complete the following information):**

- OS: [Windows 11]
- Browser [Google Chrome]

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by SiddanthNayak**
## Proposed Changes

- Fixes #12767 
- Added navigate to onValueChange function when switching tabs with the correct mode parameter

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

https://github.com/user-attachments/assets/bd3a4d35-4897-489f-abdf-a899138387c3

- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **New Features**
  * The login page URL now updates to reflect the selected login mode, ensuring the query parameter matches your current selection.

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
let's use `setQueryParams` from `useQueryParams` instead of directly calling `navigate`. 

Improves code maintainability since we don't need to worry about the current path.

**Comment by SiddanthNayak** [comment]
> let's use `setQueryParams` from `useQueryParams` instead of directly calling `navigate`.
> 
> Improves code maintainability since we don't need to worry about the current path.

hi @rithviknishad, made the necessary changes requested. Please review

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

File: src/components/Auth/Login.tsx [hunk 1]
```diff
@@ -370,6 +370,7 @@ const Login = (props: LoginProps) => {
                   value={loginMode}
                   onValueChange={(value) => {
                     setLoginMode(value as LoginMode);
```
Comment (rithviknishad) [inline src/components/Auth/Login.tsx]: now that the state is fully managed in the query params, we don't need this state managed by useState in the client right? 🤔

**Review by rithviknishad — DISMISSED** [review]

File: src/components/Auth/Login.tsx (hunk 1 above)
Comment (SiddanthNayak) [reply src/components/Auth/Login.tsx]: @rithviknishad Yes, state managed by useState becomes redundant here. 

I have made the changes as requested. Please review

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
