### PR TITLE
Fix tab switching in files tab

### LINKED ISSUE #14648: Issue while switching tabs in FilesTab in encounter
**Describe the bug**
In FilesTab in encounter, we can't switch between files, discharge summary and drawings. It always resets to files.
---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by khavinshankar**
## Proposed Changes

Fixes #14648
- Fix tab switching in files tab
- consider active query params while setting and restoring cache

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed filter initialization and restoration so defaults and saved filters are merged with — and do not overwrite — a user's current query parameters, preserving existing selections when applying defaults or restoring cached values.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/hooks/useFilters.tsx [hunk 1]
```diff
@@ -86,8 +86,10 @@ export default function useFilters({
       // Clean-up any existing cache if present for this path.
       FiltersCache.invalidate();
 
-      // Set default query params if they are not present
-      setQueryParams({ ...defaults });
+      // Set default query params if they are not present, preserving existing params
+      if (Object.keys(defaults).length > 0) {
+        setQueryParams({ ...qParams, ...defaults });
+      }
```
Comment (rithviknishad) [inline src/hooks/useFilters.tsx:92]: shouldn't the order be `defaults` followed by `qParams`? 🤔

File: src/hooks/useFilters.tsx [hunk 2]
```diff
@@ -104,12 +106,14 @@ export default function useFilters({
...
-      setQueryParams({ ...defaults });
+      if (Object.keys(defaults).length > 0) {
+        setQueryParams({ ...qParams, ...defaults });
+      }
       return;
     }
 
     // Restore cache
-    setQueryParams({ ...defaults, ...cache });
+    setQueryParams({ ...qParams, ...defaults, ...cache });
```
Comment (rithviknishad) [inline src/hooks/useFilters.tsx]: qParams here as well should be last right?

File: src/hooks/useFilters.tsx (hunk 1 above)
Comment (khavinshankar) [reply src/hooks/useFilters.tsx:92]: nice spot

**Review by rithviknishad — APPROVED** [review]

**Review by abhimanyurajeesh — APPROVED** [review]

File: src/hooks/useFilters.tsx (hunk 1 above)
Comment (amjithtitus09) [reply src/hooks/useFilters.tsx:92]: @khavinshankar Was this updated?

**Review by nihal467 — APPROVED** [review]

File: src/hooks/useFilters.tsx [hunk 3]
```diff
@@ -86,8 +86,10 @@ export default function useFilters({
       // Clean-up any existing cache if present for this path.
       FiltersCache.invalidate();
 
-      // Set default query params if they are not present
-      setQueryParams({ ...defaults });
+      // Set default query params if they are not present, preserving existing params
+      if (Object.keys(defaults).length > 0) {
+        setQueryParams({ ...qParams, ...defaults });
```
Comment (khavinshankar) [inline src/hooks/useFilters.tsx]:
```suggestion
        setQueryParams({ ...defaults, ...qParams });
```

**Review by amjithtitus09 — APPROVED** [review]
