### PR TITLE
Fix: Repeated Shift+Enter sends duplicate messages on discussion page

### LINKED ISSUE #12601: Bug: Repeated Shift+Enter sends duplicate messages on discussion page"
**Describe the bug**
Clicking Shift+Enter Multiple times sends the same message mutilple times on the discussion page

**To Reproduce**

1. Go to Encounters
2. Click on Notes
3. Start a discussion
4. Type a message and Shift + Enter multiple times
5. See error

**Expected behavior**
Send the text only once

**Recording**

https://github.com/user-attachments/assets/cb493594-b177-4752-8260-a3680eeab1f7

**Desktop (please complete the following information):**

- OS: Fedora
- Browser: Brave
---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by perpetrator1**
## Proposed Changes

- Fixes #12601 
This pull request updates the `EncounterNotesTab` component in `src/pages/Encounters/tabs/EncounterNotesTab.tsx` to improve message handling logic by introducing a new condition that prevents sending messages while a mutation is pending.

Enhancements to message handling:

* Modified the `handleSendMessage` function to include a `canSend` condition that checks if `createMessageMutation.isPending` is false before allowing a new message to be sent. This ensures that duplicate messages are not sent while a mutation is still in progress.
* Updated the `onKeyDown` handler for the "Enter + Shift" key combination to include the `canSend` condition, preventing message sending while a mutation is pending and stopping event propagation for better control.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
  - Prevented multiple messages from being sent simultaneously by disabling sending while a previous message is in progress.
  - Improved message input handling to ensure only non-empty messages can be sent.
  - Enhanced message sending behavior to support Shift+Enter for sending messages more intuitively.

### CODE REVIEW

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx [hunk 1]
```diff
@@ -715,7 +717,11 @@ export const EncounterNotesTab = ({
                             onKeyDown={(e) => {
                               if (e.key === "Enter" && e.shiftKey) {
                                 e.preventDefault();
-                                if (newMessage.trim()) {
+                                e.stopPropagation();
+                                const canSend =
+                                  newMessage.trim() &&
+                                  !createMessageMutation.isPending;
+                                if (canSend) {
```
Comment (AdityaJ2305) [inline src/pages/Encounters/tabs/EncounterNotesTab.tsx]: I think check only in `handleSendMessage()` is enough right ?

Comment (perpetrator1) [reply src/pages/Encounters/tabs/EncounterNotesTab.tsx]: Yes

**Review by AdityaJ2305 — APPROVED** [review]

**Review by AdityaJ2305 — COMMENTED** [review]
Just noticed — shouldn’t we use Cmd + Enter instead of Shift + Enter ? 🤔 That’s what GitHub uses and a bunch of other too 

cc: @rithviknishad @Jacobjeevan

**Review by Jacobjeevan — APPROVED** [review]

**Comment by Jacobjeevan** [comment]
> Just noticed — shouldn’t we use Cmd + Enter instead of Shift + Enter ? 🤔 That’s what GitHub uses and a bunch of other too
> 
> cc: @rithviknishad @Jacobjeevan

Shift + Enter is also used in a lot of places. Current setup is based on product feedback, we can change it if users request it 👍

**Comment by nihal467** [comment]
LGTM

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx [hunk 2]
```diff
@@ -715,9 +717,8 @@ export const EncounterNotesTab = ({
                             onKeyDown={(e) => {
                               if (e.key === "Enter" && e.shiftKey) {
                                 e.preventDefault();
-                                if (newMessage.trim()) {
-                                  handleSendMessage(e);
-                                }
+                                e.stopPropagation();
```
Comment (rithviknishad) [inline src/pages/Encounters/tabs/EncounterNotesTab.tsx]: can we stick to perform e.prevent / stop propogation either in handleSendMessage or here?

let's not call it multiple times here and there

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/pages/Encounters/tabs/EncounterNotesTab.tsx (hunk 2 above)
Comment (perpetrator1) [reply src/pages/Encounters/tabs/EncounterNotesTab.tsx]: ive moved them to handleSendMessage

**Review by rithviknishad — APPROVED** [review]
