### PR TITLE
FIXED: Consent validation time in consent page in Mobile View

### LINKED ISSUE #12468: Consent validation time is not visible in add consent page in Mobile View UI
**Describe the bug**
Consent validation time is not visible properly when we see it in mobile view

**To Reproduce**

1. Go to [link](https://care.ohc.network/facility/10011fb2-4510-43db-8fe7-27a436ec2583/patient/53f2d782-875d-477c-9ebe-f3adc5d12438/encounter/d2b6ea9f-05d6-46fa-a3e5-9fa808ccce38/consents)
2. Add consent
3. See in mobile view

**Expected behavior**
We can set the 'consent valid from' and 'consent valid until' to full width just like the 'Consent Given' on field

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by anupam0-0**
## Proposed Changes

- set grid-cols-1 lg:grid-cols-2
- Fixes #12468 
- Mobile View:
image

- Desktop View: (unchanged as expected)
image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Improved the layout of form fields in the consent form for better responsiveness on different screen sizes. Fields now stack vertically on small screens and display side-by-side on larger screens.

### CODE REVIEW

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
image
image

The second screenshot is the current develop, which is looking good compared to the change in your PR for most of the common devices.

**Comment by anupam0-0** [comment]
I have found another approach
Pls let me know what you think
As the 2nd screenshot @nihal467 has provided is lacking the calendar logo

What if we use `w-fit`, the results are below:

Mobile view: (for 320 px, the smallest one in the console)
image


Mobile view: (for iPhone 12 Pro that was mentioned)
image


Desktop view:
image

**Comment by AdityaJ2305** [comment]
@nihal467, in the second screenshot, the input looks cut off — if you notice, the calendar icon is missing too.

File: src/components/Consent/ConsentFormSheet.tsx [hunk 1]
```diff
@@ -340,7 +340,7 @@ export default function ConsentFormSheet({
                   )}
                 />
 
-                <div className="grid grid-cols-2 gap-4">
+                <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
```
Comment (AdityaJ2305) [inline src/components/Consent/ConsentFormSheet.tsx:343]: ~~Should we switch to use flex here? 🤔~~

Comment (AdityaJ2305) [reply src/components/Consent/ConsentFormSheet.tsx:343]: Just noticed native input is being changed to DayPicker in this PR https://github.com/ohcnetwork/care_fe/pull/12490
cc: @Jacobjeevan

Comment (rithviknishad) [reply src/components/Consent/ConsentFormSheet.tsx:343]: @AdityaJ2305 consent validity has time as well!

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
