### PR TITLE
Fix: View Facility Redirection in public page is broken

### LINKED ISSUE #10315: View Facility Redirection in public page is broken
**Describe the bug**

When we click on the view facility button, the user is being redirected to the login page with query params of overview

**To Reproduce**

1. Go to public page ( https://care.ohc.network/facilities?organization=7e576b6d-5572-4204-84f3-b1412767c406&page=1&limit=14 )
2. Click on view facility
3. See error

**Expected behavior**

It should be showing the view facility page, as show in the below screenshot. For reference of how view facility public page looks like visit : https://staging.ohc.network/facility/b754c1f3-03bf-40f1-8625-5e8927caac5b

**Screenshots**

Image

Image

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #10315 
- Change 1
- Change 2
- More?

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Navigation Update**
  - Modified facility card link to direct users to the main facility page instead of the overview page
  - No changes to component's public interface or exported entities

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

File: src/pages/Facility/components/FacilityCard.tsx [hunk 1]
```diff
@@ -53,9 +53,7 @@ export function FacilityCard({ facility, className }: Props) {
         <div className="mt-auto border-t border-gray-100 bg-gray-50 p-4">
           <div className="flex justify-end">
             <Button variant="outline" asChild>
-              <Link href={`/facility/${facility.id}/overview`}>
-                View Facility
-              </Link>
+              <Link href={`/facility/${facility.id}`}>View Facility</Link>
```
Comment (rithviknishad) [inline src/pages/Facility/components/FacilityCard.tsx:56]: nice find, 

one more reason to switch to tanstack router...

cc: @bodhish @gigincg
