### PR TITLE
fix: Added responsiveness in Select component

### LINKED ISSUE #11788: Link User Sheet need styling and responsiveness
**Describe the bug**
There is lack of responsiveness.
Need to use truncate in dropdown.

**To Reproduce**

1. Go to [link](http://localhost:4000/organization/5a921d88-a8a0-4d48-98f2-8e0cd23b09c0/users?page=1&limit=15&sheet=link)
2. Check on mobile view

**Expected behavior**
There should be proper responsiveness for drop down
There should be truncate class for select role

**Screenshots**

https://github.com/user-attachments/assets/e958410a-b479-4e07-a3a5-3bbf94e0b55d

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Tanuj1718**
## Proposed Changes

- Fixes #11788
Added responsiveness in select component
Added truncate class in select role description of Link User sheet

https://github.com/user-attachments/assets/983248de-3929-4308-bb11-e228b769ade0

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Enhanced form elements and dropdown menus with refined responsive widths for improved display across devices.
  - Upgraded label components for a more consistent and polished appearance.
  - Improved the overall layout and presentation of role selection and content sheets for a better user experience.

### CODE REVIEW

File: src/components/ui/select.tsx [hunk 1]
```diff
@@ -78,6 +78,7 @@ const SelectContent = React.forwardRef<
       ref={ref}
       className={cn(
         "relative z-50 max-h-96 min-w-[8rem] overflow-hidden rounded-md border border-gray-200 bg-white text-gray-950 shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50",
+        "min-w-[8rem] sm:min-w-[10rem] md:min-w-[12rem] lg:min-w-[14rem] max-w-[90vw]",
```
Comment (rithviknishad) [inline src/components/ui/select.tsx]: if this is a problem with shadcn's component, file issue there. PR's modifying shadcn components will not be accepted;

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by rithviknishad** [comment]
https://github.com/ohcnetwork/care_fe/issues/11788#issuecomment-2784115104

☝🏼 not done!

File: src/components/ui/select.tsx (hunk 1 above)
Comment (Tanuj1718) [reply src/components/ui/select.tsx]: @rithviknishad Yes it is component's problem

**Comment by Tanuj1718** [comment]
> [#11788 (comment)](https://github.com/ohcnetwork/care_fe/issues/11788#issuecomment-2784115104)
> 
> ☝🏼 not done!

@rithviknishad I have to use these classes wherever we are using SelectComponent. Should I do it like this way?

**Comment by rithviknishad** [comment]
not all; only wherever applicable

**Comment by Tanuj1718** [comment]
**Demo Video:** 

https://github.com/user-attachments/assets/a7266c68-656b-4e5d-8d65-5d0fed3586a5

**Review by rithviknishad — CHANGES_REQUESTED** [review]
why not use css variables to achieve this instead? 🤔 similar to how it's done in all other places?


image

**Comment by Tanuj1718** [comment]
> why not use css variables to achieve this instead? 🤔 similar to how it's done in all other places?
> 
> image

Oh I didn't know about that radix provide css variables internally.👀 
New thing to know.

File: src/components/Patient/PatientDetailsTab/PatientUsers.tsx [hunk 2]
```diff
@@ -191,7 +191,7 @@ function AddUserSheet({ patientId }: AddUserSheetProps) {
                   <SelectTrigger data-cy="patient-user-role-select">
                     <SelectValue placeholder={t("select_role")} />
                   </SelectTrigger>
-                  <SelectContent>
+                  <SelectContent className="min-w-[var(--radix-select-trigger-width)] max-w-[90vw]">
```
Comment (rithviknishad) [inline src/components/Patient/PatientDetailsTab/PatientUsers.tsx]: we can simply do this right? 🤔 correct me if i am wrong

```suggestion
                  <SelectContent className="w-[var(--radix-select-trigger-width)]">
```

Comment (Tanuj1718) [reply src/components/Patient/PatientDetailsTab/PatientUsers.tsx:194]: We have to set the min width otherwise it take width according to the content. Although we can remove max width.

Comment (Tanuj1718) [reply src/components/Patient/PatientDetailsTab/PatientUsers.tsx]: Oh yes we can do this. It is unecessary to set min and max width😅

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM
