### PR TITLE
fix: Icon of latest location with completed bed stay

### LINKED ISSUE #14678: Incorrect icon shown for completed bedstay in Location History
**Describe the bug**
In Location History, the latest location with completed bedstay still displays the map marker icon instead of the check mark.

**To Reproduce**

1. Go to 'Encounters' -> 'View Encounter'
2. Click on 'Encounter Actions'
3. Click on 'Location History'

**Expected behavior**
Latest location with completed bedstay should display check mark icon.

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by StephZam**
## Proposed Changes

Fixes #14678
- In location history, the latest location with completed bed stay shows check mark icon instead of map marker.

image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved timeline visuals for locations: completed entries now show a muted gray background, a check-style icon, and muted text; the most recent active location uses green highlights; earlier entries remain muted. Vertical line alignment and non-latest branch rendering remain unchanged.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/components/Location/LocationTree.tsx [hunk 1]
```diff
@@ -105,6 +105,8 @@ export function LocationTree({
   isLatest,
   showTimeline = false,
 }: LocationPathProps) {
+  const completed = isLatest && endTime;
+
```
Comment (rithviknishad) [inline src/components/Location/LocationTree.tsx]: do we really need the `isLatest` check to know whether it is completed or not? 🤔 

we are planning to introduce multiple active locations for an encounter. i.e., for example, an encounter would have an active location and multiple planned locations in the future as well.

```suggestion
  const isCompleted = !!endTime;

```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by nihal467 — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
