### PR TITLE
Hide time tooltip for never logged in user cards #12145

### LINKED ISSUE #12145: Hide time tooltip for never logged in user cards
**Describe the bug**

The tooltip tip show on hover for the never logged in user is wrong and not relevant

**To Reproduce**

1. Go to any facility
2. go to users and hover on never logged in user
3. see the error

**Expected behavior**

Hide the time tooltip for never logged in user card

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by gobardan1707**
## Proposed Changes

- Fixes #12145 
- added logic for tooltipTittle 
- changed title 

https://github.com/user-attachments/assets/05e218a5-9beb-4467-b981-afaaab4078af

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
  - Fixed tooltip display for user last login dates to avoid showing invalid or empty information when no date is available.

### CODE REVIEW

**Review by Tanuj1718 — CHANGES_REQUESTED** [review]
shouldn't we put it undefined instead of empty string? See coderabbit suggestion.

File: src/components/Users/UserListAndCard.tsx [hunk 1]
```diff
@@ -34,10 +34,13 @@ export const UserStatusIndicator = ({
   const authUser = useAuthUser();
   const isAuthUser = user.id === authUser.external_id;
   const { t } = useTranslation();
+  const tooltipTitle = user.last_login
+    ? `${new Date(user.last_login).toLocaleString()}`
+    : "";
```
Comment (rithviknishad) [inline src/components/Users/UserListAndCard.tsx]: i don't see any reason to refactor this out as a variable. let's keep this inlined

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Users/UserListAndCard.tsx [hunk 2]
```diff
@@ -37,7 +37,11 @@ export const UserStatusIndicator = ({
 
   return (
     <span
-      title={`${new Date(user.last_login).toLocaleString()}`}
+      title={
+        user.last_login
+          ? `${new Date(user.last_login).toLocaleString()}`
```
Comment (rithviknishad) [inline src/components/Users/UserListAndCard.tsx]:
```suggestion
          ? new Date(user.last_login).toLocaleString()
```

**Review by rithviknishad — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
