### PR TITLE
Removed extra padding on users page in mobile view

### LINKED ISSUE #5828: Users page has extra padding in mobile view
**Describe the bug**
There is extra padding on both sides for Users page in mobile view.

**To Reproduce**

1. Go to https://care.coronasafe.in/users
2. Open in mobile view
3. Compare with other pages in mobile view

**Expected behavior**
The padding should be same as that on other pages in mobile view.

**Screenshots**
image

Other pages:
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu1902**
## Proposed Changes
- Fixes #5828 
http://localhost:4000/users
Removed extra padding from Users page in mobile view
Mobile view:
image

Desktop view:
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at b77a4fc</samp>

* Remove extra margin and padding from page title ([link](https://github.com/coronasafe/care_fe/pull/5829/files?diff=unified&w=0#diff-a6a7ab3af39c9e2846bc2d69312a095aa77957d33c31ea4c0a70c034dfdfa121L419-R419))

### CODE REVIEW

File: src/Components/Users/ManageUsers.tsx [hunk 1]
```diff
@@ -416,7 +416,7 @@ export default function ManageUsers() {
     <Page
       title="User Management"
       hideBack={true}
-      className="mx-5 px-2"
+      className=""
```
Comment (rithviknishad) [inline src/Components/Users/ManageUsers.tsx]:
```suggestion
```

**Comment by nihal467** [comment]
LGTM
