### PR TITLE
FIXED: Input Overflow in Edit Administration Dialog

### LINKED ISSUE #11688: Input Overflow in Edit Administration Dialog
**Describe the bug**
The input fields in the "Edit Administration" dialog overflow, causing layout distortion on smaller screen sizes

**To Reproduce**

1. Go to 'Encounter'
2. switch to  'Medicines tab'
3. Click on 'Administrator button'

**Expected behavior**
Input fields should be fully visible and properly contained within the modal without overflow issues.

**Screenshots**

Image

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [135.0.6834.111]

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes

-  adjust size of input

- Fixes #11688 

Screenshot 2025-04-03 010852

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Enhanced styling for time input sections, ensuring consistent text size and appearance.
  - Adjusted input field widths for improved responsiveness and readability.
  - Modified maximum height and width constraints for dialog content to improve layout and scrolling behavior on smaller screens.

### CODE REVIEW

File: src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx [hunk 1]
```diff
@@ -373,7 +374,7 @@ export const MedicineAdminForm: React.FC<MedicineAdminFormProps> = ({
           </Popover>
           <Input
             type="time"
-            className="w-[150px]"
+            className="sm:w-[150px] w-[90px] text-sm"
```
Comment (AdityaJ2305) [inline src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: Can we  switch to using relative widths or rem instead of pixels ?

File: src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx [hunk 2]
```diff
@@ -435,7 +437,7 @@ export const MedicineAdminForm: React.FC<MedicineAdminFormProps> = ({
...
```
Comment (AdityaJ2305) [inline src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: same here

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

File: src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx (hunk 1 above)
Comment (modamaan) [reply src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: updated

File: src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx (hunk 2 above)
Comment (modamaan) [reply src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: updated

**Review by rithviknishad — CHANGES_REQUESTED** [review]
why hardcode size? 🤔 

why not just use `w-full` so that it takes available space?

File: src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx [hunk 3]
```diff
@@ -395,6 +396,7 @@ export const MedicineAdminForm: React.FC<MedicineAdminFormProps> = ({
                   "flex-1 justify-start text-left font-normal",
                   !administrationRequest.occurrence_period_end &&
                     "text-gray-500",
+                  "text-sm",
```
Comment (rithviknishad) [inline src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: why in a new line? why not just add it to the first line?

File: src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx [hunk 4]
```diff
@@ -329,7 +329,7 @@ export const MedicineAdminForm: React.FC<MedicineAdminFormProps> = ({
 
       <div className="space-y-2">
         <Label>{t("start_time")}</Label>
-        <div className="flex gap-2">
+        <div className="flex flex-row gap-2">
```
Comment (rithviknishad) [inline src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: isn't it flex-row by default? 🤔 correct me if i'm wrong

```suggestion
        <div className="flex gap-2">
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by modamaan** [comment]
> why hardcode size? 🤔
> 
> why not just use `w-full` so that it takes available space?

my bad

File: src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx [hunk 5]
```diff
@@ -373,7 +373,7 @@ export const MedicineAdminForm: React.FC<MedicineAdminFormProps> = ({
           </Popover>
           <Input
             type="time"
-            className="w-[150px]"
+            className="w-full text-sm"
```
Comment (rithviknishad) [inline src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: is this needed? 🤔 let's NOT deviate from design system please!
```suggestion
            className="w-full"
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by modamaan** [comment]
image
we cant give `w-full` because its effect the styling

**Comment by rithviknishad** [comment]
we can give w-full with max-w right?

**Comment by modamaan** [comment]
we need text-sm for smaller mobile screen for better alignment

**Review by rithviknishad — DISMISSED** [review]

**Comment by rithviknishad** [comment]
you haven't tested this on mobile? 🤔 

marking checklist items as checked without properly checking will lead PRs to be closed without reviews next time!

image

**Comment by modamaan** [comment]
oh,  tested on every phone

**Comment by modamaan** [comment]
Screenshot 2025-04-03 180646
Screenshot 2025-04-03 180706

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Adding scroller is better way to fix responsivness, do not adjust padding unnecessarily. This may not guarantee responsiveness on all devices.

Refer this: https://github.com/ohcnetwork/care_fe/pull/11685

File: src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx [hunk 6]
```diff
@@ -373,7 +373,7 @@ export const MedicineAdminForm: React.FC<MedicineAdminFormProps> = ({
           </Popover>
           <Input
             type="time"
-            className="w-[150px]"
+            className="w-full max-w-[6rem] sm:max-w-[9.5rem] text-sm sm:text-base"
```
Comment (yash-learner) [inline src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: image

AM/PM are not visible 

Either increase the max-w- value a bit or try adding some padding

Comment (modamaan) [reply src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: can you please share the device name

Comment (modamaan) [reply src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: image
 i cant see issue on these devices

Comment (rithviknishad) [reply src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: just use responsive mode and always test upto 320px width

Comment (modamaan) [reply src/components/Medicine/MedicationAdministration/MedicineAdminForm.tsx]: https://github.com/user-attachments/assets/0654d9a0-8b62-4759-bd86-b82177a0249f

can we add `max-w-screen` for avoid horizontal scrolling

**Comment by yash-learner** [comment]
@modamaan have you tested it on real mobile using the deploy-preview url?

**Comment by modamaan** [comment]
@yash-learner    Yeah,  I got the problem, I can fix tonight

**Comment by modamaan** [comment]
https://github.com/user-attachments/assets/1afb25e6-f8a0-4753-b8b2-6c3717a8d4c9

**Review by yash-learner — APPROVED** [review]
LGTM

**Review by rithviknishad — APPROVED** [review]

File: src/components/Medicine/MedicationAdministration/MedicineAdminDialog.tsx [hunk 7]
```diff
@@ -67,7 +67,7 @@ export const MedicineAdminDialog = ({
 
   return (
     <Dialog open={open} onOpenChange={onOpenChange}>
-      <DialogContent className="sm:max-w-[525px]">
+      <DialogContent className="max-h-screen overflow-auto max-w-screen">
```
[the remark this answers is not in the document]
Comment (rithviknishad) [reply src/components/Medicine/MedicationAdministration/MedicineAdminDialog.tsx]: @modamaan

[the remark this answers is not in the document]
Comment (modamaan) [reply src/components/Medicine/MedicationAdministration/MedicineAdminDialog.tsx]: updated

**Review by rithviknishad — APPROVED** [review]
