### PR TITLE
Show no information card if consultation and sample test history list is empty

### LINKED ISSUE #7501: No Information if list is empty.
**Describe the bug**
In consultation and sample test history, if there's no record, proper information must be provided to the user.

**To Reproduce**

1. Go to Patients tab
2. Click on any unknown patient
3. Scroll down to the end.

**Expected behavior**
A proper message must be provided 
Screenshot 2024-03-31 at 11 24 16 PM

**Screenshots**
Screenshot 2024-03-31 at 11 07 24 PM

### PR DESCRIPTION
**Pull request by Sulochan-khadka**
## Proposed Changes

- Fixes #7501 
- Added WhenEmpty component

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

File: src/Components/Facility/PatientNotesSlideover.tsx [hunk 1]
```diff
@@ -199,32 +199,36 @@ export default function PatientNotesSlideover(props: PatientNotesProps) {
...
+                border={false}
+                className="absolute right-2"
+                ghost
+                size="small"
+                disabled={!patientActive}
+                authorizeFor={NonReadOnlyUsers}
+              >
+                <CareIcon className="care-l-message text-lg" />
+              </ButtonV2>
+            </div>
```
Comment (rithviknishad) [inline src/Components/Facility/PatientNotesSlideover.tsx]: Why was this changed? Totally unrelated to the issue being solved right?

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Give a meaningful title to the PR
Refer: https://github.com/coronasafe/care_fe?tab=readme-ov-file#contributing-to-care

File: src/Components/Facility/PatientNotesSlideover.tsx (hunk 1 above)
Comment (Sulochan-khadka) [reply src/Components/Facility/PatientNotesSlideover.tsx]: To Make the layout better... Since very soon, upload icon will also be added and so thought making a layout before would be better. Just rearrangement, thats it. Will remove if you say.

Comment (rithviknishad) [reply src/Components/Facility/PatientNotesSlideover.tsx]: Unrelated to the issue being solved by this PR. Feel free to file a separate issue if so.

Comment (Sulochan-khadka) [reply src/Components/Facility/PatientNotesSlideover.tsx]: Should I remove them and file separate issue for this as well?

Comment (rithviknishad) [reply src/Components/Facility/PatientNotesSlideover.tsx]: Just saw this was addressed in another PR. Need not file an issue

Comment (Sulochan-khadka) [reply src/Components/Facility/PatientNotesSlideover.tsx]: Yeah... actually that was addressed before this, both by me, therefore, it happened so.

Comment (Sulochan-khadka) [reply src/Components/Facility/PatientNotesSlideover.tsx]: Also changed the title as was instructed.

Comment (rithviknishad) [reply src/Components/Facility/PatientNotesSlideover.tsx]: @Sulochan-khadka you've not pushed any changes plus the PR title still doesn't make sense. Refer the above link and see other PR's for example...

**Comment by Sulochan-khadka** [comment]
Have removed the unrelated code... @rithviknishad Let me have a review of yours...

**Comment by Sulochan-khadka** [comment]
@rithviknishad , I have resolved the conflicts. Kindly do the needful. Thanks

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@Sulochan-khadka 

image

- [ ] add a white padding, inside that padding write "No consultation History" similar to the No medical history available padding on the top

**Review by Ashesh3 — APPROVED** [review]

**Comment by Sulochan-khadka** [comment]
> @Sulochan-khadka
> 
> image
> 
> * [ ]  add a white padding, inside that padding write "No consultation History" similar to the No medical history available padding on the top

I think I implemented what you suggested...
Screenshot 2024-04-21 at 12 21 13 PM


Let me know if I got it wrong...

**Comment by Sulochan-khadka** [comment]
@nihal467 kindly have a review .

**Comment by Sulochan-khadka** [comment]
@nihal467 @Ashesh3 @rithviknishad kindly get this merged soon. Let me know if some modifications are required from my side. Thankyou.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
