### PR TITLE
Fix: Entering just whitespace in input fields still creates empty entries

### LINKED ISSUE #12621: Entering just whitespace in input fields still creates empty entries
**Describe the bug**
When submitting whitespace-only input (space) in these fields:  
- **Encounter Page** → Notes section  
- **Resource Requests** → Reason for Request field  

The system accepts it as valid input, creating:  
- Empty notes that clutter the UI  
- Resource requests with blank reasons

**To Reproduce**

1. Go to encouter page or resource request page
2. Click on Add Allergy, Add Diagnosis, and Add Symptom or reason of request section
3. Just enter a space and submit

**Expected behavior**
User should not be able to create empty notes, Also reason of request is not supposed to by bypassed with a whitespace.

**Screenshots**

https://github.com/user-attachments/assets/f992b635-b1de-400c-9363-9c483b2f2623

Image
Image
Image
Image
Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by perpetrator1**
## Proposed Changes

- Fixes #12621

This pull request introduces changes to improve the handling and sanitization of user-provided `note` fields and ensures string inputs are trimmed before validation. These updates enhance data cleanliness and consistency across the application.

###  Added `note` sanitization:

- Added a `sanitizeNote` utility function to trim and conditionally handle empty `note` fields. This function is now applied to `note` fields in datapoints for allergies, medications, symptoms, and diagnoses, ensuring consistent sanitization before submission.

### String trimming for validation:

- Updated the `note` field in the `consentFormSchema` to trim whitespace before validation.
- Modified the `reason` field to trim whitespace and ensure it meets the minimum length requirement.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Notes and reason fields in various forms now automatically remove leading and trailing whitespace when you finish editing, ensuring cleaner input.
- **Bug Fixes**
  - Improved consistency of note and reason field formatting by trimming unnecessary whitespace across multiple forms.

### CODE REVIEW

File: src/Utils/utils.ts [hunk 1]
```diff
@@ -333,3 +333,9 @@ export function getWeeklyIntervalsFromTodayTill(pastDate?: Date | string) {
 
   return intervals;
 }
+
+export const trimNote = (note?: string): string | undefined => {
```
Comment (AdityaJ2305) [inline src/Utils/utils.ts]: let not have it as utility since it's a global utility folder , not need it for simple task 

checkout comment below

File: src/components/Consent/ConsentFormSheet.tsx [hunk 2]
```diff
@@ -497,6 +498,13 @@ export default function ConsentFormSheet({
                       className="w-full field-sizing-content focus:outline-none focus:ring-1 focus:ring-primary-500 focus:border-primary-500 rounded-md"
                       rows={3}
                       {...field}
+                      onBlur={(e) => {
+                        const trimmed = trimNote(e.target.value);
+                        if (trimmed !== e.target.value) {
+                          e.target.value = trimmed ?? "";
+                          field.onChange(e);
+                        }
+                      }}
```
Comment (AdityaJ2305) [inline src/components/Consent/ConsentFormSheet.tsx]:
```suggestion
                      onBlur={(e) => {
                        e.target.value = e.target.value.trim();
                        field.onChange(e);
                      }}
```

File: src/components/Resource/ResourceForm.tsx [hunk 3]
```diff
@@ -475,6 +475,13 @@ export default function ResourceForm({ facilityId, id }: ResourceProps) {
                       data-cy="reason-input"
                       placeholder={t("request_reason_placeholder")}
                       onChange={(value) => field.onChange(value)}
+                      onBlur={(e) => {
+                        const trimmed = trimNote(e.target.value);
+                        if (trimmed !== e.target.value) {
+                          e.target.value = trimmed ?? "";
+                          field.onChange(e);
+                        }
+                      }}
```
Comment (AdityaJ2305) [inline src/components/Resource/ResourceForm.tsx]:
```suggestion
                      onBlur={(e) => {
                        e.target.value = e.target.value.trim();
                        field.onChange(e);
                      }}
```

File: src/components/Consent/ConsentFormSheet.tsx (hunk 2 above)
Comment (AdityaJ2305) [reply src/components/Consent/ConsentFormSheet.tsx]: same changes for rest of the places

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

**Review by rithviknishad — CHANGES_REQUESTED** [review]
i don't think this is a scalable solution

**Comment by AdityaJ2305** [comment]
@perpetrator1 , At least for `forms` we can directly use .trim() in zod validation schema 
eg: ConsentForm and ResourceForm in this PR

**Comment by perpetrator1** [comment]
@rithviknishad Do you have any suggestions?

**Comment by nihal467** [comment]
image

- empty entries are still allowed for notes in structured question, do reverify the functionality before requesting a review

**Comment by perpetrator1** [comment]
> image
> 
> - empty entries are still allowed for notes in structured question, do reverify the functionality before requesting a review

@nihal467 It wont get submitted to the backend, when you submit the questionnaire. That was the plan. You can check the encounter page to verify (It wont show see notes at all if you enter whitespaces and submit)

**Comment by nihal467** [comment]
image

- check the console error

steps to replicate

- add new allergy with empty allergy
- now option the add allergy form again, and try to add new allergy and submit it
- there are console error

**Comment by perpetrator1** [comment]
@rithviknishad @nihal467 Ive edited the sanitizeNote function to handle null values, its no longer throwing console errors and now the questionnaire gets submitted when we click submit.

**Comment by nihal467** [comment]
LGTM

File: src/components/Questionnaire/structured/handlers.ts [hunk 4]
```diff
@@ -26,6 +26,16 @@ type StructuredHandler<T extends StructuredQuestionType> = {
...
 
+const sanitizeNote = (
+  note?: string | null,
+  hasId?: boolean,
+): string | undefined => {
+  if (note === undefined || note === null) return undefined;
+  const trimmed = note.trim();
+  if (trimmed !== "") return trimmed;
+  return hasId ? "" : undefined;
+};
```
Comment (rithviknishad) [inline src/components/Questionnaire/structured/handlers.ts]: i don't understand what `hasId` has got to do with sanitizing note... something feels off here.

Comment (perpetrator1) [reply src/components/Questionnaire/structured/handlers.ts]: It is to handle empty notes based on whether the record already exists in the database

With hasId:

https://github.com/user-attachments/assets/546e1db5-ec77-4b16-9c46-a91e2c521364

Without hasId:

https://github.com/user-attachments/assets/84d0df14-a979-4b6a-b28b-a29340dd840a

Comment (perpetrator1) [reply src/components/Questionnaire/structured/handlers.ts]: @rithviknishad Lemme know which one you prefer

Comment (Jacobjeevan) [reply src/components/Questionnaire/structured/handlers.ts]: Hmm, that seems like data isn't refreshed/query isn't being invalidated - so address that instead.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Comment by perpetrator1** [comment]
> ### Bug: Whitespace Input Creates Empty Notes
> The `sanitizeNote` function returns an empty string (`""`) when its input contains only whitespace. This allows empty notes to be created, which contradicts the PR's goal of preventing empty entries from whitespace-only input. The function should return `undefined` in such cases.
> 
> `src/components/Questionnaire/structured/handlers.ts#L28-L32`
> [Fix in Cursor](https://cursor.com/open?data=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJ1Z2JvdC12MSJ9.eyJ2ZXJzaW9uIjoxLCJ0eXBlIjoiQlVHQk9UX0ZJWF9JTl9DVVJTT1IiLCJkYXRhIjp7InJlZGlzS2V5IjoiYnVnYm90OjQ4NjNkOWY1LTNlYmItNGU5MC04OTAxLTMwYmU4ZGNhNDNkZCIsImVuY3J5cHRpb25LZXkiOiJYempxUTcwaXF3VUxQSDVmVnNhNU5zU0pYUWxNWE9QZ04zejhUbi1PcEtzIiwiYnJhbmNoIjoiaXNzdWVzLzEyNjIxL3doaXRlLXNwYWNlcyJ9LCJpYXQiOjE3NTMyOTA4ODUsImV4cCI6MTc1Mzg5NTY4NX0.Ksj_d1xZ-7mtjeOHtSl5heTHCGzOe8RKpMyRQqgI0e9UKoz4WEplf7Gemc5pRvBPO4c17nNuYfOM-w6g9F8r0zdY4E6uEyFYUAFXyI3WphJLdUc34QL_wepRR9DGV5NAiyPuKiZLFknyG7rAOjRCW7q0pO8Xeaez0m8tp4boythedrkbEm6S-teqamtmU9k5Y7Mv8JAeiAccw3LxjxjhI9ijg4qFijVGlax1IcMU0EU4oFQ5ZQgRot6zTHCkeqcPCZJ0R6VY77pd-JL_-JPk8ahKLDPyBw0MhZqj-JErGxa53htTFiZ0IVMfrPx0dMU-92lpG0M_bzfjgd92aSG3sQ) • [Fix in Web](https://cursor.com/agents?data=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJ1Z2JvdC12MSJ9.eyJ2ZXJzaW9uIjoxLCJ0eXBlIjoiQlVHQk9UX0ZJWF9JTl9XRUIiLCJkYXRhIjp7InJlZGlzS2V5IjoiYnVnYm90OjQ4NjNkOWY1LTNlYmItNGU5MC04OTAxLTMwYmU4ZGNhNDNkZCIsImVuY3J5cHRpb25LZXkiOiJYempxUTcwaXF3VUxQSDVmVnNhNU5zU0pYUWxNWE9QZ04zejhUbi1PcEtzIiwiYnJhbmNoIjoiaXNzdWVzLzEyNjIxL3doaXRlLXNwYWNlcyIsInJlcG9Pd25lciI6Im9oY25ldHdvcmsiLCJyZXBvTmFtZSI6ImNhcmVfZmUiLCJwck51bWJlciI6MTI2NTQsImNvbW1pdFNoYSI6IjU3MDM3MDZhODFkMTc1NmIwNDY2OWIyNDkwOGE4NWFiZmZhOGVmNjAifSwiaWF0IjoxNzUzMjkwODg1LCJleHAiOjE3NTM4OTU2ODV9.SGMWwwWtmnN5Z89bejR-bpGpCZwDqLurez_HkSG3BsagHaFK11VxFbUQd8c5K8ULP9mVaO5dvopXEnSKnvtqqYvjB6pXf8N_xcTYtM-msiYwlMGOQLr0hUT2BNPOZqH2xE096SZdexlPkEkJKdgcXbCGuZmLonehJtpVlJE7-IZKPCElP_UO35f7zsuFen1ote7Wa9GDxk3dPXIC4TyThaBGBbr06vDCJ4ZvKQuNL5LmaK0hOcwj0M9zLJFaT_jng5vbNPnhH4IuyE4LyDEcra794de6tZcoWPV9Y0IgFXbavXCf_parssYeOqRL9bW_A0h3MUAKNmsWnMKhAfxfgA)
> 
> _Was this report helpful? Give feedback by reacting with 👍 or 👎_

Uhm no

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

**Comment by nihal467** [comment]
LGTM

File: src/components/Questionnaire/structured/handlers.ts [hunk 5]
```diff
@@ -26,6 +26,11 @@ type StructuredHandler<T extends StructuredQuestionType> = {
   >;
 };
 
+const sanitizeNote = (note?: string | null): string | undefined => {
+  if (note === undefined || note === null) return undefined;
+  return note.trim();
```
Comment (rithviknishad) [inline src/components/Questionnaire/structured/handlers.ts]:
```suggestion
  return note?.trim() ?? undefined;
```

**Review by rithviknishad — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
