### PR TITLE
Fix: Incorrect Icon in Patient nav bar | Facility switcher hovering and some minor fixes

### LINKED ISSUE #10074: Incorrect Icon in Patient nav bar | Facility switcher hovering and some minor fixes
Task 1 : Cancel appointment button is active even after cancellation in appointment details dialogue and use detructive variant for cancelled badge

Image

Task 2 : Facility and Organization switcher on hovering appearing gray it should be green

Image

Task 3 :  Incorrect icon for Nearby facilities. It should be d-hospital icon

Image

### PR DESCRIPTION
**Pull request by Rishith25**
## Proposed Changes

- Fixes #10074

- [x] Task 1 : Use destructive variant for cancelled badge
- [x] Task 2 : Facility and Organization switcher on hovering appearing gray it should be green
- [x] Task 3 : Incorrect icon in patient nav bar

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Localization**
	- Added new translation entries for medical terminology: "Onset", "Severity", and "Symptom"
	- Implemented internationalization in Diagnosis and Symptom tables

- **UI Improvements**
	- Enhanced cursor and focus styles in dropdown menus
	- Updated patient navigation icon for nearby facilities
	- Modified appointment status badge to highlight cancelled appointments

- **Minor Changes**
	- Updated creator display to show username instead of full name in tables

### CODE REVIEW

File: src/components/Patient/diagnosis/DiagnosisTable.tsx [hunk 1]
```diff
@@ -83,10 +86,7 @@ export function DiagnosisTable({
                 className="w-4 h-4"
                 imageUrl={diagnosis.created_by?.profile_picture_url}
               />
-              <span className="text-sm">
-                {diagnosis.created_by?.first_name}{" "}
-                {diagnosis.created_by?.last_name}
-              </span>
+              <span className="text-sm">{diagnosis.created_by?.username}</span>
```
Comment (rithviknishad) [inline src/components/Patient/diagnosis/DiagnosisTable.tsx]: why?

File: src/components/Patient/symptoms/SymptomTable.tsx [hunk 2]
```diff
@@ -83,9 +86,7 @@ export function SymptomTable({
                 className="w-4 h-4"
                 imageUrl={symptom.created_by?.profile_picture_url}
               />
-              <span className="text-sm">
-                {symptom.created_by?.first_name} {symptom.created_by?.last_name}
-              </span>
+              <span className="text-sm">{symptom.created_by?.username}</span>
```
Comment (rithviknishad) [inline src/components/Patient/symptoms/SymptomTable.tsx]: why?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Patient/diagnosis/DiagnosisTable.tsx (hunk 1 above)
Comment (Rishith25) [reply src/components/Patient/diagnosis/DiagnosisTable.tsx]: @rithviknishad
firstname and lastname are not displayed so I displayed the username instead same as in case of allergies. But it is addressed in #10017.
In the response firstname and lastname are coming as empty string. Anyways i reverted the changes

**Review by rithviknishad — CHANGES_REQUESTED** [review]
why not just add the cursor pointer class to DropdownMenuItem directly anyways since that is expected on all usages?

**Review by rithviknishad — APPROVED** [review]
