### PR TITLE
Redirect to Original URL After Session Expiry and Re-login

### LINKED ISSUE #6486: Redirect to Original URL After Session Expiry and Re-login
**Issue:**

Currently, when a user's session expires on a specific page, they are correctly redirected to the "Session Expired" page which subsequently leads them to the login page. However, after re-logging in, instead of being redirected to their last active page (where their session had expired), they are taken to the home page. This disrupts user flow and can lead to confusion or a poor user experience.

**Expected Behavior:**

Upon re-login after a session expiry, users should be redirected to the URL of their last active page, thereby preserving the context of their work or activity.

**Steps to Reproduce:**
1. Navigate to any page in the application.
2. Wait for the session to expire.
3. You'll be redirected to the session expired page.
4. Proceed to the login page.
5. After logging in, observe that you're taken to the home page instead of the page where the session had originally expired.

**Potential Solution:**

Preserve the URL of the page where the session expires and utilize this URL to redirect the user post re-login.

### PR DESCRIPTION
**Pull request by AshrafMd-1**
### <samp>🤖 Generated by Copilot at a838ca7</samp>

This pull request enhances the login redirection logic to take into account the user's last visited path before session expiry. It uses the local storage to store and retrieve the `lastPath` value, which is updated by the `fireRequest` function in `src/Redux/fireRequest.tsx` and used by the `Login` component in `src/Components/Auth/Login.tsx`.

## Proposed Changes

- Fixes #6486 
- Redirect to the Original URL After Session Expiry and Re-login

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at a838ca7</samp>

*  Store the last visited path before session expiry in the local storage ([link](https://github.com/coronasafe/care_fe/pull/6495/files?diff=unified&w=0#diff-e2c5c73d556d02503d5adc253828ddf5bad94f6fb9fba25df333d5ca6b9b5c56R155-R156))
*  Redirect the user to the last visited path after logging in, if it exists, or to the `/facility` path otherwise ([link](https://github.com/coronasafe/care_fe/pull/6495/files?diff=unified&w=0#diff-4c2858c07a7b7999725237900da3d8bc7f685382ae64b974f06a7b06d3c82304L112-R118))

### CODE REVIEW

File: src/Components/Auth/Login.tsx [hunk 1]
```diff
@@ -109,7 +109,13 @@ export const Login = (props: { forgot?: boolean }) => {
...
           window.location.pathname === "/login"
         ) {
-          window.location.href = "/facility";
+          const lastPath = localStorage.getItem("lastPath");
+          if (lastPath) {
+            localStorage.removeItem("lastPath");
+            window.location.href = lastPath;
+          } else {
+            window.location.href = "/facility";
+          }
```
Comment (rithviknishad) [inline src/Components/Auth/Login.tsx]: Use query params instead of local storage.

something like, `/session-expired?redirect=<url encoded url of the last url>`

File: src/Redux/fireRequest.tsx [hunk 2]
```diff
@@ -152,6 +152,8 @@ export const fireRequest = (
           if (error.response.status > 400 && error.response.status < 500) {
             if (error.response.data && error.response.data.detail) {
               if (error.response.data.code === "token_not_valid") {
+                //store the path before session expiry in local storage
+                localStorage.setItem("lastPath", window.location.href);
```
Comment (rithviknishad) [inline src/Redux/fireRequest.tsx]: This behavior shouldn't be coupled with `fireRequest`. Instead just replace all navigates to `/session-expired` to `/session-expired?redirect=<url encoded location href>`.

fireRequest is deprecated.

```suggestion
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by Ashesh3 — CHANGES_REQUESTED** [review]
Resolve this open redirect security issue:

POC: https://deploy-preview-6495--care-egov-staging.netlify.app/session-expired?redirect=https://google.com

**Review by Ashesh3 — CHANGES_REQUESTED** [review]
This is still vulnerable to open redirection attack, 

POC (Access while logged out): https://deploy-preview-6495--care-egov-staging.netlify.app/?redirect=.my.subdomain.attacker.com/virus

File: src/Components/Auth/Login.tsx [hunk 3]
```diff
@@ -109,7 +109,12 @@ export const Login = (props: { forgot?: boolean }) => {
           window.location.pathname === "/" ||
           window.location.pathname === "/login"
         ) {
-          window.location.href = "/facility";
+          const redirectParam = new URLSearchParams(window.location.search).get(
+            "redirect"
+          );
+          redirectParam
+            ? (window.location.href = window.location.origin + redirectParam)
```
Comment (Ashesh3) [inline src/Components/Auth/Login.tsx]: This is still vulnerable to open redirection attack,

POC (Access while logged out): [deploy-preview-6495--care-egov-staging.netlify.app/?redirect=.my.subdomain.attacker.com/virus](https://deploy-preview-6495--care-egov-staging.netlify.app/?redirect=.my.subdomain.attacker.com/virus)

**Review by Ashesh3 — CHANGES_REQUESTED** [review]

**Comment by AshrafMd-1** [comment]
now it adds a / in between of the .my.subdomian 
do you want me to sanitise the redirect further like remove any . or other symbols in front of the redirect?
@Ashesh3

**Comment by Ashesh3** [comment]
> now it adds a / in between of the .my.subdomian do you want me to sanitise the redirect further like remove any . or other symbols in front of the redirect? @Ashesh3

@AshrafMd-1 The POC to redirect to a different domain still works 😅 , It can be exploited to redirect to a different website.

POC: https://deploy-preview-6495--care-egov-staging.netlify.app/session-expired?redirect=https://google.com

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@AshrafMd-1 you also need to add the redirect param to `/session-expired` navigate in `handleResponse.ts` file.

image

**Comment by Ashesh3** [comment]
Try to think of a different way to pass the redirect url across pages/components 🤔 Something like the session expired page can silently pass the redirect url to the login component internally without exposing it through the URL. @rithviknishad any suggestions?

**Comment by rithviknishad** [comment]
We could use the custom hook we have `useAppHistory` (which would inherently be prone from the attack mentioned before)

**Comment by rithviknishad** [comment]
The `history` from `useAppHistory` contains all previously visited URLs (as long as the page was not refreshed)

**Comment by AshrafMd-1** [comment]
Maybe we can check if the `history` from `useAppHistory` matches the site domain and then redirect

**Comment by rithviknishad** [comment]
This history from useAppHistory would always match the site domain

**Comment by AshrafMd-1** [comment]
> We could use the custom hook we have `useAppHistory` (which would inherently be prone from the attack mentioned before)

As we are doing `window.location.href="/session-expired"` we are losing all the history we have 
tried it with `navigate()` but that is directly changing the page URL to `/` or going on a refresh loop

**Comment by rithviknishad** [comment]
The navigate should work, why is it navigating to `/` or going into the refresh loop?

**Comment by rithviknishad** [comment]
You should be using the second element from the stack if it exists. (The first element would always be the current route)

**Comment by AshrafMd-1** [comment]
>  The navigate should work, why is it navigating to `/` or going into the refresh loop?

image
image

The issue arises from the `isAuthenticated` function continuing to return `true`, even when the token is incorrect. Furthermore, I can keep the browsing history intact until the session expiration page, but when I attempt to navigate to the login page, the entire history is wiped clean.

As a solution, I reached out to @rithviknishad , who suggested revisiting the query parameter approach. Now, the recommendation is to check if the origin of the redirect URL matches the origin of care.

@Ashesh3 , I'm currently implementing the query parameter approach.

**Comment by rithviknishad** [comment]
@Ashesh3 does this seem fine?

**Comment by Ashesh3** [comment]
> @Ashesh3 does this seem fine?

Yep, seems fine.

**Comment by AshrafMd-1** [comment]
@Ashesh3 once check

**Comment by AshrafMd-1** [comment]
@Ashesh3 once check

**Review by Ashesh3 — APPROVED** [review]
LGTM

File: src/Components/Auth/Login.tsx [hunk 4]
```diff
@@ -109,7 +109,20 @@ export const Login = (props: { forgot?: boolean }) => {
...
+            if (
+              redirectParam &&
+              new URL(redirectParam).origin === window.location.origin
+            )
+              window.location.href =
+                window.location.origin + new URL(redirectParam).pathname;
+            else window.location.href = "/facility";
+          } catch {
+            window.location.href = "/facility";
+          }
```
Comment (rithviknishad) [inline src/Components/Auth/Login.tsx]: we could refactor this out to a global function, right? 

(https://codeclimate.com/github/coronasafe/care_fe/pull/6495)

**Review by rithviknishad — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@AshrafMd-1 it is not taking me to the original URL after the session expired

https://www.loom.com/share/00dccbb8d6cb41cf80bf582eb51c6572?sid=4c94d3f8-74d6-474c-9e3e-7b59204be434

CC : @Ashesh3 @rithviknishad

**Comment by AshrafMd-1** [comment]
@nihal467 it works now
The issue was with merging this PR with develop

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
