### PR TITLE
fix: department filter with child selection

### LINKED ISSUE #16182: Child department in filters does not open.
https://github.com/10bedicu/care_fe/issues/44

"encounter filter section, the child departments cannot be selected. Clicking the dropdown arrow beside a parent department selects the parent instead of expanding to show child departments."

Image

### PR DESCRIPTION
**Pull request by abhimanyurajeesh**
## Proposed Changes
Was not able to select the child department nor able to search.

Fixes #16182

image
Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Bug Fixes**
  * Department colors now display consistently.

* **Improvements**
  * Enhanced search functionality with better department filtering.
  * Improved department selection interaction and UI layout.
  * Better organization and visual presentation of available departments.

### CODE REVIEW

File: src/components/ui/multi-filter/departmentFilter.tsx [hunk 1]
```diff
@@ -173,50 +183,109 @@ function DepartmentFilterDropdown({
...
+                        className={cn(
+                          "size-3 rounded-full shrink-0 border",
+                          getColorForOrg(org.id),
+                        )}
+                      />
+                      <div className="min-w-0 flex-1">
+                        <span className="text-sm truncate block">
+                          {org.name}
+                        </span>
+                        {org.parent && org.parent.name && (
```
Comment (Jacobjeevan) [inline src/components/ui/multi-filter/departmentFilter.tsx:223]: hmm can have common sub parents (Cardiology -> ICU -> Sub dept vs Neurology -> ICU -> Sub dept).

So we might have to display whole chain; But might not look nice when doing so. Can break it up/use tooltip to display whole chain, but won't be enough for tablets 🤔

**Review by Jacobjeevan — APPROVED** [review]
Otherwise lgtm

**Comment by parvathyns-creator** [comment]
@nihal467 this looks fine

File: src/components/ui/multi-filter/departmentFilter.tsx (hunk 1 above)
Comment (Jacobjeevan) [reply src/components/ui/multi-filter/departmentFilter.tsx:223]: cc: @abhimanyurajeesh

Comment (abhimanyurajeesh) [reply src/components/ui/multi-filter/departmentFilter.tsx:223]: Noted, will inform @vinutv for next iteration. This is when searching right!?
