### PR TITLE
Fix QR code error notification

### LINKED ISSUE #7708: Modify QR code error notification
**Describe the bug**

- [ ] When we scan a valid QR Code but that asset is not accessible with my user-id privilege, the error throw is "Something went wrong"

**To Reproduce**

1. Go to the asset tab and scan a QR code
2. See error

**Expected behavior**

- [ ] show the proper notification for the above-mentioned scenario 

**Screenshots**

image

image

### PR DESCRIPTION
**Pull request by AshrafMd-1**
## Proposed Changes

- Fixes #7708 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

File: src/Components/Assets/AssetsList.tsx [hunk 1]
```diff
@@ -116,7 +116,14 @@ const AssetsList = () => {
         const { data } = await request(routes.listAssets, {
           query: { qr_code_id: assetId },
         });
-        return data?.results[0].id;
+        if (data?.results.length === 0) {
+          setIsLoading(false);
+          Notification.Error({
+            msg: "You are not authorized to view this asset",
+          });
+        } else {
```
Comment (khavinshankar) [inline src/Components/Assets/AssetsList.tsx]: This looks good, can you make the notification generic meaning, something like Asset not found or not authorized to access this asset.

File: src/Components/Assets/AssetsList.tsx [hunk 2]
```diff
@@ -116,7 +116,14 @@ const AssetsList = () => {
...
+          return data?.results[0].id;
```
Comment (khavinshankar) [inline src/Components/Assets/AssetsList.tsx]: Also, if it is just to get a single asset, consider using get API instead of list

**Review by khavinshankar — CHANGES_REQUESTED** [review]

File: src/Components/Assets/AssetsList.tsx (hunk 2 above)
Comment (AshrafMd-1) [reply src/Components/Assets/AssetsList.tsx]: @khavinshankar  The get API doesn't have qr search facility so that's the reason the list is used

Comment (rithviknishad) [reply src/Components/Assets/AssetsList.tsx]: https://careapi.ohc.network/swagger/#/asset_qr/api_v1_public_asset_qr_retrieve

Comment (AshrafMd-1) [reply src/Components/Assets/AssetsList.tsx:125]: @rithviknishad when we are using listAsset API if we are in the wrong login it gives 0 results but where as getQR API returns it even if the user is not authorized 

So instead of no assets it will show invalid QR

Comment (AshrafMd-1) [reply src/Components/Assets/AssetsList.tsx:125]: image


It shows error here saying not found

Comment (AshrafMd-1) [reply src/Components/Assets/AssetsList.tsx]: @rithviknishad when we are using listAsset API if we are in the wrong login it gives 0 results but where as getQR API returns it even if the user is not authorized

So instead of no assets it will show invalid QR

Comment (AshrafMd-1) [reply src/Components/Assets/AssetsList.tsx]: image
here it shows error saying not found 404

Like just wanted to know on what conditions we must allow assets

Comment (rithviknishad) [reply src/Components/Assets/AssetsList.tsx]: then let's continue using the list api itself since that worked so far... let's avoid changing things if it was working so far?
Instead pass query parameter: `limit: 1` to fetch only 1 item max.

**Comment by AshrafMd-1** [comment]
@khavinshankar is this okay?

i have combined the asset not found to invalid qr

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@AshrafMd-1 
image

- [ ] something went wrong error is still shown along with the invalid QR code
- [ ] When a staff user scans a valid QR code, but they do not having access to it, due to no access to the asset. So, throwing an "Invalid QR code" error won't make sense, it would be better in these scenerio's to throw a "You don't have permission to access this asset" notification, which will be more proper.

**Comment by AshrafMd-1** [comment]
@nihal467 can you check once

**Comment by AshrafMd-1** [comment]
ready for testing

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
