### PR TITLE
Minor Improvement of UI of medicine tab in patient dashboard page

### LINKED ISSUE #3384: Minor Improvement of UI of medicine tab in patient dashboard page.
**Describe the bug**
- The Prescription time beside the **prescription** heading looks weird in Samsung Fold Device 
- Horizontal padding is required in the box containing the message "No Consultation Updates Found" in **Consultation Updates** section

**To Reproduce**

1. Go to Patients Dashboard
2. Click on Medicine Tab in Samsung Fold Device
3. See error

**Expected behavior**
- The Prescription Time should come down the next line below the Prescription Heading
- Horizontal padding should be added in the box containing the message "No Consultation Updates Found" in **Consultation Updates** section

**Screenshots**
image

### PR DESCRIPTION
**Pull request by patelaryan7751**
## Proposed Changes

Fixes #3384 

- The Prescription Time should come down the next line below the Prescription Heading
- Horizontal padding should be added in the box containing the message "No Consultation Updates Found" in Consultation Updates section
image

@coronasafe/reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by cp-Coder — APPROVED** [review]

File: src/Components/Facility/ConsultationDetails.tsx [hunk 1]
```diff
@@ -901,9 +901,9 @@ export const ConsultationDetails = (props: any) => {
             )}
             {consultationData.discharge_advice && (
               <div className="mt-4">
-                <h3 className="flex text-lg font-semibold leading-relaxed text-gray-900">
+                <h3 className="flex flex-wrap justify-between text-lg font-semibold leading-relaxed text-gray-900">
                   Prescription
-                  <div className="ml-3 text-xs text-gray-600 mt-2">
+                  <div className="text-xs text-gray-600 mt-2">
```
Comment (developedBySJ) [inline src/Components/Facility/ConsultationDetails.tsx]:
```suggestion
                  <div className="text-xs text-gray-600">
```

File: src/Components/Facility/ConsultationDetails.tsx [hunk 2]
```diff
@@ -901,9 +901,9 @@ export const ConsultationDetails = (props: any) => {
             )}
             {consultationData.discharge_advice && (
               <div className="mt-4">
-                <h3 className="flex text-lg font-semibold leading-relaxed text-gray-900">
+                <h3 className="flex flex-wrap justify-between text-lg font-semibold leading-relaxed text-gray-900">
```
Comment (developedBySJ) [inline src/Components/Facility/ConsultationDetails.tsx]: Instead of applying display flex to the `<h3>`.
Structure like
```jsx
<div className="flex">
   <h3>Prescription</h3>
   <h3>
         <i className="fas fa-history text-sm pr-2"></i>
          {consultationData.modified_date && moment(consultationData.modified_date).format("lll")}
   </h3>
</div>
```

**Review by developedBySJ — CHANGES_REQUESTED** [review]

**Comment by nihal467** [comment]
@patelaryan7751 once the work is completed, change it to need testing

**Comment by nihal467** [comment]
@patelaryan7751 
image

moving the time from left to right in the normal view was intentional or not ! as currently staging it is on the left near the prescription heading !

**Comment by patelaryan7751** [comment]
@nihal467 It was not intentional i have fixed the bug
image

Now the page would look like this in samsung fold

image

**Comment by nihal467** [comment]
test approved

**Comment by khavinshankar** [comment]
@developedBySJ can you rereview this one?

**Comment by nihal467** [comment]
@patelaryan7751 merge the latest development branch and check the cypress test is passing or not,

**Review by gigincg — APPROVED** [review]
