### PR TITLE
UI Fix: Move the View Details button below the title

### LINKED ISSUE #13329: Title is getting truncate for mobile screen for healthcare service card
### Describe
Refer to the image, Title shouldn't truncate to show view detail button as title is main focus instead think about some other position for view detail button for mobile screen or just show arrow icon for mobile screen 
>[!note]
Note for core members: Please review the expected behaviour mentioned above and finalise which one to go ahead with or any other one 

>[!note]
The changes need to be done for **Healthcare service** page and **service** page and its **children** since all have same design 

### Steps to Reproduce
- Go to any facility 
- See the option for Service in sidebar and healthcare service under setting 
- see the page on mobile size 

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by LibinThankayathil**
## Proposed Changes

Fixes #13329 
- add flex col for small devices
- wrapped the icon and text together
- made the View Details button in full width in small devices

image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

- **Refactor**
  - Extracted per-service UI into a reusable ServiceCard component; service list pages now render ServiceCard for each item, delegating presentation and navigation.
- **Style**
  - Redesigned Healthcare Service cards for a more compact, responsive two-zone layout (stacked on small screens, side-by-side on md+).
  - Consolidated actions into a single inline “View details” button (full-width on small screens, right-aligned on md+); improved alignment, spacing, icon consistency and text truncation.

### CODE REVIEW

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

**Review by AdityaJ2305 — COMMENTED** [review]
The changes need to be done for Healthcare service page and service page and its children since all have same design

File: src/pages/Facility/services/FacilityServices.tsx [hunk 1]
```diff
@@ -34,40 +34,46 @@ function ServiceCard({
...
-        <div className="flex-1 min-w-0">
-          <h3 className="font-semibold truncate text-gray-900 text-base">
-            {service.name}
-          </h3>
-          <p className="mt-0.5 text-xs text-gray-500 truncate">
-            {service.extra_details}
-          </p>
+            variant="outline"
+            size="sm"
+            className="px-3 text-xs whitespace-nowrap w-full md:w-auto md:ml-auto"
```
Comment (Jacobjeevan) [inline src/pages/Facility/services/FacilityServices.tsx]: is ml-auto needed? 🤔

File: src/pages/Facility/services/FacilityServices.tsx [hunk 2]
```diff
@@ -34,40 +34,46 @@ function ServiceCard({
...
-          <ColoredIndicator
-            id={service.id}
-            className="absolute inset-0 rounded-sm opacity-20"
-          />
-          <CareIcon
-            icon={
-              service.styling_metadata?.careIcon
-                ? getIconName(service.styling_metadata.careIcon)
-                : "d-health-worker"
+      <CardContent className="py-3 px-4">
```
Comment (Jacobjeevan) [inline src/pages/Facility/services/FacilityServices.tsx]: Let's extract out ServiceCard into its own file in /healthcareService and reuse it.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by yash-learner — APPROVED** [review]
LGTM
