### PR TITLE
fix: show dropdown options instead of selected text on prefix edit

### LINKED ISSUE #12121: Prefix Dropdown Shows Selected Text Instead of Options on Edit User
**Describe the bug**
When editing a user profile and clicking on the "Prefix" dropdown, the currently selected prefix (e.g., "Dr.") appears as selected text in the input field instead of showing the list of options.

**To Reproduce**

1, Go to the 'Profile' Tab.
2. Click on 'Edit User'.
3. Click on the prefix input/dropdown.
4. Observe that the current value is selected as text in the input, and the dropdown does not immediately show all options.

https://github.com/user-attachments/assets/27885a9c-71c0-43ab-a4f5-984a4759fe25

**Expected behavior**
The dropdown should open and display all available prefix options. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by siva222003**
## Proposed Changes

- Fixes #12121
- Removed the condition that preset the previously selected value in `CommandInput`

[Screencast from 2025-05-09 11-22-18.webm](https://github.com/user-attachments/assets/0a86a287-bbc1-43d2-ab45-649a3afdbf48)

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Refactor**
  - Improved input handling in the autocomplete component for better user input flexibility.
  - Enhanced user form layout with a more responsive grid design for name fields.

### CODE REVIEW

**Comment by siva222003** [comment]
Hey @rithviknishad Please review this

**Comment by rithviknishad** [comment]
lgtm, can we get the responsiveness issue also sorted while we are at it? 🤔 


https://github.com/user-attachments/assets/d4117fe2-7ee9-486f-a09e-b9294a383972

**Comment by siva222003** [comment]
@rithviknishad Sure, I thought of adding it as well. Will let you know once it's added.

**Comment by siva222003** [comment]
@rithviknishad check this once

[Screencast from 2025-05-09 12-55-53.webm](https://github.com/user-attachments/assets/ad024dd5-2aa4-45bd-982c-6c432dcd745b)

**Comment by siva222003** [comment]
@rithviknishad check this once

[Screencast from 2025-05-09 18-48-49.webm](https://github.com/user-attachments/assets/028a0696-cf50-4164-a800-7ac39691696d)

File: src/components/ui/autocomplete.tsx [hunk 1]
```diff
@@ -214,12 +212,17 @@ export default function Autocomplete({
           variant="outline"
           role="combobox"
           aria-expanded={open}
-          className={cn("w-full justify-between", className)}
+          className={cn("min-w-0 justify-between", className)}
```
Comment (rithviknishad) [inline src/components/ui/autocomplete.tsx]: can we not change this and instead pass a className to override `w-full` if necessary? 🤔 

this would break many other existing usages

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by siva222003** [comment]
@rithviknishad Please review the new changes

**Review by rithviknishad — APPROVED** [review]
