### PR TITLE
fix: validate quantity unit and set default unit in specimen form

### LINKED ISSUE #15104: Quantity Unit Field Shows "Required" Error Despite Pre-filled Value in Specimen Collection Form
**Describe the bug**
When collecting a specimen, the quantity unit field is pre-filled with a default unit value based on the specimen definition's container capacity. However, after filling in the quantity value and clicking the "Collect" button, the form validation incorrectly displays a "This field is required" error for the quantity unit field, even though it has a pre-filled value.

**To Reproduce**
1. Navigate to a Service Request that requires specimen collection
2. Open the "Collect Specimen" form
3. Observe that the Quantity unit field is pre-filled with the default unit (e.g., "milliliter") from the specimen definition
4. Enter a valid quantity value in the "Quantity" field (e.g., "5")
5. Click the "Collect" button
6. See error: "This field is required" appears under the Quantity unit field

Make sure AD specimen has unit 

**Expected behavior**
The form should validate successfully without displaying a required field error for the quantity unit when:

The unit field has a pre-filled default value from the specimen definition
The quantity value has been entered by the user
Both required fields have valid data

**Screenshots**

Image

additional context: https://github.com/ohcnetwork/care_fe/pull/14943

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by abhimanyurajeesh**
## Proposed Changes

Fixes #15104
- set default unit in specimen form
- If the default is defined, don’t allow the user to change the unit. 

image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Bug Fixes & Improvements**
  * Validation now requires a unit only when no default unit is configured, preventing unnecessary errors.
  * Submission data normalizes specimen quantity so a unit is always included when applicable.
  * Quantity input enforces a minimum value of 1 to avoid invalid entries.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/pages/Facility/services/serviceRequests/components/SpecimenForm.tsx [hunk 1]
```diff
@@ -413,7 +419,7 @@ export function SpecimenForm({
                           });
                         }
                       }}
-                      disabled={disableEdit}
+                      disabled={disableEdit || !!defaultUnit}
```
Comment (yash-learner) [inline src/pages/Facility/services/serviceRequests/components/SpecimenForm.tsx]: why disable ?

**Review by Jacobjeevan — APPROVED** [review]

**Review by yash-learner — APPROVED** [review]

**Review by bodhish — APPROVED** [review]
