### PR TITLE
Fix nested button issue when opening an encounter

### LINKED ISSUE #14623: Fix nested button issue when opening an encounter
**Describe the bug**
When opening an encounter, we get a console error about nested buttons.

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Deepcode007**
## Proposed Changes

Fixes #14623
### Description:
This PR fixes a React hydration error caused by invalid HTML nesting (<'button'> inside <'button'>) in `EncounterAccordionLayout.tsx`.

### Changes:
- Refactored `EncounterAccordionLayout` to remove the outer CollapsibleTrigger wrapper (which renders a <'button'>), replacing it with a semantic div to preserve the layout.
- Wrapped the specific chevron icon/button with `CollapsibleTrigger` using **asChild** so only the icon acts as the accordion toggle.
- Cleaned up the className by removing an unnecessary `hover:no-underline` utility from the div.
- Added accessibility improvements:
  - Added dynamic aria-label to the chevron toggle button to indicate "expand" or "collapse" state.
  - Added missing translation keys "expand" and "collapse" to `public/locale/en.json`.

Tagging: @ohcnetwork/care-fe-code-reviewers @SiddanthNayak 

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Accessibility Improvements**
  * Added "Collapse" and "Expand" button labels for improved screen reader support and clearer user interactions with expandable sections.

* **UI Refinements**
  * Restructured expand/collapse controls within accordion components for better organization and interaction clarity.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by adarsh-priydarshi-5646 — COMMENTED** [review]
@Deepcode007 CI is failing because of lint errors. Could you please address the lint issues and update the PR?

**Comment by Deepcode007** [comment]
> @Deepcode007 CI is failing because of lint errors. Could you please address the lint issues and update the PR?

Sure @adarsh-priydarshi-5646 , I'm Looking into it.

File: src/components/Patient/EncounterAccordionLayout.tsx [hunk 1]
```diff
@@ -61,21 +61,24 @@ export function EncounterAccordionLayout({
...
+                    className="hover:bg-transparent text-gray-500 hover:text-gray-500"
+                    aria-label={isExpanded ? t("collapse") : t("expand")}
+                  >
+                    {isExpanded ? (
+                      <ChevronsDownUp className="size-4 text-gray-500" />
+                    ) : (
+                      <ChevronsUpDown className="size-4 text-gray-500" />
+                    )}
+                  </Button>
+                </CollapsibleTrigger>
```
[the remark this answers is not in the document]
Comment (Deepcode007) [reply src/components/Patient/EncounterAccordionLayout.tsx:78]: @coderabbitai look last 2 commits, fixed in those.

**Comment by Deepcode007** [comment]
After adding `React.forwardRef` to button, **`Vite`** threw a error: 
("`validateServiceRequestQuestion`" export is **incompatible**).

I searched about it and found that,
### Reason:
Vite's "Fast Refresh" (Hot Module Replacement) has a strict rule:
**A file that exports a React component should only export React components.**
`ServiceRequestQuestion.tsx` was exporting a component (`ServiceRequestQuestion`) AND a utility function (`validateServiceRequestQuestion`). This confuses the reloader because it doesn't know how to safely "hot swap" the file without losing state if there are mixed exports.
### The Fix:
I moved the utility function into a separate file (`ServiceRequestQuestionUtils.ts`).
### Result:
Now `ServiceRequestQuestion.tsx` only exports a component, satisfying Vite's rules for Fast Refresh.

Hence I added a new file `ServiceRequestQuestionUtils.ts`

**Comment by Deepcode007** [comment]
Hence, requesting the maintainers to take a look at it and suggest changes if required.
Thank you!
@SiddanthNayak @Jacobjeevan

File: src/components/Questionnaire/QuestionTypes/ServiceRequestQuestionUtils.ts [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+      .filter(([_, field]) => field.required && !value[field.key])
+      .map(([_, field]) => ({
+        question_id: questionId,
+        error: "field_required" as const,
+        type: "validation_error" as const,
+        field_key: field.key,
+        index,
+      }));
+
+    return [...errors, ...fieldErrors];
```
[the remark this answers is not in the document]
Comment (Deepcode007) [reply src/components/Questionnaire/QuestionTypes/ServiceRequestQuestionUtils.ts]: @coderabbitai review. Fixed in latest commit.

File: src/components/Questionnaire/QuestionTypes/ServiceRequestQuestionUtils.ts [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+  return values.reduce((errors: QuestionValidationError[], value, index) => {
+    const fieldErrors = Object.entries(SERVICE_REQUEST_FIELDS)
+      .filter(([_, field]) => field.required && !value[field.key])
+      .map(([_, field]) => ({
+        question_id: questionId,
+        error: "field_required" as const,
+        type: "validation_error" as const,
+        field_key: field.key,
+        index,
+      }));
```
[the remark this answers is not in the document]
Comment (Deepcode007) [reply src/components/Questionnaire/QuestionTypes/ServiceRequestQuestionUtils.ts]: @coderabbitai review. Fixed in latest commit.

File: src/components/ui/button.tsx
Comment (AdityaJ2305) [inline src/components/ui/button.tsx:1]: changes in shadcn components aren't allowed

File: src/components/Questionnaire/QuestionTypes/ServiceRequestQuestion.tsx
Comment (AdityaJ2305) [inline src/components/Questionnaire/QuestionTypes/ServiceRequestQuestion.tsx:1]: any reason for this change ?? Looks unrelated to issue

Comment (Deepcode007) [reply src/components/Questionnaire/QuestionTypes/ServiceRequestQuestion.tsx:1]: > After adding React.forwardRef to button, Vite threw a error:
> ("validateServiceRequestQuestion" export is incompatible).
> 
> I searched about it and found that,
> 
> Reason:
> Vite's "Fast Refresh" (Hot Module Replacement) has a strict rule:
> A file that exports a React component should only export React components.
> ServiceRequestQuestion.tsx was exporting a component (ServiceRequestQuestion) AND a utility function (validateServiceRequestQuestion). This confuses the reloader because it doesn't know how to safely "hot swap" the file without losing state if there are mixed exports.
> 
> The Fix:
> I moved the utility function into a separate file (ServiceRequestQuestionUtils.ts).
> 
> Result:
> Now ServiceRequestQuestion.tsx only exports a component, satisfying Vite's rules for Fast Refresh.
> 
> Hence I added a new file ServiceRequestQuestionUtils.ts

@AdityaJ2305 
Due to this issue.
Any suggestions?

File: src/components/ui/button.tsx
Comment (Deepcode007) [reply src/components/ui/button.tsx:1]: @coderabbitai suggested.

> ⚠️ Potential issue | 🔴 Critical
🧩 Analysis chain
Wrap the Button component with React.forwardRef to properly support asChild in Radix UI collapsibles.

shall i revert back to the commit just before it?

File: src/components/Questionnaire/QuestionTypes/ServiceRequestQuestion.tsx
Comment (Deepcode007) [reply src/components/Questionnaire/QuestionTypes/ServiceRequestQuestion.tsx:1]: @AdityaJ2305  Fixed in this commit, please review.

https://github.com/ohcnetwork/care_fe/pull/15393/commits/f49f5d5191c6455c64c23087810cb25ce1f7cc4f

**Comment by Deepcode007** [comment]
@coderabbitai review and post your review as comment, removed unwanted changes in the latest commit(used force-push as i reset to a previous commit)

**Review by AdityaJ2305 — APPROVED** [review]
LGTM

**Review by bodhish — APPROVED** [review]
