### PR TITLE
Fixed #13956: Made 'No Records Found' message input specific

### LINKED ISSUE #13956: Search Patients – Incorrect "No Records Found" Message
In the **Search Patients** page, the "No Patient Records Found" message is misleading.  

- When searching by **phone number**:  
  If no match is found, the message shown is correct:  
  > "No existing records found with this phone number. Would you like to register a new patient?"  

- When searching by **patient name**:  
  If no match is found, the **same phone number–specific message** is displayed, which is incorrect.  

---

## Steps to Reproduce  
1. Navigate to **Search Patients**.  
2. Select **Search by Patient Name**.  
3. Enter a name that doesn’t exist.  
4. Observe the message → still refers to **phone number**.  

---

## Expected Behavior  
Error messages should be **contextual** to the selected search method:  
- For **phone number** → keep the current message.  
- For **patient name** → show a message like:  
  *"No existing records found with this name. Would you like to register a new patient?"*  

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Ishu813**
## Proposed Changes

Fixes #13956
- Passed a value which updates input type and gives the correct `No Records Found` message.
- Updated `en.json`.

**Screen Recording**

https://github.com/user-attachments/assets/5a82657c-e6ec-4d78-aedb-22cdbf52e2ed

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

- New Features
  - The “No patient record found” message now dynamically reflects the selected identifier type (e.g., phone number, ID), improving clarity when searches return no results.
  - Patient search view updates the message based on your chosen search option, providing more contextual feedback during searches.

- Chores
  - Locale updated to support a dynamic placeholder in the no-results message, enabling identifier-based text substitution without altering existing keys.

### CODE REVIEW

File: src/components/Patient/PatientIndex.tsx [hunk 1]
```diff
@@ -205,7 +207,11 @@ export default function PatientIndex({ facilityId }: { facilityId: string }) {
                             {t("no_patient_record_found")}
                           </h3>
                           <p className="text-sm text-gray-500 mb-6">
-                            {t("no_patient_record_text")}
+                            {selectedOptionIdx === 0
+                              ? t("no_patient_record_with_phone")
+                              : selectedOptionIdx == 1
+                                ? t("no_patient_record_with_name")
+                                : t("no_patient_record_with_identifier")}
```
Comment (AdityaJ2305) [inline src/components/Patient/PatientIndex.tsx]: Let's not do this way !! 
What if there is change in options in future ? 

Can you look for some other approach ?

File: public/locale/en.json [hunk 2]
```diff
@@ -3200,7 +3200,9 @@
   "no_patient_is_finished": "No tokens have been finished",
   "no_patient_is_waiting": "No patient is waiting in this queue",
   "no_patient_record_found": "No Patient Records Found",
-  "no_patient_record_text": "No existing records found with this phone number. Would you like to register a new patient?",
+  "no_patient_record_with_identifier": "No existing records found with this identifier. Would you like to register a new patient?",
+  "no_patient_record_with_name": "No existing records found with this name. Would you like to register a new patient?",
+  "no_patient_record_with_phone": "No existing records found with this phone number. Would you like to register a new patient?",
```
Comment (AdityaJ2305) [inline public/locale/en.json]: don't need to create key for each option

We can have only one and pass variable into that right ?

File: src/components/Patient/PatientIndex.tsx (hunk 1 above)
Comment (Ishu813) [reply src/components/Patient/PatientIndex.tsx]: @AdityaJ2305 I have changed the approach....pls have a look over it.

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

File: src/components/Patient/PatientIndex.tsx [hunk 3]
```diff
@@ -205,7 +207,9 @@ export default function PatientIndex({ facilityId }: { facilityId: string }) {
                             {t("no_patient_record_found")}
                           </h3>
                           <p className="text-sm text-gray-500 mb-6">
-                            {t("no_patient_record_text")}
+                            {t("no_patient_record_text", {
+                              text: selectedOption?.toLowerCase(),
```
Comment (AdityaJ2305) [inline src/components/Patient/PatientIndex.tsx]: This won't translate the text passed right ? and AFAIK we can not have translation key for every identifier so IMO we should stick to some generic message. 

Wait for core member's comment on it

**Comment by nihal467** [comment]
@khavinshankar can you look into it

File: src/components/Patient/PatientIndex.tsx (hunk 3 above)
Comment (khavinshankar) [reply src/components/Patient/PatientIndex.tsx]: yes, this is a wrong approach, the `text` will not be translated!

nice catch @AdityaJ2305

Comment (khavinshankar) [reply src/components/Patient/PatientIndex.tsx]: @Ishu813 instead of passing `selectedOption` as text, can u instead find identifierSearch.config.display and pass that

**Review by khavinshankar — CHANGES_REQUESTED** [review]
@Ishu813 instead of passing selectedOption as text, can u instead find identifierSearch.config.display and pass that

**Comment by Ishu813** [comment]
> @Ishu813 instead of passing selectedOption as text, can u instead find identifierSearch.config.display and pass that

@khavinshankar There is no `identifierSearch.config.display` but I have used `getSearchOptions` instead. Pls have a look on the changes made.

**Comment by nihal467** [comment]
LGTM, can you add a Playwright test to ensure the functionality of the changes from your PR, since the PR checklist have been modified

File: src/components/Patient/PatientIndex.tsx [hunk 4]
```diff
@@ -205,7 +205,15 @@ export default function PatientIndex({ facilityId }: { facilityId: string }) {
...
                           <p className="text-sm text-gray-500 mb-6">
-                            {t("no_patient_record_text")}
+                            {t("no_patient_record_text", {
+                              text: getSearchOptions(
+                                t,
+                                identifierSearch,
+                                facility,
+                              ).find(
+                                (opt) => opt.key === identifierSearch.config,
+                              )?.type,
```
Comment (abhimanyurajeesh) [inline src/components/Patient/PatientIndex.tsx]:
```suggestion
                              )?.display,
```

Comment (Ishu813) [reply src/components/Patient/PatientIndex.tsx]: Should I use `.display` instead of `.type` pls confirm

**Review by AdityaJ2305 — APPROVED** [review]
