### PR TITLE
Redesign: Departments page root view 

### LINKED ISSUE #10374: Redesign the root view of facility department section
**Describe the bug**

Redesign the existing root department view of a facility to our new figma design

**Link to figma**

https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=7769-7339&p=f&t=lATfj2xH4or01kbE-0

**Existing view**

Image

*New View*

Image

### PR DESCRIPTION
**Pull request by DonXavierdev**
## Proposed Changes

- Fixes #10374 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Improved localization with new language entries for more intuitive prompts and user guidance.
	- Redesigned the organization management interface with an interactive, expandable table view and filtering functionality for a clearer hierarchical display of departments and teams. 
	- Added tooltips for enhanced user interaction within the organization management interface.

### CODE REVIEW

**Comment by DonXavierdev** [comment]
@nihal467 Review required

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 1]
```diff
@@ -85,43 +92,216 @@ export default function FacilityOrganizationIndex({
...
+    const toggleAllChildren = () => {
+      setExpandedRows((prevExpandedRows) => {
+        const newExpandedRows = { ...prevExpandedRows };
+        const toggleChildren = (parentId: string, expand: boolean) => {
+          getChildren(parentId).forEach((child) => {
+            newExpandedRows[child.id] = expand;
+            toggleChildren(child.id, expand);
+          });
+        };
+        const shouldExpand = !children.some(
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]:
```suggestion
        const shouldExpand = !children.every(
```

If user has expanded some and then clicks expand all, it should still expand rather than collapsing.

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 2]
```diff
@@ -85,43 +92,216 @@ export default function FacilityOrganizationIndex({
...
+                    <Button
+                      variant="outline"
+                      className="h-7 shadow-gray-400 border-gray-400 sm:p-2 sm:text-sm text-xs p-1"
+                      onClick={toggleAllChildren}
+                    >
+                      <CareIcon
+                        icon="l-plus"
+                        className="h-4 w-4 sm:h-2 sm:w-2"
+                      />
+                      {t("expand_all")}
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: display collapse all if everything is expanded

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 3]
```diff
@@ -85,43 +92,216 @@ export default function FacilityOrganizationIndex({
...
+            <TableHead className="w-[80%] border text-[#374151]  bg-[#f3f4f6]">
+              {t("name")}
+            </TableHead>
+            <TableHead className="bg-[#f3f4f6] text-[#374151]">
+              {t("category")}
+            </TableHead>
+          </TableRow>
+        </TableHeader>
+        <TableBody>
+          {data.results
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: For readability - do the filtering earlier and set to a diff variable and use that here.

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 4]
```diff
@@ -9,18 +10,25 @@ import {
...
+} from "@/components/ui/table";
 
 import Page from "@/components/Common/Page";
 import { CardGridSkeleton } from "@/components/Common/SkeletonLoading";
 
 import routes from "@/Utils/request/api";
 import query from "@/Utils/request/query";
-import { FacilityOrganization } from "@/types/facilityOrganization/facilityOrganization";
 
 import CreateFacilityOrganizationSheet from "./components/CreateFacilityOrganizationSheet";
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: absolute import

File: public/locale/en.json [hunk 5]
```diff
@@ -2027,6 +2032,8 @@
   "titrate_dosage": "Titrate Dosage",
   "to": "to",
   "to_be_conducted": "To be conducted",
+  "to_create_a_new_one": "to create a new one",
+  "to_open_manage_users_or_create_more_departments_teams_within_it": "to open manage users or create more departments/teams within it",
```
Comment (Jacobjeevan) [inline public/locale/en.json]: minor thing, but let's shorten this key 😄

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 6]
```diff
@@ -85,43 +92,216 @@ export default function FacilityOrganizationIndex({
...
+              ) : null}
+              {org.name}
+            </div>
+            {isTopLevel && (
+              <>
+                {children.length > 0 ? (
+                  <>
+                    <Button
+                      variant="outline"
+                      className="h-7 shadow-gray-400 border-gray-400 sm:p-2 sm:text-sm text-xs p-1"
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: Let's override styles, instead write a new variant if necessary.

In this case, white variant fits (not same as figma, but bit more subtle).

Comment (Jacobjeevan) [reply src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: try xs or sm size for expand/collapse button.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 7]
```diff
@@ -9,38 +10,44 @@ import {
...
       pathParams: { facilityId },
-      queryParams: {
-        parent: "",
-      },
+      queryParams: { limit: LIMIT },
     }),
     enabled: !!facilityId,
   });
-
+  const TableData = data?.results || [];
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]:
```suggestion
  const tableData = data?.results || [];
```

naming convention; capitalization for components.

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 8]
```diff
@@ -85,43 +92,206 @@ export default function FacilityOrganizationIndex({
...
+    return (
+      <>
+        <TableRow
+          key={org.id}
+          style={{ "--indent": `${indent * 20}px` } as React.CSSProperties}
+        >
+          <TableCell
+            className={`${
+              isTopLevel
+                ? "bg-white font-bold text-[#030712]"
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: Replace the custom text/bg/border etc with tailwind classes.

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 9]
```diff
@@ -85,43 +92,206 @@ export default function FacilityOrganizationIndex({
...
+        toggleChildren(org.id, shouldExpand);
+        return newExpandedRows;
+      });
+    };
+    const allExpanded = children.every((child) => expandedRows[child.id]);
+    return (
+      <>
+        <TableRow
+          key={org.id}
+          style={{ "--indent": `${indent * 20}px` } as React.CSSProperties}
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: use rem over px

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 10]
```diff
@@ -85,43 +92,206 @@ export default function FacilityOrganizationIndex({
...
+                <button onClick={() => toggleRow(org.id)} className=" mr-1">
+                  {expandedRows[org.id] ? (
+                    <CareIcon icon="l-angle-down" className="h-5 w-5" />
+                  ) : (
+                    <CareIcon icon="l-angle-right" className="h-5 w-5" />
+                  )}
+                </button>
+              ) : org.parent && Object.keys(org.parent).length > 0 ? (
+                <CareIcon
+                  icon="l-corner-up-right"
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: `l-corner-down-right-alt` is the icon you were looking for 👍  you can search for icons at /icons

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
Hmm, we definitely need to do something for the mobile 🤔 

image

**Comment by DonXavierdev** [comment]
> Hmm, we definitely need to do something for the mobile 🤔
> 
😅 I actually wanted the mobile view to look like that . Earlier it had overflows and got clipped too.

**Comment by Jacobjeevan** [comment]
> > Hmm, we definitely need to do something for the mobile 🤔
> 
> 😅 I actually wanted the mobile view to look like that . Earlier it had overflows and got clipped too.

Alright, Vinu will design a mobile view later, we will focus on getting this merged first.

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx (hunk 8 above)
Comment (DonXavierdev) [reply src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: So the text-[#030712] over here. Should i add it as a custom color in the tailwind config or just replace with text-gray-900 . 
If it is to replace with a similar text-color.... i'll have to use `almost similar colors` defined by tailwind instead of the custom colors from the figma design .

**Comment by DonXavierdev** [comment]
```
                <button onClick={() => toggleRow(org.id)} className=" mr-1">
                  {expandedRows[org.id] ? (
                    <CareIcon icon="l-angle-down" className="h-5 w-5" />
                  ) : (
                    <CareIcon icon="l-angle-right" className="h-5 w-5" />
                  )}
                </button>
```
Changing this to shadCN button adds unusual padding,color and size
Should i replace this and fix that or is normal button fine ?

**Comment by DonXavierdev** [comment]
@Jacobjeevan need review on latest changes 😀

**Comment by Jacobjeevan** [comment]
@DonXavierdev Checking latest, you can hide the the button texts for smaller screens.

While you are at it, make this consistent as well. Having the button on the same row on opposite ends should work for smaller screens.

image

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 11]
```diff
@@ -80,38 +87,225 @@ export default function FacilityOrganizationIndex({
...
+                      >
+                        <CareIcon icon="l-eye" className="h-4 w-4" />
+                        <span className="hidden sm:inline">
+                          {t("see_details")}
+                        </span>
+                      </Link>
+                    </Button>
+                  </>
+                ) : (
+                  <Button variant="white" size={"sm"} asChild>
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: - You don't need to duplicate the code, display the expand all button for the check.
- Reduce button size for smaller devices
- Add tooltip for the buttons
- Align the see details button on right even when expand all doesn't exist (justify-end should work).
- Add some spacing between icon (l-corner-down-right-alt) and the text.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 12]
```diff
@@ -80,38 +93,235 @@ export default function FacilityOrganizationIndex({
...
+                      </TooltipTrigger>
+                      <TooltipContent>{t("see_details")}</TooltipContent>
+                    </Tooltip>
+                  </TooltipProvider>
+                </div>
+              </div>
+            )}
+          </TableCell>
+          <TableCell className="border-l bg-white font-semibold text-gray-900">
+            {org.org_type}
```
Comment (abhimanyurajeesh) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]:
```suggestion
            t(`facility_organization_type__${org.org_type}`)}
```

@DonXavierdev  Let's use translations

**Review by abhimanyurajeesh — COMMENTED** [review]
@DonXavierdev, Let's use translations.  Also there is an updated design for Mobile view, attaching bellow.

image

Figma: https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=8403-580&t=MJUMaQTobL23fyVM-0

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx (hunk 12 above)
Comment (DonXavierdev) [reply src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: @abhimanyurajeesh I feel this is unnecessary since we already have a header that says "Category". This would be repetitive in every row under it.

Comment (rithviknishad) [reply src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: we'll still need translations anyhow to map it to readable version in other languages, be it expanded or short form

Comment (DonXavierdev) [reply src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: @rithviknishad So should there be like dynamic translations for every category names and department names ?

**Comment by nihal467** [comment]
@DonXavierdev what is the status on this PR

**Comment by DonXavierdev** [comment]
> @DonXavierdev what is the status on this PR

Original redesign is over. Doing the mobile design

**Comment by DonXavierdev** [comment]
@Jacobjeevan Can you check and let me know about the current changes for mobile view ?

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 13]
```diff
@@ -80,38 +93,246 @@ export default function FacilityOrganizationIndex({
...
+                        variant="white"
+                        size={isMobile ? "xs" : "sm"}
+                        asChild
+                      >
+                        <Link
+                          href={`/departments/${org.id}`}
+                          className="text-gray-900 flex items-center"
+                        >
+                          <CareIcon
+                            icon={isMobile ? "l-arrow-up-right" : "l-eye"}
```
Comment (Jacobjeevan) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: Let's use the same icon; switch to using the arrow for desktop.

File: package-lock.json
Comment (Jacobjeevan) [inline package-lock.json:1]: Why is this in the commit? 🤔

File: public/locale/en.json [hunk 14]
```diff
@@ -2165,6 +2169,8 @@
   "titrate_dosage": "Titrate Dosage",
   "to": "to",
   "to_be_conducted": "To be conducted",
+  "to_create_new_one": "to create a new one",
+  "to_manage_create_more": "to open manage users or create more departments/teams within it",
```
Comment (Jacobjeevan) [inline public/locale/en.json]:
```suggestion
  "to_manage_create_more": "to create or manage users and departments/teams within the corresponding dept/team",
```

File: package-lock.json
Comment (DonXavierdev) [reply package-lock.json:1]: I am not sure. How can i revert this ?

Comment (DonXavierdev) [reply package-lock.json:1]: If there is no other change then please delete that file in remote. If i do it, it might cause conflicts

Comment (Jacobjeevan) [reply package-lock.json:1]: > I am not sure. How can i revert this ?

You can checkout package-lock from develop through `git checkout` with `--` command.

`git checkout develop -- package-lock.json`

and commit that.

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 15]
```diff
@@ -80,38 +93,246 @@ export default function FacilityOrganizationIndex({
...
+            {t("click")}{" "}
+            <span className="font-semibold">{t("add_department_team")}</span>{" "}
+            {t("to_create_new_one")}
+          </p>
+          <p className="">
+            {t("click")}{" "}
+            <span className="font-semibold">{t("see_details")}</span>{" "}
+            <CareIcon icon="l-arrow-up-right"></CareIcon>{" "}
+            {t("to_manage_create_more")}
+          </p>
```
Comment (rithviknishad) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: let's not do word by word translations; this will be incorrect in other languages as placement of words is not exactly as same as how it's placed in english; use `<Trans />` block to achieve translations with stylings. Checkout similar usages in the codebase.

File: src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx [hunk 16]
```diff
@@ -9,38 +13,47 @@ import {
...
+import CreateFacilityOrganizationSheet from "@/pages/Facility/settings/organizations/components/CreateFacilityOrganizationSheet";
 
 export default function FacilityOrganizationIndex({
   facilityId,
 }: {
   facilityId: string;
 }) {
+  const [expandedRows, setExpandedRows] = useState<Record<string, boolean>>({});
   const { t } = useTranslation();
+  const LIMIT = 1000;
```
Comment (rithviknishad) [inline src/pages/Facility/settings/organizations/FacilityOrganizationIndex.tsx]: use `query.paginated` to get all elements instead of hardcoding a high limit.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by nihal467** [comment]
image

- [ ] @DonXavierdev why are we having two different button for same purpose in the mobile view

**Comment by DonXavierdev** [comment]
> @DonXavierdev why are we having two different button for same purpose in the mobile view

@nihal467 Yeah so , the first button is for displaying sub-departments below it one by one and the other one is for expanding all the rows below it ( Seeing all sub-departments ) at once.

**Comment by nihal467** [comment]
LGTM

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]
