### PR TITLE
fix:Stop camera stream on closing dialog in Add Files

### LINKED ISSUE #12341: Camera Stays On After Clicking 'Close Camera" Button
**Describe the bug**
After clicking the "Close camera" button, the camera remains active instead of turning off.

**To Reproduce**

1.  Go to 'Encounters' -> "View Details"
2.  Click on 'Files' -> "Discharge Summary" -> "Add files" -> "Open camera".
3.  Click on "Close camera"
4. See error,  the camera continues to stay active.

https://github.com/user-attachments/assets/9c5035f1-ce55-4f05-b776-27ac58025995

**Expected behavior**
The camera should immediately turn off after clikcing the close camera button.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by sindhureddy-6**
## Proposed Changes

- Fixes #12341 

- Fixed camera stream leak by stopping media tracks when the dialog is closed.
- created useMediaStream hook
- used in Avatar Upload , Files upload in Encounter page

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - Added new localization messages for microphone permission denial and camera switching.

- **Refactor**
  - Streamlined camera and audio capture dialogs to use a unified, reusable media stream management system.
  - Centralized media permission requests for both video and audio, improving reliability and consistency across components.

- **Style**
  - Improved error handling and messaging for camera and microphone permissions.

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
Nice, however at this point I'd consider creating a re-usable hook called `useMediaStream` and refactor other similar usages as well to use this logic.

image

File: src/hooks/useMediaStream.ts [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+      timer = setTimeout(() => {
+        startStream();
+      }, 100);
+    }
+
+    return () => {
+      clearTimeout(timer);
+      stopStream();
+    };
+  }, [open, startStream, stopStream]);
```
[the remark this answers is not in the document]
Comment (AdityaJ2305) [reply src/hooks/useMediaStream.ts]: @sindhureddy-6 , do checkout comments by coderabbit if you find them valid changes , push the changes and resolve them (both cases whether changes are made or not ) applicable for all comments 👍

File: src/Utils/useMediaDevicePermission.ts [hunk 2]
```diff
@@ -21,11 +34,17 @@ export const useMediaDevicePermission = () => {
...
       } catch (_error) {
         if (!toastShownRef.current) {
           toastShownRef.current = true;
-          toast.warning(t("camera_permission_denied"));
+          const deviceType =
+            options.video && options.audio
+              ? "camera and microphone"
+              : options.video
+                ? "camera"
+                : "microphone";
```
Comment (rithviknishad) [inline src/Utils/useMediaDevicePermission.ts]: when used in another language, this would look as if two languages was mixed right?

**Review by rithviknishad — CHANGES_REQUESTED** [review]
mostly lgtm

File: src/Utils/useMediaDevicePermission.ts [hunk 3]
```diff
@@ -21,11 +34,12 @@ export const useMediaDevicePermission = () => {
...
         }
 
-        return { hasPermission: true, mediaStream: mediaStream };
+        return { hasPermission: true, mediaStream };
       } catch (_error) {
         if (!toastShownRef.current) {
           toastShownRef.current = true;
-          toast.warning(t("camera_permission_denied"));
+          const deviceType = options.video ? "camera" : "microphone";
+          toast.warning(t(`${deviceType}_permission_denied`));
```
Comment (rithviknishad) [inline src/Utils/useMediaDevicePermission.ts]: static analysis tools would still find it difficult to detect missing translation coverage on these lines.

```suggestion
          const deviceType = options.video ? "camera" : "microphone";
          toast.warning(options.video ? t("camera_permission_denied") : t("mic_permission_denied"));
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Common/CameraCapture.tsx [hunk 4]
```diff
@@ -0,0 +1,201 @@
...
+        )}
+      </div>
+
+      {/* Buttons for mobile screens */}
+      <div className="flex flex-col gap-2 pt-4 sm:flex-row">
+        {!previewImage ? (
+          <>
+            <Button variant="primary" onClick={handleSwitchCamera}>
+              <CareIcon icon="l-camera-change" className="text-lg" />
+              {`${t("switch")} ${t("camera")}`}
```
Comment (rithviknishad) [inline src/components/Common/CameraCapture.tsx]: although this was there in previous code, let's not translate word by word.

**Review by rithviknishad — APPROVED** [review]

File: src/components/Common/CameraCapture.tsx (hunk 4 above)
Comment (sindhureddy-6) [reply src/components/Common/CameraCapture.tsx]: okay. i will make it single word

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image

- In the file upload of the encounter, the releasing of cam is taking some time

**Comment by sindhureddy-6** [comment]
@nihal467 
can you test it now.

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
