### PR TITLE
Fix Translations in login page

### LINKED ISSUE #7260: Translations are not made properly in some places
**Describe the bug**
in forgot password page the back to login text is not translated and also the the error translations are not changing when we change the langunage they are changing after a reload

**To Reproduce**

1. Go to 'https://care.ohc.network'
2. Click on 'forgot password'
3. See error

**Expected behavior**
back to login is to be translated and those error messages need to be changed whenever the language is changed 

**Screenshots**
Screenshot 2024-02-23 174231

Screenshot 2024-02-23 173248

### PR DESCRIPTION
**Pull request by rash-27**
## Proposed Changes

- Fixes #7260
- Add correct translation in login page(for forgot password section)
- Errors also get translated dynamically when language is changed 
- 
@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
Screenshot 2024-02-23 200459
Screenshot 2024-02-23 200515

- [ ] Completion of QA

### CODE REVIEW

File: src/Providers/HistoryAPIProvider.tsx [hunk 1]
```diff
@@ -26,7 +26,7 @@ export default function HistoryAPIProvider(props: { children: ReactNode }) {
     },
     { onInitial: true }
   );
-
+  console.log(history);
```
Comment (rithviknishad) [inline src/Providers/HistoryAPIProvider.tsx]:
```suggestion
```

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
