### PR TITLE
Fix : Missing Cursor Pointer

### LINKED ISSUE #12270: Date Picker Quick Finder: Missing Cursor Pointer on Hover
**Describe the bug**
When hovering over the time buttons in date picker, the cursor is not changing to a pointer.

**To Reproduce**

1. Go to 'Appointments'
2. Click on 'Showing all appointments edit button'
3. Click on "Pick a date" -> "Quick Finder"
4. Hover over the time unit buttons (Days, Weeks, Months, Years)
5. The cursor doesn't change to a pointer.

https://github.com/user-attachments/assets/d9d74888-d056-4b68-bbe3-b211c0aba562

**Expected behavior**
The cursor should change to a pointer when hovering over the buttons.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #12270

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

https://github.com/user-attachments/assets/30280828-f301-49c5-8da5-595bc6fb45f7
- [x] Request for Peer Reviews

- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Updated the Relative Date Picker by replacing unit badges with buttons for clearer interaction.
  - Adjusted the layout and alignment of the displayed date for improved visual consistency.

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
let's change this to a button instead!

**Comment by Jeffrin2005** [comment]
@rithviknishad used sm for small size and adjusted to avoid the overflow in text for showing date.



https://github.com/user-attachments/assets/e8d6f5eb-b7c6-4c25-8ead-422c1b3ab460

File: src/components/ui/relative-date-picker.tsx [hunk 1]
```diff
@@ -164,21 +164,22 @@ export function RelativeDatePicker({
...
           </Select>
           {timeUnits.map((unit) => (
-            <Badge
+            <Button
               key={unit}
               onClick={() => handleUnitChange(unit)}
               variant={selected.unit === unit ? "default" : "outline"}
+              size="sm"
               className={
                 !validateDate(unit, 1) ? "opacity-50 pointer-events-none" : ""
```
Comment (rithviknishad) [inline src/components/ui/relative-date-picker.tsx]: this could be changed to disabled prop instead now that its a button right?

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by Jeffrin2005** [comment]
https://github.com/user-attachments/assets/c9a183e7-949b-4ed2-97fa-d32b8bfbf17e

**Review by rithviknishad — APPROVED** [review]
