### PR TITLE
fix: Handle page crash while submitting empty questionnaires

### LINKED ISSUE #11530: Bug: Page crash while submitting empty questionnaires
**Describe the bug**
While submitting some specific questionnaires, we are getting error

**To Reproduce**

1. Go to [link](https://care.ohc.network/facility/03560a09-121e-451a-a73a-64240cbfb1ae/patient/0c2ea73a-059d-4c9a-bd7c-eb1b3b683832/encounter/45123074-ce56-4066-acc0-cbc8ae234c9a/questionnaire/bodhish)
2. Click on submit
3. See error

**Expected behavior**
It should show proper error message that why it is crashing.

**Screenshots**

https://github.com/user-attachments/assets/0532dec9-6939-4f10-84f6-8a9b0f767d5e

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Tanuj1718**
## Proposed Changes

- Fixes #11530
- Add checks for preventing Page crash while submitting empty questionnaires

https://github.com/user-attachments/assets/e368f30e-38c8-46af-9701-288989e15a65

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
  - Enhanced the questionnaire form submission by ensuring that only responses with actual input values are processed, improving data accuracy.
  - Added error notification for users when no valid responses are found during submission.

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
can't we simply disable the submit button in the first place instead of all this? 🤔

**Comment by amjithtitus09** [comment]
@Tanuj1718 Once something is typed and then removed and then submitted, empty string is being passed in the request.
image

cc @nihal467

**Comment by Tanuj1718** [comment]
> can't we simply disable the submit button in the first place instead of all this? 🤔

@rithviknishad We can. But is there any problem in this approach or is it unoptimized? I have just added simple checks🤔

**Comment by Tanuj1718** [comment]
> @Tanuj1718 Once something is typed and then removed and then submitted, empty string is being passed in the request. image
> 
> cc @nihal467

@amjithtitus09 Is this the expected behaviour or am I missing something?

https://github.com/user-attachments/assets/dacaeebb-4f72-4710-b654-a9a5b7ffaf4d

File: src/components/Questionnaire/QuestionnaireForm.tsx [hunk 1]
```diff
@@ -646,8 +646,13 @@ export function QuestionnaireForm({
       const nonStructuredResponses = form.responses.filter(
         (response) => !response.structured_type,
       );
-
-      if (nonStructuredResponses.length > 0) {
+      const validResponses = nonStructuredResponses.filter(
+        (response) =>
+          response.values.length > 0 &&
+          !response.structured_type &&
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionnaireForm.tsx:648]: this is redundant given that it's already filtered above.

File: src/components/Questionnaire/QuestionnaireForm.tsx [hunk 2]
```diff
@@ -646,8 +646,13 @@ export function QuestionnaireForm({
...
+          response.values?.[0]?.value !== "",
+      );
+      if (validResponses.length > 0) {
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionnaireForm.tsx:652]: In this case, why even call submitBatch when there are no valid responses?

(ofc, assuming there are no structured from responses).

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/QuestionnaireForm.tsx [hunk 3]
```diff
@@ -656,42 +658,38 @@ export function QuestionnaireForm({
...
+                }
+                return { value: String(value.value) };
+              }),
+              note: response.note,
+              body_site: response.body_site,
+              method: response.method,
+            })),
           },
         });
+        submitBatch({ requests });
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionnaireForm.tsx]: Now, this would not submit the form if there were only structured question responses 😅  My bad with earlier feedback (but you should always test various scenarios if see if it works).

In this case, you don't need the else condition. You can keep submitBatch outside as earlier.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/QuestionnaireForm.tsx (hunk 3 above)
Comment (Tanuj1718) [reply src/components/Questionnaire/QuestionnaireForm.tsx]: I thought of this but if there is one structured response and one non structured , should it still get submitted?

Comment (Jacobjeevan) [reply src/components/Questionnaire/QuestionnaireForm.tsx]: yes

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
