### PR TITLE
Fix sentry error: TypeError:  Cannot read property 'focus' of null

### LINKED ISSUE #1738: TypeError: Cannot read property 'focus' of null
Sentry Issue: [CARE-FE-1SF](https://sentry.io/organizations/coronasafe-network/issues/2555823736/?referrer=github_integration)

```
TypeError: Cannot read property 'focus' of null
  at None (/static/js/2.cdf619f4.chunk.js:1:1991472)
  at r (/static/js/2.cdf619f4.chunk.js:1:2759983)
```

### PR DESCRIPTION
**Pull request by abhinandanarya06**
## About the error
- Sentry Link : [link](https://sentry.io/organizations/coronasafe-network/issues/2555823736/?project=5183632&query=is%3Aunresolved)
- **Page** : `/facility/<facility_id>/patient/<patient_id>`, Eg: [Staging Link](https://care.coronasafe.in/facility/fdad4400-bd11-49dd-9da1-5be0e79fa14e/patient/9f688106-0764-4a0a-a269-58577b6908e2)
- **Suspected component generating issue:** `Assign volunteer component`: `src/Components/Common/OnlineUsersSelect.tsx`
- **Reason for the suspected component:** 
  - `focus` method is only called in this component without check for null. 
  - After refactoring by adding types, now typescript show error of possible null pointer error.

## Changes done
- [x] Remove unused imports. 51e45258aa54c35bfb0ff9bc24a7d0578e209b1e
- [x] Added types for `State` and `Props`. 224a7ce1c79872c526987f0d4fd141b8b85f05da
- [x] Remove console warning for `OnlineUserSelect` Component only for now. cb7436c30ede2195fa14d21507095d4a02b2c255
- [x] Correct spelling from `UserModal` to `UserModel` in whole codebase. 56f5a1c020e023f20207a3d42bd6fd11535ae45f
- [x] Fix sentry issue [`TypeError:  Cannot read property 'focus' of null`](https://sentry.io/organizations/coronasafe-network/issues/2555823736/?project=5183632&query=is%3Aunresolved)

closes #1738

### CODE REVIEW

File: src/Components/Common/OnlineUsersSelect.tsx [hunk 1]
```diff
@@ -1,37 +1,47 @@
...
+type State = {
+  loading: boolean;
+  isExpanded: boolean;
+  users: Array<any>;
+  searchTerm: string;
+  searchFieldRef: React.RefObject<HTMLInputElement>;
+};
+
+type Props = {
+  selectedUser: any;
```
Comment (arpancodes) [inline src/Components/Common/OnlineUsersSelect.tsx]: while we are at it, can we ignore this any as well?

File: src/Components/Common/OnlineUsersSelect.tsx [hunk 2]
```diff
@@ -1,37 +1,47 @@
...
+  userId: string;
+  onSelect: any;
+  user_type: string;
+};
+
+const initialState: State = {
+  loading: false,
+  isExpanded: false,
+  users: new Array<any>(),
```
Comment (arpancodes) [inline src/Components/Common/OnlineUsersSelect.tsx]: same with this we can have a user model, if it isn't present right now... and replace the instances if any.

**Review by arpancodes — CHANGES_REQUESTED** [review]
Test the PR once 😅

You can add the sentry issue number in your commit messages so it can automatically resolve the issue upon merging.

File: src/Components/Common/OnlineUsersSelect.tsx (hunk 1 above)
Comment (ghost) [reply src/Components/Common/OnlineUsersSelect.tsx]: Yeah i think it would be better to add model types one by one with fixing sentry issue. Let me add the `User` model type

Comment (ghost) [reply src/Components/Common/OnlineUsersSelect.tsx]: oh nice user model is already there in the codebase 😂

**Review by gigincg — APPROVED** [review]
