### PR TITLE
 Fix:  hover cursor in encounters

### LINKED ISSUE #9886: Cursor Issue: Pointer Active Throughout Encounter Section
**Describe the bug**
The mouse pointer is incorrectly displaying across the entire encounter section. The mouse pointer should only become active when hovering directly over buttons.

**To Reproduce**

1. Go to "Encounters" Tab
2. Click on any Patients
3. Click on "Encounters"
4. The mouse pointer changes to the hand icon throughout the entire encounter section instead of just over the buttons.

**Expected behavior**
The mouse cursor should only change to a pointer when hovering over the buttons. The rest of the encounter section should maintain the default cursor style.

**Record Clip**

https://github.com/user-attachments/assets/8d6e2a07-e600-476e-909a-a3ba237a9c5f

**Desktop ():**

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #9886
- Remove "cursor-pointer" 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style**
	- Removed `cursor-pointer` class from encounter card, potentially affecting visual interactivity indication

### CODE REVIEW

File: src/components/Facility/EncounterCard.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ export const EncounterCard = (props: EncounterCardProps) => {
   const { encounter } = props;
   return (
     <>
-      <div className="pb-16 block relative cursor-pointer border-l-2 px-4 border-l-secondary-300 hover:border-primary-500 transition-all before:absolute before:-left-[7px] before:top-0 before:w-3 before:aspect-square before:bg-secondary-400 before:rounded-full hover:before:bg-primary-500 before:transition-all">
+      <div className="pb-16 block relative  border-l-2 px-4 border-l-secondary-300 hover:border-primary-500 transition-all before:absolute before:-left-[7px] before:top-0 before:w-3 before:aspect-square before:bg-secondary-400 before:rounded-full hover:before:bg-primary-500 before:transition-all">
```
Comment (rithviknishad) [inline src/components/Facility/EncounterCard.tsx]:
```suggestion
      <div className="pb-16 block relative border-l-2 px-4 border-l-secondary-300 hover:border-primary-500 transition-all before:absolute before:-left-[7px] before:top-0 before:w-3 before:aspect-square before:bg-secondary-400 before:rounded-full hover:before:bg-primary-500 before:transition-all">
```

**Review by rithviknishad — APPROVED** [review]
