### PR TITLE
fix: fixed DialogContent requires a DialogTitle using SheetTitle

### LINKED ISSUE #15004: BUG: `DialogContent` requires a `DialogTitle` for the component to be accessible for screen reader users.
**Describe the bug**
This error `DialogContent requires a DialogTitle for the component to be accessible for screen reader users.` is being logged in the console when I visited Settings > General > Clicked on Edit Cover Photo > Clicked on Open Camera.

I didn't had camera connected to pc so Camera Permission Denied toast appeared.

and I could see the said Dialog Title error being logged in the console. 

**To Reproduce**

1. Disconnect your camera or disable camera permissions
2. Go to 'Settings'
3. Click on 'General'
4. Click on 'Edit Cover Photo '
5. Click on 'Open Camera '
6. See error `DialogContent requires a DialogTitle for the component to be accessible for screen reader users.` in the browser console.

**Expected behavior**
There shouldn't be any error being logged in the console.

**Screenshots**
Error in console:

Image

**Desktop (please complete the following information):**

- OS: Ubuntu 24.04 LTS
- Browser Brave, Firefox
- Version Firefox[146.0.1 (64-bit)], Brave[1.85.118 (Official Build) (64-bit) Chromium: 143.0.7499.169]

**Additional context**
-> I believe the camera controls should be hidden if the camera permission is denied for better UX. 
-> And the tanstack pop up in the bottom-right corner isn't clickable if any other overlaying element is open (even though it is visible).

Camera controls:

Image

Tanstack popup in the bottom-right:

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by 8sami**
## Proposed Changes

Fixes #15004
- Imported `SheetTitle` in `CameraCaptureDialog.tsx`
- Used `SheetTitle` in `SheetContent` with class `sr-only` to hide it and fix the issue.

Screenshot from 2026-01-05 00-55-17

Screenshot from 2026-01-05 02-30-42

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved accessibility of the camera capture dialog by adding a proper hidden title for screen readers.

* **New Features**
  * Enhanced camera selection UX: on larger screens with multiple cameras a device list is shown; otherwise a simple switch control is presented.

* **Refactor**
  * Reorganized camera UI into a permission-aware flow to simplify behavior and layout.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by Jacobjeevan — COMMENTED** [review]
Converted to draft

https://github.com/ohcnetwork/care_fe/issues/15004#issuecomment-3742481905

**Comment by 8sami** [comment]
Hi @Jacobjeevan , now the camera controls wont be rendered if the camera permission is denied.

here is the ss of the after:

image




Sorry for the force-pushes... I had realized that my git config was incorrect so first force-push was for that, and after I had mistakenly pushed an md file so I had to remove it with another force-push.

File: src/components/Files/CameraCaptureDialog.tsx [hunk 1]
```diff
@@ -148,97 +149,106 @@ export default function CameraCaptureDialog(props: CameraCaptureDialogProps) {
...
-                      <DropdownMenu
-                        open={showCameraSelector}
-                        onOpenChange={setShowCameraSelector}
-                      >
-                        <DropdownMenuTrigger asChild>
-                          <Button
-                            variant="secondary"
-                            className="rounded-full size-13"
+                  {cameraPermission !== "denied" && (
+                    <>
```
Comment (8sami) [inline src/components/Files/CameraCaptureDialog.tsx:153]: this is the real change

File: src/components/Files/CameraCaptureDialog.tsx [hunk 2]
```diff
@@ -148,97 +149,106 @@ export default function CameraCaptureDialog(props: CameraCaptureDialogProps) {
...
+                        onClick={() => {
+                          captureImage();
+                          setPreview?.(true);
+                        }}
+                        className="bg-white rounded-full size-18 flex items-center justify-center cursor-pointer [&_svg]:px-0 !p-0"
+                      >
+                        <div className="size-16 rounded-full bg-white border-2 border-black flex items-center justify-center"></div>
+                      </Button>
+                    </>
+                  )}
```
Comment (8sami) [inline src/components/Files/CameraCaptureDialog.tsx:251]: and this is the closing tag

**Review by Jacobjeevan — APPROVED** [review]
