### PR TITLE
Fix: Display Modify date and i18n Localization in Patient Encounter Page

### LINKED ISSUE #9688: Create and modify date in encounter page not showing
Create and modify date in encounter page not showing

Image

### PR DESCRIPTION
**Pull request by Rishith25**
## Proposed Changes

- Fixes #9688 
- Created and modified dates are present in Patient Encounter page"

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced encounter date display with formatted last modified date.
	- Improved localization support with updated labels for "Patient Details" and "Encounter".

- **Refactor**
	- Renamed `updated_date` property to `modified_date` in Encounter interface for improved clarity.

- **Documentation**
	- Added new localization entry for "Encounter".

### CODE REVIEW

File: src/pages/Encounters/EncounterShow.tsx
Comment (rithviknishad) [inline src/pages/Encounters/EncounterShow.tsx:1]: follow the merge checklist: add i18n for all texts in this file

File: src/pages/Encounters/EncounterShow.tsx [hunk 1]
```diff
@@ -300,6 +300,7 @@ export const EncounterShow = (props: Props) => {
               <div className="font-base flex flex-col text-xs leading-relaxed text-secondary-700">
                 <div className="flex items-center">
                   <span className="text-secondary-900">Created: </span>&nbsp;
```
Comment (rithviknishad) [inline src/pages/Encounters/EncounterShow.tsx]: let's not have this since backend is not giving the data. period.start is already shown at the top.

remove this

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by Rishith25** [comment]
@rithviknishad Can you assign 1 story point to this

File: src/pages/Encounters/EncounterShow.tsx [hunk 2]
```diff
@@ -297,21 +297,25 @@ export const EncounterShow = (props: Props) => {
...
+                  <RelativeDateUserMention
                     actionDate={encounterData.created_date}
                     user={encounterData.created_by}
                     tooltipPosition="right"
                     withoutSuffix={true}
-                  /> */}
+                  />
                 </div>
-              </div>
+              </div> */}
```
Comment (rithviknishad) [inline src/pages/Encounters/EncounterShow.tsx]: remove the comments :)

File: src/pages/Encounters/EncounterShow.tsx [hunk 3]
```diff
@@ -249,7 +249,7 @@ export const EncounterShow = (props: Props) => {
             }
             className="btn btn-primary m-1 w-full hover:text-white"
           >
-            Discussion Notes
+            {t("discussion_notes")}
```
Comment (rithviknishad) [inline src/pages/Encounters/EncounterShow.tsx]: remove this button, we no longer have this in new architecture. The Notes tab in encounter page is the new thing.

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Comment by rithviknishad** [comment]
update the PR title accordingly btw

File: src/pages/Encounters/EncounterShow.tsx (hunk 2 above)
Comment (Rishith25) [reply src/pages/Encounters/EncounterShow.tsx]: Means removing the comments Created label will be showed so i just have to show the created :) or remove all the entire comment lines from 300 - 311

Comment (rithviknishad) [reply src/pages/Encounters/EncounterShow.tsx]: delete the comments*

File: public/locale/en.json [hunk 4]
```diff
@@ -700,6 +700,7 @@
   "discontinue": "Discontinue",
   "discontinue_caution_note": "Are you sure you want to discontinue this prescription?",
   "discontinued": "Discontinued",
+  "discussion_notes": "Discussion Notes",
```
Comment (rithviknishad) [inline public/locale/en.json]:
```suggestion
```

**Review by rithviknishad — APPROVED** [review]
