### PR TITLE
Fix: Add bottom spacing to container to resolve last card visual overlap

### LINKED ISSUE #11747: The last card in the container is directly attached to the bottom edge
**Describe the bug**  
The last card in the container is directly attached to the bottom edge without any spacing or padding, which affects the visual hierarchy and breaks consistency in the layout.

**To Reproduce**  
1. Navigate to the staff/admin listing page.
2. Go to setting
3. Navigate to departments or navigate to departments and then to the administration then to users
4. Observe that the last card is visually stuck to the bottom without any spacing.
**Expected behavior**  
There should be a consistent padding or margin at the bottom of the container so that the last card is visually separated from the container's edge—just like the spacing between the cards and other boundaries.

**Screenshots**  

Image

Image

Image

**Desktop (please complete the following information):**
- OS: [e.g. Windows 11]
- Browser: [e.g. Chrome]
- Version: [e.g. 122.0.0]

**Smartphone (please complete the following information):**
- Device: [e.g. iPhone 13]
- OS: [e.g. iOS 17.1]
- Browser: [e.g. Safari]
- Version: [e.g. 17.0]

**Additional context**  
This issue may be resolved by adding `padding-bottom` to the card container or ensuring `margin-bottom` is present for the last child card.

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: 07-04-205

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Yaddalapalli-Charan-Kumar-Naidu**
## Proposed Changes

- Fixes #11747 
- Added `margin-bottom` to the container wrapping the cards to prevent the last card from sticking to the bottom edge.
- Ensured consistent visual spacing between all cards and container boundaries.
- Verified changes across various screen sizes and routes (Departments > Administration > Users).

##Screenshots
image
image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Enhanced the visual layout on organization-related pages by increasing bottom spacing on key content sections for clearer separation and improved page aesthetics.

### CODE REVIEW

**Comment by Jacobjeevan** [comment]
Please complete the merge checklist 👍

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
> Please complete the merge checklist 👍

Ok

**Comment by Yaddalapalli-Charan-Kumar-Naidu** [comment]
> Please complete the merge checklist 👍

I did them please review it @Jacobjeevan

**Comment by Jacobjeevan** [comment]
> > Please complete the merge checklist 👍
> 
> I did them please review it @Jacobjeevan

Please only check the only relevant items (and only if you have completed them) 😅  Otherwise it misses the point

**Review by Jacobjeevan — APPROVED** [review]

File: src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx [hunk 1]
```diff
@@ -127,7 +127,7 @@ export default function FacilityOrganizationUsers({
         </div>
       ) : (
         <div className="space-y-4">
-          <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-2 gap-4">
+          <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-2 gap-4 mb-4">
```
Comment (abhimanyurajeesh) [inline src/pages/Facility/settings/organizations/FacilityOrganizationUsers.tsx:130]:
```suggestion
          <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-2 gap-4 md:pb-6">
```

File: src/pages/Facility/settings/organizations/FacilityOrganizationView.tsx [hunk 2]
```diff
@@ -139,7 +139,7 @@ export default function FacilityOrganizationView({
           <CardListSkeleton count={4} />
         </div>
       ) : (
-        <div className="space-y-6">
+        <div className="space-y-6 mb-4">
```
Comment (abhimanyurajeesh) [inline src/pages/Facility/settings/organizations/FacilityOrganizationView.tsx:159]:
```suggestion
        <div className="space-y-6 md:pb-6">
```

**Review by abhimanyurajeesh — CHANGES_REQUESTED** [review]
in line 125 also make the same change.

**Comment by abhimanyurajeesh** [comment]
closing this in fav of #11808

**Review by abhimanyurajeesh — APPROVED** [review]
