### PR TITLE
Cache only the advance filters

### LINKED ISSUE #6891: Cache only the advance filters across the platform
**Describe the bug**

Currently the search across the platform cache all type of filters

**To Reproduce**

1. Go to any tab with search
2. See error

**Expected behavior**

we should be only cache the advance filters across the platform

**Screenshots**

image

### PR DESCRIPTION
**Pull request by AshrafMd-1**
## Proposed Changes

- Fixes #6891 
- Added primary searches to blacklist so no cache is stored

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

File: src/Components/Patient/ManagePatients.tsx [hunk 1]
```diff
@@ -775,7 +776,11 @@ export const PatientManager = () => {
     return {
       name,
       value: qParams[name] || defaultValue,
-      onChange: (e: FieldChangeEvent<T>) => updateQuery({ [e.name]: e.value }),
+      onChange: (e: FieldChangeEvent<T>) =>
+        updateQuery({ [e.name]: e.value }, [
+          "phone_number",
+          "emergency_phone_number",
+        ]),
```
Comment (rithviknishad) [inline src/Components/Patient/ManagePatients.tsx]: Why is `phone_number` and `emergency_phone_number` here and not in cacheBlacklist? Wouldn't this cause unexpected behaviour when filter by name and phone number is done together?

File: src/Common/hooks/useFilters.tsx [hunk 2]
```diff
@@ -18,15 +19,25 @@ interface FilterBadgeProps {
...
+  limit?: number;
+  cacheBlacklist?: string[];
+}) {
   const { t } = useTranslation();
   const { kasp_string } = useConfig();
   const hasPagination = limit > 0;
   const [showFilters, setShowFilters] = useState(false);
   const [qParams, setQueryParams] = useQueryParams();
+  const [primaryCacheBlacklist, setPrimaryCacheBlacklist] =
+    useState(cacheBlacklist);
```
Comment (rithviknishad) [inline src/Common/hooks/useFilters.tsx]: Why is a state required for this? We could simply do:

```suggestion
  const cacheBlacklist = FILTERS_CACHE_BLACKLIST.concat(cacheBlacklist);
```

File: src/Common/hooks/useFilters.tsx [hunk 3]
```diff
@@ -18,15 +19,25 @@ interface FilterBadgeProps {
...
 
-  const updateQuery = (filter: FilterState) => {
+  const updateQuery = (filter: FilterState, cacheBlacklist: string[] = []) => {
     filter = hasPagination ? { page: 1, limit, ...filter } : filter;
+    if (cacheBlacklist.length)
+      setPrimaryCacheBlacklist(primaryCacheBlacklist.concat(cacheBlacklist));
```
Comment (rithviknishad) [inline src/Common/hooks/useFilters.tsx]: Why does `updateQuery` keep updating the cache blacklist? We can resolve it once and use that variable everywhere right?

```suggestion
  const updateQuery = (filter: FilterState) => {
    filter = hasPagination ? { page: 1, limit, ...filter } : filter;
```

File: src/Common/hooks/useFilters.tsx [hunk 4]
```diff
@@ -38,7 +49,10 @@ export default function useFilters({ limit = 14 }: { limit?: number }) {
   };
   const removeFilter = (param: string) => removeFilters([param]);
 
-  useEffect(() => updateFiltersCache(qParams), [qParams]);
+  useEffect(
+    () => updateFiltersCache(qParams, primaryCacheBlacklist),
+    [qParams, primaryCacheBlacklist]
+  );
```
Comment (rithviknishad) [inline src/Common/hooks/useFilters.tsx]: This is not required when the useState is avoided

```suggestion
```

File: src/Common/hooks/useFilters.tsx [hunk 5]
```diff
@@ -170,7 +184,7 @@ export default function useFilters({ limit = 14 }: { limit?: number }) {
             id="clear-all-filters"
             className="rounded-full border border-gray-300 bg-white px-2 py-1 text-xs text-gray-600 hover:text-gray-800"
             onClick={() => {
-              updateFiltersCache({});
+              updateFiltersCache({}, primaryCacheBlacklist);
```
Comment (rithviknishad) [inline src/Common/hooks/useFilters.tsx]:
```suggestion
              updateFiltersCache({}, cacheBlacklist);
```

File: src/Common/hooks/useFilters.tsx [hunk 6]
```diff
@@ -266,9 +280,12 @@ const getFiltersCacheKey = () => `filters--${window.location.pathname}`;
...
   return JSON.parse(localStorage.getItem(getFiltersCacheKey()) || "{}");
 };
-const updateFiltersCache = (cache: Record<string, unknown>) => {
+const updateFiltersCache = (
+  cache: Record<string, unknown>,
+  cacheBlacklist: string[]
+) => {
   const result = { ...cache };
-  for (const param of FILTERS_CACHE_BLACKLIST) {
+  for (const param of FILTERS_CACHE_BLACKLIST.concat(cacheBlacklist)) {
```
Comment (rithviknishad) [inline src/Common/hooks/useFilters.tsx]: Skip multiple concats since the caller would already passes the concated final list

```suggestion
  for (const param of cacheBlacklist) {
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/Components/Patient/ManagePatients.tsx (hunk 1 above)
Comment (AshrafMd-1) [reply src/Components/Patient/ManagePatients.tsx]: it was not directly using the useFilters parameters.
```
 <PhoneNumberFormField
                label="Search by Primary Number"
                {...queryField("phone_number", "+91")}
                value={phone_number}
                onChange={(e) => setPhoneNum(e.value)}
                error={phoneNumberError}
                types={["mobile", "landline"]}
              />
```

so I needed to hardcode it there 

should I refactor this component

File: src/Common/hooks/useFilters.tsx (hunk 2 above)
Comment (AshrafMd-1) [reply src/Common/hooks/useFilters.tsx:35]: needed to use the state to get data from the updateQuery 
due to PhoneNumberFormField else directly using the useFilter params works

File: src/Components/Patient/ManagePatients.tsx (hunk 1 above)
Comment (rithviknishad) [reply src/Components/Patient/ManagePatients.tsx]: You need not refactor this component. In the end the caching works at the query params level right? It'd work if you simply keep that query param's name in the blacklist right?

File: src/Common/hooks/useFilters.tsx (hunk 2 above)
Comment (rithviknishad) [reply src/Common/hooks/useFilters.tsx]: It'd be nice to avoid complications and make the code readable and straight forward.
If there's an issue with how phone number updates the query, that should be fixed.

But I don't think that's an issue since even if you had added the phone number field's key in the global list, it'd work the same way without these complications right?

File: src/Components/Patient/ManagePatients.tsx (hunk 1 above)
Comment (AshrafMd-1) [reply src/Components/Patient/ManagePatients.tsx]: ya i kept a wrong name in the blacklist so it was not working

File: src/Common/hooks/useFilters.tsx (hunk 6 above)
Comment (AshrafMd-1) [reply src/Common/hooks/useFilters.tsx]: didnt understand this 
shouldnt we concat both the arrays

File: src/Common/hooks/useFilters.tsx (hunk 4 above)
Comment (AshrafMd-1) [reply src/Common/hooks/useFilters.tsx]: so delete the whole useEffect ?

Comment (rithviknishad) [reply src/Common/hooks/useFilters.tsx]: nope, ignore. my bad. i got confused with `updateFiltersCache` with update cache blacklist.

File: src/Common/hooks/useFilters.tsx (hunk 6 above)
Comment (rithviknishad) [reply src/Common/hooks/useFilters.tsx]: you have to concat both arrays, but you need not concat it two times. you would already be passing the concated items to the args, and hence you need not perform concat again here.

**Review by rithviknishad — COMMENTED** [review]
Everything LGTM.

Except skip keeping cacheBlacklist as an arg of updateFiltersCache.
Instead:

- Skip passing cacheBlacklist as an arg to updateFitlersCache, there's no need for it to sit there.
- Concat the cache blacklist outside the updateFiltersCache, because you need not keep concating everytime the function is invoked, you can just execute it while the useFilters hook runs.

**Comment by AshrafMd-1** [comment]
@rithviknishad is this okay or are there any changes

**Comment by rithviknishad** [comment]
@AshrafMd-1 was the filters cache working in your PR? How were you able to test whether this PR was working or not?

**Comment by AshrafMd-1** [comment]
It wasn't working. Even when I tested it
I was looking at local storage to find if the variable is stored or not

**Comment by rithviknishad** [comment]
No worries, #7009 would fix it. Once it's merged, you could rebase so that @nihal467 could test this out

**Comment by AshrafMd-1** [comment]
@rithviknishad once can u review this

**Review by rithviknishad — APPROVED** [review]

**Review by Ashesh3 — APPROVED** [review]

**Comment by nihal467** [comment]
@AshrafMd-1 fix the cypress test

**Comment by rithviknishad** [comment]
@AshrafMd-1 the lint checks are failing

**Comment by AshrafMd-1** [comment]
@rithviknishad @nihal467 done

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
