### PR TITLE
Prevent Duplicate Organization Selection

### LINKED ISSUE #12327: Duplicate Organization Selection Allowed, Leading to Confusing Error Toast
**Describe the bug**
When a user attempts to add an organization by selecting from the list, the same organization can be selected multiple times. This leads to confusion if the user accidentally clicks the same organization twice. Upon clicking the "Add Organizations" button, a toast error message appears saying "Organization already exists", even though the user might think they selected different organizations.

**To Reproduce**

1. Go to 'Encounter'
2. Add organizations
3. Select the same organization multiple times
4. Click 'Add organizations'

**Expected behavior**
- The user should not be able to select the same organization more than once.

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by NikhilA8606**
## Proposed Changes

- Fixes #12327 
- Enhance Organization Selection Logic to Prevent Duplicates and Clarify Error Notifications

Demo video:

[Screencast from 2025-05-22 22-42-19.webm](https://github.com/user-attachments/assets/fde11b77-6095-4515-a88d-dc2187129f5f)

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist
- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved organization selection by preventing duplicate additions and clearly indicating when an organization is already selected, enhancing user clarity and interaction consistency.

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
we are already showing "Already selected" and disabling the button for such instances in certain cases! This is not happening for all cases.

can we continue to do that itself and do this for all applicable cases instead of adding a block logic in `handleConfirmSelection` so that it has a better UX? 🤔 

image

image

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image
image


- Don't change the existing workflow. If a user selects a location without any child locations, allow the selection without asking for confirmation. If the user selects a location that has already been added, show a message at the bottom indicating it has already been added, as similar to screenshot 2

File: src/pages/Facility/settings/organizations/components/FacilityOrganizationSelector.tsx [hunk 1]
```diff
@@ -93,20 +94,32 @@ export default function FacilityOrganizationSelector(
...
     if (org.has_children) {
       setNavigationLevels([...navigationLevels, org]);
-      setCurrentSelection(org);
     } else {
-      setCurrentSelection(org);
       handleConfirmSelection(org);
     }
+    setCurrentSelection(org);
     setFacilityOrgSearch("");
+    return;
```
Comment (rithviknishad) [inline src/pages/Facility/settings/organizations/components/FacilityOrganizationSelector.tsx]:
```suggestion
```

File: src/pages/Facility/settings/organizations/components/FacilityOrganizationSelector.tsx [hunk 2]
```diff
@@ -263,6 +276,20 @@ export default function FacilityOrganizationSelector(
...
+                  variant="ghost"
+                  size="sm"
+                  className="h-8 gap-2"
+                  disabled={alreadySelected}
+                  data-cy="confirm-organization"
+                >
+                  <span>{t("already_selected")}</span>
+                  <CareIcon icon="l-multiply" className="h-4 w-4" />
+                </Button>
+              </>
```
Comment (rithviknishad) [inline src/pages/Facility/settings/organizations/components/FacilityOrganizationSelector.tsx]: not needed ryt?

```suggestion
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-8 gap-2"
                  disabled={alreadySelected}
                  data-cy="confirm-organization"
                >
                  <span>{t("already_selected")}</span>
                  <CareIcon icon="l-multiply" className="h-4 w-4" />
                </Button>
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]
minor things

File: src/pages/Facility/settings/organizations/components/FacilityOrganizationSelector.tsx (hunk 2 above)
Comment (NikhilA8606) [reply src/pages/Facility/settings/organizations/components/FacilityOrganizationSelector.tsx]: yeah

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
