### PR TITLE
Fixed Page redirection malfunction issue in the facility cns page

### LINKED ISSUE #5179: Page redirection is malfunctioning in the facility cns page
**Describe the bug**

When we are on the second page of the facility CNS and open a patient consultation page by clicking on the name in the vital card. Once we are on the page and hit the back button, rather than redirecting to the second page of the facility CNS page, we are redirected to the first page of the facility CNS page.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/cns
2. move to page 2 , and click on any patient name
3. once on a patient consultation page, hit the back button

**Expected behavior**

user should be redirected to the previous page he visited, in this case, the user should be redirected to the second page of the facility cns page

**Screenshots**

image

### PR DESCRIPTION
**Pull request by patelaryan7751**
## Proposed Changes

- Fixes #5179 
Fixed Page redirection malfunction issue in the facility cns page
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

File: src/Components/Facility/FacilityCard.tsx [hunk 1]
```diff
@@ -95,7 +95,7 @@ export const FacilityCard = (props: { facility: any; userType: any }) => {
                       {facility.name}
                     </Link>
                     <ButtonV2
-                      href={`/facility/${facility.id}/cns`}
+                      href={`/facility/${facility.id}/cns?page=1`}
```
Comment (khavinshankar) [inline src/Components/Facility/FacilityCard.tsx]: @patelaryan7751 
instead of hardcoding the page, why not make the page = 1 when there is no query params passed

**Review by khavinshankar — CHANGES_REQUESTED** [review]

File: src/Components/Facility/FacilityCard.tsx (hunk 1 above)
Comment (patelaryan7751) [reply src/Components/Facility/FacilityCard.tsx]: Hey @khavinshankar i have removed all hardcoded links

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
