### PR TITLE
Fix non-responsiveness of org patients and org facilities

### LINKED ISSUE #11341: Adjust Orgs patients and orgs facilities cards for tablet
**Describe the bug**
Orgs patients and orgs facilities cards are not responsive for tablet

**To Reproduce**

1. Go to [https://care.ohc.network/organization/6ae703c4-e97c-4097-885f-f0912f0a20be/facilities](url)
2. Click on Facilities and Patients tab
3. See error

**Expected behavior**
Tablet view should be clean as mobile and desktop view.

**Screenshots**
1. 

Image

2.

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by aditissigh24**
## Proposed Changes
- Fixes #11341 
- made patients and facility tab responsive

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Deskt

## Screenshot
Screenshot 2025-03-19 125718
op Devices

## Summary by CodeRabbit

- **New Features**
  - Introduced a mobile dropdown menu for navigation, enhancing the user experience on smaller screens while maintaining a menubar for larger displays.

- **Style**
  - Refined the responsive grid layouts for patients and users, ensuring optimal content organization across different device sizes.
  - Enhanced the layout of facilities to allow for better responsiveness with the addition of flex-wrap functionality.

### CODE REVIEW

File: src/pages/Organization/components/OrganizationLayout.tsx [hunk 1]
```diff
@@ -1,10 +1,17 @@
 import { useQuery } from "@tanstack/react-query";
```
Comment (abhimanyurajeesh) [inline src/pages/Organization/components/OrganizationLayout.tsx:1]: Was QrganizationLayout change requested 🤔  !?

cc: @Jacobjeevan @rithviknishad

**Review by abhimanyurajeesh — COMMENTED** [review]
(noticed in the last PR)
could you fix this also.

File: src/pages/Organization/components/OrganizationLayout.tsx (hunk 1 above)
Comment (yash-learner) [reply src/pages/Organization/components/OrganizationLayout.tsx:1]: > Was QrganizationLayout change requested 🤔 !?
> 
> cc: @Jacobjeevan @rithviknishad

@abhimanyurajeesh 

I think no https://github.com/ohcnetwork/care_fe/issues/11341 based on issue and requested @vinutv to check here https://rebuildearth.slack.com/archives/C080225HC6B/p1742380927614709

Comment (vinutv) [reply src/pages/Organization/components/OrganizationLayout.tsx:1]: I don’t think we need something like what’s mentioned [here](https://github.com/ohcnetwork/care_fe/pull/11216#pullrequestreview-2673872546). Since this navigation has only four fixed elements, a dropdown on smaller screens should work fine.

A couple of suggestions for improvement:
Screenshot 2025-03-19 at 5 02 17 PM

- Making the DropdownMenuContent full-width would increase the interactive space for the items.
- Adding a checkmark to the selected item.

Comment (yash-learner) [reply src/pages/Organization/components/OrganizationLayout.tsx:1]: > I don’t think we need something like what’s mentioned [here](https://github.com/ohcnetwork/care_fe/pull/11216#pullrequestreview-2673872546). Since this navigation has only four fixed elements, a dropdown on smaller screens should work fine.
> 
> A couple of suggestions for improvement: Screenshot 2025-03-19 at 5 02 17 PM
> 
> * Making the DropdownMenuContent full-width would increase the interactive space for the items.
> * Adding a checkmark to the selected item.

@aditissigh24 please make the requested changes

Comment (aditissigh24) [reply src/pages/Organization/components/OrganizationLayout.tsx:1]: okay, i'll change the header to dropdown

Comment (aditissigh24) [reply src/pages/Organization/components/OrganizationLayout.tsx:1]: @yash-learner the width of the dropdown doesn't match the width of the button which triggers the dropdown, we have to use dynamic width, so shall i proceed with this solution?

File: src/pages/Organization/components/OrganizationLayout.tsx [hunk 2]
```diff
@@ -148,7 +148,15 @@ export default function OrganizationLayout({
                 />
               </Button>
             </DropdownMenuTrigger>
-            <DropdownMenuContent className="w-[200px]">
+            <DropdownMenuContent
+              align="start"
+              sideOffset={5}
+              className="w-[var(--radix-dropdown-menu-trigger-width)]"
+              style={{
+                width: dropdownContainerRef.current?.clientWidth || "auto",
```
Comment (Jacobjeevan) [inline src/pages/Organization/components/OrganizationLayout.tsx]: Since we have the width based on trigger width, this shouldn't be necessary.

**Review by Jacobjeevan — DISMISSED** [review]

File: src/pages/Organization/components/OrganizationLayout.tsx (hunk 1 above)
Comment (rithviknishad) [reply src/pages/Organization/components/OrganizationLayout.tsx:1]: Yes!

File: src/pages/Organization/components/OrganizationLayout.tsx (hunk 2 above)
Comment (aditissigh24) [reply src/pages/Organization/components/OrganizationLayout.tsx]: actually, the width of drfopdown down content at smaller screen view is fixed at 200px, so i tried the dynamic width solution and it has worked

Comment (Jacobjeevan) [reply src/pages/Organization/components/OrganizationLayout.tsx]: `w-[var(--radix-dropdown-menu-trigger-width)]` should be enough, no? Try testing it out, seems to be fine on my end.

Comment (aditissigh24) [reply src/pages/Organization/components/OrganizationLayout.tsx]: @Jacobjeevan  are we not keeping that drop down content for smaller screens??
I had a merge conflict and i saw that there's Breadcrumb items now

Comment (Jacobjeevan) [reply src/pages/Organization/components/OrganizationLayout.tsx]: @aditissigh24 We are keeping dropdown for mobile 👍

**Comment by yash-learner** [comment]
@aditissigh24 Looks like you accidentally deleted the changes you have made for dropdown, while fixing the merge conflicts

https://github.com/ohcnetwork/care_fe/pull/11393/commits/3d823e479c0c223c2f8454b1350e0ffd3a9d47a0

**Review by yash-learner — APPROVED** [review]
LGTM
