### PR TITLE
fix: add loading indicator to UserForm submit button

### LINKED ISSUE #14837: Add loading indicator to UserForm submit button
**Describe the bug**
When creating or updating a user through the UserForm component, clicking the "Create User" or "Update User" button disables the button but doesn't show any loading indicator. The button just becomes grey/disabled with the same text, making it unclear whether the submission is in progress or if something went wrong.

**To Reproduce**

1. Navigate to an organization's users page (e.g., `/organization/:id/users`)
2. Open browser DevTools (F12) and go to the Network tab
3. Enable network throttling by selecting "Slow 3G" or "Fast 3G" from the throttling dropdown (this helps observe the button state during submission)
4. Click the "Add User" button in the top-right corner
5. Fill out the required form fields (Username, Password, First Name, Last Name, Email, Phone Number, User Type)
6. Click the "Create User" button at the bottom of the form
7. While the request is pending (visible in the Network tab), observe the button: it becomes disabled (grey) but shows no loading spinner or text change

**Expected behavior**
The submit button should:
- Display a loading spinner while the request is processing
- Change the text from "Create User" to "Creating..." or "Saving..." (similar to other forms like ProductKnowledgeForm)
- Remain disabled during submission

This provides clear visual feedback that the form is being submitted.

**Screenshots**

Image

**Desktop:**

- OS: macOS
- Browser: Chrome
- Version: Latest

**Smartphone:**

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

**Additional context**
This is inconsistent with other forms in the codebase. For example, `ProductKnowledgeForm` shows a loading state with text changing to "Saving..." when `isPending` is true. The `UserForm` component has `createPending` and `updatePending` states available but doesn't use them to show loading feedback.

The button is located in `src/components/Users/UserForm.tsx` around lines 821-833. The form uses React Query mutations with `isPending` states that can be used to implement the loading indicator.

### PR DESCRIPTION
**Pull request by harsh04044**
Fixes #14837 

## Proposed Changes

This PR adds a loading indicator to the UserForm submit button to provide better visual feedback during user creation/update. Previously, the button would just become disabled without any indication that the form was being submitted, which could confuse users.

- Add loading spinner icon and "Saving..." text when the form is submitting (using `createPending` or `updatePending` states)
- Disable the submit button when form has validation errors to prevent showing loading state unnecessarily
- Follows the same pattern used in other forms like ProductKnowledgeForm for consistency

The button now shows a spinner and changes text to "Saving..." when submitting, and stays disabled when there are validation errors (like invalid email format) so users get immediate feedback without triggering a submission.

## Before
image

## After
image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Bug Fixes**
  * Submit button now shows a loading state with context-specific labels ("creating" or "updating") while an operation is pending for clearer feedback.
  * Button remains disabled during pending operations and when the form is incomplete; when idle, it preserves distinct "create" vs "update" labels.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/components/Users/UserForm.tsx [hunk 1]
```diff
@@ -826,10 +826,24 @@ export default function UserForm({
             isLoadingUser ||
             !form.formState.isDirty ||
             updatePending ||
-            createPending
+            createPending ||
+            !form.formState.isValid
```
Comment (AdityaJ2305) [inline src/components/Users/UserForm.tsx]: Let’s allow the user to submit the form; otherwise, they won’t know exactly what error they’re making

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

File: src/components/Users/UserForm.tsx (hunk 1 above)
Comment (harsh04044) [reply src/components/Users/UserForm.tsx]: okay thats right , i have changed it in my latest commit

**Comment by parvathyns-creator** [comment]
@nihal467 this looks fine

File: src/components/Users/UserForm.tsx [hunk 2]
```diff
@@ -829,7 +829,20 @@ export default function UserForm({
             createPending
           }
         >
-          {isEditMode ? t("update_user") : t("create_user")}
+          {updatePending || createPending ? (
+            <>
+              <CareIcon
+                icon="l-spinner"
+                className="mr-2 h-4 w-4 animate-spin"
```
Comment (AdityaJ2305) [inline src/components/Users/UserForm.tsx]:
```suggestion
                className="mr-2 size-4 animate-spin"
```

**Review by AdityaJ2305 — APPROVED** [review]

**Comment by harsh04044** [comment]
@nihal467  sir plz review

File: src/components/Users/UserForm.tsx [hunk 3]
```diff
@@ -829,7 +829,17 @@ export default function UserForm({
             createPending
           }
         >
-          {isEditMode ? t("update_user") : t("create_user")}
+          {updatePending || createPending ? (
+            <>
+              <CareIcon icon="l-spinner" className="mr-2 size-4 animate-spin" />
+
+              {t("saving")}
```
Comment (nihal467) [inline src/components/Users/UserForm.tsx]: - text needs to be based on isEditMode
- remove the spinner

**Review by nihal467 — CHANGES_REQUESTED** [review]
.

File: src/components/Users/UserForm.tsx (hunk 3 above)
Comment (harsh04044) [reply src/components/Users/UserForm.tsx]: @nihal467  i have addresed your review in the latest commit.

**Comment by harsh04044** [comment]
**About the failing Tests**
The CI failures are unrelated to this PR. They're in patient age button selectors and questionnaire visibility tests, not the UserForm submit button changes.
This  latest commit only removes the spinner and makes the button text conditional based on isEditMode. No UserForm tests failed, and the user creation test still expects "Create User", which matches our implementation.
These look like pre-existing flaky tests.

**Review by nihal467 — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
