### PR TITLE
Minor UI enhancements in Questionniares and Valuesets list pages

### LINKED ISSUE #11131: Valuesets list page has no proper Empty State
**Describe the bug**
Currently the empty state just shows no_valuesets_found and that too without any translation.

**To Reproduce**

1. Go to Admin Dashboard
2. Click on Valuesets
3. See error

**Expected behavior**
The page needs some minor UI enhancement by adding a proper empty state similar to the existing pages in the care like resources page, encounters page

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### LINKED ISSUE #11210: Add loading state to questionnaire dashboard for mobile view
**Describe the bug**

When we search for a questionnaire on a normal device, the list is filtered live. However, in the mobile view, no questionnaire is shown initially, and the results appear only after the filtering is completed.

**To Reproduce**

1. Go to admin dashboard
2. search a questionnaire (In real mobile device)

**Expected behavior**

Add a loading state to the questionnaire so that users on mobile devices understand that it is loading and the results will appear soon.

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by hrit2773**
## Proposed Changes

- Fixes #11131
- Fixes #11210
- Changed the empty state for the Questionnaires and Valuesets pages for better UX.
- Changed the loading component to table skeleton loading for better UX.

Screenshot 2025-03-08 131626

Screenshot 2025-03-08 131515
achments/assets/08dd5cc1-909a-41e8-846e-9d1201522821)

@rithviknishad @Jacobjeevan 

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
	- Introduced additional user messages offering guidance on adjusting filters for questionnaires and valuesets.
	- Enhanced the user experience by adding loading indicators with placeholder skeletons for both questionnaire and valueset listings, ensuring smooth feedback during data fetching.
	- Added an `EmptyState` component for scenarios where no valuesets are found, improving user feedback.

### CODE REVIEW

File: src/components/Questionnaire/QuestionnaireList.tsx [hunk 1]
```diff
@@ -157,59 +170,51 @@ const RenderTable = ({
...
-            <TableRow>
-              <TableCell colSpan={3} className="text-center py-4">
-                {t("no_questionnaires_found")}
+                  <Button
+                    variant="outline"
+                    size="sm"
+                    className="font-semibold shadow-gray-300 text-gray-950 border-gray-400"
+                  >
+                    <EyeIcon className="w-4 h-4 mr-0" />
+                    {t("View")}
```
Comment (abhimanyurajeesh) [inline src/components/Questionnaire/QuestionnaireList.tsx]: is this correct !?

**Hint:** look into the translations.

Comment (hrit2773) [reply src/components/Questionnaire/QuestionnaireList.tsx]: @abhimanyurajeesh What do you want me to change??

**Comment by hrit2773** [comment]
@Jacobjeevan @rithviknishad can you review this

File: src/components/Questionnaire/QuestionnaireList.tsx (hunk 1 above)
Comment (Jacobjeevan) [reply src/components/Questionnaire/QuestionnaireList.tsx]: compare against the en.json file.

**Review by Jacobjeevan — COMMENTED** [review]
everything else looks fine, check the translation.

**Comment by hrit2773** [comment]
@Jacobjeevan cypress error in patient creation!!!!!!!! It has nothing to do with this PR I guess. cc @nihal467

**Comment by hrit2773** [comment]
@Jacobjeevan @rithviknishad can I get a review on this again because I made some changes as per the new issue as well https://github.com/ohcnetwork/care_fe/issues/11210#event-16690741795

**Comment by hrit2773** [comment]
@Jacobjeevan @rithviknishad @nihal467 lets close this by today EOD coz its P1 issue. So can You guys give a quick review on this.

**Review by khavinshankar — APPROVED** [review]

File: src/components/Questionnaire/QuestionnaireList.tsx (hunk 1 above)
Comment (khavinshankar) [reply src/components/Questionnaire/QuestionnaireList.tsx]: @hrit2773 yes, lets keep the translations in snake case and in lower case

Comment (hrit2773) [reply src/components/Questionnaire/QuestionnaireList.tsx]: @khavinshankar Yup! that's what I changed it which was there in the existing code

**Comment by hrit2773** [comment]
@Jacobjeevan @rithviknishad Can I get your reviews as well??

**Review by Jacobjeevan — APPROVED** [review]

**Comment by hrit2773** [comment]
@nihal467 can you test this and merge

**Comment by hrit2773** [comment]
@Jacobjeevan @khavinshankar I have resolved the merge conflicts. @nihal467 to test and merge

**Comment by nihal467** [comment]
LGTM

File: src/components/Questionnaire/QuestionnaireList.tsx [hunk 2]
```diff
@@ -30,131 +32,165 @@ import {
...
+                    onClick={(e) => {
+                      e.stopPropagation();
+                      navigate(
+                        `/admin/questionnaire/${questionnaire.slug}/edit`,
+                      );
+                    }}
+                    className="font-semibold shadow-gray-300 text-gray-950 border-gray-400"
+                  >
+                    <EyeIcon className="w-4 h-4 mr-1" />
+                    {t("View")}
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireList.tsx:154]: invalid i18n translation!

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/Questionnaire/QuestionnaireList.tsx (hunk 2 above)
Comment (hrit2773) [reply src/components/Questionnaire/QuestionnaireList.tsx:154]: @rithviknishad fixed

**Review by rithviknishad — APPROVED** [review]
