### PR TITLE
fixes overlapping text

### LINKED ISSUE #9762: Overlapping text on mobile
**Describe the bug**
Text overlapping in mobile.

**To Reproduce**

1. Go to organization page.
2. Click on side nav.
3. See error

**Expected behavior**

**Screenshots**
Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by cbum-dev**
## Proposed Changes

- Fixes  #9762 #9765

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Style**
	- Updated both left and right sheet variants to occupy full width instead of three-quarters width.

### CODE REVIEW

File: src/components/ui/sheet.tsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ const sheetVariants = cva(
           "inset-x-0 bottom-0 border-t data-[state=closed]:slide-out-to-bottom data-[state=open]:slide-in-from-bottom",
         left: "inset-y-0 left-0 h-full w-3/4 border-r data-[state=closed]:slide-out-to-left data-[state=open]:slide-in-from-left sm:max-w-sm",
         right:
-          "inset-y-0 right-0 h-full w-3/4 border-l data-[state=closed]:slide-out-to-right data-[state=open]:slide-in-from-right sm:max-w-sm",
+          "inset-y-0 right-0 h-full w-full border-l data-[state=closed]:slide-out-to-right data-[state=open]:slide-in-from-right sm:max-w-sm",
```
Comment (rithviknishad) [inline src/components/ui/sheet.tsx]: left and right needs to have same behaviour

**Review by rithviknishad — CHANGES_REQUESTED** [review]

File: src/components/ui/sheet.tsx (hunk 1 above)
Comment (cbum-dev) [reply src/components/ui/sheet.tsx]: Okay.

**Review by rithviknishad — APPROVED** [review]
