### PR TITLE
Fix: Proper Validation for DiscountCodeForm to Prevent Whitespace-Onl…

### LINKED ISSUE #14021: Proper Validation for DiscountCodeForm to Prevent Whitespace-Only Inputs
**Description:**

Currently, in DiscountCodeForm, the Save button becomes enabled when the user enters just spaces in the name or code fields and it is accepting white space.

https://github.com/user-attachments/assets/740e68cd-7499-46e1-85db-f81643ca9f36

**Expected Behavior:**

- Fields should not accept values containing only spaces.

---

🚨 DO NOT EDIT BELOW THIS LINE 🚨
Instructions for Requesting Assignment:
To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

Describe your solution clearly:
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

Expected Timeline:

End date: [Expected submission date of a completed Pull Request]
Additional Context:
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by geyamrutha16**
## Proposed Changes

Fixes #14021

**Key changes:**
- Added a `.transform((val) => val.trim())` in the Zod schema to remove leading and trailing spaces before validation.
- Added a controlled `onChange` handler that removes only **leading spaces** in real time using.
- This ensures the field value in the UI never starts with whitespace, while still allowing spaces in between words (e.g., “Hello World”).
- The form’s `isDirty` and validation logic now correctly prevent saving when the input is empty or whitespace-only.

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate the bug or test the new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [x] Complete QA on mobile devices.
- [x] Complete QA on desktop devices.

## Summary by CodeRabbit

* **Refactor**
  * Optimized discount code form input handling to improve performance by simplifying the validation schema approach.

* **Bug Fixes**
  * Improved discount code input normalization to ensure whitespace is properly handled before validation checks.

### CODE REVIEW

**Comment by tasnimshaji** [comment]
LGTM @nihal467

File: src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx [hunk 1]
```diff
@@ -32,8 +32,18 @@ export function DiscountCodeForm({
...
+          .transform((val) => val.trim())
+          .refine((val) => val.trim().length > 0, {
+            message: t("field_required"),
+          }),
+        display: z
+          .string()
+          .transform((val) => val.trim())
+          .refine((val) => val.trim().length > 0, {
+            message: t("field_required"),
+          }),
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx]: Don't need to complicate the logic

Just add `.trim()` that's it. Look at other places in code how it has been done 👍

File: src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx [hunk 2]
```diff
@@ -64,7 +74,10 @@ export function DiscountCodeForm({
             <FormItem>
               <FormLabel>{t("name")}</FormLabel>
               <FormControl>
-                <Input {...field} />
+                <Input
+                  {...field}
+                  onChange={(e) => field.onChange(e.target.value.trim())}
+                />
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx]: discard changes here

File: src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx [hunk 3]
```diff
@@ -81,7 +94,10 @@ export function DiscountCodeForm({
             <FormItem>
               <FormLabel>{t("code")}</FormLabel>
               <FormControl>
-                <Input {...field} />
+                <Input
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx]: discard changes here

**Review by AdityaJ2305 — CHANGES_REQUESTED** [review]

**Review by abhimanyurajeesh — CHANGES_REQUESTED** [review]
@geyamrutha16 I think @Jacobjeevan already mentioned only trim is needed.

https://github.com/ohcnetwork/care_fe/issues/14021#issuecomment-3425402134

**Comment by geyamrutha16** [comment]
@abhimanyurajeesh , @AdityaJ2305 , Updated 👍

File: src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx [hunk 4]
```diff
@@ -32,8 +32,14 @@ export function DiscountCodeForm({
   const formSchema = useMemo(
```
Comment (AdityaJ2305) [inline src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx]: Can you remove useMemo

File: src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx [hunk 5]
```diff
@@ -32,8 +32,14 @@ export function DiscountCodeForm({
...
     () =>
       z.object({
-        code: z.string().min(1, { message: t("field_required") }),
-        display: z.string().min(1, { message: t("field_required") }),
+        code: z
+          .string()
+          .trim()
```
Comment (bodhish) [inline src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx]: Is it possible to have zod trim all strings by default?

**Review by bodhish — CHANGES_REQUESTED** [review]

File: src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx (hunk 4 above)
Comment (geyamrutha16) [reply src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx]: I noticed that useMemo was already present in the existing codebase, so I initially retained. That it’s not really necessary here. I’ll go ahead and remove it 👍

File: src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx (hunk 5 above)
Comment (geyamrutha16) [reply src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx]: Yes! we can make Zod trim all strings by default by creating a helper function but i think that is not efficient, Instead, we can create a global Zod utility.

**Review by AdityaJ2305 — APPROVED** [review]

File: src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx (hunk 5 above)
Comment (geyamrutha16) [reply src/pages/Facility/settings/billing/discount/discount-codes/DiscountCodeForm.tsx]: @bodhish , Should I create a global ZOD utility .. ?

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM @geyamrutha16 as per the new PR guideline, create the playwright test to verify the functionality of the changes from this PR
