### PR TITLE
Fix : Search Bar Dropdown Visibility

### LINKED ISSUE #10541: Search Bar Dropdown Visibility
**Describe the bug**
The search bar is displaying options without clicking on it.
 It should only show options when the search bar is clicked.

**To Reproduce**

1. Login with careadmin
2. Click on 'Admin Dashboard' 
3. Click on ' Create New' 
4. Options are displayed without clicking on the search bar.
5. similarly  issue persists in 
 *  Click on 'acitve' button (Status) -> Manage -> Clone Questionnaire (issue is also presents) 

**Expected behavior**
The search bar should display options only when the user clicks on

**Record Clip**

Image

### PR DESCRIPTION
**Pull request by Jeffrin2005**
## Proposed Changes

- Fixes #10541 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.

- For "Clone Questionnaire" and "Create Questionnaire" we are using drop down selection.

- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.

   issu10

## Summary by CodeRabbit

- **New Features**
	- **Streamlined Organization Selection:** The old command-based interface has been replaced with a dropdown menu, providing a smoother selection process with clear loading states and messages when no organizations are found.
	- **Enhanced Localization:** Button labels, messages, and indicators (including badges for selected items) are now fully translatable for a more consistent user experience.
	- **Improved Questionnaire Layout:** A minor addition to the layout style selection text enhances clarity without altering functionality.

- **Style Changes**
	- Updated styling for various paragraph elements for improved visual consistency.

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
Let's not switch to select. Command with Popover (or Autocomplete), exactly does what this does now.

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan Can we re-open this, Used Command with Popover instead of Select.

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan Used Command with Popover instead of Select. Can we re-open this PR ?

**Comment by Jeffrin2005** [comment]
https://github.com/user-attachments/assets/130c81b8-864b-4a1b-afa9-fa737ebb7cb6

**Comment by Jeffrin2005** [comment]
https://github.com/user-attachments/assets/f359dbbc-f649-4cb2-8dde-1593d7a1e594

**Comment by Jacobjeevan** [comment]
Wait for #10678 to be merged

**Comment by Jeffrin2005** [comment]
@rithviknishad 


https://github.com/user-attachments/assets/70c897d1-3553-4fe5-b5c9-acfcd88d0baf

**Comment by Jacobjeevan** [comment]
@Jeffrin2005 do a self review

With the recent changes to UI, lot of changes in this PR is unnecessary (update the description in PR as well).

- Right now, the only one that needs a popover is add organizations in clone questionnaire.

**Comment by Jeffrin2005** [comment]
@Jacobjeevan Removed the duplicate code in clone questionnaire.

**Comment by Jeffrin2005** [comment]
@Jacobjeevan we only need to display the selected tags . Is there anything to remove ?

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan we only need to display the selected tags ?      Is there anything to remove ?

**Comment by Jacobjeevan** [comment]
> @rithviknishad @Jacobjeevan we only need to display the selected tags ? Is there anything to remove ?

Adjust the PR description. What exactly is being changed in the questionnaire editor? 🤔

**Comment by Jeffrin2005** [comment]
@Jacobjeevan For more clarity regarding this issue, 

In this clip, we can see that the while selecting options from the search bar is not looking good , To improve the selection while choosing a option, the option will be removed from the list.


https://github.com/user-attachments/assets/4acb97df-581f-42ba-89a5-202d7529441b

My proposed solution is in this video, 
https://github.com/ohcnetwork/care_fe/pull/10696#issuecomment-2676033775

Any changes required ?

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan For more clarity regarding this issue,
> 
> In this clip, we can see that the while selecting options from the search bar is not looking good , To improve the selection while choosing a option, the option will be removed from the list.
> issue82.mp4
> 
> My proposed solution is in this video, [#10696 (comment)](https://github.com/ohcnetwork/care_fe/pull/10696#issuecomment-2676033775)
> 
> Any changes required ?

🤔  I'm not sure what you mean...not seeing the issue here 😅

**Comment by Jeffrin2005** [comment]
@Jacobjeevan No.  i am trying to enhance the interface of selecting the options from search bar, Do i need to close this issue ?

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan No. i am trying to enhance the interface of selecting the options from search bar, Do i need to close this issue ?

Ah, I see, nah that's not needed. Let's keep it as is - allow user to see the selected ones within the menu as well.

**Comment by nihal467** [comment]
@Jeffrin2005 what is the status on the PR

**Comment by Jeffrin2005** [comment]
@nihal467 The code for the current implementation has already been completed. but  there seems to be a slight misunderstanding regarding the issue that Jacob Jeevan mentioned earlier.

@jacobjeevan Could you please confirm if I need to close this PR and the issue?

**Comment by Jacobjeevan** [comment]
> @nihal467 The code for the current implementation has already been completed. but there seems to be a slight misunderstanding regarding the issue that Jacob Jeevan mentioned earlier.
> 
> @Jacobjeevan Could you please confirm if I need to close this PR and the issue?

🤔  I am not sure why you need to close this PR - you are still adding popover for clone questionnaire, no?

Changes in QuestionnaireEditor can be discarded.

**Review by rithviknishad — CHANGES_REQUESTED** [review]
refer readme and how translations are done in other places

File: src/components/Questionnaire/CloneQuestionnaireSheet.tsx [hunk 1]
```diff
@@ -219,10 +249,10 @@ export default function CloneQuestionnaireSheet({
               {isCloning ? (
                 <>
                   <Loader2 className="mr-2 h-4 w-4 animate-spin" />
-                  Cloning...
+                  {t("cloning")}
```
Comment (AdityaJ2305) [inline src/components/Questionnaire/CloneQuestionnaireSheet.tsx]: I don’t think the key for cloning exists in en.json. @Jeffrin2005, could you check and add it accordingly?

File: src/components/Questionnaire/CloneQuestionnaireSheet.tsx [hunk 2]
```diff
@@ -219,10 +249,10 @@ export default function CloneQuestionnaireSheet({
...
                 </>
               ) : (
-                "Clone"
+                t("clone")
```
Comment (AdityaJ2305) [inline src/components/Questionnaire/CloneQuestionnaireSheet.tsx]: Same here

File: src/components/Questionnaire/CloneQuestionnaireSheet.tsx (hunk 1 above)
Comment (Jeffrin2005) [reply src/components/Questionnaire/CloneQuestionnaireSheet.tsx]: Thank You

**Comment by Jeffrin2005** [comment]
https://github.com/user-attachments/assets/c7d1bfc3-8ee8-4579-b6ec-ee140c56bcb4

**Comment by Jacobjeevan** [comment]
> temp11.mp4

Go ahead and adjust the width of the popover content as well, to match the trigger.

**Comment by Jeffrin2005** [comment]
@rithviknishad Any changes required?

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 3]
```diff
@@ -699,9 +699,10 @@ export default function QuestionnaireEditor({ id }: QuestionnaireEditorProps) {
     mutationFn: mutate(questionnaireApi.update, {
       pathParams: { id: id! },
     }),
-    onSuccess: () => {
+    onSuccess: (data: QuestionnaireDetail) => {
       toast.success("Questionnaire updated successfully");
       queryClient.invalidateQueries({ queryKey: ["questionnaireDetail", id] });
+      navigate(`/admin/questionnaire/${data.slug}`);
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]: let's not add this for now. Questionnaire is slightly different anyways, since there's no draft feature, users might want to save and keep on editing.

**Review by Jacobjeevan — COMMENTED** [review]
image

Adjust the styling a bit 👍

**Comment by rithviknishad** [comment]
merge checklist not followed;

**Comment by Jeffrin2005** [comment]
@rithviknishad @Jacobjeevan Completed merge checklist, Can we re-open this PR ?

**Comment by Jeffrin2005** [comment]
@Jacobjeevan

 In CloneQuestionnaire.
issu10

currently In care-fe website it is like this 



https://github.com/user-attachments/assets/4976b5ce-d126-47c1-8617-f62da1a0053b

Just a suggestion  do we need to make  it as like in the below manner in QuestionnaireEditor.tsx ?

https://github.com/user-attachments/assets/550c6949-a54f-4f8f-bef3-cc835e819b3f

**Review by Jacobjeevan — APPROVED** [review]
