### PR TITLE
Fix: ValueSetSelect selected value label text cutting out

### LINKED ISSUE #13101: `ValueSetSelect` selected value label text cutting out
**Describe the bug**

Image

**Expected behavior**
Either we can truncate or wrap the text 

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Akhileswaran-K-R**
## Proposed Changes

- Fixes #13101 
- Added truncate class to the span element displaying value

valueSetSelect

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA in Mobile Devices
- [x] Completion of QA in Desktop Devices

## Summary by CodeRabbit

* **Style**
  * Improved text display in the value selection button by truncating overflow text for better readability and layout consistency.

### CODE REVIEW

**Review by AdityaJ2305 — COMMENTED** [review]
Let's wrap the text since it also shows code when showCode is true

**Comment by AdityaJ2305** [comment]
Screenshot 2025-07-29 at 3 05 25 AM

It should look like this. This looks more clean !!

**Comment by tasnimshaji** [comment]
Looks good to me @nihal467

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Let's not show the full text. this could be very long and since this is used in so many palces, forms would look weird. let's truncate and show in one line itself.

File: src/components/Questionnaire/ValueSetSelect.tsx [hunk 1]
```diff
@@ -250,7 +250,7 @@ export default function ValueSetSelect({
                   !value?.display && "text-gray-400",
                 )}
               >
-                <span>
+                <span className="truncate block max-w-full">
```
Comment (rithviknishad) [inline src/components/Questionnaire/ValueSetSelect.tsx]:
```suggestion
                <span className="truncate">
```

**Review by rithviknishad — APPROVED** [review]

**Review by abhimanyurajeesh — APPROVED** [review]
