### PR TITLE
Display the errors when presets fetch fails

### LINKED ISSUE #3179: Presets fetch errors are not shown
If there's an error while fetching presets, the error is not shown to the user and just logged to the console.
Expected: The error should be appropriately displayed to the user to let them know that fetching the preset has failed.

image

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #3179 

The errors from the backend are appropriately displayed to the user whenever getting the presets fails.

image

### CODE REVIEW

**Review by cp-Coder — APPROVED** [review]

**Comment by nihal467** [comment]
@Ashesh3 check the merge conflict and update it to need testing label

**Comment by nihal467** [comment]
@Ashesh3 
image

i can only find this error, @khavinshankar can you check this !

**Comment by Ashesh3** [comment]
> @Ashesh3 image
> 
> i can only find this error, @khavinshankar can you check this !

I think this error is related to saving the configuration, and not while fetching presets. To trigger the preset error, save the asset with blank hostname, address and key.

File: src/Components/Facility/Consultations/Feed.tsx [hunk 1]
```diff
@@ -188,7 +188,18 @@ export const Feed: React.FC<IFeedProps> = ({ consultationId }) => {
 
   useEffect(() => {
     if (cameraAsset.hostname) {
-      getPresets({ onSuccess: (resp) => setPresets(resp.data) });
+      getPresets({
+        onSuccess: (resp) => setPresets(resp.data),
+        onError: (resp) => {
+          resp instanceof AxiosError &&
+            resp.response?.data?.errors &&
+            resp.response?.data?.errors.map((error: { message: string }) => {
```
Comment (khavinshankar) [inline src/Components/Facility/Consultations/Feed.tsx]:
```suggestion
            resp.response?.data?.errors.forEach((error: { message: string }) => {
```
As we are not returning anything why not just use forEach instead of map

also change it in the other file too

**Review by khavinshankar — CHANGES_REQUESTED** [review]

File: src/Components/Facility/Consultations/Feed.tsx (hunk 1 above)
Comment (Ashesh3) [reply src/Components/Facility/Consultations/Feed.tsx]: Resolved!

**Comment by nihal467** [comment]
@Ashesh3 
image

unable to find the particular PR changes, can you screen record while using the deploy preview link itself, so it will be easy for me to review it?

**Comment by Ashesh3** [comment]
@nihal467 made some changes, attached the recordings for both scenarios.

## Original

https://care.coronasafe.in/assets/5f659f66-648d-4c6b-8a20-a9e8366980a1/configure

chrome_jSXoYW2DHP

No error is shown even though fetching the preset has failed.

## With this PR:

https://deploy-preview-3186--care-egov-staging.netlify.app/assets/5f659f66-648d-4c6b-8a20-a9e8366980a1/configure

chrome_fEXiggwzYB

**Comment by nihal467** [comment]
test approved
