### PR TITLE
bugfix:Remove arrow icon from cancel button in Create Questionnaire

### LINKED ISSUE #10725: Remove Unnecessary Arrow Near Cancel Button
**Describe the bug**
Arrow is displayed next to the "Cancel" button, which is not needed for cancel button.

**To Reproduce**

1. Go to 'Admin Dashboard'.
2. Click on 'Create New'.
4. Arrow symbol nearer to 'Cancel' button.

Image

**Expected behavior**
The "Cancel" button should not have an arrow next to it.

### PR DESCRIPTION
**Pull request by ashwinpraveengo**
## Proposed Changes

- Fixes #10725 
- Removed the left arrow icon from cancel button `QuestionnaireEditor.tsx`

@ohcnetwork/care-fe-code-reviewers

image

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
  - Enhanced the questionnaire interface with translatable text for labels, buttons, and alerts, providing improved multilingual support.
  - Introduced new localization entries for actions like adding questions, conditions, cloning questionnaires, editing forms, previewing, and managing data collection.
- **Bug Fixes**
  - Updated messaging for unavailable questionnaires to improve user clarity.

### CODE REVIEW

File: src/components/Questionnaire/QuestionnaireEditor.tsx
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireEditor.tsx:1]: follow merge checklist and readme; let's add translations to all literal strings in this file as well;

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by Jacobjeevan — DISMISSED** [review]
Clear merge conflict.

**Review by Jacobjeevan — APPROVED** [review]

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 1]
```diff
@@ -965,7 +963,7 @@ export default function QuestionnaireEditor({ id }: QuestionnaireEditorProps) {
                   </div>
 
                   <div>
-                    <Label htmlFor="slug">Slug</Label>
+                    <Label htmlFor="slug">{t("Slug")}</Label>
```
Comment (Jacobjeevan) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]:
```suggestion
                    <Label htmlFor="slug">{t("slug")}</Label>
```

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

File: public/locale/en.json [hunk 2]
```diff
@@ -1170,6 +1182,7 @@
   "footer_body": "Open Healthcare Network is an open-source public utility designed by a multi-disciplinary team of innovators and volunteers. Open Healthcare Network CARE is a Digital Public Good recognised by the United Nations.",
   "forget_password": "Forgot password?",
   "forget_password_instruction": "Enter your username, and if it exists, we will send you a link to reset your password.",
+  "form_preview": "Preview form",
```
Comment (rithviknishad) [inline public/locale/en.json]:
```suggestion
  "preview_form": "Preview form",
```

File: src/components/Questionnaire/QuestionnaireEditor.tsx [hunk 3]
```diff
@@ -1232,11 +1230,11 @@ function QuestionEditor({
...
             <div className="flex gap-2 mt-1">
               <Badge variant="secondary">{type}</Badge>
-              {required && <Badge variant="secondary">Required</Badge>}
-              {repeats && <Badge variant="secondary">Repeatable</Badge>}
+              {required && <Badge variant="secondary">{t("required")}</Badge>}
+              {repeats && <Badge variant="secondary">{t("repeatable")}</Badge>}
               {type === "group" && questions && questions.length > 0 && (
                 <Badge variant="secondary">
-                  {questions.length} sub-questions
+                  {questions.length} {t("sub_questions")}
```
Comment (rithviknishad) [inline src/components/Questionnaire/QuestionnaireEditor.tsx]: use variables in translations to include the length in it. 

this may be incorrectly represented in other languages;

```
t("sub_questions_count", { count: questions.length })
```

**Review by rithviknishad — CHANGES_REQUESTED** [review]

**Review by rithviknishad — APPROVED** [review]
