### PR TITLE
Remove redundant facility selection pop-up for single facility users

### LINKED ISSUE #6518: Pop-up for selection of facility, redundant
**Describe the bug**
When a user has access to only 1 facility, and he/she goes to patient page (https://care.coronasafe.in/patients) and tries to register a new patient by clicking on "+ Add patient details", a pop-up window to select the facility the patient is admitted to appears. Such pop-up window is redundant since the user can anyway only choose the one facility he has access to.

Desirable flow: The pop-up window for user to select facility must only appear for users that have access to more than one facility.

**To Reproduce**

1. Login with the username "test-staff123", pass: Lilo@123
2. Note that the user has access to only 1 facility
3. Click on 'patients' in side nav menu
4. Click on "+ Add patient details"
5. See the pop-up window to select facility and the dropdown has only 1 option.

**Expected behaviour**
The user upon clicking "+ Add patient details" must be taken to the patient registration form, since it is obvious that the patient is being admitted to the only facility that the user has access to.

### PR DESCRIPTION
**Pull request by sriharsh05**
### <samp>🤖 Generated by Copilot at 05d165a</samp>

Added `useQuery` to fetch user permissions and facilities in `ManagePatients.tsx`. Added response type to `getPermittedFacilities` route in `api.tsx`.

## Proposed Changes

- Fixes #6518 ?
- I have removed the unnecessary facility selection pop-up that appeared for users with access to only one facility when attempting to register a new patient. This change streamlines the patient registration process by automatically assigning the single available facility to the new patient.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 05d165a</samp>

*  Add `useQuery` hook and `routes` object to fetch and access API endpoints ([link](https://github.com/coronasafe/care_fe/pull/6535/files?diff=unified&w=0#diff-6a60fce2df893cf91c0457f6445b903c1d6667b6a86fc21c38a9e8fc385c7575R52-R53))
*  Declare `permittedData` variable to store the response from `getPermittedFacilities` endpoint ([link](https://github.com/coronasafe/care_fe/pull/6535/files?diff=unified&w=0#diff-6a60fce2df893cf91c0457f6445b903c1d6667b6a86fc21c38a9e8fc385c7575R482-R483))
*  Modify `onClick` handler for `add-patient-details` button to check user's facility permission and navigate accordingly ([link](https://github.com/coronasafe/care_fe/pull/6535/files?diff=unified&w=0#diff-6a60fce2df893cf91c0457f6445b903c1d6667b6a86fc21c38a9e8fc385c7575L784-R792))
*  Add `TRes` property to `getPermittedFacilities` route definition to specify the expected response type ([link](https://github.com/coronasafe/care_fe/pull/6535/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cR225))

### CODE REVIEW

File: src/Components/Patient/ManagePatients.tsx [hunk 1]
```diff
@@ -477,6 +479,8 @@ export const PatientManager = () => {
     [fetchFacilityBadgeName, fetchLocationBadgeName]
   );
 
+  const { data: permittedData } = useQuery(routes.getPermittedFacilities, {});
```
Comment (rithviknishad) [inline src/Components/Patient/ManagePatients.tsx]: variable name `permittedData` doesn't make sense right?

```suggestion
  const { data: permittedFacilities } = useQuery(routes.getPermittedFacilities, {});
```

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
