### PR TITLE
Fix: Align loading skeleton with user cards layout

### LINKED ISSUE #11183: Loading Skeleton Doesn't Match User Cards
**Describe the bug**
The loading card in the users section does not match the screen cards. Let's update it to align with the actual cards. (Refer the recording)

**To Reproduce**
Steps to reproduce the issue:

1. Go to the users section.
2. Check across different screen sizes.
3. Observe the mismatch.

**Make sure to load the user page on all screen sizes to verify the issue.**

**Expected behavior**
The loading card should match the size, spacing, and layout of the user cards across all screen sizes for a consistent UI.

**Screenshots**
https://github.com/user-attachments/assets/f9e5c341-29f6-423e-bb86-ed75da879f6f

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by siva222003**
## Proposed Changes

- Fixes #11183 
- Adjusted the skeleton structure to align with user card dimensions.
- Ensured consistent spacing and layout across different screen sizes.

[Screencast from 2025-03-10 15-20-35.webm](https://github.com/user-attachments/assets/241e1c33-206b-4bce-b4d0-1870012c69a3)

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA in Mobile Devices
- [ ] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **Style**
  - Enhanced the responsiveness of the loading indicator, ensuring a smoother display on different screen sizes during data fetching.

### CODE REVIEW

**Comment by siva222003** [comment]
@rithviknishad Please review this.

File: src/components/Facility/FacilityUsers.tsx [hunk 1]
```diff
@@ -48,7 +48,7 @@ export default function FacilityUsers(props: { facilityId: string }) {
   if (userListFetching || !userListData) {
     usersList =
       activeTab === "card" ? (
-        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
+        <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4">
```
Comment (abhimanyurajeesh) [inline src/components/Facility/FacilityUsers.tsx:51]: LGTM

Tested!

cc: @amjithtitus09

**Review by abhimanyurajeesh — APPROVED** [review]

**Review by amjithtitus09 — APPROVED** [review]
