### PR TITLE
 fixed username and id not visible on mobile devices in sidebar 

### LINKED ISSUE #11507: Users name is not visible in sidebar of mobile devices
**Describe the bug**

When we open the side navbar from a facility page, on mobile devices, the user's name is not visible

**To Reproduce**

1. Go to the facility page
2. open the nav sidebar
3. See error

**Expected behavior**

- [ ] users name and id should be properly visible on all devices

device name : iPhone 14 pro

**Screenshots**

Image

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by Vikaspal8923**
…sidebar is  collapsed form

## Proposed Changes

- Fixes #11507 
- add  username and id when screen size is of mobile device and sidebar is in collapsed mode
 ( i.e when is mobile is true and open  == false)

screenshot :
image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [X] Request for Peer Reviews
- [X] Completion of QA in Mobile Devices
- [X] Completion of QA in Desktop Devices

## Summary by CodeRabbit

- **New Features**
  - The user avatar is now always displayed in the sidebar, enhancing visibility regardless of the sidebar's state.
  - Additional user information is shown when the sidebar is open or in mobile view, improving clarity and accessibility.

### CODE REVIEW

**Review by abhimanyurajeesh — CHANGES_REQUESTED** [review]
This works but not the ideal fix.

Don't you think there is a better way!?

**Comment by Vikaspal8923** [comment]
@abhimanyurajeesh  i have Avoid Code Duplication . please review it and tell me if something more  need to change

File: src/components/ui/sidebar/nav-user.tsx [hunk 1]
```diff
@@ -65,17 +65,9 @@ export function FacilityNavUser({
...
-                  <Avatar
-                    name={`${user.first_name} ${user.last_name}`}
-                    className="size-8 rounded-lg"
-                    imageUrl={user.read_profile_picture_url}
-                  />
-                </div>
-              )}
             </SidebarMenuButton>
           </DropdownMenuTrigger>
+
```
Comment (rithviknishad) [inline src/components/ui/sidebar/nav-user.tsx]:
```suggestion
```

File: src/components/ui/sidebar/nav-user.tsx [hunk 2]
```diff
@@ -49,13 +49,13 @@ export function FacilityNavUser({
               className="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
               data-cy="user-menu-dropdown"
             >
-              {open && (
+              <Avatar
+                className="h-8 w-8 rounded-lg"
```
Comment (rithviknishad) [inline src/components/ui/sidebar/nav-user.tsx]:
```suggestion
                className="size-8 rounded-lg"
```

**Review by rithviknishad — APPROVED** [review]
