### PR TITLE
Fix: Align facility type tooltip closer to the badge text

### LINKED ISSUE #14358: Misaligned 'Private Hospital' badge on hover
**Describe the bug**
The "Private Hospital" badge in the header is positioned too far to the right, creating excessive gap between the 'Private Hospital' text and the badge

**To Reproduce**

1. Go to Governance, click on the `Facilities`option from the filtering options.
2. Click on `FACILITY WITH PATIENTS`
3. Hover over the 'Private Hospital Text'
4. See the misaligned pop-up

**Expected behavior**
The pop-up should be aligned horizontally closer to the text

**Screenshots**

Image

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 141

**Smartphone (please complete the following information):**

N/A

**Additional context**
N/A

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by atif09**
## Proposed Changes

Fixes #14358 
- adjusted facility type tooltip positioning to appear closer to the badge text by adding `side="right"`, `align="center"`, and `sideOffset={4}` props
- added `inline-block` class to h2 element to constrain tooltip trigger width to text content only
- additional context if needed : 
### BEFORE
image

### AFTER
image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **Style**
  * Facility tooltips are now centered with refined horizontal spacing for clearer, more consistent placement.
  * Facility-type headings use an inline presentation to improve layout consistency and visual alignment.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/components/Facility/FacilityHome.tsx [hunk 1]
```diff
@@ -188,8 +188,13 @@ export const FacilityHome = ({ facilityId }: Props) => {
                       <TooltipComponent
                         content={facilityData?.facility_type}
                         side="right"
+                        align="center"
+                        sideOffset={4}
                       >
-                        <h2 className="text-xs sm:text-sm md:text-base lg:text-base text-white/70">
+                        <h2
+                          className="text-xs sm:text-sm md:text-base lg:text-base text-white/70 inline-block"
+                          data-cy="facility-type-card"
```
Comment (Jacobjeevan) [inline src/components/Facility/FacilityHome.tsx]: data cy isn't needed, do remove.

Comment (atif09) [reply src/components/Facility/FacilityHome.tsx]: Noted, will do it soon 
> data cy isn't needed, do remove.

**Comment by nihal467** [comment]
LGTM

**Review by nihal467 — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
