### PR TITLE
fix: medication dispense as a clickable link in charge items tab

### LINKED ISSUE #15823: Medication Dispense not redirecting to Dispense Order page from Charge Items tab
**Describe the bug**
The resource column in Charge Items tab is not rendering the medication dispense as a clickable link.

**To Reproduce**

1. Go to 'Billing' -> 'Accounts'
2. Go to an account
3. Click on 'Charge Items' tab
4. Click 'Medication Dispense' in 'Resources' column.
5. See error

**Expected behavior**
Medication Dispense should be rendered as a clickable link

**Screenshots**

Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

### PR DESCRIPTION
**Pull request by StephZam**
## Proposed Changes

Fixes #15823

image

Tagging: @ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate the bug or test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is placed in I18n files.
- [ ] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [ ] Request peer reviews.
- [ ] Complete QA on mobile devices.
- [ ] Complete QA on desktop devices.
- [ ] Add or update Playwright tests for related changes

## Summary by CodeRabbit

* **New Features**
  * Added a medication-dispense redirect allowing direct navigation to medication dispense orders from billing/account.
  * New route enables direct access via medication-dispense links.
  * Charge items now include links that route users into the medication-dispense redirect flow for faster navigation.

* **Bug Fixes**
  * Improved error handling in the dispense view to show an error page when dispense order data is missing; loading states retained.

### CODE REVIEW

File: src/pages/Facility/billing/account/components/MedicationDispenseRedirect.tsx [hunk 1]
```diff
@@ -0,0 +1,40 @@
+import query from "@/Utils/request/query";
+import Loading from "@/components/Common/Loading";
+import medicationDispenseApi from "@/types/emr/medicationDispense/medicationDispenseApi";
+import { useQuery } from "@tanstack/react-query";
+import { Redirect } from "raviger";
+
+interface MedicationDispenseRedirectProps {
+  facilityId: string;
+  service_resource_id: string;
```
Comment (Jacobjeevan) [inline src/pages/Facility/billing/account/components/MedicationDispenseRedirect.tsx]: Not our convention 👍 we follow camel case, same in other file.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]

File: src/pages/Facility/billing/account/components/MedicationDispenseRedirect.tsx [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+  const locationId = data?.location?.id;
+  const dispenseOrderId = data?.order?.id;
+  if (facilityId && locationId && dispenseOrderId) {
+    return (
+      <Redirect
+        to={`/facility/${facilityId}/locations/${locationId}/medication_dispense/order/${dispenseOrderId}`}
+      />
+    );
+  }
+  return <Loading />;
```
[the remark this answers is not in the document]
Comment (Jacobjeevan) [reply src/pages/Facility/billing/account/components/MedicationDispenseRedirect.tsx]: @StephZam do take a look at all coderabbit comments btw and see if they are worth implementing. In this case, doesn't make sense to return Loading, no? We can return `<></>` empty component.

File: src/pages/Facility/billing/account/components/MedicationDispenseRedirect.tsx [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+import { Redirect } from "raviger";
+
+interface MedicationDispenseRedirectProps {
+  facilityId: string;
+  serviceResourceId: string;
+}
+
+const MedicationDispenseRedirect = ({
+  facilityId,
+  serviceResourceId,
```
Comment (bodhish) [inline src/pages/Facility/billing/account/components/MedicationDispenseRedirect.tsx]: We should be calling it medicationDispenseId right?

File: src/pages/Facility/billing/account/components/MedicationDispenseRedirect.tsx [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+    }),
+    enabled: !!serviceResourceId,
+  });
+
+  if (isLoading) {
+    return <Loading />;
+  }
+
+  const locationId = data?.location?.id;
+  const dispenseOrderId = data?.order?.id;
```
Comment (bodhish) [inline src/pages/Facility/billing/account/components/MedicationDispenseRedirect.tsx:28]: What happens if a random id is passed? I don't see a not found page implemented.

**Review by bodhish — DISMISSED** [review]

File: src/pages/Facility/billing/account/components/MedicationDispenseRedirect.tsx [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+  facilityId,
+  medicationDispenseId,
+}: MedicationDispenseRedirectProps) => {
+  const { data, isLoading } = useQuery({
+    queryKey: ["medication_dispense", medicationDispenseId],
+    queryFn: query(medicationDispenseApi.get, {
+      pathParams: { id: medicationDispenseId },
+    }),
+    enabled: !!medicationDispenseId,
+  });
```
Comment (NikhilA8606) [inline src/pages/Facility/billing/account/components/MedicationDispenseRedirect.tsx]: medicationDispenseId is always present, so the query will always try to fetch

**Review by NikhilA8606 — CHANGES_REQUESTED** [review]

File: src/Routers/routes/FacilityRoutes.tsx [hunk 6]
```diff
@@ -190,6 +191,15 @@ const FacilityRoutes: AppRoutes = {
   "/facility/:facilityId/template/builder/:slug": ({ facilityId, slug }) => (
     <TemplateBuilder facilityId={facilityId} slug={slug} />
   ),
+  "/facility/:facilityId/medication_dispense/redirect/:medicationDispenseId": ({
+    facilityId,
+    medicationDispenseId,
+  }) => (
+    <MedicationDispenseRedirect
+      facilityId={facilityId}
+      medicationDispenseId={medicationDispenseId}
```
Comment (NikhilA8606) [inline src/Routers/routes/FacilityRoutes.tsx:200]:
```suggestion
      medicationDispenseId
```

**Review by NikhilA8606 — DISMISSED** [review]

File: src/pages/Facility/services/pharmacy/DispensesView.tsx [hunk 7]
```diff
@@ -83,8 +88,8 @@ export default function DispensesView({ facilityId, dispenseOrderId }: Props) {
     return <TableSkeleton count={5} />;
   }
 
-  if (!dispenseOrder) {
-    return null;
+  if (isError || !dispenseOrder) {
+    return <ErrorPage />;
```
Comment (Jacobjeevan) [inline src/pages/Facility/services/pharmacy/DispensesView.tsx:88]: Don't need isError, we can display Error Page with just dispenseOrder check.

File: src/pages/Facility/billing/account/components/MedicationDispenseRedirect.tsx [hunk 8]
```diff
@@ -0,0 +1,38 @@
...
+  const locationId = data?.location?.id;
+  const dispenseOrderId = data?.order?.id;
+  if (facilityId && locationId && dispenseOrderId) {
+    return (
+      <Redirect
+        to={`/facility/${facilityId}/locations/${locationId}/medication_dispense/order/${dispenseOrderId}`}
+      />
+    );
+  }
+  return <></>;
```
Comment (Jacobjeevan) [inline src/pages/Facility/billing/account/components/MedicationDispenseRedirect.tsx]: Let's add ErrorPage here instead.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
Minor changes, let's get this merged soon.

**Review by Jacobjeevan — APPROVED** [review]

**Review by nihal467 — APPROVED** [review]
