### PR TITLE
fixed word wrapping in patient page tabs

### LINKED ISSUE #2562: Patient details tabs are wrapping
image

### PR DESCRIPTION
**Pull request by skks1212**
image
fixes word wrap problem for page tabs, now they are in a single line

closes #2562

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

File: src/Components/Facility/ConsultationDetails.tsx [hunk 1]
```diff
@@ -162,7 +162,7 @@ export const ConsultationDetails = (props: any) => {
   }
 
   const tabButtonClasses = (selected: boolean) =>
-    `capitalize min-w-max-content cursor-pointer border-transparent text-gray-700 hover:text-gray-700 hover:border-gray-300 font-bold ${
+    `capitalize min-w-max-content cursor-pointer border-transparent text-gray-700 hover:text-gray-700 hover:border-gray-300 font-bold whitespace-nowrap ${
       selected === true ? "border-primary-500 text-primary-600 border-b-2" : ""
     }`;
```
Comment (khavinshankar) [inline src/Components/Facility/ConsultationDetails.tsx:167]: can you please refactor this using clsx
```js
className={clsx(
"capitalize min-w-max-content cursor-pointer border-transparent text-gray-700 hover:text-gray-700 hover:border-gray-300 font-bold whitespace-nowrap", 
selected && "border-primary-500 text-primary-600 border-b-2"
)}
```
