### PR TITLE
Fix: UI changes in shifting and resources pages

### LINKED ISSUE #9381: Minor Changes in Shifitng and Resource Page
Image

Image

In List and Board  viewof Shifiting and Resource having difference in search bar length and size of button . The space from the top was different in both pages.
 I think i would put some better and consistent spacing and Change of alingment accordingly

### PR DESCRIPTION
**Pull request by SathishAdithiyaaSV**
## Proposed Changes

- Fixes #9381
- Adjusted the height of the "List View" button to match the height of the "Advanced Filters" button on both the shifting and resources pages.
- Ensured consistent alignment of the top section in both list view and block view across the shifting and resources pages.

## Video of Solution:
<video src="https://github.com/user-attachments/assets/6b28351d-31dd-4967-992e-f96b81fda62b" controls></video>

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `PageTitle` component for improved layout and organization.
	- Added an `ExportButton` for downloading resource requests in CSV format.
  
- **Improvements**
	- Enhanced styling for buttons and components for better visibility and usability.
	- Improved alignment and spacing of search input and buttons using a flexbox structure.

- **Bug Fixes**
	- Preserved existing functionality for data fetching and rendering across components.

### CODE REVIEW

File: src/components/ui/button.tsx [hunk 1]
```diff
@@ -30,6 +30,7 @@ const buttonVariants = cva(
         xs: "h-6 rounded-md px-2 text-xs",
         sm: "h-8 rounded-md px-3 text-xs",
         lg: "h-10 rounded-md px-8",
+        xl: "h-10.8 px-4 py-2",
```
Comment (bodhish) [inline src/components/ui/button.tsx]: Lets nor extend shadcn buttons

File: src/components/Shifting/ShiftingBoard.tsx [hunk 2]
```diff
@@ -109,7 +109,7 @@ export default function BoardView() {
             value={qParams.patient_name}
             onChange={(e) => updateQuery({ [e.name]: e.value })}
             placeholder={t("search_patient")}
-            className="w-full md:w-60"
+            className="w-full md:w-60 mb-1"
```
Comment (bodhish) [inline src/components/Shifting/ShiftingBoard.tsx]: lets not use margin bottom;

**Review by bodhish — DISMISSED** [review]

File: src/components/ui/button.tsx (hunk 1 above)
Comment (SathishAdithiyaaSV) [reply src/components/ui/button.tsx]: I have now removed the "xl" size and have directly added the necessary height and padding in the className of the respective buttons.

File: src/components/Shifting/ShiftingBoard.tsx (hunk 2 above)
Comment (SathishAdithiyaaSV) [reply src/components/Shifting/ShiftingBoard.tsx]: I have now removed the "mb-1" for the search bar

**Comment by SathishAdithiyaaSV** [comment]
@bodhish I have now made changes as per your request

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]

**Review by Jacobjeevan — APPROVED** [review]
