### PR TITLE
Fix (Sidebar): made the sidebar collapse on clicking active links

### LINKED ISSUE #4372: MobileSidebar doesn't collapse on clicking the active tab
**Describe the bug**
Clicking the active/current tab in the mobile sidebar does not collapse the sidebar

**To Reproduce**

1. Open http://care.coronasafe.in/facility in mobile view
2. Open the sidebar
3. Click on the Facility tab

**Expected behavior**
The sidebar should collapse even when the active tab is clicked

https://user-images.githubusercontent.com/57593654/208491683-917a7177-4f69-41dc-9dad-e49bbe4ac893.mp4

### PR DESCRIPTION
**Pull request by naman114**
## Proposed Changes

- Fixes #4372
- Made the mobile sidebar collapse on clicking the active/current tab

https://user-images.githubusercontent.com/57593654/208735156-5f1aa605-68b3-41c1-b049-525348f7685b.mp4

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

File: src/Components/Common/Sidebar/Sidebar.tsx [hunk 1]
```diff
@@ -101,7 +104,7 @@ const StatelessSidebar = ({
     } else {
       indicatorRef.current.style.display = "none";
     }
-  }, [activeLink]);
+  }, [activeLink, lastIndicatorPosition]);
```
Comment (khavinshankar) [inline src/Components/Common/Sidebar/Sidebar.tsx]: updating `lastIndicatorPosition` and having it in deps array might cause infinite loop

**Review by khavinshankar — CHANGES_REQUESTED** [review]

**Comment by naman114** [comment]
@khavinshankar I have removed the dependency from the useEffect hook

**Comment by khavinshankar** [comment]
@nihal467 can you retest this pr again, changes have been made

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
