### PR TITLE
admitted field patient consultation

### LINKED ISSUE #1289: Admission fields patient consultation
**Describe the bug**
When `Decision after consultation` field is set from `Admitted` to any other value, `admitted` is not set to `No` automatically.

### PR DESCRIPTION
**Pull request by divyagar**
Closes #1289 

When `decision after consultation` is set to a value other than `Admitted`, `admitted` checkbox will be set to `No` automatically.

### CODE REVIEW

**Review by arpancodes — APPROVED** [review]

File: src/Components/Facility/ConsultationForm.tsx [hunk 1]
```diff
@@ -358,6 +358,8 @@ export const ConsultationForm = (props: any) => {
     if (value === "A") {
       form.admitted = "true";
     }
+    else
+      form.admitted = "false"
```
Comment (smartclash) [inline src/Components/Facility/ConsultationForm.tsx]:
```suggestion
    } else {
      form.admitted = "false";
    }
```

**Review by smartclash — CHANGES_REQUESTED** [review]
